### ISSUE TITLE
When measuring 2 empty functions using deno bench, first function is 8 times faster than second.

### ISSUE THREAD

**Issue by Lesiuk** [denoland/deno#17117] opened 2022-12-18 21:27 UTC
```javascript
Deno.bench(function a() {

});

Deno.bench(function b() {
});
```

```
xxx@xxx xxx % deno bench
Check file:///Users/xxx/WebstormProjects/radash/main_bench.ts
cpu: Apple M1 Pro
runtime: deno 1.29.1 (aarch64-apple-darwin)

file:///Users/xxx/WebstormProjects/xxx/main_bench.ts
benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
a          504.73 ps/iter   (458.3 ps … 10.54 ns)    500 ps  654.2 ps   1.22 ns
b             4.2 ns/iter    (4.08 ns … 16.21 ns)   4.23 ns   4.99 ns   7.39 ns
```

After adding the same code into a and b.

```javascript
import { draw } from 'npm:radash';

Deno.bench(function a() {
    draw(['test', '123', 'fff', 'ggg']);
});

Deno.bench(function b() {
    draw(['test', '123', 'fff', 'ggg']);
});
```

```
xxx@xxx xxx % deno bench
Check file:///Users/xxx/WebstormProjects/xxx/main_bench.ts
cpu: Apple M1 Pro
runtime: deno 1.29.1 (aarch64-apple-darwin)

file:///Users/xxx/WebstormProjects/xxx/main_bench.ts
benchmark      time (avg)             (min … max)       p75       p99      p995
------------------------------------------------- -----------------------------
a            7.56 ns/iter     (6.8 ns … 92.49 ns)   7.48 ns  14.83 ns  16.84 ns
b           27.21 ns/iter    (24.8 ns … 64.18 ns)  27.06 ns  42.39 ns  44.32 ns
```

**Comment by ayame113** [comment] 2022-12-19 00:46
This looks like it's related to #15277.

**Comment by Lesiuk** [comment] 2022-12-19 09:03
Maybe we needed more warm up for those functions.

**Comment by dsherret** [comment] 2022-12-19 15:08
Duplicate of #15277.

**Closed by dsherret** 2022-12-19 15:08 UTC
