### ISSUE TITLE
Deno linking to missing openssl version as of 0.28.0?

### ISSUE THREAD

**Issue by alexjeffburke** [denoland/deno#3577] opened 2020-01-02 18:12 UTC
Hi,

We've just had an Unexpected build fail on Travis (https://travis-ci.org/unexpectedjs/unexpected/jobs/631967085), which currently defaults to Xenial, that says deno was unable to load openssl as a shared library.

I'm not 100% certain but I seem to remember that deno was intended to be a static linked binary, so it might be this runtime dependency is not intended hence reporting just in case.

Thanks, Alex J Burke.

**Comment by bartlomieju** [comment] 2020-01-03 09:32
That's caused by recent upgrade to reqwest: https://github.com/seanmonstar/reqwest#requirements

I'll see if OpenSSL can be completely omitted.

**Comment by bartlomieju** [comment] 2020-01-03 13:16
@alexjeffburke this should be now fixed and it will be included in next release. Sorry it slipped through, we were landing quite a few big refactors!

**Closed** 2020-01-03 13:15 UTC
Labels: build

**Comment by ry** [comment] 2020-01-03 15:46
Thanks for the fast fix @bartlomieju.

I've cut a new release because of this issue: https://github.com/denoland/deno/releases/tag/v0.28.1

**Comment by alexjeffburke** [comment] 2020-01-03 15:55
@bartlomieju no probs and @ry thanks for the release :) Can confirm all is well again: https://travis-ci.org/unexpectedjs/unexpected/jobs/632334827
