### ISSUE TITLE
Coverage Lcov Output Wrong?

### ISSUE THREAD

**Issue by ebebbington** [denoland/deno#12126] opened 2021-09-17 19:01 UTC
Wonder if i've found a possible bug with coverage, where the standard coverage output is correct, but maybe not the lcov file?
lemme paste some code and links
mod.ts is clearly being covered: https://github.com/ebebbington/crumpets/runs/3624986294#step:4:76

but in the codecov results, only the test deps are being shown: https://app.codecov.io/gh/ebebbington/crumpets

this is the gh workflow i use: https://github.com/ebebbington/crumpets/blob/main/.github/workflows/master.yml#L25

**Comment by bartlomieju** [comment] 2022-01-12 11:45
@ebebbington any chance you could try again with latest canary? I landed https://github.com/denoland/deno/pull/13334 which should resolve most of the issues with wrong output.

**Comment by ebebbington** [comment] 2022-01-12 14:22
@bartlomieju Thanks, will try as soon as i have the spare time

**Comment by bartlomieju** [comment] 2022-01-18 01:58
I'm going to tentatively close this issue. Please let me know if the issue still can be reproduced.

**Comment by jespertheend** [comment] 2022-01-20 21:21
I'm getting weird output in `1.18.0`. If I place empty lines at the top of the file the coverage seems to shift downwards for every line I place.
I'll try to make a reduced test case.

**Comment by jespertheend** [comment] 2022-01-20 22:17
I think it's related to cache somehow. The moment I move the file with incorrect coverage to another location the issue gets fixed.

**Comment by dsherret** [comment] 2022-01-20 22:26
@jespertheend I believe that would be fixed by #13303. The emit cache has the potential to get out of sync at the moment.

**Comment by jespertheend** [comment] 2022-01-20 22:29
Ah yes that would be it I think. Thanks! If I remove caches/gen the issue is fixed. There's a .js and .js.meta file in there with old content of my script.

**Comment by jespertheend** [comment] 2022-01-20 22:36
This is probably useless at this point but I put effort in it so just in case: [denocoverage.zip](https://github.com/denoland/deno/files/7908912/denocoverage.zip)
Run with `./runtest.js` and then view `cov/html/denocoverage/foobar.js.gcov.html`, though you'll need to place the content of `placeInCache` in your cache in order to trigger the issue.

**Comment by jespertheend** [comment] 2022-01-20 23:21
I checked out the PR and I can confirm this indeed fixes my issue.

**Comment by jespertheend** [comment] 2022-02-27 14:16
Any updates on this? I keep having to downgrade to deno 1.17.3 in order to get meaningful coverage reports.

**Comment by bartlomieju** [comment] 2022-02-27 14:18
@jespertheend unfortunately not, I haven't got time to look into this problem yet. I can provide some hints on what might be the problem, but I don't expect to be look into this for a few more weeks.

**Comment by jespertheend** [comment] 2022-02-27 14:24
@bartlomieju alright thanks for the info, I can wait a little longer :)
fwiw, I was still able to reproduce this in #13462 which I think will have to be merged before this can be fixed anyway.

**Comment by bartlomieju** [comment] 2022-02-27 14:30
> @bartlomieju alright thanks for the info, I can wait a little longer :) fwiw, I was still able to reproduce this in #13462 which I think will have to be merged before this can be fixed anyway.

That suggest that the problem lies in either coverage collection (I doubt it, V8 should collect that data) or in "post-processing" step that merges the coverage data and outputs it (more likely).

**Comment by jespertheend** [comment] 2022-02-27 18:07
All I know is that the formatting of the files in the deno cache folder does not match the formatting of my source files, especially around empty lines, this seems to match the behaviour around coverage. It's as if coverage is not using the source maps from the cache.

**Comment by bartlomieju** [comment] 2022-03-01 23:45
> Strangely enough, the issue still occurs when adding --no-check to the deno test command.

That's a good data point - the emitted files are different depending if `--no-check` is present or not (a long standing issue that we want to address is to consolidate emitted files to always come from SWC, instead of TSC when type-checking and SWC if no-check). 

@jespertheend are you able to boil down the reproduction to a single file that exercises the problem?

**Comment by jespertheend** [comment] 2022-03-02 07:55
> are you able to boil down the reproduction to a single file that exercises the problem?

Sure, I’ll try this later today.

**Comment by jespertheend** [comment] 2022-03-02 19:36
Good thing I didn't delete the test case [from last time](https://github.com/denoland/deno/issues/12126#issuecomment-1017988006), because all I had to do was add a `deno.json` with `"checkJs": true` to it: [denocoverage.zip](https://github.com/denoland/deno/files/8172386/denocoverage.zip)

Run `./runtest.js` and open the generated `cov/html/denocoverage/foobar.js.gcov.html` to view the coverage. (lcov needs to be installed)

If you remove all empty new lines from `foobar.js`, the coverage is correct. But otherwise it seems that every empty line shifts the coverage downwards.

**Comment by jespertheend** [comment] 2022-09-24 21:11
This seems to have been fixed somewhere between Deno 1.23.4 and 1.24.0
Not sure about the initial report, but I can confirm that at least the `"checkJs": true` option no longer messes up the coverage. I can't reproduce it using the reduced test case anymore either.

**Closed** 2024-09-18 10:05 UTC
Labels: bug, needs investigation, testing
