### ISSUE TITLE
bug: Connection refused (os error 111)

### ISSUE THREAD

**Issue by alexanderGalushka** [denoland/deno#7686] opened 2020-09-25 23:25 UTC
I run deno in the docker container in the k8s pod for as a REST API service. Every N seconds this deno service sends a POST request with metrics data over to another service in k8s, [prometheus pushgateway](https://github.com/prometheus/pushgateway)

here is the code snippet of how the POST request is being made with fetch:
```ts
// function to push metrics to prometheus "pushgateway"
export async function pushMetrics(
  id: string,
  metrics: string,
) {
  const pgURL = getPushgatewayHostName(pushgatewayJobName, id);
  try {
    const cleanedUpFileContent = unescape(encodeURIComponent(metrics));
    const out = new TextEncoder().encode(cleanedUpFileContent);  
    const response = await fetch(
      pgURL,
      {
        method: "POST",
        body: out,
      },
    );
    if (response.status != 202 && response.status != 200) {
      log.error(`failed to POST to pushgateway URL ${pgURL}, status ${response.status}`);
    }
  } catch (e) {
    log.error(`unexpected error: failed to POST to pushgateway URL ${pgURL}, ${e}`);
  }
}

function getPushgatewayHostName(pushgatewayJobName: string, id: string): string {
  const pushgatewayURI = `metrics/job/${pushgatewayJobName}/instance/${id}`;
  if (ENV == undefined || ENV == "") {
    return `http://pushgateway:9091/${pushgatewayURI}`;
  }
  return `http://${ENV}-${basePushgatewayK8sServiceHost}/${pushgatewayURI}`; 
}
```

permissions for the network calls are wide open:

`CMD ["deno", "run", "--cached-only", "--unstable", **"--allow-net"**, "--allow-read=./workers", "--allow-env", "--v8-flags=--disallow-code-generation-from-strings", "main.ts"]`

request comes through OK if I run it outside of k8s (not using k8s dns service host name e.g. `pgURL=http://pushgateway.mynamespace.svc.cluster.local:9091`): bring up 2 docker containers attached to the same network, so the deno service POST to `http://pushgateway:9091`, pushgateway is the name of the second container deno service is POSTing to

if I run it in the k8s I get the following error:

`unexpected error: failed to POST to pushgateway URL http://myenv-pushgateway.mynamespace.svc.cluster.local:9091/metrics/job/myjob/instance/1234567890, Http: error sending request to url (http://myenv-pushgateway.mynamespace.svc.cluster.local:9091/metrics/job/myjob/instance/1234567890): error trying to connect: tcp connect error: Connection refused (os error 111)`

looks like a Rust error message:

`
 error trying to connect: tcp connect error: Connection refused (os error 111)
`

I can exec into the deno container in k8s and curl pushgateway, so it's not related to k8s network policies

not sure if these 2 issues are related:
https://github.com/denoland/deno/issues/7660
https://github.com/denoland/deno/issues/6751

using:
* latest deno v1.4.2
* k8s cluster v1.18.6

@bartlomieju @kitsonk @hayd can you please take a look

**Comment by kitsonk** [comment] 2020-09-26 00:05
You don't need to `@` people to have a potential issue looked at.

**Comment by hayd** [comment] 2020-09-26 05:43
This certainly reads like #6751.

**Comment by alexanderGalushka** [comment] 2020-10-01 22:58
> You don't need to `@` people to have a potential issue looked at.

true

**Comment by alexanderGalushka** [comment] 2020-10-13 18:24
has anyone looked at this?

**Comment by puneetk** [comment] 2020-10-13 18:26
*bump*

**Comment by Merulast** [comment] 2022-11-02 17:33
Same thing appeared again on my setup. Suddenly with the recent update of the docker image (denoland/latest) Iam not able to connect to my mariadb nodes anymore. If lucky I get the os error 111, if not the entire thread just get hung.

Also reproductable with the smalest possible mysql connection sample excluding all higher level libs.

**Comment by itsahsiao** [comment] 2022-11-03 18:17
Same here @Merulast 😞  

We're also having issues with our application on production connecting to our supabase postgres db. No issues when running the application locally or when connecting to the database directly.

**Comment by bartlomieju** [comment] 2022-11-03 18:40
@littledivy please take a look

**Comment by itsahsiao** [comment] 2022-11-03 19:48
We resolved it by updating our deno postgres driver to the latest version. We were on `postgres@v0.16.0` and changing to `postgres@v0.17.0` seemed to fix it for some reason.

**Comment by hamanuha** [comment] 2023-01-11 22:27
I am having the same issue. I can not connect to the local postgres database (using supabase).

**Comment by hamanuha** [comment] 2023-01-12 10:48
> I’m having the same issue. I can’t connect to the local postgres database (using supabase).

It works when using `172.17.0.1` instead of `localhost`

**Comment by cohlar** [comment] 2023-01-25 10:33
I have the same issue. Thanks for sharing @hamanuha , replacing `localhost` by `172.17.0.1` works for me as well.

**Comment by Peter-Kang** [comment] 2023-04-27 03:37
> > I’m having the same issue. I can’t connect to the local postgres database (using supabase).
> 
> It works when using `172.17.0.1` instead of `localhost`

I had the same issue connecting from deno to mongodb over docker. This solved my issue. Thank you so much for shareing!

**Comment by topperspal** [comment] 2023-12-19 16:34
> > I’m having the same issue. I can’t connect to the local postgres database (using supabase).
> 
> It works when using `172.17.0.1` instead of `localhost`

Wow this just worked! 

I am using supabase and deno edge function. Could you explain how this works?

**Comment by anil-zenollect** [comment] 2024-07-01 06:29
it's Docker's gateway for its bridge network. 

try running command `docker network inspect bridge`

![image](https://github.com/denoland/deno/assets/172481072/87b7b2bc-5481-41dc-b707-2620547afe7b)

**Comment by SaiHarshaVardhan-ez** [comment] 2024-08-28 01:50
> I have the same issue. Thanks for sharing @hamanuha , replacing `localhost` by `172.17.0.1` works for me as well.

-- hey ! i was getting the same error while working with supabase -- i have tried to change it to 172.17.0.1 it did not work it is giving connection timed out error can you help me with this

**Comment by lucacasonato** [comment] 2024-09-16 12:33
This is likely related to `localhost` resolving to an IPv6 address, but the port not actually listening on IPv6. This would be fixed by us implementing Happy Eyeballs: https://github.com/denoland/deno/issues/25661. I'll close this in favor of that.

**Closed by lucacasonato** 2024-09-16 12:33 UTC
Labels: bug, ext/fetch

**Comment by aj-ats** [comment] 2025-01-07 19:38
this was helpfull and worked thanks
