### ISSUE TITLE
Implement transferable ArrayBuffer for use in postMessage

### ISSUE THREAD

**Issue by johnspurlock** [denoland/deno#11583] opened 2021-08-04 21:01 UTC
In browsers, sending large array buffers over postMessage, for example to a [Worker](https://developer.mozilla.org/en-US/docs/Web/API/Web_Workers_API), can be optimized by indicating that an ArrayBuffer (which is [Transferable](https://developer.mozilla.org/en-US/docs/Web/API/Transferable)) should transfer ownership, instead of being cloned. See the [transfer parameter](https://developer.mozilla.org/en-US/docs/Web/API/Worker/postMessage#parameters) to postMessage on MDN.

This does not appear to be working in Deno 1.12.2: `const tmp = new Uint8Array(0); w.postMessage({ tmp }, [ tmp.buffer ]);` throws `DOMException: Value not transferable` - yet `const tmp = new Uint8Array(0); w.postMessage({ tmp }, [ ]);` succeeds.

There is a related issue #8341, but it's far more broad - this issue is requesting only ArrayBuffer support, which is part of the spec all browsers implement.

**Comment by kitsonk** [comment] 2021-08-04 22:10
Duplicate of #8341

**Closed by kitsonk** 2021-08-04 22:10 UTC
Labels: duplicate

**Comment by lucacasonato** [comment] 2021-08-05 00:25
I don't think it is a duplicate of #8341. This issue is specific to ArrayBuffer, while the #8341 talks about general resources (Deno.Conn for example). I am going to work on this once I am back from vacation. It is definitely a duplicate of https://github.com/denoland/deno/issues/11303 though :-)
