### ISSUE TITLE
deno bundle bugs?

### ISSUE THREAD

**Issue by zalelion** [denoland/deno#6516] opened 2020-06-27 09:07 UTC
deno version 1.1.0

### index.tsx

```tsx
//@deno-types="https://deno.land/x/types/react/v16.13.1/react.d.ts"
import React from "https://cdn.pika.dev/react@16.13.1";
console.log(React);
const App = () => {
  return <div>Hello deno</div>;
};

console.log(<App />);

```
> use `deno run index.tsx`
output:
```
{
  $$typeof: Symbol(react.element),
  type: [Function: App],
  key: null,
  ref: null,
  props: {},
  _owner: null
}
```
> no problem, but use `deno bundle index.tsx index.js`, then 
### browser to index.html
```html
<body>
    <script src="index.js"></script>
</body>
```

![image](https://user-images.githubusercontent.com/8503065/85918814-7a9ef900-b898-11ea-82ab-616ba38624f6.png)

**Comment by zalelion** [comment] 2020-06-27 09:09
### bundle index.js
```js
// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

// This is a specialised implementation of a System module loader.

"use strict";

// @ts-nocheck
/* eslint-disable */
let System, __instantiateAsync, __instantiate;

(() => {
  const r = new Map();

  System = {
    register(id, d, f) {
      r.set(id, { d, f, exp: {} });
    },
  };

  async function dI(mid, src) {
    let id = mid.replace(/\.\w+$/i, "");
    if (id.includes("./")) {
      const [o, ...ia] = id.split("/").reverse(),
        [, ...sa] = src.split("/").reverse(),
        oa = [o];
      let s = 0,
        i;
      while ((i = ia.shift())) {
        if (i === "..") s++;
        else if (i === ".") break;
        else oa.push(i);
      }
      if (s < sa.length) oa.push(...sa.slice(s));
      id = oa.reverse().join("/");
    }
    return r.has(id) ? gExpA(id) : import(mid);
  }

  function gC(id, main) {
    return {
      id,
      import: (m) => dI(m, id),
      meta: { url: id, main },
    };
  }

  function gE(exp) {
    return (id, v) => {
      v = typeof id === "string" ? { [id]: v } : id;
      for (const [id, value] of Object.entries(v)) {
        Object.defineProperty(exp, id, {
          value,
          writable: true,
          enumerable: true,
        });
      }
    };
  }

  function rF(main) {
    for (const [id, m] of r.entries()) {
      const { f, exp } = m;
      const { execute: e, setters: s } = f(gE(exp), gC(id, id === main));
      delete m.f;
      m.e = e;
      m.s = s;
    }
  }

  async function gExpA(id) {
    if (!r.has(id)) return;
    const m = r.get(id);
    if (m.s) {
      const { d, e, s } = m;
      delete m.s;
      delete m.e;
      for (let i = 0; i < s.length; i++) s[i](await gExpA(d[i]));
      const r = e();
      if (r) await r;
    }
    return m.exp;
  }

  function gExp(id) {
    if (!r.has(id)) return;
    const m = r.get(id);
    if (m.s) {
      const { d, e, s } = m;
      delete m.s;
      delete m.e;
      for (let i = 0; i < s.length; i++) s[i](gExp(d[i]));
      e();
    }
    return m.exp;
  }

  __instantiateAsync = async (m) => {
    System = __instantiateAsync = __instantiate = undefined;
    rF(m);
    return gExpA(m);
  };

  __instantiate = (m) => {
    System = __instantiateAsync = __instantiate = undefined;
    rF(m);
    return gExp(m);
  };
})();

System.register("index", ["https://cdn.pika.dev/react@16.13.1"], function (exports_1, context_1) {
    "use strict";
    var react_16_13_1_1, App;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (react_16_13_1_1_1) {
                react_16_13_1_1 = react_16_13_1_1_1;
            }
        ],
        execute: function () {
            console.log(react_16_13_1_1.default);
            App = () => {
                return react_16_13_1_1.default.createElement("div", null, "Hello deno");
            };
            console.log(react_16_13_1_1.default.createElement(App, null));
        }
    };
});

__instantiate("index");

```

**Comment by wongjiahau** [comment] 2020-06-27 12:34
Have you tried changing:
```ts
import React from "https://cdn.pika.dev/react@16.13.1";
```
to
```ts
import * as React from "https://cdn.pika.dev/react@16.13.1";
```
?

**Comment by zalelion** [comment] 2020-06-27 13:17
@waldyrious 
same

**Comment by zalelion** [comment] 2020-06-27 13:20
### index.js
```js
// Copyright 2018-2020 the Deno authors. All rights reserved. MIT license.

// This is a specialised implementation of a System module loader.

"use strict";

// @ts-nocheck
/* eslint-disable */
let System, __instantiateAsync, __instantiate;

(() => {
  const r = new Map();

  System = {
    register(id, d, f) {
      r.set(id, { d, f, exp: {} });
    },
  };

  async function dI(mid, src) {
    let id = mid.replace(/\.\w+$/i, "");
    if (id.includes("./")) {
      const [o, ...ia] = id.split("/").reverse(),
        [, ...sa] = src.split("/").reverse(),
        oa = [o];
      let s = 0,
        i;
      while ((i = ia.shift())) {
        if (i === "..") s++;
        else if (i === ".") break;
        else oa.push(i);
      }
      if (s < sa.length) oa.push(...sa.slice(s));
      id = oa.reverse().join("/");
    }
    return r.has(id) ? gExpA(id) : import(mid);
  }

  function gC(id, main) {
    return {
      id,
      import: (m) => dI(m, id),
      meta: { url: id, main },
    };
  }

  function gE(exp) {
    return (id, v) => {
      v = typeof id === "string" ? { [id]: v } : id;
      for (const [id, value] of Object.entries(v)) {
        Object.defineProperty(exp, id, {
          value,
          writable: true,
          enumerable: true,
        });
      }
    };
  }

  function rF(main) {
    for (const [id, m] of r.entries()) {
      const { f, exp } = m;
      const { execute: e, setters: s } = f(gE(exp), gC(id, id === main));
      delete m.f;
      m.e = e;
      m.s = s;
    }
  }

  async function gExpA(id) {
    if (!r.has(id)) return;
    const m = r.get(id);
    if (m.s) {
      const { d, e, s } = m;
      delete m.s;
      delete m.e;
      for (let i = 0; i < s.length; i++) s[i](await gExpA(d[i]));
      const r = e();
      if (r) await r;
    }
    return m.exp;
  }

  function gExp(id) {
    if (!r.has(id)) return;
    const m = r.get(id);
    if (m.s) {
      const { d, e, s } = m;
      delete m.s;
      delete m.e;
      for (let i = 0; i < s.length; i++) s[i](gExp(d[i]));
      e();
    }
    return m.exp;
  }

  __instantiateAsync = async (m) => {
    System = __instantiateAsync = __instantiate = undefined;
    rF(m);
    return gExpA(m);
  };

  __instantiate = (m) => {
    System = __instantiateAsync = __instantiate = undefined;
    rF(m);
    return gExp(m);
  };
})();

System.register("index", ["https://cdn.pika.dev/react@16.13.1"], function (exports_1, context_1) {
    "use strict";
    var React, App;
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [
            function (React_1) {
                React = React_1;
            }
        ],
        execute: function () {
            console.log(React);
            App = () => {
                return React.createElement("div", null, "Hello deno");
            };
            console.log(React.createElement(App, null));
        }
    };
});

__instantiate("index");

```

![image](https://user-images.githubusercontent.com/8503065/85923225-ec3c6e80-b8bb-11ea-9e14-9b606ace61b2.png)

**Comment by jsejcksn** [comment] 2020-06-28 13:19
`deno bundle` is for running code in Deno. It also does not bundle remote imports.

In order to run your compiled TypeScript code in the browser, you're going to need a compiler for that purpose (like `tsc` with an appropriate `tsconfig.json` or `webpack`, etc.)

**Comment by kitsonk** [comment] 2020-06-29 03:15
Duplicate of #4539 (explained below)

> `deno bundle` is for running code in Deno.

It is its primary purpose.  Some bundles _can_ work under browsers, but it is a happy side effect, not intent.

> It also does not bundle remote imports.

Incorrect. It does in a lot of cases...

In this case it is a duplicate of #4539 which is not handled properly at the moment. (In this case Pika is providing an `X-TypeScript-Types` headers, but it is functionally equivalent to the triple slash directive.

> In order to run your compiled TypeScript code in the browser, you're going to need a compiler for that purpose (like `tsc` with an appropriate `tsconfig.json` or `webpack`, etc.)

Yes, you would likely get better results with other tools (`tsc` doesn't do any substantial bundling) but the compiler APIs (`Deno.compile()` and `Deno.bundle()`) are intended for this purpose as well, though they don't do minification or tree-shaking yet, which other tools do do.

**Comment by jsejcksn** [comment] 2020-06-29 03:27
> Incorrect. It does in a lot of cases...
> 
> In this case it is a duplicate of #4539 which is not handled properly at the moment. (In this case Pika is providing an `X-TypeScript-Types` headers, but it is functionally equivalent to the triple slash directive.

@kitsonk Thanks for correcting me. I never want to spread misinformation.

**Closed** 2020-06-29 07:59 UTC
