### ISSUE TITLE
Feature request: Use conventional commit messages. 

### ISSUE THREAD

**Issue by deeptechuz** [denoland/deno#2427] opened 2019-05-30 05:27 UTC
It will be easy to understand for contributors or new coming contributors while looking through the project history.

[Conventional commit messages](https://www.conventionalcommits.org/en/v1.0.0-beta.4/)

**Comment by bartlomieju** [comment] 2019-05-30 08:52
Duplicate of #2075

**Closed** 2019-05-30 12:42 UTC
