### ISSUE TITLE
TTY width/height should be accessible

### ISSUE THREAD

**Issue by Alhadis** [denoland/deno#3718] opened 2020-01-20 09:20 UTC
I might be missing something, but Deno doesn't appear to expose the number of rows and columns of a controlling terminal:

~~~js
// Node
[width, height] = [process.stdout.columns, process.stdout.rows];

// QuickJS
[width, height] = os.ttyGetWinSize(1);

// Deno
[width, height] = ???;
~~~

Also, it'd be nice if we could configure a TTY stream to operate as a "raw" device (so that keystrokes like `^C` could copy-to-clipboard in a terminal-based editing app). For example:

~~~js
export function setRawTTY(fd = 0){
	if(isQuickJS && "object" === typeof os)
		os.ttySetRaw(fd);
	else if(isNode)
		[process.stdin, process.stdout, process.stderr][fd].setRawMode(true);
	else unsupported(setRawTTY, fd);
}
~~~

**Comment by kitsonk** [comment] 2020-01-20 10:55
Duplicate of #3456

**Comment by Alhadis** [comment] 2020-01-20 10:56
Derp. I searched, but nothing came up. Thanks. 😓

**Comment by nayeemrmn** [comment] 2020-01-20 12:22
@Alhadis Can this be closed?

**Closed** 2020-01-20 13:05 UTC
