### ISSUE TITLE
cannot ‘write’ to TLS connection while ‘read’ is pending

### ISSUE THREAD

**Issue by zamfofex** [denoland/deno#9061] opened 2021-01-09 02:05 UTC
Consider:

~~~ JavaScript
let connection = await Deno.connectTls({hostname: "google.com", port: 443})

// No ‘await’.
connection.read(new Uint8Array(2048))

await connection.write(new Uint8Array([0x0D, 0x0A]))
console.log("yo")
~~~

I’d expect the `connection.write(...)` promise to resolve eventually, but instead it does not (and the process blocks without ever logging `"yo"`).

**Comment by zamfofex** [comment] 2021-01-09 02:07
Note: If I replace `await Deno.connectTls({hostname: "google.com", port: 443})` with `await Deno.connect({hostname: "google.com", port: 80})` (i.e. no TLS), it *does* log `"yo"` as expected.

**Comment by starkpsmichael** [comment] 2021-01-09 09:34
Same problem as in #8945 and #9032.

**Comment by lucacasonato** [comment] 2021-01-09 09:36
Closing as a duplicate of #9032

**Closed by lucacasonato** 2021-01-09 09:36 UTC
