### ISSUE TITLE
Request: CLI flag to set language mode

### ISSUE THREAD

**Issue by joehillen** [denoland/deno#5088] opened 2020-05-05 17:05 UTC
I'm trying out deno for scripting (it's been a great experience so far, kudos!).

I'd like to be able to create script files without a `.ts` extension. If I do this, then the following is interpreted as JS and I get a syntax error on the type annotations:

```ts
#!/usr/bin/env -S deno run --allow-run --allow-read --allow-write

// code: language=typescript

function hello(name: string) {
  console.log("Hello,", name);
}

hello(Deno.args[0]);
```

```
$  ./myscript 
error: Uncaught SyntaxError: Unexpected token ':'
function hello(name: string) {
                   ^
    at file:///home/joe/tmp/myscript:5:20
```

I believe the simplest solution would be to add a CLI flag to force script to be interpreted as typescript.

Something like:

```
--language=[javascript, typescript]
```

so in the above script the shebang becomes:

```
#!/usr/bin/env -S deno run --language=typescript --allow-run --allow-read --allow-write
```

**Comment by kitsonk** [comment] 2020-09-09 20:58
I missed this before. I would prefer something like `--media-type` or just `--type` which we make all extensionless local files be assigned the supplied type.

**Comment by joehillen** [comment] 2020-09-09 22:06
@kitsonk In that case, I think `--default-type` would be more clear, since it might not be intuitive that `--type` affects more than one file.

**Comment by d10n** [comment] 2021-03-12 19:54
`deno compile` is definitely useful and has overlapping use case, especially for distribution.

I still think there are valuable use cases for executing deno scripts without requiring a compile, primarily relating to development and local system administration:
* My 10KB script makes a 44MB binary. For one program, maybe not a huge deal, but for many scripts, that can add up quickly, which especially matters in containers/VMs and small/embedded devices. I've had to spend time clearing up disk space just to install Kubernetes multiple times in the past, because Kubernetes has huge executables. Right now, I only have one script, but this size issue may be a deciding factor against writing some deno scripts in the future.
* Frequently-updated scripts will be cumbersome to update; even if compiling is reasonably automated, it is an extra step in the process.
* Single-purpose and infrequently-updated/oneshot scripts may not be worth the extra ceremony to maintain for deno.

In my opinion, it is good to provide options for an appropriate level of convenience, and I think this is an appropriate level of convenience that enables more uses of deno.

**Comment by satyarohith** [comment] 2021-04-20 11:09
We use `--ext` to set the language for `deno fmt`  and `deno eval`; we should probably use the same flag.

**Comment by Thief-K** [comment] 2021-05-06 14:36
Same issue #5623 but was closed. It is very meaningful to me, so i can run most npm lib without append the extension in source code.

**Comment by jiraguha** [comment] 2021-08-31 05:23
Just to add weight on this issue:

I have the same issue, but with a different use-case. I am trying to use the deno as a runner in the kubernetes ecosystem to run pipelines. The tool I use is [argo-workflow] (https://argoproj.github.io/argo-workflows/)... A great project, though! Basically, when you deploy the following manifest

```
apiVersion: argoproj.io/v1alpha1
kind: Workflow
metadata:
  name: deno
  namespace: "argo"
spec:
  entrypoint: deno
  templates:
  - name: deno
    script:
      image: denoland/deno:1.13.2
      command: ["deno","run"]
      source: |
        console.log("hello world");
```

It will host a file named `script` with **no extension** that will be executed by `deno run` in the deno container like a pipeline script in the same way as gitlab-ci or github-actions.

This manifest does not work for the typescript!

I have 2 points to make
- I am sure that there are many more use-cases where we want to be able to run deno script without specifying the script extension
- Why `js` language is the default?  At first glance, it sounds a bit random as deno manage both js and ts.

**Comment by joehillen** [comment] 2021-08-31 05:25
> Why js language is the default? At first glance, it sounds a bit random as deno manage both js and ts.

I makes even less sense when you consider the fact that Typescript is a superset of Javascript. Shouldn't Typescript be the default?

**Comment by kitsonk** [comment] 2021-08-31 07:51
TypeScript currently is type checked by default, which incurs a significant cost of startup of the type checker, and it requires transpiling to JavaScript to be executable. JavaScript is actually what is executed, so JavaScript is the default.

**Comment by lcrocker** [comment] 2021-11-04 23:04
I absolutely need this, because I'm developing a large suite of tools (something similar to ImageMagick) in Deno. I don't want them to have .ts extensions, and 40+ MB overhead per script is a non-starter. This is clearly the best of the several suggestions for making executable TypeScript scripts, it breaks nothing, and nothing I've read here is a legitimate argument against it. I don't generally like making "me too!" comments, but this is important. If it remains unassigned, I may tackle it myself.

**Comment by mateja176** [comment] 2021-11-23 23:57
Deno boasts about having first class Typescript support, but at least for now, it doesn't live up to the statement.
I got fed up with `ts-node` and thought to myself that this is the perfect opportunity to get my feet wet with Deno. I had high hopes for it, but this issue is a show stopper for me.

**Comment by mxcl** [comment] 2022-01-09 15:52
Only workaround that I could figure out is:

```sh
./foo
./foo.ts
```

Where `./foo` contains:

```sh
#!/bin/sh

exec ./foo.ts "$@"
```

Then you can put `foo.ts` wherever you want.

---

## Discussion

1. This is a bug AFAICT, deno should execute `.ts` by default.
2. We need someone from the core team to chime in and confirm if it is a bug or not.
3. I will happily write the PR if I know it is going to be applied

Personally I *absolutely* need this, I am attempting to replace other commands with deno scripts. I intend to compile the deno scripts for distribution (great feature btw) but for development I need extensionless scripts that execute typescript with deno and that's that.

**Comment by kitsonk** [comment] 2022-01-09 19:33
I have chimed in several times, it is not a bug. I have also chimed in

> 2\. We need someone from the core team to chime in and confirm if it is a bug or not.

It is not a bug. I have stated this several times. JavaScript is the default. `--ext` is an acceptable solution as it aligns to `deno fmt` and `deno eval`.

**Comment by mxcl** [comment] 2022-01-10 14:47
My bad, I didn’t realize. I intended no malice. My reading of this thread left me thinking there was no consensus or direction. I scanned it so: my bad.

I am still left unsure if any PR I submitted would be merged, so am going to stick with my workaround.

**Comment by bartlomieju** [comment] 2022-01-10 15:25
> I am still left unsure if any PR I submitted would be merged, so am going to stick with my workaround.

Yes, the PR adding support for `--ext` would be merged.

**Comment by martin-braun** [comment] 2022-01-18 01:33
Well I get `error: Found argument '--ext' which wasn't expected, or isn't valid in this context` when using this shebang:

```sh
#!/usr/bin/env -S deno run --ext=ts --unstable --allow-all
```

I use the latest version: 

```sh
$% deno --version
deno 1.17.3 (release, x86_64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2
```

Do I miss anything, please?

**Comment by crowlKats** [comment] 2022-01-18 05:30
It isnt implemented yet

**Comment by martin-braun** [comment] 2022-01-18 14:25
@crowlKats Thanks, searched for "--ext" in the release notes and found it, should have read closer, as it was implemented for `eval`.

**Comment by aiotter** [comment] 2022-02-08 05:01
It's a good hack, but I think it's inconsistent that deno always defaults to JS except reading from stdin.
I wonder if there was any change in direction of thought after https://github.com/denoland/deno/pull/6130#discussion_r436272509.

**Comment by joehillen** [comment] 2022-02-08 18:40
It's weird that it would autodetect for stdin but not for files. Perhaps that should be part of the PR for this. I recently quit my job, so I plan to open a PR for this soon.

**Comment by redxtech** [comment] 2022-04-06 08:55
Has there been any progress on this yet?

**Comment by kitsonk** [comment] 2022-04-25 23:35
No, because for the core team, it isn't a priority.  It is a good opportunity for a contribution.  As stated above, adding the `--ext` argument would be an acceptable solution.

**Comment by joehillen** [comment] 2022-12-08 18:22
@Cre3per even better would be if it could infer Typescript by attempting to parse the file. Is that an option? Although an explicit flag is still desired.

**Comment by Cre3per** [comment] 2022-12-09 11:48
@joehillen Inferring the type is an option. From a quick look, `file_fetcher.rs fetch_local()` would be the place to run a type guesser. I'm assuming cross-platform crates for type guessing are readily available.

Type guessing is in no conflict with `--ext`.  
`--ext` can have other use-cases, eg. a user might be porting TS to JS and wants to check if their script can be executed. Type guessing would be disadvantageous in that case.

I won't be adding type guessing in this MR, as I'm new to deno and prefer to take small steps. I'm not opposed to the idea.

**Closed** 2023-03-22 14:15 UTC
Labels: feat, cli, help wanted

**Comment by FranklinYu** [comment] 2023-04-05 04:21
I can confirm that the example in the issue description works under latest release! For easier copy-pasting, this is the full script:

```typescript
#!/usr/bin/env -S deno run --ext=ts

function hello(name: string) {
  console.log("Hello,", name);
}

hello(Deno.args[0]);
```

Thank @Cre3per for implementing this, and thank @dsherret for reviewing it! This is worth celebration!
