### ISSUE TITLE
Intermittent segfaulting using cbor-x since 1.44.2

### ISSUE THREAD

**Issue by Hexagon** [denoland/deno#24405] opened 2024-07-03 09:20 UTC
I've encontered an issue with any version of cbor-x in Deno versions 1.44.2 and later. A segmentation fault (or intermittently a runtime error) is triggered by specific data structures, such as the example provided below. The issue does not occur if the encoded result is immediately decoded without any intermediate steps (e.g., decode(encode(obj))).

Reported in https://github.com/kriszyp/cbor-x/issues/110, but also reporting here as the problem only affects very recent versions of Deno, indicating a possible internal problem in Deno

**Minimal repro: `test.ts`**
```ts 
import { decode, encode } from "npm:cbor-x@1.5.9";
// - In Deno 1.44.2, 100 repeatitions is fine, 200 gives typeError
// - In Deno 1.44.1 - everything is fine
decode(new Uint8Array(encode({"a":"a".repeat(200)})));
```

**Output:**
```
> deno run -A test.ts

error: Uncaught (in promise) TypeError: Unexpected end of buffer reading string
    at readString (file:///.../.deno/cbor-x@1.5.9/node_modules/cbor-x/decode.js:531:22)
```

**Segmentation fault repro: `test2.ts`**
```ts
import { decode, encode } from "npm:cbor-x@1.5.9";
for(let i=0; i < 1000; i++) {
  try {
    decode(new Uint8Array(encode({"a":"a".repeat(200000)})));
  } catch (_e) { /* Ignore */}
}
```

**Output:**
```
> deno run -A test2.ts

Segmentation fault (core dumped)
```

Tested on Windows

```
deno 1.44.2 (release, x86_64-pc-windows-msvc)
v8 12.6.228.9
typescript 5.4.5
```

And Linux

```
deno 1.44.4 (release, x86_64-unknown-linux-gnu)
v8 12.6.228.9
typescript 5.4.5
```

**Comment by kriszyp** [comment] 2024-07-06 10:08
I believe the issue is that [napi_get_buffer_info](https://nodejs.org/dist/latest-v20.x/docs/api/n-api.html#napi_get_buffer_info) is no longer working for `Uint8Array`s (fails to assign pointer and returns napi_invalid_arg instead napi_ok), and only working for `Buffer`s. This used to work, and the docs specifically state that (despite the name) this should accept `Uint8Array`s. I imagine this might have been a regression from the NAPI refactor?

**Comment by Hexagon** [comment] 2024-07-06 19:28
@devsnek What do you think about this?

**Comment by devsnek** [comment] 2024-07-06 19:44
This was fixed in https://github.com/denoland/deno/commit/293a36f98d3614368d24f7804d2fc4191a54c0e3 and should be available in the next deno release.

**Comment by Hexagon** [comment] 2024-07-06 19:48
Awesome, thanks!

**Closed** 2024-07-15 21:02 UTC
