### ISSUE TITLE
BUG

### ISSUE THREAD

**Issue by nirnay01** [denoland/deno#22737] opened 2024-03-06 08:17 UTC
deno test --inspect  org
.testCases.js 
Cannot start inspector server: Os { code: 98, kind: AddrInUse, message: "Address already in use" }

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux aarch64
Version: 1.40.5
Args: ["deno", "test", "--inspect", "org.testCases.js"]

thread 'tokio-runtime-worker' panicked at runtime/inspector_server.rs:88:53:
called `Result::unwrap()` on an `Err` value: TrySendError { kind: Disconnected }
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by bartlomieju** [comment] 2024-03-06 13:00
Duplicate of https://github.com/denoland/deno/issues/22113

**Closed by bartlomieju** 2024-03-06 13:00 UTC
