### ISSUE TITLE
`deno prune` / `deno remove --prune`

### ISSUE THREAD

**Issue by Malix-Labs** [denoland/deno#26522] opened 2024-10-24 16:02 UTC
Removes unnecessary packages

_Maybe running it automatically by default / with a flag_
_Go mod removes import when unused (unless specified otherwise with `_`) which I think is a good workflow_

Also see [`pnpm prune`](https://pnpm.io/cli/prune)

**Comment by lucacasonato** [comment] 2024-12-10 16:48
Duplicate of #27229

**Closed by lucacasonato** 2024-12-10 16:48 UTC
Labels: suggestion
