### ISSUE TITLE
repl: fails to print surrogate outside of pair

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno#13482] opened 2022-01-24 22:33 UTC
```console
% deno
Deno 1.18.0
exit using ctrl+d or close()
> "😂"[0]
Uncaught "Unterminated string literal"
```

I suggest printing the escaped value, `"\uD83D"`, like Chromium.

**Comment by lucacasonato** [comment] 2022-06-07 11:19
Duplicate of #12226

**Closed by lucacasonato** 2022-06-07 11:19 UTC
Labels: bug, repl
