### ISSUE TITLE
deno test log file paths

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#7861] opened 2020-10-07 15:23 UTC
As mentioned [here](https://discord.com/channels/684898665143206084/684911491035430919/763129882594508821):
There is a problem what tests belong to which file/module. `std` solves that currently with prefixing every test name. Though that works, I think there would be a better solution. `deno test` should log file paths to differentiate the tests like so for a better overview:
```sh
std/datetime/test.ts
  test parse ... ok
  test format ... ok
  …
std/bytes/test.ts
  test findIndex1 ... ok
  test findIndex2 ... ok
  …
```

**Comment by nayeemrmn** [comment] 2020-10-07 15:26
Duplicate of #4366. This requires some kind of isolation between runs on each module instead of just importing them all into the same environment.

**Comment by bartlomieju** [comment] 2020-10-07 15:28
CC @caspervonb for looking into this.

Closing as duplicate

**Closed by bartlomieju** 2020-10-07 15:28 UTC
