### ISSUE TITLE
Deno lint flags incorrect  `no-unreachable` rule flags valid code.

### ISSUE THREAD

**Issue by khrome83** [denoland/deno#7467] opened 2020-09-14 11:14 UTC
Deno lint in 1.4.0 is flagging this piece of code unreachable.

```
    switch (token) {
      case "auto":
        return i + "width: auto;" + nl;
      case "full":
        return i + "width: 100%;" + nl;
      case "screen":
        return i + "width: 100vw;" + nl;
      case "min-content":
        return i + "width: -webkit-min-content;" + nl +
          i + "width: -moz-min-content;" + nl +
          i + "width: min-content;" + nl;
      case "max-content":
        return i + "width: -webkit-max-content;" + nl +
          i + "width: -moz-max-content;" + nl +
          i + "width: max-content;" + nl;
    }

    return i + "width: " + calcUnit(token) + ";" + nl;
```

Specifically the last line. As a switch without a default, it would fall through the switch to the bottom return statement.

This get's flagged as part of `no-unreachable` rule.

**Comment by lucacasonato** [comment] 2020-09-14 11:16
Duplicate of https://github.com/denoland/deno_lint/issues/318

**Comment by khrome83** [comment] 2020-09-14 11:17
👍 Sorry @lucacasonato should of checked.

**Closed by lucacasonato** 2020-09-14 11:16 UTC
