### ISSUE TITLE
Dockerode won't work with Deno 2

### ISSUE THREAD

**Issue by ptrxyz** [denoland/deno#26255] opened 2024-10-14 23:52 UTC
Try this code:

```ts
// @deno-types="npm:@types/dockerode"
import Docker from "dockerode";

const docker = new Docker({ socketPath: "/var/run/docker.sock" });
const containers = await docker.listContainers({ all: true });
const images = await docker.listImages();
console.log({ images, containers });
```

It works nicely in Node and Bun yet Deno doesn't seem to like it.
If you run it with `deno run -A main.ts`, you'll get this error:
```
error: Uncaught (in promise) TypeError: error sending request for url (http://localhost/containers/json?all=true): client error (Connect): tcp connect error: Connection refused (os error 111): Connection refused (os error 111)
    at async node:http:313:21
```

Could this be a compatibility error?

Version:
deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2

**Comment by redabacha** [comment] 2024-10-15 21:35
related to https://github.com/denoland/deno/issues/17910

**Comment by marvinhagemeister** [comment] 2024-10-17 12:08
Marking as duplicate of #17910 .

**Closed by marvinhagemeister** 2024-10-17 12:08 UTC
Labels: bug, node compat
