### ISSUE TITLE
spurious check error on Iterator.toArray()

### ISSUE THREAD

**Issue by rjbudzynski** [denoland/deno#23523] opened 2024-04-24 09:22 UTC
Version: Deno 1.42.4

File test.ts contains:

```ts
const a = new Array(10).keys().toArray()
console.log(a)
```
Running it works as expected:
```
$ deno run test.ts
[
  0, 1, 2, 3, 4,
  5, 6, 7, 8, 9
]

```
But:

```
$ deno check test.ts
Check file:///home/rjb/Work/Deno/misc/test.ts
error: TS2339 [ERROR]: Property 'toArray' does not exist on type 'IterableIterator<number>'.
const a = new Array(10).keys().toArray()
                               ~~~~~~~
    at file:///home/rjb/Work/Deno/misc/test.ts:1:32
```

Yes, `.toArray()` on general Iterables is marked as experimental (as per MDN), however since it's implemented in Deno, the check error is spurious.

**Comment by Delapouite** [comment] 2024-04-26 11:18
Probably another manifestation of this issue https://github.com/denoland/deno/issues/23357

**Comment by lucacasonato** [comment] 2024-06-08 17:26
Closing as dupe of #23357

**Closed by lucacasonato** 2024-06-08 17:26 UTC
Labels: types
