### ISSUE TITLE
[feat] permission file

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#16019] opened 2022-09-25 01:14 UTC
### Scenario
```sh
$ deno test ${pem_hello} ./hello.ts
$ deno test ${pem_world} ./world.ts
# WILD PERM
$ deno test -A
$ deno run ${perm_hello} ./hello.ts
$ deno run ${perm_hello} ./world.ts
$ deno compile ${perm_hello} ./hello.ts
$ deno compile ${perm_world} ./world.ts
```

### Feat
deno.jsonc
```jsonc
{
  "perm": Perm | Path | WhatwgImportId
}
```

```typescript
type Perm = Record<PermId, DenoPerm>
type PermId = ImportMapId | PlaceHolderImportId | WhatwgImportId;
```

```sh
$ deno test
$ deno run ./hello.ts
$ deno run ./world.ts
$ deno compile ./hello.ts
$ deno compile ./world.ts
```

**Comment by kitsonk** [comment] 2022-09-26 08:01
Duplicate of #12763

**Closed by kitsonk** 2022-09-26 08:01 UTC
