### ISSUE TITLE
thread 'worker-0' panicked at 'not yet implemented: Worker are currently not supported in standalone binaries',

### ISSUE THREAD

**Issue by ralyodio** [denoland/deno#12611] opened 2021-10-31 05:49 UTC
```
thread 'worker-0' panicked at 'not yet implemented: Worker are currently not supported in standalone binaries', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.15.3/standalone.rs:208:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

deno v1.15.3

**Comment by kitsonk** [comment] 2021-10-31 06:40
The error message is pretty self explanatory, web workers are not supported in compiled binaries yet. Is there a reason you expected then to work?

**Comment by bartlomieju** [comment] 2021-10-31 09:21
Duplicate of https://github.com/denoland/deno/issues/8654

**Closed by bartlomieju** 2021-10-31 09:21 UTC
