### ISSUE TITLE
quarto install tinytex command not working

### ISSUE THREAD

**Issue by aminehochlef** [denoland/deno#25834] opened 2024-09-23 17:39 UTC
When trying to run the command `quarto install tinytex` to install tinytex, I get a log message and the installation don't start, the message returned : 

![P0vkWbxXcE](https://github.com/user-attachments/assets/3b26f135-49bc-488b-a8d2-df56775c30c8)

**Comment by marvinhagemeister** [comment] 2024-09-23 20:23
Duplicate of https://github.com/denoland/deno/issues/24137 . This issue has been fixed in Deno for a while, but the Quarto folks haven't updated their Deno version yet. This issue will be resolved for you once they update Deno. Here is the relevant issue on the Quarto issue tracker https://github.com/quarto-dev/quarto-cli/issues/10809

**Closed by marvinhagemeister** 2024-09-23 20:23 UTC
