### ISSUE TITLE
console log not aligning

### ISSUE THREAD

**Issue by t829702** [denoland/deno#5653] opened 2020-05-19 22:55 UTC
wonder if `console.log` on objects, and any non-string types has any standard?

```js
> var data = {"totalTax":7.45,"summary":[{"jurisName":"Utah","taxCalculated":4.85,"jurisType":"State","taxType":"Sales"},{"jurisName":"Salt Lake","taxCalculated":1.35,"jurisType":"County","taxType":"Sales"},{"jurisName":"Murray","taxCalculated":0.2,"jurisType":"City","taxType":"Sales"},{"jurisName":"Salt Lake Co Tr","taxCalculated":1.05,"jurisType":"Special","taxType":"Sales"}]};

> console.log(data);
{
 totalTax: 7.45,
 summary: [
  { jurisName: "Utah", taxCalculated: 4.85, jurisType: "State", taxType: "Sales" },
  {
    jurisName: "Salt Lake",
    taxCalculated: 1.35,
    jurisType: "County",
    taxType: "Sales"
   },
  { jurisName: "Murray", taxCalculated: 0.2, jurisType: "City", taxType: "Sales" },
  {
    jurisName: "Salt Lake Co Tr",
    taxCalculated: 1.05,
    jurisType: "Special",
    taxType: "Sales"
   }
]        // I believe this line not aligning is a bug, it has no leading space, better align with above `summary`
}
undefined
```

compare with in node:

```js
> console.log(data)
{ totalTax: 7.45,
  summary:
   [ { jurisName: 'Utah',
       taxCalculated: 4.85,
       jurisType: 'State',
       taxType: 'Sales' },
     { jurisName: 'Salt Lake',
       taxCalculated: 1.35,
       jurisType: 'County',
       taxType: 'Sales' },
     { jurisName: 'Murray',
       taxCalculated: 0.2,
       jurisType: 'City',
       taxType: 'Sales' },
     { jurisName: 'Salt Lake Co Tr',
       taxCalculated: 1.05,
       jurisType: 'Special',
       taxType: 'Sales' } ] }
undefined
```

also, node's REPL console.log has ansi coloring output for different types on terminals, will this come into Deno anytime soon?

**Comment by kitsonk** [comment] 2020-05-20 01:31
Duplicate of #3165

Also see #5404

**Comment by bartlomieju** [comment] 2020-05-20 10:54
Fixed in #5404

**Comment by t829702** [comment] 2020-05-24 16:29
the not aligning problem is not a dup, and not fixed in deno 1.0.2

I can still reproduce:

```js

{
  totalTax: 7.75,
  summary: [
    { jurisName: "California", taxCalculated: 6, jurisType: "State", taxType: "Sales" },
    {
        jurisName: "Riverside",
        taxCalculated: 0.25,
        jurisType: "County",
        taxType: "Sales"
      },
    {
        jurisName: "Riverside Co Local Tax Sl",
        taxCalculated: 1,
        jurisType: "Special",
        taxType: "Sales"
      },
    {
        jurisName: "Riverside County District Tax Sp",
        taxCalculated: 0.5,
        jurisType: "Special",
        taxType: "Sales"
      }
]           // what I meant is this line, supposed to be aligned with `summary`, should have leading spaces
}

```

**Comment by bartlomieju** [comment] 2020-05-24 17:19
CC @Speykious

**Comment by amarkantku** [comment] 2020-05-26 17:39
The issue is still able to reproduce.

**Comment by kitsonk** [comment] 2020-05-26 20:05
That is why the issue is open @amarkantku.

**Comment by Speykious** [comment] 2020-05-27 17:10
Oh... I didn't know, I thought I fixed it somehow.
I'll try to see how I can fix it

**Comment by actual-size** [comment] 2020-06-18 13:19
@t829702/@kitsonk - Looks like this issue was fixed with @Speykious's PR

**Closed** 2020-08-27 10:29 UTC
Labels: bug, cli, web
