### ISSUE TITLE
TypesScript support for extensionless executables

### ISSUE THREAD

**Issue by feluxe** [denoland/deno#7404] opened 2020-09-09 13:57 UTC
At our company we started to use `deno` as an alternative to `make` and `bash` to provide and run build-scripts for multiple projects. Each project contains an `aid.ts` file in its root which provides a micro-CLI using [docopt](https://deno.land/x/docopt@v1.0.1). So far this works nicely.

To make the `aid.ts` files executable from the command line we use this shebang (works on Linux and Mac):

```
#!/bin/sh
":" //; exec deno run -A --allow-run --unstable --allow-env --allow-write=.local/ --allow-read "$0" "$@"
```

A user can access the CLI like this: `aid.ts arg1 arg2 ...`

I would love to remove the `.ts` file extension so that a user can run the tools via `aid arg1 arg2...`, but as far as I can tell this doesn't work right now. When I remove the extension, deno will interpret the `aid` file as JavaScript and complain.

I think it would be nice if deno offered a way to run such executables without extension. I guess a simple `--ts` flag for `deno run` would suffice. What do you think? :-)

**Comment by nayeemrmn** [comment] 2020-09-09 20:02
Duplicate of #5088.

**Closed** 2020-09-10 16:01 UTC
