### ISSUE TITLE
String.normalize()

### ISSUE THREAD

**Issue by zekth** [denoland/deno#1952] opened 2019-03-18 09:33 UTC
Was working on a `removeDiacritics()` helper for `deno_std` and it appears that Deno is not properly handling `string.normalize()`.
**env**:
```
deno: 0.3.2
v8: 7.4.238
typescript: 3.2.1
```
**Example**:
strTest.ts
```ts
let input = "éèñëàäáüúùìíîïæç";
console.log(input.normalize("NFD").replace(/[\u0300-\u036f]/g, ""));
```
```
tsc strTest.ts -target esnext | node strTest.js // output: eeneaaauuuiiiiæc
deno strTest.ts // output: éèñëàäáüúùìíîïæç
```
ref: https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

**Comment by kitsonk** [comment] 2019-03-18 22:39
Sounds like it might be the same category as #1636.

**Comment by callionica** [comment] 2020-10-14 09:15
Any progress on this? Code doesn't fail, but it also doesn't do the expected conversion.

**Comment by coyotte508** [comment] 2020-10-27 21:01
In Rust it's possible with https://docs.rs/unicode-normalization/0.1.13/unicode_normalization/trait.UnicodeNormalization.html (is it possible to do a rust module that overwrites `String.protoype.normalize`?)

Node can be compiled with [system-icu](https://nodejs.org/api/intl.html#intl_build_with_a_pre_installed_icu_system_icu) which doesn't seem to add much weight and adds support for normalize.

**Comment by kitsonk** [comment] 2020-10-27 22:46
This is a duplicate of #1968 (even though this came before it) and adding ICU is the right way to fix it.  So closing in favour of that.

Implementing it in Rust would complicate things which can be solved by adding the ICU.

**Closed by kitsonk** 2020-10-27 22:46 UTC
