### ISSUE TITLE
Allow specifying tasks that just have dependencies.

### ISSUE THREAD

**Issue by lishaduck** [denoland/deno#27328] opened 2024-12-11 03:55 UTC
Deno v2.1 adds task dependencies 🎉
I've been missing them from Turborepo for so long, but no more!

Currently, however, the following configuration gives an error: 

```json
{
  "tasks": {
    "check": {
      "dependencies": ["format", "typecheck"]
    },
    "format": "biome format",
    "typecheck": "deno check **/*.ts **/*.tsx"
  },
}
```

I instead need a dummy `"command": "sleep 0"` line, which then shows up in the Deno task output. It'd be nice to relax this constraint.

**Comment by marvinhagemeister** [comment] 2024-12-11 09:31
Duplicate of https://github.com/denoland/deno/issues/27165

**Closed by marvinhagemeister** 2024-12-11 09:31 UTC
