### ISSUE TITLE
'new Date' creating wrong date

### ISSUE THREAD

**Issue by eikooc** [denoland/deno#20685] opened 2023-09-26 13:32 UTC
I think there is a bug in Deno's date module.

When I run these Date constructors in a browser I get the expected dates:
```js
new Date(2022, 0, 0)
// Fri Dec 31 2021 00:00:00 GMT+0100 (Central European Standard Time)
new Date(2022, 0, 1)
// Sat Jan 01 2022 00:00:00 GMT+0100 (Central European Standard Time)
new Date(2022, 0, 2)
// Sun Jan 02 2022 00:00:00 GMT+0100 (Central European Standard Time)
```

When I do the same in the Deno REPL I get these dates that seem to be offset by one:
```js
> new Date(2022, 0, 0)
// 2021-12-30T23:00:00.000Z
> new Date(2022, 0, 1)
// 2021-12-31T23:00:00.000Z
> new Date(2022, 0, 2)
// 2022-01-01T23:00:00.000Z
```

It might be it's only the `toString` (and the `toISOString`) function, since calling `getDate()`, `getFullYear()` and so on gives back the right date.

**Comment by Seally** [comment] 2023-09-26 14:23
I think this is because the browser's display string shows the time in your current timezone and Deno's date display shows the time in UTC. It's off by 1 hour for you and 7 hours for me, corresponding to our timezone offsets. The constructor evaluates the parameters in local time.

Deno's display string format seems to be the same as in Node, by the way.

**Comment by lucacasonato** [comment] 2023-09-26 14:54
Yes, we display dates in UTC (this is what the Z suffix on the date means, Z stands for [Zulu time](https://en.wikipedia.org/wiki/Coordinated_Universal_Time)).

**Comment by lucacasonato** [comment] 2023-09-27 05:19
Going to close this as it's working as designed.

**Closed by lucacasonato** 2023-09-27 05:19 UTC
Labels: working as designed

**Comment by eikooc** [comment] 2023-09-27 06:09
Alright. I just haven't found documentation on this and it confused me :+1:
