### ISSUE TITLE
Feature Request: Deno Repl as module with top-level await

### ISSUE THREAD

**Issue by 00ff0000red** [denoland/deno#7077] opened 2020-08-16 23:57 UTC
This derives from the browser console, which is the only thing comparable to Deno's terminal repl.

As of right now, the repl is a normal script, I believe that it would be more helpful to anyone using it If it were a module allowing imports, and with top-level await, as most of Deno is promise focused.

I believe it to be reasonable to derive from the browser in this case as the repl / console is often used for something simple and short, and having more utility there would be helpful, and it shouldn't break any backward compatibility as scripts aren't intended to be programmatically run there.

The console is merely a simple tool to help us out, is it not? What could go wrong?

If anything, having an optional flag wouldn't be that bad,

Maybe something like so: ```
deno --repl=module```

**Comment by crowlKats** [comment] 2020-08-17 00:03
Duplicate of #1285
Duplicate of #3700

**Comment by 00ff0000red** [comment] 2020-08-17 01:58
Ahh, it's a duplicate, I'll close it down.

**Closed** 2020-08-17 01:58 UTC
