### ISSUE TITLE
In array map method can not use division

### ISSUE THREAD

**Issue by sholvoir** [denoland/deno#8532] opened 2020-11-28 16:32 UTC
Deno 1.5.3

code:
[2,4].map(a=>a/2)

can not run.

**Comment by RDambrosio016** [comment] 2020-11-28 16:34
Works fine for me on 1.5.4
```js
> [2,4].map(a=>a/2)
[ 1, 2 ]
```

**Comment by sholvoir** [comment] 2020-11-28 20:31
I upgrade my Deno to 1.5.4
and it still can not work.

I use `macOS Big Sur version 11.0.1`
intall method: `curl -fsSL https://deno.land/x/install/install.sh | sh`
when run code `[2,4].map(a=>a/2)`, it die and it's same in 1.5.3.

**Comment by lucacasonato** [comment] 2020-11-28 23:00
What is the error message? Are you on an Apple Silicon device?

**Comment by lucacasonato** [comment] 2020-11-28 23:03
Are you running this from REPL?

**Comment by sholvoir** [comment] 2020-11-29 00:52
There is no error message, just die. It run from REPL on Intel not Apple Silicon.

**Comment by Sparkenstein** [comment] 2020-11-29 06:48
Checked this on Ubuntu 20.04, Deno v1.5.3 same issue. REPL just stops working

![image](https://user-images.githubusercontent.com/24642451/100535220-fbde2b80-323c-11eb-8ff2-628ea68dc7b3.png)

**Comment by magurotuna** [comment] 2020-11-29 08:02
I'm on Manjaro 20.2 and can reproduce it on v1.5.4.
But I've also noticed that it works fine when running on the current master.

I  did binary search to find when this bug was fixed; it seems like https://github.com/denoland/deno/commit/228ecb0acbcc2f0299428380d03f7f3681d21128 fixed it.

**Comment by kevinkassimo** [comment] 2020-11-29 10:22
> Checked this on Ubuntu 20.04, Deno v1.5.3 same issue. REPL just stops working
> 
> 
> 
> ![image](https://user-images.githubusercontent.com/24642451/100535220-fbde2b80-323c-11eb-8ff2-628ea68dc7b3.png)
> 
> 

Yeah apparently this is a REPL only issue due to the old parsing strategy which could not distinguish between division, regex and comments at times. This should have been fixed in recent PRs using swc parser and would hopefully work in the next release.

**Comment by bartlomieju** [comment] 2020-11-29 13:27
I'm gonna close this issue as provisionally fixed by https://github.com/denoland/deno/pull/8496, it will be released as part of `1.6.0` on 8th of December

**Closed by bartlomieju** 2020-11-29 13:27 UTC
