### ISSUE TITLE
Deno has panicked when typing invalid code into VSCode Debug Console

### ISSUE THREAD

**Issue by ArmaanAS** [denoland/deno#25106] opened 2024-08-20 08:52 UTC
Version: Deno 1.45.5

Using VSCode debugger with my launch.json configuration provided below:

```jsonc
// launch.json
{
  "version": "0.2.0",
  "configurations": [
    {
      "request": "launch",
      "name": "Deno",
      "type": "node",
      "program": "${workspaceFolder}/${relativeFile}",
      "cwd": "${workspaceFolder}",
      "env": {
        "DENO_FUTURE": "1", // Still panics without this
        "RUST_BACKTRACE": "full"
      },
      "runtimeExecutable": "deno",
      "runtimeArgs": ["run", "--inspect-wait", "-A"],
      "attachSimplePort": 9229
    }
  ]
}
```

Add a breakpoint / debugger statement, no other code / deno.json required

```typescript
// main.ts
debugger
```

While viewing `main.ts`, press F5 or the start debugging in VSCode "Run and Debug". This will run deno and immediately pause the program which allows you to type code into the console. If you type something that would throw a javascript error, Deno panics.

E.g. typing "a" causes this error:

```shell
/home/user/.deno/bin/deno run --inspect-wait -A main.ts

> a

Debugger listening on ws://127.0.0.1:9229/ws/c0c6592b-8b43-458d-9a70-ed38766d01de
Visit chrome://inspect to connect to the debugger.
Deno is waiting for debugger to connect.
Debugger session started.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.45.5
Args: ["/home/user/.deno/bin/deno", "run", "--inspect-wait", "-A", "./types/t.ts"]

thread 'main' panicked at /home/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_core-0.299.0/error.rs:1245:36:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0:     0x564fd5fbf5c5 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3692694645b1bb6a
   1:     0x564fd5ff1f7b - core::fmt::write::h5131d80b4c69b88d
   2:     0x564fd5fb969f - std::io::Write::write_fmt::h1fb327a7d8b0eb36
   3:     0x564fd5fbf39e - std::sys_common::backtrace::print::h998d75b840f75a73
   4:     0x564fd5fc0e09 - std::panicking::default_hook::{{closure}}::h18ec7fe6a38b9da0
   5:     0x564fd5fc0baa - std::panicking::default_hook::hfb3f22c2e4075a6a
   6:     0x564fd657593d - deno::setup_panic_hook::{{closure}}::hd5bd3712b479b3db
   7:     0x564fd5fc147b - std::panicking::rust_panic_with_hook::h51af00bcb4660c4e
   8:     0x564fd5fc11bb - std::panicking::begin_panic_handler::{{closure}}::h39f76aa863fbe8ce
   9:     0x564fd5fbfa89 - std::sys_common::backtrace::__rust_end_short_backtrace::h4d10fc2251b89840
  10:     0x564fd5fc0f27 - rust_begin_unwind
  11:     0x564fd5feeec3 - core::panicking::panic_fmt::h319840fcbcd912ef
  12:     0x564fd5feef6c - core::panicking::panic::h19def44c80243eda
  13:     0x564fd5feec09 - core::option::unwrap_failed::h9b45086d3ec3e03c
  14:     0x564fd8000f7a - deno_core::error::format_location::h94bfae1e02ede56e
  15:     0x564fd7fb2060 - <extern "C" fn(A0,A1,A2) .> R as v8::support::CFnFrom<F>>::mapping::c_fn::h9d12c281b4b623fd
  16:     0x564fd4b215a5 - _ZN2v88internal10ErrorUtils16FormatStackTraceEPNS0_7IsolateENS0_6HandleINS0_8JSObjectEEENS4_INS0_6ObjectEEE
  17:     0x564fd4b26267 - _ZN2v88internal10ErrorUtils17GetFormattedStackEPNS0_7IsolateENS0_6HandleINS0_8JSObjectEEE
  18:     0x564fd49eeceb - _ZN2v88internal9Accessors16ErrorStackGetterERKNS_20FunctionCallbackInfoINS_5ValueEEE
  19:     0x564fd49f4439 - _ZN2v88internal25FunctionCallbackArguments4CallENS0_6TaggedINS0_20FunctionTemplateInfoEEE
  20:     0x564fd49f3b71 - _ZN2v88internal8Builtins17InvokeApiFunctionEPNS0_7IsolateEbNS0_6HandleINS0_20FunctionTemplateInfoEEENS4_INS0_6ObjectEEEiPS8_NS4_INS0_10HeapObjectEEE
  21:     0x564fd4ed3176 - _ZN2v88internal6Object23GetPropertyWithAccessorEPNS0_14LookupIteratorE
  22:     0x564fd4ed29e0 - _ZN2v88internal6Object11GetPropertyEPNS0_14LookupIteratorEb
  23:     0x564fd4fe15ef - _ZN2v88internal7Runtime17GetObjectPropertyEPNS0_7IsolateENS0_6HandleINS0_6ObjectEEES6_S6_Pb
  24:     0x564fd49d78db - _ZN2v86Object3GetENS_5LocalINS_7ContextEEENS1_INS_5ValueEEE
  25:     0x564fd55de9d7 - _ZN12v8_inspector12_GLOBAL__N_119descriptionForErrorEN2v85LocalINS1_7ContextEEENS2_INS1_6ObjectEEENS0_9ErrorTypeE
  26:     0x564fd55dcef8 - _ZN12v8_inspector11ValueMirror6createEN2v85LocalINS1_7ContextEEENS2_INS1_5ValueEEE
  27:     0x564fd55a3e54 - _ZN12v8_inspector14InjectedScript18wrapEvaluateResultEN2v810MaybeLocalINS1_5ValueEEERKNS1_8TryCatchERKNS_8String16ERKNS_11WrapOptionsEbPNSt2Cr10unique_ptrINS_8protocol7Runtime12RemoteObjectENSE_14default_deleteISI_EEEEPN8v8_crdtp6detail8PtrMaybeINSH_16ExceptionDetailsEEE
  28:     0x564fd557a5b8 - _ZN12v8_inspector19V8DebuggerAgentImpl19evaluateOnCallFrameERKNS_8String16ES3_N8v8_crdtp6detail10ValueMaybeIS1_EENS6_IbEES8_S8_S8_S8_NS6_IdEEPNSt2Cr10unique_ptrINS_8protocol7Runtime12RemoteObjectENSA_14default_deleteISE_EEEEPNS5_8PtrMaybeINSD_16ExceptionDetailsEEE
  29:     0x564fd558d096 - _ZN12v8_inspector8protocol8Debugger20DomainDispatcherImpl19evaluateOnCallFrameERKN8v8_crdtp12DispatchableE
  30:     0x564fd55f10e4 - _ZN8v8_crdtp14UberDispatcher14DispatchResult3RunEv
  31:     0x564fd55c47fa - _ZN12v8_inspector22V8InspectorSessionImpl23dispatchProtocolMessageENS_10StringViewE
  32:     0x564fd8004a2f - deno_core::inspector::JsRuntimeInspector::poll_sessions::hf899c5e5e1b65c03
  33:     0x564fd812e176 - v8_inspector__V8InspectorClient__BASE__runMessageLoopOnPause
  34:     0x564fd5562c4d - _ZN12v8_inspector10V8Debugger18handleProgramBreakEN2v85LocalINS1_7ContextEEENS2_INS1_5ValueEEERKNSt2Cr6vectorIiNS7_9allocatorIiEEEENS1_4base7EnumSetINS1_5debug11BreakReasonEiEENSG_13ExceptionTypeEb
  35:     0x564fd5562f6f - _ZN12v8_inspector10V8Debugger21BreakProgramRequestedEN2v85LocalINS1_7ContextEEERKNSt2Cr6vectorIiNS5_9allocatorIiEEEENS1_4base7EnumSetINS1_5debug11BreakReasonEiEE
  36:     0x564fd4ab3c63 - _ZN2v88internal5Debug12OnDebugBreakENS0_6HandleINS0_10FixedArrayEEENS0_10StepActionENS_4base7EnumSetINS_5debug11BreakReasonEiEE
  37:     0x564fd4abadf8 - _ZN2v88internal5Debug16HandleDebugBreakENS0_15IgnoreBreakModeENS_4base7EnumSetINS_5debug11BreakReasonEiEE
  38:     0x564fd4fddf65 - _ZN2v88internal31Runtime_HandleDebuggerStatementEiPmPNS0_7IsolateE
  39:     0x564fd5e60236 - Builtins_CEntry_Return1_ArgvOnStack_NoBuiltinExit
```

**Comment by nathanwhit** [comment] 2024-08-20 16:07
Hello, thanks for reporting (and with such a small reproduction)!

This issue should be fixed in the main branch, and the fix will be in the next release (scheduled for this week).

If you want, you can try the latest canary build right now (`deno upgrade --canary`) to confirm it's fixed.

I'll close this for now (since my testing shows this doesn't reproduce on canary), but feel free to reopen if you continue to hit this.

**Closed by nathanwhit** 2024-08-20 16:07 UTC
