### ISSUE TITLE
Deno panic (because of --fail-fast?)

### ISSUE THREAD

**Issue by voltrevo** [denoland/deno#16947] opened 2022-12-05 05:38 UTC
Got this panic output:

```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.28.3
Args: ["deno", "test", "--fail-fast=3", "--allow-net", "--allow-env", "--allow-read", "--unstable", "--", "--env", "undefined"]

thread 'tokio-runtime-worker' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 32, kind: BrokenPipe, message: "Broken pipe" }', cli/tools/test.rs:1650:56
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: core::result::Result<T,E>::unwrap
   4: deno::tools::test::TestOutputPipe::flush
   5: deno::tools::test::TestEventSender::send
   6: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
error: Uncaught Error: Command: "deno test --fail-fast=3 --allow-net --allow-env --allow-read --unstable -- --env " exited with code 1
    throw new Error(
          ^
    at Module.run (file:///Users/andrew/workspaces/ethf/bls-wallet/aggregator/programs/helpers/shell.ts:16:11)
    at async file:///Users/andrew/workspaces/ethf/bls-wallet/aggregator/programs/premerge.ts:34:7
    at async file:///Users/andrew/workspaces/ethf/bls-wallet/aggregator/programs/premerge.ts:15:3
```

Since this is a broken pipe, I'm guessing this has to do with the `--fail-fast` option nuking a stream in a way that doesn't get handled correctly.

This has reproduced every time for me so far. To reproduce:

```
git clone git@github.com:web3well/bls-wallet
cd bls-wallet
git checkout 0bfaf98dfa4e0ad24ddebc5e687ea8e643729e38
cd aggregator
cp .env.example .env
./programs/premerge.ts
```

Running the test suite 'properly' requires some other set-up, but it's not necessary to reproduce the panic.

To clarify, this bug involves some failing tests in my project, but they aren't caused by the deno bug (ie I'm not asking for help with my own tests).

**Comment by bartlomieju** [comment] 2022-12-05 14:00
@dsherret can you take a look?

**Comment by dsherret** [comment] 2022-12-05 14:13
Duplicate of #15650

**Closed by dsherret** 2022-12-05 14:13 UTC
Labels: bug, cli, duplicate, testing

**Comment by dsherret** [comment] 2022-12-06 00:06
Will be fixed in the next patch release on Thursday.
