### ISSUE TITLE
(jupyter) Console log in jupyter notebook prints only last message

### ISSUE THREAD

**Issue by zph** [denoland/deno#24437] opened 2024-07-04 22:35 UTC
Versions of Deno affected (non-exhaustive):
- 8fcc26310 near tip of main
- 1.44.4
- 1.43.6

Working versions: 
- 1.43.5
- 1.43.3
- 1.43.0
- 1.42.4
- (etc)

The regression occurred between v1.43.5 and 1.43.6: https://github.com/denoland/deno/compare/v1.43.5...v1.43.6

Expected behavior: console.log will print all messages from a cell
<img width="662" alt="image" src="https://github.com/denoland/deno/assets/1026584/36206dbf-5416-4204-ab1b-d4e4db4bf260">

Actual behavior: console.log prints only last message from a cell

<img width="1169" alt="image" src="https://github.com/denoland/deno/assets/1026584/cc079adc-96ca-452f-8cdc-9d7f3078f337">

The changes to jupyter occurred in: https://github.com/denoland/deno/commit/93d7b37e5c045372182da2dd5bf8c9958290c7a7 as part of refactoring the jupyter integration.

@rgbkrk Do you have a hunch about where this is happening since you authored the work in 93d7b37e5c045372182da2dd5bf8c9958290c7a7?

**Comment by rgbkrk** [comment] 2024-07-05 20:34
Yeah this is bound to be in that stdio sender. Oddly I'm not seeing this in `1.44.1`.

<img width="812" alt="image" src="https://github.com/denoland/deno/assets/836375/4ab87ce8-156c-4d8e-98ec-79fb57a7bad4">

**Comment by rgbkrk** [comment] 2024-07-05 21:10
This only reproduces in VS Code. In Jupyterlab, classic, and Zed Nightly it all displays normally.

**Comment by lucacasonato** [comment] 2024-07-09 13:06
@rgbkrk Is this something we should change in `deno jupyter`, or do you think this is an upstream VS Code issue?

**Comment by rgbkrk** [comment] 2024-07-09 15:58
It looks like it's on the VS Code side. I'll dig in to find out why though as all clients should be treating the protocol the same.

**Comment by sinedied** [comment] 2024-07-12 08:20
Can it also be the reason why errors are not being displayed in the console?

<img width="1186" alt="image" src="https://github.com/user-attachments/assets/504d7249-9ca2-4bc7-a576-25009ea8cef4">

I'm only using VS Code and currently I'm unable to see errors in code cells. Let me know if you think I should open a separate issue, but I may get nothing because only the last print (newline?) is shown.

**Comment by mrbelderock** [comment] 2024-07-13 09:06
Just commenting to say I have the same issue. VSCode, Deno 1.44.1 - console.log prints only last line and (so?) errors don't print either.

**Comment by rgbkrk** [comment] 2024-07-15 16:32
@DonJayamanne -- I haven't discovered yet why VS Code is treating messages differently than other jupyter frontends. Can you check this out?

**Comment by sinedied** [comment] 2024-07-15 17:29
I have an extra hint that may be useful for the investigation: it's not only the last log that is shown, but only the last one from the same tick.

The following code:
```js
console.log("1");
console.log("2");
window.setTimeout(() => {
  console.log("3");
});
```
outputs
```
2
3
```
in VS Code. So console logs in different ticks are still visible.

**Comment by DonJayamanne** [comment] 2024-07-26 11:56
Root cause is here, https://github.com/denoland/deno/issues/24737
Apologies for taking so long

**Comment by rgbkrk** [comment] 2024-07-26 20:57
Egg on my face, I'm going to go fix this now.

**Comment by bartlomieju** [comment] 2024-07-27 08:39
Closed in https://github.com/denoland/deno/pull/24762

**Closed by bartlomieju** 2024-07-27 08:39 UTC
Labels: bug, deno jupyter
