### ISSUE TITLE
Expose DENO_DIR, Remote Modules, & Typescript compiler cache folder.

### ISSUE THREAD

**Issue by andreespirela** [denoland/deno#8231] opened 2020-11-03 14:38 UTC
The idea is to expose the mentioned paths in the Deno namespace as a const.

`Deno.DENO_DIR` maybe.

or maybe some sort of const or function that has/return an object as its value. This object would contain the three mentioned
`{
deno_dir,
remote_modules,
typescript_compiler_cache
}`

**Comment by nayeemrmn** [comment] 2020-11-03 14:50
Duplicate of #2096, #6891.

**Comment by MarkTiedemann** [comment] 2020-11-03 16:57
Also related: https://github.com/denoland/deno/issues/3551

@andreespirela What's your use case? :)

**Comment by andreespirela** [comment] 2020-11-03 17:54
@MarkTiedemann It would be good to download things such as plugin in the deno cache folder. Having it in the repo seems a little annoying. Also for dynamic building purposes so for example in [Mandarine Framework](https://github.com/mandarineorg/mandarinets) there's an option to auto-generate the entry point file Deno will run & then Mandarine handles the logic and runs this dynamic generated file in the background, I also think these kind of files shouldn't belong to the repo, the developers could target DENO_DIR instead.

**Comment by kitsonk** [comment] 2020-11-03 21:45
Closing it as duplicate of #2096 #6891 and #3551.  I would recommend adding comments/suggestions to #6891.

**Closed by kitsonk** 2020-11-03 21:45 UTC
