### ISSUE TITLE
lsp errors with "The current snapshot version is missing."

### ISSUE THREAD

**Issue by MierenManz** [denoland/deno#9348] opened 2021-01-31 15:34 UTC
I have no idea what exactly happened
```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', cli\lsp\tsc.rs:806:43
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error processing TypeScript diagnostics:
channel closed
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: "PoisonError { inner: .. }"', cli\lsp\language_server.rs:532:8
```

**Comment by kitsonk** [comment] 2021-01-31 22:22
Can you provide the version of Deno you were using?  Also, what you were doing at the time it occurred?

**Comment by MierenManz** [comment] 2021-01-31 22:24
Either deno 1.7.0 or deno 1.7.1 (not sure, sorry) and I was editing the .vscode/settings.json

**Comment by kitsonk** [comment] 2021-01-31 22:27
Are you using a `tsconfig.json` with the workspace?  If so, could you share it?

**Comment by MierenManz** [comment] 2021-01-31 23:09
I do not. Didn't even know I could to be honest.

**Comment by kitsonk** [comment] 2021-01-31 23:15
Ok, sorry to bother, but could you provide a version of your `.vscode/settings.json`.  Basically trying to figure out why you were in this part of the code when you were editing `.vscode/settings.json` because there is nothing obvious of why you ended up where you ended up.

**Comment by MierenManz** [comment] 2021-02-01 22:05
```json
{
    "deno.enable": true,
    "deno.lint": true
}
```
This is the only thing in the settings.json

after I thought about it. I think these were the steps that caused it
1. delete settings.json
2. disable deno canary
3. reload vsc
4. enable deno canary
5. create setting.json with your hand and copy paste these settings.

This is what I did

**Comment by danopia** [comment] 2021-02-28 09:14
I think I just encountered the same panic in 1.7.5. The code has changed a bit since 1.7.0 but it's a none-unwrap within the same function. My stack is pointing at this line: https://github.com/denoland/deno/blob/v1.7.5/cli/lsp/tsc.rs#L1099

```
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', cli/lsp/tsc.rs:1099:63
```

It happened twice about 90 seconds apart. I don't really recall doing anything interesting; just working on some typescript libraries. I'll report back if it recurs with more-interesting notes.

**Comment by kitsonk** [comment] 2021-02-28 20:04
Ok thanks, it is a bit crazy it is occurring there, as it shouldn't, but it is. I think we are going to have to add some code there to deal with it more safely and log out some information when it occurs, as it seems we are getting into code that logically we shouldn't.

**Comment by danopia** [comment] 2021-02-28 20:13
I just noticed that this LSP panic issue that I filed in December: #8881 on 1.6.1 is pointing at the sameish unwrap too? https://github.com/denoland/deno/blob/v1.6.1/cli/lsp/tsc.rs#L693

**Comment by kitsonk** [comment] 2021-02-28 22:44
@danopia was it a similiar/same project?  Is it possible to get a `deno info` of the file you were editing when the error occurred?

You are right the previous one was effectively the same bit of code... I had assumed the previous one had been to some race-conditions we knew we had which we thought we fixed, but I guess not.

**Comment by kitsonk** [comment] 2021-02-28 23:37
Ok, I think I suspect I know where the error is coming from... I have hardened the code there so it shouldn't panic anymore and cause an error that will be more informative, but I am not sure how to reproduce at the moment.  It "might" be related to opening up a document in the editor that was previously a dependency on disk, but I am not totally sure.

There was also some code that _could_ have maybe resulted something going wrong I fixed, but again, I haven't been able to produce it.

**Comment by danopia** [comment] 2021-03-03 05:37
So, I suppose this new error message is in because after installing 1.8.0 I started get a lot of messages - no panic means the LSP can serve them up more efficiently 😄 

This is one of the full exact message that I get:

```
Unable to get quick info: Error: The current snapshot version is missing.
  Args: "GetChangeRangeArgs { specifier: "https://deno.land/x/base64@v0.2.1/base.ts", old_length: 4170, old_version: "1613322623381", version: "1614747692610" }"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:236:12)
    at ScriptSnapshot.getChangeRange (deno:cli/tsc/99_main_compiler.js:224:19)
    at acquireOrUpdateDocument (deno:cli/tsc/00_typescript.js:123008:133)
    at Object.updateDocumentWithKey (deno:cli/tsc/00_typescript.js:122974:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (deno:cli/tsc/00_typescript.js:149726:49)
    at tryReuseStructureFromOldProgram (deno:cli/tsc/00_typescript.js:107087:28)
    at Object.createProgram (deno:cli/tsc/00_typescript.js:106618:29)
    at synchronizeHostData (deno:cli/tsc/00_typescript.js:149648:26)
    at Object.getQuickInfoAtPosition (deno:cli/tsc/00_typescript.js:149810:13)
```

This bit was the same in every message (40+ by the time I stopped): `Args: "GetChangeRangeArgs { specifier: "https://deno.land/x/base64@v0.2.1/base.ts", old_length: 4170, old_version: "1613322623381", version: "1614747692610" }"`

Since this file was 100% unrelated to anything i was doing - I was actually editing a for-browser .js file at the time - I realized the massive pile of 'open editors' I had probably wasn't helping, and after closing them the problem went away.

I don't think this comment will help to repro :( but the new message should help the first time this crops up again

**Comment by kitsonk** [comment] 2021-03-03 06:09
No, that actually helps a lot... I think I know what is going on, though I am not sure why the files are getting touched on the file system in the DENO_CACHE, but it is happening at points where we aren't expecting it to happen.  Before with the panic, we would simply lose everything and it was hard to guess.

**Closed** 2021-03-10 10:39 UTC
Labels: bug, lsp
