### ISSUE TITLE
Static build of deno

### ISSUE THREAD

**Issue by glensc** [denoland/deno#13891] opened 2022-03-09 16:41 UTC
Running on super old distro (don't ask), yields errors:

```
$ /home/glen/.deno/bin/deno --help
/home/glen/.deno/bin/deno: /lib64/libgcc_s.so.1: version `GCC_4.0.0' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/libgcc_s.so.1: version `GCC_4.2.0' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libm.so.6: version `GLIBC_2.27' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libc.so.6: version `GLIBC_2.4' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libc.so.6: version `GLIBC_2.7' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libc.so.6: version `GLIBC_2.9' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libc.so.6: version `GLIBC_2.10' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libc.so.6: version `GLIBC_2.14' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libc.so.6: version `GLIBC_2.15' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libc.so.6: version `GLIBC_2.18' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libc.so.6: version `GLIBC_2.25' not found (required by /home/glen/.deno/bin/deno)
/home/glen/.deno/bin/deno: /lib64/tls/libc.so.6: version `GLIBC_2.27' not found (required by /home/glen/.deno/bin/deno)
```

perhaps possible to add fully static build, not to rely on glibc and gcc?

**Comment by littledivy** [comment] 2022-03-09 16:44
Duplicate of https://github.com/denoland/deno/issues/3711 (MUSL builds)

Let's keep the discussion going on there

**Closed by littledivy** 2022-03-09 16:44 UTC
