### ISSUE TITLE
Argument of type 'string | URL' is not assignable to parameter of type 'string'.

### ISSUE THREAD

**Issue by welldonexing** [denoland/deno#5764] opened 2020-05-22 19:30 UTC
const [errors, emitted] = await Deno.compile("./app.ts", undefined, {
  lib: ["es6","dom", "esnext", "deno.ns","scripthost","dom.iterable"], // include "deno.ns" for deno namespace
  outDir: "./",
});

if (errors) {
  console.log("There was an error:");
  console.log(errors);
} else {
  console.log(emitted); // normally we would write the file
}

when i was use    Deno.compile    case error

 {
    message: "Argument of type 'string | URL' is not assignable to parameter of type 'string'.",
    messageChain: {
      message: "Argument of type 'string | URL' is not assignable to parameter of type 'string'.",
      code: 2345,
      category: 3,
      next: [Array]
    },
    code: 2345,
    category: 3,
    startPosition: 12702,
    endPosition: 12705,
    sourceLine: "  return new URL(url).pathname;",
    lineNumber: 432,
    scriptResourceName: "https://deno.land/std@0.51.0/path/posix.ts",
    startColumn: 17,
    endColumn: 20
  },
{
    message: "Argument of type 'string | URL' is not assignable to parameter of type 'string'.",
    messageChain: {
      message: "Argument of type 'string | URL' is not assignable to parameter of type 'string'.",
      code: 2345,
      category: 3,
      next: [Array]
    },
    code: 2345,
    category: 3,
    startPosition: 27167,
    endPosition: 27170,
    sourceLine: "  return new URL(url).pathname",
    lineNumber: 910,
    scriptResourceName: "https://deno.land/std@0.51.0/path/win32.ts",
    startColumn: 17,
    endColumn: 20
  },
{
    message: "Argument of type 'string | URL' is not assignable to parameter of type 'string'.",
    messageChain: {
      message: "Argument of type 'string | URL' is not assignable to parameter of type 'string'.",
      code: 2345,
      category: 3,
      next: [Array]
    },
    code: 2345,
    category: 3,
    startPosition: 12702,
    endPosition: 12705,
    sourceLine: "  return new URL(url).pathname;",
    lineNumber: 432,
    scriptResourceName: "https://deno.land/std@0.52.0/path/posix.ts",
    startColumn: 17,
    endColumn: 20
  },
{
    message: "Argument of type 'string | URL' is not assignable to parameter of type 'string'.",
    messageChain: {
      message: "Argument of type 'string | URL' is not assignable to parameter of type 'string'.",
      code: 2345,
      category: 3,
      next: [Array]
    },
    code: 2345,
    category: 3,
    startPosition: 27167,
    endPosition: 27170,
    sourceLine: "  return new URL(url).pathname",
    lineNumber: 910,
    scriptResourceName: "https://deno.land/std@0.52.0/path/win32.ts",
    startColumn: 17,
    endColumn: 20
  }

but if  i  use   deno.run     that was no problem ,  but i want to compile.  deno v 1.0.1

**Comment by kitsonk** [comment] 2020-05-22 21:02
Duplicate of #5365 

Please use the search function to avoid opening duplicate issues.

**Comment by bartlomieju** [comment] 2020-05-23 09:55
Closing in favor of #5365

**Closed by bartlomieju** 2020-05-23 09:55 UTC
