### ISSUE TITLE
Error on try using decorators

### ISSUE THREAD

**Issue by mtwzim** [denoland/deno#5736] opened 2020-05-22 01:29 UTC
Hello guys, I'm trying to create decorators with the deno, however this is not being possible, the deno console also does not provide me with information.

See the code:
```class TBaseClass {}

interface Newable<T> {
    new(...args: any[]): T;
}

function Decorate() {
    return function <T extends Newable<TBaseClass>>(constructor: T): any {
        // extend constructor
        console.log(constructor);
        return class extends constructor {
            protected _extraField: string = '-'
        }; 
    }
}
@Decorate()
class ExtTest{}
console.log((new ExtTest))
```
*OBS: I tried remove the <T extends Newable<TBaseClass>> and but not working
If i comment the "@Decorate" the error fades away.
See the console:
![image](https://user-images.githubusercontent.com/42474938/82621736-57ef3580-9bb2-11ea-9433-453fe7d6fe05.png)
and my tsconfig.json:
![image](https://user-images.githubusercontent.com/42474938/82621767-6ccbc900-9bb2-11ea-88fa-d12c6c04c0af.png)
am i doing something wrong?

See you later!

**Comment by kitsonk** [comment] 2020-05-22 01:33
Please see the manual: https://deno.land/manual/getting_started/typescript#custom-typescript-compiler-options

**Comment by mtwzim** [comment] 2020-05-22 01:35
> Please see the manual: https://deno.land/manual/getting_started/typescript#custom-typescript-compiler-options

I just read and test, but I still can't remove my error

**Comment by kitsonk** [comment] 2020-05-22 01:38
Nothing you provided shows that you are following the manual.  Please provide what you are specifically running on the command line.

**Comment by rafaelferres** [comment] 2020-05-22 02:04
Try to run with just
```
{
   "compilerOptions": {
       "experimentalDecorators": true
   }
}
```
in your tsconfig.json and run with these settings: 
```
run -c tsconfig.json mod.ts
```
![Screenshot_1](https://user-images.githubusercontent.com/20958849/82623778-5c6a1d00-9bb7-11ea-9204-5d611668d2b1.png)

**Comment by mtwzim** [comment] 2020-05-22 10:53
> Try to run with just
> 
> ```
> {
>    "compilerOptions": {
>        "experimentalDecorators": true
>    }
> }
> ```
> 
> in your tsconfig.json and run with these settings:
> 
> ```
> run -c tsconfig.json mod.ts
> ```
> 
> ![Screenshot_1](https://user-images.githubusercontent.com/20958849/82623778-5c6a1d00-9bb7-11ea-9204-5d611668d2b1.png)

Thank you, your answer is working.
But not in version v1.0.1, I had to downgrade to v.1.0.0 with: $ deno upgrade --version 1.0.0
The same code does not work in both versions, is it a bug?

**Comment by bartlomieju** [comment] 2020-05-22 11:01
@mtwzim thanks for the report I can repeat the problem; I'll look into it.

**Comment by lucacasonato** [comment] 2020-05-22 11:06
Duplicate of #5715, but this is the better report I guess.

**Closed** 2020-05-22 17:23 UTC
Labels: bug
