### ISSUE TITLE
about native apps

### ISSUE THREAD

**Issue by saroamirkhanyan** [denoland/deno#7955] opened 2020-10-13 08:51 UTC
I'm interested, in the future it will be possible to create a native app by deno ? - was without electron etc.

**Comment by David-Else** [comment] 2020-10-13 09:07
People have already started working on it :) https://github.com/webview/webview_deno

**Comment by kitsonk** [comment] 2020-10-13 09:40
Duplicate of #3234

**Closed by kitsonk** 2020-10-13 09:40 UTC
Labels: duplicate
