### ISSUE TITLE
extension-less shebang scripts should be interpreted as TypeScript by default

### ISSUE THREAD

**Issue by zhangyuannie** [denoland/deno#9063] opened 2021-01-09 05:08 UTC
From #929 and #1226, I believe that the intended behaviour is that extension-less shebang scripts are seen as TypeScript files, but that does not seems to be the case?

Minimal example:
```ts
#!/usr/bin/env -S deno run --allow-all
// filename: hi
interface Foo {
  bar: string;
}
console.log("Hi");
```

Running `./hi` or `deno run hi` yields ``error: Unexpected token `interface`.``

**Comment by caspervonb** [comment] 2021-01-26 12:53
Duplicate of https://github.com/denoland/deno/issues/5088

**Comment by zhangyuannie** [comment] 2021-01-26 17:31
> Duplicate of #5088

Thank you. Sorry for being unclear.

I guess it is more about the default behaviour here: extension-less shebang scripts should be interpreted as TypeScript by default instead of JavaScript.

I'm fine closing this if we don't wish to change that.

**Comment by kitsonk** [comment] 2021-01-27 00:45
I believe #5088 is a better solution/suggestion.  Ideally we want to treat JavaScript and TypeScript equally.  Technically it isn't a duplicate.  I don't think we would consider this suggestion though as it would have significant breaking changes.  We interpret TypeScript in strict mode, this means a lot of plain JavaScript would simply error out, which would be a bad experience for those already taking advantage of the feature.

**Closed** 2021-01-27 00:47 UTC
Labels: cli, suggestion
