### ISSUE TITLE
npm:table fails because of duplicate '__esModule'

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#15768] opened 2022-09-05 00:02 UTC
```ts
await import("npm:table");
```

```
error: Uncaught (in promise) SyntaxError: Identifier '__esModule' has already been declared
```

**Comment by dsherret** [comment] 2022-09-05 02:54
Did you try the latest version and search for past issues?

**Comment by dsherret** [comment] 2022-09-05 02:56
Duplicate of #15618 and already fixed in latest release.

**Closed by dsherret** 2022-09-05 02:56 UTC
Labels: duplicate, node compat
