### ISSUE TITLE
`deno check` fails to read package.json `./*` export mappings

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#20513] opened 2023-09-15 11:55 UTC
It looks like the `deno check` command isn't able to deal with wildcard mappings in `package.json#exports`.

```sh
# (formatted for readability)
error: Uncaught Error: Failed resolving package config for 'npm:puppeteer@20.8.3/install.js':
  [ERR_INVALID_PACKAGE_TARGET] Invalid "exports" target {"import":"./*","require":"./*"} defined for './*' in the package config
   /Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/puppeteer/20.8.3/package.json imported from
   file:///Users/marvinh/Library/Caches/deno/npm/registry.npmjs.org/puppeteer/20.8.3/; target must start with "./"
```

## Steps to reproduce

1. Create a file `foo.ts` with the following content:
  ```ts
  import * as install from "npm:puppeteer/install.js";
  console.log(install);
  ```
2. Run `deno check -A foo.ts`

**Comment by zhmushan** [comment] 2023-09-19 02:35
https://github.com/denoland/deno/blob/b9b4ad31d991bdbc50ddaea8d423a5d285d5f317/ext/node/resolution.rs#L836-L840

The resolution process has got the JS file path, but for the purpose of type checking, it attempts to locate the corresponding d.ts file.
Perhaps we can consider degrading it to the original file path when the d.ts file does not exist?

**Comment by tv42** [comment] 2023-10-25 19:33
This might be duplicate of #19666.

**Comment by bartlomieju** [comment] 2024-12-06 02:04
Works fine in Deno 2.1.2 👍

**Closed by bartlomieju** 2024-12-06 02:04 UTC
Labels: bug, important for fresh
