### ISSUE TITLE
'cargo install deno' still fails with compilation errors

### ISSUE THREAD

**Issue by liborty** [denoland/deno#7261] opened 2020-08-30 00:28 UTC
after failing to install 1.3.1 it still seems to be going back to that failed version.
Trying explicit --version fails also with:
```
$ cargo install deno --version 1.3.2 
    Updating crates.io index
error: could not find `deno` in registry `https://github.com/rust-lang/crates.io-index` with version `=1.3.2`
```

**Comment by liborty** [comment] 2020-08-30 00:34
```
$ cargo -V
cargo 1.46.0 (149022b1d 2020-07-17)
$ rustc -V
rustc 1.46.0 (04488afe3 2020-08-24)
```

**Comment by liborty** [comment] 2020-08-30 00:39
Same compilation errors as per #7260

**Comment by liborty** [comment] 2020-08-30 00:45
```
l:~$ cargo install deno
    Updating crates.io index
  Installing deno v1.3.1
   Compiling libc v0.2.76
   Compiling proc-macro2 v1.0.19
   Compiling unicode-xid v0.2.1
   Compiling syn v1.0.39
   Compiling cfg-if v0.1.10
   Compiling memchr v2.3.3
   Compiling lazy_static v1.4.0
   Compiling log v0.4.11
   Compiling autocfg v1.0.1
   Compiling once_cell v1.4.1
   Compiling fnv v1.0.7
   Compiling serde_derive v1.0.115
   Compiling serde v1.0.115
   Compiling getrandom v0.1.14
   Compiling itoa v0.4.6
   Compiling ppv-lite86 v0.2.9
   Compiling byteorder v1.3.4
   Compiling regex-syntax v0.6.18
   Compiling ryu v1.0.5
   Compiling bitflags v1.2.1
   Compiling siphasher v0.3.3
   Compiling strsim v0.9.3
   Compiling ident_case v1.0.1
   Compiling tinyvec v0.3.4
   Compiling unicode-width v0.1.8
   Compiling matches v0.1.8
   Compiling serde_json v1.0.57
   Compiling slab v0.4.2
   Compiling either v1.6.0
   Compiling scoped-tls v1.0.0
   Compiling percent-encoding v2.1.0
   Compiling stable_deref_trait v1.2.0
   Compiling new_debug_unreachable v1.0.4
   Compiling precomputed-hash v0.1.1
   Compiling futures-core v0.3.5
   Compiling version_check v0.9.2
   Compiling pin-project-internal v0.4.23
   Compiling bytes v0.5.6
   Compiling cc v1.0.59
   Compiling rand_core v0.4.2
   Compiling autocfg v0.1.7
   Compiling base64 v0.11.0
   Compiling proc-macro-nested v0.1.6
   Compiling futures-sink v0.3.5
   Compiling proc-macro-hack v0.5.18
   Compiling pin-utils v0.1.0
   Compiling futures-io v0.3.5
   Compiling smallvec v1.4.2
   Compiling lexical-core v0.7.4
   Compiling version_check v0.1.5
   Compiling arc-swap v0.4.7
   Compiling untrusted v0.7.1
   Compiling if_chain v1.0.0
   Compiling spin v0.5.2
   Compiling arrayvec v0.5.1
   Compiling pin-project-lite v0.1.7
   Compiling static_assertions v1.1.0
   Compiling typenum v1.12.0
   Compiling httparse v1.3.4
   Compiling siphasher v0.2.3
   Compiling cargo_gn v0.0.15
   Compiling byte-tools v0.3.1
   Compiling base64 v0.12.3
   Compiling proc-macro2 v0.4.30
   Compiling crc32fast v1.2.0
   Compiling alloc-no-stdlib v2.0.1
   Compiling fake-simd v0.1.2
   Compiling try-lock v0.2.3
   Compiling unicode-xid v0.1.0
   Compiling opaque-debug v0.2.3
   Compiling mime v0.3.16
   Compiling syn v0.15.44
   Compiling retain_mut v0.1.1
   Compiling downcast-rs v1.2.0
   Compiling tower-service v0.3.0
   Compiling adler v0.2.3
   Compiling encoding_rs v0.8.24
   Compiling safemem v0.3.3
   Compiling nix v0.17.0
   Compiling utf-8 v0.7.5
   Compiling dtoa v0.4.6
   Compiling remove_dir_all v0.5.3
   Compiling same-file v1.0.6
   Compiling lazycell v1.3.0
   Compiling quick-error v1.2.3
   Compiling void v1.0.2
   Compiling termcolor v1.1.0
   Compiling vec_map v0.8.2
   Compiling anymap v0.12.1
   Compiling ipnet v2.3.0
   Compiling ansi_term v0.11.0
   Compiling urlencoding v1.1.1
   Compiling utf8parse v0.2.0
   Compiling strsim v0.8.0
   Compiling unicode-segmentation v1.6.0
   Compiling dissimilar v1.0.2
   Compiling semver-parser v0.9.0
   Compiling thread_local v1.0.1
   Compiling tracing-core v0.1.15
   Compiling unicode-bidi v0.3.4
   Compiling owning_ref v0.4.1
   Compiling textwrap v0.11.0
   Compiling futures-task v0.3.5
   Compiling phf_shared v0.8.0
   Compiling futures-channel v0.3.5
   Compiling rand_core v0.3.1
   Compiling rand_jitter v0.1.4
   Compiling unicode-normalization v0.1.13
   Compiling block-padding v0.1.5
   Compiling http v0.2.1
   Compiling input_buffer v0.3.1
   Compiling alloc-stdlib v0.2.1
   Compiling miniz_oxide v0.4.1
   Compiling walkdir v2.3.1
   Compiling rand_isaac v0.1.1
   Compiling rand_hc v0.1.0
   Compiling rand_xorshift v0.1.1
   Compiling brotli-decompressor v2.3.1
   Compiling rand_chacha v0.1.1
   Compiling rand_pcg v0.1.2
   Compiling rand v0.6.5
   Compiling unicase v1.4.2
   Compiling hashbrown v0.8.2
   Compiling indexmap v1.5.1
   Compiling num-traits v0.2.12
   Compiling num-integer v0.1.43
   Compiling num-bigint v0.2.6
   Compiling crossbeam-utils v0.7.2
   Compiling tracing v0.1.19
   Compiling log v0.3.9
   Compiling want v0.3.0
   Compiling nom v5.1.2
   Compiling unicase v2.6.0
   Compiling aho-corasick v0.7.13
   Compiling twoway v0.1.8
   Compiling buf_redux v0.8.4
   Compiling fxhash v0.2.1
   Compiling quote v1.0.7
   Compiling quote v0.6.13
   Compiling mime v0.2.6
   Compiling idna v0.2.0
   Compiling phf_shared v0.7.24
   Compiling phf v0.7.24
   Compiling crossbeam-channel v0.4.3
   Compiling mime_guess v2.0.3
   Compiling url v2.1.1
   Compiling brotli v3.3.0
   Compiling regex v1.3.9
   Compiling http-body v0.3.1
   Compiling headers-core v0.2.0
   Compiling iovec v0.1.4
   Compiling net2 v0.2.34
   Compiling signal-hook-registry v1.2.1
   Compiling num_cpus v1.13.0
   Compiling rand_os v0.1.3
   Compiling time v0.1.44
   Compiling socket2 v0.3.12
   Compiling inotify-sys v0.1.3
   Compiling flate2 v1.0.17
   Compiling atty v0.2.14
   Compiling filetime v0.2.12
   Compiling utime v0.3.1
   Compiling generic-array v0.12.3
   Compiling ordered-float v1.1.0
   Compiling rand_core v0.5.1
   Compiling mio v0.6.22
   Compiling inotify v0.8.3
   Compiling clap v2.33.3
   Compiling Inflector v0.11.4
   Compiling block-buffer v0.7.3
   Compiling digest v0.8.1
   Compiling rand_chacha v0.2.2
   Compiling rand_pcg v0.2.1
   Compiling sha-1 v0.8.2
   Compiling headers v0.3.2
   Compiling rand v0.7.3
   Compiling mio-uds v0.6.8
   Compiling mio-extras v2.0.6
   Compiling phf_generator v0.7.24
   Compiling notify v5.0.0-pre.3
   Compiling ring v0.16.15
   Compiling sys-info v0.7.0
   Compiling phf_codegen v0.7.24
   Compiling phf_generator v0.8.0
   Compiling tungstenite v0.10.1
   Compiling tempfile v3.1.0
   Compiling uuid v0.8.1
   Compiling string_cache_codegen v0.5.1
   Compiling mime_guess v1.8.8
   Compiling pmutil v0.5.3
   Compiling darling_core v0.10.2
   Compiling swc_atoms v0.2.2
   Compiling swc_macros_common v0.3.1
   Compiling rustyline v6.2.0
   Compiling multipart v0.16.1
   Compiling async-compression v0.3.5
   Compiling dlopen_derive v0.1.4
   Compiling webpki v0.21.3
   Compiling sct v0.6.0
   Compiling dlopen v0.1.8
   Compiling rustls v0.18.1
   Compiling rustls v0.17.0
   Compiling webpki-roots v0.19.0
   Compiling darling_macro v0.10.2
   Compiling from_variant v0.1.2
   Compiling enum_kind v0.2.0
   Compiling is-macro v0.1.8
   Compiling string_enum v0.3.0
   Compiling futures-macro v0.3.5
   Compiling swc_visit_macros v0.1.1
   Compiling swc_visit_macros v0.2.0
   Compiling tokio-macros v0.2.5
   Compiling swc_ecma_parser_macros v0.4.1
   Compiling thiserror-impl v1.0.20
   Compiling swc_ecma_transforms_macros v0.1.0
   Compiling swc_ecma_codegen_macros v0.5.0
   Compiling tokio v0.2.22
   Compiling darling v0.10.2
   Compiling ast_node v0.7.0
   Compiling thiserror v1.0.20
   Compiling which v4.0.2
   Compiling rusty_v8 v0.8.1
   Compiling tokio-util v0.3.1
   Compiling tokio-rustls v0.14.0
   Compiling tokio-rustls v0.13.1
   Compiling swc_visit v0.2.0
   Compiling swc_visit v0.1.1
   Compiling pin-project v0.4.23
   Compiling futures-util v0.3.5
   Compiling tracing-futures v0.2.4
   Compiling futures-executor v0.3.5
   Compiling h2 v0.2.6
   Compiling futures v0.3.5
   Compiling tokio-tungstenite v0.10.1
   Compiling string_cache v0.8.0
   Compiling swc_common v0.10.0
   Compiling serde_urlencoded v0.6.1
   Compiling dprint-core v0.28.0
   Compiling jsdoc v0.4.0
   Compiling swc_ecma_ast v0.30.0
   Compiling sourcemap v6.0.1
   Compiling swc_common v0.9.1
   Compiling hyper v0.13.7
   Compiling swc_ecma_ast v0.28.0
   Compiling jsdoc v0.1.0
   Compiling hyper-rustls v0.21.0
   Compiling warp v0.2.4
   Compiling reqwest v0.10.8
   Compiling swc_ecma_visit v0.16.0
   Compiling swc_ecma_visit v0.13.0
   Compiling swc_ecma_codegen v0.31.0
   Compiling swc_ecma_parser v0.36.2
   Compiling swc_ecma_utils v0.20.0
error[E0599]: no method named `is_byte` found for type parameter `I` in the current scope
  --> /home/l/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.36.2/src/lexer/util.rs:66:20
   |
66 |         self.input.is_byte(c)
   |                    ^^^^^^^ method not found in `I`

error[E0599]: no method named `eat_byte` found for type parameter `I` in the current scope
  --> /home/l/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_parser-0.36.2/src/lexer/util.rs:70:20
   |
70 |         self.input.eat_byte(c)
   |                    ^^^^^^^^ method not found in `I`

   Compiling swc_ecma_utils v0.17.0
   Compiling swc_ecma_parser v0.33.3
error: aborting due to 2 previous errors

For more information about this error, try `rustc --explain E0599`.
error: could not compile `swc_ecma_parser`.

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.3.1`, intermediate artifacts can be found at `/tmp/cargo-installP7rAs9`

Caused by:
  build failed
```

**Comment by kitsonk** [comment] 2020-08-30 20:36
Duplicate of #7260

**Closed** 2020-08-31 09:48 UTC
