### ISSUE TITLE
deno compile + Worker + Blob URL dose not working

### ISSUE THREAD

**Issue by narumincho** [denoland/deno#23431] opened 2024-04-18 09:55 UTC
Version: Deno 1.42.4

```ts
// worker.ts

const blobUrl = URL.createObjectURL(
  new Blob(
    [
      `
onmessage = () => {
  postMessage("Hello from worker");
}
`,
    ],
    { type: "text/javascript" }
  )
);
const worker = new Worker(blobUrl, { type: "module" });

worker.onmessage = (e) => {
  console.log(e.data);
  worker.terminate();
};
worker.postMessage(undefined);
```

## deno run

```sh
deno run ./worker.ts
```

```
Hello from worker
```

## deno compile

```sh
deno compile ./worker.ts
./worker
```

```
error: Uncaught (in worker "") Module not found: blob:null/d75b07ad-f560-48f7-ad16-ec44df0eaca3
error: Uncaught (in promise) Error: Unhandled error in child worker.
    at Worker.#pollControl (ext:runtime/11_workers.js:204:19)
    at eventLoopTick (ext:core/01_core.js:168:7)
```

## workaround

As a workaround, using DataURL works.

```ts
import { encodeBase64 } from "jsr:@std/encoding/base64";

const dataUrl = `data:text/javascript;base64,${encodeBase64(
  `
onmessage = () => {
  postMessage("Hello from worker");
}
`
)}`;
const worker = new Worker(import.meta.resolve(dataUrl), {
  type: "module",
});

worker.onmessage = (e) => {
  console.log(e.data);
  worker.terminate();
};
worker.postMessage(undefined);
```

**Comment by lucacasonato** [comment] 2024-06-08 17:56
Duplicate of #18327

**Closed by lucacasonato** 2024-06-08 17:56 UTC
