### ISSUE TITLE
Proposal: std/crypto

### ISSUE THREAD

**Issue by ssslambda** [denoland/deno#8006] opened 2020-10-17 12:40 UTC
We already have [bcrypt](https://deno.land/x/bcrypt) and [argon2](https://deno.land/x/argon2) modules on /x, it would be nice to have them in std just like in golang, also i think both of them (and others too) can be implemented via wasm for better perfomance

**Comment by crowlKats** [comment] 2020-10-17 13:06
I think before we do a std/crypto we should first have webcrypto api implemented

**Comment by ssslambda** [comment] 2020-10-17 15:12
> I think before we do a std/crypto we should first have webcrypto api implemented

I don't see WebCrypto in Deno Q4 roadmap, but we need to have at least bcrypt right now, it is very popular and used to hash passwords (it is necessary for almost any Deno web server)

**Comment by timonson** [comment] 2020-10-17 15:21
I would like to add [god_crypto](https://github.com/invisal/god_crypto) as another third party module which tries to *use WebCrypto if available*.

**Comment by crowlKats** [comment] 2020-10-17 15:29
The problem is getting crypto stuff right is difficult, that is why we still dont have webcrpyto even tho it is quite important.  for that same reason, i think we should hold off having something like std/crypto.
Also, the two modules you linked are written in TS & as a plugin, respectively. neither of those 2 things is ideal. the right solution would be using WASM.

**Comment by ssslambda** [comment] 2020-10-17 15:33
> The problem is getting crypto stuff right is difficult, that is why we still dont have webcrpyto even tho it is quite important. for that same reason, i think we should hold off having something like std/crypto.
> Also, the two modules you linked are written in TS & as a plugin, respectively. neither of those 2 things is ideal. the right solution would be using WASM.

WASM is possible for both of them

**Comment by crowlKats** [comment] 2020-10-17 15:36
I know it is. but the main issue remains: we dont have someone knowledgeable about cryptography.
even if we'd have such a person, webcrypto would be a higher priority.

**Comment by kitsonk** [comment] 2020-10-18 09:03
The Q4 roadmap is the current priorities of the core team, it is not everything for Q4.

WebCrypto would be preferred over any `std`, so closing as a duplicate of #1891.

**Closed by kitsonk** 2020-10-18 09:03 UTC

**Comment by caspervonb** [comment] 2020-10-18 09:16
> I don't see WebCrypto in Deno Q4 roadmap

I *might* get to it.

**Comment by 89z** [comment] 2021-03-18 17:15
https://github.com/denoland/deno/issues/1891
https://github.com/denoland/deno/issues/2372
https://github.com/denoland/deno/issues/6712

https://github.com/denoland/deno/issues/8006
https://github.com/denoland/deno_std/issues/48

**Comment by halvardssm** [comment] 2024-05-05 07:51
Dont mean to reopen a dormant issue, but just wanted to chime in for future reference: 

@ssslambda I recently started a new project to extend Deno STD (it does not replace STD, but extends it). It encourages the addition of functionality that exists in other standard libraries (PHP, Go etc.), and also allows for functionality that benefits from being in a standard library rather than in third party modules. One example is the crypto package which provides Argon2 and Bcrypt, and other password hashes can be submitted by PR. Here is the link: https://jsr.io/@stdext/crypto
