### ISSUE TITLE
Improve serde_v8 deserialization errors

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10064] opened 2021-04-08 00:04 UTC
```
> Deno.listenTls({})
Uncaught TypeError: Error parsing args: serde_v8 error: ExpectedString
    at processErr (deno:core/core.js:107:12)
    at processResponse (deno:core/core.js:91:11)
    at Object.jsonOpSync (deno:core/core.js:119:12)
    at opListenTls (deno:runtime/js/40_tls.js:19:17)
    at Object.listenTls (deno:runtime/js/40_tls.js:56:17)
    at <anonymous>:2:6
```

This error should include the field name, and generally look more like `serde_json` errors.

**Comment by zaoying** [comment] 2021-05-19 03:49
I met the same issue. What is the progress ? Why this error come up in the first place ?

**Comment by sam-parsons** [comment] 2021-07-01 03:10
I'm using `Deno.listenDatagram()` and getting the same issue.

**Comment by zaoying** [comment] 2021-07-05 09:47
I have solved this problem. never mind.

**Comment by martin-braun** [comment] 2022-03-10 02:45
@zaoying You should always share your solution so others who have the same problem can benefit from that, thank you.

**Comment by zaoying** [comment] 2022-03-12 11:55
Actually I had done nothing useful to solved this problem, all I do just upgrade deno then it's solved. 
Sorry if I had not doing anything helping people

**Comment by martin-braun** [comment] 2022-03-12 15:21
@zaoying Thanks for your response 👍🏻

**Comment by 0x1af2aec8f957** [comment] 2022-08-08 07:23
Same mistake:
```bash
error: Uncaught TypeError: Error parsing args at position 0: serde_v8 error: ExpectedString
Deno.listenTls({ port: 443, hostname: 'localhost', cert: options.cert, key: options.key })
         ^
        at Object.opSync (deno:core/01_core.js:171:38)
        at opListenTls (deno:ext/net/02_tls.js:19:17)
        at Object.listenTls (deno:ext/net/02_tls.js:76:17)
        at file:///@workDir/app.ts:16:6
```

**Comment by magurotuna** [comment] 2022-08-08 09:40
@0x1af2aec8f957 Which version of Deno do you use?

**Comment by crowlKats** [comment] 2023-01-09 03:36
Tested on latest and this seem to have been addressed, so closing.

**Closed by crowlKats** 2023-01-09 03:36 UTC
Labels: refactor, l-rust, serde_v8

**Comment by josephrocca** [comment] 2023-07-17 06:00
In case someone gets the same problem and hits this issue via Google like I did - when upgrading from Deno `1.34.3` to `1.35.x`, I got this:

```
 error: Uncaught TypeError: Error parsing args at position 0: serde_v8 error: invalid type; expected: integer, got: string
  const listener = Deno.listen({
                        ^
    at Object.listen (ext:deno_net/01_net.js:421:39)
    at serve (https://deno.land/std@0.194.0/http/server.ts:604:25)
```
And the problem seems to have been that Deno `1.34.3` (and earlier versions) would allow `serve` to accept a string as a `port`, like this:
```js
import { serve } from "https://deno.land/std@0.194.0/http/server.ts";
await serve(async request => {
  // ...
}, {port: Deno.env.get("PORT")});
```

I had to cast the `PORT` env variable to a number like this: `{port: Number(Deno.env.get("PORT"))}` and that fixed it.

Pinging @crowlKats just in case this was an unintended breaking change - please ignore if this was intended.

**Comment by bartlomieju** [comment] 2023-07-17 22:22
Thanks for the report @josephrocca, this is indeed unintended break that we will fix. I believe that typechecking the code would catch the problem, but we'll see how we can work around it.

**Comment by abecciu** [comment] 2023-07-20 05:28
Got another instance of this bug. See error below:

```
error: Uncaught (in promise) TypeError: Error parsing args at position 1: serde_v8 error: invalid type; expected: integer, got: undefined
    at IncomingMessageForClient._read (node:http:734:14)
    at IncomingMessageForClient.Readable.read (ext:deno_node/_stream.mjs:2997:16)
    at resume_ (ext:deno_node/_stream.mjs:3347:16)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:33:29)
    at runNextTicks (ext:deno_node/_next_tick.ts:71:5)
    at eventLoopTick (ext:core/01_core.js:189:21)
 ```
 
 I'm running:
 ```
 deno 1.35.1 (release, aarch64-apple-darwin)
v8 11.6.189.7
typescript 5.1.6
```


This occurred while using the nodejs library got (https://www.npmjs.com/package/got) to perform http requests.

**Comment by bartlomieju** [comment] 2023-07-23 12:24
So I took a look at this and the only thing we can do is actually upgrade the `deno_std/http/server.ts` module as well as our internal `node:http` polyfill to handle this better.
