### ISSUE TITLE
socket performance in 1.34.x

### ISSUE THREAD

**Issue by aricart** [denoland/deno#19348] opened 2023-06-01 22:12 UTC
I am finding that performance in my application drops tremendously doing socket i/o - this was not the case with 1.33.x or earlier. Also tracking that elusive stack size exceeded issue. Fairly certain there's no extra timers or recursion, but still digging. The stack trace as is is not very useful - and only shows a line number on the exact 612000 iteration of the application.
```
error: Uncaught RangeError: Maximum call stack size exceeded
    at eventLoopTick (ext:core/01_core.js:173:23)
```

```bash

# 1.34.1 - test takes 33 seconds

> ~/D/c/s/g/n/nats.deno (deno-transport-changes)> deno upgrade
Looking up latest version
Local deno version 1.34.1 is the most recent release
> ~/D/c/s/g/n/nats.deno (deno-transport-changes)> deno run --reload -A examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 18,127 msgs/sec - [33.10 secs] ~ 60.51 MB/sec 33099.310713/33099.310713
                                                               ^^^^^
# 1.34.0 takes 33.96 seconds
> ~/D/c/s/g/n/nats.deno (deno-transport-changes)> deno upgrade --version 1.34.0
Downloading https://github.com/denoland/deno/releases/download/v1.34.0/deno-x86_64-apple-darwin.zip
Deno is upgrading to version 1.34.0
Archive:  /var/folders/1y/_rk6yz81341g5q8k1vr5nqmw0000gq/T/.tmpPuhtAQ/deno.zip
  inflating: deno                    
Upgraded successfully
> ~/D/c/s/g/n/nats.deno (deno-transport-changes)> 
> ~/D/c/s/g/n/nats.deno (deno-transport-changes)> deno run --reload -A examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 17,666 msgs/sec - [33.96 secs] ~ 58.96 MB/sec 33964.489852/33964.489852
                                                              ^^^^^^^

# 1.33.0 takes 5.6 seconds
> ~/D/c/s/g/n/nats.deno (deno-transport-changes)> deno upgrade --version 1.33.0
Downloading https://github.com/denoland/deno/releases/download/v1.33.0/deno-x86_64-apple-darwin.zip
Deno is upgrading to version 1.33.0
Archive:  /var/folders/1y/_rk6yz81341g5q8k1vr5nqmw0000gq/T/.tmplCZD38/deno.zip
  inflating: deno                    
Upgraded successfully
Release notes: https://github.com/denoland/deno/releases/tag/v1.33.0
Blog post: https://deno.com/blog/v1.33
> ~/D/c/s/g/n/nats.deno (deno-transport-changes)> deno run --reload -A examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 106,286 msgs/sec - [5.65 secs] ~ 354.77 MB/sec 5645.142427000001/5645.142427000001
                                                                 ^^^^^^^
```

**Comment by bartlomieju** [comment] 2023-06-02 05:10
Do you see such a regression in v1.33.5? We haven't really changed much in Websocket implementation between v1.33.5 and v1.34.0. The major difference is V8 version upgrade, but it would be surprising if it had impact.

Could you share a reproduction code?

**Comment by aricart** [comment] 2023-06-02 12:04
@bartlomieju I think you meant 1.33.4 - it works fine there. - Note the application is just TCP socket
```
 deno upgrade --version 1.33.4
Downloading https://github.com/denoland/deno/releases/download/v1.33.4/deno-x86_64-apple-darwin.zip
Deno is upgrading to version 1.33.4
Archive:  /var/folders/1y/_rk6yz81341g5q8k1vr5nqmw0000gq/T/.tmp76Fikb/deno.zip
  inflating: deno                    
Upgraded successfully
Release notes: https://github.com/denoland/deno/releases/tag/v1.33.4
Blog post: https://deno.com/blog/v1.33
synadia@malaga ~/D/c/s/g/n/nats.deno (deno-transport-changes)> deno run --reload -A examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 104,408 msgs/sec - [5.75 secs] ~ 348.50 MB/sec 5746.708397/5746.708397
```

**Comment by aricart** [comment] 2023-06-02 12:15
If you want to try, you'll need to download a nats-server:
(https://github.com/nats-io/nats.deno/tree/deno-transport-changes)
```
brew install nats-server (github.com/nats-io/nats-server)
nats-server &
deno run --reload -A https://raw.githubusercontent.com/nats-io/nats.deno/deno-transport-changes/examples/ben
ch.js --subject a --payload 3500 --pub --count 600000
```

Note that using any number 612000 for --count, will also trigger a:
```
error: Uncaught RangeError: Maximum call stack size exceeded
    at eventLoopTick (ext:core/01_core.js:172:23)
```
However fairly sure that there are no timer leaks on this version, but still doing the due diligence - I cannot run it under 1.19   because of a typescript compilation `TS2322 [ERROR]: Type 'AliasNames<TArgName, TAliases>' is not assignable to type 'string | number | symbol'.` possibly from something in std or one of my types (the code is on std@0.177.0)

**Comment by bartlomieju** [comment] 2023-06-04 18:56
Thanks! We'll look into that, it's always very useful to have these kinds of problems reported 🙏

**Comment by bartlomieju** [comment] 2023-06-09 11:36
@aricart would you mind trying with v1.34.2 and letting me know if that fixes your problem?

**Comment by aricart** [comment] 2023-06-09 13:31
@bartlomieju unfortunately it actually seems much worse!
```bash
# 1.33.x
> deno --version
deno 1.33.4 (release, x86_64-apple-darwin)
v8 11.4.183.2
typescript 5.0.4

> deno run --reload -A https://raw.githubusercontent.com/nats-io/nats.deno/deno-transport-changes/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 107,157 msgs/sec - [5.60 secs] ~ 357.68 MB/sec 5599.246615/5599.246615
^^^^^^^^^^^^^^^^^^^^^^^^^^^^

# 1.34.2
> deno upgrade
Looking up latest version
Found latest version 1.34.2
Downloading https://github.com/denoland/deno/releases/download/v1.34.2/deno-x86_64-apple-darwin.zip
Deno is upgrading to version 1.34.2
Archive:  /var/folders/1y/_rk6yz81341g5q8k1vr5nqmw0000gq/T/.tmpyfVbRn/deno.zip
  inflating: deno                    
Upgraded successfully
Release notes: https://github.com/denoland/deno/releases/tag/v1.34.2
Blog post: https://deno.com/blog/v1.34

> deno run --reload -A https://raw.githubusercontent.com/nats-io/nats.deno/deno-transport-changes/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 6,775 msgs/sec - [88.56 secs] ~ 22.61 MB/sec 88562.758474/88562.758474
^^^^^^^^^^^^^^^^^^^^^^^^^^

# 1.34.1
> deno upgrade --version 1.34.1
Downloading https://github.com/denoland/deno/releases/download/v1.34.1/deno-x86_64-apple-darwin.zip
Deno is upgrading to version 1.34.1
Archive:  /var/folders/1y/_rk6yz81341g5q8k1vr5nqmw0000gq/T/.tmpbTtnV9/deno.zip
  inflating: deno                    
Upgraded successfully

> deno run --reload -A https://raw.githubusercontent.com/nats-io/nats.deno/deno-transport-changes/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 16,873 msgs/sec - [35.56 secs] ~ 56.32 MB/sec 35560.456011/35560.456011
^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

**Comment by bartlomieju** [comment] 2023-06-09 13:44
That's really strange, our own benchmarks shows increase in msg/s in Websocket benchmarks. We'll have to dig into your reproduction code to see what's going on.

**Comment by aricart** [comment] 2023-06-09 14:20
@bartlomieju this is tcp socket.

**Comment by aricart** [comment] 2023-06-09 14:21
@caspervonb may possibly have some idea

**Comment by bartlomieju** [comment] 2023-06-09 15:17
> @bartlomieju this is tcp socket.

Ah, sorry for confusion. We'll investigate in the coming days and get back to you.

**Comment by bartlomieju** [comment] 2023-06-11 11:36
@aricart I just did some profiling of your provided example and I see that 99% of time is spent in JavaScript. It appears that the bulk of the time is actually spent handling timers (essentially almost all the time is spent iterating over scheduled timers and looking if there's a timer to resolve). 

Could you give me a hand here and tell if you by any chance a lot of timers and these timers use `0ms` timeout?

**Comment by marvinhagemeister** [comment] 2023-06-11 13:10
From what I can tell looking at the trace all timers seem to come from these two locations:

- https://github.com/nats-io/nats.deno/blob/37d009aad3753fe417ad2150d348384a8e985377/nats-base-client/protocol.ts#L609-L611
- https://github.com/nats-io/nats.deno/blob/37d009aad3753fe417ad2150d348384a8e985377/nats-base-client/util.ts#L159-L161

**Comment by aricart** [comment] 2023-06-11 15:56
Correct - they are with no argument assuming min (next event loop) - but there's one thing to keep in mind - in the code you are running (the bench) the event loop is dominated by a for loop, which will schedule one timer on the first write to flush to a socket, but will continue adding data to it - at some point the buffer will have reached some size, and the code will inline a flush - discarding the schedule timer and creating a new one before it ever executes, On the next write the same process will repeat. 

If the socket has not yet finished writing, the buffer is appended, and the call returns - this is a side issue that the socket writing cannot be schedule, and creates a burden because instead of allowing the socket to handle the writes,  user code has to queue them for it - if not queued, the socket will interleave writes, which has zero use - had a lot of fun chats with @caspervonb on this :)

The timer is a misdirection.

If you repeat the same test with the dev branch which actually creates many less promises - you'll still notice that 1.34 has exactly the same issue, I can also do a simple fix, where I don't even cancel the next timer, and instead ignore it - let me try that as that may provide some boost somewhere.
```
deno run --reload -A https://raw.githubusercontent.com/nats-io/nats.deno/dev/examples/bench.js --subject a --payload 3500 --pub --count 600000
```

I also tracked the `Uncaught RangeError: Maximum call stack size exceeded` - same loop issue depending on the outbound size, if you bump the count to `--count 1000000`, as buffers are appended for the socket to process (array.push(buf)) the range error will hit if it adds 100,000 entries in the buffer. Not quire sure why that array is allocated in the heap.

**Comment by aricart** [comment] 2023-06-11 16:01
hum - that one escaped me - let me fix that now

**Comment by aricart** [comment] 2023-06-11 16:17
Nope - I read the code wrong - the message I hastly deleted is correct:

https://github.com/nats-io/nats.deno/blob/ca8e13d92bee8f69df1c26cd8a5f94560a12c45f/nats-base-client/protocol.ts#L838

For each pending buffer created there will be a timer created (and cancelled) in the bench that you are executing - never will there be more than one timer active. The reason being that at some point my code decides that it has buffered too much and it simply inlines the flush call - sending everything that it collected to the transport (deno socket code)- the transport may further delay writing, but the point is that when it inlines (the bench is in a for loop that dominates the event loop so the timer in questing is never going to trigger:

instrumenting for sanity, you can see the actual runtime behaviour.
```
creating timer
inline timer
timer cancelled
creating timer
inline timer
timer cancelled
creating timer
inline timer
timer cancelled
creating timer
inline timer
timer cancelled
creating timer
inline timer
timer cancelled
creating timer
inline timer
timer cancelled
creating timer
```

So there should be some hotness in timer cancels and creations, but most will be cancelled.

**Comment by aricart** [comment] 2023-06-11 16:25
Please try this version which is more optimal (the slow down is still there)

deno run -A --reload https://raw.githubusercontent.com/nats-io/nats.deno/dev/examples/bench.js --subject a --payload 3500 --pub --count 600000

As a side, note that on the other side on the transport if you bump the count higher says 612,000 or something that causes an array push to get to 100K elements, `error: Uncaught RangeError: Maximum call stack size exceeded` will happen. Not sure why V8 is putting this:
https://github.com/nats-io/nats.deno/blob/ca8e13d92bee8f69df1c26cd8a5f94560a12c45f/src/deno_transport.ts#L205

on the heap.

**Comment by bartlomieju** [comment] 2023-06-11 21:12
Thanks @aricart, we'll get to the bottom of it. I believe the problem is actually on the Deno side - we changed out timer implementation for very short timers around the time you started having troubles. I think there is a bug lurking there somehow. We'll debug and get back to you. (and sorry for the troubles!)

**Comment by bartlomieju** [comment] 2023-06-11 22:40
@aricart I think I indentified the problematic bit, however applying a fix causes the benches never to finish (after a few seconds the event loop just stalls and nothing is happening). I will have to dig into it a bit more.

**Comment by bartlomieju** [comment] 2023-06-11 23:34
Okay, I found the problem, we are hitting nested loop when resolving timers. We need to rewrite some bits of code in `02_timers.js` to be smarter how we handle multiple timers that are scheduled for the same instant. Will look into fixing that and releasing in v1.34.3. @marvinhagemeister is it something you could help me with?

**Closed** 2023-06-14 15:04 UTC
Labels: perf

**Comment by bartlomieju** [comment] 2023-06-14 15:56
@aricart we'll release fix to this problem in v1.34.3 tomorrow. Sorry for the trouble

**Comment by aricart** [comment] 2023-06-14 15:57
Glad to be of help!

**Comment by bartlomieju** [comment] 2023-06-16 00:06
@aricart v1.34.3 is now published, let me know how number look on your side!

**Comment by aricart** [comment] 2023-06-16 00:45
@bartlomieju the performance is slightly worse, but in line!!! Thank you!
```bash
> deno upgrade
Looking up latest version
Found latest version 1.34.3
Downloading https://github.com/denoland/deno/releases/download/v1.34.3/deno-x86_64-apple-darwin.zip
Deno is upgrading to version 1.34.3
Archive:  /var/folders/1y/_rk6yz81341g5q8k1vr5nqmw0000gq/T/.tmpOBGdCI/deno.zip
  inflating: deno                    
Upgraded successfully
Release notes: https://github.com/denoland/deno/releases/tag/v1.34.3
Blog post: https://deno.com/blog/v1.34
> deno run -A --reload https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 103,006 msgs/sec - [5.82 secs] ~ 343.82 MB/sec 5824.904294/5824.904294
> deno run -A --reload https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 105,333 msgs/sec - [5.70 secs] ~ 351.59 MB/sec 5696.2324960000005/5696.2324960000005
> deno run -A --reload https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 102,741 msgs/sec - [5.84 secs] ~ 342.93 MB/sec 5839.934848/5839.934848
> deno run -A --reload https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 104,536 msgs/sec - [5.74 secs] ~ 348.93 MB/sec 5739.623057/5739.623057


> deno upgrade --version 1.33.4
Downloading https://github.com/denoland/deno/releases/download/v1.33.4/deno-x86_64-apple-darwin.zip
Deno is upgrading to version 1.33.4
Archive:  /var/folders/1y/_rk6yz81341g5q8k1vr5nqmw0000gq/T/.tmpv08t7Z/deno.zip
  inflating: deno                    
Upgraded successfully
Release notes: https://github.com/denoland/deno/releases/tag/v1.33.4
Blog post: https://deno.com/blog/v1.33
> deno run -A --reload https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 112,854 msgs/sec - [5.32 secs] ~ 376.69 MB/sec 5316.6160709999995/5316.6160709999995
> deno run -A --reload https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 111,753 msgs/sec - [5.37 secs] ~ 373.02 MB/sec 5368.967229000001/5368.967229000001
> deno run -A --reload https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/bench.js --subject a --payload 3500 --pub --count 600000
pub 110,552 msgs/sec - [5.43 secs] ~ 369.01 MB/sec 5427.292727/5427.292727
```

**Comment by bartlomieju** [comment] 2023-06-16 00:47
Huh, that's not great. I can get some flamegraphs done and see what's going on between the two versions.

**Comment by aricart** [comment] 2023-06-16 00:49
Note that I released a new version so you can use the main branch as I am showing on the latest one.
(I also need to run it on node and see how far that falls)

**Comment by bartlomieju** [comment] 2023-06-16 15:49
Running some profiles on macOS with M1 Max I get these:

Deno v1.34.3
https://share.firefox.dev/42Fb0q1
```
deno run -A https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/bench.js --subject a --payload 3500 --pub --count 500000
pub 215,908 msgs/sec - [2.32 secs] ~ 720.67 MB/sec 2315.796166/2315.796166
```

Deno v1.33.4
https://share.firefox.dev/3qEo6Gw
```
deno run -A https://raw.githubusercontent.com/nats-io/nats.deno/main/examples/bench.js --subject a --payload 3500 --pub --count 500000
pub 215,304 msgs/sec - [2.32 secs] ~ 718.66 MB/sec 2322.2940000000003/2322.2940000000003
```

@aricart FYI it appears that half of the whole benchmark time is spent in `Array.shift()` - sounds like something that could potentially be optimized.

**Comment by aricart** [comment] 2023-06-16 16:12
the M1 seems to have more stable results - I am running on intel xeons - I think it is still within the acceptable. One thing though is that on the same machine node is about 10% faster, the transport implementation is different, but the rest is the same exact library.

**Comment by bartlomieju** [comment] 2023-06-16 16:49
> the M1 seems to have more stable results - I am running on intel xeons - I think it is still within the acceptable. One thing though is that on the same machine node is about 10% faster, the transport implementation is different, but the rest is the same exact library.

Interesting. Any chance you could provide some flamegraphs? I'm a bit strapped on time to investigate it myself, but should be way easier with existing flamegraph. (I used https://github.com/mstange/samply/ to generate the above graphs)
