### ISSUE TITLE
Question/Feature-Request: Way to Track Async Context and/or Promise Creation 

### ISSUE THREAD

**Issue by astorm** [denoland/deno#6449] opened 2020-06-23 22:46 UTC
My apologies if this is the wrong venue. It wasn't clear from the contributors guidelines whether issues are a suitable place for questions/feature-requests, and when I asked via [the community chat room](https://discordapp.com/channels/684898665143206084/689420767620104201/725083870164287540) and the [usual places](https://stackoverflow.com/questions/62544235/does-deno-have-a-way-to-track-async-contexts) I didn't get much engagement. 

Does Deno have a supported-or-experimental way to track the creation of asynchronous contexts? I [see async_hooks](https://github.com/denoland/deno/issues/945) isn't something you'll be implementing -- at least until [Node lands a non-experimental version of it](https://github.com/denoland/deno/blob/d16337cc9c59732fe81655482e08b72d844472e6/std/node/README.md). 

The specific use-case I have in mind is [an OpenTelementry context manager](https://www.npmjs.com/package/@opentelemetry/context-async-hooks), but I'm also thinking of other Application Performance Monitoring use-cases where we're trying to tie multiple asynchronous actions to a single scope (scope meaning a single HTTP request, or a single GRPC method invocation, etc.)

Also, FWIW, the usual cowboy way APM vendors would handle this doesn't look like it's possible in Deno -- redefining the global `Promise` doesn't carry over when you `import` other modules. Probably "the right" behavior, but it does seem to make our usual monkey patching not possible. 

Is this something that's on the roadmap and/or people's minds? "No" is a perfectly acceptable answer, I'm just trying to get the lay of the land before I go down one particular road or the other.

**Comment by kitsonk** [comment] 2020-06-23 23:33
Duplicate of #5638

Currently, not really.  Yes, my opinion is it is a consideration.  I just don't think it has been a priority yet.  We should consolidate thoughts in #5638 though.

**Comment by astorm** [comment] 2020-06-23 23:58
thank you @kitsonk

**Closed** 2020-06-23 23:57 UTC
