### ISSUE TITLE
crypto api stopped working in v1.17.x

### ISSUE THREAD

**Issue by ralyodio** [denoland/deno#13222] opened 2021-12-29 06:49 UTC
```
error: Uncaught (in promise) DataError: invalid key data
const key = await crypto.subtle.importKey(
                                ^
    at Object.opSync (deno:core/01_core.js:149:12)
    at importKeyHMAC (deno:ext/crypto/00_crypto.js:2055:34)
    at SubtleCrypto.importKey (deno:ext/crypto/00_crypto.js:793:18)
```

**Comment by bnoordhuis** [comment] 2021-12-29 11:21
Can you post a minimal test case?

**Comment by ralyodio** [comment] 2021-12-30 03:17
```
const keyData = await Deno.readTextFile("jwk.json");

const key = await crypto.subtle.importKey(
  "jwk",
  JSON.parse(keyData),
  { name: "HMAC", hash: "SHA-512" },
  true,
  ["sign", "verify"],
);
```

here is the key file:

```
{
  "kty": "oct",
  "k": "xxx",
  "alg": "HS512",
  "key_ops": ["sign", "verify"],
  "ext": true
}
```

**Comment by littledivy** [comment] 2021-12-31 04:33
@ralyodio Just to make sure `xxx` is the actual key material and not a placeholder value?

**Comment by littledivy** [comment] 2022-01-03 12:29
Fixed in https://github.com/denoland/deno/pull/13240

**Comment by ralyodio** [comment] 2022-01-05 05:59
i tried this on canary and it still is broken:

deno 1.17.1+19c8cd3

**Comment by littledivy** [comment] 2022-01-05 06:04
@ralyodio I can't reproduce the issue on the same canary version.

![Screenshot from 2022-01-05 11-32-34](https://user-images.githubusercontent.com/34997667/148168235-284053db-3fc3-4201-bacb-2720d6f33d90.png)

Please verify the key material `k` is exacly what you are using

**Comment by ralyodio** [comment] 2022-01-05 06:36
This is not the full key, but I've removefd some characters. It has +'s in it, is that the issue?

It worked fine in 1.16

```
{
  "kty": "oct",
  "k": "dtPQIio1j0Sf6vmPOSa2sPwA8DlR3jUuMK3nlL44laPn+8EiYTxj9DTu5JdkoEGfmfnhgTFg6TqnT7+y8zV4gQJEsRRIhLwEMZGtRptqZTxRoUYnODn8IkjF9f6SW7oT+ijTTolQPYUxvaEqw",
  "alg": "HS512",
  "key_ops": ["sign", "verify"],
  "ext": true
}
```

**Comment by littledivy** [comment] 2022-01-05 06:44
@ralyodio That is not a valid base64 URL encoded key. ImportKey operation fails on Firefox and Chrome as well. It is a bug in the software that generated that key.

**Comment by SeanWykes** [comment] 2022-01-05 19:23
> @ralyodio That is not a valid base64 URL encoded key. ImportKey operation fails on Firefox and Chrome as well. It is a bug in the software that generated that key.

@ralyodio base64url for JWK must use `-` and `_` characters, see [here](https://base64.guru/standards/base64url), and no padding. Even so, your key is invalid as @littledivy stated. You can use something like [cryptii](https://cryptii.com/pipes/base64-to-hex) to check your data, just select `base64url` in the middle block.

**Comment by ralyodio** [comment] 2022-01-19 21:41
How is it invalid? It worked fine for months before upgrading deno?

**Comment by kitsonk** [comment] 2022-01-19 21:54
It isn't invalid, it is working as designed.  Previous of versions of Deno allowed keys that were invalid per the spec.  If you try to run your code in Chrome, you will get:

> Uncaught DOMException: The JWK member "k" could not be base64url decoded or contained padding

Ensuring keys are valid is a fix and makes Deno more spec compliant.  Deno prior to 1.17 should have never accepted the invalid keys, but did.

**Closed by kitsonk** 2022-01-19 21:54 UTC
Labels: working as designed, ext/crypto

**Comment by ralyodio** [comment] 2022-01-25 01:06
Ok, so I tried with a new key and it still doesn't work.

Here's my key generation script:

```
// deno run --allow-write generateKey.ts

const key = await crypto.subtle.generateKey(
  { name: "HMAC", hash: "SHA-512" },
  true,
  ["sign", "verify"],
);

const result = await crypto.subtle.exportKey("jwk", key);

await Deno.writeTextFile("./newKey.json", JSON.stringify(result));
console.log("New key written to ./newKey.json");
```

Here is the actual jwk.json file:
```
{
  "kty": "oct",
  "k": "kYyY+QNCzR/eM3K3BpxNVLzS30Ug7fXV8jb0x1sa3DiTt2C/4Zn1miDekpZxu7097H6NV4teGlrz0Q+lMOgzjytgBhmeB8ONWhewMqsSEzhtNgp5I7ofUtSGED/c6Jrs0IK5Ehnmn8rM5iv7z7Ihd2KT2nLPndsHj9s1zcQ9B/8",
  "alg": "HS512",
  "key_ops": [
    "sign",
    "verify"
  ],
  "ext": true
}
```

sitll not working. worked fine with 1.16

**Comment by cryptographix** [comment] 2022-01-25 01:30
@ralyodio - the JWK specifications determine base64url, BUT your key is NOT base64url, it is standard base64. 

You must change your key to base64url and try again.

Changes: 
1) Change + into -
2) Change / into _

then it will work.

**Comment by cryptographix** [comment] 2022-01-25 02:33
@ralyodio - your JWK must obey specification, it must use base64url, BUT it is standard base64. They are different.

You must replace characters in your jwk.json
1) Change + to -
2) Change / to _

Then the key will work.

Deno 1.18 will generate JWK correctly on export. Update to 1.18 if needed and regenerate your key.

**Comment by ralyodio** [comment] 2022-01-25 04:48
Ok thanks!
