### ISSUE TITLE
Deno install fails to import private repo when 'git+http' in path

### ISSUE THREAD

**Issue by und-miller** [denoland/deno#26274] opened 2024-10-15 15:49 UTC
Version: Deno 2.0.0

```
PS C:\Users\user.name\Source\project> deno install
error: Failed to install from package.json

Caused by:
    0: Invalid version requirement
    1: Unexpected character.
         git+https://oauth2:password@git.package-name.com/
         ~
PS C:\Users\user.name\Source\project> 
```

package.json
```json
{
  "name": "frontend",
  "version": "0.1.0",
  "scripts": {
    "dev": "astro dev",
    "start": "astro dev --host",
    "build": "astro build",
    "preview": "deno run --allow-net --allow-read --allow-env ./dist/server/entry.mjs",
    "astro": "astro"
  },
  "dependencies": {
    "@astrojs/check": "^0.9.4",
    "@deno/astro-adapter": "^0.1.3",
    "@fortawesome/fontawesome-free": "^6.6.0",
    "@popperjs/core": "^2.11.8",
    "astro": "^4.16.4",
    "http-status-codes": "^2.3.0",
    "ui-kit": "git+https://oauth2:password@git.package-name.com/package.git#8.0.0",
    "typescript": "^5.5.3"
  }
}

```

**Comment by lucacasonato** [comment] 2024-10-21 09:39
Duplicate of https://github.com/denoland/deno/issues/18557

**Closed by lucacasonato** 2024-10-21 09:39 UTC
Labels: bug, install
