### ISSUE TITLE
MongoDB Node.js Driver doesn't work when connecting to MongoDB Atlas from Deno

### ISSUE THREAD

**Issue by alexbevi** [denoland/deno#16633] opened 2022-11-14 20:09 UTC
Potentially related to issue #15824, but the [`mongodb`](https://www.npmjs.com/package/mongodb) driver cannot be used directly via Deno when targeting a [MongoDB Atlas](https://www.mongodb.com/atlas) cluster. This was reported at [NODE-4782](https://jira.mongodb.org/browse/NODE-4782) however it doesn't appear to be an issue with the Node driver itself.

```js
// file: main.ts
import { MongoClient } from "mongodb"

const URI = "mongodb+srv://user:pass@cluster0.abcde.mongodb.net/test"
const client = new MongoClient(URI)

async function main() {
  console.log('connecting')  
  await client.connect()  
  console.log('connected')
  const collection = client.db('test_db').collection('test_collection')
  await collection.deleteMany({})
  await collection.insertOne({ a: 2.3 })
  var results = await collection.count({ a: 2.3 })
  console.log(`found ${results}`)
  process.exit(1)
}

main()
```

For example, when running the preceding using `npx ts-node main.ts` the script will connect to Atlas, authenticate/authorize, clear the collection, insert a new doc and execute a count.

```
connecting
connected
found 1
```

To make this run with Deno the script was updated as follows:

```js
// file: main.ts
import { MongoClient } from 'npm:mongodb' // updated for Deno

const URI = "mongodb+srv://user:pass@cluster0.abcde.mongodb.net/test"
const client = new MongoClient(URI)

async function main() {
  console.log('connecting')  
  await client.connect()  
  console.log('connected')
  const collection = client.db('test_db').collection('test_collection')
  await collection.deleteMany({})
  await collection.insertOne({ a: 2.3 })
  var results = await collection.count({ a: 2.3 })
  console.log(`found ${results}`)
  process.exit(1)
}

main()
```

When the above script variation is run using `deno run --unstable --allow-all main.ts` it will fail with the following error as it doesn't appear to be able to resolve a [DNS Seed List Connection String](https://www.mongodb.com/docs/manual/reference/connection-string/#std-label-connections-dns-seedlist):

```
connecting
error: Uncaught MongoAPIError: Server record does not share hostname with parent URI
    at resolveSRVRecord (file:///Users/alex/Library/Caches/deno/npm/registry.npmjs.org/mongodb/4.11.0/lib/connection_string.js:62:19)
    at async file:///Users/alex/Library/Caches/deno/npm/registry.npmjs.org/mongodb/4.11.0/lib/mongo_client.js:120:31
    at async main (file:///Users/alex/temp/main.ts:17:3)
```

Changing the `URI` constant to use a [Standard Connection String](https://www.mongodb.com/docs/manual/reference/connection-string/#std-label-connections-standard-connection-string-format) of `mongodb://user:pass@cluster0-shard-00-00.abcde.mongodb.net:27017,cluster0-shard-00-01.abcde.mongodb.net:27017,cluster0-shard-00-02.abcde.mongodb.net:27017/test?ssl=true&replicaSet=Cluster0-shard-0&authSource=admin&retryWrites=true&w=majority` and re-running results in the operation just timing out:

```
connecting
error: Uncaught MongoServerSelectionError: connection timed out
    at Timeout.<anonymous> (file:///Users/alex/Library/Caches/deno/npm/registry.npmjs.org/mongodb/4.11.0/lib/sdam/topology.js:293:38)
    at https://deno.land/std@0.162.0/node/timers.ts:21:15
    at Object.action (deno:ext/web/02_timers.js:147:13)
    at handleTimerMacrotask (deno:ext/web/02_timers.js:64:12)
```

Note this was tested with:
```
deno 1.27.2 (release, x86_64-apple-darwin)
v8 10.8.168.4
typescript 4.8.3
```

### Steps to Reproduce

1. Sign up for a free M0 Atlas Cluster
2. Get a [Connection String](https://www.mongodb.com/docs/guides/atlas/connection-string/) (pick an older version of any driver to get the `mongodb://` version instead of `mongodb+srv://`)
3. Update the `URI` constant with your connection string
4. `deno run --unstable --allow-all main.ts`

**Comment by ThePotatoChronicler** [comment] 2022-11-24 11:19
The same error pops up on Linux x86_64 with Deno 1.28.1

**Comment by brendantang** [comment] 2022-11-24 18:57
Same issue!

**Comment by NovqiGarrix** [comment] 2022-11-30 03:56
Same issue here with Deno v1.28.2

**Comment by KiPSOFT** [comment] 2023-02-04 18:13
Same on Deno 1.30.2

**Comment by alexbevi** [comment] 2023-02-05 16:48
Note the MongoDB Node.js team has filed [NODE-5042](https://jira.mongodb.org/browse/NODE-5042) which may address the _"MongoAPIError: Server record does not share hostname with parent URI"_ portion of this issue.

**Comment by ImagiNFT** [comment] 2023-02-05 17:40
is there any solution for this?

**Comment by alexbevi** [comment] 2023-02-07 15:21
Interesting development. Using a DNS Seed List in the URI appears to work correctly in the latest Deno:

```
$ deno --version
deno 1.30.3 (release, x86_64-apple-darwin)
v8 10.9.194.5
typescript 4.9.4
```

```js
// file: main.ts
import { MongoClient } from 'npm:mongodb' // updated for Deno

const URI =
"mongodb://<user>:<pass>@cluster0-shard-00-00.abcde.mongodb.net:27017,cluster0-shard-00-01.abcde.mongodb.net:27017,cluster0-shard-00-02.abcde.mongodb.net:27017/?ssl=true&replicaSet=atlas-122v8z-shard-0&authSource=admin&retryWrites=true&w=majority"
const client = new MongoClient(URI)

async function main() {
  console.log('connecting')
  await client.connect()
  console.log('connected')
  const collection = client.db('test_db').collection('test_collection')
  await collection.deleteMany({})
  await collection.insertOne({ a: 2.3 })
  var results = await collection.count({ a: 2.3 })
  console.log(`found ${results}`)
  Deno.exit(1)
}

main()
```

```
connecting
connected
found 1
```

**Comment by mdmusaibali** [comment] 2023-03-19 05:32
This issue still remains on deno 1.31.3.
mongoose.connect connects successfully to mongodb localhost string but when given mongodb+srv string, connection fails with:
`Cannot connect to DB MongoAPIError: Server record does not share hostname with parent URI
    at resolveSRVRecord (file:///home/mdmusaibali/.cache/deno/npm/registry.npmjs.org/mongodb/5.1.0/lib/connection_string.js:60:19)
    at async MongoClient.connect (file:///home/mdmusaibali/.cache/deno/npm/registry.npmjs.org/mongodb/5.1.0/lib/mongo_client.js:117:27)
    at async _createMongoClient (file:///home/mdmusaibali/.cache/deno/npm/registry.npmjs.org/mongoose/7.0.2/lib/connection.js:859:3)
    at async NativeConnection.openUri (file:///home/mdmusaibali/.cache/deno/npm/registry.npmjs.org/mongoose/7.0.2/lib/connection.js:728:5)
    at async file:///home/mdmusaibali/Documents/GitHub/pda-paper-validation-deno-ts/db/mongo.ts:6:5`
    
Connection code:
`import mongoose from "npm:mongoose@7.0.2";
try {
  const MONGO_URL = Deno.env.get("MONGO_URL");
  if (MONGO_URL) {
    await mongoose.connect(
      "mongodb+srv://<username>:<password>@cluster0.byaerrd.mongodb.net/<db-name>?retryWrites=true&w=majority"
    );
    console.log("Connected to db");
  }
} catch (error) {
  if (error instanceof Error) {
    console.log("Cannot connect to DB", error);
  }
}
`

**Comment by avalero** [comment] 2023-03-19 09:22
Damn! I hope this is fixed soon. It is very annoying not been able to work with mongo and Deno, and MongoDB Deno native library is abandoned and I think is does not support MongoDB v6

**Comment by jyemin** [comment] 2023-03-19 15:35
@avalero can you clarify whether you are not able to using MongoDB at all with Deno, or if the issue is only with support for "mongodb+srv" connection string (see [@alexbevi](https://github.com/denoland/deno/issues/16633#issuecomment-1420954429)'s comment just above).

**Comment by avalero** [comment] 2023-03-19 15:37
With the "mongodb+srv" connection string

**Comment by jyemin** [comment] 2023-03-19 16:09
To get a non-SRV connection string, click the Connect button in the Atlas UI, choose the `Node.js` driver, and then select `2.2.12 or later`.  The connection string supplied for this version will work with all later versions of the Node.js driver and should also work with Deno.


<img width="596" alt="Screen Shot 2023-03-19 at 12 00 06 PM" src="https://user-images.githubusercontent.com/1111546/226188933-81dbc089-52cd-4829-be76-eba485278cb5.png">

**Comment by hazelnutcloud** [comment] 2023-03-24 11:01
I think I have figured out the source of this problem. When connecting with the `mongodb+srv` protocol, the node.js mongo driver compares the resolved SRV records against the parent domain.

To do that, it calls  `resolveSrv()` function imported from node's `dns` module. Calling this API from Deno results in trailing dots in the `name` field of the objects in the array returned by the `resolveSrc()` function meanwhile running it node produces no trailing dots

Here's the code I used to test this:
```typescript
import dns from "node:dns";

console.log(await dns.promises.resolveSrv("_mongodb._tcp.cluster.1abcd.mongodb.net"))
```

And here are the outputs when running in Deno:
```typescript
[
  {
    priority: 0,
    weight: 0,
    port: 27017,
    name: "cluster-shard-00-01.1abcd.mongodb.net."
  },
  {
    priority: 0,
    weight: 0,
    port: 27017,
    name: "cluster-shard-00-02.1abcd.mongodb.net."
  },
  {
    priority: 0,
    weight: 0,
    port: 27017,
    name: "cluster-shard-00-00.1abcd.mongodb.net."
  }
]
```

in node:
```typescript
[
  {
    priority: 0,
    weight: 0,
    port: 27017,
    name: "cluster-shard-00-01.1abcd.mongodb.net"
  },
  {
    priority: 0,
    weight: 0,
    port: 27017,
    name: "cluster-shard-00-02.1abcd.mongodb.net"
  },
  {
    priority: 0,
    weight: 0,
    port: 27017,
    name: "cluster-shard-00-00.1abcd.mongodb.net"
  }
]
```

I edited all the hostnames displayed there to hide some info but that's what it should look like.

@bartlomieju @crowlKats

**Comment by hazelnutcloud** [comment] 2023-03-24 11:23
calling `Deno.resolveDns("...", "SRV")` also results in the same behavior (produces trailing dots)

**Comment by alexbevi** [comment] 2023-03-24 12:40
@hazelnutcloud from a MongoDB Driver POV a bug for this was reported previously (see [NODE-5042](https://jira.mongodb.org/browse/NODE-5042)) which we're hoping to get sorted out soon.

It's really helpful to see further confirmation that resolving this bug should improve the Deno experience using MongoDB!

**Comment by eikooc** [comment] 2023-04-13 11:54
Just chiming in with an update. The ticket over at MongoDB's Jira is marked as done with fix version v5.3.0.

https://jira.mongodb.org/browse/NODE-5042

**Comment by alexbevi** [comment] 2023-04-13 12:29
@eikooc you beat me to it :) The MongoDB Node Driver team addressed this with https://github.com/mongodb/node-mongodb-native/commit/051b8615ac0ebebb8c07d7a661bf1ab4f99cf4b2, which will be included in the next release of the driver.

I'll close this issue out once the release is made :)

**Comment by alexbevi** [comment] 2023-04-18 18:14
FYI https://github.com/mongodb/node-mongodb-native/releases/tag/v5.3.0 has been released, which includes the fixes to SRV resolution that were affecting Deno. There may still be an opportunity to address this behavior in Deno directly, but for now the MongoDB driver should work :)

**Comment by topperspal** [comment] 2023-06-27 11:01
It now started connecting to MongoDB with `npm:mongodb@5.6.0` from Atlas uri. I can use CRUD operations but it throws error after a few minutes

```
error: Uncaught Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:89:11)
    at __node_internal_errnoException (ext:deno_node/internal/errors.ts:137:12)
    at TCP.onStreamRead [as onread] (ext:deno_node/internal/stream_base_commons.ts:205:24)
    at TCP.#read (ext:deno_node/internal_binding/stream_wrap.ts:223:18)
    at eventLoopTick (ext:core/01_core.js:183:11)
```

**Comment by eikooc** [comment] 2023-07-10 11:11
@topperspal I experience the same thing

**Comment by TillaTheHun0** [comment] 2023-07-10 20:10
I am experiencing the same issue as @topperspal on `npm:mongodb@5.6.0` and Deno `1.35.0`. At first, operations performed using the driver succeed, but then after a few minutes, I get that same `ECONNRESET` error which crashes the process.

Perhaps worth noting that [`5.6.0` introduced support for Node `20`](https://github.com/mongodb/node-mongodb-native/releases/tag/v5.6.0), so maybe some regression with node compat?

**Comment by eikooc** [comment] 2023-07-11 05:31
@TillaTheHun0 if you can create a minimal reproduction then there's this issue where you can post it https://github.com/denoland/deno/issues/19078

I haven't been able to create a succesful minimal production showing the error.

**Comment by TillaTheHun0** [comment] 2023-07-11 18:27
@eikooc I posted a repo with steps to reproduce. I was only able to replicate with an Atlas Serverless Cluster, which seems correlated, but can't say for sure without digging deeper.

**Comment by eikooc** [comment] 2023-08-04 06:47
I've noticed that this happens every time the MongoDB cluster scales up or down so the connection is cut.

**Comment by eikooc** [comment] 2023-08-29 19:24
I believe this has been fixed in v1.37 https://github.com/denoland/deno/pull/20314.
Right now it is possible to update by running `deno upgrade --canary`

**Comment by fro-profesional** [comment] 2023-09-25 21:42
I jus tried on local an deploy and seems to be working with MongoDB Atlas serverless deno v1.37

```ts
import { MongoClient } from "npm:mongodb"
import { ulid } from "https://deno.land/std@0.202.0/ulid/mod.ts";

const client = new MongoClient("<url>")

client.connect();

Deno.serve(async () => {

  const data = await client.db("deno").collection("deno").insertOne({
    name: ulid()
  })

  return new Response(JSON.stringify({
    data
  }), {
    headers: { "Content-Type": "application/json" },
  })
})
```

**Comment by ryvwel** [comment] 2024-05-31 12:07
> It now started connecting to MongoDB with `npm:mongodb@5.6.0` from Atlas uri. I can use CRUD operations but it throws error after a few minutes
> 
> ```
> error: Uncaught Error: read ECONNRESET
>     at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:89:11)
>     at __node_internal_errnoException (ext:deno_node/internal/errors.ts:137:12)
>     at TCP.onStreamRead [as onread] (ext:deno_node/internal/stream_base_commons.ts:205:24)
>     at TCP.#read (ext:deno_node/internal_binding/stream_wrap.ts:223:18)
>     at eventLoopTick (ext:core/01_core.js:183:11)
> ```

Does anyone experience this error yet? It happens  so random i can't reproduce it locally, but my serverless service sometimes crashes because of this

**Comment by alexbevi** [comment] 2024-05-31 12:16
@ryvwel that's just a socket error, so "why" the connection was closed would need investigation (it's likely not a Deno, or even MongoDB issue). Note that MongoDB's drivers support automatic retryability of [reads](https://www.mongodb.com/docs/manual/core/retryable-reads/) and [writes](https://www.mongodb.com/docs/manual/core/retryable-writes/) so it's possible the associated operation may not have even failed (though you may see a logged error).

**Comment by jantoney** [comment] 2024-06-29 04:41
@ryvwel @topperspal 
I think the issue around `error: Uncaught Error: read ECONNRESET` might be related to #21951 
If correct, it is something around a CLOSE and ERROR event being out of order in Deno.

Further links to others in that issue

**Comment by bartlomieju** [comment] 2024-07-30 14:51
We believe this is now fixed with #21951. Please try with Deno v1.45.4 and let us know if the problem persists.

**Closed by bartlomieju** 2024-07-30 14:51 UTC
Labels: needs investigation, node compat

**Comment by gydobroos** [comment] 2024-12-01 18:26
Problem persists on Deno 2.1.2 with MongoDB 6.11.0.

Tried all potential workaround/fixes mentioned here, but none seem to work.

Any ideas?

{"error":"MongoServerSelectionError: Server selection timed out after 30000 ms\n    at Topology.selectServer (file:///deno-dir/npm/registry.npmjs.org/mongodb/6.11.0/lib/sdam/topology.js:320:38)\n    at eventLoopTick (ext:core/01_core.js:214:9)\n    at async Topology._connect (file:///deno-dir/npm/registry.npmjs.org/mongodb/6.11.0/lib/sdam/topology.js:204:28)\n    at async Topology.connect (file:///deno-dir/npm/registry.npmjs.org/mongodb/6.11.0/lib/sdam/topology.js:156:13)\n    at async topologyConnect (file:///deno-dir/npm/registry.npmjs.org/mongodb/6.11.0/lib/mongo_client.js:233:17)\n    at async MongoClient._connect (file:///deno-dir/npm/registry.npmjs.org/mongodb/6.11.0/lib/mongo_client.js:246:13)\n    at async MongoClient.connect (file:///deno-dir/npm/registry.npmjs.org/mongodb/6.11.0/lib/mongo_client.js:171:13)\n ],"timestamp":"2024-12-01T18:09:05.091Z"}

**Comment by jamesej** [comment] 2024-12-11 16:40
Same issue. I can add that the generated error has the property reason.type = 'ReplicaSetNoPrimary' and reason.servers lists 3 servers all of which have primary = null. No work around solves it, I've also tried downgrading the NPM mongodb driver to 5.3.0.

**Comment by alexbevi** [comment] 2025-03-06 12:44
Note that more often than not `ReplicaSetNoPrimary` or `MongoServerSelectionError` are just networking errors between the client and the server. Are you able to connect to the MongoDB cluster through the `mongosh` shell from the same machine where your Deno application is running?

If you're using MongoDB Atlas ensure you have a valid [IP Access List](https://www.mongodb.com/docs/atlas/security/ip-access-list/) configured (you can use `0.0.0.0/32` to allow all).
