### ISSUE TITLE
Bug: tailwindcss v4 alpha errors on import

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#22801] opened 2024-03-08 16:04 UTC
```ts
import tailwindcss from "npm:@tailwindcss/postcss@4.0.0-alpha.6";
console.log(tailwindcss);
```

Error:

```sh
error: Could not resolve 'npm:@tailwindcss/postcss@4.0.0-alpha.6'.

Caused by:
    0: Failed resolving package subpath '.' for '/Users/marvinh/dev/test/deno-tw2/node_modules/.deno/@tailwindcss+postcss@4.0.0-alpha.6/node_modules/@tailwindcss/postcss/package.json'
    1: [ERR_INVALID_PACKAGE_TARGET] Invalid "exports" main target {"types":"./dist/index.d.ts","require":"./dist/index.js"} defined in the package config /Users/marvinh/dev/test/deno-tw2/node_modules/.deno/@tailwindcss+postcss@4.0.0-alpha.6/node_modules/@tailwindcss/postcss/package.json imported from file:///Users/marvinh/dev/test/deno-tw2/foo.ts; target must start with "./"
```

Version: Deno 1.41.1

**Comment by kt3k** [comment] 2024-11-27 06:09
Looks like this was fixed in upstream. The package doesn't error at v4.0.0-beta.2:

```
$ cat a.js 
import tailwindcss from "npm:@tailwindcss/postcss@4.0.0-beta.2";
console.log(tailwindcss);
$ deno -A a.js 
[Function: A] { postcss: true }
```

**Comment by bartlomieju** [comment] 2024-12-06 02:42
Confirmed it works fine in a newer version.

**Closed by bartlomieju** 2024-12-06 02:42 UTC
Labels: bug, node compat, node API
