### ISSUE TITLE
Deno.serve cause error when using req.clone

### ISSUE THREAD

**Issue by winston0410** [denoland/deno#15978] opened 2022-09-21 08:13 UTC
The following snippets will cause errors. After removing `req.clone` it will be fine, so 100% req.clone is the source of issue.

```ts
Deno.serve(opts, (req) => {
	console.log('check req', req.clone())
	return new Response()
})
```

```sh
TypeError: Array.prototype.map called on null or undefined
    at map (<anonymous>)
    at cloneInnerRequest (deno:ext/fetch/23_request.js:164:9)
    at Request.clone (deno:ext/fetch/23_request.js:489:18)
    at Object.serve (deno:ext/flash/01_http.js:543:22)
    at async Promise.all (index 0)
    at async Object.serve (deno:ext/flash/01_http.js:619:5)
```

**Comment by littledivy** [comment] 2022-09-21 08:24
Duplicate of https://github.com/denoland/deno/issues/15858

**Closed by littledivy** 2022-09-21 08:24 UTC
