### ISSUE TITLE
JavaScript equivalent of `deno info`?

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4300] opened 2020-03-09 14:12 UTC
`deno info` command can be used to print all dependencies of a module to terminal, but I want to use it in JavaScript/TypeScript code. It would be nice to have a function (let's say `Deno.info()`) that returns an object with these information.

**Comment by bartlomieju** [comment] 2020-03-09 14:15
Duplicate of #2096

**Closed** 2020-03-09 14:22 UTC
