### ISSUE TITLE
I hope compiling to native binary was added for Deno.

### ISSUE THREAD

**Issue by Foxchandaisuki** [denoland/deno#22823] opened 2024-03-09 04:59 UTC
I was very excited to know Deno has "Deno Compile", which can make executable file. But soon I got depressed because I found that is not compiling JavaScript, TypeScript to native binary, but merging Deno runtime with JS, TS code, which can't make the program executed faster.

I hope someday compiling to native binary was truly supported. It would be very nice to see Fully compiled, not interpreted program made with Deno. Using LLVM as a backend could be an option.

**Comment by bartlomieju** [comment] 2024-03-10 01:43
Duplicate of https://github.com/denoland/deno/issues/22828.

As per https://github.com/denoland/deno/issues/22828#issuecomment-1987036350 there's nothing actionable for us to do here at the moment.

**Closed by bartlomieju** 2024-03-10 01:43 UTC
