### ISSUE TITLE
test conver don't cover trailing line

### ISSUE THREAD

**Issue by jimmywarting** [denoland/deno#12629] opened 2021-11-02 19:59 UTC
Whenever i run: `deno test --fail-fast --coverage=x && deno coverage x`
then i get almost 100% code coverage.

the issue is with the last empty trailing line...
```
cover file:///path/quality.js ... 98.148% (53/54)
  54 | 
```

This should be accounted for

deno 1.15.3 (release, x86_64-apple-darwin)
v8 9.5.172.19
typescript 4.4.2

**Comment by kitsonk** [comment] 2021-11-02 20:27
Duplicate of #11327

**Closed by kitsonk** 2021-11-02 20:27 UTC
Labels: duplicate
