### ISSUE TITLE
Deno panic while using `Deno.connectTls()` in `(async function(){}())`  

### ISSUE THREAD

**Issue by vdata1** [denoland/deno#24389] opened 2024-07-02 08:21 UTC
Hi, 
I want to report Deno panic while using `Deno.connectTls()`, you can reproduce the permission panic by running the following code: 

```javascript
// Deno Version: 1.44.4 
(async function () {
    const conn3 = await Deno.connectTls({
        hostname: '[2001:db8::1]',
        port: 80
    })
}())
```

STACKTRACE logs: 

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.44.4
Args: ["deno", "run", "test.ts"]

thread 'main' panicked at /Users/runner/work/deno/deno/runtime/permissions/lib.rs:698:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: deno_permissions::UnaryPermission<deno_permissions::NetDescriptor>::check
   4: deno_net::ops_tls::op_net_connect_tls::op_net_connect_tls<NP>::call::{{closure}}
   5: <deno_core::runtime::op_driver::futures_unordered_driver::FuturesUnorderedDriver<C> as deno_core::runtime::op_driver::OpDriver<C>>::submit_op_fallible
   6: deno_net::ops_tls::op_net_connect_tls::op_net_connect_tls<NP>::v8_fn_ptr

Thanks,

**Comment by lucacasonato** [comment] 2024-07-02 11:21
Duplicate of #23753

**Closed by lucacasonato** 2024-07-02 11:21 UTC

**Comment by vdata1** [comment] 2024-07-02 12:08
Hi @lucacasonato , 

Many thanks for your reply, I think the Deno versions are not the same(mine is 1.44.4 while the other is a bit older) and it seems the bug is different.
