### ISSUE TITLE
Module reloading

### ISSUE THREAD

**Issue by deckchairlabs** [denoland/deno#15685] opened 2022-08-30 11:30 UTC
Now I know this is something not inline with web specs, with how Deno handles modules and all. But an API to "invalidate" a module would be so handy for implementing some rudimentary HMR. `import.meta.invalidate('./path/to/module.js')` for instance

I've got this `dev.ts` module which I run with `deno run -A dev.ts ./server.tsx` that creates a Worker of `./server.tsx`.
I'm then watching project directory for changes and posting a message to that worker. Server is then listening for messages posted to it and sending a message via websocket to the browser to reload.... phew. Problem is, any modules imported in the server, aren't "fresh". So on my frontend, the window reloads, yet I get hydration mismatch, since the "server" is still using the old modules.

I hope this makes sense.

My `dev.ts` contents below. Server is kind of irrelavant, so have left that out of this issue.
```ts
import {
  join,
  SEP,
  toFileUrl,
} from "https://deno.land/std@0.153.0/path/mod.ts";

const cwd = join(Deno.cwd(), SEP);
const watcher = Deno.watchFs(cwd);

// args[0] will be something like ./server.tsx
const mainModule = new URL(Deno.args[0], toFileUrl(cwd)).href;

let mainWorker = new Worker(mainModule, {
  type: "module",
  name: "main",
});

for await (const event of watcher) {
  if (event.kind === "modify") {
    mainWorker.postMessage({
      type: "reload",
      paths: [mainModule, ...event.paths],
    });

    queueMicrotask(() => {
      mainWorker.terminate();
      mainWorker = new Worker(mainModule + `?t=${new Date().getTime()}`, {
        type: "module",
        name: "main",
      });

      console.log(Deno.resources());
    });
  }
}
```

**Comment by deckchairlabs** [comment] 2022-08-30 11:32
As you can see, I'm trying to get around the limits by recreating a Worker, even appending a timestamp. Which if I console log `import.meta.url` in `server.tsx` will have the timestamp appended and it updates, although any "child" modules will still be the previous.

**Comment by kitsonk** [comment] 2022-08-30 22:32
Duplicate of #6173

**Closed by kitsonk** 2022-08-30 22:32 UTC
Labels: duplicate
