### ISSUE TITLE
Import an absolute path from an online module

### ISSUE THREAD

**Issue by thgh** [denoland/deno#1701] opened 2019-02-07 13:55 UTC
Input
```
import cowsay from 'https://dev.jspm.io/cowsay-browser'
console.log(cowsay.say({ text: 'yolo' }))
```

First line of `https://dev.jspm.io/cowsay-browser`
```
import { dew } from "/npm:cowsay-browser@1.1.8/index.dew.js";
```

### Actual
Deno tries to import `/npm:cowsay-browser@1.1.8/index.dew.js` and fails.
```
Cannot resolve module "/npm:cowsay-browser@1.1.8/index.dew.js"
from ".../.deno/deps/https/dev.jspm.io/cowsay-browser"
```

### Expected
Deno imports `https://dev.jspm.io/npm:cowsay-browser@1.1.8/index.dew.js`

### Quick reproduction
This should not fail:
`deno https://dev.jspm.io/cowsay-browser`

**Comment by kitsonk** [comment] 2019-02-07 22:40
Duplicate of #203

**Closed** 2019-02-07 23:38 UTC
