### ISSUE TITLE
"Deno has panicked. This is a bug in Deno" when compiling

### ISSUE THREAD

**Issue by akpi816218** [denoland/deno#19266] opened 2023-05-26 01:27 UTC
When running `deno compile --allow-read --allow-env --allow-sys .src/feces-cli.ts`
I can provide config files upon request.

```
Compile file:///home/akpi/git/feces-cli/src/feces-cli.ts to feces-cli

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.34.0
Args: ["deno", "compile", "--allow-read", "--allow-env", "--allow-sys", "./src/feces-cli.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: StripPrefixError(())', cli/standalone/virtual_fs.rs:154:53
stack backtrace:
   0:     0x5a97c18d380a - std::backtrace_rs::backtrace::libunwind::trace::ha271a8a7e1f3d4ef
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5a97c18d380a - std::backtrace_rs::backtrace::trace_unsynchronized::h85739da0352c791a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5a97c18d380a - std::sys_common::backtrace::_print_fmt::hbc6ebcfb2910b329
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:65:5
   3:     0x5a97c18d380a - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::he1c117e52d53614f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:44:22
   4:     0x5a97c190008e - core::fmt::write::h25eb51b9526b8e0c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/fmt/mod.rs:1213:17
   5:     0x5a97c18ca595 - std::io::Write::write_fmt::ha9edec5fb1621933
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/io/mod.rs:1682:15
   6:     0x5a97c18d35d5 - std::sys_common::backtrace::_print::hf8657cd429fc3452
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:47:5
   7:     0x5a97c18d35d5 - std::sys_common::backtrace::print::h41b9b18ed86f86bd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:34:9
   8:     0x5a97c18d53cf - std::panicking::default_hook::{{closure}}::h22a91871f4454152
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:267:22
   9:     0x5a97c18d510b - std::panicking::default_hook::h21ddc36de0cd4ae7
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:286:9
  10:     0x5a97c1cc9041 - deno::setup_panic_hook::{{closure}}::h6b637d0223f22f3d
  11:     0x5a97c18d5b5a - <alloc::boxed::Box<F,A> as core::ops::function::Fn<Args>>::call::h6f7e3c94ecc52e2f
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/alloc/src/boxed.rs:2002:9
  12:     0x5a97c18d5b5a - std::panicking::rust_panic_with_hook::h5059419d6d59b3d0
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:692:13
  13:     0x5a97c18d58d9 - std::panicking::begin_panic_handler::{{closure}}::h0f383c291cd78343
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:579:13
  14:     0x5a97c18d3cbc - std::sys_common::backtrace::__rust_end_short_backtrace::h70ab22f2ad318cdd
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/sys_common/backtrace.rs:137:18
  15:     0x5a97c18d55e2 - rust_begin_unwind
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:575:5
  16:     0x5a97c18fd543 - core::panicking::panic_fmt::hd1d46bcde3c61d72
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/panicking.rs:64:14
  17:     0x5a97c18fda73 - core::result::unwrap_failed::h456a23f68607268c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/result.rs:1790:5
  18:     0x5a97c19d0052 - core::result::Result<T,E>::unwrap::h5aeea41338c282af
  19:     0x5a97c1c4f7fb - deno::standalone::virtual_fs::VfsBuilder::add_dir_recursive::h88f460a7c0e31303
  20:     0x5a97c1c4f4d1 - deno::standalone::virtual_fs::VfsBuilder::add_dir_recursive::h88f460a7c0e31303
  21:     0x5a97c1c4bfd7 - deno::standalone::binary::DenoCompileBinaryWriter::write_standalone_binary::{{closure}}::h9627bed3428a47ad
  22:     0x5a97c1c62eac - deno::tools::compile::compile::{{closure}}::h87e9f59d35bb32fa
  23:     0x5a97c1ae171c - <deno_core::task::MaskFutureAsSend<F> as core::future::future::Future>::poll::h7c1a8655040411bf
  24:     0x5a97c1a1e77c - tokio::runtime::task::raw::poll::h68723962e8ad1764
  25:     0x5a97c1cc9e94 - deno::main::ha8754a53c91c576c
  26:     0x5a97c1962002 - std::sys_common::backtrace::__rust_begin_short_backtrace::haf7b0912d908212d
  27:     0x5a97c1966624 - std::rt::lang_start::{{closure}}::h97f201e2df6e2f77
  28:     0x5a97c18bf96c - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h203afb3af230319a
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/core/src/ops/function.rs:287:13
  29:     0x5a97c18bf96c - std::panicking::try::do_call::hf68e87013b70f3c5
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  30:     0x5a97c18bf96c - std::panicking::try::h040ea8f298390ba2
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  31:     0x5a97c18bf96c - std::panic::catch_unwind::h1e17b198887a05fa
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  32:     0x5a97c18bf96c - std::rt::lang_start_internal::{{closure}}::hfb902d8927e51b86
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:48
  33:     0x5a97c18bf96c - std::panicking::try::do_call::h354e6eb41f2e7d42
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:483:40
  34:     0x5a97c18bf96c - std::panicking::try::h4a39749cd018228c
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panicking.rs:447:19
  35:     0x5a97c18bf96c - std::panic::catch_unwind::h30bce83b8de61cca
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/panic.rs:140:14
  36:     0x5a97c18bf96c - std::rt::lang_start_internal::h8f7e70b1a2558118
                               at /rustc/9eb3afe9ebe9c7d2b84b71002d44f4a0edac95e0/library/std/src/rt.rs:148:20
  37:     0x5a97c1d632a5 - main
  38:     0x7f1eb70e7d0a - __libc_start_main
  39:     0x5a97c087d029 - _start
  40:                0x0 - <unknown>
```

Steps to reproduce:
1. Run the command at the top.
Error is reliably reproduced after deleting the created executable and re-running the command.

**Update:** The executable created is empty.

**Comment by bartlomieju** [comment] 2023-05-26 03:07
This is a duplicate of https://github.com/denoland/deno/issues/19251. Please update to canary version (`deno upgrade --canary`), try again and let us know.

**Closed by bartlomieju** 2023-05-26 03:07 UTC

**Comment by akpi816218** [comment] 2023-05-26 04:28
That works, thanks!
