### ISSUE TITLE
Panic: "Code generation from strings disallowed for this context" with 1.27.1

### ISSUE THREAD

**Issue by jfrancos** [denoland/deno#16535] opened 2022-11-04 13:28 UTC
Me and at least one other using Netlify edge functions are seeing
```
thread 'main' panicked at 'Failed to execute bootstrap script: EvalError: Code generation from strings disallowed for this context
```
I tried downgrading to `1.27.0` and the panic went away.
More info [here](https://answers.netlify.com/t/nextjs-netlify-cli-deno-panic-due-to-next-dev-edge-function/78563)

**Comment by lucacasonato** [comment] 2022-11-04 15:39
Caused by https://github.com/denoland/deno/commit/e18950284f279cfa8ec090cb8a882dbd64e92d4a. We need to not use dynamic code eval (instead `isolate.execute_script`, or generate the functions from JS rust side).

**Comment by jfrancos** [comment] 2022-11-04 18:16
I came here to close this ticket since Netlify has this addressed in this morning's release of netlify-cli@12.1.0 (and I can confirm it works).

But, it looks like Deno is also taking accountability for this so ... just want to connect you two @eduardoboucas @lucacasonato so you're not both fixing the same issue in different places.

**Comment by eduardoboucas** [comment] 2022-11-04 23:47
Yes, we're in touch. 🙂

But thanks for following up!

**Comment by vazexqi** [comment] 2022-12-09 21:21
Any updates on this?

I see that netlify solved this in https://github.com/netlify/edge-bundler/commit/d34499214be4311e28b9b2292b9ba714cd01c06b by _removing_ `--disallow-code-generation-from-strings`.

But, I'd like to enable that flag for my use case to actually prevent code-generation when we are executing code (we are taking in user's code and would like to restrict what they can do).

**Comment by bartlomieju** [comment] 2022-12-09 21:49
@littledivy please take a look

**Comment by vazexqi** [comment] 2022-12-14 19:04
@littledivy - Any updates on this? Trying to see if there's any chance this will be fixed in 1.29.

**Comment by bartlomieju** [comment] 2022-12-14 21:51
> @littledivy - Any updates on this? Trying to see if there's any chance this will be fixed in 1.29.

It will not be fixed in 1.29, maybe in one of the patch releases after 1.29.

**Comment by vazexqi** [comment] 2023-01-27 00:28
Sorry for the ping again, do we have an ETA on when this will be fixed? We are locked down to 1.27.0 until it's fixed.

**Comment by bartlomieju** [comment] 2023-01-27 15:14
@littledivy is looking into this

**Comment by mcodik** [comment] 2023-02-08 16:04
Any news on this? we'd also like to use `--disallow-code-generation-from-strings`, but are holding off due to the panic

**Closed** 2023-02-23 19:50 UTC
Labels: bug, core
