### ISSUE TITLE
Dynamic local file import is quite slow and seems not cached in the next launch

### ISSUE THREAD

**Issue by Shougo** [denoland/deno#12805] opened 2021-11-18 05:23 UTC
Continues of https://github.com/denoland/deno/issues/12519

`test.ts`

```typescript
// test.ts
async function main() {
  await Promise.all([
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
    import("https://deno.land/x/denops_core@v2.0.3/mod.ts"),
  ]);
}
await main();
```

`$ cp test.ts test.ts2`

`test2.ts`

```typescript
import { toFileUrl } from "https://deno.land/std@0.115.1/path/mod.ts";

async function main() {
  const t = performance.now();
  await Promise.all([
    import(toFileUrl(Deno.cwd() + "/test.ts").href),
    import(toFileUrl(Deno.cwd() + "/test.ts2").href),
  ]);
  console.log(performance.now() - t);
}
await main();
```

```
% deno --version
deno 1.16.2 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.2
typescript 4.4.2
% deno run -A --no-check ./test2.ts
151.510647
[~/work]
% deno run -A --no-check ./test2.ts
154.57850399999998
[~/work]
% deno run -A --no-check ./test2.ts
153.059971
```

After #12604, remote URL dynamic loading is very fast!  But it is not same with dynamic local file import :-(
Simple dynamic import takes almost 80ms and it seems not cached.  It is really slow for me.
Because dynamic remote URL import is less than 2.0ms.

**Comment by nayeemrmn** [comment] 2021-11-18 05:47
Similar to https://github.com/denoland/deno/issues/12519#issuecomment-955529389, if you instead time using the command line you will find that `time deno run -A --no-check test.ts` and `time deno run -A --no-check test2.ts` give similar results.

The reason the `await import(...)`s themselves are fast in `test.ts` but slow in `test2.ts` is because the specifiers in `test2.ts` are not statically determined, whereas the ones in `test.ts` are actually being fetched on startup and so not included in your time delta. But the program execution times are similar.

**Comment by Shougo** [comment] 2021-11-18 07:19
Oh ....

```
% time deno run -A --no-check ./test.ts
deno run -A --no-check ./test.ts  0.10s user 0.02s system 88% cpu 0.138 total
[~/work]
% time deno run -A --no-check ./test2.ts
148.441442
deno run -A --no-check ./test2.ts  0.19s user 0.01s system 93% cpu 0.218 total
```

**Comment by Shougo** [comment] 2021-11-18 07:27
So dynamic local file import cannot be optimized?
Simple script loading is almost 80ms, my software needs import several scripts(`200ms x n`).

My software loading time is almost `2000ms`.

**Comment by Shougo** [comment] 2021-11-18 07:33
In previous deno version:

```
% time deno run -A --no-check ./test.ts
deno run -A --no-check ./test.ts  0.78s user 0.03s system 99% cpu 0.817 total
[~/work]
% time deno run -A --no-check ./test2.ts
1491.0866350000001
deno run -A --no-check ./test2.ts  1.48s user 0.07s system 99% cpu 1.557 total
```

Hm... It seems faster.

**Comment by nayeemrmn** [comment] 2021-11-18 07:39
@Shougo Do your dynamically imported modules share a lot of dependencies? There is actually an important optimisation we need to make which should drastically improve that case.

**Comment by Shougo** [comment] 2021-11-18 07:42
My dynamic imported file sample is here.

https://github.com/Shougo/ddc-around/blob/main/denops/%40ddc-sources/around.ts

Yes.  It has several dependencies.

**Comment by Shougo** [comment] 2021-12-16 11:16
Thank you!

**Comment by Shougo** [comment] 2021-12-17 01:15
Sorry, after I upgrade deno to 1.17.  The performance is really worse unfortunately.
Please see my tests.

```
% deno --version
deno 1.17.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
[~/work]
% deno run -A --no-check ./test2.ts
Download https://deno.land/std@0.115.1/path/mod.ts
Download https://deno.land/std@0.115.1/_util/os.ts
Download https://deno.land/std@0.115.1/path/_interface.ts
Download https://deno.land/std@0.115.1/path/common.ts
Download https://deno.land/std@0.115.1/path/glob.ts
Download https://deno.land/std@0.115.1/path/posix.ts
Download https://deno.land/std@0.115.1/path/separator.ts
Download https://deno.land/std@0.115.1/path/win32.ts
Download https://deno.land/std@0.115.1/_util/assert.ts
Download https://deno.land/std@0.115.1/path/_constants.ts
Download https://deno.land/std@0.115.1/path/_util.ts
Download https://deno.land/x/denops_core@v2.0.3/mod.ts
Download https://deno.land/x/denops_core@v2.0.3/mod.ts
Download https://deno.land/x/denops_core@v2.0.3/denops.ts
Download https://deno.land/x/denops_core@v2.0.3/deps.ts
Download https://deno.land/x/denops_core@v2.0.3/denops.ts
Download https://deno.land/x/denops_core@v2.0.3/deps.ts
711.751076
[~/work]
% deno run -A --no-check ./test2.ts
146.059181
[~/work]
% deno run -A --no-check ./test2.ts
143.357182
[~/work]
% deno run -A --no-check ./test2.ts
144.695777
```

```
% deno upgrade -f --version 1.16.3
Checking https://github.com/denoland/deno/releases/download/v1.16.3/deno-x86_64-unknown-linux-gnu.zip
31.7 MiB / 31.7 MiB (100.0%)
Deno is upgrading to version 1.16.3
Archive:  /tmp/.tmp5CulPK/deno.zip
  inflating: deno
Upgraded successfully
[~/work]
% deno run -A --no-check ./test2.ts
155.73468499999998
[~/work]
% deno run -A --no-check ./test2.ts
101.86162999999999
[~/work]
% deno run -A --no-check ./test2.ts
105.43141
[~/work]
% deno run -A --no-check ./test2.ts
103.11573899999999
[~/work]
% deno run -A --no-check ./test2.ts
102.091372
[~/work]
% deno --version
deno 1.16.3 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.5
typescript 4.4.2
```

My dynamic loading performance is almost `100` to almost `150`.  It is really worse for me.

**Comment by nayeemrmn** [comment] 2021-12-17 05:16
Looks like there was a prepare-module-load perf regression since 1.16.4. 1.17.0 is still faster for this case than 1.16.4+e28fb70 (the commit before #12960), so it occurred somewhere before that. That regression affects static module loading in general e.g. `deno cache --no-check https://deno.land/x/denops_core@v2.0.3/mod.ts`. cc @bartlomieju

**Comment by nayeemrmn** [comment] 2021-12-17 13:47
It occurred at the `deno_graph` 0.14.0 update #13080.

**Comment by nayeemrmn** [comment] 2021-12-22 19:07
Fixed by #13173.

@Shougo On my machine, your example gives:
- (1.16.4) ~160ms
- (1.17.0) ~180ms
- (1.17.1) ~100ms

We've removed all redundant loading in dynamic imports and there are no more similar problems I can see. So that's as good as it's going to get for the foreseeable future.

**Closed** 2021-12-22 19:10 UTC
Labels: perf, feat, cli

**Comment by Shougo** [comment] 2021-12-23 01:20
Thanks.  It fixes the problem!

**Comment by Shougo** [comment] 2021-12-23 01:21
```
% deno run -A --no-check ./test2.ts
129.719481
[~/work]
% deno run -A --no-check ./test2.ts
55.100047
[~/work]
% deno run -A --no-check ./test2.ts
54.600699
[~/work]
% deno run -A --no-check ./test2.ts
55.55068500000001
```

It is faster than previous version!
