### ISSUE TITLE
deno.json not used as config by default when installing global script

### ISSUE THREAD

**Issue by annervisser** [denoland/deno#26212] opened 2024-10-13 18:28 UTC
When installing a local typescript file as a global script,
the default behaviour is to not take the deno.json in the same folder into account.

This is unexpected, since the documentation for the `--config` options says:

>	Typically the configuration file will be called `deno.json` or `deno.jsonc` and 
>	automatically detected; in that case this flag is not necessary.

This results in confusing behaviour, and discrepancies between `deno run main.ts` and `deno install --global --name my-script main.ts && my-script`

## Example:
```shell
cd ~/my-script-repo
deno install --global --name my-script main.ts
```

## Expected behaviour
- Running `my-script` should run `~/my-script-repo/main.ts` it using `~/my-script-repo/deno.json`

## Actual behaviour:
- Running `my-script` runs `~/my-script-repo/main.ts` with no/the global deno configuration.

I've uploaded a reproduction at https://github.com/annervisser/deno-relative-import-repro

Version: deno 2.0.0 (stable, release, x86_64-unknown-linux-gnu)
v8 12.9.202.13-rusty
typescript 5.6.2

**Comment by annervisser** [comment] 2024-10-14 08:42
I've realized this is also the case when installing a package globally from deno.land,
which is a bigger problem since you can't work around it by specifying --config.

Example:
```
deno install --reload --force --global --name pr-cli --allow-run --allow-read --allow-env https://deno.land/x/prcli/main.ts
```

When running pr-cli, the following error is output:
```
error: Relative import path "@std/log" not prefixed with / or ./ or ../
    at https://deno.land/x/prcli@1.10.0/main.ts:6:22
```

This is once again caused by deno not using the deno.json of that package as its config

**Comment by dsherret** [comment] 2024-10-14 19:09
Duplicate of https://github.com/denoland/deno/issues/17572

See https://github.com/denoland/deno/issues/17855 for improving this.

> `deno install --reload --force --global --name pr-cli --allow-run --allow-read --allow-env https://deno.land/x/prcli/main.ts`

Deno never auto-discovers configuration files in https dependencies. I'd recommend publishing to [JSR](https://jsr.io/) instead because it handles publishing code with the config inlined.

**Closed by dsherret** 2024-10-14 19:09 UTC
Labels: duplicate
