### ISSUE TITLE
Allow specifying path prefix for --allow-net permissions

### ISSUE THREAD

**Issue by AurelienZintzmeyer** [denoland/deno#12382] opened 2021-10-09 13:05 UTC
Currently --allow-net=domain/A has the same effect as --allow-net=domain. It would be nice to be able to only allow network access to an URL with a given domain & path prefix.

**Comment by nayeemrmn** [comment] 2021-10-09 13:20
Duplicate of #5242. I don't think it makes sense, path is just data being sent to the same entity.

**Comment by AurelienZintzmeyer** [comment] 2021-10-09 13:32
This feature could be used to restrict module sources, for example only the scripts in https://raw.githubusercontent.com/SOME_ORGANIZATION/

**Comment by lucacasonato** [comment] 2021-11-03 12:03
Closing as duplicate of #5242

**Closed by lucacasonato** 2021-11-03 12:03 UTC
