### ISSUE TITLE
Deno should respect TZ environment variable 

### ISSUE THREAD

**Issue by ry** [denoland/deno#11053] opened 2021-06-19 22:41 UTC
like Node does

**Comment by wperron** [comment] 2021-06-20 03:43
Pretty sure it does, we've had bugs in std because that were only apparent when running the test suite with different `TZ` values

**Comment by cvng** [comment] 2021-06-20 10:51
I can confirm running `echo "console.log(new Date().toString())" | TZ=UTC+4 deno run -` does respect the `TZ` value.

What is not supported though is dynamically changing `TZ` during runtime, but I'm not sure if this is a case we want to support.

A way to make that work is: https://github.com/nodejs/node/commit/eba348b6aecf5c764f786f6f049431237702c88f

**Comment by bartlomieju** [comment] 2021-06-20 13:22
> What is not supported though is dynamically changing TZ during runtime, but I'm not sure if this is a case we want to support.

I'm not in favor - we don't change behavior during when any of the other env variables changes (like `DENO_DIR`, or `DENO_HTTP_PROXY`). What's the use case for listening on `TZ` changes? Is there any valid reason outside testing?

**Comment by cvng** [comment] 2021-06-20 13:30
I'm also not in favor of listening on `TZ` changes. If we don't want to support this, `TZ=UTC deno run tz.js` is fine.

**Comment by bartlomieju** [comment] 2021-06-30 02:36
I'm gonna close this issue as we already support `TZ` env variable.

**Closed by bartlomieju** 2021-06-30 02:36 UTC
Labels: feat
