### ISSUE TITLE
Tests failing showing error TS5009:  Cannot find the common subdirectory path for the input files.

### ISSUE THREAD

**Issue by Ashniu123** [denoland/deno#807] opened 2018-09-23 15:19 UTC
I ran into this error when running `python .\tools\test.py`

```
E:\Workspace\Github\deno\out\debug\deno.exe E:\Workspace\Github\deno\tests\003_relative_import.ts --reload
E:\Workspace\Github\deno\out\debug\deno.exe E:\Workspace\Github\deno\tests\004_set_timeout.ts --reload
E:\Workspace\Github\deno\out\debug\deno.exe E:\Workspace\Github\deno\tests\005_more_imports.ts --reload
E:\Workspace\Github\deno\out\debug\deno.exe E:\Workspace\Github\deno\tests\006_url_imports.ts --reload
127.0.0.1 - - [23/Sep/2018 20:32:26] "GET /tests/subdir/mod2.ts HTTP/1.1" 200 -
127.0.0.1 - - [23/Sep/2018 20:32:27] "GET /tests/subdir/print_hello.ts HTTP/1.1" 200 -
Expected success but got error. Output:
Downloading http://localhost:4545/tests/subdir/mod2.ts
Downloading http://localhost:4545/tests/subdir/print_hello.ts
error TS5009: Cannot find the common subdirectory path for the input files.
```
OS: Windows 10 x64
Node version: v8.12.0
NPM version: v6.4.1

How to solve this issue?

P.S. Similar issue was faced [here](https://github.com/ivogabe/gulp-typescript/issues/193) and [here](https://github.com/Microsoft/TypeScript/issues/11727) not sure if both are relevent but I can't figure it out still.

**Comment by hlege** [comment] 2018-09-26 17:50
It is because deno try to compile the typescript sources that are located in two different partition (c:\\~\\.deno\\.., e:\\... )

My solution right now is:
Solution right now is to put your test file somewhere to c: partition.

**Comment by Ashniu123** [comment] 2018-09-26 20:17
Thanks a bunch. I think collaborators should find a way around this, because it could be a very common issue soon.

**Comment by hstarorg** [comment] 2019-01-10 18:18
Evevyone, would you tell me when will release this feature? It's very important for get IDE intellisense.

**Comment by kitsonk** [comment] 2019-01-10 23:44
This is a duplicate of #1383 (which is still open @hstarorg)

**Comment by hstarorg** [comment] 2019-01-14 17:58
@kitsonk Very thanks. So I can tracking the status.

**Comment by HairyRabbit** [comment] 2019-03-25 08:03
Any update here? looks like still not work.

```
deno: 0.3.4
v8: 7.4.238
typescript: 3.3.3333
os: Windows 10 x64
```

use with different partition and set `DENO_DIR` also not work.

**Comment by ry** [comment] 2019-03-25 15:49
See https://github.com/denoland/deno/issues/1383

**Closed by ry** 2019-03-25 15:49 UTC
