### ISSUE TITLE
`fetch()` panics if `--unstable-otel` is specified but `OTEL_EXPORTER_OTLP_PROTOCOL` isn't specified

### ISSUE THREAD

**Issue by uki00a** [denoland/deno#27274] opened 2024-12-08 09:47 UTC
### How to reproduce

```javascript
// main.js
await fetch("https://api.github.com/repos/denoland/deno", {
  headers: {
    "Accept": "application/vnd.github+json",
    "X-GitHub-Api-Version": "2022-11-28",
  },
});
```

```
$ RUST_BACKTRACE=1 deno run --allow-env --allow-net --unstable-otel main.js

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 2.1.3
Args: ["deno", "run", "--allow-env", "--allow-net", "--unstable-otel", "main.js"]

thread 'main' panicked at ext/telemetry/lib.rs:736:42:
called `Option::unwrap()` on a `None` value
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: core::option::unwrap_failed
   4: deno_telemetry::op_otel_instrumentation_scope_enter_builtin::op_otel_instrumentation_scope_enter_builtin::v8_fn_ptr
   5: <unknown>
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

Specifying `OTEL_EXPORTER_OTLP_PROTOCOL=http/json` resolves the above error.

Maybe a duplicate of #27272.

### Environment
- Deno 2.1.3

**Comment by devsnek** [comment] 2024-12-09 14:43
Duplicate of https://github.com/denoland/deno/issues/27272

**Closed by devsnek** 2024-12-09 14:43 UTC
Labels: bug, otel
