### ISSUE TITLE
TS type imports broken in v1.0.1

### ISSUE THREAD

**Issue by fox-cat** [denoland/deno#5704] opened 2020-05-21 10:46 UTC
im no good at opening bug reports but here;
this kind of stuff was working pre-1.0.1, but it isn't working now
![image](https://user-images.githubusercontent.com/30391304/82551187-97674480-9b14-11ea-947f-0f0dc63c3ae5.png)
_not entirely sure what the issue is so i apologize that this isn't the most informative issue request, as well as not-so-good title_

**Comment by bartlomieju** [comment] 2020-05-21 10:51
@fox-cat please provide some source code for reference

**Comment by garronej** [comment] 2020-05-21 16:08
Hi @bartlomieju,
@fox-cat errors come from [EVT](https://evt.land), the module has indeed been broken by v1.0.1.
Investigating the issue. I will report what I found here.

Regards,

**Comment by garronej** [comment] 2020-05-21 17:47
@bartlomieju #5029 is the commit that breaks EVT. 
I think the problems lies in the circular type imports but I am having a hard time isolating the issue as I get so many compile error with Deno but I get no error message when compiling for myself with tsc...

**Comment by ry** [comment] 2020-05-21 17:53
@garronej @fox-cat Do you a way to reproduce the issue? It looks like a typescript error - which is quite odd - there weren't any changes to the type declarations (AFAICT)

**Comment by bartlomieju** [comment] 2020-05-21 18:18
I identified the issue - declaration files are mistakenly analyzed for imports which causes to download referenced libs. I'll have a fix soon.

**Comment by garronej** [comment] 2020-05-21 18:19
@bartlomieju @ry thank you for your reactivity!

**Comment by bartlomieju** [comment] 2020-05-21 19:35
@garronej I think I will need some repro after all; the issue I found might not be related to this one.

**Comment by garronej** [comment] 2020-05-21 19:38
Ok, brb

**Comment by garronej** [comment] 2020-05-21 19:49
```bash
git clone --single-branch --branch 1.7.0 https://github.com/garronej/evt
deno run evt/lib/Ctx.ts
```
With 1.0.0 it compile, with 1.0.1 it doesn't.   
Is it okay?

**Comment by bartlomieju** [comment] 2020-05-21 19:52
@garronej thanks, I will investigate 👍

**Comment by garronej** [comment] 2020-05-21 19:53
@bartlomieju No thank you!

**Comment by bartlomieju** [comment] 2020-05-21 21:24
```
type EvtLike<T> = import("./types/helper/UnpackEvt.ts").EvtLike<T>;
type Evt<T> = import("./types/interfaces/index.ts").Evt<T>;
type CtxLike<T> = import("./types/interfaces/index.ts").CtxLike<T>;
type DoneOrAborted<Result> = import("./types/interfaces/Ctx.ts").DoneOrAborted<Result>;

export type Ctx<Result> = import("./types/interfaces/index.ts").Ctx<Result>;
```

These lines seem to be the root cause of the problem - dynamic imports that expose types. I guess these were picked by `ts.preProcessFile()` and somehow analysed.

I tried changing module graph parsing to include dynamic imports but it did not help with this problem. Calling @kitsonk for opinion

**Comment by kitsonk** [comment] 2020-05-21 22:49
> I tried changing module graph parsing to include dynamic imports but it did not help with this problem.

We should include dynamic imports in the sources... that still _might_ be hard to grab all the ones TypeScript can see itself and use... I mean structures like the above I find crazy work at all, but obviously they do (like why does it not require an `await` 🤷).  I thought we might still need an escape hatch where if the TypeScript compiler finds something it needs we didn't identify, we need to go grab it and return in sync to the compiler.

**Comment by garronej** [comment] 2020-05-21 23:04
@bartlomieju  You are right 👍👍👍
I fixed the module ([v1.73](https://github.com/garronej/evt)) by using [the new TS type only import syntax](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#type-only-imports-and-exports) instead of ``import("...").TheType``.  
However, these changes mean that EVT drops support for TypeScript from 3.4 (Mar 2019) to 3.7 (Feb 2020 )... Some users will have to upgrade TypeScript to keep using EVT in their Node project.  
However, thank you for finding the issue 😊 
I hope it will get fixed in the next Deno release.

**Comment by garronej** [comment] 2020-05-21 23:16
And @bartlomieju @kitsonk, I think maybe you are confusing [dynamic import](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-4.html#dynamic-import-expressions) with [type import](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-2-9.html#import-types) that are two different things although the syntax is the same...

**Comment by kitsonk** [comment] 2020-05-22 01:36
@garronej oh yeah, I had totally forgotten about that! Either way, we should support it.

**Closed** 2020-05-22 17:05 UTC
Labels: bug, cli
