### ISSUE TITLE
Sheband of python 2 scripts within Deno repository

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4556] opened 2020-04-01 05:55 UTC
## Problem

Most Linux distribution provide `python2` as Python 2 program, yet python scripts within the repo still use `#! /usr/bin/env python` making it impossible to run them on Linux outside Docker sandbox.

## Suggestion

Change these shebangs to `#! /usr/bin/env python2`

**Comment by nayeemrmn** [comment] 2020-04-01 11:41
Duplicate of #3294.

**Comment by KSXGitHub** [comment] 2020-04-01 11:44
@nayeemrmn Do you have a suggestion on how to successfully compile Deno on my Linux machine without using Docker?

**Comment by nayeemrmn** [comment] 2020-04-01 11:51
I don't remember `python3` being the default honestly. Try installing differently named packages? Anyway now I don't use the system's python in favour of `pyenv`. I remember doing `pyenv install python2 python3` which installs both and putting `python2` first makes it the default.

**Comment by ry** [comment] 2020-04-01 14:06
@KSXGitHub what’s the error you’re running into?

I’m not keen on assuming “python2” exists.

**Comment by KSXGitHub** [comment] 2020-04-01 14:18
> what’s the error you’re running into?

Many errors, I did not remember, I don't want to reproduce it either.

It would be cool too if someone can set up a [Docker development environment](https://code.visualstudio.com/docs/remote/containers)?

**Comment by hayd** [comment] 2020-04-01 16:14
You need python to point to python2, since v8 build scripts do calls to python. So fixing the shebang just delays the error.

There's no way around it: you need python to point to python2 in your PATH. Virtualenv is the standard solution https://docs.python-guide.org/dev/virtualenvs/

**Comment by ry** [comment] 2020-04-01 16:21
@hayd is right. 

I know everyone is eager to upgrade to python3, but it's simply not possible for us until V8 does. Follow https://bugs.chromium.org/p/chromium/issues/detail?id=942720 if you're interested in that effort.

**Closed by ry** 2020-04-01 16:21 UTC
