### ISSUE TITLE
IANA TimeZone Support

### ISSUE THREAD

**Issue by Lonniebiz** [denoland/deno#1636] opened 2019-02-01 05:55 UTC
deno: 0.2.8
v8: 7.2.502.16
typescript: 3.2.1

Run the following in both node and deno:

```
new Date().toLocaleString("en-US", {timeZone: "America/Halifax"});
new Date().toLocaleString("en-US", {timeZone: "America/New_York"});
new Date().toLocaleString("en-US", {timeZone: "America/Chicago"});
new Date().toLocaleString("en-US", {timeZone: "America/Denver"});
new Date().toLocaleString("en-US", {timeZone: "America/Los_Angeles"});
new Date().toLocaleString("en-US", {timeZone: "America/Anchorage"});
new Date().toLocaleString("en-US", {timeZone: "Pacific/Honolulu"});
```

Deno returns incorrect times. It doesn't appear to support the [IANA](https://www.iana.org/time-zones) time zones yet.

**Comment by kitsonk** [comment] 2019-02-01 06:12
The `Date()` object comes directly from V8.  Deno currently does nothing with it, but the behaviour is quite a lot different:

**Deno**

```
> new Date().toLocaleString("en-US", {timeZone: "Pacific/Honolulu"});
Fri Feb 01 2019 16:09:28 GMT+1000 (AEST)
```

**Node.js v8.11.4**

```
> new Date().toLocaleString("en-US", {timeZone: "Pacific/Honolulu"});
'1/31/2019, 8:09:11 PM'
```

**Chrome 71.0.3578.98**

```
> new Date().toLocaleString("en-US", {timeZone: "Pacific/Honolulu"});
"1/31/2019, 8:04:45 PM"
```

**Comment by Lonniebiz** [comment] 2019-02-01 06:47
Exactly. The "en-US" argument has no effect on the date/time format, and the specified [IANA](https://www.iana.org/time-zones) timezone argument is ignored too.

Maybe V8 depends on its host (slightly) to facilitate this functionality and that slight thing isn't "wired up" yet in deno? Not sure.....

**Comment by Lonniebiz** [comment] 2019-02-02 13:12
Perhaps the spec might reveal something:
http://www.ecma-international.org/ecma-402/5.0/index.html#sup-date.prototype.tolocalestring

**Comment by hayd** [comment] 2019-02-02 18:51
It looks like ICU needs to be included in the build:

https://github.com/phpv8/v8js/issues/306
https://nodejs.org/api/intl.html#intl_embed_the_entire_icu_full_icu

**Comment by Lonniebiz** [comment] 2020-05-24 20:52
A first attempt at compiling deno with ICU embedded:
https://github.com/denoland/deno/issues/1968#issuecomment-633204393

**Comment by ry** [comment] 2020-06-15 16:39
duplicate of https://github.com/denoland/deno/issues/1968

**Closed by ry** 2020-06-15 16:39 UTC

**Comment by nu8** [comment] 2020-09-11 22:10
https://github.com/denoland/deno/issues/3878
