### ISSUE TITLE
"Could not set npm package requirements" when lock:false in deno.json 

### ISSUE THREAD

**Issue by guy-borderless** [denoland/deno#23734] opened 2024-05-08 05:25 UTC
Version: Deno 1.43.1
In my project I have deno.json with `lock: false`. Some dependencies fail to cache with
`Could not set npm package requirements. Error getting a response at https://registry.npmjs.org/@types/node for package "@types/node": An npm specifier not found in cache: "@types/node", --cached-only is specified.
`
or in a different project with the same problem
`Could not set npm package requirements. Error getting response at https://registry.npmjs.org/@tailwindcss/typography for package "@tailwindcss/typography": An npm specifier not found in cache: "@tailwindcss/typography", --cached-only is specified.
`
I don't know why it started happening, I tried deleting the cache dir, downgrading deno, ext.
project still runs fine, this is only in the lsp. 
changing to `lock:true` fixes the issue.

The errors still show in the deno output view, but the dependency is shown as cached in the editor. 
Not sure if related, but I also see this errors which is strange: 
`Hit the language server document preload limit of **100000** file system entries. You may want to use the "deno.enablePaths" configuration setting to only have Deno partially enable a workspace or increase the limit via "deno.documentPreloadLimit". In cases where Deno ends up using too much memory, you may want to lower the limit.
` 
It's not that big a project I just put the 100000 limit to see if this warning shows regardless.

**Comment by dsherret** [comment] 2024-05-08 15:22
Are you talking about in the LSP? This is probably a duplicate of https://github.com/denoland/deno/issues/23659

**Comment by guy-borderless** [comment] 2024-05-08 16:51
indeed

**Comment by guy-borderless** [comment] 2024-05-08 16:57
Actually, having deleted the deno.lock, seems the problem is still there ( just changed to lock:false before and forgot to delete deno.lock)
![image](https://github.com/denoland/deno/assets/100129659/a7154407-0adc-48f6-a5c5-b3789bfaabc6)

**Comment by dsherret** [comment] 2024-05-08 16:59
What happens after you cache the dependencies by running "Deno: Cache dependencies" from the vscode command pallete?

By the way, I wouldn't recommend using `lock: false` with npm packages. It causes everything to be much slower because it doesn't cache the npm resolution in the lockfile.

**Comment by guy-borderless** [comment] 2024-05-08 17:02
> What happens after you cache the dependencies by running "Deno: Cache dependencies" from the vscode command pallete?
> 
> By the way, I wouldn't recommend using `lock: false` with npm packages. It causes everything to be much slower because it doesn't cache the npm resolution in the lockfile.

![image](https://github.com/denoland/deno/assets/100129659/37b77b2a-bbf8-438e-b660-a915e5cda89d)

**Comment by dsherret** [comment] 2024-05-08 17:14
What happens when you go to https://registry.npmjs.org/@types/node? Sometimes the npm registry is flaky. You may need to try caching a few times.

If that doesn't work, do you have a repo that we could try reproducing in?

**Comment by guy-borderless** [comment] 2024-05-08 17:18
> What happens when you go to https://registry.npmjs.org/@types/node? Sometimes the npm registry is flaky. It looks like it's attempting to download then the connection is closed (the error on the last line is just what occurs after caching was attempted). You may need to try caching a few times.
> 
> If that doesn't work, do you have a repo that we could try reproducing 
I tried that, the url always works.

**Closed** 2024-05-08 17:27 UTC
Labels: bug, lsp
