### ISSUE TITLE
Missing LSP auto-completion for Node imports when package.json exists

### ISSUE THREAD

**Issue by quadratz** [denoland/deno#24764] opened 2024-07-27 07:02 UTC
Version: Deno 1.45.4

## Steps to reproduce
1. Create a `package.json` file.
2. Reload the window.
3. The auto-completion does not works.

    ![image](https://github.com/user-attachments/assets/2ea7bcc6-9914-4824-9d2c-56672dd8f21f)

4. Remove the `package.json` file.
5. Reload the window.
6. The auto-completion works normally.

   ![image](https://github.com/user-attachments/assets/85d6a581-522c-4469-a2d6-67ab81683089)

**Comment by nayeemrmn** [comment] 2024-07-31 14:21
@quadratz I can only reproduce this with `DENO_FUTURE=1` (or `"deno.future": true` in settings). Do you have this enabled? Can you share your what's in your Deno output panel when a package.json is there?

**Comment by quadratz** [comment] 2024-07-31 14:47
Sorry, I forgot to mention that `deno.future` is enabled. Here is my VS Code `settings.json`
```json
{
  "deno.enable": true,
  "deno.future": true
}
```

Deno Language Server output when `package.json` does **NOT** exist:
```log
Starting Deno language server...
  version: 1.45.4 (release, x86_64-unknown-linux-gnu)
  executable: /home/qz/.deno/bin/deno
Connected to "Visual Studio Code" 1.91.1
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Resolved package.json: "file:///home/qz/Desktop/A/package.json"
  Resolved .npmrc: "/home/qz/.npmrc"
Server ready.
```

Deno Language Server output when `package.json` exist:
```log
Starting Deno language server...
  version: 1.45.4 (release, x86_64-unknown-linux-gnu)
  executable: /home/qz/.deno/bin/deno
Connected to "Visual Studio Code" 1.91.1
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Resolved package.json: "file:///home/qz/Desktop/A/package.json"
  Resolved .npmrc: "/home/qz/.npmrc"
  Enabled 'bring your own node_modules'.
Server ready.
```

**Comment by nayeemrmn** [comment] 2024-07-31 14:54
@quadratz Okay, `DENO_FUTURE` enables byonm which requires you to manage your own `node_modules` and list your own npm dependencies. The types for `node:` builtins are provided by `npm:@types/node`. So you need to run `npm install --save @types/node`.

**Comment by nayeemrmn** [comment] 2024-07-31 15:00
We're actively looking to make DX improvements in this area but the above solution with `npm` is intended for now. Closing.

**Closed by nayeemrmn** 2024-07-31 15:00 UTC
Labels: bug, lsp

**Comment by quadratz** [comment] 2024-07-31 15:02
I can confirm that installing `@types/node` solves the issue. Thank you.
