### ISSUE TITLE
crete-vite@latest in not working right

### ISSUE THREAD

**Issue by FlashAmarillo** [denoland/deno#16825] opened 2022-11-26 05:11 UTC
hello! i have the problem when i use the node module "create vite@latest" on Windows OS, with deno it asks me for certain permissions and when i start in the command terminal it does not allow me to select the correct tool, it only stays stuck in the vanilla option, is there any way to solve this? i want to select the react option but it does not allow me, is it a problem of deno or the problem is specific to vite?

another detail is that to use the create vite@latest package as indicated in the official vite documentation is with a blank space between the words, why with deno you have to put a hyphen as in the following form? npm:create-vite@latest

**Comment by lino-levan** [comment] 2022-11-26 05:25
I believe this is a duplicate of #15427. 

Specifically this comment: https://github.com/denoland/deno/issues/15427#issuecomment-1267078210

**Comment by bartlomieju** [comment] 2022-11-26 14:01
This is a same problem as in https://github.com/denoland/deno/issues/5945, let's track it there.

> why with deno you have to put a hyphen as in the following form? npm:create-vite@latest

Because `npm init <name>` is an alias to `npm install create-<name>` (https://docs.npmjs.com/cli/v9/commands/npm-init#description) - Deno doesn't support equivalent `npm init` command and it's required to type it out manually.

**Closed by bartlomieju** 2022-11-26 14:01 UTC
