### ISSUE TITLE
feat(tests): better promise error messages

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#25809] opened 2024-09-22 19:01 UTC
When running `deno test` on a large project you may run into the error `error: Promise resolution is still pending but the event loop has already resolved.` at the end of all the tests passing. 

The problem with this is that you have no idea on where this error originated from. You have no idea where to even look, especially when said error only occasionally happens. 

It would be nice when using the --parellel flag, and maybe possibly when not, if this error message told us what file the error originated from.

**Comment by lucacasonato** [comment] 2024-09-23 09:25
Duplicate of #13146

**Closed by lucacasonato** 2024-09-23 09:25 UTC

**Comment by BlackAsLight** [comment] 2024-09-23 10:41
I guess. That issue seems more interested in suppressing the error or adding a random timeout for it, while this issue is more focused on trying to figure out which test caused that error.
