### ISSUE TITLE
Windows: Deno.realPath joins paths with `/` while otherwise it's `\\`

### ISSUE THREAD

**Issue by Ciantic** [denoland/deno#7832] opened 2020-10-05 21:24 UTC
This discrepancy makes comparing file paths very difficult:

```
import { join } from "https://deno.land/std/path/mod.ts";

console.log(Deno.realPathSync("."));
console.log(join("C:", "Source", "Deno", "fsdisrepancy"));
```

Prints out this:

```
C:/Source/Deno/fsdisrepancy
C:\Source\Deno\fsdisrepancy
```

This is very problematic, because a lot of libraries are written using `join`, and if on some point of your code you use realPath then comparing the paths with `===` is not possible. 

Imagine using a library A that uses `realPath`, and library that uses `join` at some point, one can't compare the paths with `===` without sanitization which becomes messy.

**Comment by nayeemrmn** [comment] 2020-10-05 21:27
Duplicate of #5685.

**Closed** 2020-10-05 21:27 UTC
