### ISSUE TITLE
Deno "fatal error in , line 0"

### ISSUE THREAD

**Issue by Jess4Tech** [denoland/deno#11258] opened 2021-07-03 21:07 UTC
I'm writing a project using MySQL and Opine. Recently when I try to run it I get a really weird error, posted below. I'm not sure if code is related to this but if it's needed I can post it. It's a relatively simple backend that manages sessions and gets some data from a database. I'm running the latest build of Windows 10 and the output of `deno --version` is below as well.
```
deno 1.11.4 (release, x86_64-pc-windows-msvc)                        v8 9.1.269.35                                                        typescript 4.3.2
```
```
#
# Fatal error in , line 0
#Check failed: module->status() == kEvaluating || module->status() == kEvaluated.
#
#
#
#FailureMessage Object: 0000000331531D10
==== C stack trace ===============================

CrashForExceptionInNonABICompliantCodeRange [0x00007FF653FCA5CB+620539]
        (No symbol) [0x00007FF653DDF247]
        (No symbol) [0x00007FF653E54C09]
        (No symbol) [0x00007FF653EBA691]
        (No symbol) [0x00007FF653EBA1AB]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FF6542364E1+3159825]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FF65498791C+10832716]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FF6549D12B8+11134184]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FF65493EB7B+10534315]
        CrashForExceptionInNonABICompliantCodeRange [0x00007FF65491BE25+372053]                                                                   (No symbol) [0x00007FF653E493D1]                                     (No symbol) [0x00007FF653DC010A]                                     (No symbol) [0x00007FF653DB7E82]                                     (No symbol) [0x00007FF652EB4C33]                                     (No symbol) [0x00007FF65359BD7E]                                     (No symbol) [0x00007FF6536B49BA]                                     (No symbol) [0x00007FF653571AC7]                                     (No symbol) [0x00007FF65355EB8C]                                     (No symbol) [0x00007FF65355B020]                                     (No symbol) [0x00007FF65355B0BA]                                     CrashForExceptionInNonABICompliantCodeRange [0x00007FF654BAAC0C+13073980]                                                                 BaseThreadInitThunk [0x00007FF869847034+20]                          RtlUserThreadStart [0x00007FF869BE2651+33]
```

**Comment by piscisaureus** [comment] 2021-07-03 21:18
@Jess4Tech 
This looks like a bug in the deno module loader. Can you share the code that triggers this error?

**Comment by Jess4Tech** [comment] 2021-07-03 21:21
App.js is below. Tell me if you need any others
```
import { Config } from './services/config.js';

import { json, opine, Router } from 'https://deno.land/x/opine@1.3.2/mod.ts';

import { ListenAddr } from './services/config.js';

import { Tension } from './api/tension.js';

import { Projects } from './api/projects.js';

import { Authorization, getToken, Key } from './api/authorize.js';

for (let arg of Deno.args) {
  let args = arg.split('=');
  switch (args[0]) {
    case '--cli':
      Config.cli_key = args[1];
      warning('CLI has been enabled');
      break;
    default:
      break;
  }
}

export function info(message) {
  console.log(`%cINFO ${message}`, 'color: #2472C8;');
}

export function warning(message) {
  console.log(`%cWARNING ${message}`, 'color: yellow;');
}

export function error(message) {
  console.log(`%cERROR ${message}`, 'color: red;');
}

const ApiRouter = Router();
ApiRouter.use(json());

const AuthRouter = Router();

AuthRouter.post('/login', async (req, res) => {
  await Authorization.login(req, res);
});

AuthRouter.post('/otac', (req, res) => {
  if (!req.body.user) {
    res.setStatus(400).end();
  } else if (Authorization.isAuthorized(getToken(req), 'adm').auth) {
    let code = Authorization.addOtac(req.body.user);
    res.setStatus(200).json({ otac: code });
  } else {
    res.setStatus(401).end();
  }
});

AuthRouter.delete('/otac', (req, res) => {
  if (Authorization.isAuthorized(getToken(req), 'adm').auth) {
    res.setStatus(200).end();
    Authorization.removeOtac(req.body.user);
  } else {
    res.setStatus(401).end();
  }
});

AuthRouter.get('/authenticated', (req, res) => {
  res.setStatus(200).json(Authorization.isAuthorized(getToken(req), 'plr'));
});

ApiRouter.use('/auth', AuthRouter);

const TensionRouter = Router();

TensionRouter.use(async (req, res, next) => {
  if (Authorization.isAuthorized(getToken(req), 'plr').auth) {
    next();
  } else {
    res.setStatus(401).end();
  }
});

TensionRouter.get('/leaderboard/:dir', async (_req, res) => {
  res.setStatus(200).json(await Tension.leaderboard(req.params.dir == 'asc'));
});

TensionRouter.post('/', async (req, res) => {
  if (Authorization.isAuthorized(getToken(req), 'svr')) {
    res.setStatus(200).end();
    await Tension.setTension(req.body.id, req.body.tension);
  } else {
    res.setStatus(401).end();
  }
});

TensionRouter.get('/', async (req, res) => {
  let data = req.body.id
    ? Tension.getTension(req.body.id)
    : Tension.getTension();
  res.setStatus(200).json(await data);
});

TensionRouter.delete('/', async (req, res) => {
  if (Authorization.isAuthorized(getToken(req), 'svr')) {
    res.setStatus(200).end();
    await Tension.delete(req.body.id);
  } else {
    res.setStatus(401).end();
  }
})

ApiRouter.use('/tension', TensionRouter);

const ProjectRouter = Router();

ProjectRouter.use(async (req, res, next) => {
  if (Authorization.isAuthorized(getToken(req), 'plr').auth) {
    next();
  } else {
    res.setStatus(401).end();
  }
});

ProjectRouter.post('/', async (req, res) => {
  if (Authorization.isAuthorized(getToken(req), 'adm')) {
    res.setStatus(200).end();
    await Projects.addProject(
      req.body.name,
      req.body.description,
      req.body.weight,
    );
  } else {
    res.setStatus(401).end();
  }
});

ProjectRouter.get('/', async (req, res) => {
  res.setStatus(200).json(await Projects.getProjects(req.body.name ? req.body.name : null));
});

ProjectRouter.delete('/', async (req, res) => {
  if (Authorization.isAuthorized(getToken(req), 'adm')) {
    res.setStatus(200).end();
    await Projects.removeProject(req.body.name);
  } else {
    res.setStatus(401).end();
  }
});

ApiRouter.use('/projects', ProjectRouter);

const app = opine();

// Allow all CORS requests, because I'm lazy. What could go wrong?
app.use((req, res, next) => {
  res.set('Access-Control-Allow-Origin', Config.frontendAddr);
  res.set('Access-Control-Allow-Headers', 'Content-Type, Authorization');
  if (req.method == 'OPTIONS') {
    res.setStatus(200).end();
  } else {
    next();
  }
});

app.use('/api/v1', ApiRouter);

app.disable('x-powered-by')
app.listen(ListenAddr);
info(`Listening on ${ListenAddr}`);

console.log(Key.key());
```

**Comment by piscisaureus** [comment] 2021-07-03 21:30
> App.js is below. Tell me if you need any others

I can't reproduce the issue with just app.js.

I suspect that the crash happens immediately when starting up the program; can you confirm that?
If so, it'd be most helpful if you could share all files that have `import`/`export` statements in your project.

**Comment by Jess4Tech** [comment] 2021-07-03 21:35
Yes, it happens immediately after starting it.
/api/authorize.js
```

```

/api/projects.js
```

```

/a

**Comment by Jess4Tech** [comment] 2021-07-03 21:53
Yes, it happens on startup. (Btw sorry I deleted the previous comment, I clicked comment too early and then went to edit it and accidentally pressed the back button.)

/api/authorize.js
```
import { Sessions } from "../services/session_manager.js";
import { Config } from "../services/config.js";

// Alphabet and generator
const alphabet =
  "AaBbCcDdEeFfGgHhIiJjKkLlMmNnOoPpQqRrSsTtUuVvWwXxYyZz1234567890";

function randomAlpha(len = 5) {
  let code = "";
  for (let i = 0; i < len; i++) {
    code += alphabet[Math.floor(Math.random() * alphabet.length)];
  }
  return code;
}

const CookieConfig = {
  httpOnly: true,
  domain: Config.frontendAddr,
  secure: Config.frontendAddr.contains("https"),
  sameSite: "Strict",
};

// Enum for hiearchy of roles
const RoleTiers = {
  // Not Authorized
  nat: 0,
  // Player
  plr: 1,
  // Faction Leader
  ldr: 2,
  // Admin
  adm: 3,
  // Server
  svr: 4,
  // Command Line Interface
  cli: 4,
};

class AuthorizationService {
  constructor(admin, key) {
    this.admins = admin;
    this.key = key;
    this.otacs = [];
  }

  // Add a One Time Access Code to the internal list
  addOtac(ign) {
    if (ign == "") return;

    const code = randomAlpha();

    this.otacs = this.otacs.filter((v, _i, _a) => {
      return v != ign;
    });

    this.otacs.push({
      user: ign,
      otac: code,
      expires: new Date(Date.now() + (5 * 60) * 1000),
    });

    return code;
  }

  // Remove an issued One Time Access Code
  removeOtac(ign) {
    if (ign == "") return;

    this.otacs = this.otacs.filter((v) => {
      return v.user != ign;
    });
  }

  // Remove invalid One Time Access Code(s)
  removeInvalidOtac() {
    this.otacs = this.otacs.filter((val, _i, _arr) => {
      return val.expires > Date.now();
    });
  }

  // Verify crendentials are correct
  verifyCredentials(creds) {
    this.removeInvalidOtac();
    for (const present of this.otacs) {
      console.log(creds, present);
      if (
        present.user.toLowerCase() == creds.user.toLowerCase() &&
        present.otac == creds.otac
      ) {
        return true;
      }
    }

    return false;
  }

  // Check if credentials present, and provide signed JWT if so
  async login(req, res) {
    const token = Sessions.newSession(
      await this.isAdmin(req.body.user) ? RoleTiers.adm : RoleTiers.plr,
    );
    if (this.verifyCredentials(req.body)) {
      res.cookie({
        name: "tkn",
        value: token,
        ...CookieConfig,
      });
      res.setStatus(200).end();
    } else {
      res.setStatus(401).end();
    }
  }

  // Check if username is admin
  async isAdmin(ign) {
    const req = await fetch("https://api.mojang.com/profiles/minecraft", {
      method: "POST",
      headers: { "Content-Type": "application/json" },
      body: JSON.stringify([ign]),
    });
    const uuid = (await req.json())[0];
    return this.admins.indexOf(uuid.id) != -1;
  }

  // Determine if provided credentials in request match the specified role and are valid
  isAuthorized(token, role) {
    if (Config.cli_key && token == Config.cli_key) {
      return { auth: true, prov: "cli" };
    } else if (token == Key.key()) {
      return { auth: true, prov: "svr" };
    } else if (Sessions.sessionPresent(token)) {
      const session = Sessions.getSession(token);
      if (session.tier >= RoleTiers[role]) {
        return { auth: true, prov: role };
      } else {
        return { auth: false };
      }
    } else {
      return { auth: false };
    }
  }
}

class KeyService {
  constructor(regen = 1) {
    this.regen = regen;
  }

  // Test if key is invalid and regenerate if so
  key() {
    if (this.next > Date.now() && this.pkey != undefined) {
      return this.pkey;
    } else {
      this.next = new Date(Date.now() + ((this.regen * 60) * 60) * 1000);
      this.pkey = randomAlpha(128);
      return this.pkey;
    }
  }
}

// Get token from request object
function getToken(req) {
  try {
    if (req.get("Authorization") != "" && req.get("Authorization")) {
      return req.get("Authorization").split(" ")[1];
    } else {
      const cookiesStr = req.get("Cookie").split("; ");
      const cookies = [];
      cookiesStr.forEach((v, _i, _a) => {
        cookies.push(v.split("="));
      });
      for (const val of cookies) {
        if (val[0] == "tkn") {
          return val[1];
        }
      }
      return null;
    }
  } catch (_e) {
    return null;
  }
}

// Initialize and export services
const Authorization = new AuthorizationService(Config.admins, randomAlpha(50));
const Key = new KeyService();

export { Authorization, getToken, Key, RoleTiers };
```

/api/projects.js
```
import { Database } from "../services/database.js";

// Project handler
class ProjectService {
  constructor() {}

  // Execute preliminary commands to make sure database is useable
  async prepare() {
    await Database.conn.execute(`CREATE TABLE IF NOT EXISTS projects(
      name VARCHAR(20) NOT NULL,
      description TEXT NOT NULL,
      weight int(8) NOT NULL,
      PRIMARY KEY (name)
    )`);
  }

  // Add project into database
  async addProject(name, description, weight) {
    await Database.conn.execute(
      "INSERT INTO projects(name, description, weight) VALUES (?, ?, ?)",
      [name, description, weight],
    );
  }

  // Remove project from database
  async removeProject(name) {
    await Database.conn.execute("DELETE FROM projects WHERE name = ?", [name]);
  }

  // Get projects
  async getProjects(name = null) {
    if (name) {
      return await Database.conn.query(
        "SELECT * FROM projects WHERE name = ?",
        [name],
      );
    } else {
      return await Database.conn.query("SELECT * FROM projects");
    }
  }
}

const Projects = new ProjectService();
await Projects.prepare();

export { Projects };
```

/api/tension.js
```
import { Database } from "../services/database.js";

class TensionService {
  constructor() {}

  async prepare() {
    await Database.conn.execute(`CREATE TABLE IF NOT EXISTS tensions (
            id int(8) NOT NULL AUTO_INCREMENT,
            tension int(8),
            PRIMARY KEY (id)
        )`);
  }

  async delete(id) {
    await Database.conn.execute("DELETE FROM tensions WHERE id = ?", [id]);
  }

  async setTension(id, tension) {
    await Database.conn.execute(
      "REPLACE INTO tensions(id, tension) VALUES (?, ?)",
      [id, tension],
    );
  }

  async getTension(id = null) {
    if (id) {
      return (await Database.conn.query(
        "SELECT tension FROM tensions WHERE id = ?",
        [id],
      ))[0];
    } else {
      return await Database.conn.query("SELECT * FROM tensions");
    }
  }

  async leaderboard(ascending) {
    const data = await this.getTension();
    if (ascending) {
      return data.sort((a, b) => {
        if (a.tension > b.tension) {
          return 1;
        } else if (a.tension < b.tension) {
          return -1;
        } else {
          return 0;
        }
      });
    } else {
      return data.sort((a, b) => {
        if (a.tension < b.tension) {
          return 1;
        } else if (a.tension > b.tension) {
          return -1;
        } else {
          return 0;
        }
      });
    }
  }
}

const Tension = new TensionService();
await Tension.prepare();

export { Tension };
```

/services/config.js
```
let config;

const defaultConfig = {
  listen: {
    addr: "localhost",
    port: 10000,
  },
  frontendAddr: "http://localhost:10001",
  followers: [],
  admins: [],
};

try {
  config = Deno.readTextFileSync("./config.json");
} catch (_e) {
  config = JSON.stringify(defaultConfig);
  const encoder = new TextEncoder();
  const data = encoder.encode(JSON.stringify(defaultConfig));
  Deno.writeFileSync("./config.json", data);
}

const Config = JSON.parse(config);

const TestDatabaseCredentials = {
  hostname: "10.0.0.55",
  username: "terra_user",
  password: "password",
  database: "terra",
};

const ListenAddr = `${Config.listen.addr}:${Config.listen.port}`;

export { Config, ListenAddr, TestDatabaseCredentials };
```

/services/database.js
```
import { Client } from "https://deno.land/x/mysql/mod.ts";
import { error } from "../app.js";

import { TestDatabaseCredentials } from "./config.js";

const Types = {
  testingReal: 1,
  production: 3,
};

class DatabaseHandler {
  constructor() {}

  BlankDatabase() {
    this.conn = {
      query: (_query, _args = []) => {},
      execute: (_query, _args = []) => {},
    };
  }

  // Connect to testing database
  async TestingDatabase() {
    this.conn = await new Client().connect({
      hostname: TestDatabaseCredentials.hostname,
      username: TestDatabaseCredentials.username,
      db: TestDatabaseCredentials.database,
      password: TestDatabaseCredentials.password,
      poolSize: 5,
    });
  }

  // Connect to production database
  async ProductionDatabase() {
    const envs = [
      Deno.env.get("HOST"),
      Deno.env.get("USER"),
      Deno.env.get("PASSWORD"),
      Deno.env.get("DATABASE"),
    ];
    if (envs.indexOf(undefined) != -1) {
      error("One or more required environmental variables were not set");
    } else {
      this.conn = await new Client().connect({
        hostname: envs[0],
        username: envs[1],
        password: envs[2],
        db: envs[3],
        poolSize: 5,
      });
    }
  }

  // Connect and prepare database for use
  async prepare(testing) {
    switch (Types[testing]) {
      case 1:
        try {
          await this.TestingDatabase();
        } catch (_e) {
          error("Failed to connect to the testing database");
        }
        break;
      case 3:
        try {
          await this.ProductionDatabase();
        } catch (_e) {
          error(
            "Failed to connect to the production database, attempting to connect to the testing database",
          );
          try {
            await this.TestingDatabase();
          } catch (_e) {
            error("Failed to connect to the testing database, exiting");
            Deno.exit(-1);
          }
        }
        break;
      default:
        error(`Internal error, type ${testing} not recognized`);
        break;
    }
  }
}

const Database = new DatabaseHandler();
await Database.prepare(
  Deno.args.indexOf("--test-database") > -1 ? "testingReal" : "production",
);

export { Database, DatabaseHandler };
```

/services/session_manager.js
```
import { v4 } from "https://deno.land/std/uuid/mod.ts";

class Session {
  // "id" is the identifer of the session, with renew being the session length in a period of hours. Defaults to 1
  constructor(id, tier, renew = 1) {
    this.renew = (renew * 60 * 60 * 1000);
    this.id = id;
    this.tier = tier;
    this.validUntil = Date.now() + this.renew;
  }

  // Check if session is still valid
  valid() {
    return this.validUntil > Date.now();
  }

  // Renew session by interval specified in constructor
  renew() {
    this.validUntil = Date.now() + this.renew;
  }
}

class SessionManager {
  constructor(renew = 1) {
    this.renew = renew;
    this.sessions = [];
    this.toRemove = [];
  }

  removeInvalidSessions() {
    this.sessions = this.sessions.filter((v, _i, _a) => {
      return v.valid() && this.toRemove.indexOf(v.id) == -1;
    });
  }

  sessionPresent(id) {
    this.removeInvalidSessions();
    for (const session of this.sessions) {
      if (session.id == id) {
        return true;
      }
    }
    return false;
  }

  newSession(tier) {
    this.removeInvalidSessions();
    const session = new Session(v4.generate(), tier, this.renew);
    if (this.sessionPresent(session)) {
      return this.newSession();
    }
    this.sessions.push(session);
    return session.id;
  }

  invalidateSession(id) {
    this.toRemove.push(id);
  }

  getSession(id = null) {
    this.removeInvalidSessions();
    return id ? this.sessions.filter((v, _i, _a) => v.id == id) : this.sessions;
  }
}

const Sessions = new SessionManager();
export { Sessions };
```
(I think that's all of them.)

**Comment by piscisaureus** [comment] 2021-07-04 18:58
I've pushed a reduced test case to https://github.com/piscisaureus/deno_import_bug/commit/0854bd97c5697c2cd524bd2ae241fb4f998d05e9

**Comment by Jess4Tech** [comment] 2021-07-04 21:50
> I've pushed a reduced test case to [piscisaureus/deno_import_bug@0854bd9](https://github.com/piscisaureus/deno_import_bug/commit/0854bd97c5697c2cd524bd2ae241fb4f998d05e9)

That's just plain impressive you could do that. Now we just have to fix it! Not sure if I'll be of much use there though

**Comment by piscisaureus** [comment] 2021-07-05 14:05
This probably a V8 bug; I can also reproduce it in node.js: 

```
D:\>git clone git@github.com:piscisaureus/deno_import_bug

D:\>node --version
v16.4.1

D:\>git clone git@github.com:piscisaureus/deno_import_bug
Cloning into 'deno_import_bug'...
remote: Enumerating objects: 10, done.
remote: Counting objects: 100% (10/10), done.
remote: Compressing objects: 100% (8/8), done.
remote: Total 10 (delta 1), reused 10 (delta 1), pack-reused 0
Receiving objects: 100% (10/10), done.
Resolving deltas: 100% (1/1), done.

D:\>cd deno_import_bug

D:\deno_import_bug>node app.js


#
# Fatal error in , line 0
# Check failed: module->status() == kEvaluated.
#
#
#
#FailureMessage Object: 0000007E0C2FEA40
 1: 00007FF61827A73F v8::internal::CodeObjectRegistry::~CodeObjectRegistry+111711
 2: 00007FF61819AC7F v8::CFunctionInfo::HasOptions+7039
 3: 00007FF618EC1E12 V8_Fatal+162
 4: 00007FF618824DFF v8::internal::SerializeStackFrameInfo+6879
 5: 00007FF618B46518 v8::internal::Builtins::builtin_handle+279864
 6: 00007FF618C27721 v8::internal::SetupIsolateDelegate::SetupHeap+461073
 7: 00007FF618C6E812 v8::internal::SetupIsolateDelegate::SetupHeap+752130
 8: 00007FF618BDFB14 v8::internal::SetupIsolateDelegate::SetupHeap+167172
 9: 00007FF618BBE23B v8::internal::SetupIsolateDelegate::SetupHeap+29739
10: 00007FF618A7C882 v8::internal::Execution::CallWasm+1906
11: 00007FF618A7C98B v8::internal::Execution::CallWasm+2171
12: 00007FF618A7D3FA v8::internal::Execution::TryCall+378
13: 00007FF618A59CF5 v8::internal::MicrotaskQueue::RunMicrotasks+501
14: 00007FF618A59A50 v8::internal::MicrotaskQueue::PerformCheckpoint+32
15: 00007FF6182A9DD6 node::CallbackScope::~CallbackScope+710
16: 00007FF6182A9B7E node::CallbackScope::~CallbackScope+110
17: 00007FF6181F5D50 v8::base::CPU::has_sse+33184
18: 00007FF6182DE197 uv_timer_stop+775
19: 00007FF6182DA98B uv_async_send+331
20: 00007FF6182DA11C uv_loop_init+1292
21: 00007FF6182DA2BA uv_run+202
22: 00007FF6182A9565 node::SpinEventLoop+309
23: 00007FF6181C5023 EVP_CIPHER_CTX_buf_noconst+53651
24: 00007FF61823FF1D node::Start+221
25: 00007FF61806844C RC4_options+346956
26: 00007FF619120398 v8::internal::compiler::RepresentationChanger::Uint32OverflowOperatorFor+14456
27: 00007FF8F59E7034 BaseThreadInitThunk+20
28: 00007FF8F5B22651 RtlUserThreadStart+33
```

**Comment by piscisaureus** [comment] 2021-07-05 14:26
Upstream bug report: https://bugs.chromium.org/p/v8/issues/detail?id=11949

**Comment by bartlomieju** [comment] 2021-12-01 14:04
According to https://bugs.chromium.org/p/v8/issues/detail?id=11949 this issue should already be fixed, so I'm going to tentatively close it. Please comment if the issue occurs again.

**Closed by bartlomieju** 2021-12-01 14:04 UTC
Labels: bug, core, upstream
