### ISSUE TITLE
Tryng to replicate shinylive webr

### ISSUE THREAD

**Issue by josezea** [denoland/deno#23117] opened 2024-03-28 17:18 UTC
https://tutorials.thecoatlessprofessor.com/quarto-webr-with-quarto-shinylive/

It appears this error when I execute quarto add quarto-ext/shinylive

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.37.2
Args: ["C:\\Program Files\\Quarto\\bin\\tools\\x86_64\\deno", "run", "--unstable", "--no-config", "--cached-only", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--importmap", "C:\\Program Files\\Quarto\\bin\\vendor\\import_map.json", "C:\\Program Files\\Quarto\\bin\\quarto.js", "add", "quarto-ext/shinylive"]

thread 'main' panicked at cli\args\mod.rs:525:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by HaotianQian** [comment] 2024-03-29 02:58
Try on another computer, download quarto manually on website and "choose for all users on this machine" during setup.

**Comment by lucascat7** [comment] 2024-03-29 03:04
Try on another computer, download quarto manually on website and "choose for all users on this machine" during setup.
It may work.

**Comment by lucacasonato** [comment] 2024-06-12 10:31
Closing as dupe of https://github.com/denoland/deno/issues/24137

**Closed by lucacasonato** 2024-06-12 10:31 UTC
