### ISSUE TITLE
Deno Emit Typings Not Useable In Node.js

### ISSUE THREAD

**Issue by Skillz4Killz** [denoland/deno#11661] opened 2021-08-12 03:33 UTC
If possible can Deno.emit just include all typings from other files inside it's output, instead of importing them from other files. Currently, it adds imports using `.ts` and my theory is that these imports then somehow break the behavior in node.js or VSC making it so the library is not able to have proper typings available.

For example:
![image](https://user-images.githubusercontent.com/23035000/129134366-e1599d8a-7e48-47a9-86c4-4a8e1c35d834.png)

These imports should just write out the types directly in this file at the top instead of importing them.

**Comment by kitsonk** [comment] 2021-08-12 04:17
Effectively a duplicate of #3385.  Emitting types for bundles would allow type bundling requested here.

**Closed by kitsonk** 2021-08-12 04:17 UTC
Labels: duplicate
