### ISSUE TITLE
`integration::node_compat_tests::node_compat_tests` is flaky

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#18653] opened 2023-04-11 05:20 UTC
```

failures:

---- integration::node_compat_tests::node_compat_tests stdout ----
thread 'integration::node_compat_tests::node_compat_tests' panicked at 'assertion failed: `(left == right)`
  left: `Some(0)`,
 right: `Some(1)`', cli/tests/integration/node_compat_tests.rs:17:3
```

https://github.com/denoland/deno/actions/runs/4664060803/jobs/8255956913?pr=18649#step:35:4996

**Comment by GJZwiers** [comment] 2023-04-11 19:09
I think it is a duplicate of https://github.com/denoland/deno/issues/18586

**Closed** 2023-04-13 14:48 UTC
Labels: flaky
