### ISSUE TITLE
Bug: [Deno 1.25.0 Deno.serve(...)] Deno panicked while using "--watch" after restart after file change

### ISSUE THREAD

**Issue by sagea** [denoland/deno#15756] opened 2022-09-03 23:19 UTC
### Description
The issue below happens in these scenarios:
1. Running the server.ts with --watch and modifying the server.ts file triggering a restart.
2. Running the same file twice in separate terminal windows

Both of these cases result in the exact same message.

**I added reproduce steps below the stack trace**

### Error Log W/ RUST_BACKTRACE
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.25.0
Args: ["deno", "run", "-A", "--unstable", "--watch", "test-server.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ext/flash/lib.rs:1316:42
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: <extern "C" fn(A0) .> R as v8::support::CFnFrom<F>>::mapping::c_fn
   5: __ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEENS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EEPmi
   6: __ZN2v88internal21Builtin_HandleApiCallEiPmPNS0_7IsolateE
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

### Error Log original
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.25.0
Args: ["deno", "run", "-A", "--unstable", "--watch", "test-server.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ext/flash/lib.rs:1316:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

### Exact Repro Steps
**Scenario 1: --watch**
1. Create new project folder `mkdir project-test-watch`
2. Navigate to project folder `cd project-test-watch`
3. Create server.ts file
```
echo "
Deno.serve(
  (request) => {
    console.log('url', request.url);
    const url = new URL(request.url);
    console.log('url', url);
    return new Response('hehe');
  },
  { port: 4500 },
);
" > server.ts
```
4. Start server in watch mode `RUST_BACKTRACE=1 deno run -A --unstable --watch server.ts`
5. Modify the server.ts file `echo "\n // update file :)" >> server.ts`
EXPECTED:
Server Restarts fine
ACTUAL:
The error above shows

**Scenario 2: Running file twice**
1. Follow Scenario 1's steps 1-3;
2. Start server `RUST_BACKTRACE=1 deno run -A --unstable server.ts` **--watch is not needed**
3. Open up a another terminal window
4. Run the same deno script to start the server (Make sure the other one is still running) `RUST_BACKTRACE=1 deno run -A --unstable server.ts`
EXPECTED:
Some error akin to `port already in use`
ACTUAL
The Second tab from step 4 outputs the error above.

**Comment by crowlKats** [comment] 2022-09-03 23:27
Duplicate of #15646

**Closed by crowlKats** 2022-09-03 23:27 UTC
