### ISSUE TITLE
deno run fails with "Unsupported scheme" error for tasks containing colons

### ISSUE THREAD

**Issue by g4yamanaka** [denoland/deno#25256] opened 2024-08-28 10:09 UTC
In Deno version 1.46, it's now possible to run tasks using `deno run`. However, there is an issue when running tasks that contain colons (e.g., `lint:fix`). When attempting to run such tasks using `deno run`, an "Unsupported scheme" error occurs.

This error seems to arise because `deno run` interprets the colon as part of a scheme. However, using colons in task names is a common convention, and these tasks work fine with the `deno task` command. It would be beneficial if deno run could handle tasks with colons in the same way, without resulting in an error.

**Comment by marvinhagemeister** [comment] 2024-08-28 10:49
Duplicate of https://github.com/denoland/deno/issues/25232 .

This was fixed yesterday in `main` and will be part of the next release. You can try out a canary build in the meantime by running:

```sh
deno upgrade --canary
```

**Closed by marvinhagemeister** 2024-08-28 10:49 UTC
