### ISSUE TITLE
Feature request: Also parse flags passed after the command and arguments when running the Deno executable

### ISSUE THREAD

**Issue by hex3928** [denoland/deno#10097] opened 2021-04-09 20:45 UTC
*This works*
`deno run --allow-write writeToFile.ts`

*But this does not, it just ignores the flag*
`deno run writeToFile.ts --allow-write`

It should at least throw a warning or something, not just silently ignore flags passed like in the second example. Please adjust the parser in such a way, that the second example will also work.

**Comment by nayeemrmn** [comment] 2021-04-09 20:50
Duplicate of #2708.



> _But this does not, it just ignores the flag_
> `deno run writeToFile.ts --allow-write`

It's not ignored, it's passed to the script in `Deno.args`. Please read through https://deno.land/manual@v1.8.3/getting_started/command_line_interface#script-arguments. This behaviour matches Node or any other scripting runtime.

**Comment by kitsonk** [comment] 2021-04-09 21:03
As mentioned duplicate of #2708

**Closed by kitsonk** 2021-04-09 21:03 UTC
Labels: duplicate

**Comment by hex3928** [comment] 2021-04-10 13:40
Oh it's passed to the script, sorry didn't know that, makes sense perfectly then
