### ISSUE TITLE
this.port.unref is not a function Deno Canary

### ISSUE THREAD

**Issue by rroblf01** [denoland/deno#23252] opened 2024-04-06 10:21 UTC
Version: Deno canary
OS: Windows 11
```
deno upgrade --canary
Looking up latest canary version
Found latest version 0e4018a25bf4fb923f83c796b834ef718f6f75f9
Downloading https://dl.deno.land/canary/0e4018a25bf4fb923f83c796b834ef718f6f75f9/deno-x86_64-pc-windows-msvc.zip
Deno is upgrading to version 0e4018a25bf4fb923f83c796b834ef718f6f75f9
Upgraded successfully
```

I was trying to run an ng serve (Angular 17.3.2) with deno canary, but I'm getting this error.

```
deno run -A npm:@angular/cli serve
⠋ Building...
error: Uncaught (in promise) TypeError: this.port.unref is not a function
    at WorkerInfo.unref (file:///C:/Users/Sheik/Documents/proyectos/ricardorobles/node_modules/piscina/dist/src/index.js:326:19)
    at onReady (file:///C:/Users/Sheik/Documents/proyectos/ricardorobles/node_modules/piscina/dist/src/index.js:486:28)
    at NodeWorker.<anonymous> (file:///C:/Users/Sheik/Documents/proyectos/ricardorobles/node_modules/piscina/dist/src/index.js:496:70)
    at NodeWorker.emit (ext:deno_node/_events.mjs:386:28)
    at NodeWorker.#pollMessages (node:worker_threads:159:12)
    at eventLoopTick (ext:core/01_core.js:168:7
```

In case anyone wants to see more details of the project I was trying to run, this is
https://github.com/rroblf01/ricardorobles

**Comment by bartlomieju** [comment] 2024-04-07 05:22
@littledivy @satyarohith can you folks investigate it?

**Comment by littledivy** [comment] 2024-04-07 06:51
Duplicate of https://github.com/denoland/deno/issues/23002 but lets track it here

**Closed** 2024-04-09 18:15 UTC
Labels: needs investigation, node compat, node API polyfill
