### ISSUE TITLE
deno run with npm specifier should resolve scopes in deno.json

### ISSUE THREAD

**Issue by sant123** [denoland/deno#24276] opened 2024-06-19 19:30 UTC
Hi, I'm not sure if this is currently possible but take a look on this script:

`deno run --allow-read --allow-env --allow-sys npm:@swc/cli/swc compile-me.ts`

The `@swc/cli` module has a peer dependency to `@swc/core`, currently is resolving the latest version and is fine for me.

However in the case I should need a different `@swc/core` version how can I do it?

I have tried this in my deno.json:

```json
{
  "scopes": {
    "@swc/cli/swc": {
      "@swc/core": "npm:@swc/core@1.6.1"
    }
  }
}
```

But still resolves the latest version `@swc/core@1.6.3`, not `@swc/core@1.6.1`.

In case you need it, this is the content of `compile-me.ts` file:

```ts
export function add(a: number, b: number) {
    return a + b;
}

```

Thanks.

**Comment by dsherret** [comment] 2024-06-19 20:09
I think #18191 would cover this?

**Comment by dsherret** [comment] 2024-06-19 20:10
FWIW, you can hackily force this behaviour at the moment by modifying a lockfile.

**Comment by sant123** [comment] 2024-06-20 01:35
Ohh there is an issue already, @dsherret how can I do it with the lockfile? However the deno.json file has `lock: false` so there is no deno.lock in my directory.

**Comment by lucacasonato** [comment] 2024-06-20 07:23
Closing as dupe of https://github.com/denoland/deno/issues/18191

But hopefully @dsherret can respond regardless 😀

**Closed by lucacasonato** 2024-06-20 07:23 UTC
