### ISSUE TITLE
Considering making the deno-cli crate also available as a library

### ISSUE THREAD

**Issue by lgalabru** [denoland/deno#9728] opened 2021-03-09 05:05 UTC
What is the general sentiment on having the `deno-cli` crate producing a `lib` that can be imported by other projects? I think that taking this path would also help making this module lighter - for instance, subproject like the LSP could become a separate crate consuming the `deno-cli` module, etc.

**Comment by lgalabru** [comment] 2021-03-09 05:22
I see. It feels like this decision is locking a good amount value in the `cli` bin (GraphBuilder, Typescript transpilation, etc) that could be used by community members for creating more tooling and enriching the Deno ecosystem.  
Is this sentiment shared by others? What would be the tradeoff being made by making this crate available as a lib? Interfaces breaking is fine IMHO, developers could just be pinning in their projects the versions they want to support.

**Comment by Lispython** [comment] 2021-03-09 09:41
I have similar suggestion. I'm working on integration Typescript runtime into [devrc](https://github.com/devrc-hub/devrc) project and I encountered exactly the same problems as @lgalabru. There are a lot of code that can be reusable. The biggest deno_runtime disadvantage is that it hasn't typescript integration.

**Comment by yarkeeb** [comment] 2021-03-09 13:42
+1 for this. This library could be very useful for my upcoming projects.

**Comment by kitsonk** [comment] 2021-03-09 22:31
Duplicate of #7928

**Closed by kitsonk** 2021-03-09 22:31 UTC
Labels: duplicate
