### ISSUE TITLE
Deno Panic report

### ISSUE THREAD

**Issue by omar2205** [denoland/deno#15724] opened 2022-09-01 10:49 UTC
I tried building this simple app on two servers with deno panic.

```ts
// main.ts
import fast, {
  type Context,
} from 'https://deno.land/x/fast@4.0.0-alpha.3/mod.ts'

import {
  getCookies,
} from 'https://deno.land/std@0.150.0/http/cookie.ts'

const app = fast()

app.get('/', async (ctx: Context) => {

  const h = await ctx.request.headers
  const cookie = getCookies(h)
  console.log(cookie)

  return 'no id'
})

await app.serve()
```

``` 
RUST_BACKTRACE=1
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.25.0
Args: ["deno", "compile", "main.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/eszip-0.25.0/src/v2.rs:512:60
stack backtrace:
   0: rust_begin_unwind
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
   1: core::panicking::panic_fmt
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
   2: core::panicking::panic
             at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
   3: eszip::v2::EszipV2::from_graph::visit_module
   4: eszip::v2::EszipV2::from_graph::visit_module
   5: eszip::v2::EszipV2::from_graph
   6: deno::compile_command::{{closure}}
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: deno::main::{{closure}}
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: deno_runtime::tokio_util::run_local
  11: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**full backtrace**
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.25.0
Args: ["deno", "compile", "main.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/eszip-0.25.0/src/v2.rs:512:60
stack backtrace:
   0:     0x5628386393bd - std::backtrace_rs::backtrace::libunwind::trace::h8217d0a8f3fd2f41
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
   1:     0x5628386393bd - std::backtrace_rs::backtrace::trace_unsynchronized::h308103876b3af410
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x5628386393bd - std::sys_common::backtrace::_print_fmt::hc208018c6153605e
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:66:5
   3:     0x5628386393bd - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf89a7ed694dfb585
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:45:22
   4:     0x56283866449c - core::fmt::write::h21038c1382fe4264
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/fmt/mod.rs:1197:17
   5:     0x562838630981 - std::io::Write::write_fmt::h7dbb1c9a3c254aef
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/io/mod.rs:1672:15
   6:     0x56283863b0c5 - std::sys_common::backtrace::_print::h4e8889719c9ddeb8
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:48:5
   7:     0x56283863b0c5 - std::sys_common::backtrace::print::h1506fe2cb3022667
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:35:9
   8:     0x56283863b0c5 - std::panicking::default_hook::{{closure}}::hd9d7ce2a8a782440
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:295:22
   9:     0x56283863ade6 - std::panicking::default_hook::h5b16ec25444b1b5d
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:314:9
  10:     0x5628389b5ed4 - deno::setup_panic_hook::{{closure}}::h341d5a693a381a24
  11:     0x56283863b76a - std::panicking::rust_panic_with_hook::hb0138cb6e6fea3e4
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:702:17
  12:     0x56283863b569 - std::panicking::begin_panic_handler::{{closure}}::h4cb67095557cd1aa
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:586:13
  13:     0x562838639874 - std::sys_common::backtrace::__rust_end_short_backtrace::h2bfcac279dcdc911
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/sys_common/backtrace.rs:138:18
  14:     0x56283863b2d9 - rust_begin_unwind
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:584:5
  15:     0x5628386618e3 - core::panicking::panic_fmt::h1de71520faaa17d3
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:142:14
  16:     0x56283866172d - core::panicking::panic::h467ee1bf554babeb
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/panicking.rs:48:5
  17:     0x562838b129c5 - eszip::v2::EszipV2::from_graph::visit_module::hf8cde778538d759c
  18:     0x562838b12100 - eszip::v2::EszipV2::from_graph::h6f0b31198b05afbe
  19:     0x5628389a8b18 - deno::compile_command::{{closure}}::hfc19cadbb984a73a
  20:     0x56283884e45a - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha891be8286511a5f
  21:     0x5628389b91db - deno::main::{{closure}}::h31e232cb60ae3fda
  22:     0x56283882d52f - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h6f5ae49f0f985a84
  23:     0x56283869309f - deno_runtime::tokio_util::run_local::hf92ebef368c4d8de
  24:     0x5628389b60f9 - deno::main::h3e6f490f5e940ede
  25:     0x5628386c7b5d - std::sys_common::backtrace::__rust_begin_short_backtrace::hf665e2180d8d8a39
  26:     0x5628386cba4b - std::rt::lang_start::{{closure}}::hc15c712b31ddab75
  27:     0x562838626a9e - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::h4937aaa125c8d4b2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/core/src/ops/function.rs:280:13
  28:     0x562838626a9e - std::panicking::try::do_call::h6f5c70e8b0a34f92
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  29:     0x562838626a9e - std::panicking::try::h68766ba264ecf2e2
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  30:     0x562838626a9e - std::panic::catch_unwind::hc36033d2f9cc04af
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  31:     0x562838626a9e - std::rt::lang_start_internal::{{closure}}::h78c037f4a1a28ded
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:48
  32:     0x562838626a9e - std::panicking::try::do_call::he6e1fffda4c750ee
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:492:40
  33:     0x562838626a9e - std::panicking::try::h48a77ddbb2f4c87a
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panicking.rs:456:19
  34:     0x562838626a9e - std::panic::catch_unwind::hfa809b06a550a9e7
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/panic.rs:137:14
  35:     0x562838626a9e - std::rt::lang_start_internal::h4db69ed48eaca005
                               at /rustc/4b91a6ea7258a947e59c6522cd5898e7c0a6a88f/library/std/src/rt.rs:128:20
  36:     0x5628389cf182 - main
  37:     0x7f4702c52d90 - <unknown>
  38:     0x7f4702c52e40 - __libc_start_main
  39:     0x562837623029 - _start
  40:                0x0 - <unknown>
```

**Comment by littledivy** [comment] 2022-09-01 10:50
Duplicate of https://github.com/denoland/deno/pull/15672

The fix for this will be release tomorrow.

**Closed by littledivy** 2022-09-01 10:50 UTC
