### ISSUE TITLE
LSP: The current snapshot version is missing - error code: -32603

### ISSUE THREAD

**Issue by c4spar** [denoland/deno#9716] opened 2021-03-07 14:08 UTC
Not sure if this is related to #9348.

I am working on two projects at the same time and project `B` imports a local file from project `A` (for development only).
When I change the file in project `A`, I get the following LSP error in project `B`.
I think that the LSP is not updated when an imported file has changed that is outside the project directory.

```
Starting Deno language server...
  version: 1.8.0 (release, x86_64-apple-darwin)
Connected to "Visual Studio Code" 1.54.1
language server initialized
Server ready.
Error processing TypeScript request: Error: The current snapshot version is missing.
  Args: "GetChangeRangeArgs { specifier: "file:///******/deno-cliffy/command/command.ts", old_length: 50291, old_version: "1615124690846", version: "1615124762886" }"
    at processResponse (deno:core/core.js:212:11)
    at Object.jsonOpSync (deno:core/core.js:236:12)
    at ScriptSnapshot.getChangeRange (deno:cli/tsc/99_main_compiler.js:224:19)
    at acquireOrUpdateDocument (deno:cli/tsc/00_typescript.js:123008:133)
    at Object.updateDocumentWithKey (deno:cli/tsc/00_typescript.js:122974:20)
    at Object.getOrCreateSourceFileByPath [as getSourceFileByPath] (deno:cli/tsc/00_typescript.js:149726:49)
    at tryReuseStructureFromOldProgram (deno:cli/tsc/00_typescript.js:107087:28)
    at Object.createProgram (deno:cli/tsc/00_typescript.js:106618:29)
    at synchronizeHostData (deno:cli/tsc/00_typescript.js:149648:26)
    at Object.getReferencesAtPosition (deno:cli/tsc/00_typescript.js:149911:13)
[Error - 14:46:04] Request codeLens/resolve failed.
  Message: Internal error
  Code: -32603
```

**Comment by kitsonk** [comment] 2021-03-07 20:26
Duplicate of #9438 

Will be fixing it this week.

**Closed by kitsonk** 2021-03-07 20:26 UTC
Labels: duplicate
