### ISSUE TITLE
[lsp] Deno 1.9.2 - Importing exported type declarations doesn't work

### ISSUE THREAD

**Issue by rracariu** [denoland/deno#10483] opened 2021-05-03 18:28 UTC
The following:
```
import type {HVal} from 'https://cdn.skypack.dev/haystack-core?dts'
import {HNum} from 'https://cdn.skypack.dev/haystack-core?dts'

function num() : HVal {
    return HNum.make(100)
}
console.log(num().getKind())
```

Gives this error in the VSCode plugin:
```
Module '"https://cdn.skypack.dev/haystack-core?dts"' has no exported member 'HVal'. Did you mean to use 'import HVal from "https://cdn.skypack.dev/haystack-core?dts"' instead?deno-ts(2614)
```

Removing the `type` from the import fixes the issue. But the type declaration is available and downloaded in the cache.

**Comment by kitsonk** [comment] 2021-05-03 19:55
Duplicate of #10031 which is already fixed and should be available in canary.

**Closed by kitsonk** 2021-05-03 19:55 UTC
