### ISSUE TITLE
navigator.gpu.requestAdapter() logs messages to stdout

### ISSUE THREAD

**Issue by andykais** [denoland/deno#9949] opened 2021-04-01 02:20 UTC
a script like the following:
```ts
// gpu.ts
const gpu_adapter = await navigator.gpu.requestAdapter()
```
will print a message to the terminal via some internal webgpu code
```bash
$ deno run --unstable gpu.ts
MESA-INTEL: warning: Performance support disabled, consider sysctl dev.i915.perf_stream_paranoid=0
```

I would like it to either configure the webgpu logging, or just never let it log to stdout

**Comment by DjDeveloperr** [comment] 2021-04-01 02:51
I also see some warnings in stdout sometimes, like:

![img](https://cdn.discordapp.com/attachments/688040863313428503/818799539301122098/unknown.png)

There should be a way to configure that.

**Comment by Ar37-rs** [comment] 2021-04-01 02:52
The following environment variables can be used to configure how the framework examples run:

    WGPU_BACKEND

    Options: vulkan, metal, dx11, dx12, gl, webgpu

    If unset a default backend is chosen based on what is supported by your system.

    WGPU_POWER_PREF

    Options: low, high

    If unset a low power adapter is preferred.

source: https://github.com/gfx-rs/wgpu-rs

**Comment by F3n67u** [comment] 2021-08-21 15:06
@andykais Could you help to confirm that this is still happening? I cannot reproduce on my side.
```
 % cat gpu.ts 
const gpu_adapter = await navigator.gpu.requestAdapter();
 % deno run --unstable gpu.ts
Check file:///deno/gpu.ts
 % deno --version
deno 1.13.1 (release, x86_64-apple-darwin)
v8 9.3.345.11
typescript 4.3.5
```

**Comment by littledivy** [comment] 2021-08-21 16:34
It is only reproducible with the right hardware. 
![stillhappens](https://user-images.githubusercontent.com/34997667/130328701-d4bfc165-cf5d-4d1c-beef-7dbfe8b4b376.png)

**Comment by littledivy** [comment] 2024-06-13 11:45
Is this still happening with 1.44.2? Unfortunately, I don't have that hardware anymore to test

**Comment by crowlKats** [comment] 2024-07-30 15:09
Closing as I believe this to be fixed, as changes in wgpu were made related to logging. Please re-open if you are encountering this again.

**Closed by crowlKats** 2024-07-30 15:09 UTC
Labels: bug, webgpu

**Comment by andykais** [comment] 2024-08-01 20:18
I no longer see these logs in 1.45.5. Thanks team!
