### ISSUE TITLE
Uncaught TypeError: Cannot read property '_TextDecoder' of undefined

### ISSUE THREAD

**Issue by satishbabariya** [denoland/deno#5839] opened 2020-05-25 11:43 UTC
When we bundle `https://deno.land/std/uuid/mod.ts` and run,  the following error occurs.

```log
➜  deno bundle https://deno.land/std/uuid/mod.ts uuid.bundle.js

➜  deno run uuid.bundle.js                                     
error: Uncaught TypeError: Cannot read property '_TextDecoder' of undefined
        exports_6("TextDecoder", TextDecoder = _utils_ts_1._TextDecoder);
                                                           ^

```

**Comment by zhmushan** [comment] 2020-05-27 00:52
I can't reproduce this.

**Comment by kitsonk** [comment] 2020-05-27 03:10
Same here... what version of Deno?

**Comment by satishbabariya** [comment] 2020-05-27 04:10
```
 ~ deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2
```

**Comment by satishbabariya** [comment] 2020-05-27 04:17
oh, it's working with `1.0.2` after upgrading. the only issue was in `1.0.0`

**Comment by kitsonk** [comment] 2020-05-27 05:20
You are using the master branch of standard, it is only compatible with the master branch of Deno.  It is by luck that it works with 1.0.2.  The version compatible with 1.0.0 is `v0.51.0` (`https://deno.land/std@v0.51.0/uuid/mod.ts`).  The version with 1.0.2 is `v0.53.0` (https://deno.land/std@v0.53.0/uuid/mod.ts`).

**Comment by satishbabariya** [comment] 2020-05-27 05:35
@kitsonk thanks for clarifying.
so the std@1.0.0, std@1.0.1, and std@1.0.2 are missing?
also, is there any warning message shown when running incompatible std lib with deno?

**Comment by kitsonk** [comment] 2020-05-27 06:58
There is mention of it in the manual which was added here https://deno.land/manual/standard_library#versioning-and-stability but it looks like the README was not updated: https://github.com/denoland/deno/tree/master/std#how-to-use. 

cc/ @bartlomieju @lucacasonato

**Comment by kitsonk** [comment] 2020-05-27 07:00
@satishbabariya you were also likely ignoring the warning that was being logged to the console...

```
Warning Implicitly using master branch https://deno.land/std/uuid/mod.ts
```

**Comment by bartlomieju** [comment] 2020-07-11 14:01
Warning are now printed when using non-tagged imports. Closing as resolved.

**Closed by bartlomieju** 2020-07-11 14:01 UTC
Labels: bug, cli
