### ISSUE TITLE
Cached warning messages cause confusion in editors

### ISSUE THREAD

**Issue by masontikhonov** [denoland/deno#15970] opened 2022-09-20 18:24 UTC
When importing the standard library without specifying a version, there are two warnings:
1. Implicitly using latest version (\<version\>) for \<url\>;
2. The import of "\<url\>" was redirected to "\<new-url\>".

But it shows wrong redirect and wrong latest version (older ones).
You could see on screenshots, that version offered by Deno is `0.151.0`; but the real redirect refers to version `0.156.0`:
![image](https://user-images.githubusercontent.com/32432324/191333419-6483c111-cb91-42a1-9f75-62d78e479296.png)

Quick fix "Update specifier to its redirected specifier" updates the link to the outdated version.

Expected behavior:
When no version is defined, show real redirects in hints; follow real redirects on "quick fix".

**Comment by kitsonk** [comment] 2022-09-20 21:53
Duplicate of #14933

**Closed by kitsonk** 2022-09-20 21:53 UTC
Labels: duplicate
