### ISSUE TITLE
deno config data access in namespace

### ISSUE THREAD

**Issue by timreichen** [denoland/deno#15846] opened 2022-09-10 09:35 UTC
I think it would be good to have a standardised way to access `deno.json` config data, since 3rd party tools (bundlers for example) need to have read `compilerOptions` and `importMap` to prevent a separate config file.

It is possible to do find and parse the file manually (PR in deno/std https://github.com/denoland/deno_std/pull/2356, but @ry is hesitant, since it could get out of sync with the runtime behavior.
So it would be better to include it in the deno namespace.

```ts
namespace Deno {
  export interface ConfigObject {
    tasks: Record<string, string>;
    importMap: ImportMap
    compilerOptions: CompilerOptions;
    …
  }
  export interface config {
    /**
     * returns the filePath of the deno.json or deno.jsonc file that was parsed by the runtime
     */
    filePath: string | null;
    /**
     * returns the resolved json or jsonc data that was parsed by the runtime
     */
    toObject(): ConfigObject | null;
  }
}
```
What are your thoughts on that?

**Comment by kitsonk** [comment] 2022-09-10 10:20
Duplicate of #15482

**Closed by kitsonk** 2022-09-10 10:20 UTC
Labels: duplicate
