### ISSUE TITLE
lsp: allow "lint-only" mode

### ISSUE THREAD

**Issue by mjgerace** [denoland/deno#15956] opened 2022-09-19 06:34 UTC
**Is your feature request related to a problem? Please describe.**
It's no secret that deno_lint is fast. Like, much, [much faster than eslint](https://github.com/denoland/deno_lint#performance). As such (and as the [deno_lint roadmap](https://github.com/denoland/deno_lint/issues/176) heads toward eslint plugin compatibility and autofix), deno will see an increasing number of users and companies adopt deno lint for their linting solution, whether they use node, deno, or any other runtime. 

Obviously, running lint in CI is nice, but most users want LSP integration, so that they can see lint issues as they write code.

**Describe the solution you'd like**
If this extension/lsp were to enable users to run the deno lsp _purely_ for linting, **without** disabling normal typescript language features, and without enabling _any_ other deno lsp features, we could have a hybrid world where users who use node, bun, etc, could use deno lint to great success.

This would increase adoption and awareness of deno tooling, and make other engineers happy.

Essentially, I wish the deno vscode extension would let us do `"deno.enable": false, "deno.lint": true`. In this sense, we get the linting features of the deno lsp without turning off visual studio code typescript language features.

Please consider this request! Let me know if I can provide any further information.

**Comment by kitsonk** [comment] 2022-09-19 09:55
This is something that would need to be addressed in the Deno CLI's language server primarily, so I have moved it here.

**Comment by kitsonk** [comment] 2022-09-29 04:37
Actually, forgot, this is really a duplicate of https://github.com/denoland/vscode_deno/issues/622

**Closed by kitsonk** 2022-09-29 04:37 UTC
Labels: suggestion, lsp
