### ISSUE TITLE
Allow fetch() to load local file when --allow-read is specified

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4624] opened 2020-04-04 13:39 UTC
When I make [yaml-wasm](https://github.com/KSXGitHub/yaml-wasm), I must open a web server to test it. If `fetch` can load local file, then a web server is no longer necessary, making automated testing much easier.

This would also help a static website development as well.

**Comment by lucacasonato** [comment] 2020-04-04 13:40
Duplicate of https://github.com/denoland/deno/issues/2150

**Closed** 2020-04-04 13:42 UTC
