### ISSUE TITLE
Deno can find a `*.d.ts` file of the corresponding `*.js` file even w/o a `/// <reference types` directive, but only in the web server context

### ISSUE THREAD

**Issue by canonic-epicure** [denoland/deno#10879] opened 2021-06-07 11:17 UTC
Steps to reproduce:
1) Clone the https://github.com/canonic-epicure/deno-d-ts-bug
2) Initially, the `Some.js` contains a reference to the `Some.d.ts` as:
```
/// <reference types="./Some.d.ts" />
```
3) `deno run -A src/Some.js`
4) Observe the error `error: Expected ident at file:///home/nickolay/workspace/Bryntum/typedoc-test2/src/Some.d.ts:4:41` - this is filed as #10878
5) Remove the `/// <reference types="./Some.d.ts" />` line
6) `deno run -A src/Some.js` now completes w/o error, as expected
7) Now, try to open this url in the web server context:
![image](https://user-images.githubusercontent.com/72431/121007600-c5a8d800-c79a-11eb-8686-795641812dbb.png)
```
nickolay@frontier:~/workspace/Bryntum/typedoc-test2$ deno run -A http://lh/typedoc-test2/src/Some.js
error: Expected ident at http://lh/typedoc-test2/src/Some.d.ts:4:41
```
Observe the same error as in 4), which means Deno can find the `*.d.ts` file

**Comment by wperron** [comment] 2021-06-09 17:49
Closing this as it is due to a user error https://discord.com/channels/684898665143206084/684898665151594506/851812061289775154

**Comment by canonic-epicure** [comment] 2021-06-10 06:38
@wperron You understood me incorrectly:

>I found the solution for the #10879, #10878 - I embed the reference but with the wrong URL!

This means - I embed the wrong URL by purpose, so that Deno fetches the missing `*.d.ts` file, receives 404 and continues. If I _do not_ embed the URL, Deno _still_ tries to fetch the *.d.ts file and fails because of the #10878 - that's the bug. This may be a fetuare, but docs says otherwise: 
```
If I try to import mod.js into Deno, it will only do what I ask it to do, and import mod.js, but that means my code won't be as well type checked as if TypeScript was considering the mod.d.ts file in place of the mod.js file.
```

More over, this happens only if the url of the module is `http`, does not happen for the file system

Please re-open.

**Comment by wperron** [comment] 2021-06-10 11:59
what's this `lh` server? is it some sort of local webserver you use locally? try `curl -i http://lh/typedoc-test2/src/Some.js` and look for a `X-TypeScript-Types` header, or `deno info --json --unstable http://lh/typedoc-test2/src/Some.js`

**Comment by canonic-epicure** [comment] 2021-06-10 12:33
Yes, `lh` is my local alias for `localhost`. Glad you were able to reproduce it.

**Comment by canonic-epicure** [comment] 2021-06-10 12:34
Please re-open the #10878 too? That is more important issue than this one I think. It means that Deno crashes on certain `*.d.ts` files, emitted by the TS compiler (outdated parser?)

**Comment by wperron** [comment] 2021-06-10 12:35
just to tick off the obvious -- did you try with `--reload`?

**Comment by wperron** [comment] 2021-06-10 12:35
> It means that Deno crashes on certain `*.d.ts` files, emitted by the TS compiler (outdated parser?)

Can you share the tsconfig used to generate the type definitions file?

**Comment by canonic-epicure** [comment] 2021-06-10 12:39
> just to tick off the obvious -- did you try with --reload?
The issue goes away indeed with the `-r`. So its a caching thing

**Comment by canonic-epicure** [comment] 2021-06-10 12:43
> Can you share the tsconfig used to generate the type definitions file?

Sure: https://github.com/bryntum/siesta/blob/master/tsconfig.json

**Comment by wperron** [comment] 2021-06-10 12:45
> The issue goes away indeed with the `-r`. So its a caching thing

Yup. In this case I'll close this issue as this is the intended behavior -- among potential solutions: put the run command with the `--reload` flag in a Makefile so it's always reloaded when developing locally, use `deno run` on the filesystem directly instead of going through the web server, and if this is a third-party lib, use a versioned import URL so that changes are reflected as a different URL, this bypassing the caching issue.

**Closed by wperron** 2021-06-10 12:45 UTC
Labels: cli, needs investigation

**Comment by canonic-epicure** [comment] 2021-06-10 12:48
Hm.. In one way you are right, but it seems caching is done simply by hashing the file URL. Shoudn't it include the file content in hash too?

**Comment by kitsonk** [comment] 2021-06-10 23:03
At the moment, remote URLs are never checked for their content.  That would be expensive, to always check with the server if the content of a URL has changed or not.  We want the cache to respect cache headers from the server though, which would allow a server to determine when a remote resource could possible be changed. (see: #9931)
