### ISSUE TITLE
`Deno.upgradeWebSocket` fails on `connection: "keep-alive, Upgrade"` header

### ISSUE THREAD

**Issue by silen-z** [denoland/deno#11494] opened 2021-07-22 23:03 UTC
Hi, I'm trying out the unstable `Deno.upgradeWebSocket` and encountered an issue accepting a WebSocket from Firefox. 

Firefox is sending this `connection: "keep-alive, Upgrade"` header when connecting to a websocket. That causes throw [here](https://github.com/denoland/deno/blob/8b34f07bb000a16b60b119ee24f5c0b4a5f7f937/extensions/http/01_http.js#L324)

```ts
  function upgradeWebSocket(request, options = {}) {

    // ...

    if (request.headers.get("connection")?.toLowerCase() !== "upgrade") {
      throw new TypeError(
        "Invalid Header: 'connection' header must be 'Upgrade'",
      );
    }

    // ...

```

 while the [current std logic for accepting sockets](https://github.com/denoland/deno_std/blob/bf73521428ce724d31dba0d403d14acc929f39ab/ws/mod.ts#L396) doesn't care about the `connection` header at all.
 
 ```ts
 export function acceptable(req: { headers: Headers }): boolean {
  const upgrade = req.headers.get("upgrade");
  if (!upgrade || upgrade.toLowerCase() !== "websocket") {
    return false;
  }
  const secKey = req.headers.get("sec-websocket-key");
  return (
    req.headers.has("sec-websocket-key") &&
    typeof secKey === "string" &&
    secKey.length > 0
  );
}
 ```

**Comment by kitsonk** [comment] 2021-07-22 23:39
Duplicate of #11487

**Comment by crowlKats** [comment] 2021-07-22 23:40
@kitsonk not duplicate, this is about inclusion, not equality

**Comment by silen-z** [comment] 2021-07-23 01:45
Oh I did look first and haven't found that issue. That gives me some direction on how to make PR to fix this one. I'll get to it tomorrow.

**Closed** 2021-07-24 02:14 UTC
Labels: bug, extensions

**Comment by rojserbest** [comment] 2021-12-08 18:08
I have this problem on `deno 1.16.4 (release, x86_64-unknown-linux-gnu)`.

**Comment by rojserbest** [comment] 2021-12-08 18:10
With `Deno.upgradeWebSocket`.
