### ISSUE TITLE
[BUG] Deno 1.5.0 alert, confirm, prompt incorrect behaviour

### ISSUE THREAD

**Issue by ibanchevski** [denoland/deno#8165] opened 2020-10-28 09:13 UTC
After the update, the new confirm, alert and prompt do not work properly.

Platform: Windows 10 x 86_64

I was able to reproduce the issue in another Windows machine.

```
let name = prompt("What's your name?");
let sure = confirm(`Is ${name} your real name?`);
if (sure) {
    alert("OK, you are sure");
} else {
    alert("Well, you are not sure!");
}
```

![deno-issue](https://user-images.githubusercontent.com/62385800/97415756-456dea80-190e-11eb-9386-63f7188e2cd0.PNG)

_Note: The example code from the release blog post do not work as well._

**Comment by lucacasonato** [comment] 2020-10-28 09:19
Duplicate of #8146. We will release a hot fix release with a fix today.

**Closed by lucacasonato** 2020-10-28 09:19 UTC
