### ISSUE TITLE
Segmentation fault on uncaught throw with nonblocking FFI call pending

### ISSUE THREAD

**Issue by aapoalas** [denoland/deno#14854] opened 2022-06-12 19:14 UTC
If an error is thrown is uncaught and would cause the Deno process to exit while a nonblocking FFI call is pending, then a segmentation fault will occur.

Minimal reproduction:
```js
const dylib = Deno.dlopen("./target/debug/libtest_ffi.so", {
    "sleep_nonblocking": {
        name: "sleep_blocking",
        parameters: ["u64"],
        result: "void",
        nonblocking: true,
    },
});

dylib.symbols.sleep_nonblocking(100);

throw new TypeError("foo");
```

**Comment by sgorsh** [comment] 2022-09-23 13:56
I've also come across this issue when developing my Rust library on Windows machine with Deno FFI calls. It's very annoying to debug code when exceptions are not thrown, Deno just exits.
Tried to reproduce with example above and debug version of Deno. In debugger I get the following message:
`Exception thrown at 0x00007FFE29761FDE in deno.exe: 0xC0000005: Access violation executing location 0x00007FFE29761FDE.`

Stack trace
**tokio-runtime-worker** thread (this thread throws exception 0xC0000005):
```
00007ffe29761fde() (Unknown Source:0)
0000000000000001() (Unknown Source:0)
```
**main** thread
```
ntdll.dll!00007ffe62eb09f4() (Unknown Source:0)
ntdll.dll!00007ffe62e737ed() (Unknown Source:0)
ntdll.dll!00007ffe62e736a2() (Unknown Source:0)
ntdll.dll!00007ffe62e733b3() (Unknown Source:0)
KernelBase.dll!00007ffe60b3d00f() (Unknown Source:0)
deno.exe!parking_lot_core::thread_parker::imp::waitaddress::WaitAddress::wait_on_address(core::sync::atomic::AtomicUsize * self, unsigned int key) Line 114 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot_core-0.9.3\src\thread_parker\windows\waitaddress.rs:114)
deno.exe!parking_lot_core::thread_parker::imp::waitaddress::WaitAddress::park(core::sync::atomic::AtomicUsize * self) Line 68 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot_core-0.9.3\src\thread_parker\windows\waitaddress.rs:68)
deno.exe!parking_lot_core::thread_parker::imp::ThreadParker::park() Line 118 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot_core-0.9.3\src\thread_parker\windows\mod.rs:118)
deno.exe!parking_lot_core::parking_lot::park::closure$0<parking_lot::condvar::impl$1::wait_until_internal::closure_env$0,parking_lot::condvar::impl$1::wait_until_internal::closure_env$1,parking_lot::condvar::impl$1::wait_until_internal::closure_env$2>(parking_lot_core::parking_lot::park::closure_env$0<parking_lot::condvar::impl$1::wait_until_internal::closure_env$0,parking_lot::condvar::impl$1::wait_until_internal::closure_env$1,parking_lot::condvar::impl$1::wait_until_internal::closure_env$2> thread_data, parking_lot_core::parking_lot::ThreadData *) Line 635 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot_core-0.9.3\src\parking_lot.rs:635)
[Inline Frame] deno.exe!parking_lot_core::parking_lot::with_thread_data(parking_lot_core::parking_lot::park::closure_env$0<parking_lot::condvar::impl$1::wait_until_internal::closure_env$0,parking_lot::condvar::impl$1::wait_until_internal::closure_env$1,parking_lot::condvar::impl$1::wait_until_internal::closure_env$2> f) Line 207 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot_core-0.9.3\src\parking_lot.rs:207)
deno.exe!parking_lot_core::parking_lot::park<parking_lot::condvar::impl$1::wait_until_internal::closure_env$0,parking_lot::condvar::impl$1::wait_until_internal::closure_env$1,parking_lot::condvar::impl$1::wait_until_internal::closure_env$2>(unsigned __int64 key, parking_lot::condvar::impl$1::wait_until_internal::closure_env$0 validate, parking_lot::condvar::impl$1::wait_until_internal::closure_env$1 before_sleep, parking_lot::condvar::impl$1::wait_until_internal::closure_env$2 timed_out, parking_lot_core::parking_lot::ParkToken park_token, enum$<core::option::Option<std::time::Instant>> timeout) Line 600 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot_core-0.9.3\src\parking_lot.rs:600)
deno.exe!parking_lot::condvar::Condvar::wait_until_internal(parking_lot::raw_mutex::RawMutex * self, enum$<core::option::Option<std::time::Instant>> mutex) Line 333 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot-0.12.1\src\condvar.rs:333)
deno.exe!parking_lot::condvar::Condvar::wait<tuple$<>>(lock_api::mutex::MutexGuard<parking_lot::raw_mutex::RawMutex,tuple$<>> * self) Line 257 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\parking_lot-0.12.1\src\condvar.rs:257)
deno.exe!tokio::loom::std::parking_lot::Condvar::wait<tuple$<>>(tokio::loom::std::parking_lot::MutexGuard<tuple$<>> self) Line 150 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\loom\std\parking_lot.rs:150)
deno.exe!tokio::park::thread::Inner::park() Line 116 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\park\thread.rs:116)
deno.exe!tokio::park::thread::impl$6::park::closure$0(tokio::park::thread::impl$6::park::closure_env$0, tokio::park::thread::ParkThread * park_thread) Line 285 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\park\thread.rs:285)
deno.exe!tokio::park::thread::impl$5::with_current::closure$0<tokio::park::thread::impl$6::park::closure_env$0,tuple$<>>(tokio::park::thread::impl$5::with_current::closure_env$0<tokio::park::thread::impl$6::park::closure_env$0,tuple$<>> inner, tokio::park::thread::ParkThread *) Line 253 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\park\thread.rs:253)
deno.exe!std::thread::local::LocalKey<tokio::park::thread::ParkThread>::try_with<tokio::park::thread::ParkThread,tokio::park::thread::impl$5::with_current::closure_env$0<tokio::park::thread::impl$6::park::closure_env$0,tuple$<>>,tuple$<>>(tokio::park::thread::impl$5::with_current::closure_env$0<tokio::park::thread::impl$6::park::closure_env$0,tuple$<>> self) Line 445 (c:\rustc\4b91a6ea7258a947e59c6522cd5898e7c0a6a88f\library\std\src\thread\local.rs:445)
deno.exe!tokio::park::thread::CachedParkThread::with_current<tokio::park::thread::impl$6::park::closure_env$0,tuple$<>>(tokio::park::thread::impl$6::park::closure_env$0 self) Line 253 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\park\thread.rs:253)
deno.exe!tokio::park::thread::impl$6::park(tokio::park::thread::CachedParkThread * self) Line 285 (c:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\tokio-1.21.1\src\park\thread.rs:285)
```

Unfortunately I don't know where to go from here...

Deno version: v1.25.4
Windows 10 x64 21H1

**Comment by littledivy** [comment] 2023-01-21 17:00
@aapoalas I can't reproduce the crash anymore. Closing, please reopen if this is still an issue.

**Closed by littledivy** 2023-01-21 17:00 UTC
Labels: bug, ext/ffi
