### ISSUE TITLE
Loading numpy package in kernel freezes

### ISSUE THREAD

**Issue by hinthornw** [denoland/deno#22025] opened 2024-01-22 03:28 UTC
If I run the following code in a jupyter notebook using a deno kernel, the cell freezes after printing out "loading numpy".

```
import pyodideModule from "npm:pyodide/pyodide.js";

const pyodide = await pyodideModule.loadPyodide();
await pyodide.loadPackage("numpy")
```

The same lines work in a `.ts` file when running `deno run file.ts`.

It's a bit hard to debug, since there isn't much documentation on the notebook functionality and hard to step through a statement like this in a notebook. 

Thanks in advance for any pointers!

Version: deno 1.39.0 (release, aarch64-apple-darwin)
v8 12.0.267.8
typescript 5.3.3

**Comment by littledivy** [comment] 2024-01-22 03:44
I can reproduce this in `deno repl`

The event loop seems to be spinning the CPU at 100%. 

![lsp](https://github.com/denoland/deno/assets/34997667/63ba3ce7-ae36-412a-8674-d9ba47605f5f)

**Comment by fivethreeo** [comment] 2024-02-21 04:37
See https://github.com/pyodide/pyodide/issues/3420

**Comment by devsnek** [comment] 2024-06-11 07:59
This seems to be working now, though I don't see it using any native modules, only wasm.

**Comment by lucacasonato** [comment] 2024-06-18 15:13
Closing as this is working now.

**Closed by lucacasonato** 2024-06-18 15:13 UTC
Labels: bug, node compat, node native extension
