### ISSUE TITLE
file_fetcher::tests::* always failing for local testing

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#4097] opened 2020-02-23 20:50 UTC
Unable to run tests locally due to at least one of the `file_fetcher::tests::*` almost always failing.

**Comment by bartlomieju** [comment] 2020-02-23 20:55
@kevinkassimo which tests are failing? I have no problems running them locally

**Comment by kevinkassimo** [comment] 2020-02-23 21:12
@bartlomieju Different ones fail during different runs (I haven't been able to ).
Failing ones I have seen so far (they sometimes pass, but then other breaks)
```
thread 'file_fetcher::tests::test_get_source_code_2' panicked at 'assertion failed: result.is_ok()', cli/file_fetcher.rs:826:5

thread 'file_fetcher::tests::test_get_source_cached_only' panicked at 'assertion failed: result.is_ok()', cli/file_fetcher.rs:1134:5

thread 'file_fetcher::tests::test_get_source_code_1' panicked at 'assertion failed: result.is_ok()', cli/file_fetcher.rs:743:5

thread 'file_fetcher::tests::test_fetch_source_2' panicked at 'assertion failed: result.is_ok()', cli/file_fetcher.rs:1233:5

thread 'file_fetcher::tests::test_get_source_code_multiple_downloads_of_same_file' panicked at 'assertion failed: r.is_ok()', cli/file_fetcher.rs:889:5
```

**Comment by ry** [comment] 2020-02-24 13:26
@kevinkassimo You know you can selectively run tests? EG "cargo test overflow"

But also I can't repeat your errors. (Is the python server running erroneously in the background?)

**Comment by kevinkassimo** [comment] 2020-02-24 18:29
@ry I tried it and it does not really make any difference. Also I have checked there are no other python servers running. I'll investigate a bit more

**Comment by bartlomieju** [comment] 2020-03-20 10:11
@kevinkassimo I can't reproduce this problem locally; nor is it visible in CI. I'm gonna close the issue for now; if problem reappears feel free to reopen.

**Closed by bartlomieju** 2020-03-20 10:11 UTC
