### ISSUE TITLE
error: The module's source code could not be parsed: Expected ',', got ':' at

### ISSUE THREAD

**Issue by mateja176** [denoland/deno#12880] opened 2021-11-23 23:38 UTC
```ts
const camelCase = (s: string) => s.charAt(0).toUpperCase().concat(s.slice(1));
// error: The module's source code could not be parsed: Expected ',', got ':' at <file-name>

const camelCase = (s) => s.charAt(0).toUpperCase().concat(s.slice(1));
OK

```

**Comment by lucacasonato** [comment] 2021-11-23 23:44
Is this inside of a JS, or TS file?

**Comment by mateja176** [comment] 2021-11-23 23:46
@lucacasonato I was led to https://github.com/denoland/deno/issues/9063

**Comment by lucacasonato** [comment] 2021-11-23 23:47
Closing as a duplicate of #9063 then :-)

**Closed by lucacasonato** 2021-11-23 23:47 UTC

**Comment by kitsonk** [comment] 2021-11-24 00:12
Which is a duplicate of #5088
