### ISSUE TITLE
JSError: error: Uncaught ReferenceError: self is not defined inside web worker

### ISSUE THREAD

**Issue by GrosSacASac** [denoland/deno#2639] opened 2019-07-11 23:41 UTC
[example-deno/file_usage.js](https://github.com/GrosSacASac/worka/blob/master/example-deno/file_usage.js)
[example-deno/sort_worka.js](https://github.com/GrosSacASac/worka/blob/master/example-deno/sort_worka.js)

**Comment by nayeem-rahman** [comment] 2019-07-14 12:57
Duplicate of #650. Not quite what it was originally about but this is being tracked there.

**Comment by nayeemrmn** [comment] 2019-12-17 02:55
@GrosSacASac Can you close this?

**Closed** 2019-12-17 08:49 UTC
