### ISSUE TITLE
Feature request of LSP: features like "source.addMissingImports", "source.organizeImports"

### ISSUE THREAD

**Issue by runminlook** [denoland/deno#11077] opened 2021-06-22 11:04 UTC
Feature request of LSP: features like "source.addMissingImports", "source.organizeImports"

**Comment by kitsonk** [comment] 2021-06-22 11:51
Duplicate of denoland/vscode_deno#433

It is on my roadmap coming up soon.

**Closed by kitsonk** 2021-06-22 11:51 UTC
Labels: duplicate, lsp, suggestion
