### ISSUE TITLE
Deno bundle errors on new automatic JSX runtime

### ISSUE THREAD

**Issue by ayoreis** [denoland/deno#15102] opened 2022-07-06 11:29 UTC
I get this error; in the Deno 1.23.2.

```
error: Unable to output during bundling.

Caused by:
    0: load_transformed failed
    1: failed to analyze module
    2: failed to resolve https://esm.sh/react@^18.2.0?pin=v86?bundle/jsx-runtime from file:///C:/Users/ayovr/Documents/dev/deno-bundle-automatic-jsx-runtime-error-reproduction/mod.tsx
    3: Cannot resolve "https://esm.sh/react@^18.2.0?pin=v86?bundle/jsx-runtime" from "file:///C:/Users/ayovr/Documents/dev/deno-bundle-automatic-jsx-runtime-error-reproduction/mod.tsx".
```

I made this repository with a simple reproduction: https://github.com/ayoreis/deno-bundle-automatic-jsx-runtime-error-reproduction

**Comment by ayoreis** [comment] 2022-07-10 09:27
Something I found which may be related is that you can't use your own file as the `"jsxImportSource"` option, because it will never an extension (`.js` or `.ts`) to end. E.g. `"jsxImportSource": ".."` will resolve to `./jsx-runtime` and not `./jsx-runtime.[jt]s`

**Comment by kitsonk** [comment] 2022-07-10 23:44
Duplicate of #13389

**Closed by kitsonk** 2022-07-10 23:44 UTC
Labels: duplicate
