### ISSUE TITLE
Building deno_core to a single executable

### ISSUE THREAD

**Issue by apeltsi** [denoland/deno#13210] opened 2021-12-27 15:46 UTC
I am using deno_core version 0.112.0 in my project. But when I make a release build and run it on another computer without cargo installed I get the following error:

    thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: The system cannot find the path specified. (os error 3)', C:\Users\user\.cargo\registry\src\github.com-1ecc6299db9ec823\deno_core-0.112.0\runtime.rs:390:38

It appears to be trying to load `00_primordials.js` which doesn't exist on my other system. Deno ships in a single executable so i figured that it is possible to do the same with deno_core.

**Comment by andreubotella** [comment] 2021-12-27 16:42
This is the same bug as #11030.

**Comment by kitsonk** [comment] 2021-12-28 08:57
Duplicate of #11030

**Closed by kitsonk** 2021-12-28 08:57 UTC
Labels: duplicate
