### ISSUE TITLE
Deno on MUSL linux not working

### ISSUE THREAD

**Issue by lygstate** [denoland/deno#6774] opened 2020-07-16 14:30 UTC
```
localhost:~# uname -a
Linux localhost 5.4.51-0-lts #1-Alpine SMP Fri, 10 Jul 2020 10:54:20 UTC x86_64 Linux
localhost:~# wget https://github.com/denoland/deno/releases/download/v1.2.0/deno-x86_64-unknown-linux-gnu.zip
localhost:~# unzip deno-x86_64-unknown-linux-gnu.zip
Archive:  deno-x86_64-unknown-linux-gnu.zip
  inflating: deno
localhost:~# ldd deno
        /lib64/ld-linux-x86-64.so.2 (0x7fdb1cc33000)
        libdl.so.2 => /lib64/ld-linux-x86-64.so.2 (0x7fdb1cc33000)
        librt.so.1 => /lib64/ld-linux-x86-64.so.2 (0x7fdb1cc33000)
        libpthread.so.0 => /lib64/ld-linux-x86-64.so.2 (0x7fdb1cc33000)
        libgcc_s.so.1 => /usr/lib/libgcc_s.so.1 (0x7fdb1a2d2000)
        libc.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fdb1cc33000)
Error loading shared library ld-linux-x86-64.so.2: No such file or directory (needed by deno)
        libm.so.6 => /lib64/ld-linux-x86-64.so.2 (0x7fdb1cc33000)
Error relocating deno: __res_init: symbol not found
Error relocating deno: strtoull_l: symbol not found
Error relocating deno: __memcpy_chk: symbol not found
Error relocating deno: __isnan: symbol not found
Error relocating deno: __vfprintf_chk: symbol not found
Error relocating deno: strtoll_l: symbol not found
Error relocating deno: backtrace: symbol not found
Error relocating deno: __vsnprintf_chk: symbol not found
Error relocating deno: __isnanf: symbol not found
Error relocating deno: __isinf: symbol not found
Error relocating deno: backtrace_symbols: symbol not found
Error relocating deno: __register_atfork: symbol not found
```

**Comment by ebebbington** [comment] 2020-07-16 14:33
How did you install Deno? Can you run through the installation steps again and provide code blocks of what you ran and the output for each command(s)?

**Comment by lucacasonato** [comment] 2020-07-16 15:31
duplicate of #3711

**Closed** 2020-08-27 09:58 UTC
