### ISSUE TITLE
The "WebSocketStream" or "WebSocket" function does not allow to modify the "host" in the request header, resulting in the inability to implement the proxy websocket of the reverse proxy server.

### ISSUE THREAD

**Issue by masx200** [denoland/deno#14910] opened 2022-06-19 12:49 UTC
This can be done in nodejs.

This is not possible in deno.

```ts
import { serve } from "https://deno.land/std@0.144.0/http/mod.ts";
import { assertEquals } from "https://deno.land/std@0.144.0/testing/asserts.ts";


Deno.test("websocket-host", async () => {
    const ac = new AbortController();
    const { signal } = ac;
    const p = serve(
        function (req) {
            console.log("request", req);
            const { socket, response } = Deno.upgradeWebSocket(req);

            socket.addEventListener("open", () => {
                socket.send(req.url);
                socket.close();
            });

            return response;
        },
        {
            signal,
            port: 5000,
        }
    );
    const socket = new WebSocketStream("ws://127.0.0.1:5000/", {
        headers: { host: "localhost.hello.world:9900" },
    });
    const connection = await socket.connection;
    const reader = connection.readable.getReader();
    let text = "";

    while (true) {
        const result = await reader.read();
        if (result.done) {
            break;
        } else {
            text = text + result.value;
        }
    }
    assertEquals(text, "http://localhost.hello.world:9900/");
    ac.abort();
    await p;
});

```
```
websocket-host => ./test.ts:26:6
error: AssertionError: Values are not equal:


    [Diff] Actual / Expected


-   http://127.0.0.1:5000/
+   http://localhost.hello.world:9900/


  throw new AssertionError(message);
        ^
    at assertEquals (https://deno.land/std@0.144.0/testing/asserts.ts:176:9)
    at file:///C:/Documents/test/test.ts:62:5

 FAILURES


websocket-host => ./test.ts:26:6
```

**Comment by kitsonk** [comment] 2022-09-09 00:58
@lucacasonato thoughts?

**Comment by crowlKats** [comment] 2022-09-09 08:33
The host header is a forbidden header. See #11017. So this is correct behaviour. Same goes for #14909

**Comment by kitsonk** [comment] 2022-09-09 22:58
Duplicate of #14909

**Closed by kitsonk** 2022-09-09 22:58 UTC
Labels: ext/fetch, needs investigation
