### ISSUE TITLE
code with import map failed to run after bundle

### ISSUE THREAD

**Issue by meepeek** [denoland/deno#14741] opened 2022-05-27 04:25 UTC
The following code works fine with deno run but it will throws error after bundle. When I removed import map and import deno-dom directly to the file, it run successfully after bundle. Please check the code below.

test.ts
```
import {denodom} from '@/deps.ts'

const url = 'http://google.com'
const response = await fetch(url)
const data = await response.text()
const document = new denodom.DOMParser().parseFromString(data, 'text/html')
console.log(document)
```

import-map.json
```
{
    "imports": {
        "@/": "./"
    }
}
```

deps.ts
```
export * as denodom from "https://deno.land/x/deno_dom@v0.1.30-alpha/deno-dom-wasm.ts"
```

bundle cli
```
deno bundle --importmap=import-map.json test.ts test.js
```

**Comment by kitsonk** [comment] 2022-05-27 05:27
> deno run but it will throws error after bundle.

What version of Deno are you using `deno --version`?

When you say "throws error after bundle", what error and how are you executing the bundle?

**Comment by meepeek** [comment] 2022-05-27 05:31
deno 1.22.0 (release, aarch64-apple-darwin)
v8 10.0.139.17
typescript 4.6.2

the error message is as follow:
```
error: Uncaught (in promise) TypeError: mod.DOMParser is not a constructor
const document3 = new mod.DOMParser().parseFromString(data, 'text/html');
                  ^
    at file:///Users/thee/git-repo/server-config-2022/functions/scraper/test.js:4270:19
```

**Comment by kitsonk** [comment] 2022-05-27 05:32
> how are you executing the bundle?

**Comment by meepeek** [comment] 2022-05-27 08:45
I bundle as following code.
```
deno bundle --importmap=import-map.json test.ts test.js
```
Then I execute
```
deno run test.js
```
My understanding is bundle should package everything to a self-contained single js file so I no longer need to add map option when running the bundled js, is that correct ?

**Comment by kitsonk** [comment] 2022-05-30 04:52
Not if the code you are loading loads other code dynamic, which I believe `deno_doc` does.  What happens when you supply the import map on `deno run`?

**Comment by meepeek** [comment] 2022-05-30 06:07
<img width="600" alt="Screen Shot 2565-05-30 at 13 06 28" src="https://user-images.githubusercontent.com/2456033/170927489-bd83bec0-5a1a-4c10-a3be-a843d6d780d7.png">

**Comment by PolarETech** [comment] 2022-08-25 06:40
Hi,
I have looked into this issue a little.

It seems that the cause is not import map, but ```export * from ...``` and top level await.
And it looks like a bundle issue on SWC side.

Bundling the above code will output the following js:

```deno
// omitted
await init();
register(parse, parse_frag);
const mod = await async function() {
    return {};
}();
const url = 'http://google.com';
const response = await fetch(url);
const data = await response.text();
const document1 = new mod.DOMParser().parseFromString(data, 'text/html');
console.log(document1);
```

Since there is no `DOMParser` in `const mod = {}`, the mentioned error occurs.

After some trial and error, it occurred when `export * from ...` and top level await existed in the same file.
Similar output can be reproduced with the following minimal code:

```
// lib/greeting.ts
export const greeting = (name: string) => console.log(`Hello, ${name}!`);

// lib/mod.ts
export * from "./greeting.ts";
await Promise.resolve(true);

// deps.ts
export * as foo from "./lib/mod.ts";

// main.ts
import { foo } from "./deps.ts"
foo.greeting("world");
```

Here is the output of the bundle:

```deno
await Promise.resolve(true);
const mod = await async function() {
    return {};
}();
mod.greeting("world");
```

And it occurs even when bundling directly using SWC ([spack](https://swc.rs/docs/usage/bundling)).

Based on the results, I think this would be an issue for SWC.
I would like to look more into SWC side if others are not already working on this.

**Current Deno version:**
deno 1.24.3 (release, x86_64-apple-darwin)
v8 10.4.132.20
typescript 4.7.4

**Current SWC version:**
@swc/cli: 0.1.57
@swc/core: 1.2.242

**Comment by PolarETech** [comment] 2022-08-26 11:09
I have submitted the issue.
https://github.com/swc-project/swc/issues/5642

**Comment by PolarETech** [comment] 2022-09-04 20:04
https://github.com/swc-project/swc/issues/5642 has been fixed in @swc/core 1.2.247 (swc_bundler 0.184.1).
It is expected that once the fixed version of SWC is imported into Deno, this issue will no longer reproduce.

Note that Deno seems to be using swc_bundler 0.169.0 at the moment. (https://github.com/denoland/deno_ast/blob/0.17.0/Cargo.toml#L64)

**Comment by PolarETech** [comment] 2022-09-11 05:42
The error is not reproduced with Deno 1.25.2 (deno_ast 0.19.0, swc_bundler 0.185.5) and the DOM parser works well in the bundled js.
This issue can be considered resolved.

**Comment by lucacasonato** [comment] 2024-09-19 09:44
`deno bundle` has been deprecated and removed in Deno 2.

**Closed by lucacasonato** 2024-09-19 09:44 UTC
Labels: bug, needs investigation
