### ISSUE TITLE
Illegal SNI hostname received

### ISSUE THREAD

**Issue by caramboleyo** [denoland/deno#18002] opened 2023-03-03 15:59 UTC
My logs are full with lines like this:
```
Illegal SNI hostname received [50, 97, 48, 51, 58, 52, 48, 48, 48, 58, 51, 98, 58, 50, 52, 52, 58, 50, 55, 49, 48, 58, 52, 101, 50, 48, 58, 55, 53, 51, 48, 58, 57, 99, 52, 49]
Sending fatal alert DecodeError
```
i think websockets are causing this when they've been running a while but i am not sure.
currently on latest deno version but i can't say with what version this started - a while ago.

also http errors appear that cause the whole app to crash and seem to bypass the unhandledrejection event.
```
error: Uncaught Http: connection closed while sending response
    at async respondWith (internal:deno_http/01_http.js:246:9)
```
i think it happens when you relead a page before it was completly loaded. Why would this cause an error that shuts down the whole app? This makes deno unusable in production. It also seems to bypass several catchblocks.

**Comment by aapoalas** [comment] 2023-03-03 16:30
Hey. Apologies for this, it seems you've found a path to trigger this V8 bug: https://bugs.chromium.org/p/v8/issues/detail?id=13600#c_ts1675025714

That makes the errors uncatchable in certain circumstances that had been thought to be impossible in real life. It's likely that the repeated SNI errors are leading V8 to that circumstance.

**Comment by caramboleyo** [comment] 2023-03-03 16:55
ok, thanks

the sni errors seem to be catchable, they dont cause the app to crash.

but with an error appearing in deno_http everything halts and waits for systemd to restart. appears randomly in production. i cannot reproduce it manually.

**Comment by aapoalas** [comment] 2023-03-03 17:03
We'll probably be disabling the Fast API path for fallible ops for the time being.

The reproduction we've used in V8 includes sometimes thousands of calls to an API with exactly the same parameters. Eg. Changing one parameter in the call from false to true already deoptimises V8 in such a way as to make the bug not occur.

So, a manual reproduction with the HTTP server likely requires a significant amount of time.

**Comment by mmastrac** [comment] 2024-04-04 21:52
I'm closing this issue since we've rewritten nearly all the code in this path and I'm pretty sure it's more stable now. Please re-open if you can repro

**Closed by mmastrac** 2024-04-04 21:52 UTC
