### ISSUE TITLE
`declare` keyword on public field transpiled incorrectly by Deno.emit

### ISSUE THREAD

**Issue by dgreensp** [denoland/deno#12532] opened 2021-10-25 05:19 UTC
It's very important that declaring a class field with `declare x` does _not_ emit a real field.

See this example ([playground link](https://www.typescriptlang.org/play?useDefineForClassFields=true&target=99&isolatedModules=true&ts=4.4.4#code/KYDwDg9gTgLgBAYwDYEMDOa4DEITgbwFgAoOMuEALjgDsBXAWwCNgoBuE8xCGtGKOghjQAFFVqMWUAJQFOXcjAAWASzQA6EHAC8FDqXIBfEseIlQkWIlQY4AIRRQ4oGMBoATTDjxEDZd8DIjsAU1ACMAEwAzPpcCDx8AkKisr4K5Gh0YKwikVHSsUYmQA)):

```ts
export class Foo {
    x: number;
    constructor(x: number) {
        this.x = x;
    }
}

export class Bar extends Foo {
    declare x: 123;
    constructor() {
        super(123);
    }
}
```

Correctly compiled by TSC:

```js
export class Foo {
    x;
    constructor(x) {
        this.x = x;
    }
}
export class Bar extends Foo {
    constructor() {
        super(123);
    }
}
```

Incorrectly emitted by Deno:

```js
    class Foo {
        x;
        constructor(x){
            this.x = x;
        }
    }
    class Bar extends Foo {
        x; // <-- should not be here
        constructor(){
            super(123);
        }
    }
```

Now Foo and Bar have two completely different fields named `x`.  The `declare` keyword is supposed to give you a way around this.

**Comment by lucacasonato** [comment] 2021-11-03 11:17
@dgreensp We pull at least once a minor (every 4 weeks), but usually more like every 1.5 weeks or so.

**Comment by KyleJune** [comment] 2021-11-18 04:58
@nayeemrmn Identified that this is a duplicate of https://github.com/denoland/deno/issues/10861 and that the swc fix will resolve both issues.

**Closed** 2021-12-09 00:12 UTC
Labels: bug, upstream, fix available, swc
