### ISSUE TITLE
bug: bundled code is missing definitions for "import as" functions

### ISSUE THREAD

**Issue by alexanderGalushka** [denoland/deno#8285] opened 2020-11-07 23:14 UTC
deno --version

```
deno 1.5.0
v8 8.7.220.3
typescript 4.0.3
```

`deno bundle "https://deno.land/x/djwt@v1.9/mod.ts" > djwt.js`

using the bundled djwt.js produces the following error:

`ReferenceError: convertUint8ArrayToHex is not defined`

convertUint8ArrayToHex is declared in [deps.ts of the djwt lib](https://github.com/timonson/djwt/blob/master/_depts.ts#L4)

referencing [an issue opened against djwt ](https://github.com/timonson/djwt/issues/39)

**Comment by kitsonk** [comment] 2020-11-08 03:15
While `convertUint8ArrayToHex` is declared in `_depts.ts` it is not imported and subsequently exported from `mod.ts`, so the bundling appears to be working as designed.

The only exported symbols from `mod.ts` are `create`, `decode`, `getNumericDate`, and `verify` and if I run the bundle with a simply:

```js
import * as djwt from "./djwt.js";
console.log(djwt);
```

I get no errors, and exactly the same symbols logged if I use the module directly.

**Comment by alexanderGalushka** [comment] 2020-11-08 06:10
@kitsonk thank you for looking into this, I've put together a [quick test](https://github.com/alexanderGalushka/djwt_test ), 
see reamde to reproduce reported issue

it comes down to 
https://github.com/timonson/djwt/blob/master/mod.ts#L97 -> 
https://github.com/timonson/djwt/blob/master/mod.ts#L1 -> 
https://github.com/timonson/djwt/blob/master/_depts.ts#L4

`convertUint8ArrayToHex` is the second `import as` in _depts.ts

**Comment by quaos** [comment] 2020-11-12 02:56
I also encountered this with `_reactDevelopmentDewDew is not defined`

**Comment by burkeholland** [comment] 2020-11-23 04:38
Ran into this with Handlebars for Deno...

https://github.com/alosaur/handlebars/issues/8

**Comment by lucacasonato** [comment] 2020-12-01 17:18
@alexanderGalushka Can you check if this is still present in 1.5.4? I think this is a duplicate of #8314, which is fixed.

**Comment by kdy1** [comment] 2020-12-27 12:21
This is fixed by new version of swc_bundler. (I've added test for it)

**Closed** 2020-12-28 23:22 UTC
Labels: cli, needs investigation, swc
