### ISSUE TITLE
Run `deno fetch` on URL to a JavaScript file that has Triple-Slash Directive should also fetch TypeScript definition that the directive points to

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4476] opened 2020-03-24 11:18 UTC
JavaScript file at https://deno.land/x/once/index.js has a Triple-Slash Directive that define location of TypeScript definition:

```javascript
/// <reference types="./index.d.ts" />
```

When I run `deno fetch --reload https://deno.land/x/once/index.js`, I expect Deno to also fetch `index.d.ts` but it does not.

---

This issue was suspected to be the cause of https://github.com/axetroy/vscode-deno/issues/102.

**Comment by bartlomieju** [comment] 2020-03-24 11:26
Related https://github.com/denoland/deno/issues/4000

**Comment by kitsonk** [comment] 2020-03-25 06:25
Likely a duplicate of #4000 actually.  Again surprising `deno fetch` is using a different resolution path.

**Comment by grosto** [comment] 2020-04-05 15:50
I can take this if no one is working on it.

**Comment by grosto** [comment] 2020-04-05 20:32
From a quick look, it seems that types from triple-slash directive are not fetched when the main module is JS, even with deno run command. The only place in the code where types_url are fetched is op_fetch_source_files which is never called if the main module is JS. 

For the fix, I guess the first it comes to decision if deno run should fetch type_urls too if main module is JS.

**Comment by kitsonk** [comment] 2020-04-05 20:52
Yeah, it should, even though with `deno run` it would not be used, it is obviously important for placing in the cache. Thanks for looking at this. A fix would then fix #4000 as well.

**Closed** 2020-04-06 20:52 UTC
