### ISSUE TITLE
Responding with boxed strings breaks HTTP server

### ISSUE THREAD

**Issue by Mabi19** [denoland/deno#25203] opened 2024-08-25 15:20 UTC
Version: Deno 1.46.0 and 1.46.1 (does not happen on 1.45.5 and below)
OS: Windows 11 / Linux (Debian 12)

Returning a `Response` made with a boxed string in the `Deno.serve` callback results in multiple calls to the handler per request and no data actually being sent, resulting in a "connection reset" / "empty response" error on the client-side.

```ts
Deno.serve(() => new Response(new String("uh oh!") as string));
```
Boxed strings are occasionally sent by Hono apps, like this one:
```ts
// assuming import map entry for "hono" exists
import { Hono } from "hono";
import { html } from "hono/html";

const app = new Hono();

app.get("/", (ctx) => {
    console.log("this will be logged multiple times!");
    return ctx.html(
        Promise.resolve(html`<div></div>`),
    );
});

Deno.serve(app.fetch);
```

**Comment by lucacasonato** [comment] 2024-08-26 09:05
Caused by ba40347a35d10cffeae83ee95f69f7bc281096dd. Trying to figure out right now whether this is intentional or not.

**Comment by lucacasonato** [comment] 2024-08-26 09:20
Yup, definitely a bug.

**Comment by lucacasonato** [comment] 2024-08-29 12:42
Fixed in https://github.com/denoland/deno/pull/25207

**Closed by lucacasonato** 2024-08-29 12:42 UTC
Labels: bug, ext/http
