### ISSUE TITLE
deno compile with deno.json lost import map

### ISSUE THREAD

**Issue by iugo** [denoland/deno#16985] opened 2022-12-08 03:36 UTC
https://gist.github.com/iugo/1dde0cb200e57f64df71c31ca0400b16

```ts
// main.ts
import { blue } from 'colors';

console.log(blue('hehe'));

// deno compile --output=bin -c deno.json main.ts
// ./bin (error, lost import map)

// deno compile --output=bin --import-map import_map.json main.ts
// ./bin (works!)
```

```ts
// deno.json
{
  "compilerOptions": {
    "strict": true
  },
  "importMap": "./import_map.json"
}
```

```ts
// import_map.json
{
  "imports": {
    "colors": "https://deno.land/std@0.167.0/fmt/colors.ts"
  }
}
```

deno version: 1.28.3

**Comment by dsherret** [comment] 2022-12-08 14:14
This is a duplicate of #14246. We'll look into it soon.

A workaround is to specify the import map as a command line argument.

**Closed by dsherret** 2022-12-08 14:14 UTC
