### ISSUE TITLE
Package.json git+ flag not supported

### ISSUE THREAD

**Issue by PauTym** [denoland/deno#26620] opened 2024-10-29 15:01 UTC
Deno 2.0.3 (stable, release, x86_64-pc-windows-msvc)
v8 12.9.202.13-rusty
typescript 5.6.2

When trying to run `deno install` with a package.json file that has git-links as dependencies we get this error. 
![image](https://github.com/user-attachments/assets/b55fccee-0227-4b16-89d7-4a89ac7aac88)
package.json example: 
`{
    "dependencies": {
          "@gitUser/customDependencie": "git+https://bitbucket....",
           ....
     }
}`

when removing the `git+` it will work, but then its no longer compatible with node (wich still runs the project on my server)

**Comment by marvinhagemeister** [comment] 2024-10-29 15:06
Duplicate of https://github.com/denoland/deno/issues/18557

**Closed by marvinhagemeister** 2024-10-29 15:06 UTC
