### ISSUE TITLE
Cannot run wasm on apple m1 device (MacBook Air)

### ISSUE THREAD

**Issue by yw662** [denoland/deno#9551] opened 2021-02-19 20:52 UTC
(It is very likely an issue of V8, but)
https://github.com/denoland/deno/issues/9421 says it should be fixed.

However, I am on a newly upgraded Deno binary but it still happens.
```
deno 1.7.5 (release, aarch64-apple-darwin)
v8 9.0.123
typescript 4.1.4
```
This error happens when trying to invoke a wasm module:
```
#
# Fatal error in , line 0
# Check failed: allocator->SetPermissions(reinterpret_cast<void*>(region.begin()), region.size(), PageAllocator::kNoAccess).
#
#
#
#FailureMessage Object: 0x16f0547e8
==== C stack trace ===============================

    0   deno                                0x00000001014e7fb4 v8::base::debug::StackTrace::StackTrace() + 24
    1   deno                                0x00000001014ec094 v8::platform::(anonymous namespace)::PrintStackTrace() + 24
    2   deno                                0x00000001014e48e8 V8_Fatal(char const*, ...) + 268
    3   deno                                0x0000000101a63304 v8::internal::wasm::NativeModule::NativeModule(v8::internal::wasm::WasmEngine*, v8::internal::wasm::WasmFeatures const&, v8::internal::VirtualMemory, std::__1::shared_ptr<v8::internal::wasm::WasmModule const>, std::__1::shared_ptr<v8::internal::Counters>, std::__1::shared_ptr<v8::internal::wasm::NativeModule>*) + 0
    4   deno                                0x0000000101a6655c v8::internal::wasm::NativeModule::FreeCode(v8::internal::Vector<v8::internal::wasm::WasmCode* const>) + 44
    5   deno                                0x0000000101a7483c v8::internal::wasm::WasmEngine::FreeDeadCodeLocked(std::__1::unordered_map<v8::internal::wasm::NativeModule*, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> >, std::__1::hash<v8::internal::wasm::NativeModule*>, std::__1::equal_to<v8::internal::wasm::NativeModule*>, std::__1::allocator<std::__1::pair<v8::internal::wasm::NativeModule* const, std::__1::vector<v8::internal::wasm::WasmCode*, std::__1::allocator<v8::internal::wasm::WasmCode*> > > > > const&) + 348
    6   deno                                0x0000000101a72744 v8::internal::wasm::WasmEngine::PotentiallyFinishCurrentGC() + 544
    7   deno                                0x0000000101a73e30 v8::internal::wasm::WasmEngine::ReportLiveCodeForGC(v8::internal::Isolate*, v8::internal::Vector<v8::internal::wasm::WasmCode*>) + 464
    8   deno                                0x0000000101a73fb0 v8::internal::wasm::WasmEngine::ReportLiveCodeFromStackForGC(v8::internal::Isolate*) + 272
    9   deno                                0x0000000101643614 v8::internal::StackGuard::HandleInterrupts() + 2148
    10  deno                                0x000000010193f5b4 v8::internal::Runtime_StackGuard(int, unsigned long*, v8::internal::Isolate*) + 312
    11  deno                                0x0000000101e2aeac Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_NoBuiltinExit + 108
    12  deno                                0x0000000101ec0408 Builtins_JumpLoopHandler + 200
    13  deno                                0x0000000101dc4c50 Builtins_InterpreterEntryTrampoline + 272
    14  deno                                0x0000000101e4724c Builtins_ArrayMap + 1292
    15  deno                                0x0000000101dc4c50 Builtins_InterpreterEntryTrampoline + 272
    16  deno                                0x0000000101dc4c50 Builtins_InterpreterEntryTrampoline + 272
    17  deno                                0x0000000101df283c Builtins_AsyncFunctionAwaitResolveClosure + 92
    18  deno                                0x0000000101e74f9c Builtins_PromiseFulfillReactionJob + 60
    19  deno                                0x0000000101de5780 Builtins_RunMicrotasks + 672
    20  deno                                0x0000000101dc2824 Builtins_JSRunMicrotasksEntry + 164
    21  deno                                0x000000010161b004 v8::internal::(anonymous namespace)::Invoke(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) + 2468
    22  deno                                0x000000010161b51c v8::internal::(anonymous namespace)::InvokeWithTryCatch(v8::internal::Isolate*, v8::internal::(anonymous namespace)::InvokeParams const&) + 88
    23  deno                                0x000000010161b5e4 v8::internal::Execution::TryRunMicrotasks(v8::internal::Isolate*, v8::internal::MicrotaskQueue*, v8::internal::MaybeHandle<v8::internal::Object>*) + 64
    24  deno                                0x00000001016407d0 v8::internal::MicrotaskQueue::RunMicrotasks(v8::internal::Isolate*) + 420
    25  deno                                0x000000010164060c v8::internal::MicrotaskQueue::PerformCheckpoint(v8::Isolate*) + 56
    26  deno                                0x0000000101630f88 v8::internal::Isolate::FireCallCompletedCallback(v8::internal::MicrotaskQueue*) + 72
    27  deno                                0x0000000101545890 v8::Promise::Resolver::Resolve(v8::Local<v8::Context>, v8::Local<v8::Value>) + 364
    28  deno                                0x00000001014df2a0 v8__Promise__Resolver__Resolve + 12
    29  deno                                0x0000000100f9efc4 deno_core::runtime::JsRuntime::dyn_import_done::h35f6587d6755a58d + 388
    30  deno                                0x0000000101081694 tokio::runtime::Runtime::block_on::h725c4f0b2fff3478 + 960
    31  deno                                0x0000000100df1e40 std::sys_common::backtrace::__rust_begin_short_backtrace::h5e70bc2b112988fa + 12
```

**Comment by lucacasonato** [comment] 2021-02-19 20:58
It is fixed in V8, but the V8 revision that this is fixed in has not yet made it into Deno. We are hoping this will be resolved for 1.8 on March 2nd. Closing as duplicate of https://github.com/denoland/deno/issues/9421 (it is still open).

**Closed by lucacasonato** 2021-02-19 20:58 UTC
