### ISSUE TITLE
Support Astro

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#16659] opened 2022-11-16 05:22 UTC
Tracking issue for supporting [astro](https://astro.build/).

Known issues:
- [x] `TypeError: Cannot set property localStorage of #<Window> which has only a getter` when running `deno run npm:astro dev`
- ~~`ReferenceError: process is not defined at validateComponentProps (/node_modules/.deno/astro@1.6.8/node_modules/astro/dist/runtime/server/render/astro.js, <anonymous>:13:61)`~~ This error (strangely) disappeared on the latest version.
- [x] createRequire doesn't accept `URL` (issue for `astro@1.3.0`, but not for latest)
- [x] `astro dev` hangs without any error message #17194 https://github.com/denoland/deno_std/pull/3062
- [ ] `astro build` requires the import map of `{"html-escaper": "npm:html-escaper"}` to work correctly.

**Comment by brenelz** [comment] 2022-11-17 01:59
Now it gets by that error and I get the following:

>  Expected string at position 0
TypeError: Expected string at position 0
    at createRequire (deno:ext/node/02_require.js:823:31)
    at new DependencyWalker (file:///Users/brenelz/Desktop/denoland/deno/node_modules/.deno/astro@1.3.0/node_modules/astro/dist/core/create-vite.js:129:20)

**Comment by kt3k** [comment] 2022-11-17 06:43
> TypeError: Expected string at position 0

Added it to the issue list. (`createRequire doesn't accept URL`)

**Comment by kt3k** [comment] 2022-12-16 10:00
The 2nd issue disappeared. Added the 4th and 5th issues.

**Comment by brenelz** [comment] 2022-12-17 22:44
So I played around with it and it seems to be some kind of bug with ReadableStream. If i turn off streaming it works fine.

https://github.com/withastro/astro/blob/main/packages/astro/src/core/render/dev/environment.ts#L35

**Comment by brenelz** [comment] 2022-12-17 23:40
So I think the issue is it sending a 0 length UIntArray which is screwing up ReadableStream

**Comment by kt3k** [comment] 2022-12-27 11:45
@brenelz I looked into your fix in details, and it looked like 0 length Uint8Array is ok for ReadableStream, but it causes an issue in our server implementation (Deno.serve) https://github.com/denoland/deno/issues/17194. I created an workaround in deno_std https://github.com/denoland/deno_std/pull/3062. Thanks for your research!

**Comment by brenelz** [comment] 2022-12-27 13:32
@kt3k should I close my pr then? Hopefully it at least helped put you on the right track

**Comment by kt3k** [comment] 2022-12-27 15:20
@brenelz 
> I would test it but not sure how to use in progress deno_std

You can replace `std/node` implementation with your local one, by setting `DENO_NODE_COMPAT_URL` env var, like:

`DENO_NODE_COMPAT_URL=file:///path/to/deno_std/ deno run -A --node-modules-dir npm:astro dev`

You can also replace it with one in a remote branch, like:

`DENO_NODE_COMPAT_URL=https://raw.githubusercontent.com/kt3k/deno_std/workaround-empty-chunk-issue/ deno run -A --node-modules-dir npm:astro dev`

**Comment by brenelz** [comment] 2022-12-27 17:28
Works great from what I can tell. Thanks!

**Comment by kt3k** [comment] 2023-02-24 12:51
Now `astro dev` command seems working.

(The below steps work with 1.31.0)
```
deno run -A npm:create-astro my-app
cd my-app
deno task dev
```

`astro build` still fails with the error `Relative import path "html-escaper" not prefixed with / or ./ or ../`

**Comment by lilnasy** [comment] 2023-05-01 18:26
There seems to have been a regression since 1.31, there are multiple other dependencies that fail to resolve now.
![Screenshot (119)](https://user-images.githubusercontent.com/69170106/235506116-349750ac-0270-466c-925b-fa9e9656ac59.png)

**Comment by lilnasy** [comment] 2023-05-01 20:05
Deno can run dev for an older version of Astro
![Screenshot (120)](https://user-images.githubusercontent.com/69170106/235521438-a8d6b88f-ef53-48a6-bb29-e973879e5a22.png)

Newer versions fail in a variety of ways
![Screenshot (121)](https://user-images.githubusercontent.com/69170106/235521746-05948f13-57d2-4297-a1b8-eb9db232e7c7.png)
![Screenshot (122)](https://user-images.githubusercontent.com/69170106/235521598-3a0eed80-9a5c-4431-9257-2e6a9a76c6d0.png)
![Screenshot (123)](https://user-images.githubusercontent.com/69170106/235521604-17ab1175-4a68-4cb4-98ec-b606b4e2ce41.png)

**Comment by bartlomieju** [comment] 2023-05-01 22:53
@lilnasy the problem you with the latest Deno version should be fixed by https://github.com/denoland/deno/pull/18948 and will be released in Deno 1.32.2 later this week.

**Comment by lilnasy** [comment] 2023-05-01 23:32
@bartlomieju I built and ran deno from you branch, and I can cofirm those issues are gone, but there are others blocking astro support still. In particular, detecting package.json breaks module graph resolution.
![Screenshot (125)](https://user-images.githubusercontent.com/69170106/235548932-9537456a-b729-41b6-9012-bbe208ea1c1e.png)
![Screenshot (126)](https://user-images.githubusercontent.com/69170106/235548940-e23bd0d0-5bb3-4b0a-a3e1-44b74c7c7149.png)
![Screenshot (127)](https://user-images.githubusercontent.com/69170106/235548951-173f04d6-5c2d-430f-a0b6-847dddfecd10.png)

**Comment by bartlomieju** [comment] 2023-05-01 23:33
Thanks for the report. I will take a deeper look at Astro in the coming days.

**Comment by lilnasy** [comment] 2023-05-18 19:51
There was more progress in 1.33.4. Now seems to be blocked on createBrotliDecompress.
![Screenshot (173)](https://github.com/denoland/deno/assets/69170106/910f61d9-0978-4ce2-aa45-c408b5357745)

**Comment by lilnasy** [comment] 2023-05-18 23:07
Thanks to @bartlomieju, astro is really close to working on deno again. The one blocker is undici, which isn't even necessary on deno, and planned for removal with node 16 EOL.

![Screenshot (179)](https://github.com/denoland/deno/assets/69170106/0de9c06f-f582-4ba8-ac0e-148b105f1c48)

**Comment by bartlomieju** [comment] 2023-05-18 23:24
@lilnasy thanks for keeping tabs. We did not manage to complete `createBrotliDecompress` for v1.33.4 but we'll try to ship it for v1.34 next week. If you find any more quirks, make sure to let me know!

**Comment by bartlomieju** [comment] 2023-06-28 20:25
With #19223 landed Astro should now work in Deno. I'm gonna close this issue, please open new issues if you hit any more problems.

**Closed by bartlomieju** 2023-06-28 20:25 UTC
Labels: node compat
