### ISSUE TITLE
deno completions zsh crashing after update, with thread panic

### ISSUE THREAD

**Issue by Sparkenstein** [denoland/deno#8686] opened 2020-12-09 11:30 UTC
After updating to 1.6.0, `deno completions` command is crashing with zsh, note that earlier shell completions are working, just the `deno completions zsh` is crashing, other completions like `deno completions bash` or even `deno completions elvish` working fine.

error:
```
thread 'main' panicked at 'Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/completions/zsh.rs:407:29
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

with backtrace:
```
thread 'main' panicked at 'Fatal internal error. Please consider filing a bug report at https://github.com/clap-rs/clap/issues', /home/runner/.cargo/registry/src/github.com-1ecc6299db9ec823/clap-2.33.3/src/completions/zsh.rs:407:29
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1226
   3: core::option::Option<T>::expect
   4: clap::completions::zsh::get_args_of
   5: clap::completions::zsh::get_subcommands_of
   6: deno::flags::flags_from_vec_safe
   7: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

```

this looks clap-rs issue to me, not sure if something is wrong on deno side

**Comment by lucacasonato** [comment] 2020-12-09 11:44
Duplicate of #8472

**Closed by lucacasonato** 2020-12-09 11:44 UTC
