### ISSUE TITLE
CLI Wont Let The User Input (Closes the CLI without letting the user to input data)

### ISSUE THREAD

**Issue by Tenuka22** [denoland/deno#23154] opened 2024-03-31 16:17 UTC
`
╭─tenuka22@tenuka in ~
╰─λ deno run --allow-read --allow-write --allow-env npm:create-vite-extra@latest
? Project name: › vite-projecterror: Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'Symbol(Deno.internal.rid)')
at TTY.#read (ext:deno_node/internal_binding/stream_wrap.ts:220:45)
at TTY.readStart (ext:deno_node/internal_binding/stream_wrap.ts:90:17)
at _tryReadStart (node:net:276:30)
at ReadStream._read (node:net:856:7)
at ReadStream.Readable.read (ext:deno_node/_stream.mjs:2999:16)
at ReadStream.read (node:net:789:34)
at resume_ (ext:deno_node/_stream.mjs:3349:16)
at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:33:15)
at eventLoopTick (ext:core/01_core.js:165:29)

╭─tenuka22@tenuka in ~ took 184ms
[🔴] ×
`
![image](https://github.com/denoland/deno/assets/135237290/43a955b4-a0b7-41e5-9ccf-1b676debeea0)

This Is The Error I'm Getting. The CLiI wont let me input anything,

**Comment by dsherret** [comment] 2024-03-31 20:47
Duplicate of #23115 and #23107?

**Comment by KieranP** [comment] 2024-03-31 23:56
This is a huge issue. We can't even follow the deno tutorials for react app. If the issue is fixed (de0b230078daebbbec82ea5d7aabb9f0a429125f), shouldn't a 1.42.1 release be issued ASAP? Otherwise the first impression of following the tutorials isn't great. cc @dsherret @bartlomieju @littledivy

**Comment by bartlomieju** [comment] 2024-04-01 07:00
Divy is cutting v1.42.1 right now

**Comment by littledivy** [comment] 2024-04-01 09:09
v1.42.1 released

**Closed by littledivy** 2024-04-01 09:09 UTC
