### ISSUE TITLE
JsPrettyError panics on unwrap

### ISSUE THREAD

**Issue by MierenManz** [denoland/deno#9392] opened 2021-02-03 21:26 UTC
Panic on format:

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli\fmt_errors.rs:211:45
```

It only panic's specifically on this specific line:

```ts
if (name === this.#DB[i].name) throw new Error(name);
```

I wanted to provide a log but idk how to run with `RUST_BACKTRACE=1`

deno info:

deno 1.7.1 (release, x86_64-pc-windows-msvc)
v8 8.9.255.3
typescript 4.1.3

**Comment by MierenManz** [comment] 2021-02-03 21:29
```ts
      if (name === this.#DB[i].name) {
        throw new Error(name);
      }
```
this fixes that issue

**Comment by dsherret** [comment] 2021-02-03 22:33
@MierenManz what command are you running? (ex. `deno <what-cmd>`?)

**Comment by MierenManz** [comment] 2021-02-03 22:35
`deno run -A test.ts`

**Comment by nayeemrmn** [comment] 2021-02-03 22:37
Duplicate of #6965. It may occur or not occur for different formattings, but that's a red herring.

**Comment by dsherret** [comment] 2021-02-06 17:04
Could we rename the title on this issue since it's not a deno fmt panic?

**Comment by kitsonk** [comment] 2021-02-07 22:34
Duplicate of #6965.

**Closed by kitsonk** 2021-02-07 22:34 UTC
Labels: duplicate
