### ISSUE TITLE
deno_test_fail_fast failed on 1.0.1, printed non-failfast output

### ISSUE THREAD

**Issue by 06kellyjac** [denoland/deno#5676] opened 2020-05-20 18:34 UTC
Just ran into this error on the test `deno_test_fail_fast` building on the tag `v1.0.1`

The output matches the non-failfast output

Going to run again with a full backtrace

```
failures:

---- deno_test_fail_fast stdout ----
target_dir /build/source/target/debug
root path /build/source/cli/..
deno_exe path /build/source/target/debug/deno
target_dir /build/source/target/debug
output path /build/source/cli/../cli/tests/deno_test_fail_fast.out
[cli/tests/integration_tests.rs:2767] part = "\nrunning 4 tests\ntest fail1 ... FAILED "
[cli/tests/integration_tests.rs:2767] i = 1
[cli/tests/integration_tests.rs:2773] "found " = "found "
[cli/tests/integration_tests.rs:2773] found = 52
[cli/tests/integration_tests.rs:2767] part = "\n\nfailures:\n\nfail1\nAssertionError: fail1 assertion\n"
[cli/tests/integration_tests.rs:2767] i = 2
[cli/tests/integration_tests.rs:2773] "found " = "found "
[cli/tests/integration_tests.rs:2773] found = 88
[cli/tests/integration_tests.rs:2767] part = "\n\nfailures:\n"
[cli/tests/integration_tests.rs:2767] i = 3
[cli/tests/integration_tests.rs:2773] "found " = "found "
[cli/tests/integration_tests.rs:2773] found = 1261
[cli/tests/integration_tests.rs:2767] part = "\n\ntest result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out "
[cli/tests/integration_tests.rs:2767] i = 4
[cli/tests/integration_tests.rs:2776] "exit false " = "exit false "
[cli/tests/integration_tests.rs:2776] i = 4
OUTPUT
Compile file:///build/source/cli/tests/.deno.test.ts
running 4 tests
test fail1 ... FAILED (1ms)
test fail2 ... FAILED (0ms)
test success1 ... ok (4ms)
test fail3 ... FAILED (0ms)

failures:

fail1
AssertionError: fail1 assertion
    at assert (file:///build/source/std/testing/asserts.ts:135:11)
    at file:///build/source/cli/tests/test_runner_test.ts:6:3
    at asyncOpSanitizer ($deno$/testing.ts:36:11)
    at Object.resourceSanitizer [as fn] ($deno$/testing.ts:70:11)
    at TestApi.[Symbol.asyncIterator] ($deno$/testing.ts:264:22)
    at TestApi.next (<anonymous>)
    at Object.runTests ($deno$/testing.ts:346:20)

fail2
AssertionError: fail2 assertion
    at assert (file:///build/source/std/testing/asserts.ts:135:11)
    at file:///build/source/cli/tests/test_runner_test.ts:10:3
    at asyncOpSanitizer ($deno$/testing.ts:36:11)
    at Object.resourceSanitizer [as fn] ($deno$/testing.ts:70:11)
    at TestApi.[Symbol.asyncIterator] ($deno$/testing.ts:264:22)
    at TestApi.next (<anonymous>)
    at Object.runTests ($deno$/testing.ts:346:20)

fail3
AssertionError: fail3 assertion
    at assert (file:///build/source/std/testing/asserts.ts:135:11)
    at file:///build/source/cli/tests/test_runner_test.ts:18:3
    at asyncOpSanitizer ($deno$/testing.ts:36:11)
    at Object.resourceSanitizer [as fn] ($deno$/testing.ts:70:11)
    at TestApi.[Symbol.asyncIterator] ($deno$/testing.ts:264:22)
    at TestApi.next (<anonymous>)
    at Object.runTests ($deno$/testing.ts:346:20)

failures:

        fail1
        fail2
        fail3

test result: FAILED. 1 passed; 3 failed; 0 ignored; 0 measured; 0 filtered out (7ms)


OUTPUT
EXPECTED
[WILDCARD]
running 4 tests
test fail1 ... FAILED [WILDCARD]

failures:

fail1
AssertionError: fail1 assertion
[WILDCARD]

failures:
[WILDCARD]

test result: FAILED. 0 passed; 1 failed; 0 ignored; 0 measured; 0 filtered out [WILDCARD]


EXPECTED
thread 'deno_test_fail_fast' panicked at 'pattern match failed', cli/tests/integration_tests.rs:2734:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace


failures:
    deno_test_fail_fast

test result: FAILED. 177 passed; 1 failed; 12 ignored; 0 measured; 9 filtered out
```

**Comment by 06kellyjac** [comment] 2020-05-20 18:46
2nd run with backtrace full passed...

**Comment by 06kellyjac** [comment] 2020-05-20 19:13
Worked again, very odd...

I'm happy for this to be closed as not reproducible.
Very weird considering I was using nix so the repo & cargo.lock are against SHAs, the build directory is fresh every time so no remnants from previous builds

**Comment by bartlomieju** [comment] 2020-05-21 11:15
@06kellyjac closing this one as I can't reproduce it locally and CI is green

**Closed by bartlomieju** 2020-05-21 11:15 UTC
