### ISSUE TITLE
"module not found" for binaries compiled with 1.19

### ISSUE THREAD

**Issue by irbull** [denoland/deno#13904] opened 2022-03-10 22:30 UTC
The following example worked fine in 🦖 Deno 1.18, but fails in Deno 1.19

```
// example.ts
import Yargs from 'https://deno.land/x/yargs@v17.3.0-deno/deno.ts';
Yargs();
```
Compile:
```
deno compile -A --unstable example.ts 
```

then run `./example`
This fails with:
```
error: Module not found
```
This worked with Deno 1.18 and earlier.

**Comment by kitsonk** [comment] 2022-03-11 00:06
I can reproduce.

@littledivy I suspect something is going wrong with the eszip in this scenario.  I don't see anything specifically odd with `deno info` for this.  It also feels like we need a better error message when this occurs, because there are 49 unique dependencies in that graph.

**Comment by dshick-nydig** [comment] 2022-03-15 15:08
I think this issue is a dupe of https://github.com/denoland/deno/issues/13704, but yeah, I agree the bug was introduced here...https://github.com/denoland/deno/pull/13563

**Comment by kitsonk** [comment] 2022-03-15 22:39
Yes, there are 3 redirects in there:

```json
{
  "redirects": {
    "https://deno.land/std/fmt/printf.ts": "https://deno.land/std@0.129.0/fmt/printf.ts",
    "https://deno.land/std/path/mod.ts": "https://deno.land/std@0.129.0/path/mod.ts",
    "https://deno.land/std/testing/asserts.ts": "https://deno.land/std@0.129.0/testing/asserts.ts"
  }
}
```

**Comment by kitsonk** [comment] 2022-03-15 22:40
Duplicate of #13704

**Closed by kitsonk** 2022-03-15 22:39 UTC
Labels: bug, compile
