### ISSUE TITLE
Some WHATWG streams types not available on `globalThis`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#12484] opened 2021-10-18 20:57 UTC
The CI errors seem to be typing issues exposed by this PR:

```
  ByteLengthQueuingStrategy,
  ~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/runner/work/deno_std/deno_std/node/stream/web.ts:2:3

TS2339 [ERROR]: Property 'CountQueuingStrategy' does not exist on type 'typeof globalThis'.
  CountQueuingStrategy,
  ~~~~~~~~~~~~~~~~~~~~
    at file:///Users/runner/work/deno_std/deno_std/node/stream/web.ts:3:3

TS2339 [ERROR]: Property 'TextDecoderStream' does not exist on type 'typeof globalThis'.
  TextDecoderStream,
  ~~~~~~~~~~~~~~~~~
    at file:///Users/runner/work/deno_std/deno_std/node/stream/web.ts:8:3

TS2339 [ERROR]: Property 'TextEncoderStream' does not exist on type 'typeof globalThis'.
  TextEncoderStream,
  ~~~~~~~~~~~~~~~~~
    at file:///Users/runner/work/deno_std/deno_std/node/stream/web.ts:9:3

TS2339 [ERROR]: Property 'TransformStreamDefaultController' does not exist on type 'typeof globalThis'.
  TransformStreamDefaultController,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/runner/work/deno_std/deno_std/node/stream/web.ts:11:3

TS2339 [ERROR]: Property 'WritableStreamDefaultController' does not exist on type 'typeof globalThis'.
  WritableStreamDefaultController,
  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at file:///Users/runner/work/deno_std/deno_std/node/stream/web.ts:13:3
```

these are definitely defined on the global so just seem to be omitted from the types for some reason.

_Originally posted by @guybedford in https://github.com/denoland/deno_std/issues/1430#issuecomment-946153497_

**Comment by kitsonk** [comment] 2021-10-19 03:07
(though they will appear in the ambient global context, :shrug:)

**Comment by kitsonk** [comment] 2021-10-19 07:21
Yeah, this is a duplicate of #9957 really, forgot about it.

**Closed** 2021-10-21 06:47 UTC
