### ISSUE TITLE
Failed to get directory listing

### ISSUE THREAD

**Issue by abhi11210646** [denoland/deno#5563] opened 2020-05-17 19:32 UTC
> Querying the GitHub API failed. This is usually caused by a network outage or because you have reached your hourly API rate limit of 60 requests.

![image](https://user-images.githubusercontent.com/16542492/82158080-19e8cd80-98a3-11ea-891f-75d141819330.png)

**Comment by nayeemrmn** [comment] 2020-05-17 19:34
Duplicate of https://github.com/denoland/deno_website2/issues/433.

**Closed** 2020-05-17 19:36 UTC
