### ISSUE TITLE
expose rusqlite natively under Deno global

### ISSUE THREAD

**Issue by andykais** [denoland/deno#14460] opened 2022-05-02 14:51 UTC
So far I have been watching node compatibility features, wasm features, and ffi features all to serve one purpose for myself, to expose a a reliable, fast sqlite interface in deno. There are several good sqlite implementations that exist in deno userland thus far:
- https://deno.land/x/sqlite (a wasm compilation)
- https://deno.land/x/sqlite3 (an ffi binding)
- https://github.com/denodrivers/async-sqlite3 (ffi bindings using rusqlite)

These projects are usable, but they all have their own pitfalls. The wasm libraries are portable, but suffer a reduction in speed, and their memory usage is capped at 4GB. The FFI libraries are generally faster, but still cannot match native bindings, and have an added difficulty of requiring an external dependency. Developers of FFI libraries also have the headache of dealing with end users using different versions of sqlite underneath their js interface.

Here is a small benchmark report given by the `async-sqlite3` library:
```deno_sqlite3
  insert 10_000 rows in bench.db: 1114.5801ms
  query 10_000 rows in bench.db: 30.3004ms

x/sqlite3
  insert 10_000 rows in bench.db: 1306.1578ms
  query 10_000 rows in bench.db: 163.2021ms

node-sqlite3
  insert 10_000 rows in bench.db: 1165.0645ms
  query 10_000 rows in bench.db: 8.1728ms

better-sqlite3
  insert 10_000 rows in bench.db: 592.1117ms
  query 10_000 rows in bench.db: 11.3483ms

x/sqlite
  insert 10_000 rows in bench.db: 28672.3261ms
  query 10_000 rows in bench.db: 16.8747ms
```

Wherever I see a javascript interface to sqlite, better-sqlite3 always seems to win out. It uses NAN (Native Abstractions for Node.js). Deno already includes a rusqlite implementation inside it for things like `localStorage`, so exposing the library to users would not require pulling more dependencies into deno, just exposing more of the underlying systems. I feel (but dont know for certain) that if we had native rust v8 bindings to a library inside deno core, we could achieve some very impressive speeds, and avoid some of the traps that come with wasm compilations.

The interface could be very simple, just exposing prepared statements, database open & close and query execution. That alone would allow deno developers to write their own database abstractions with a solid foundation. The existing sqlite library authors do not need to go away if this is implemented,. Of course, an STD implementation of a sqlite database would be fantastic, but I think starting with the building blocks here makes the most sense.

## drawbacks to deno exposing rusqlite

So far as I can tell, here are the arguments against this:
1. This is another interface to maintain, and `localStorage` has its own special considerations, so making rusqlite exposed generically would be difficult
2. being able to pick and choose your version of sqlite is actually a feature, not a bug. Tying sqlite version to the deno version limits the flexibility of sqlite

I think these are valid points, but they certainly wouldnt be true for me, but Ill let others speak to their own concerns.

**Comment by crowlKats** [comment] 2022-05-02 15:29
Duplicate of #11657

**Closed by crowlKats** 2022-05-02 15:29 UTC
Labels: suggestion

**Comment by andykais** [comment] 2022-05-02 15:56
It seems like the original issue is suggesting how to include a wasm implementation in std, not a native one. I will move my discussion there though

**Comment by crowlKats** [comment] 2022-05-02 16:22
> It seems like the original issue is suggesting how to include a wasm implementation in std, not a native one.

The issue asks to add sqlite functionality to the Deno ns, but Bartek replied with that we wont add such thing, but rather we might move a third party library into std to do that via wasm.

**Comment by waynebloss** [comment] 2022-05-05 20:16
I was under the impression that the WASM lib also prevents you from using WAL. Is that true?

I can't remember where I read that right now.

**Comment by andykais** [comment] 2022-05-05 20:19
I don't know if that is a limitation of WASM, or just the library itself https://github.com/dyedgreen/deno-sqlite/issues/158
