### ISSUE TITLE
Deno.serve does not work with `deno watch` nicely

### ISSUE THREAD

**Issue by winston0410** [denoland/deno#15980] opened 2022-09-21 08:16 UTC
I use the following command to run my scripts:

```sh
deno run --watch --allow-net --allow-env --allow-read --unstable ./src/index.ts
```

```ts
// index.ts
Deno.serve(opts, (req) => {
	return new Response()
})
```

Whenever I change the code in that file, I will get an error like this:

```
error: Uncaught (in promise) AddrInUse: Address already in use (os error 48)
Watcher Process finished. Restarting on file change...
```

Which does not happen for the `std/http` api

**Comment by littledivy** [comment] 2022-09-21 08:23
Duplicate of #15646. Thanks for reporting

**Closed by littledivy** 2022-09-21 08:23 UTC
