### ISSUE TITLE
Is it compatible with ttypescript transformers?

### ISSUE THREAD

**Issue by masx200** [denoland/deno#15458] opened 2022-08-11 15:30 UTC
https://www.npmjs.com/package/ttypescript

```json
{
    "compilerOptions": {
        "plugins": [
            { "transform": "transformer-module" },
        ]
    }
}
```
https://www.npmjs.com/package/tst-reflect-transformer

**Comment by kitsonk** [comment] 2022-08-11 23:29
Duplicate of #3354

**Closed by kitsonk** 2022-08-11 23:29 UTC
Labels: duplicate
