### ISSUE TITLE
The console display is abnormal on Windows when console encoding is not utf-8

### ISSUE THREAD

**Issue by idanran** [denoland/deno#14516] opened 2022-05-06 16:57 UTC
implement:
```js
console.log("你好，世界")
```
output:
```
浣犲ソ锛屼笘鐣?
```
Deno:1.21.2
OS:Windows 11

**Comment by andreubotella** [comment] 2022-05-06 17:03
Seems to be a duplicate of #6001, with the windows command line interpreting the UTF-8 output as if it was GBK.

**Comment by idanran** [comment] 2022-05-07 01:40
> Seems to be a duplicate of #6001, with the windows command line interpreting the UTF-8 output as if it was GBK.

This problem did not exist before

**Comment by andreubotella** [comment] 2022-05-07 09:52
I tried this out on a Windows machine and there is indeed a difference on the `console.log` output. #14435 seems to be the most likely culprit.

cc @dsherret

**Comment by idanran** [comment] 2022-05-07 10:14
> I tried this out on a Windows machine and there is indeed a difference on the `console.log` output since 1.21.1. #14435 seems to be the most likely culprit.
> 
> cc @dsherret

i see

**Comment by andreubotella** [comment] 2022-05-07 10:20
Looking further into this, it looks like `deno_core`'s `op_print` is using Rust's [`std::io::stdout()`](https://doc.rust-lang.org/std/io/fn.stdout.html), which seems to explicitly handle text encoding in Windows, while the new `op_print` in `deno_runtime` (which was created so you could capture output in tests) uses [`std::fs::File`](https://doc.rust-lang.org/std/fs/struct.File.html) wrapping the stdout file descriptor, which of course doesn't handle encoding. This is also the reason for #6001, since `Deno.stdout` also uses the `std::fs::File` wrapper.

**Comment by dsherret** [comment] 2022-05-08 15:33
At least it's consistent now.

@piscisaureus since you were involved in #6001, what would you recommend here? Us calling `SetConsoleOutputCP(CP_UTF8)`?

**Closed** 2022-05-11 16:48 UTC
Labels: bug, windows
