### ISSUE TITLE
File Server malformed request

### ISSUE THREAD

**Issue by dysc** [denoland/deno#2216] opened 2019-04-26 06:46 UTC
@ry I noticed today at js.la you had to use `-A` to make the file server demo work. Something with some malformed header and unicode data. Just wanted to keep this posted as it wasn't already afaik :)

Great presentation Ryan, I love the work you're doing at Deno and I'm excited to use it for javascript sandboxing! Thanks!

**Comment by ry** [comment] 2019-04-26 15:13
Thanks for reporting! I still have the log, it looks like this:
```
>  deno https://deno.land/std/http/file_server.ts
⚠️  Deno requests network access to "listen". Grant? [a/y/n/d (a = allow always, y = allow once, n = deny once, d = deny always)] a
HTTP server listening on http://0.0.0.0:4500/
⚠️  Deno requests read access to "/Users/rld/deno_examples_jsla2". Grant? [a/y/n/d (a = allow always, y = allow once, n = deny once, d = deny always)] a
[2019-04-26 03:26:38] "GET / HTTP/1.1" 200
/Users/rld/Library/Caches/deno/deps/https/raw.githubusercontent.com/denoland/deno_std/master/textproto/mod.ts:85:22
                throw new ProtocolError(`malformed MIME header line: ${str(kv)}`);
                      ^
Uncaught ProtocolError: malformed MIME header line: �
    at ProtocolError (file:///Users/rld/Library/Caches/deno/deps/https/raw.githubusercontent.com/denoland/deno_std/master/textproto/mod.ts:20:5)
    at readMIMEHeader (file:///Users/rld/Library/Caches/deno/deps/https/raw.githubusercontent.com/denoland/deno_std/master/textproto/mod.ts:95:15)
```
I'm playing around with it now, but can't seem to repeat the exception...

**Comment by zekth** [comment] 2019-04-26 15:20
@ry seems like the `deno_examples_jsla2` file has a problem. Could you provide it?

**Comment by ry** [comment] 2019-04-26 15:32
@zekth that's just the working directory. I guess it was caused by using chromium to visit the file_server and somehow it sent some unicode in a header?

**Comment by zekth** [comment] 2019-04-26 16:11
Can't reproduce on any browser on Windows / MacOs. Maybe you had an IO issue during the demo?

**Comment by zekth** [comment] 2019-05-24 08:22
I think we can close this one now.

**Closed** 2019-05-24 10:27 UTC
Labels: bug
