### ISSUE TITLE
Add a `--strip` option for `deno compile`

### ISSUE THREAD

**Issue by Dialga** [denoland/deno#9198] opened 2021-01-20 15:09 UTC
```
$ cat hi.js
console.log('hi');
$ deno --unstable compile hi.js 
Bundle file:///home/me/js/hi.js
Compile file:///home/me/js/hi.js
Emit hi
$ ./hi
hi
$ strip hi
$ ./hi
Deno 1.7.0
exit using ctrl+d or close()
> 
$ rm -f hi
$ deno --unstable compile --lite hi.js                                                                                                                               
Bundle file:///home/me/js/hi.js
Compile file:///home/me/js/hi.js
Archive:  /tmp/.tmpguS2X5/denort..zip
  inflating: denort                  
Emit hi
$ ./hi
hi
$ strip hi
$ ./hi
error: This executable is used internally by 'deno compile', it is not meant to be invoked directly.
```

If compile normally and stripped, the deno repl is run, if compiled with --lite it errors out as above.

**Comment by lucacasonato** [comment] 2021-01-20 15:27
`deno compile` binaries do not support being stripped. We might provide a `--strip` flag to do this in the future.

**Comment by Dialga** [comment] 2021-01-20 15:29
Sorry I was not aware of that.

**Comment by evs-chris** [comment] 2021-01-20 22:56
If you're desperate to save ~12mb, on linux-x64 anyways, it looks like you can find the denort archive, extract it, strip the bin, and repack it. A simple hello world continues to work for me after doing that.

```sh
cd /tmp
echo "console.log('hello, smaller deno');" > hello.ts
deno compile --unstable --lite hello.ts
ls -alh hello
# -rwxrwxrwx 1 chris chris 33M Jan 20 17:53 hello
./hello
# hello, smaller deno
cd ~/.cache/deno/dl/release/v1.7.0
unzip denort-x86_64-unknown-linux-gnu.zip
mv denort-x86_64-unknown-linux-gnu.zip denort-x86_64-unknown-linux-gnu.zip.orig
strip denort
zip denort-x86_64-unknown-linux-gnu.zip denort
rm denort
cd /tmp
deno compile --unstable --lite hello.ts
./hello
# hello, smaller deno
ls -alh hello
# -rwxrwxrwx 1 chris chris 21M Jan 20 17:54 hello
```

**Comment by kitsonk** [comment] 2021-01-21 03:22
We have debated stripping debug, even for the light binaries.  The problem is the moment you realise you need the debugging symbols it is too late.  Anyways, let's turn this into the issue for tracking the potential `--strip` option.

**Comment by JohannesRudolph** [comment] 2021-05-20 06:10
I think having a —strip option would be very valuable, especially for those building smallish cli tools using deno. Binary size and process startup time matter a lot for those interactive tools, and they typically need to come with robust input validation and error handling anyways, so debug symbols are not of much help (compared to say a server app that you’re running yourself and want to debug in production). 

I personally find deno compile to be a incredible productive platform for cli tools, but binary size is on the scale of 50 MiB and I’d appreciate any reasonable opportunity to slim them down further.

**Comment by kaiyzen** [comment] 2021-09-01 04:47
I am looking at some CLI use cases, definitely would like to see option to produce as slim a base binary install as possible.

In testing out some examples on my current 1.13.1 install a hello world compile that just does `console.log('hello world');` comes out to ~87MiB on an aws-linux instance. Seeing ref above to "scale of 50MiB" and in searching discord I see references on older versions being ~15Mib leveraging `--lite` else ~34Mib.

Question, assume new versions are adding more bloat to the binary as new features come in, is 80+ MiB the baseline now going forward until something like `--strip` is there and/or reintroducing `--lite`?

**Comment by clemens-tolboom** [comment] 2022-03-12 12:48
My deno compiled executables are quite different in size (Mac 84MB, Linux 89MB, Windows 58MB).

Stripping my `deno` generated files gives error
> ... : the LINKEDIT segment does not cover the end of the file (can't be processed) in ...

On MacOS I can `strip deno` (part of Xcode?) results in size reduction from 84MB to 52MB.

```
cp `which deno` ./deno-stripped
lipo -info deno-stripped
chmod u+w deno-stripped
strip deno-stripped
lipo -info deno-stripped
```

Using this `deno-stripped` generates smaller executables.

**Comment by roj1512** [comment] 2022-03-27 16:50
Really need this.

**Comment by zoubingwu** [comment] 2022-06-07 09:04
Just found this gif in [deno's 1.7 release notes](https://deno.com/blog/v1.7), you can see he copied the 31mb binary to another linux machine.

![https://deno.com/v1.7/cross_compile.gif](https://deno.com/v1.7/cross_compile.gif)

From 31mb to 90mb, that is...huge. 

How do you guys think if we keep a track on this number in deno benchmarks? I believe 30-50 is a relatively acceptable size and it will be a huge help when you want to distribute you app to other machine that doesn't have deno installed.

**Comment by crowlKats** [comment] 2022-06-07 09:09
> From 31mb to 90mb, that is...huge.

in that example the lite flag is used, which was a reduced version of the cli binary. there is no equivalent currently, so its not a fair comparison. the main cli wasnt ever 31mb (or a really long time ago).

**Comment by bartlomieju** [comment] 2024-02-22 20:43
@littledivy I think we can close this issue now that `denort` strips by default?

**Comment by littledivy** [comment] 2024-02-23 03:01
Yes, #22426

**Closed by littledivy** 2024-02-23 03:01 UTC
Labels: suggestion, compile
