### ISSUE TITLE
importmap ignored by `deno install`

### ISSUE THREAD

**Issue by thomas3577** [denoland/deno#17834] opened 2023-02-20 20:29 UTC
When I use importMap, my code does not work as executable (`deno install`).

**Tested with Deno v1.30.3**.

## Minimal reproducible example:

**deno.json:**

```JSON
{
  ...
  "imports": {
    "std/": "https://deno.land/std@0.177.0/"
  },
  ...
}
```

**my-cli.ts**

```TypeScript
import * as log from 'std/log/mod.ts';

log.info('Hello world!')
```

**Install & run:**

```bash
deno install -A ./my-cli.ts

my-cli <--- This throws the error
```

**Error output:**
```bash
error: Relative import path "std/log/mod.ts" not prefixed with / or ./ or ../
    at file:///C:/temp/app.ts:1:22
```

The same problem when I use an import map file (import_map.json). Only if I use absolute paths, it also works with `deno install`.

**Comment by dsherret** [comment] 2023-02-21 17:36
This is a duplicate of #17572. See https://github.com/denoland/deno/issues/17572#issuecomment-1407474656 and I opened https://github.com/denoland/deno/issues/17855

**Closed by dsherret** 2023-02-21 17:36 UTC
