### ISSUE TITLE
Deno picks up code in comment

### ISSUE THREAD

**Issue by jakajancar** [denoland/deno#4464] opened 2020-03-23 00:31 UTC
Ran into this error while working on `fp-ts`:

```
% cat import-in-comment.ts 
function hello(who: string): string {
  return `hello ${who}`;
}
/**
 * `
 * import { scanLeft } from 'some/path/in/comment.ts'
 */

% deno import-in-comment.ts
Compile file:///Users/jaka/Desktop/import-in-comment.ts
error: Uncaught URIError: relative import path "some/path/in/comment.ts" not prefixed with / or ./ or ../ Imported from "file:///Users/jaka/Desktop/import-in-comment.ts"
► $deno$/errors.ts:35:13
    at constructError ($deno$/errors.ts:35:13)
    at unwrapResponse ($deno$/dispatch_json.ts:41:12)
    at sendSync ($deno$/dispatch_json.ts:70:10)
    at resolveModules ($deno$/compiler_imports.ts:70:10)
    at processImports ($deno$/compiler_imports.ts:172:27)
    at processImports ($deno$/compiler_imports.ts:181:13)
```

Some rogue regexp somewhere?

**Comment by nayeemrmn** [comment] 2020-03-23 09:20
Potential duplicate: https://github.com/denoland/deno/issues/3089. Same TS bug I guess.

**Comment by kitsonk** [comment] 2020-03-23 21:54
Duplicate of #3089 

It isn't the comment persay... it is the backtick.  The TypeScript pre-process parser gets confused.  A work around, remove the backtick.  If you want JSDoc that works until the issue in TypeScript is resolved, don't use backticks for code, use four spaces indented above the previous paragraph:

```ts
function hello(who: string): string {
  return `hello ${who}`;
}
/**
 * Example that works:
 *
 *     import { scanLeft } from 'some/path/in/comment.ts'
 */
```

**Comment by bartlomieju** [comment] 2020-05-15 19:06
Closing in favor of #3089

**Closed by bartlomieju** 2020-05-15 19:06 UTC
Labels: bug
