### ISSUE TITLE
--no-check mangles export names

### ISSUE THREAD

**Issue by AnInternetTroll** [denoland/deno#12799] opened 2021-11-17 22:28 UTC
Running [x/oauth2_server@0.9.0/authorization_server.ts](https://deno.land/x/oauth2_server@0.9.0/authorization_server.ts) with `--no-check` gives the following output 
```ts
error: Uncaught SyntaxError: The requested module './models/scope.ts' does not provide an export named 'Scope1'
export { SCOPE, Scope, SCOPE_TOKEN } from "./models/scope.ts";
                ~~~~~~~~~~~~~~~
    at <anonymous> (https://deno.land/x/oauth2_server@0.9.0/resource_server.ts:240:17)
```
Running without `--no-check` works as intended. 

Additional notes
```console
$ deno --version
deno 1.16.1+cc38580 (canary, x86_64-unknown-linux-gnu)
v8 9.7.106.2
typescript 4.4.2
```

**Comment by dsherret** [comment] 2021-12-08 23:43
Swc is doing:

```ts
import { Scope as Scope1 } from "./models/scope.ts";

// ...then later...

export { SCOPE, Scope1 as Scope, SCOPE_TOKEN } from "./models/scope.ts";
```

in https://raw.githubusercontent.com/udibo/oauth2_server/0.9.0/resource_server.ts

I think this is a bug in the hygiene pass. It should leave those identifiers alone when they are in an `export {} from "..."`

**Comment by dsherret** [comment] 2021-12-09 01:58
Opened [#2996](https://github.com/swc-project/swc/issues/2996). This is actually because swc marks these identifiers in export specifiers in module declarations with a module specifier as being "references" instead of module bindings (not a bug in the hygiene pass). Unfortunately the fix requires a bit of a redesign in swc (I think).

**Comment by KyleJune** [comment] 2021-12-29 13:29
The issue in swc has just been resolved. This issue should be resolved in deno once swc is updated to the release that has the fix.

**Closed** 2022-01-04 22:02 UTC
Labels: bug, fix available, swc
