### ISSUE TITLE
TLS ALPN support

### ISSUE THREAD

**Issue by yearsyan** [denoland/deno#6334] opened 2020-06-17 10:48 UTC
## Feature request 
I thiink it is necessary to support alnp. For example, if a developer want to create a http2 server,  alpn can make handshake quicker.

**Comment by kitsonk** [comment] 2020-06-17 20:48
ALPN would need to be implemented as part of HTTP/2, so effectively duplicate of #3995.

**Comment by lucacasonato** [comment] 2020-06-17 20:50
@kitsonk Not per se - if the HTTP/2 server is Rust based, then an implementation of ALPN for `Deno.connectTls` or `Deno.listenTls` would need to happen separately from HTTP/2 right?

**Comment by kitsonk** [comment] 2020-06-17 21:02
I mean we wouldn't have to implemented ALPN to implement HTTP/2, but it doesn't make sense... the whole thing should be addressed as one (likely along with moving HTTP/1.1 into Rust as well which is something we said we were going to have to do).

**Comment by yearsyan** [comment] 2020-06-18 05:21
@kitsonk I think an implementation of ALPN for `Deno.connectTls` or `Deno.listenTls` is good for developer who want to create a protocol over tls, HTTP/2 is not the only protocol needs ALPN.

**Closed** 2021-04-10 20:04 UTC
Labels: cli, feat, tls
