### ISSUE TITLE
WebSocket browser API

### ISSUE THREAD

**Issue by aricart** [denoland/deno#6967] opened 2020-08-06 01:57 UTC
The websocket functionality from std/ws is awesome. However, when writing code that targets deno and browser, it doesn't fare as well. Wondering if RT should provide a browser compatible version that can be wrapped by std/ws or vice versa. 

This would allow us to have it both ways, and I for one am sold on it.

**Comment by crowlKats** [comment] 2020-08-06 02:00
duplicate of #3539

**Closed** 2020-08-06 07:42 UTC
