### ISSUE TITLE
Deno upgrade command. 

### ISSUE THREAD

**Issue by getshcc** [denoland/deno#19756] opened 2023-07-07 11:27 UTC
C:\Users\iamsh>deno upgrade
Looking up latest version

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.28.1
Args: ["deno", "upgrade"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected character '<' while parsing major version number")', cli\tools\upgrade.rs:306:62
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by dsherret** [comment] 2023-07-07 19:29
Duplicate of #17957. Please manually upgrade the version.

**Closed by dsherret** 2023-07-07 19:29 UTC
Labels: bug, windows, duplicate
