### ISSUE TITLE
Consider adding a shorthand for only/ignore to `Deno.test()`

### ISSUE THREAD

**Issue by GCSBOSS** [denoland/deno#10257] opened 2021-04-19 14:05 UTC
## Scenario

`Deno.test()` has basically two forms currently (`1.9.0`):

1. `Deno.test(<name>, <test function>)` and
2. `Deno.test(<options object>)`

Personally, I tend to write all my tests on the first form for it is generally simpler to read and write. 
This leaves the second form to be used only when strictly necessary (i.e to use some of the available options).

## Issue
While writing my long list of tests I often feel the need to run *only* the test being currently worked on, to have a cleaner output and lower wait time.

In order to quickly mark any tests as `only` or `ignore` I have to refactor the function considerably in order to add an options object, which will just be removed after the test code is finished.

I suggest reading [this discussion](https://github.com/denoland/deno/issues/5197) where the issue has been pointed out before.

## Suggestion
Among the existing suggestions, I'll just add two more.

```js
Deno.test('foobar is bahbaz', function(){
    i.like.to('move it move it');
}, 'only') // I know...
```

Or even accept the options as the last argument too. (easier to add and remove)

```js
Deno.test('foobar is bahbaz', function(){
    i.like.to('move it move it');
}, { only: true });
```

**Comment by nayeemrmn** [comment] 2021-04-19 14:13
Duplicate of #7474. It was discussed again recently and there's an open PR (#10078) but we're still not sure.

**Closed** 2021-04-19 14:17 UTC

**Comment by GCSBOSS** [comment] 2021-04-19 14:32
Sorry for the duplicate.

Gonna leave here this fun stub for people that write tests a lot:

```js
const Reno = {
    test(name, fn){
        Deno.test({ name, fn, only: true })
    }
};
```

Usage should be intuitive.
