### ISSUE TITLE
Feature: Deno compile binary of js backend application?

### ISSUE THREAD

**Issue by filburt-turle** [denoland/deno#6091] opened 2020-06-03 23:23 UTC
Hi, 

I've been watching Deno for a while and I think what you guys have done is amazing. I started learning rust 6 months ago and the fact that you have Rust on the backend of this has me as a fan. I did wonder if there was any thought around potentially being able to compile an executable for javascript applications?

Essentially wrapping your entire JS project into a binary instead of having all your code exposed when you deploy into production. This question is more or less for the backend bits rather than the frontend. I know from a frontend perspective the browser will have to use your plain view javascript files, but I was wondering if you guys have given some thought into potentially having a flag within Deno to create a binary of your javascript service for the backend?

Thanks in advance.

**Comment by crowlKats** [comment] 2020-06-03 23:24
you might want to look at #986

**Comment by nayeemrmn** [comment] 2020-06-03 23:27
Duplicate of #986.

**Closed** 2020-06-03 23:52 UTC
