### ISSUE TITLE
Server hangs on close with unix socket

### ISSUE THREAD

**Issue by teleclimber** [denoland/deno#8272] opened 2020-11-06 22:50 UTC
```
deno 1.5.1
v8 8.7.220.3
typescript 4.0.3
std lib 0.76
```

This code never exits (it gets to "closing server" then hangs):

```
import { Server } from "https://deno.land/std/http/server.ts";
import { exists } from "https://deno.land/std/fs/mod.ts";
import { sleep } from "https://deno.land/x/sleep/mod.ts";

const sock_path = Deno.args[Deno.args.length -1];
if( !sock_path.endsWith('.sock') ) throw new Error("socket path should be specified and end with sock");
console.log( sock_path );

if( await exists(sock_path) ) await Deno.remove(sock_path);

const listener = await Deno.listen({ path: sock_path, transport: "unix" });
const server = new Server(listener);

(async function() {
	for await (const request of server) {
		request.respond({status: 200});
	}
	console.log("request loop finished");
})();

console.log("server started");

await sleep(1);

console.log("closing server");
server.close();
```

However, the nearly identical code using a regular connection exits as expected after server close:
```
import { Server } from "https://deno.land/std/http/server.ts";
import { sleep } from "https://deno.land/x/sleep/mod.ts";

const listener = await Deno.listen({port:3333});
const server = new Server(listener);

(async function() {
	for await (const request of server) {
		request.respond({status: 200});
	}
	console.log("request loop finished");
})();

console.log("server started");

await sleep(1);

console.log("closing server");
server.close();
```

This makes it impossible to cleanly shut down a unix-socket based server (unless I am missing something, of course).

I tried to step through the close function in the debugger but somewhere in `mux` code everything just stops. 

I also ran it with `RUST_BACKTRACE=1` but there are no errors and Deno is not crashing, it just hangs.

I don't know how to pursue this any further. 🤷‍♂️

Thanks,

✌️

**Comment by teleclimber** [comment] 2020-11-09 18:05
Still happening in deno 1.5.2 and std lib 0.77.

**Comment by bartlomieju** [comment] 2020-11-09 18:12
@teleclimber this is most likely related to https://github.com/denoland/deno/issues/7457 and requires refactor to `ResourceTable` that we are working on.

**Comment by Soremwar** [comment] 2020-12-16 18:12
This code now throws instead of hanging when trying to process the next request of the server, so there is still inconsistency between socket and basic server implementation.

**Comment by bartlomieju** [comment] 2021-12-01 14:32
I'm unable to reproduce the problem due to changed dependencies in provided test case (unversioned imports). I'm going to tentatively close this issue, please open a new one if problem perists.

**Closed by bartlomieju** 2021-12-01 14:32 UTC
Labels: bug, cli
