### ISSUE TITLE
LSP: file extension changed from `.ts` to `.js` after renaming

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#21887] opened 2024-01-10 16:35 UTC
Take the following project:

```ts
// a.ts
import "./b.ts";
```

```ts
// b.ts
console.log("foo");
```

```ts
// c.ts
import "./a.ts";
```

1. Open this project and VS Code, select file `a.ts` in the sidebar and Rename (F2 on Linux). Rename the file to `d.ts`.
2. VS Code asks whether I want to let extensions apply fixes. Select yes.
3. See the following output:

```ts
// d.ts
import "./b.js";
```

```ts
// b.ts
console.log("foo");
```

```ts
// c.ts
import "./d.ts";
```

This is _nearly_ correct. `c.ts` was updated correctly, but `a.ts` was not. The specifiers there were changed from `.js` to `.ts` specifiers.

It should have been:

```ts
// d.ts
import "./b.ts";
```

Version: Deno 1.39.2+be888c0

**Comment by nayeemrmn** [comment] 2024-01-15 21:20
I can't reproduce on release or main. If you move a file within the same dir, the imports in that file shouldn't be touched. When I try moving to a different dir, the extension is correctly preserved.

**Comment by king8fisher** [comment] 2024-01-16 12:26
Occasionally renaming of the files does flip .ts to .js in imports for me as well.

**Comment by melbourne2991** [comment] 2024-01-18 12:21
Are you guys still able to reproduce with other extensions disabled?

I am only able to reproduce this when I have the MDX extension enabled in VS Code.

When I perform the rename VSCode notifies there are two plugins trying to make modifications. 
Seems the MDX one stomps over the Deno extension changes for me at least.

![Screenshot 2024-01-18 at 11 08 20 pm](https://github.com/denoland/deno/assets/4619280/e83e0382-bc5d-41b2-bdf9-df409f220595)
![Screenshot 2024-01-18 at 11 08 06 pm](https://github.com/denoland/deno/assets/4619280/579d925a-cdb8-49e3-9576-e1f97ee864b7)

Possibly relevant: https://github.com/mdx-js/mdx-analyzer/blob/16a3240fe083a8a7254201179fc1204a9a260f3d/packages/language-server/index.js#L55

**Comment by lucacasonato** [comment] 2024-01-22 12:56
I also have the MDX extension enabled. Is it doing that?

**Comment by nayeemrmn** [comment] 2024-01-22 13:01
You can try setting `"typescript.updateImportsOnFileMove.enabled": "never"` to disable Deno's renames, and seeing if it still happens. Unless mdx refers to the same setting..

**Comment by nayeemrmn** [comment] 2024-01-29 17:08
@marvinhagemeister @king8fisher Do you also have the MDX extension, or something else that could be causing these renames?

**Comment by king8fisher** [comment] 2024-01-29 17:11
@marvinhagemeister Now as you say that I confirm that I do have that extension enabled. Disabling it to see if that helps to narrow down the issue.

**Comment by nayeemrmn** [comment] 2024-02-01 03:33
This will probably require a setting to disable this on the MDX extension. Closing for now unless there's something we can do to alleviate it from here.

**Closed by nayeemrmn** 2024-02-01 03:33 UTC
Labels: bug, lsp
