### ISSUE TITLE
deno.jsonc isn't used for checking JSX element

### ISSUE THREAD

**Issue by ooker777** [denoland/deno#23223] opened 2024-04-04 07:39 UTC
If you use `deno.jsonc` instead of `deno.json`, you will get this error:
```
JSX element implicitly has type 'any' because no interface 'JSX.IntrinsicElements' exists
```
Related: https://github.com/denoland/deno/issues/9425
Version: Deno 1.42.0

**Comment by bartlomieju** [comment] 2024-04-04 13:28
Where do you get this error? In the editor or on the terminal? Does it still happen if you upgrade to v1.42.1?

**Comment by ooker777** [comment] 2024-04-04 15:36
I use VS Code. Upgrade Deno then restart VS Code and change `deno.json` to `deno.jsonc` I still get this error

**Comment by bartlomieju** [comment] 2024-04-04 15:40
@nayeemrmn please take a look

**Comment by nayeemrmn** [comment] 2024-04-05 15:14
I can't reproduce this. Please show the output log.

**Comment by ooker777** [comment] 2024-04-05 15:31
I test on a test project and indeed it doesn't reproduce. Can you have a look on [my actual project](https://github.com/QuaCau-TheSphere/CW-rut-gon-utm)? Here is the output log on it:
```
Starting Deno language server...
  version: 1.42.1 (release, x86_64-pc-windows-msvc)
  executable: C:\Users\ganuo\AppData\Local\Microsoft\WinGet\Links\deno.EXE
Connected to "Visual Studio Code" 1.87.2
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///D:/QC%20supplements/Code/Apps/T%E1%BA%A1o%20v%C3%A0%20r%C3%BAt%20g%E1%BB%8Dn%20link%20UTM/deno.json"
  Resolved import map from configuration file
Enabling import suggestions for: https://deno.land
Server ready.
Error resolving. Referring specifier "https://esm.sh/marked@5.1.0" was not found.
Error resolving. Referring specifier "https://esm.sh/marked-mangle@v1.1.0" was not found.
Error resolving. Referring specifier "https://esm.sh/marked-gfm-heading-id@3.0.4" was not found.
Refreshing configuration tree...
  Couldn't read Deno configuration file "file:///D:/QC%20supplements/Code/Apps/T%E1%BA%A1o%20v%C3%A0%20r%C3%BAt%20g%E1%BB%8Dn%20link%20UTM/deno.json": Error reading config file 'file:///D:/QC%20supplements/Code/Apps/T%E1%BA%A1o%20v%C3%A0%20r%C3%BAt%20g%E1%BB%8Dn%20link%20UTM/deno.json'.
```

**Comment by nayeemrmn** [comment] 2024-06-11 15:26
@ooker777 Is this still an issue? Please share your `deno.jsonc` file if so.

**Comment by lucacasonato** [comment] 2024-06-17 05:40
Closing this as OP has not responded. Please re-open with the contents of `deno.jsonc` if you still encounter this issue.

**Closed by lucacasonato** 2024-06-17 05:40 UTC
Labels: bug, needs info, lsp
