### ISSUE TITLE
macOS: Deno.connect({ port: 80 }) fails

### ISSUE THREAD

**Issue by HappyStriker** [denoland/deno#5993] opened 2020-05-31 10:07 UTC
Hey there,

first of all Deno is a great piece of software and I am very curious how it develops in the future.

Right now I am testing the method `Deno.connect` and for some time it drove me crazy until I realized, that I might have found a bug in it.

Using the following code works fine for me:
``` javascript
const encode = (() => {
  const encoder = new TextEncoder();
  return (data) => encoder.encode(data);
})();

const conn = await Deno.connect({ port: 2000 });
await conn.write(encode("Hello World"));
```

On the other side of the connection I was simply using `nc -kl 2000` to show the incoming requests, which works fine. But as soon as I **change the port to** `port: 80` it **suddenly stops working** and no requests from Deno receive on `nc -kl 80`.  
All other clients, like a browser, do not have any trouble to properly connect to that port (tested with and without root permissions).

Hopefully you can use the provided information to track down and fix the issue.

About Deno: *Version 1.0.3*  
About the OS: *macOS 10.15.5*

Best regards,  
Happy Striker

**Comment by marcosc90** [comment] 2020-05-31 10:27
It currently works perfectly for me on:

```
deno 1.0.3
Ubuntu 20.04
```

**Comment by actual-size** [comment] 2020-05-31 10:33
Can reproduce on:
```
deno 1.0.3
macOS 10.15.4
```

**Comment by actual-size** [comment] 2020-05-31 10:40
Appears to be a bug in macOS's shipped netcat. I can fix the issue by `brew install netcat` and using `nc -l -p 80`.

**Comment by HappyStriker** [comment] 2020-05-31 10:55
Well, I would not correlate the issue with `nc` as the connection to a Apache httpd server as well as a node.js based server both serving on port 80 did not work either.

**Comment by HappyStriker** [comment] 2020-05-31 10:57
I have also tried to connect to a server on the the internet like `Deno.connect({ hostname: "www.google.com", port: 80 })`
and it did not work either.

**Comment by actual-size** [comment] 2020-05-31 11:04
Would you run `echo "const conn2 = await Deno.connect({ hostname: \"google.com\", port: 80 })" > test_google_connection.ts && deno run --allow-net test_google_connection.ts`?

**Comment by HappyStriker** [comment] 2020-05-31 11:08
This results in an empty line without any issues:
```
HappyStriker on Mac-mini in ~/Desktop via ⬢ v14.3.0 
❯ echo "const conn2 = await Deno.connect({ hostname: \"google.com\", port: 80 })" > test_google_connection.ts && deno run --allow-net test_google_connection.ts
Compile file:///Users/Daniel/Desktop/test_google_connection.ts

HappyStriker on Mac-mini in ~/Desktop via ⬢ v14.3.0 
```

**Comment by actual-size** [comment] 2020-05-31 11:17
Weird that the connection isn't being immediately refused then

**Comment by HappyStriker** [comment] 2020-05-31 11:26
This is the result:

```
HappyStriker on Mac-mini in ~ 
❯ sudo lsof -i:80
COMMAND     PID   USER            FD  TYPE            DEVICE SIZE/OFF NODE NAME
nc        35176   HappyStriker    3u  IPv4 0xf4d5704aaf089ef      0t0  TCP *:http (LISTEN)
nc        35649   HappyStriker    3u  IPv4 0xf4d5704b549a78f      0t0  TCP *:http (LISTEN)
```

**Comment by HappyStriker** [comment] 2020-05-31 11:29
> Weird that the connection isn't being immediately refused then. Can you double check that something's listening on the port when you do `nc -kl 80` by running `sudo lsof -i:80`?

When running the request like in the following code block, then after a while (I guess after timeout occurs), `null` gets returned:

```
const conn = await Deno.connect({ hostname: "www.google.com", port: 80 });
console.log(await connection.read(new Uint8Array(1024)));  // null
```

**Comment by ry** [comment] 2020-06-01 13:51
@HappyStriker I'm 99% sure this is a bug on your end and not in Deno... I'm preemptively closing this issue, but feel free to continue to debug here and reopen if this turns out to actually be a bug on our end.

In your last example, where you connect to google, HTTP servers need to be sent a request before they respond.

**Closed by ry** 2020-06-01 13:51 UTC

**Comment by HappyStriker** [comment] 2020-06-03 17:50
> @HappyStriker I'm 99% sure this is a bug on your end and not in Deno... I'm preemptively closing this issue, but feel free to continue to debug here and reopen if this turns out to actually be a bug on our end.
> 
> In your last example, where you connect to google, HTTP servers need to be sent a request before they respond.

Thank you for that feedback. Finally I have got sorted it out, at least for manually doing a http request:

``` javascript
'use strict';

// requirements
const { connect } = Deno;
const encode = (() => {
  const encoder = new TextEncoder();
  return (data) => encoder.encode(data);
})();
const decode = (() => {
  const decoder = new TextDecoder();
  return (data) => decoder.decode(data);
})();


// create the connection
const connection = await Deno.connect({ port: 80 });

// send the http request
await connection.write(encode("GET / HTTP/1.1\r\nHost: localhost\r\nConnection: close\r\n\r\n"));

// read and prepare the answer
let answer = new Uint8Array(1024);
await connection.read(answer);
answer = decode(answer);

// log the result of the request
console.log(answer);
```

The order of operations in the `connection.read` part where kind of hard to understand, as I am not used to the `Uint8Array` object and I had expected the answer to be returned by the `connection.read` method instead of the value being written into the `Uint8Array`.

One final question: What is the considered best practise for the read size, especially when dealing with a response of unknown size?
