### ISSUE TITLE
Warning about both "importMap" and "imports" setting in config does not say the config file path

### ISSUE THREAD

**Issue by ry** [denoland/deno#24519] opened 2024-07-11 01:03 UTC
Version: Deno 1.45.0

```
# deno eval -p "1+2"
Warning "importMap" setting is ignored when "imports" or "scopes" are specified in the config file.
3
#
```

probably caused by a stray `deno.json` in my home directory (when I delete it the warning goes away). It contains
```
{
  "imports": {
    "@manzt/googler": "jsr:@manzt/googler@^0.1.0"
  },
  "importMap": "./src/oak/vendor/import_map.json"
}
```

**Comment by dsherret** [comment] 2024-07-11 02:27
We should move that warning to deno_config as a diagnostic because it will show the config file the issue is in.

**Comment by dsherret** [comment] 2024-07-12 18:54
Closed by https://github.com/denoland/deno/pull/24553

**Closed by dsherret** 2024-07-12 18:54 UTC
