### ISSUE TITLE
exception inside async functions transforms into a segfault when using certain ffi lib

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#14795] opened 2022-06-04 06:49 UTC
code:
```ts
import { ReedLine } from "https://deno.land/x/reedline_deno@0.5.0/reedline.ts";

const rl = await ReedLine.new();

rl.readLine();
throws();

async function throws() {
  throw "";
}
```
output:
```
fish: Job 1, 'deno $ar…' terminated by signal SIGSEGV (Address boundary error)
```

**Comment by bartlomieju** [comment] 2022-06-06 11:13
Might be related to https://github.com/denoland/deno/issues/12653

**Comment by sigmaSd** [comment] 2022-08-05 16:13
bump (still happens in deno 1.24.0)

**Comment by sigmaSd** [comment] 2022-10-08 07:33
stll happens in 1.26.1

stacktrace using gdb

```sh
Thread 5 (Thread 0x7ffff68716c0 (LWP 75426) "V8 DefaultWorke"):
#0  0x00007ffff7d084b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7d0acd0 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00005555573fd587 in v8::platform::DelayedTaskQueue::GetNext() () at ../../../../v8/src/libplatform/delayed-task-queue.cc:79
#3  0x00005555573fccff in v8::platform::DefaultWorkerThreadsTaskRunner::WorkerThread::Run() () at ../../../../v8/src/libplatform/default-worker-threads-task-runner.cc:72
#4  0x00005555573f5d50 in v8::base::ThreadEntry(void*) () at ../../../../v8/src/base/platform/platform-posix.cc:1112
#5  0x00007ffff7d0b8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff7d8da60 in ?? () from /usr/lib/libc.so.6

Thread 4 (Thread 0x7ffff70726c0 (LWP 75425) "V8 DefaultWorke"):
#0  0x00007ffff7d084b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7d0acd0 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00005555573fd587 in v8::platform::DelayedTaskQueue::GetNext() () at ../../../../v8/src/libplatform/delayed-task-queue.cc:79
#3  0x00005555573fccff in v8::platform::DefaultWorkerThreadsTaskRunner::WorkerThread::Run() () at ../../../../v8/src/libplatform/default-worker-threads-task-runner.cc:72
#4  0x00005555573f5d50 in v8::base::ThreadEntry(void*) () at ../../../../v8/src/base/platform/platform-posix.cc:1112
#5  0x00007ffff7d0b8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff7d8da60 in ?? () from /usr/lib/libc.so.6

Thread 3 (Thread 0x7ffff78736c0 (LWP 75424) "V8 DefaultWorke"):
#0  0x00007ffff7d084b6 in ?? () from /usr/lib/libc.so.6
#1  0x00007ffff7d0acd0 in pthread_cond_wait () from /usr/lib/libc.so.6
#2  0x00005555573fd587 in v8::platform::DelayedTaskQueue::GetNext() () at ../../../../v8/src/libplatform/delayed-task-queue.cc:79
#3  0x00005555573fccff in v8::platform::DefaultWorkerThreadsTaskRunner::WorkerThread::Run() () at ../../../../v8/src/libplatform/default-worker-threads-task-runner.cc:72
#4  0x00005555573f5d50 in v8::base::ThreadEntry(void*) () at ../../../../v8/src/base/platform/platform-posix.cc:1112
#5  0x00007ffff7d0b8fd in ?? () from /usr/lib/libc.so.6
#6  0x00007ffff7d8da60 in ?? () from /usr/lib/libc.so.6

Thread 2 (Thread 0x7ffff7c7f6c0 (LWP 75423) "tokio-runtime-w"):
#0  0x00007ffff5fc517e in ?? ()
#1  0x00007ffff6045830 in ?? ()
#2  0x00007ffff5fb6de1 in ?? ()
#3  0x7ffff00058400000 in ?? ()
#4  0x00007ffff7c7e2b0 in ?? ()
#5  0x7ffff7c7d0b80000 in ?? ()
#6  0x7ffff7c7d1b00000 in ?? ()
#7  0x7ffff7c7d1000000 in ?? ()
#8  0x7ffff5fdd8400000 in ?? ()
#9  0x0000000000000001 in ?? ()
#10 0x0000000000000000 in ?? ()

Thread 1 (Thread 0x7ffff7c80c00 (LWP 75420) "deno"):
#0  0x00007ffff7d857fd in syscall () from /usr/lib/libc.so.6
#1  0x00005555597898b0 in <parking_lot_core::thread_parker::imp::ThreadParker as parking_lot_core::thread_parker::ThreadParkerT>::park ()
#2  0x000055555978a592 in parking_lot::condvar::Condvar::wait_until_internal ()
#3  0x0000555559629b6b in _ZN5tokio4park6thread5Inner4park17h41e1e922f8eecac8E.llvm.18442409270581243320 ()
#4  0x0000555559641c49 in _ZN5tokio7runtime8blocking4pool12BlockingPool8shutdown17h5956e833be408cdcE.llvm.18442409270581243320 ()
#5  0x0000555559642e14 in <tokio::runtime::blocking::pool::BlockingPool as core::ops::drop::Drop>::drop ()
#6  0x00005555584b8b81 in core::ptr::drop_in_place<tokio::runtime::blocking::pool::BlockingPool> ()
#7  0x000055555843f82f in deno_runtime::tokio_util::run_local ()
#8  0x0000555558771f3e in deno::main ()
#9  0x0000555558472fc8 in std::sys_common::backtrace::__rust_begin_short_backtrace ()
#10 0x000055555847a107 in std::rt::lang_start::{{closure}} ()
#11 0x00005555583ccf3e in core::ops::function::impls::{impl#2}::call_once<(), (dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> () at library/core/src/ops/function.rs:280
#12 std::panicking::try::do_call<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> () at library/std/src/panicking.rs:492
#13 std::panicking::try<i32, &(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe)> () at library/std/src/panicking.rs:456
#14 std::panic::catch_unwind<&(dyn core::ops::function::Fn<(), Output=i32> + core::marker::Sync + core::panic::unwind_safe::RefUnwindSafe), i32> () at library/std/src/panic.rs:137
#15 std::rt::lang_start_internal::{closure#2} () at library/std/src/rt.rs:128
#16 std::panicking::try::do_call<std::rt::lang_start_internal::{closure_env#2}, isize> () at library/std/src/panicking.rs:492
#17 std::panicking::try<isize, std::rt::lang_start_internal::{closure_env#2}> () at library/std/src/panicking.rs:456
#18 std::panic::catch_unwind<std::rt::lang_start_internal::{closure_env#2}, isize> () at library/std/src/panic.rs:137
#19 std::rt::lang_start_internal () at library/std/src/rt.rs:128
#20 0x0000555558794a22 in main ()
```

**Comment by lucacasonato** [comment] 2024-09-19 09:49
Tenatively considering this a duplicate of https://github.com/denoland/deno/issues/12653 (panic on exit with FFI).

**Closed by lucacasonato** 2024-09-19 09:49 UTC
