### ISSUE TITLE
Panic when using --disallow-code-generation-from-strings

### ISSUE THREAD

**Issue by jerebtw** [denoland/deno#17351] opened 2023-01-11 15:36 UTC
Deno panics when running ```deno run --v8-flags=--disallow-code-generation-from-strings index.ts```

index.ts:
```ts
console.log("Hello World!");
```

The error:
```
Platform: windows x86_64
Version: 1.29.2
Args: ["deno", "run", "--v8-flags=--disallow-code-generation-from-strings", "TestFlags.ts"]

thread 'main' panicked at 'Failed to execute bootstrap script: EvalError: Code generation from strings disallowed for this context
    at new Function (<anonymous>)
    at genAsyncOp (deno:core/01_core.js:176:14)
    at Object.initializeAsyncOps (deno:core/01_core.js:220:19)
    at Object.bootstrapMainRuntime [as mainRuntime] (deno:runtime/js/99_main.js:398:10)
    at [deno:runtime\worker.rs:327:24]:1:11', runtime\worker.rs:328:8
```

**Comment by dsherret** [comment] 2023-01-11 19:04
Duplicate of #16535 

https://github.com/denoland/deno/issues?q=is%3Aissue+is%3Aopen+disallow-code-generation-from-strings

**Closed by dsherret** 2023-01-11 19:04 UTC
Labels: duplicate
