### ISSUE TITLE
Deno Bug with Quarto publish command

### ISSUE THREAD

**Issue by cparmer** [denoland/deno#24272] opened 2024-06-19 16:49 UTC
Platform: macos aarch64
Version: 1.41.0
Args: ["/Applications/quarto/bin/tools/aarch64/deno", "run", "--unstable-ffi", "--no-config", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--no-check", "--v8-flags=--enable-experimental-regexp-engine,--max-old-space-size=8192,--max-heap-size=8192", "--importmap=/Applications/quarto/bin/vendor/import_map.json", "/Applications/quarto/bin/quarto.js", "publish"]

thread 'main' panicked at cli/args/mod.rs:596:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: deno::args::get_root_cert_store
   4: once_cell::imp::OnceCell<T>::initialize::{{closure}}
   5: once_cell::imp::initialize_or_wait
   6: <deno::args::CliRootCertStoreProvider as deno_tls::RootCertStoreProvider>::get_or_try_init
   7: deno_fetch::Options::root_cert_store
   8: deno_fetch::get_or_create_client_from_state
   9: deno_fetch::op_fetch<FP>::v8_fn_ptr
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.

**Comment by bartlomieju** [comment] 2024-06-19 17:17
Do you get the same problem on Deno v1.44?

**Comment by lucacasonato** [comment] 2024-06-19 21:44
Duplicate of https://github.com/denoland/deno/issues/24137

**Closed** 2024-06-19 21:44 UTC
Labels: needs info
