### ISSUE TITLE
Scripts installed by `deno install` on Windows does not handle Ctrl+C

### ISSUE THREAD

**Issue by felipecrs** [denoland/deno#10136] opened 2021-04-11 14:30 UTC
```sh-session
➜ deno install --allow-net --allow-read https://deno.land/std@0.92.0/http/file_server.ts
Download https://deno.land/std@0.92.0/http/file_server.ts
Download https://deno.land/std@0.92.0/path/mod.ts
Download https://deno.land/std@0.92.0/flags/mod.ts
Download https://deno.land/std@0.92.0/_util/assert.ts
Download https://deno.land/std@0.92.0/http/server.ts
Download https://deno.land/std@0.92.0/async/mod.ts
Download https://deno.land/std@0.92.0/http/_io.ts
Download https://deno.land/std@0.92.0/io/bufio.ts
Download https://deno.land/std@0.92.0/path/posix.ts
Download https://deno.land/std@0.92.0/path/common.ts
Download https://deno.land/std@0.92.0/path/glob.ts
Download https://deno.land/std@0.92.0/path/separator.ts
Download https://deno.land/std@0.92.0/path/win32.ts
Download https://deno.land/std@0.92.0/_util/os.ts
Download https://deno.land/std@0.92.0/path/_interface.ts
Download https://deno.land/std@0.92.0/path/_constants.ts
Download https://deno.land/std@0.92.0/path/_util.ts
Download https://deno.land/std@0.92.0/textproto/mod.ts
Download https://deno.land/std@0.92.0/http/http_status.ts
Download https://deno.land/std@0.92.0/async/deferred.ts
Download https://deno.land/std@0.92.0/async/delay.ts
Download https://deno.land/std@0.92.0/async/pool.ts
Download https://deno.land/std@0.92.0/async/mux_async_iterator.ts
Download https://deno.land/std@0.92.0/io/buffer.ts
Download https://deno.land/std@0.92.0/bytes/mod.ts
Download https://deno.land/std@0.92.0/io/util.ts
Check https://deno.land/std@0.92.0/http/file_server.ts
✅ Successfully installed file_server
C:\Users\felip\.deno\bin\file_server.cmd
C:\Users\felip\.deno\bin\file_server (shell)
ℹ️  Add C:\Users\felip\.deno\bin to PATH
    set PATH=%PATH%;C:\Users\felip\.deno\bin
➜ C:\Users\felip\.deno\bin\file_server.cmd
HTTP server listening on http://0.0.0.0:4507/
^CTerminate batch job (Y/N)?
```

As can be seen, `cmd.exe` handles the `Ctrl`+`C` event instead of the deno process.

**Comment by littledivy** [comment] 2021-04-11 15:40
Duplicate of #9873

**Comment by kitsonk** [comment] 2021-04-11 21:44
Duplicate of #9873

**Closed by kitsonk** 2021-04-11 21:44 UTC
Labels: duplicate

**Comment by rivy** [comment] 2021-05-31 14:28
@kitsonk , wouldn't this be a duplicate of #9995 requesting signal handlers ?

@felipecrs , as for the final "Terminate batch job (Y/N)?", I've prototyped an enhanced shim which suppresses this behavior (as well as supporting better command line expansion/globbing under Windows) in [dxx](https://deno.land/x/dxx@v0.0.4). I'd be curious as to your experience with it. If you want to try it...

```shell
deno install -Af https://deno.land/x/dxx@v0.0.4/src/dxi.ts
dxi --allow-net --allow-read https://deno.land/std@0.92.0/http/file_server.ts
```

<kbd>CTRL-C</kbd> will stop the job will stop without any subsequent prompt.  It does leave a double <kbd>CTRL-C</kbd> on the screen, but, I think that's due to lack of signal handling and should be fixable when #9995 is addressed.
