### ISSUE TITLE
feat: `deno fmt` should inline code when `lineWidth` allows it.

### ISSUE THREAD

**Issue by BlackAsLight** [denoland/deno#24044] opened 2024-05-30 03:40 UTC
`deno fmt` automatically pushes one line of code, like the parameters of a function onto several lines when the line exceeds the `lineWidth` length, but it does not re-inline this code if the total length becomes less than `lineWidth`, say via increasing `lineWidth` or removing/renaming parameters and/or types.

## lineWidth: 128
![Screenshot 2024-05-30 at 13 33 13](https://github.com/denoland/deno/assets/44320105/6fa5fc9c-9658-436e-ab18-476e2cfbcb13)

## lineWidth: 80
![Screenshot 2024-05-30 at 13 33 31](https://github.com/denoland/deno/assets/44320105/6193b30e-208a-4d4f-a858-31d3c219bdd3)

For example, when `lineWidth` is changed from 80 to 128, after being formatted, it does not inline the function parameters even though they can now fit within the `lineWidth`.

**Comment by dsherret** [comment] 2024-05-30 13:56
Duplicate of https://github.com/denoland/deno/issues/23047 and #7868

**Closed by dsherret** 2024-05-30 13:56 UTC
