### ISSUE TITLE
node:timers/promises setInterval not working

### ISSUE THREAD

**Issue by jefbarn** [denoland/deno#26499] opened 2024-10-23 22:44 UTC
Version: Deno 2.0.2

Example straight from the docs (https://docs.deno.com/api/node/timers/promises/~/setInterval)

```typescript
import {
  setInterval,
} from 'node:timers/promises';

const interval = 100;
for await (const startTime of setInterval(interval, Date.now())) {
  const now = Date.now();
  console.log(now);
  if ((now - startTime) > 1000)
    break;
}
console.log(Date.now());
```

```
error: Uncaught (in promise) TypeError: The "callback" argument must be of type function. Received type number (100)
    at __node_internal_ (ext:deno_node/internal/validators.mjs:283:13)
    at setInterval (node:timers:35:3)
    at ext:deno_node/internal/util.mjs:97:15
    at new Promise (<anonymous>)
    at setInterval (ext:deno_node/internal/util.mjs:82:12)

```

**Comment by cu8code** [comment] 2024-10-25 05:23
Hi @bartlomieju @littledivy, this is my first time contributing to Deno. I’ve successfully built the project, And I’m encountering the same error when trying to run the above code with the new build. Could someone point me in the right direction to resolve this issue? I’d really appreciate the help! Thanks in advance!

**Comment by Gaurav23V** [comment] 2024-10-25 07:26
@cu8code   I think deno node compatibility layer might be incorrectly resolving the node:times/promises to the traditional timers module since:
Traditional: setInterval(callback, delay, ...args)
Promises: setInterval([delay[, value[, options]]])

@bartlomieju @littledivy I would also like to look at the issue further and work on a fix if you could assign it to me.

**Comment by marvinhagemeister** [comment] 2024-10-28 11:22
For folks wanting to tackle this: The issue is here where we're trying to promisify the existing `setInterval` implementation, whereas in node the promisified variant is a completely different implementation with different arguments, etc.

https://github.com/denoland/deno/blob/5389972ba5037b1ed48da11506f6798deec2b48e/ext/node/polyfills/timers.ts#L95

**Comment by cu8code** [comment] 2024-10-29 04:08
@marvinhagemeister thanks will look into it

**Closed** 2024-11-16 15:01 UTC
Labels: bug, good first issue, node compat
