### ISSUE TITLE
deno -A npm:create-next-app@latest requires NPM

### ISSUE THREAD

**Issue by ksed** [denoland/deno#26242] opened 2024-10-14 14:40 UTC
Version: Deno 2.0

We supposedly have the ability to create Next.js app with Deno rather than Node.js. Yet, when I run `deno -A npm:create-next-app@latest` without Node/NPM installed Deno crashes during the setup complaining that it can't run NPM.

Thus, IFF Deno is supposed to be able to replace Nodejs outright, then it needs a way to generate such apps without Node.js installed. Just saying...

**Comment by littledivy** [comment] 2024-10-14 15:26
Duplicate of https://github.com/denoland/deno/issues/26232

`create-next-app` spawns `npm` and there seems to be no way to skipping the install step. There is nothing Deno can do about this. I would suggest requesting a `--use-deno` or `--skip-install` flag from the Next.js folks.

**Closed by littledivy** 2024-10-14 15:26 UTC

**Comment by TeamDman** [comment] 2025-04-24 13:43
Looks like there's a `--use-pnpm` flag n stuff, but no deno D:

```
❯ deno run -A npm:create-next-app@latest --help
Usage: create-next-app [directory] [options]

Options:
  -v, --version                            Output the current version of create-next-app.
  --ts, --typescript                       Initialize as a TypeScript project. (default)
  --js, --javascript                       Initialize as a JavaScript project.
  --tailwind                               Initialize with Tailwind CSS config. (default)
  --eslint                                 Initialize with ESLint config.
  --app                                    Initialize as an App Router project.
  --src-dir                                Initialize inside a 'src/' directory.
  --turbopack                              Enable Turbopack by default for development.
  --import-alias <prefix/*>                Specify import alias to use (default "@/*").
  --api                                    Initialize a headless API using the App Router.
  --empty                                  Initialize an empty project.
  --use-npm                                Explicitly tell the CLI to bootstrap the application using npm.
  --use-pnpm                               Explicitly tell the CLI to bootstrap the application using pnpm.
  --use-yarn                               Explicitly tell the CLI to bootstrap the application using Yarn.
  --use-bun                                Explicitly tell the CLI to bootstrap the application using Bun.
  --reset, --reset-preferences             Reset the preferences saved for create-next-app.
  --skip-install                           Explicitly tell the CLI to skip installing packages.
  --yes                                    Use saved preferences or defaults for unprovided options.
  -e, --example <example-name|github-url>

    An example to bootstrap the app with. You can use an example name
    from the official Next.js repo or a public GitHub URL. The URL can use
    any branch and/or subdirectory.

  --example-path <path-to-example>

    In a rare case, your GitHub URL might contain a branch name with
    a slash (e.g. bug/fix-1) and the path to the example (e.g. foo/bar).
    In this case, you must specify the path to the example separately:
    --example-path foo/bar

  --disable-git                            Skip initializing a git repository.
  -h, --help                               Display this help message.

```
