### ISSUE TITLE
"deno install" breaks fresh Next.js project on Deno 2

### ISSUE THREAD

**Issue by Janhouse** [denoland/deno#26166] opened 2024-10-11 20:09 UTC
Deno 2 is not usable with Next.js because next stops building as soon as `deno install` is run for the first time in fresh project even without adding any new npm modules.

Version: Deno 2.0.0
```sh
deno run -A npm:create-next-app@latest .
deno run -A build
# This works and Next.js builds

# Immediately after run

deno install
deno run -A build
# This fails with `..Error: Cannot find module './chunks/379.js'`
# Deleting `node_modules` and `deno.lock` does not help

```

**Comment by Janhouse** [comment] 2024-10-11 20:15
Here is terminal recording of it:

[![asciicast](https://asciinema.org/a/XKhY3bue7t4UFPPy4clY0O2us.svg)](https://asciinema.org/a/XKhY3bue7t4UFPPy4clY0O2us)

**Comment by nathanwhit** [comment] 2024-10-12 00:17
Try deleting the .next folder and then rebuilding (you may want to delete node_modules and re-run deno install to be safe, but I think it shouldn’t be necessary.

---

I believe the issue is that in this case, create-next-app first runs a npm install. When you do the first build, next caches the results, and the cache is dependent on the exact layout of the node_modules folder. Then, when you run `deno install` the node_modules folder is updated, and the new layout breaks the cached build.

We plan on upstreaming a PR to next to use deno install instead of npm when running in deno, which would fix this. Aside from that, I'll see if we could provide a better diagnostic here to prevent this confusing situation

**Comment by ashishk15678** [comment] 2024-10-18 15:24
Hi , Is the issue fixed or it still persists ?

**Comment by lucacasonato** [comment] 2024-10-21 09:08
I am going to close this, because there is not much we can do here. The answer is to delete your `.next` and `node_modules` folder before running `deno install`.

**Closed by lucacasonato** 2024-10-21 09:08 UTC

**Comment by Anshumankhanna** [comment] 2024-11-14 07:18
> We plan on upstreaming a PR to next to use deno install instead of npm when running in deno, which would fix this. Aside from that, I'll see if we could provide a better diagnostic here to prevent this confusing situation

When that happens will it be the case that when we run a next project our typescript files will no longer be compiled to js files as deno can run .ts natively?

**Comment by bartlomieju** [comment] 2024-11-14 13:29
> > We plan on upstreaming a PR to next to use deno install instead of npm when running in deno, which would fix this. Aside from that, I'll see if we could provide a better diagnostic here to prevent this confusing situation
> 
> When that happens will it be the case that when we run a next project our typescript files will no longer be compiled to js files as deno can run .ts natively?

Most likely not, Next is a meta framework that runs all files through a bundler so it will most likely continue to do so and produce JS files that Deno will execute.
