### ISSUE TITLE
fetch doesn't seem to support certificates?

### ISSUE THREAD

**Issue by camow7** [denoland/deno#11576] opened 2021-08-03 23:25 UTC
Deno doesn't seem to have a way to do a POST fetch that includes an openssl cert file and key? This is how it would be done in Python
```
#!/usr/bin/env python
 
import requests
  
payload = 'username=myusername&password=password'
headers = {Content-Type': 'application/x-www-form-urlencoded'}
 
resp = requests.post('https://example.com', data=payload, cert=('client-2048.crt', 'client-2048.key'), headers=headers)
```

I imagined it working something like this:
```
    const response = await fetch(
        url,
        {
            method: "POST",
            headers: { "Content-Type": "application/x-www-form-urlencoded","X-Application": appkey},
            cert:'client-2048.crt', 
            key:'client-2048.key',
            body: form,
        },
    );
    return response.json();
```
However there is no cert or key for `RequestInit()`

```
No overload matches this call.
  Overload 1 of 2, '(input: string | Request | URL, init?: RequestInit | undefined): Promise<Response>', gave the following error.
    Argument of type '{ method: string; headers: { "Content-Type": string; "X-Application": string; }; cert: string; key: string; body: FormData; }' is not assignable to parameter of type 'RequestInit'.
      Object literal may only specify known properties, and 'cert' does not exist in type 'RequestInit'.  Overload 2 of 2, '(input: string | Request | URL, init?: (RequestInit & { client: HttpClient; }) | undefined): Promise<Response>', gave the following error.
    Argument of type '{ method: string; headers: { "Content-Type": string; "X-Application": string; }; cert: string; key: string; body: FormData; }' is not assignable to parameter of type 'RequestInit & { client: HttpClient; }'.
      Object literal may only specify known properties, and 'cert' does not exist in type 'RequestInit & { client: HttpClient; }'.deno-ts(2769)
```

**Comment by kitsonk** [comment] 2021-08-04 00:31
Duplicate of #10516.

**Closed by kitsonk** 2021-08-04 00:31 UTC
Labels: duplicate

**Comment by camow7** [comment] 2021-08-04 01:37
So that link handles .pem (which I can deal with). The issue is the `fetch()` call only allows two arguments? How do I get the client and the `payload` object into the `fetch()` call?

This example shows the client going into the second argument
```
const client = Deno.createHttpClient({ caData: await Deno.readTextFile("./ca.pem") });
const response = await fetch("https://myserver.com", { client });
```

However I can't get my payload into the client?

**Comment by bartlomieju** [comment] 2021-08-04 10:53
You can, `client` is an "extension" provided by Deno to the option bag in fetch.

**Comment by camow7** [comment] 2021-08-09 07:45
Ah right. So it's as simple as tacking it on like so?
```
    const client = Deno.createHttpClient({ caData: await Deno.readTextFile("./ca.pem") });
    const response = await fetch(
        url,
        {
            method: "POST",
            headers: { "Content-Type": "application/x-www-form-urlencoded","X-Application": appkey},
            body: `username=${username}&password=${password}`,
            client,
        },
    );
```

**Comment by lucacasonato** [comment] 2021-08-09 07:51
Yup, exactly.
