### ISSUE TITLE
`Intl.Segmenter` missing in typedefs

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#14183] opened 2022-04-02 08:45 UTC
[`Intl.Segmenter`](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Segmenter) is available at runtime, but usage creates a compiler error in Deno v`1.20.4`:

`example.ts`:
```ts
const segmenter = new Intl.Segmenter("en", { granularity: "grapheme" });

console.log({ denoVersion: Deno.version.deno, segmenter });

```

```
$ deno run example.ts
Check file:///Users/deno/example.ts
error: TS2339 [ERROR]: Property 'Segmenter' does not exist on type 'typeof Intl'.
const segmenter = new Intl.Segmenter("en", { granularity: "grapheme" });
                           ~~~~~~~~~
    at file:///Users/deno/example.ts:1:28
```

```
$ deno run --no-check example.ts
{ denoVersion: "1.20.4", segmenter: Intl.Segmenter {} }
```

**Comment by kitsonk** [comment] 2022-04-02 08:58
Duplicate of #14182

**Closed by kitsonk** 2022-04-02 08:58 UTC
Labels: duplicate
