### ISSUE TITLE
npm-compat deno compile slint fails

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#24873] opened 2024-08-04 20:03 UTC
deno 1.45.5 (release, x86_64-unknown-linux-gnu)

```ts
import * as slint from "npm:slint-ui@1.7.1";

const source = `export component Main {
     in-out property <string> greeting <=> label.text;
     label := Text {
         text: "Hello World";
     }
}`;
const ui = slint.loadSource(source, "main.js");
// deno-lint-ignore no-explicit-any
const main = new (ui as any).Main();
main.greeting = "Hello friends";

main.run();
```

```
deno compile -A a.ts && ./a
```

```
error: Uncaught (in promise) TypeError: /tmp/deno-compile-a/node_modules/localhost/@slint-ui/slint-ui-binary-linux-x64-gnu/1.7.1/index.linux-x64-gnu.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:module:774:20)
    at Module.load (node:module:655:32)
    at Function.Module._load (node:module:523:12)
    at Module.require (node:module:674:19)
    at require (node:module:785:16)
    at Object.<anonymous> (file:///tmp/deno-compile-a/node_modules/localhost/slint-ui/1.7.1/rust-module.cjs:190:31)
    at Object.<anonymous> (file:///tmp/deno-compile-a/node_modules/localhost/slint-ui/1.7.1/rust-module.cjs:343:4)
    at Module._compile (node:module:730:34)
    at Object.Module._extensions..js (node:module:744:10)
    at Module.load (node:module:655:32)
```

I tried copying the library to that path, the error becomes
```
error: Uncaught (in promise) TypeError: /tmp/deno-compile-a/node_modules/localhost/@slint-ui/slint-ui-binary-linux-x64-gnu/1.7.1/index.linux-x64-gnu.node: undefined symbol: napi_create_error
    at Object.Module._extensions..node (node:module:774:20)
    at Module.load (node:module:655:32)
    at Function.Module._load (node:module:523:12)
    at Module.require (node:module:674:19)
    at require (node:module:785:16)
    at Object.<anonymous> (file:///tmp/deno-compile-a/node_modules/localhost/slint-ui/1.7.1/rust-module.cjs:190:31)
    at Object.<anonymous> (file:///tmp/deno-compile-a/node_modules/localhost/slint-ui/1.7.1/rust-module.cjs:343:4)
    at Module._compile (node:module:730:34)
    at Object.Module._extensions..js (node:module:744:10)
    at Module.load (node:module:655:32)
```

**Comment by lucacasonato** [comment] 2024-08-05 07:19
Duplicate of https://github.com/denoland/deno/issues/23266

**Closed by lucacasonato** 2024-08-05 07:19 UTC
