### ISSUE TITLE
Panicked while compiling on macos aarch64, 1.25.0

### ISSUE THREAD

**Issue by danielmahal** [denoland/deno#15712] opened 2022-08-31 20:18 UTC
```typescript
// main.ts

import { parse } from "https://deno.land/std/flags/mod.ts"

console.log(parse(Deno.args))
```

```
Platform: macos aarch64
Version: 1.25.0
Args: ["deno", "compile", "main.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/ib/.cargo/registry/src/github.com-1ecc6299db9ec823/eszip-0.25.0/src/v2.rs:512:60
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: eszip::v2::EszipV2::from_graph::visit_module
   4: eszip::v2::EszipV2::from_graph::visit_module
   5: deno::compile_command::{{closure}}
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: deno::main::{{closure}}
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: deno_runtime::tokio_util::run_local
  10: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by kitsonk** [comment] 2022-08-31 20:50
Duplicate of #15705

**Closed by kitsonk** 2022-08-31 20:50 UTC
Labels: duplicate
