### ISSUE TITLE
chalk imported from npm:prettier is somehow incomplete

### ISSUE THREAD

**Issue by yamavol** [denoland/deno#21269] opened 2023-11-20 12:16 UTC
This deno code threw an error
```node
import prettier from 'npm:prettier@3.1.0';
await prettier.format('</p>', { parser: 'html'});
/* TypeError: Cannot read properties of undefined (reading 'bold') */
```
but I was expecting this error to be thrown. (This is a node.js script)
```node
const prettier = require('prettier')
prettier.format('</p>', { parser: 'html'});
/* SyntaxError: Unexpected closing tag "p". It may happen when the tag has 
    already been closed by another tag. */
```
The error is thrown from prettier lib
```js
function getDefs(chalk2) {
  return {
    keyword: chalk2.cyan,     // these properties are defined...
    capitalized: chalk2.yellow,
    jsxIdentifier: chalk2.yellow,
    punctuator: chalk2.yellow,
    number: chalk2.magenta,
    string: chalk2.green,
    regex: chalk2.magenta,
    comment: chalk2.grey,
    invalid: chalk2.white.bgRed.bold   // but bgRed is undefined
  };
}
```
...which was strange. This indicates npm:chalk imported from npm:prettier is incomplete. 

 This code works fine in Node.js, so I think it is deno related. I know npm support is still on progress, but does this issue reproduce? Is this a known issue?

#13321 states that old version of chalk do not work with deno, but I npm:prettier is depending on chalk@5, so I think it is a different issue. I also found this error will not reproduce if I launch and attach the debugger (using VSCode). I have no clue about this behavior.

my environment:
```
deno --version
deno 1.38.2 (release, x86_64-pc-windows-msvc)
v8 12.0.267.1
typescript 5.2.2
```
tips:
```
import chalk from "npm:chalk@5.3.0";
console.log(chalk.white.bgRed.bold('abc')); // this was ok
```

**Comment by lucacasonato** [comment] 2023-11-20 12:57
Can you post your deno.lock file?

**Comment by yamavol** [comment] 2023-11-20 14:52
deno.lock
```
{
  "version": "3",
  "packages": {
    "specifiers": {
      "npm:chalk@5.3.0": "npm:chalk@5.3.0",
      "npm:prettier@3.1.0": "npm:prettier@3.1.0"
    },
    "npm": {
      "chalk@5.3.0": {
        "integrity": "sha512-dLitG79d+GV1Nb/VYcCDFivJeK1hiukt9QjRNVOsUtTy1rR1YJsmpGGTZ3qJos+uw7WmWF4wUwBd9jxjocFC2w==",
        "dependencies": {}
      },
      "prettier@3.1.0": {
        "integrity": "sha512-TQLvXjq5IAibjh8EpBIkNKxO749UEWABoiIZehEPiY4GNpVdhaFKqSTu+QrlU6D2dPAfubRmtJTi4K4YkQ5eXw==",
        "dependencies": {}
      }
    }
  },
  "remote": {}
}

```

**Comment by dsherret** [comment] 2023-11-20 15:47
This is because chalk2 relies on the `__proto__`. Would be fixed by https://github.com/denoland/deno/pull/16775

**Comment by dsherret** [comment] 2023-11-20 18:04
Closing as working as designed. Deno doesn't allow `__proto__` for security reasons. This will be fixed once Babel 8 is released and prettier upgrades to that. Babel 8 uses a more modern chalk version that doesn't use `__proto__`.

**Closed by dsherret** 2023-11-20 18:04 UTC
Labels: working as designed
