### ISSUE TITLE
Wrong type erasure typescript compiler 

### ISSUE THREAD

**Issue by shoffmeister** [denoland/deno#18646] opened 2023-04-09 10:12 UTC
In the simple sample reproducing code below, deno 1.32.3 complains
```
'result' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.  deno-ts(7022)
const result: any
```
although there is nothing to complain about.

Regardless of any code flow, `result` will always have type `Collection`; it is the presence of the line underneath the FIXME which confuses the Deno compiler.

`tsc` does not complain and correctly resolves type information.

```
export interface Collection {
  nextPageKey: string | null;
}

function get<T>(_url?: string): T {
  return {} as T;
}

function getMetrics() {
  const result = get<Collection>();

  let nextPageKey = result.nextPageKey;

  // FIXME this line triggers a Deno Typescript compiler defect
  nextPageKey = null;

  while (nextPageKey) {
    const result = get<Collection>(nextPageKey);
    nextPageKey = result.nextPageKey;
  }
}
```

//exp: no diagnostics
//act: deno-ts(7022)

**Comment by marvinhagemeister** [comment] 2023-04-09 15:56
Which TypeScript version of `tsc` are you using? Asking because the type of `result` is marked as an error [in the official TS playground](https://www.typescriptlang.org/play?#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgYQgBsjhsYEIk4BvAKDjiVBgAVMBzYAaWAE8AXHADOMKMg5wAPkwCuJANx0AvnTrpZScpWpcYAHgAqAPgAUAfVlQiAfiGjxSDgEohh2gzhRgMK9RrKcJjCcIZKquqa2lRwegCyPuLYwqbOHozYVKJewMLy8AC8sT76hCRkFFRmzkqepPDMIGycPPxwRd55RDAAdI3NXLx8tYwA9KNwAGIAkgAacQCicDAAFgghRMh4YggcXFAhmHAAIsBIEKF8YLnY4mDwmQC2YAikUHAAJsDoFZ797IM2kUkPIiCM4AB3NakOCmf4tIZpeiMDJZeCdfLtYoGMqkaJIMzwwF8GqeRhE1p8LEY7p9FgAylKRiqZRAA)

**Comment by shoffmeister** [comment] 2023-04-09 16:34
```
✦ ❯ npx tsc --version
Version 5.0.4
```
This version was installed into my local `node_modules`; no shenanigans and, really, I cannot explain why I have 5.0.4 and why the TS playground is at 5.0.3, as I am writing this :)

```
✦ ❯ npx tsc ./buggy-deno-typescript-compiler.ts 

✦ ❯ echo $?
0
```

Fedora Linux 37, but I'd hope that this does not matter :)

**Comment by lucacasonato** [comment] 2023-04-14 21:49
What does your tsconfig look like?

**Comment by shoffmeister** [comment] 2023-04-15 01:34
The reproducer is run without a Deno config file.

**Comment by lucacasonato** [comment] 2023-04-15 08:15
I meant the tsconfig file for TSC. If you are not using one, `noImplicitAny` is not enabled in TSC. In Deno, `noImplicitAny` is always enabled.

**Comment by shoffmeister** [comment] 2023-04-15 08:41
I appreciate your response, but I am not reporting an issue in `tsc`. For the sake of simplicity, and going forward, may I ask you to ignore every paragraph that contains the word `tsc`? ;)

To reiterate, for _Deno_ this is what I see happening when I run the reproducer with `deno reproducer.ts`
```
//exp: no diagnostics
//act: deno-ts(7022)
```

Now, there are a number of ways to resolve this:
* resolve this issue here as "works as designed"
* provide instructions to the user to tune Deno to suit - i.e. "you must run Deno with a specific Deno configuration file and settings such-and-such"
* fix the thing

From the perspective of someone who was a compiler QA person in a Former Life, I think I have made clear my opinion ;)

(And, FWIW, I don't use a `tsconfig.json`, either - this is a barebones `npm install tsc && npx tsc reproducer.ts`, where `tsc` was at 5.0.4. And, really, I do not want to talk about `tsc` when I report a `Deno` compiler type inference problem against ... _Deno_. I am happy to discuss type inference and the Typescript language in general, though.)

**Comment by lucacasonato** [comment] 2023-04-15 09:28
Deno uses TSC internally for type checking. If you are reporting an issue and saying "it is broken because the TSC binary does something else here", then you must accept me asking questions about your TSC setup.

The type check is working as intended. If you run tsc with --noImplicitAny or --strict you will see the same behavior as you see in Deno out of the box.

**Comment by lucacasonato** [comment] 2023-04-15 09:31
There may well be a defect, but if there is, it would be in TSC either way. If you can reproduce the same issue in TSC when using some compiler flags, then it is a defect in TSC.

**Comment by shoffmeister** [comment] 2023-04-15 10:18
@lucacasonato I don't think this is going into a constructive direction, to be frank.

Here is my proposal: I'll close this issue with a comment saying: "Sorry for uttering the word `tsc`" - and immediately reopen a new issue which totally avoids the word `tsc`. Perhaps this would get this conversation onto the right track?

As a (naïve) consumer, I do not care whether Deno embeds `tsc` as the type inference engine or something else. I look at Deno, because I use Deno, only *_Deno_*, and no `tsc` anywhere here (well - you get the point by now, I guess).

If it turns out that the version of `tsc` that is embedded inside Deno is faulty, well, cool, but that still makes *_Deno_* faulty as well, and Deno still does not use `tsconfig.json`, at least according to the documentation I see, so any discussion about `tsc` and `tsconfig.json` appears to be a bit ... moot.

From a "oh by the way" point of view, it is apparent that tsc 5.0.4 is not defective (as mentioned earlier).

**Comment by lino-levan** [comment] 2023-04-15 14:19
> As a (naïve) consumer, I do not care whether Deno embeds tsc as the type inference engine or something else.

Totally understand where you're coming from, I'd agree.

> If it turns out that the version of tsc that is embedded inside Deno is faulty, well, cool, but that still makes Deno faulty as well...

Is Deno faulty? Yes. Can the Deno team do anything about it? Besides opening an issue on tsc and waiting for them to fix it, no. There isn't an alternative (yet!) to tsc for type checking so this isn't really an actionable issue. I understand how that may feel frustrating as a consumer of Deno.

**Comment by littledivy** [comment] 2023-04-15 14:52
```
$ tsc --noImplicitAny --strict ./bug.ts
main.ts:18:11 - error TS7022: 'result' implicitly has type 'any' because it does not have a type annotation and is referenced directly or indirectly in its own initializer.

18     const result = get<Collection>(nextPageKey);
             ~~~~~~


Found 1 error in main.ts:18
```

This is working as expected. Deno's runs `tsc` in `strict` mode. 

This is a TypeScript language issue. See https://github.com/microsoft/TypeScript/issues/35546 (I won't pretend to understand the issue but there is previous iteration reference between result and nextPageKey)

**Closed by littledivy** 2023-04-15 14:52 UTC
Labels: tsc

**Comment by shoffmeister** [comment] 2023-04-15 16:14
@littledivy I am 100% certain that you are running an outdated version of `tsc` and that you are very _very_ aggressive in closing this issue on Deno.

Please understand that I am looking at this specific issue from two very much orthogonal points of view:
a) a naïve, simple-minded programmer
b) a solution architect who decides whether working with Deno as a platform will be sustainable

I really don't care a whole lot about a). My reproducer is of little consequence, and there are plenty of ways of work around this.

Alas, Deno (the company and the engineering maturity of said company) is totally _totally_ failing on b).

**Comment by littledivy** [comment] 2023-04-15 16:43
>  I am 100% certain that you are running an outdated version

No. Try it yourself:

![image](https://user-images.githubusercontent.com/34997667/232238491-443d88f7-d04c-43bf-970a-a436d799964f.png)

**Comment by lucacasonato** [comment] 2023-04-15 16:44
@shoffmeister I really dislike your attitude... please be kind to folks when interacting on our repositories.

@littledivy is not using an outdated version of TSC. Version 5.0.4 with `--strict` reproduces the behaviour. You can see this in the official TypeScript playground: https://www.typescriptlang.org/play?ts=5.0.4#code/KYDwDg9gTgLgBASwHY2FAZgQwMbDgYQgBsjhsYEIk4BvAKDjiVBgAVMBzYAaWAE8AXHADOMKMg5wAPkwCuJANx0AvnTrpZScpWpcYAHgAqAPgAUAfVlQiAfiGjxSDgEohh2gzhRgMK9RrKcJjCcIZKquqa2lRwegCyPuLYwqbOHozYVKJewMLy8AC8sT76hCRkFFRmzkqepPDMIGycPPxwRd55RDAAdI3NXLx8tYwA9KNwAGIAkgAacQCicDAAFgghRMh4YggcXFAhmHAAIsBIEKF8YLnY4mDwmQC2YAikUHAAJsDoFZ797IM2kUkPIiCM4AB3NakOCmf4tIZpeiMDJZeCdfLtYoGMqkaJIMzwwF8GqeRhE1p8LEY7p9FgAylKRiqVRAA

This issue is marked as "will not fix" by the TypeScript project: https://github.com/microsoft/TypeScript/issues/35546. As such, this issue is out of scope for us too.
