### ISSUE TITLE
Better implementation for Intl/ICU - JavaScript Fails Story

### ISSUE THREAD

**Issue by mhf-ir** [denoland/deno#6017] opened 2020-06-01 08:29 UTC
I18n is essetial i think so:
ICU/Intl is require but there is a problem in JS word to using i18n:

* There is no valid implementation ISO for Intl. It's wired implementation for JS.
* It's not the entire ICU library it's just simple the implementation that not cover all use cases.
* There is no parser for Convert none Georgian calendar to Standard Unix time or Standard Date Object. and etc. 
* Access standard CLDR data (json output: https://github.com/unicode-cldr/cldr-json). List of valid locales and currency/calendar and etc ...specs... why it's not essential part of JS core ? I donno !!!

https://stackoverflow.com/questions/29961992/javascript-intl-datetimeformatter-as-iso-8601custom-output-pattern
https://medium.com/@semnanweb/javascript-intl-fails-da3cda114370

I suggest to see PHP implementation instead of Using same problem for JS
https://www.php.net/manual/en/book.intl.php
C library:
https://unicode-org.github.io/icu-docs/apidoc/released/icu4c/
CLDR data:
http://cldr.unicode.org/

**Comment by ry** [comment] 2020-06-15 16:38
duplicate of https://github.com/denoland/deno/issues/1968

**Closed by ry** 2020-06-15 16:38 UTC
