### ISSUE TITLE
 "Cannot find name 'Deno'."

### ISSUE THREAD

**Issue by pradipmudi** [denoland/deno#6201] opened 2020-06-09 12:02 UTC
denoland extension is installed in the VSCode IDE, but it still doesn't works.
![deno error](https://user-images.githubusercontent.com/6489613/84145237-24981c00-aa77-11ea-9a5e-7ffbaac4cc4e.png)

**Comment by David-Else** [comment] 2020-06-09 12:05
https://github.com/denoland/vscode_deno/issues/80#issuecomment-640676940

**Comment by nayeemrmn** [comment] 2020-06-09 14:33
Duplicate of https://github.com/denoland/vscode_deno/issues/80, wrong repo.

**Closed** 2020-06-16 14:21 UTC
