### ISSUE TITLE
the request.signal is not aborted when the request is cancelled

### ISSUE THREAD

**Issue by tmkx** [denoland/deno#21653] opened 2023-12-20 08:51 UTC
Version: Deno 1.39.0

user code:
```ts
Deno.serve(async (request) => {
  console.log("signal 1", request.signal.aborted); // expect false
  await new Promise((resolve) => setTimeout(resolve, 3000)); // abort during waiting
  console.log("signal 2", request.signal.aborted); // expect true
  return new Response("Welcome to Deno!");
});
```

send a request, and then abort it while waiting
```bash
curl "http://localhost:8000/"
^C
```

current behavior:
```
signal 1 false
signal 2 false // unexpected :(
```

**Comment by mmastrac** [comment] 2023-12-21 04:07
Dupe of Dupe of https://github.com/denoland/deno/issues/10829

**Comment by mmastrac** [comment] 2024-05-06 17:24
Re-opening as we don't support cancellation in the request phase of an HTTP transaction.

**Comment by ayonli** [comment] 2024-08-13 02:26
@mmastrac Is there any plan for this implementation?

It would be nice if there is a way to determine that the connection is closed, and there isn't a better way to do so than utilizing the Request.signal property. It literally indicates that the request is aborted, and it can be passed around asynchronous operations like the Context object in Golang.

When the request is aborted, we can cancel some pending tasks that are still running, we can even roll back database transactions if we want.

**Closed** 2024-11-07 11:42 UTC
