### ISSUE TITLE
How to get deno autocomplete bash and shell file. autosuggestions tab completion.

### ISSUE THREAD

**Issue by jabed-web-dev** [denoland/deno#21897] opened 2024-01-11 15:20 UTC
![image](https://github.com/denoland/deno/assets/59810760/c9cc7d14-3f19-48ec-bbc1-2295906ec2f3)

**Comment by littledivy** [comment] 2024-06-13 12:06
Duplicate of https://github.com/denoland/deno/issues/22349

**Closed by littledivy** 2024-06-13 12:06 UTC
Labels: question, usability
