### ISSUE TITLE
dw.js, like nw.js

### ISSUE THREAD

**Issue by trusktr** [denoland/deno#4138] opened 2020-02-26 02:55 UTC
Is there anything like this for Deno yet, that gives us a graphical window?

**Comment by nayeemrmn** [comment] 2020-02-26 03:03
Duplicate of #3234.

**Comment by axetroy** [comment] 2020-02-26 03:03
duplicated #3234

**Comment by trusktr** [comment] 2021-09-28 19:03
Actually, this isn't too much of a duplicate, because people in that thread suggest connecting Deno to non-web-based GUI toolsets.

This is specifically about a web-based front end (i.e. connecting Deno to a webview).

At this point, having transitioned to Rust, it seems that [Servo](https://servo.org/) would be a possible option for Deno if it will have tight integration (as in running Deno code directly in a web view, not just puppeteering of an external browser that does not run actual Deno code).

Deno relies on V8 though, so conveivably they could also fork Chrome, and hook the Rust-stuff onto Chrome's V8, so that the JS context is both Deno and Web.

**Comment by crowlKats** [comment] 2021-09-28 19:12
The discussion is for a whole solution of GUI, be it web-based or not, so it does include this. In the discussion both servo and chomium have been mentioned a plethora of times, and reasons why either isnt a possible solution currently have been given. 

> Deno relies on V8 though, so conveivably they could also fork Chrome, and hook the Rust-stuff onto Chrome's V8, so that the JS context is both Deno and Web.

That is more work than what you think it is, and most definitively not a proper and sustainable solution. 

In regards to GUI though, there is movement towards having such a project, as in the [deno discord server](discord.gg/deno) has added a channel for such discussion and work is being put into it.

**Comment by trusktr** [comment] 2021-09-28 19:46
I suppose that is `#deno-desktop`.

It seems that using https://deno.land/x/puppeteer@9.0.1 may be an easy way to do this right now, setting headless mode to false so a window is opened and allows user interaction, and then using message passing between the browser context and the Deno backend.

That would be secure by default: a web site would not be able to modify the file system, even if Deno's file system APIs are enabled, unless the Deno backend allows the client to do so.

With some crafty browser detection, the Deno backend could launch puppeteer connected to whichever browser exists (limited to Chrome, FF, and Edge currently), in some specified fallback order.

Another puppeteering option is Playwright, which supports all browsers, but there is no Deno package for Playwright yet.

**Closed** 2021-09-28 22:34 UTC
