### ISSUE TITLE
@deno-types doesn't follow redirects

### ISSUE THREAD

**Issue by sholladay** [denoland/deno#7380] opened 2020-09-07 14:29 UTC
When the URL given to `@deno-types` returns an HTTP redirect, Deno seems to ignore the response rather than following it. I believe this is a regression, but I haven't bisected which version.

```sh
$ deno --version
deno 1.3.3
v8 8.6.334
typescript 4.0.2
```

**Comment by bartlomieju** [comment] 2020-09-08 11:00
@sholladay I checked and `@deno-types` definitely follows redirects when downloading the file. It'd be useful to have a minimal reproduction that we can test against.

**Comment by lucacasonato** [comment] 2020-09-08 12:45
@bartlomieju This works:

```ts
// @deno-types="https://raw.githubusercontent.com/soremwar/deno_types/master/react/v16.13.1/react.d.ts"
import React from "https://cdn.skypack.dev/react@16.13.1";

const App = () => {
  return (
    <body>Hello, World!</body>
  );
};

console.log(App);
```

While this does not: 

```ts
// @deno-types="https://denopkg.com/soremwar/deno_types/react/v16.13.1/react.d.ts"
import React from "https://cdn.skypack.dev/react@16.13.1";

const App = () => {
  return (
    <body>Hello, World!</body>
  );
};

console.log(App);
```

This is interesting because the denopkg link is just a redirect to raw.githubusercontent.com:
```
/m/f/P/g/d/deno ❯❯❯ curl -i https://denopkg.com/soremwar/deno_types/react/v16.13.1/react.d.ts
HTTP/2 301 
location: https://raw.githubusercontent.com/soremwar/deno_types/master/react/v16.13.1/react.d.ts
cache-control: public, max-age=0, must-revalidate
content-length: 0
date: Tue, 08 Sep 2020 12:44:36 GMT
x-vercel-cache: MISS
age: 0
server: Vercel
x-vercel-id: lhr1::sfo1::zq758-1599569075509-e9e9c566466d
strict-transport-security: max-age=63072000
```

**Comment by sholladay** [comment] 2020-09-08 19:03
I also confirmed that it's not specific to `denopkg.com` because the same problem occurs if you use `https://github.com/<owner>/repo/raw/<path>`.

I wonder if it could have something to do with the redirect location pointing to a different origin?

**Comment by jeanlescure** [comment] 2020-09-20 05:28
Can confirm I'm having the exact same issue, it's becoming quite the homework to get React working again on latest Deno version, sat down with the sole purpose of prototyping an idea on React with Deno and instead have spent the last hour trying to get the hello world to work :confused:

**Comment by sholladay** [comment] 2020-09-21 06:15
For anyone who's trying to get things done, I've published a workaround in the Pogo framework and our React apps are working.

This should work, without needing to import the types yourself...

```tsx
import React from 'https://jspm.dev/react@16.13.1';
import pogo from 'https://deno.land/x/pogo/main.ts';

const server = pogo.server({ port : 3000 });

server.router.get('/', () => {
    return <h1>Hello, React!</h1>;
});

server.start();

console.log('Server started: http://localhost:3000');
```

**Comment by bartlomieju** [comment] 2020-11-02 22:53
@kitsonk could this issue be resolved by latest module graph refactors?

**Comment by kitsonk** [comment] 2020-11-02 23:34
Yes, just checked it and it is now working.

**Closed by kitsonk** 2020-11-02 23:34 UTC
Labels: bug :bug:, cli :computer:
