### ISSUE TITLE
Support XMLHttpRequest.

### ISSUE THREAD

**Issue by fenginsc** [denoland/deno#11967] opened 2021-09-09 17:51 UTC
Hello everyone, we already have fetch available, but it would be better if it also supports XMLHttpRequest, which will increase the usability to be compatible with many AJAX technology JavaScript projects, thank you.

**Comment by crowlKats** [comment] 2021-09-09 17:59
Duplicate of https://github.com/denoland/deno/issues/2191

**Closed** 2021-09-09 19:44 UTC
