### ISSUE TITLE
Cannot use std/fs/mod.ts without --unstable

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#5264] opened 2020-05-13 11:38 UTC
## Problem

I want to some stable functions provided by `std/fs/mod.ts` without enabling unstable features, but it does not compile.

## Proposal

Separate unstable part of standard libraries from stable part. For example: `std/fs/mod.ts` will only include stable functions, `std/fs/unstable/mod.ts` will include all functions.

**Comment by kitsonk** [comment] 2020-05-13 11:51
Duplicate of #5012

Please use the search feature before opening new issues.

**Closed** 2020-05-13 12:05 UTC
