### ISSUE TITLE
Deno 1.8.0 not working on Windows 7

### ISSUE THREAD

**Issue by pedropaulosuzuki** [denoland/deno#9711] opened 2021-03-06 17:10 UTC
As pointed out on a [deno_install/#181](https://github.com/denoland/deno_install/issues/181) thread, there seems to have some issues on running Deno 1.8.0 on Windows 7, which is not a problem on Ubuntu 20.04 LTS, ElementaryOS 5.1 Hera or PopOS 20.10, which run fine. As pointed out earlier, there seems to be an issue with the WebGPU API on Win7, which seems to require some kind of Direct3D DLL on the 1.8.0 version, which was not an issue on 1.7.5. I know Windows 7 is end-of-life, and I don't know if there should be a fix for this issue or not, but as a Deno teacher, some of my students use Windows 7 or even Vista to this day, and knowing if the Deno runtime is supposed to run on their systems end up being an important issue because of that.

Here is what happens when running Deno 1.8.0 on Windows 7:

![image](https://user-images.githubusercontent.com/32345702/110214871-71354a00-7e85-11eb-84f7-bab3a3b3d57f.png)

And here is what happens when running Deno 1.7.5 on Windows 7 (works fine):

![image](https://user-images.githubusercontent.com/32345702/110214889-87dba100-7e85-11eb-98f0-bf6e95988e82.png)

Thanks for reading and sorry for bringing an issue on an end-of-life, closed-source operating system.

**Comment by kitsonk** [comment] 2021-03-06 21:33
Duplicate of #9608

**Closed by kitsonk** 2021-03-06 21:33 UTC
Labels: duplicate

**Comment by pedropaulosuzuki** [comment] 2021-03-06 22:20
> Duplicate of #9608

Actually it is not a duplicate of [denoland/deno#9608], because 1.7.5 works fine here, and 1.8.0 doesn't, while on 9608 he cannot go from 1.7.0 to 1.7.5, and both error codes are different, this one being related to the WebGPU API requirements on 1.8.0, which are not present on 1.7.5.

**Comment by kitsonk** [comment] 2021-03-06 23:11
While it maybe a different error message, the fundamental situation is the same, we don't test on Windows 7 nor target it.  If it works, it is coincidence versus intent.
