### ISSUE TITLE
Deno.bundle() does not handle `export * as` (export-star-as) correctly

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4542] opened 2020-03-31 12:59 UTC
More details in [this repo](https://github.com/KSXGitHub/deno-issue-bundle-export-star-as)

**Comment by kitsonk** [comment] 2020-03-31 19:31
This is a bug.  I think we missed this export pattern when we do the analysis of the exported nodes for the module and don't properly resolve the symbol names.

**Comment by grosto** [comment] 2020-04-08 19:30
I can work on this

**Comment by grosto** [comment] 2020-04-10 08:07
Could it be bug with typescript?
It seems that bundle is not emitting `System.regiter` for '`./a'` and `'./b'`, and this seems to be done on typescript side
https://github.com/KSXGitHub/deno-issue-bundle-export-star-as/blob/master/bundle.js#L89

**Comment by kitsonk** [comment] 2020-04-11 01:11
@grosto actually, I probably need to take a look into it further.  It might or might not be TypeScript.  The problem is the main module is JavaScript, so that works a bit differently, and it feels like we might not be setting up right when the main module is JS and we are bundling, which means the issue has nothing to do with the `export *` and has everything to do with bundling a JavaScript module as the main module.

**Comment by gewoonwoutje** [comment] 2020-05-18 21:35
While waiting for a fix, here is an ugly workaround: use `import * as` from the file also.

For instance:
```ts
// external.ts
// This file contains the imports of external source from URLs.

import * as Oak from "https://deno.land/x/oak/mod.ts";
export * as Oak from "https://deno.land/x/oak/mod.ts";
```
and 
```ts
// src/main.ts
import { Oak } from '../external.ts';
```

**Comment by gewoonwoutje** [comment] 2020-05-19 21:38
Related to #5219

**Comment by kitsonk** [comment] 2020-06-21 04:53
I am unable to reproduce now on Deno 1.1.1.  I cloned the repo and updated to the proper version of `std`.  I suspect there were fixes in TypeScript 3.9 that fixed this issue (as I believe there were some bugs related to `export * as`).

This can be closed now.

**Comment by katywings** [comment] 2020-06-21 08:11
@kitsonk I gonna try it out with my prototype as well then 🙂

**Comment by bartlomieju** [comment] 2020-06-21 11:13
Closing as resolved

**Closed by bartlomieju** 2020-06-21 11:13 UTC
Labels: bug, cli
