### ISSUE TITLE
Cannot run file without extension (.ts or .js)

### ISSUE THREAD

**Issue by davidnguyen179** [denoland/deno#5368] opened 2020-05-14 15:39 UTC
So I have structure of app like this

```bash
index.ts
package.json
```

**package.json**

worked
```json
{
  "scripts": {
    "test": "deno run index.ts"
  }
}
```

not working

```json
{
  "scripts": {
    "test": "deno run index.ts"
  }
}
```
I am not sure that whether or not `deno` will support execute script without extension name in the future.

**Comment by galkowskit** [comment] 2020-05-14 15:53
1. `package.json` is part of Node.js stack, not Deno.
2. Deno doesn't support imports without the extension name.

```
import { x } from "./test.ts"; // works
import { x } from "./test"; // won't
```

**Comment by nayeemrmn** [comment] 2020-05-14 16:03
> I am not sure that whether or not `deno` will support execute script without extension name in the future.

It won't, or it would already. Duplicate of #2506.

**Comment by kt3k** [comment] 2020-05-14 17:18
(off-topic: I think this should be in the list of FAQ)

**Comment by davidnguyen179** [comment] 2020-05-15 01:50
should it be somewhere in documentation? I think many JS developers have the same concern.

**Comment by Soremwar** [comment] 2020-05-15 02:16
@davidnguyen179 Technically is more directed towards Node users, JS users are aware of this

A common asked section would be cool!

**Closed** 2020-05-15 16:25 UTC
