### ISSUE TITLE
[bug] deno run bundle not recongized

### ISSUE THREAD

**Issue by ZenLiuCN** [denoland/deno#5618] opened 2020-05-19 09:33 UTC
1. source is as simple this
```ts
import { serve } from 'https://deno.land/std@0.51.0/http/server.ts'
const s = serve({ port: 8000 })
console.log('servce on http://localhost:8000')
for await (const req of s) {
    req.respond({ body: "hhhhhh" })
}
```
2. after with ` @deno bundle --unstable  .\main.ts main.js`
3. try to run with `@deno run --unstable --allow-net main.js`
4. get this error
```js
error: Uncaught SyntaxError: Unexpected reserved word
        for await (const req of s) {
```

**Comment by crowlKats** [comment] 2020-05-19 09:37
bundling top-level-await is currently not supported. duplicate of #4207

**Comment by ZenLiuCN** [comment] 2020-05-19 09:40
```js
  execute: async function () {
        s = server_ts_2.serve({ port: 8000 });
        console.log("servce on http://localhost:8000");
        for await (let req of s) {
          req.respond({ body: "hhhhhh" });
        }
      },
```
with this hack, it's effective

**Closed** 2020-05-19 09:42 UTC
