### ISSUE TITLE
Deno panics when called from a non-existent directory.

### ISSUE THREAD

**Issue by andre4ik3** [denoland/deno#14870] opened 2022-06-15 11:11 UTC
**Description:**

When Deno is called from a directory that used to exist but doesn't anymore (i.e. deleted externally), it will panic.

**Steps to Reproduce:**

1. `mkdir /tmp/testing && cd /tmp/testing`
2. `deno` or `deno repl` or `deno run https://deno.land/std/examples/welcome.ts`
3. Observe that it works

-_in another terminal_-

`rm -rf /tmp/testing`

-_back to the original terminal_-

4. Re-run the command.
5. Observe panic.

**Backtrace:** [backtrace.txt](https://github.com/denoland/deno/files/8908708/backtrace.txt)

**Comment by cjihrig** [comment] 2022-06-15 18:06
Closing as a duplicate of https://github.com/denoland/deno/issues/14868.

**Closed by cjihrig** 2022-06-15 18:06 UTC
