### ISSUE TITLE
Add file extension suffix for import quick fixes again

### ISSUE THREAD

**Issue by itohatweb** [denoland/deno#10774] opened 2021-05-27 13:41 UTC
**Is your feature request related to a problem? Please describe.**
In version 2.x Quick Fix imports have suffixed the imports with the correct file extension now in 3.x I always have to add `.ts` etc manually which is painful.

**Describe the solution you'd like**
Add the feature back which automatically handled the file extensions.

**Comment by lucacasonato** [comment] 2021-05-28 10:14
Actually closing as duplicate of #10765

**Closed by lucacasonato** 2021-05-28 10:14 UTC
Labels: bug, lsp
