### ISSUE TITLE
Fmt destroys GitHub Blockquote highlights (TIP, WARNING) etc

### ISSUE THREAD

**Issue by Hexagon** [denoland/deno#23189] opened 2024-04-02 20:14 UTC
Version: Deno 1.42.0

Feature: https://github.com/orgs/community/discussions/16925

```
> [!NOTE]  
> Highlights information that users should take into account, even when skimming.
```

> [!NOTE]  
> Highlights information that users should take into account, even when skimming.

... becomes ...

```
> [!NOTE] Highlights information that users should take into account, even when skimming.
```

> [!NOTE] Highlights information that users should take into account, even when skimming.

... after `deno fmt`

Destroying the feature

**Comment by dsherret** [comment] 2024-04-02 20:20
Duplicate of #21905

**Closed by dsherret** 2024-04-02 20:20 UTC
Labels: duplicate
