### ISSUE TITLE
RegEx parse error in REPL -- single quote in character class -- /[']/

### ISSUE THREAD

**Issue by waugh** [denoland/deno#21654] opened 2023-12-20 11:30 UTC
Version: Deno 1.39.0

Paste in:

`/[']/`

When I try this in the Chromium browser's console, it accepts the expression and echos it back, as I expected. But Deno colors the part after the single quote, and does not give the "> " prompt afterward.

**Comment by mmastrac** [comment] 2023-12-21 04:08
Dupe of https://github.com/denoland/deno/issues/20751 I think

**Closed by mmastrac** 2023-12-21 04:08 UTC
Labels: bug, repl

**Comment by waugh** [comment] 2023-12-21 04:18
The cited report only talks about color. However, the present complaint mentions the more important issue, which is that the REPL is waiting for more input, when it should instead process the expression. Moreover, the present example showing failure is much shorter than the cited one. Maybe this report should supersede the other one, as easier to investigate.
