### ISSUE TITLE
Bug: html formatter breaks up `style` attribute

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#26245] opened 2024-10-14 17:51 UTC
## Steps to reproduce

1. Create an `index.html` file with this content:
  ```html
  <ul style="display: grid; grid-template-columns: 50% 50%; justify-items: stretch; padding: 0">
    <li>1</li>
  </ul>
  ```
2. Run `deno fmt`

Output:

```html
<ul
  style="display: grid; grid-template-columns:
  50% 50%; justify-items: stretch; padding: 0"
>
  <li>1</li>
</ul>
```

Version: Deno 2.0.0

**Comment by MohammadSu1** [comment] 2024-10-16 07:18
I will pick this up

**Comment by MohammadSu1** [comment] 2024-10-24 07:48
Hi @marvinhagemeister, the HTML formatter breaks up the style attribute because the number of characters exceeds the default value of 80. I tried to change the default value in the fmt.rs file to a larger value (120), but it didn’t take effect. Instead, I used the --line-width flag to set the value to 120, which worked. My question is: what is the expected output, and is this the right approach? The attached pictures show what I used and the output.
![format_command](https://github.com/user-attachments/assets/208be3c2-1273-4f2f-b0ef-8348433c016c)
![html_file](https://github.com/user-attachments/assets/5dfbd1c5-e112-4388-9184-df5543754ef3)

**Comment by marvinhagemeister** [comment] 2024-10-24 08:18
Good find!  Both `prettier` and `biome` seem to ignore the line number limit in this case. Seems like we should follow suite.

**Comment by MohammadSu1** [comment] 2024-10-24 09:06
So, the approach here would be to either ignore the line number limit or provide a warning or error to the user indicating that it should be written differently. What is your suggestion?

**Comment by bartlomieju** [comment] 2024-10-24 22:27
@MohammadSu1 are you gonna try and fix it upstream in https://github.com/g-plane/markup_fmt?

**Comment by bartlomieju** [comment] 2024-10-26 19:21
Actually, the problem is inside `cli/tools/fmt.rs`. I have a simple fix that would produce output like this:
```
<ul
  style="display: grid; grid-template-columns: 50% 50%; justify-items: stretch; padding: 0"
>
  <li>1</li>
</ul>
```
Which I think is correct here because the `style` output is 90 chars long which puts the whole `<ul ...>` over 80 char limit.

**Comment by MohammadSu1** [comment] 2024-10-26 19:45
@bartlomieju Yes, I’ll try fixing it upstream at https://github.com/g-plane/markup_fmt. I was actually searching for the root of the problem, and it appears to be related to markup_fmt, as it is responsible for the formatting process and all its attributes. But I’d like to ask if I should ignore the line limit in all cases, or handle only this specific case

**Comment by bartlomieju** [comment] 2024-10-26 19:47
@MohammadSu1 I just opened #26570 - turns out the problem was configuration inside Deno itself.

**Comment by MohammadSu1** [comment] 2024-10-27 07:45
@bartlomieju I found the problem in the code at https://github.com/g-plane/markup_fmt. Could I fix it upstream?

**Comment by MohammadSu1** [comment] 2024-10-27 07:51
As you can see in the attached picture, the line_width is configured to unwrap_or(80). This causes a problem whenever the style exceeds 80 characters. Additionally, this helped me understand why modifying the line_width in cli/tools/fmt.rs still depends on 80 instead of the modified value.
![upstream_pic](https://github.com/user-attachments/assets/aded25a5-4ed4-4f6f-9c26-bbbd318a386d)

**Comment by MohammadSu1** [comment] 2024-10-27 09:05
I have opened an issue at https://github.com/g-plane/markup_fmt and submitted a pull request to fix it. Without this fix, Deno continues to take the line_width as 80 and ignores the new value.

**Comment by bartlomieju** [comment] 2024-10-27 17:29
@MohammadSu1 thanks, let me know once it gets merged. I think I will merge my fix in the meantime as it already produces better results.

**Closed** 2024-10-31 13:50 UTC
Labels: bug, deno fmt
