### ISSUE TITLE
Deno test --watch flag only works when specifying a path

### ISSUE THREAD

**Issue by KyleJune** [denoland/deno#17310] opened 2023-01-08 22:55 UTC
Specifying a file isn't required to run deno test.  It will run all the tests in the directory I'm running the command in.

```
$ deno test -A
Check file:///home/kyle/Projects/deno/react_app/env_test.ts
running 10 tests from ./env_test.ts
...
```

I found that if I add the `--watch` flag, it wasn't finding any of the files.

```
$ deno test --watch -A
Watcher Test started.

ok | 0 passed | 0 failed (0ms)

Watcher Test finished. Restarting on file change...
```

I found that if I add a path like `.`, it is able to find the test files like it can without the `--watch` flag.

```
$ deno test --watch -A .
Watcher Test started.
running 10 tests from ./env_test.ts
...
```

I believe that the test command should be able to find the test files without a path when using the `--watch` flag, like it can without the `--watch` flag.

**Comment by bartlomieju** [comment] 2023-01-09 12:06
I believe this problem was fixed in https://github.com/denoland/deno/pull/17008. @dsherret could you confirm?

**Comment by dsherret** [comment] 2023-01-09 14:59
Duplicate of #16609, which will be fixed in the next release.

**Closed by dsherret** 2023-01-09 14:59 UTC
Labels: duplicate
