### ISSUE TITLE
Request: Separate console functions from Standard Output

### ISSUE THREAD

**Issue by KSXGitHub** [denoland/deno#4256] opened 2020-03-05 07:31 UTC
## Rationale

In the web browser, [console](https://developer.mozilla.org/en-US/docs/Web/API/Console) was always meant to be a developer's debugging tool, not a way to show output to the end user. [(more on this)](https://github.com/denoland/deno/issues/4256#issuecomment-596092949)

## Benefits

* Allow developer to separate debugging logs from stdout.
* Allow console functions to emit additional useful debug information, such as stack trace, time, etc.

## Implementation

* Deno user can specify logging target:
  * `--log-target-file` redirects logs to a file.
  * ~~`--log-to-stdio` redirects logs to stdout/stderr.~~
  * `--silent-console`: does not print logs to stdout/stderr.
* Default behavior: ~~Without the flags, logs should be redirect to a default file. (I have considered stdout/stderr as default behavior, but it is noisy, and does not discourage Deno user from misusing console.log as output printer)~~ Without flags, logs should still be printed to stdout/stderr, but with additional information such filename and line of code, so that we may discourage developer to use `console` methods as output printer.
* Console functions should filter out all ANSI escape characters.
* Provide Deno's own output functions (preferably via https://deno.land/std). This function is equivalent to `printf` in C, `std::cout` in C++, `println!` in Rust, and `document.write` in the browser.

**Comment by hazae41** [comment] 2020-03-07 13:20
### console.log === printf

In a GUI app, you can see debugs in the terminal.
In a CLI app, stdout/stderr are used to display all information.

Browsers are like GUI apps, the main infos are on the web page, but if you want additional debug, you open the logs.

Thus, console.log is the equivalent of printf for JS.

As Deno should not make assumptions on the way it's used (as a GUI app or as a CLI app), so console.log should write to stdout by default. 

### Redirect stdout/stderr

But it's a good idea to provide a method for redirecting console output.
Also, Unix fans should be able to pipe stdout/stderr to the file they want.
By the way, you said console.log should show a stack trace and debug infos, but that's why console.error and console.debug exists.

I'm not a fan of flags, maybe a function for setting console output? Like dup2 in C?
    
    Deno.stdout.pipe(myfile);
    Deno.stderr.pipe(myfile);

**Comment by KSXGitHub** [comment] 2020-03-07 14:16
@hazae41 `console.log` and `printf` are not equivalent concept.

For browsers, main information is not DevTools console, but the webpage. Its equivalent to `printf` is `document.write`, not `console.log`.

For GUI apps, main information is not in stdout/stderr, but in the GUI itself, `console.log` in such environment does not change GUI output.

> But it's a good idea to provide a method for redirecting console output.

Indeed. For CLI commands, stdio can be used as pipeline, program in receiving end of the pipeline would expect a parseable input. Using `console.log` for such purpose would mess with output syntax correctness.

You suggested using `console.error` and `console.debug`, but you forget that `console.log` belongs to the same namespace (`console`), this namespace is meant for debugging, not for outputing.

Regarding stack-trace, `console.log` in Chrome will display 
[file and line](https://user-images.githubusercontent.com/11488886/76144887-0ce77b00-60b7-11ea-8363-1efab19b9bdf.png) from whence it originated.

In [Jest](https://jestjs.io/), if `console.log` was called during test, rather than write data to `process.stdout` as-is, it will be treated as debug log and format the message before print it to the terminal.

You may say that C users like to use `printf` for debugging, but it is only because C doesn't have equivalent of `console.log` (unlike C# which has `System.Diagnostics.Debug.WriteLine`), this is not unlike PHP college students using `echo`, or early web developers using `document.write` for debugging: Because they don't have access to debug logger.

Do I need more proof?

You now may say that Node.js users expect Deno to log `console.log` to stdout, not doing so may frustrate user unnecessarily. Then you are right, perhaps we should prints `console.*` to stdout/stderr, but formatted and with stack-trace and time to distinguish them from `Deno.{stdout,stderr}`.

**Comment by hazae41** [comment] 2020-03-07 14:30
> For browsers, main information is not DevTools console, but the webpage. Its equivalent to printf is document.write, not console.log.

> For GUI apps, main information is not in stdout/stderr, but in the GUI itself, console.log in such environment does not change GUI output.

That's exactly what I said

**Comment by KSXGitHub** [comment] 2020-03-07 14:33
> > For browsers, main information is not DevTools console, but the webpage. Its equivalent to printf is document.write, not console.log.
> 
> > For GUI apps, main information is not in stdout/stderr, but in the GUI itself, console.log in such environment does not change GUI output.
> 
> That's exactly what I said

Nope. Your conclusion is "Thus, console.log is the equivalent of printf for JS". My conclusion is that `console.log` is NOT `printf`.

**Comment by hazae41** [comment] 2020-03-07 16:11
It is, because console.log behaviour in browser is the same as printf behaviour in GUI apps.

**Comment by nayeemrmn** [comment] 2020-03-07 19:45
> In the web browser, [console](https://developer.mozilla.org/en-US/docs/Web/API/Console) was always meant to be a developer's debugging tool, not a way to show output to the end user.

We _are_ using it as a developer's debugging tool. The person using Deno and seeing its output is not the end user but a developer. The end user is the person, say, consuming a web service running on Deno. Your comparison between denoland and the web is very flawed. Like @hazae41 has been trying to say:

| | Web | Deno
-|-|-
**Debug output** | `console.log` | `console.log`
**End user output** | DOM | Developers's choice. Probably some GUI application that the user has in front of them, which we talk to over net (e.g. their web browser).

What you've done is shift the right column down one because everything must have an obvious end user output channel. But Deno is a developer tool unlike browsers, it's natural that it doesn't.

That was the philosophy. Let me also say that we're going to use it like Node is and not add non-portable APIs for something as basic as writing to stdout, just because of the way `console.log` is named. There is zero chance of this happening. You can close this.

**Comment by hazae41** [comment] 2020-03-07 19:59
We should make another issue for redirecting stdout/stderr

**Comment by KSXGitHub** [comment] 2020-03-08 00:28
@nayeemrmn 

> > In the web browser, [console](https://developer.mozilla.org/en-US/docs/Web/API/Console) was always meant to be a developer's debugging tool, not a way to show output to the end user.
> 
> We _are_ using it as a developer's debugging tool. The person using Deno and seeing its output is not the end user but a developer. The end user is the person, say, consuming a web service running on Deno

What about the person using Deno CLI/TUI apps? Web/GUI apps can have logging, but not CLI/TUI?

> Developers's choice. Probably some GUI application that the user has in front of them, which we talk to over net (e.g. their web browser).

So you consider stdout not being valid choice of output? Your double standard is against countless CLI/TUI apps out there.

> But Deno is a developer tool unlike browsers, it's natural that it doesn't.

1. One of [Deno's goal](https://deno.land/std/manual.md#goals) is to be as "Browser compatible" as possible.

2. The more similarity between production and development environment, the easier it is for developer to work, wouldn't you agree? As such, it is in our best interest to minimize the differences between production and development environment.

> That was the philosophy

No. That was merely bad habit carried over from Node.js.

> Let me also say that we're going to use it like Node is and not add non-portable APIs for something as basic as writing to stdout, just because of the way `console.log` is named.

1. IIRC, Node.js compatibility was explicitly a Non-Goal in Deno's roadmap.

2. To use Node.js apps in Deno, one must have a compatibility layer (i.e. polyfilling `require` function, `global`, native modules). And polyfilling `console.log` is the easiest amongst all Node.js's native module.

3. We get a redo from Node.js. We got to do it right.

> There is zero chance of this happening. You can close this.

Who are you to be so certain? Unless Ryan is against this, this issue will be left open. Your words of discouragement had left my feeling scarred, and deformed. But I assure you, my resolve has never been stronger.

**Comment by KSXGitHub** [comment] 2020-03-08 00:29
> We should make another issue for redirecting stdout/stderr

It is not necessary for now.

**Comment by nayeemrmn** [comment] 2020-03-08 01:47
> IIRC, Node.js compatibility was explicitly a Non-Goal in Deno's roadmap.

In general, but we're talking about an API for writing to stdout which also exists on the web (even if its purpose there isn't the same in your opinion). There isn't a good enough reason to stray in this case. The use of `console.log` won't break any web code.

> What about the person using Deno CLI/TUI apps? Web/GUI apps can have logging, but not CLI/TUI?

They can, they just can no longer use `console.log` for it because the console is their primary interface -- at least if they want to keep the two separate which they don't have to. There isn't a problem with this.

> > But Deno is a developer tool unlike browsers, it's natural that it doesn't.
> 
> 1. One of [Deno's goal](https://deno.land/std/manual.md#goals) is to be as "Browser compatible" as possible.
> 2. The more similarity between production and development environment, the easier it is for developer to work, wouldn't you agree? As such, it is in our best interest to minimize the differences between production and development environment.

Compatibility, as in use APIs that exist on the web where possible like the `fetch` API. Having a concept that mirrors the DOM has nothing to do with that. Are you saying the production environment for deno runtime code is browsers?

> Who are you to be so certain? Unless Ryan is against this, this issue will be left open. Your words of discouragement had left my feeling scarred, and deformed.

It's true I don't know what anyone else is thinking, I guess it was more of a confident prediction. Sorry I worded it in a way that made you take it personally.

If we compared the DOM to stdout/stderr and the web console to a log file, that means fail silently on uncaught errors and write them to the log file. By that system, why does every scripting runtime write uncaught errors to stderr?

**Comment by KSXGitHub** [comment] 2020-03-08 02:10
> > IIRC, Node.js compatibility was explicitly a Non-Goal in Deno's roadmap.
> 
> In general, but we're talking about an API for writing to stdout which also exists on the web

The web doesn't have stdout. DevTools console is not stdout (server might have, but its stdout is invisible to the end user, so it's not either). Thus, `console.log` is not stdout.

> If we compared the DOM to stdout/stderr and the web console to a log file, that means fail silently on uncaught errors and write them to the log file.

Your reason is sound. Perhaps instead of ignoring `console.log` by default, we can still print `console.log` to stdout but with additional information such as line of code from whence it came. For example, `console.log('foo')` in line 5 of `foo.ts` should look like this:

```
ℹ foo                      foo.ts:5
```

There would be no problem whatsoever if we apply the same convention for uncaught errors too.

> By that system, why does every scripting runtime write uncaught errors to stderr?

Because stderr is meant to log errors in UNIX. But I guess this is a rhetorical question.

**Comment by nayeemrmn** [comment] 2020-03-08 02:31
Yes, the point is that in browsers uncaught errors and `console.log` output are written to the same place.

> The web doesn't have stdout. DevTools console is not stdout (server might have, but its stdout is invisible to the end user, so it's not either). Thus, `console.log` is not stdout.

It doesn't, but for _practical_ reasons (like no silent failure) the console output is a better equivalent than the DOM.

> Perhaps instead of ignoring `console.log` by default, we can still print `console.log` to stdout but with additional information such as line of code from whence it came

That's a huge step back and a lot more reasonable. But we still lose the simple and predictable println behaviour and have to re-add it as a non-portable API, for what practical benefit?

**Comment by kitsonk** [comment] 2020-03-22 06:21
Clearly people expect a command line JavaScript runtime to log `console.log()` to stdout.  Not doing that would break everyone's expectations.

As @nayeemrmn says `console.trace()` can provide the desired behaviour.

**Comment by echd** [comment] 2020-03-31 09:02
Coming from a background of writing command-line programs in a variety of languages other than JavaScript/TypeScript, it was non-obvious to me that I had to use `console.log()` to write to stdout. I was looking for a function named something like print, printf, or println. Awk, bash, C, Go, Java, Perl, Python, Ruby and Rust all have functions like that. Tcl uses puts.

I think it'd help people like me who write command-line utility scripts in other languages to onboard easier if there were an obvious write-to-stdout function that follows prior art.

**Comment by kitsonk** [comment] 2020-03-31 09:08
@echd that would be a seperate issue from this.  There might be benefit in easier to use APIs for `Deno.stdout` and `Deno.stderr` as these are file interfaces and a bit cryptic to use.  Likely they would be better suited to be part of the `std` library.

**Comment by metaquanta** [comment] 2020-07-28 20:49
> Clearly people expect a command line JavaScript runtime to log `console.log()` to stdout. Not doing that would break everyone's expectations.

How/why is that clear? I expected `console.log` to write to stderr like every other command line tool on my computer. 

One expects to see logs in their terminal. One still expect to see logs in their terminal when redirecting stdout. 

Important expectations are broken if `my_tool.ts > some_file.some_format` results in an apparently corrupted file and apparently silently.

Clearly `console.log` should write to stderr

**Comment by nayeemrmn** [comment] 2020-07-28 20:56
> How/why is that clear? I expected `console.log` to write to stderr like every other command line tool on my computer.

We're talking about the expectations of the pre-existing server-side JS community, otherwise I would agree that a `log` function should probably write to stderr. But that would also be useless because there are other `console` functions which print to stderr.

The minor naming issue of `console.log()` is not a sufficient justification to change behaviour at this point.

**Comment by metaquanta** [comment] 2020-08-01 23:37
@nayeemrmn, that was a quick response. I deleted that comment upon realizing my expectations were based on my own lazy use of `console.log` where `debug` or `error` were more appropriate.

**Comment by Yamboy1** [comment] 2020-08-01 23:49
Personally, I use console.log while debugging, but for everything else i have a very simple print function, which takes an optional Deno.Writer as an argument. Splitting the two uses makes it easy to just find and remove all debugging logs imo.

**Comment by carragom** [comment] 2020-09-21 04:31
> We're talking about the expectations of the pre-existing server-side JS community, otherwise I would agree that a `log` function should probably write to stderr. But that would also be useless because there are other `console` functions which print to stderr.

Hi @nayeemrmn could you point me to what `console` function writes to `stderr`?. I'm building a CLI tool with Deno and really need something like `console.log()` that prints to `stderr` instead of `stdout`. That's how I found this issue.

As for the general discussion. My 5 cents. All good cli applications I know do the following:
1. Are able to read data to be processed from `stdin`.
2. Are able to write processed data to `stdout`.
3. Write debugging, diagnostics, errors, etc. to `stderr` by default so it does not get mixed with the processing data.

Here is an example:
`pv bigfile.txt.gz | zcat | grep -v '^#' | gzip -c > bigfilewithoutcomments.txt.gz`

Errors and diagnostics messages show in the console along with a progress bar all written to `stderr`. While the processed data never shows up as it travels through the `stdin`/`stdout` pipe.

If `console.log()`'s (and friends) purpose really is to write debugging, diagnostics, errors, etc. Then IMHO it should go to `stderr` by default.

**Comment by kitsonk** [comment] 2020-09-21 04:43
@carragom `console.error()`?

**Comment by kitsonk** [comment] 2020-09-21 04:44
> If `console.log()`'s (and friends) purpose really is to write debugging, diagnostics, errors, etc.

Also, in Deno that is not the _main_ purpose of `console.log()`.  It is the main way of providing a user interface.

**Comment by carragom** [comment] 2020-09-21 04:48
@kitsonk thanks for the quick reply. According to the [docs](https://doc.deno.land/builtin/stable#Console) it writes to `stdout`. But doing a quick check it does appears to write to `stderr`. So I guess this is a bug in the docs and all is good.

**Comment by kitsonk** [comment] 2020-11-05 06:51
There has been sufficient discussion on this.

At the moment, the convention of `console.log`, `console.debug` and `console.info` going to stdout meets the widest range of user expectations for server side JavaScript.  Breaking that expectation would disappoint more people than it would please.  Adding additional flag to redirect this is also not something we would consider at this point in time.

There are sufficient APIs to be able to allow authors to be able to direct output to stdout or stderr as they see fit.

**Closed by kitsonk** 2020-11-05 06:51 UTC
Labels: cli :computer:, suggestion :bulb:

**Comment by sswam** [comment] 2021-03-14 02:55
`console.log` should go to `stderr`

As it is, console.log is unsuitable for debug / logging a software tool that writes to stdout.

The convention of reading input from stdin, writing output to stdout, and writing errors and loggin to stderr has been normal since the early 1970s:

> Unix originally did not have pipes. They were conceived by Doug McIlroy, then head of the Bell Labs Computing Sciences Research Center, and in 1973 were added to the OS by Ken Thompson. Starting with Version 3 Unix, the shell and the various utilities supported pipes in the way they are used in this contest.

This issue might not seem like much, but it is a deal-breaker for me.

**Comment by KSXGitHub** [comment] 2021-03-14 03:08
I find console in Node.js doesn't match the behaviour of Chrome DevTools.

In Chrome DevTools, there are 4 "levels" of logs:
* **Verbose:** For `console.debug`. Turned off by default.
* **Info:** For `console.log` and `console.info`. Turned on by default.
* **Warnings:** For `console.warn`. Turned on by default.
* **Errors:** For `console.error`. Turned on by default.

So providing flags that redirect or hide these logs would make Deno more browser-like.

**Comment by kitsonk** [comment] 2021-03-14 22:23
Browsers don't have a `stdin` or `stdout`, they have a debug console.  I am not sure your comparison is valid of the behaviour of Node.js versus a browsers debug console.

The reason the issue is closed still stands.

**Comment by amithm7** [comment] 2021-11-03 01:23
@kitsonk Can this issue be reopened? It has been an year.

I see that deno cli has a `--log-level` option, which works for logging deno runtime.

But how to get the same `log-level=debug` for the app itself? Currently the `console.log()` and `console.debug()` are treated the same way. I was wondering if `console.debug()` statements could be executed only on setting the log-level to `debug` somehow.
