### ISSUE TITLE
CreateRequire broke at v2.1.0

### ISSUE THREAD

**Issue by unimonkiez** [denoland/deno#27092] opened 2024-11-26 15:52 UTC
I'm using createRequire specifically with Prisma since they use commonJS.
My project works fine with deno `2.0.6` but broke when transitioning to `2.1.0` and `2.1.1`.
Here is my `prisma.ts` file
```ts
import { createRequire } from "node:module";

const require = createRequire(import.meta.url);

export const prisma = require(
    "./prisma-generated/index.js",
) as typeof import("./prisma-generated/index.d.ts");

export type * from "./prisma-generated/index.d.ts";
```

When I run this code with `2.0.6` it works fine, but here is the error I get with new Deno versions:
```bash
> deno run --watch --allow-import --allow-read --allow-env --allow-net --allow-ffi src/start.ts


Watcher Process started.
error: Uncaught (in promise) ReferenceError: exports is not defined
Object.defineProperty(exports, "__esModule", { value: true });
                      ^
    at file:///Users/yuvalsaraf/dev/manager/app/graphql-device/src/prisma-generated/index.js:2:23
    at loadESMFromCJS (node:module:777:21)
    at Module._compile (node:module:722:12)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:812:16)
    at file:///Users/yuvalsaraf/dev/manager/app/graphql-device/src/prisma.ts:5:23

    info: Deno supports CommonJS modules in .cjs files, or when the closest
          package.json has a "type": "commonjs" option.
    hint: Rewrite this module to ESM,
          or change the file extension to .cjs,
          or add package.json next to the file with "type": "commonjs" option.
    docs: https://docs.deno.com/go/commonjs
Watcher Process failed. Restarting on file change...
```

Version: Deno 2.1.1

**Comment by dsherret** [comment] 2024-11-26 16:28
Duplicate of https://github.com/denoland/deno/issues/27079

**Closed by dsherret** 2024-11-26 16:28 UTC
