### ISSUE TITLE
Import maps do not work within workers

### ISSUE THREAD

**Issue by EliteScientist** [denoland/deno#7890] opened 2020-10-08 23:34 UTC
Attempting to load any ts file into a worker where an import map is used fails within the worker. It results in a relative import path error.

We extensively use import maps in our project to keep it clean and prevent having a lot of relative paths "../../../" in our imports.

**Comment by kitsonk** [comment] 2020-10-09 04:43
Duplicate of #6675

Please ensure you search issue before opening new ones.

**Closed by kitsonk** 2020-10-09 04:43 UTC
Labels: duplicate
