### ISSUE TITLE
node compact layer should setup earlier

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#20038] opened 2023-08-03 17:29 UTC
https://github.com/lukeed/kleur/blob/v3.0.0/index.js#L1

Use `npm:kleur@3.0.0` as reproduce example, because 

- it is a small library 

- it need node compact layer for `process.env`.

foo.test.ts

```ts
import kleur from 'npm:kleur@3.0.0'

Deno.test('x', () => {
  console.log({ kleur })
  kleur.red('x')
})
```

test.ts

```ts
const tests = () => ['./foo.test.ts']

await Promise.all(tests().map(async (x) => await import(x)))
```

version 1.35.3

```sh
$ deno test -A --no-check ./test.ts
Uncaught error from ./test.ts FAILED

 ERRORS 

./test.ts (uncaught error)
error: (in promise) TypeError: Cannot read properties of undefined (reading 'env')
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/kleur/3.0.0/index.js:1:136)
    at Object.<anonymous> (file:///home/vscode/.cache/deno/npm/registry.npmjs.org/kleur/3.0.0/index.js:109:4)
    at Module._compile (node:module:721:36)
    at Object.Module._extensions..js (node:module:735:12)
    at Module.load (node:module:653:34)
    at Function.Module._load (node:module:536:16)
    at Module.require (node:module:672:23)
    at require (node:module:779:20)
    at file:///home/vscode/.cache/deno/npm/registry.npmjs.org/kleur/3.0.0/index.js:3:13
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./test.ts (uncaught error)

FAILED | 0 passed | 1 failed (2s)

error: Test failed
```

**Comment by bartlomieju** [comment] 2023-08-03 17:46
Duplicate of https://github.com/denoland/deno/issues/20028

**Closed by bartlomieju** 2023-08-03 17:46 UTC
