### ISSUE TITLE
Getting compilation issues when importing fromFileUrl  from "https://deno.land/std@0.51.0/path/posix.ts"

### ISSUE THREAD

**Issue by mwoodpatrick** [denoland/deno#6886] opened 2020-07-26 17:37 UTC
I'm getting a compilation error when importing fromFileUrl  from "https://deno.land/std@0.51.0/path/posix.ts"

My trivial test case is:

import { fromFileUrl } from "https://deno.land/std@0.51.0/path/posix.ts";
import { CHAR_FORM_FEED } from "./deno_cache/deps/https/deno.land/deca9362afe2080ad38d09cee2792ec9c8b8acc7ed9b0ceeee1049a441ad0dd4"

let u: URL = new URL("");

console.log(fromFileUrl(u));

posix.ts does not build and gets error

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18

what am I doing wrong. Is there a Deno discussion group I could use to discuss such problems before filing an issue like this?

**Comment by crowlKats** [comment] 2020-07-26 17:38
Duplicate of #6755

**Closed** 2020-07-26 18:48 UTC
