### ISSUE TITLE
Deno Panicked after running code for a simple Vue.js app

### ISSUE THREAD

**Issue by JetSetVideo** [denoland/deno#19650] opened 2023-06-29 09:31 UTC
RUST_BACKTRACE=full deno run -A --node-modules-dir npm:vite

Download https://registry.npmjs.org/vite (2/3)
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.34.3
Args: ["deno", "run", "-A", "--node-modules-dir", "npm:vite"]

thread 'main' panicked at 'not found package: vue@3.2.47', /Users/ib/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_npm-0.8.1/src/resolution/graph.rs:375:17
stack backtrace:
   0:        0x1014f04c4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h3c406a4521928e59
   1:        0x100bcdb5c - core::fmt::write::hc60df9bae744c40c
   2:        0x1014c60a4 - std::io::Write::write_fmt::h1c4129dfc94f7c33
   3:        0x1014f4af4 - std::sys_common::backtrace::print::h34db077f1fa49c76
   4:        0x1014f4754 - std::panicking::default_hook::{{closure}}::hff4fe3239c020cef
   5:        0x1014f4434 - std::panicking::default_hook::hd2988fbcc86fdc46
   6:        0x100b43ac0 - deno::setup_panic_hook::{{closure}}::h9bccfc027f584975
   7:        0x1014f53f4 - std::panicking::rust_panic_with_hook::h01730ad11d62092c
   8:        0x1014f51f8 - std::panicking::begin_panic_handler::{{closure}}::h30f454e305d4a708
   9:        0x1014f5168 - std::sys_common::backtrace::__rust_end_short_backtrace::hb7ff1894d55794a1
  10:        0x1014f5144 - _rust_begin_unwind
  11:        0x100bcbcb4 - core::panicking::panic_fmt::hf1070b3fc33229fa
  12:        0x10100e334 - deno_npm::resolution::graph::Graph::from_snapshot::get_or_create_graph_node::hc46e481e85cc2cce
  13:        0x10100e250 - deno_npm::resolution::graph::Graph::from_snapshot::get_or_create_graph_node::hc46e481e85cc2cce
  14:        0x1008bd084 - deno_npm::resolution::snapshot::NpmResolutionSnapshot::resolve_pending::{{closure}}::h1c74addc195bdd9b
  15:        0x1008e9148 - deno::npm::resolvers::CliNpmResolver::resolve_pending::{{closure}}::hdfaebcf97e57dc9e
  16:        0x1008d4a14 - deno::graph_util::ModuleGraphBuilder::build_graph_with_npm_resolution::{{closure}}::hca44f74d7cb3150c
  17:        0x1008d338c - deno::module_loader::ModuleLoadPreparer::prepare_module_load::{{closure}}::h9a63dee5c464c5c9
  18:        0x100917238 - <deno::module_loader::CliModuleLoader as deno_core::modules::loaders::ModuleLoader>::prepare_load::{{closure}}::hfc1dc169971be663
  19:        0x100cd8dec - deno_core::modules::RecursiveModuleLoad::prepare::{{closure}}::h513361dcf71d0f82
  20:        0x100ceeb1c - deno_core::modules::map::ModuleMap::load_dynamic_import::{{closure}}::hb18da8e620e34aa7
  21:        0x100cdbd88 - deno_core::runtime::jsruntime::JsRuntime::poll_event_loop::h57756d6f50dbe13b
  22:        0x1008b5b50 - deno_runtime::worker::MainWorker::run_event_loop::{{closure}}::h9a797c3e9da666ca
  23:        0x10095eb88 - deno::worker::CliMainWorker::run::{{closure}}::h2e0fd501990fe273
  24:        0x100b044ac - deno::tools::run::run_script::{{closure}}::h5ad6ae6eeed051fa
  25:        0x100b02c94 - <deno_core::task::MaskFutureAsSend<F> as core::future::future::Future>::poll::h0dedf6011b8f5d18
  26:        0x100b093d8 - tokio::runtime::task::raw::poll::h3312096563d7d0bb
  27:        0x10086bb9c - deno::main::h53ea8b5818f035b8
  28:        0x10084ab08 - std::sys_common::backtrace::__rust_begin_short_backtrace::h9a6a8a5253274ff2
  29:        0x10086a718 - _main

**Comment by bartlomieju** [comment] 2024-12-06 02:03
We've done a ton of fixes to Vite support since this issue was opened. I'm gonna close it, because it lacks a reproduction.

**Closed by bartlomieju** 2024-12-06 02:03 UTC
Labels: needs info
