### ISSUE TITLE
String.prototype.localeCompare implementation

### ISSUE THREAD

**Issue by jsejcksn** [denoland/deno#6288] opened 2020-06-14 02:53 UTC
[`String.prototype.localeCompare()` on MDN](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare)

I noticed that some results differ significantly from Chrome in test cases when using this method. I'm not sure if/how this is standardized or where the responsibility lies, but I wanted to surface this because it seems like a bug.

Here's an example you can copy+paste to run in a browser console or Deno REPL:
```js
(() => {
  const pairs = [
    ['a', 'á'],
    ['á', 'a'],
    ['a', 'b'],
    ['b', 'a'],
    ['á', 'b'],
    ['b', 'á'],
  ];

  const compare = (a, b) => a.localeCompare(b, 'en-US', {sensitivity: 'base'});
  const results = pairs
    .map(pair => [...pair, compare(...pair)].join(' '))
    .join('\n');
  console.log(results);
})();
```

a | b | Chrome | Deno
---|---|--:|--:
a | á | 0 | -128
á | a | 0 | 128
a | b | -1 | -1
b | a | 1 | 1
á | b | -1 | 127
b | á | 1 | -127

Chrome `83.0.4103.97`
Deno `1.1.0`

Specifically, note [the description](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/Collator/Collator#:~:text=Only%20strings%20that%20differ%20in%20base%20letters%20compare%20as%20unequal) for using the value "base" for the "sensitivity" option:

> Only strings that differ in base letters compare as unequal. Examples: `a ≠ b`, `a = á`, `a = A`

In the example above for `a` and `á`, Chrome returns `0` (equal), but Deno does not.

**Comment by bartlomieju** [comment] 2020-07-14 12:56
Most likely #1968

**Comment by kitsonk** [comment] 2020-07-15 04:50
@bartlomieju it is a duplicate of #1968

**Comment by jsejcksn** [comment] 2020-07-15 05:17
@kitsonk If this is a duplicate, feel free to close.

**Comment by bartlomieju** [comment] 2020-07-15 08:41
Please continue in #1968

**Closed by bartlomieju** 2020-07-15 08:41 UTC
