### ISSUE TITLE
Basic values in deno repl are considered "syntax errors"

### ISSUE THREAD

**Issue by Qix-** [denoland/deno#3746] opened 2020-01-22 09:09 UTC
The Deno repl is very... well, unhelpful I'd say. Aside from the fact I can't actually run typescript in it, it also doesn't allow very basic values:

```
> {"foo":"bar"}
error: Uncaught SyntaxError: Unexpected token ':'
► <unknown>:1:7
    at evaluate ($deno$/repl.ts:84:34)
    at replLoop ($deno$/repl.ts:175:13)
```

Valid javascript, valid typescript. Why is this a syntax error?

**Comment by kevinkassimo** [comment] 2020-01-22 17:54
This is not valid JavaScript -- technically. Top level `{}` is treated as scope instead of object, so `"foo"` was treated as labels. In Node.js the REPL does a hack by trying wrapping `{}` with `()`. Maybe we can also do this to avoid confusion (since labels are uncommon in JavaScript)

**Comment by Qix-** [comment] 2020-01-22 18:31
It is 100% a valid Javascript expression...

**Comment by kevinkassimo** [comment] 2020-01-22 18:39
@Qix- See [`BlockStatement`](https://www.ecma-international.org/ecma-262/10.0/index.html#prod-BlockStatement), [`StatementListItem`](https://www.ecma-international.org/ecma-262/10.0/index.html#prod-StatementListItem), [`Statement`](https://www.ecma-international.org/ecma-262/10.0/index.html#prod-Statement), and [`LabelledStatement`](https://www.ecma-international.org/ecma-262/10.0/index.html#prod-LabelledStatement) from ECMA-262 for the case I mentioned here.

**Comment by kevinkassimo** [comment] 2020-01-22 19:13
Duplicate of #1421

**Closed** 2020-01-22 19:45 UTC
