### ISSUE TITLE
Build fails on raspberry pi 4

### ISSUE THREAD

**Issue by thpglobal** [denoland/deno#10873] opened 2021-06-07 02:49 UTC
Rust and cargo installed nicely today on my raspberry pi 4, but running the build script for deno resulted in 
```Compiling rand v0.7.3
error: failed to add native library /tmp/cargo-installYJydOT/release/gn_out/obj/librusty_v8.a: file too small to be an archive

error: aborting due to previous error

error: could not compile `rusty_v8`

To learn more, run the command again with --verbose.
warning: build failed, waiting for other jobs to finish...
error: failed to add native library /tmp/cargo-installYJydOT/release/gn_out/obj/librusty_v8.a: file too small to be an archive

error: aborting due to previous error

error: failed to compile `deno v1.10.3`, intermediate artifacts can be found at `/tmp/cargo-installYJydOT`

Caused by:
  build failed

**Comment by kitsonk** [comment] 2021-06-07 03:52
Duplicate of #1846

**Closed by kitsonk** 2021-06-07 03:52 UTC
Labels: duplicate
