### ISSUE TITLE
Deno User Manual missing page (404 - Not Found) for Cache API

### ISSUE THREAD

**Issue by lukepuplett** [denoland/deno#16768] opened 2022-11-22 18:13 UTC
Hey all, just learning Deno. Nice docs so far, clear, concise, consistent.

Anyway, this page is a 404.

https://deno.land/manual@v1.28.1/runtime/cache_api

**Comment by voizlav** [comment] 2022-11-22 18:57
I believe this is out of scope for deno core, it would be suited to transfer the issue to the [manual](/denoland/manual/) repository.

**Comment by crowlKats** [comment] 2022-11-22 19:26
Duplicate of denoland/manual#436

**Closed by crowlKats** 2022-11-22 19:26 UTC
