### ISSUE TITLE
Binary releases for arm64

### ISSUE THREAD

**Issue by odidev** [denoland/deno#8252] opened 2020-11-05 12:11 UTC
Expected behavior
Is there any plan to release a Deno binary for linux-arm64?

I have successfully created the binary for  Deno by running following:

curl --proto '=https' --tlsv1.2 -sSf https://sh.rustup.rs | sh
export PATH=$PATH:$HOME/.cargo/bin
apt install libglib2.0-dev
git clone https://github.com/denoland/deno/
cd deno
cargo build -vv

It will be very helpful if arm64 binaries are released. If any help is required in releasing them, I am happy to contribute.

Actual behavior
Deno binary is available for amd64 only.

**Comment by lucacasonato** [comment] 2020-11-05 12:35
Duplicate of https://github.com/denoland/deno/issues/1846.

We can not release arm64 until we have the capability to run the tests under arm. Currently running the test suite with QEMU results in a panic inside of the emulation layer.

**Closed** 2020-11-05 12:38 UTC
