### ISSUE TITLE
Native HTTP server: `Request.signal` should be aborted when request errors or is finished

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#10829] opened 2021-06-03 11:35 UTC
The signal would be aborted on connection errors, and once the request is responded to and the body is fully sent.

Depends on #5471

**Comment by davbrito** [comment] 2022-11-30 23:17
A reproducible example for this issue is the following:
```js
import { delay } from "https://deno.land/std@0.166.0/async/mod.ts";

Deno.serve(request => {
   const stream = new ReadableStream({
     start(controller) {
       (async () => {
         controller.enqueue("Hello ");
         await delay(5000, { signal: request.signal });
         controller.enqueue("World");
         controller.close();         
       })();
     }
   })
   return new Response(stream, { status: 200 })
})
```

1. Run the server.
2. Go to the page.
3. Reload or close the page.
4. At this moment the delay ends and when it tries to enqueue the string "World" it throws an unhandled rejection, because it's trying to enqueue into a closed connection.


It should instead abort de signal from the request, or call the `.cancel` method of the response body so the underlying source can know when to stop.

**Comment by TimoWilhelm** [comment] 2023-02-15 18:16
I'm trying to create a [Server-Sent Event](https://deno.com/blog/deploy-streams#server-sent-events) reply with Deno and I ran into this issue. 

The `AbortSignal` on a request does not notify if the client aborts the reuqest. 

There already is an `AbortSignal` attached to the request 
https://github.com/denoland/deno/blob/b34e751a5b2193e8ce65203386e00147c08a7a64/ext/http/01_http.js#L138

but it might be better to use an `AbortController` and pass it to the `createRespondWith` so it can be aborted when the response is cancelled?
https://github.com/denoland/deno/blob/b34e751a5b2193e8ce65203386e00147c08a7a64/ext/http/01_http.js#L182

**Comment by josephrocca** [comment] 2023-09-21 06:02
@aapoalas This doesn't seem to be fixed?
```js
import { delay } from "https://deno.land/std@0.202.0/async/mod.ts";
const textEncoder = new TextEncoder();

Deno.serve(request => {
  request.signal.addEventListener("abort", () => {
    console.log("request.signal aborted");
  });
  
  const stream = new ReadableStream({
    start(controller) {
     (async () => {
        controller.enqueue(textEncoder.encode("Hello "));
        await delay(5000, { signal: request.signal });
        controller.enqueue(textEncoder.encode("World"));
        controller.close();         
      })();
    },
    cancel(reason) {
      console.log("ReadableStream cancelled", reason);
    },
  });
  return new Response(stream);
});
```
If I open the page, then close it before the `delay` finishes I get:
```
ReadableStream cancelled resource closed
error: Uncaught (in promise) TypeError: The stream controller cannot close or enqueue.
        controller.enqueue(textEncoder.encode("World"));
```
So `ReadableStream.cancel` is being called, but the signal isn't being aborted? If my understanding is correct here, can this be reopened?

**Comment by mmastrac** [comment] 2024-04-24 18:04
Fixed in Deno.serve by https://github.com/denoland/deno/pull/23425 -- serveHttp will be fixed once we land the serveHttp-on-serve implementation at a later date.

**Closed by mmastrac** 2024-04-24 18:04 UTC
Labels: bug, runtime, ext/http
