### ISSUE TITLE
await Deno.stdout.write doesn't resolve when called in rapid succession

### ISSUE THREAD

**Issue by luke-john** [denoland/deno#6840] opened 2020-07-22 14:56 UTC
Came across this when using the https://github.com/jakobhellermann/deno-progressbar library to provide feedback on a series of tasks.

**example script that has the issue**

```ts
const exampleSource = ["one", "two"];
const encoder = new TextEncoder();

const exampleProcesses = exampleSource.map(async (value) => {
  const text = `${value}`;
  await Deno.stdout.write(encoder.encode(text));
});

await Promise.all([
  ...exampleProcesses,
  // not needed to reproduce, this is just to show the promise unresolved status in output
  new Promise((_, reject) => {
    setTimeout(() => {
      console.log("\n---\nfailures");
      exampleProcesses.forEach(console.log);
      reject();
    }, 1000);
  }),
]);
console.log("never reached");
```
**output of example script**

```sh
deno run test.ts
Check file:///Users/lukewoollard/work/deno-figma/test.ts
onetwo
---
failures
Promise { <pending> } 0 [ Promise { <pending> }, Promise { undefined } ]
Promise { undefined } 1 [ Promise { <pending> }, Promise { undefined } ]
error: Uncaught undefined
```

Worked around this locally by vendoring that code and replacing the use of `await Deno.stdout.write` with `Deno.stdout.writeSync`.

**Related issue**: https://github.com/denoland/deno/issues/5515

**Comment by caspervonb** [comment] 2020-07-22 16:58
Stripped down example:

```typescript
const encoder = new TextEncoder();
const pending = [
	Deno.stdout.write(encoder.encode("Hello, ")),
	Deno.stdout.write(encoder.encode("world!")),
];

await Promise.all(pending);
```

**Comment by caspervonb** [comment] 2020-07-23 10:17
From what I've gathered so far this was introduced by https://github.com/denoland/deno/issues/3565.
Removing the flush fixes this and works locally but breaks the CI 🤔

**Comment by bartlomieju** [comment] 2020-07-23 10:27
@caspervonb not really. Just yesterday I landed tokio upgrade. Does this problem persist?

**Comment by caspervonb** [comment] 2020-07-23 10:35
> Does this problem persist?

Unfortunately yes, this is reproducible with b573bbe4471c3872f96e1d7b9d1d1a2b39ff4cf1 as-well.

**Comment by CGQAQ** [comment] 2020-07-23 13:16
> From what I've gathered so far this was introduced by #3565.
> 
> Removing the flush fixes this and works locally but breaks the CI 🤔
> 
> Before I put another bandaid on top of the bandaid... did anyone ever work out the details of why we need this flush?
> 
> cc @bartlomieju @piscisaureus

![image](https://user-images.githubusercontent.com/15936231/88290549-88c22700-cd29-11ea-834e-94b847cbef7a.png)
![image](https://user-images.githubusercontent.com/15936231/88290668-b5763e80-cd29-11ea-9ebb-241af37eac48.png)
Me, too. Remove it works again

**Comment by caspervonb** [comment] 2020-07-23 23:10
>  I think it must be something wrong with that poll_flush, because first run the println!("{}", nwritten); corresponding to 'hello, ' did not run which was must been blocked by poll_flush

Pretty sure this would deadlock even with just two pairs poll_write and await in succession.

**Comment by Soremwar** [comment] 2020-12-16 19:12
Minimal reproduction provided by caspervonb no longer hangs in latest canary, but the code that sparked the issue still hangs due to first stdout write not being resolved before the second takes place

**Comment by caspervonb** [comment] 2020-12-17 09:20
> but the code that sparked the issue still hangs due to first stdout write not being resolved before the second takes place

Hm, the longer original test case also works fine now.

**Closed** 2020-12-17 14:01 UTC
Labels: bug, cli, high priority
