### ISSUE TITLE
deno.info api

### ISSUE THREAD

**Issue by jcc10** [denoland/deno#8644] opened 2020-12-07 12:33 UTC
This may sound weird but a deno.info api would be really helpful for me. (Exposing the output of the deno info command in some form without having to access the CLI.)

My use case is having deno make requests for the module and all imported modules to the webserver it's also running (allowing the server to trigger compiles for said modules.) and caching external modules to the local webserver by making requests. Finally, checking if any of the modules are loading from internet sources as opposed to local cache sources.

I'm sure there could be other ways of doing this, but it might be nice to be able to build custom tooling around the deno info command.

**Comment by nayeemrmn** [comment] 2020-12-07 12:45
Duplicate of #2096.

**Closed** 2020-12-07 12:47 UTC
