### ISSUE TITLE
ops panic in net/ext with a tls operation

### ISSUE THREAD

**Issue by riimalaj** [denoland/deno#13926] opened 2022-03-12 07:51 UTC
Hi,

Following code of mine caused panic, was instructed to report here. More accuratelly when fetching return value from haeMPYhteenveto function.

```js
const haeMPYhteenveto = () => {
    const mpSumma = itemServices.haeSumma();
    console.log(mpSumma);
    return mpSumma;
};

const haeOstokset = async ({ response }) => {
    const mpSumma = haeMPYhteenveto();
    response.body = await renderFile('../views/kulut.eta', {
        kustannukset: await itemServices.haeHankinnat(),
        mpsumma: mpSumma,
    });
};
```

**Error note:**
```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.18.1
Args: ["C:\\Users\\Admin\\.deno\\bin\\deno.exe", "run", "--allow-net", "--unstable", "--allow-read", "--allow-write", "app.js"]

thread 'main' panicked at 'Only a single use of this resource should happen: FullDuplexResource { rd: AsyncRefCell<tokio::net::tcp::split_owned::OwnedReadHalf>, wr: AsyncRefCell<tokio::net::tcp::split_owned::OwnedWriteHalf>, cancel_handle: CancelHandle { node: Node { inner: UnsafeCell { .. }, _pin: PhantomPinned } } }', D:\a\deno\deno\ext\net\ops_tls.rs:812:6
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by kitsonk** [comment] 2022-03-13 21:30
Duplicate of #13345

**Closed** 2022-03-13 21:30 UTC
Labels: duplicate
