### ISSUE TITLE
Un-catchable 'import()', Deno crash (V8 bug?)

### ISSUE THREAD

**Issue by lorenbrichter** [denoland/deno#7910] opened 2020-10-09 23:38 UTC
Not sure if this is rooted in a V8 glitch, but it still causes Deno to terminate. Basically can't seem to 'catch' an exception when importing a module a second time. Exception flies right to the top and terminates Deno. Tried to make the smallest possible case reproducing the issue:

     % deno run --allow-read test.js
    about to import...
    caught
    about to import again...
    error: Uncaught uh oh

test.js:

    console.log('about to import...');
    let a = await import('./test_module.js').catch(e => console.log("caught"));
    console.log('about to import again...');
    await import('./test_module.js').catch(e => console.log("caught again"));

test_module.js:

    throw "uh oh";

**Comment by kitsonk** [comment] 2020-10-10 03:23
Duplicate of #6259

**Closed by kitsonk** 2020-10-10 03:23 UTC
Labels: duplicate
