### ISSUE TITLE
streaming request support detection

### ISSUE THREAD

**Issue by jimmywarting** [denoland/deno#20690] opened 2023-09-26 18:04 UTC
I'm developing a lib that is suppose to work on multiple platform and today i had to resort to this [feature detection](https://developer.chrome.com/articles/fetch-streaming-requests/#feature-detection):

One modification i did was using a full url instead of /
```js
(() => {
  let duplexAccessed = false

  const hasContentType = new Request('http://localhost', {
    body: new ReadableStream(),
    method: 'POST',
    get duplex () {
      duplexAccessed = true
      return 'half'
    },
  }).headers.has('Content-Type')

  return duplexAccessed && !hasContentType
})()
```

Bun and NodeJS (undici), Blink all return true. 

I know that Deno (and all backends) supports streaming, but this came to bite me. 
probably have to do something like: `isBackend || test()` instead. 

anyway. wished this feature detection got fixed.

**Comment by lucacasonato** [comment] 2023-09-27 01:14
Duplicate of #16032

**Closed by lucacasonato** 2023-09-27 01:14 UTC
