### ISSUE TITLE
Possibly adding more customization to deno lint?

### ISSUE THREAD

**Issue by gm112** [denoland/deno#15937] opened 2022-09-17 19:50 UTC
Hi, I hope this is an appropriate forum for a feature request. For context - I've just been confused by the lack of configuring semicolons for the `deno lint` command, when you're able to customize other things such as quotes(double vs single).

Now, I understand not everyone likes ASI in JavaScript, but isn't the whole point of a linting tool to empower users to define their own coding standards? 

So to that end, I would like to ask the Deno maintainers if there are any plans to expand the scope of what can be configured with `deno lint`? Or is the intent of the tool to be opinionated and enforce one standard upon all users of the built in command?

**Comment by AnInternetTroll** [comment] 2022-09-17 20:11
First of all, you're thinking of `deno fmt` and `deno fmt --check`. Second, deno's core team has unfortunately been mostly against adding no semi colons into deno, so I doubt it will get added any time soon.

Luckily it's not that hard of a thing to add to deno. [Here's a patch that adds it for you](https://gist.github.com/AnInternetTroll/81ed97db853dc3628effed4157782509). Full disclaimer, I am the author of that patch. It's a couple of versions old now but hopefully it will still work

**Comment by kitsonk** [comment] 2022-09-17 23:32
Duplicate of #13616

**Closed by kitsonk** 2022-09-17 23:32 UTC
Labels: duplicate

**Comment by dsherret** [comment] 2023-01-26 16:00
@gm112 you can configure semicolons in Deno 1.30 https://deno.com/blog/v1.30#deno-fmt-supports-configuring-semicolons
