### ISSUE TITLE
TypeScript error when trying to run Rollup

### ISSUE THREAD

**Issue by bartlomieju** [denoland/deno#12339] opened 2021-10-06 00:45 UTC
I'm trying to run `rollup` with `--compat` flag, however I'm getting following error:
```
❯ deno run --compat --unstable dist/es/rollup.js
Check file:///Users/biwanczuk/dev/rollup/dist/es/rollup.js
error: TS2502 [ERROR]: 'thisArg' is referenced directly or indirectly in its own type annotation.
    bind<T>(this: T, thisArg: ThisParameterType<T>): OmitThisParameter<T>;
                     ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    at asset:///lib.es5.d.ts:350:22

```
I'm not entirely sure what's the problem here, are our declarations out of date?

CC @kitsonk

**Comment by kitsonk** [comment] 2021-10-06 01:15
Duplicate of #9073

Our definitions aren't out of date.  In particular I believe it is related to this: https://github.com/denoland/deno/issues/9073#issuecomment-758377830

**Closed** 2021-10-06 01:16 UTC
Labels: duplicate
