### ISSUE TITLE
Exiting from Deno REPL has diferent behaviours

### ISSUE THREAD

**Issue by Marcos-Costa** [denoland/deno#5407] opened 2020-05-14 18:22 UTC
When Deno REPL get invoked via bash in [Elementary OS](https://elementary.io/pt_BR/) (which is a ubuntu based distro), and then closed via Key binds ```Ctrl + c ``` or ```Ctrl + d ``` both work the same way closing it successfully.
But when one tries to close the REPL using ```close()``` function call, Deno blocks **visually** the shell. 

The user cannot  see anymore anything that is being typed at the terminal, until it's terminated.

I've added a GIF to illustrate:

![ezgif com-video-to-gif](https://user-images.githubusercontent.com/19848508/81970768-68257480-95f6-11ea-85a0-453efd48bf2b.gif)

I'm not sure if it's the intended behaviour of deno or a problem due to OS being used:
elementary OS 5.1.4 Hera Built on Ubuntu 18.04.4 LTS.

**Comment by kitsonk** [comment] 2020-05-15 11:44
Duplicate of #5449 

(though this was earlier, it was triaged there first)

**Comment by bartlomieju** [comment] 2020-05-15 16:26
Closing in favor of #5449

**Closed by bartlomieju** 2020-05-15 16:26 UTC
