### ISSUE TITLE
jupyter kernel issues

### ISSUE THREAD

**Issue by sigmaSd** [denoland/deno#20524] opened 2023-09-16 06:28 UTC
*importing npm:nodejs-polars in jupyter kills the client*
to reproduce
- add `import * as pl from 'npm:nodejs-polars'; ` to a cell
- execute it

Expected no error
Actual kernel crashes and restarts

Other (more simple) npm imports work (like npm:cowsay)

linux deno 1.36.4+bf07604
jupyter lab 4.0.5

![image](https://github.com/denoland/deno/assets/22427111/c1582a5d-2779-48a5-8560-28f64405e279)

**Comment by sigmaSd** [comment] 2023-09-16 06:39
** using dax fails**

- import {$} from "https://deno.land/x/dax/mod.ts"
- await $`ls` // was using this because we don't have ipython `!` to execute shell

errors with 
```
BadResource: Bad resource ID
    at opFetchSend (ext:deno_fetch/26_fetch.js:89:15)
    at mainFetch (ext:deno_fetch/26_fetch.js:277:18)
    at ext:deno_fetch/26_fetch.js:462:9
    at new Promise (<anonymous>)
    at fetch (ext:deno_fetch/26_fetch.js:425:18)
    at instantiateModule (https://deno.land/x/dax@0.17.0/src/lib/rs_lib.generated.js:375:34)
    at async https://deno.land/x/dax@0.17.0/src/lib/rs_lib.generated.js:316:27
    at async instantiate (https://deno.land/x/dax@0.17.0/src/lib/rs_lib.generated.js:294:11): 
    ```

**Comment by sigmaSd** [comment] 2023-09-16 06:43
*type errors are not show*

- Deno.writeTextFileSync("")

Expected error/warning that its missing a second param
Actual no error/warning

ipython seems to show an error for this 
![image](https://github.com/denoland/deno/assets/22427111/2f60e05c-97b9-4001-84db-572941de65a4)

**Comment by bartlomieju** [comment] 2023-09-16 08:32
Thanks for reporting @sigmaSd, could you please attach screenshots and/or output from the terminal for each error? These seems like minor issues that should be easy to fix.

**Comment by bartlomieju** [comment] 2023-09-16 09:30
@sigmaSd which version of Notebook do you use? @mmastrac hit the same problem on version 6 and worked on version 7. @rgbkrk can we somehow return errors in a backwards compatible way?

**Comment by sigmaSd** [comment] 2023-09-16 14:34
I tried jupyter 7.0.3, jupyter lab 4.0.5 (linuxà

same error on both

**Comment by sigmaSd** [comment] 2023-09-16 14:35
![image](https://github.com/denoland/deno/assets/22427111/1cf9f925-12d7-43fa-ac4d-46ad40c28ff7)

**Comment by rgbkrk** [comment] 2023-09-16 16:57
If you're seeing `BadResource: Bad resource ID` then `deno` likely wasn't built with `--features __runtime_js_sources`. If you're using `cargo run` to do the kernel install, `--features __runtime_js_sources` has to be in the cargo run line like:

```
cargo run --features __runtime_js_sources -- jupyter --install
```

> can we somehow return errors in a backwards compatible way

I'll look into that now. It might be something super silly like needing to add in an empty string into the traceback field `traceback: ['']`

**Comment by sigmaSd** [comment] 2023-09-16 17:13
I'm just using `deno upgrade --canary` don't know which features are set by default

**Comment by rgbkrk** [comment] 2023-09-16 17:28
Darn. I can't use the canaries on my Mac (M1) even in Docker (aarch64) due to a lack of ARM builds.

```
------
 > [4/6] RUN curl -fsSL https://deno.land/x/install/install.sh | sh:
#7 0.779 Error: Official Deno builds for Linux aarch64 are not available. (see: https://github.com/denoland/deno/issues/1846 )
------
process "/bin/sh -c curl -fsSL https://deno.land/x/install/install.sh | sh" did not complete successfully: exit code: 1
```

**Comment by rgbkrk** [comment] 2023-09-16 17:48
Confirmed errors looking ok in 7.0.3

<img width="787" alt="image" src="https://github.com/denoland/deno/assets/836375/dd521e0f-d006-4b1a-afd2-6083f00e16c1">

I downgraded to 6.5.1 and confirmed we don't have errors showing. Working on a PR shortly.

**Comment by bartlomieju** [comment] 2023-09-16 18:19
> If you're seeing `BadResource: Bad resource ID` then `deno` likely wasn't built with `--features __runtime_js_sources`. If you're using `cargo run` to do the kernel install, `--features __runtime_js_sources` has to be in the cargo run line like:
> 
> ```
> cargo run --features __runtime_js_sources -- jupyter --install --unstable
> ```
> 
> That's likely why the native modules aren't working either. Deno behaves really strangely without that flag.

@rgbkrk you shouldn't need that flag. It is only meant for development when working on internal JavaScript or TypeScript. The effect it has is that it doesn't embed these sources inside the binary and reads them from disk (so when you change something, it's enough to restart the process to see JS/TS changes reflected, without a need to build again). When working on something in Rust (like Jupyter kernel) this flag has no meaning and you still need to rebuild everytime you change something.

> I downgraded to 6.5.1 and confirmed we don't have errors showing. Working on a PR shortly.

Sweet, thanks 👍

**Comment by rgbkrk** [comment] 2023-09-16 18:41
Figured it out. Classic Notebook was less tolerant of `evalue` being empty, even if `ename` was set.

**Comment by mmastrac** [comment] 2023-09-16 19:46
@rgbkrk feel free to ping me on any PRs and I'll be happy to review quickly so we can solidify this as much as possible before the release!

**Comment by rgbkrk** [comment] 2023-09-17 00:01
Ok after banging my head on the `ExceptionDetails` object and trying to learn rust by diving in headfirst here, I've opted for the dumbest fix https://github.com/denoland/deno/pull/20531

**Comment by mmastrac** [comment] 2023-09-18 16:27
> import * as pl from 'npm:nodejs-polars'; 

This one appears to be fixed now.

> `import {$} from "https://deno.land/x/dax/mod.ts"/ await $ls`

Also appears to be working now.

> Deno.writeTextFileSync("")

Appears not to be working in `jupyter console`, but works in lab. I'm going to open a new bug for this one. https://github.com/denoland/deno/issues/20553

**Comment by mmastrac** [comment] 2023-09-18 16:53
@sigmaSd I'm going to close this in favour of smaller follow-up issues. I believe that your initially reported issues are fixed (with the exception of exceptions in `jupyter console`). Thanks for testing this out so early and letting us know about these issues.

**Closed by mmastrac** 2023-09-18 16:53 UTC
Labels: bug, cli, jupyter

**Comment by rgbkrk** [comment] 2023-09-18 16:57
```
import {$} from "https://deno.land/x/dax/mod.ts"

await $`pwd`
```

Wow this is pretty cool. I can see the result in the console but it doesn't show up in the notebook. Is stdout not being captured in some cases?

**Comment by mmastrac** [comment] 2023-09-18 17:07
> Is stdout not being captured in some cases?

I believe that is correct. We need to make stdout and stderr a pipe. Right now we're only feeding console.log and the family to the notebook's stdout/stderr streams.

**Comment by rgbkrk** [comment] 2023-09-18 17:52
Confirmed that polars imports properly with the canary release now too!

**Comment by rgbkrk** [comment] 2023-09-23 04:08
I don't have the ability to edit the above so I just want to mention that the right way to import polars is:

```
import pl from "npm:nodejs-polars";
```

The default export has, for example `pl.col` whereas `import * as pl` won't give access to some of the selector functions.
