### ISSUE TITLE
deno cache --vendor does not generate an import map

### ISSUE THREAD

**Issue by andreas-wagner** [denoland/deno#24647] opened 2024-07-19 08:45 UTC
I used `deno vendor` over `deno cache` (the latter with setting `DENO_DIR` to something like "./_cache"), because of how small and flexible it is, especially with the import map and the IDE being able to follow up on definitions properly.

Generally my requirement is to have a full working offline copy of everything directly in the project.

My issue is, that `deno cache --vendor deps.ts` does generate a "vendor" folder, but it does not generate an `import_map.json` file inside the "vendor" folder, and also does not update "deno.json" at all.

This means if I do `deno run --cached-only --no-remote main.ts` then it does not run, because of course it does not know anything about the vendor folder.

Moving things from `deno vendor` to `deno cache` is generally a good idea, but it would be good to have a result that would actually be meaningful, instead of creating a folder with some "unrelated" (that's how `deno run` and `deno test` "sees" it) files in it...

Sorry I did not want to sound rude at all, I don't know how to express this more positively...

```sh
deno --version
deno 1.45.2 (release, x86_64-apple-darwin)
v8 12.7.224.12
typescript 5.5.2
```

**Comment by dsherret** [comment] 2024-07-19 15:43
This is by design. An import map cannot represent all scenarios necessary for vendoring unfortunately.

> This means if I do `deno run --cached-only --no-remote main.ts` then it does not run, because of course it does not know anything about the vendor folder.

Use `deno run --cached-only main.ts` and it will only use what's in the vendor folder. You don't need to specify `--no-remote`. The vendor folder maintains that the module is remote and so will work the same way vendored as not instead of potentially changing behaviour like with `deno vendor`.

**Comment by lucacasonato** [comment] 2024-08-02 09:45
@andreas-wagner I think the missing link is that you also need to pass `--vendor` to `deno run`. Or you need to specify `vendor: true` in your `deno.json`. Both of these will cause Deno to use the vendor folder.

**Comment by lucacasonato** [comment] 2024-08-02 09:46
I'm going to close this for now. If you have any other problems, feel free to re-open the issue.

**Closed by lucacasonato** 2024-08-02 09:46 UTC
Labels: question
