### ISSUE TITLE
Don't die on invalid utf8 source files

### ISSUE THREAD

**Issue by ry** [denoland/deno#1489] opened 2019-01-09 18:08 UTC
example: https://github.com/denoland/deno/commit/0ceb554343ff3d311a19f027b7aa8f0806bbb162#diff-b9d53e20d7eb637f2c93606fc9b689b4L36

**Comment by bartlomieju** [comment] 2019-12-27 16:17
Duplicate of #627

**Closed by bartlomieju** 2019-12-27 16:17 UTC
Labels: bug

**Comment by gewoonwoutje** [comment] 2020-04-10 21:21
#627 Seems to be about the paths, but the file content encoding also makes deno panic.
For instance, when running this in powershell (which defaults to UTF-16 LE encoding?):
```pwsh
"console.log(`hi`);" > test.ts     
deno bundle test.ts test.bundle.js
```
You'll receive:
```err
thread 'deno-ts-compiler' panicked at 'called `Result::unwrap()` on an `Err` value: FromUtf8Error { bytes: [255, 254, 99, 0, 111, 0, 110, 0, 115, 0, 111, 0, 108, 0, 101, 0, 46, 0, 108, 0, 111, 0, 103, 0, 40, 0, 104, 0, 105, 0, 41, 0, 59, 0, 13, 0, 10, 0], error: Utf8Error { valid_up_to: 0, error_len: Some(1) } }', cli\ops\compiler.rs:159:16
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
thread 'main' panicked at 'Compiler didn't respond', cli\compilers\ts.rs:623:15
```
Fyi, I figured this out after stumbling over manually piping the bundle output to a file. This will panic when run:
```pwsh
deno bundle utf8_encoded_file.ts > piped.bundle.js
deno run piped.bundle.js # Will panic
```
While using the output arg of bundle will work fine:
```pwsh
deno bundle utf8_encoded_file.ts output.bundle.js
deno run piped.bundle.js # Will work fine
```

**Comment by gewoonwoutje** [comment] 2020-04-10 21:23
What is the desired behavior here? Like rust, only accept UTF-8 encoded input files?
