### ISSUE TITLE
[Feature Request] Public API for TTYs

### ISSUE THREAD

**Issue by AZMCode** [denoland/deno#6915] opened 2020-07-29 22:07 UTC
I'm suggesting some sort of interface to incorporate the functionality of Node's `tty` module, which would solve #6738, as well as setting all sort of terminal configurations, such as enabling/disabling input echo, and getting the terminal size.

**Comment by kitsonk** [comment] 2020-07-30 04:12
Duplicate of #6706 and #3456 which was closed by #6520.

**Comment by AZMCode** [comment] 2020-07-30 21:14
What about the cursor positioning, terminal echo, and potentially other configs? 
While I am aware some of these features have been solved separately, would it not be better to put these in a unified interface?

**Comment by caspervonb** [comment] 2020-07-30 23:35
> What about the cursor positioning, terminal echo, and potentially other configs?

In the runtime, or in std as escape sequences?

**Comment by kitsonk** [comment] 2020-07-30 23:38
I don't see how this issue is unique/different from #6706 you opened, which is far more specific about what capabilities you would like to see... For the sake of everyone's sanity, could we try to keep the discussion in one issue, up until there is something actionable that warrants creating multiple issues?

**Comment by caspervonb** [comment] 2020-07-30 23:40
Also related https://github.com/denoland/deno/issues/6738

**Closed** 2020-07-30 23:42 UTC

**Comment by AZMCode** [comment] 2020-07-31 20:48
Understandable
