### ISSUE TITLE
thread 'main' panicked at 'internal error: entered unreachable code'

### ISSUE THREAD

**Issue by hanzlahabib** [denoland/deno#5119] opened 2020-05-06 23:27 UTC
I just started playing with Deno, 
i made simpler handler which intercepts req and process that

here is my index file
```
import { serve } from "https://deno.land/std@v0.42.0/http/server.ts";
import handler from './handler.ts'
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");

if(Deno.args.length !== 1){
  throw new Error('Handler is not defined')
}

// console.log(finalHandler)
for await (const req of s) {
  if(req.url === '/'){
    req.respond({ body: handler(req) });
  }else{
    req.respond({})
  }
}

```

and this is my simple handler file

```
import { ServerRequest } from "https://deno.land/std@v0.42.0/http/server.ts";
export default (req: ServerRequest) => {
    return `test ${req.url} `
}

```

if i run this command 
```
deno run --allow-net --allow-read index.ts handler.ts
 ```
it works fine, and when i try loading handler file from Deno args and try importing them then it give me error

Updated code in index.ts which fails

```
import { serve } from "https://deno.land/std@v0.42.0/http/server.ts";
// import handler from './handler.ts'
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");

if(Deno.args.length !== 1){
  throw new Error('Handler is not defined')
}

let handlerPath = await Deno.realPath(Deno.args[0])
console.log(handlerPath)
let finalHandler = await import(handlerPath)

console.log(finalHandler)
for await (const req of s) {
  if(req.url === '/'){
    req.respond({ body: finalHandler(req) });
  }else{
    req.respond({})
  }
}

```
it throws error at time of importing file

```
let finalHandler = await import(handlerPath)
```
now when i run this command
```
deno run --allow-net --allow-read index.ts handler.ts
 ```
 it gives me this error
```
thread 'main' panicked at 'internal error: entered unreachable code', cli\state.rs:492:12
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by zjopy** [comment] 2020-05-07 06:35
Duplicate of #5058

**Comment by bartlomieju** [comment] 2020-05-07 12:14
Closing in favor of #5048

**Closed by bartlomieju** 2020-05-07 12:14 UTC

**Comment by hanzlahabib** [comment] 2020-05-18 07:06
@bartlomieju  why it works for some? i was walking through lecture and he did same as i explained in my question, his deno compiler didn't throw any error
is there any specific reason for that? or it was supported earlier and now it is deprecated?

**Comment by bartlomieju** [comment] 2020-05-18 09:02
@hanzlahabib when using dynamic import that are absolute, make sure to pass full URL - it must be with `file`, `http` or `https` scheme. I presume you were running on Windows and ended up with path to file which was not a URL
