### ISSUE TITLE
deno bundle doesn't resolve conflicting names (ex. Map)

### ISSUE THREAD

**Issue by bxantus** [denoland/deno#12121] opened 2021-09-17 14:18 UTC
`deno bundle` (also `Deno.emit` with bundle) seems to have broken. 

For example when I export a class named Map, it conflicts with the builtin javascript Map type. By conflict I mean, that on each place where I like to use the map data structure, my own Map class will be instantiated (bundle should have renamed it to Map1 or something similar).

## Steps to reproduce
I made a minimal example consisting of two files, with which the problem can be easily reproduced:
**myMap.ts**
```ts
export class Map {
    hello() {
        console.log("Hi")
    }
}
```
**test.ts**
```
import { Map as MyMap } from "./myMap.ts"

const map = new MyMap()
map.hello()
const tests = new Map<string, string>()
tests.set("test1", "my test")
```

When running test via `deno run test.ts`, I get the correct results:
```
Hi
```

But when running, after bundling, the error shows up:
```
>deno bundle test.ts test.js
Check file:///C:/work/test/test.ts
Bundle file:///C:/work/test/test.ts
Emit "test.js" (153B)

>deno run test.js 
Hi
error: Uncaught TypeError: tests.set is not a function
tests.set("test1", "my test");
      ^
    at file:///C:/work/test/test.js:9:7
```

**test.js**
```js
class Map {
    hello() {
        console.log("Hi");
    }
}
const map = new Map();
map.hello();
const tests = new Map();
tests.set("test1", "my test");
```
Which is obviously incorrect.
## Additional details
Deno version: deno 1.14.0

**Comment by bxantus** [comment] 2021-09-17 14:22
Update: deno 1.13 isn't affected by this bug (my project and the small test behaves correctly with it too)
**test.js** with deno 1.13.0
```js
class Map1 {
    hello() {
        console.log("Hi");
    }
}
const map = new Map1();
map.hello();
const tests = new Map();
tests.set("test1", "my test");
```

**Comment by MarkTiedemann** [comment] 2021-09-17 15:18
Seems like this is the same issue: https://github.com/denoland/deno/issues/12086

**Comment by kitsonk** [comment] 2021-09-18 07:21
Yes, duplicate of #10286. Previously symbols that shadowed the global scope symbols were being unnecessarily renamed, now they aren't being renamed at all.

**Closed by kitsonk** 2021-09-18 07:21 UTC
Labels: duplicate
