### ISSUE TITLE
deno.json(compilerOptions.jsx): options doesn't align with tsconfig. "preserve" not allowed

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#25767] opened 2024-09-20 14:53 UTC
Version: deno 2.0.0-rc.4+a92ebd9

repro:
- deno run npm:create-solid
  - Not SolidStart
  - Select TypeScript
- cd solid-project
- deno install
- delete tsconfig.json
- make deno.json with the following ([solid-js docs](https://docs.solidjs.com/configuration/typescript#configuring-typescript)):
```
{
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```
- deno task dev

The error is:
`error: Unsupported 'jsx' compiler option value 'preserve'. Supported: 'react-jsx', 'react-jsxdev', 'react', 'precompile'`

I assume it's because these are the allowed values:
https://github.com/denoland/deno/blob/471a15ecfffff009d24a684dda47a42aa71001d7/cli/args/mod.rs#L170-L175

Where in the tsconfig docs, these are the allowed options:
https://www.typescriptlang.org/tsconfig/#jsx

```
preserve
react
react-native
react-jsx
react-jsxdev
```

**Comment by marvinhagemeister** [comment] 2024-09-20 15:15
Related https://github.com/denoland/deno/issues/25677

**Comment by lucacasonato** [comment] 2024-09-23 09:02
Duplicate of #25677

**Closed by lucacasonato** 2024-09-23 09:02 UTC
