### ISSUE TITLE
`deno info` should return proper exit codes

### ISSUE THREAD

**Issue by janie314** [denoland/deno#21829] opened 2024-01-06 20:14 UTC
Version: Deno 1.39.2

When `deno info` fails, it should return proper Unix exit codes.

```shell
# deno info zzazz.com
error: module could not be found
# echo $?
0
```

**Comment by muddlebee** [comment] 2024-01-08 21:52
hey I would like to take this up 👀 

Common Unix exit codes are:
1: General errors or unspecified errors.
2: Misuse of shell built-ins (according to Bash documentation).

I think, a general error code like 1 would be appropriate for a situation where a command fails to execute its intended action (in this case, failing to find and provide information on a module).

**Comment by tannal** [comment] 2024-01-09 02:00
@muddlebee Here are something that might be helpful.
Deno will exit with 1 when it receives an error from the callee.
https://github.com/denoland/deno/blob/be888c068cbe42c1cb93d9885827dc97aa40d6f6/cli/main.rs#L260

Perhaps some of the code in the Deno info didn't return the error correctly.
Deno subcommands are usually in cli/tools.

**Comment by dsherret** [comment] 2024-01-09 23:15
Based on the code, I wonder if it's by design that it works this way.

That said, to make this change, only a few of these blocks just need to be changed to return an error instead of writing to the writer (ex. https://github.com/denoland/deno/blob/741afc4b94427588c628925fef464623d373430f/cli/tools/info.rs#L425-L431)

**Comment by muddlebee** [comment] 2024-01-15 16:45
hey I found the section where the `std::process::exit(1)` needs to be added.

https://github.com/denoland/deno/blob/741afc4b94427588c628925fef464623d373430f/cli/tools/info.rs#L509-L518

Although after adding it `std::process::exit(1) `, the error message is not getting printed. I did some research and I found the write buffer needs to be flushed, but its not supported in the library `use std::fmt::Write;` which we are using.

**Comment by dsherret** [comment] 2024-01-15 16:50
@muddlebee `std::process:exit` shouldn't be used in that file. Probably just need to change some return types like:

```rs
fn into_writer<TWrite: Write>(mut self, writer: &mut TWrite) -> fmt::Result
```

To:

```rs
fn into_writer<TWrite: Write>(mut self, writer: &mut TWrite) -> Result<(), AnyError>
```

Then modify some of the `writeln!` statements to instead use [`bail!`](https://docs.rs/anyhow/latest/anyhow/macro.bail.html) (only the ones for a top level error, not the ones for an error deep in the module graph). That will propagate the error up and cause a non-zero exit code.

**Comment by muddlebee** [comment] 2024-01-23 05:08
we can close this now. thank you so much for support. I made my first contribution 🍻

**Closed** 2024-01-23 14:36 UTC
Labels: bug, good first issue
