### ISSUE TITLE
Sometimes print "undefined" when close() in REPL since 1.5.0

### ISSUE THREAD

**Issue by KNnut** [denoland/deno#8338] opened 2020-11-10 15:53 UTC
And 1.4.6 works well.

**Comment by kitsonk** [comment] 2020-11-11 05:51
cc/ @caspervonb

**Comment by caspervonb** [comment] 2020-11-11 07:18
Race condition I suppose, the result of calling close is undefined, we check if closing is set before printing eval

**Comment by caspervonb** [comment] 2020-11-30 16:53
Am unable to reproduce this at all, had like 100-200 runs at it.
`close` and `globalThis.closing` are synchronous so my initial theory of a race was wrong.

**Comment by KNnut** [comment] 2020-12-01 10:25
@caspervonb Still on latest `master`.
![](https://user-images.githubusercontent.com/9387720/100727943-de0df380-3401-11eb-8a11-166f28f47fa8.gif)
![](https://user-images.githubusercontent.com/9387720/100727952-e1a17a80-3401-11eb-9abd-403475596c8c.gif)

**Comment by caspervonb** [comment] 2020-12-01 10:42
Yeah forgot, moved the condition to the loop condition.
Have a PR moving it back but this might be wontfix as close isn't necessarily the same as Deno.exit.

**Closed** 2020-12-01 13:13 UTC
Labels: bug :bug:, repl :keyboard:
