### ISSUE TITLE
Deno.lstat not accepting "file://" on Windows

### ISSUE THREAD

**Issue by mitom18** [denoland/deno#10266] opened 2021-04-20 10:21 UTC
**System:**

- OS: Windows
- Deno 1.9.0 (error also on 1.8.3)

```
error: Uncaught (in promise) Error: The filename, directory name, or volume label syntax is incorrect. (os error 123)
    await Deno.lstat(filePath);
    ^
    at unwrapOpResult (deno:core/core.js:100:13)
    at async Object.lstat (deno:runtime/js/30_fs.js:200:17)
    at async exists (https://deno.land/std@0.90.0/fs/exists.ts:7:5)
```
Looks like `Deno.lstat` has problem reading file path with the `file://` prefix. The problem can be reproduced with the following code:
```
import { resolve } from "https://deno.land/std@0.90.0/path/mod.ts";
await Deno.lstat("file://" + resolve("./config.ts"));
```
The `import("file://" + resolve("./config.ts"))` is working fine, however.

**Comment by caspervonb** [comment] 2021-04-20 11:10
Working as intended.
URLs and file paths are not the same thing.

**Comment by mitom18** [comment] 2021-04-20 11:45
Oh, I see, so the string needed by `import` is different than the one needed by `Deno.lstat`? The first one is URL and the other is file path?

**Comment by lucacasonato** [comment] 2021-04-20 11:46
Actually `lstat` does support file URLs, you just have to pass the URL as a `new URL()` instead of a string. If you pass a string it will be interpreted as a path.

**Comment by lucacasonato** [comment] 2021-04-20 11:47
Closing as working as intended.

File path? -> pass a plain string
File URL? -> pass a `URL`

**Closed by lucacasonato** 2021-04-20 11:47 UTC

**Comment by caspervonb** [comment] 2021-04-20 11:56
> Oh, I see, so the string needed by import is different than the one needed by Deno.lstat? The first one is URL and the other is file path?

Some file system functions in the Deno namespace do accept urls, but they have to be specified with URL objects to trigger the overload because "file://whatever" as a string is actually a valid name for a file (that's the incompatible part).

**Comment by domenic** [comment] 2024-03-17 10:20
Oof, this is a definite sharp edge. Being unable to do `Deno.readDirSync(import.meta.resolve("../foo"))` sucks.

**Comment by lucacasonato** [comment] 2024-03-20 05:54
@domenic You can do `Deno.readDirSync(new URL(import.meta.resolve("../foo")))`. Unfortunately `file:///foo/bar` is a valid relative file paths on Unix.

**Comment by domenic** [comment] 2024-03-20 07:59
Yeah just feels terrible. I wish there were an import.meta.resolveFile or something. I ended up having this workaround which I'll need in every file that reads from the FS. https://github.com/domenic/corrigibility/blob/fd158e63cc80dc1bf5eb821376db804e556219b9/test/scenarios.ts#L63
