### ISSUE TITLE
Implement Cache​Storage

### ISSUE THREAD

**Issue by davidbarratt** [denoland/deno#2194] opened 2019-04-24 14:16 UTC
I noticed that [CacheStorage](https://developer.mozilla.org/en-US/docs/Web/API/CacheStorage) hasn't been implemented yet, so here's a task to implement it. Thank you for all your hard work! :)

**Comment by zekth** [comment] 2019-04-24 15:21
There is already an issue about the implementation of different kind of `Storage` : https://github.com/denoland/deno/issues/1657

**Comment by davidbarratt** [comment] 2019-04-24 15:28
> There is already an issue about the implementation of different kind of `Storage` : #1657

That's a different API / Interface. :)

**Comment by zekth** [comment] 2019-04-24 15:29
If you read the whole issue there is same concern about Cache Session and so on

**Comment by davidbarratt** [comment] 2019-04-24 15:35
> If you read the whole issue there is same concern about Cache Session and so on

Ah!

**Comment by kitsonk** [comment] 2020-11-05 07:33
I know this came well before #5957 but we should consolidate everything around implementing Service Workers as a whole, not just parts of the API.  So closing this as a duplicate of #5957.

**Closed by kitsonk** 2020-11-05 07:33 UTC
Labels: duplicate :dancers:
