### ISSUE TITLE
`deno repl` is hanging after upgrading to 1.32.2

### ISSUE THREAD

**Issue by roj1512** [denoland/deno#18540] opened 2023-03-31 22:39 UTC
```
deno 1.32.2 (release, x86_64-unknown-linux-gnu)
v8 11.2.214.9
typescript 5.0.3
```

**Comment by dsherret** [comment] 2023-04-01 02:20
Does this occur only when launching in specific folders?

**Comment by dsherret** [comment] 2023-04-01 02:21
Pretty sure this is a duplicate of #18538

**Comment by roj1512** [comment] 2023-04-01 02:21
Yes.

**Comment by roj1512** [comment] 2023-04-01 02:21
> Does this occur only when launching in specific folders?

Yes.

**Comment by roj1512** [comment] 2023-04-01 02:23
> Pretty sure this is a duplicate of https://github.com/denoland/deno/issues/18538

Maybe edit its title to exclude Windows and generalize it?

**Closed** 2023-04-01 02:22 UTC
Labels: duplicate

**Comment by dsherret** [comment] 2023-04-02 00:37
Should be fixed now in 1.32.3.

**Comment by roj1512** [comment] 2023-04-02 01:07
Target clear. Copy.
