### ISSUE TITLE
unexpected dynamic import on string literals

### ISSUE THREAD

**Issue by hsiaosiyuan0** [denoland/deno#3457] opened 2019-12-07 03:58 UTC
Hi,

It looks like a bug while Deno doing its import statements parsing or regexp, below is the reproduction code:

```js
import { parse } from "https://www.unpkg.com/@babel/parser@7.7.5/lib/index.js";
console.log(parse);
```

results:

```
Compile file:///Users/hsy/ws/deno-js/js.ts
error: Uncaught ImportPrefixMissing: relative import path "a.js" not prefixed with / or ./ or ../ Imported from "https://www.unpkg.com/@babel/parser@7.7.5/lib/index.js"
► $deno$/dispatch_json.ts:40:11
    at DenoError ($deno$/errors.ts:20:5)
    at unwrapResponse ($deno$/dispatch_json.ts:40:11)
    at sendAsync ($deno$/dispatch_json.ts:91:10)
```

here is the potential being misrecognized statement in that js file:

```js
this.raise(id.start, `Dynamic imports require a parameter: import('a.js')`);
```

Does Deno use regexp to match the dynamic import expressions? I think it's  is a pretty unlikely scenario if a syntax parser is applied.

please correct me if something wrong

**Comment by nayeemrmn** [comment] 2019-12-07 04:02
Duplicate of #3089. This is a reported TS bug.

**Closed** 2019-12-08 02:59 UTC
