### ISSUE TITLE
There is way to reimport changed source file ?

### ISSUE THREAD

**Issue by xReveres** [denoland/deno#5937] opened 2020-05-29 08:27 UTC
Hi, I need to reimport script after changes (by others) at runtime, but deno doesn't want to recompile sources.
Simple test:
File test.ts
```typescript
await import("./abc.ts");

await Deno.writeTextFile("./abc.ts", "console.log('After changes');");

await import("./abc.ts");
```
File abc.ts
```typescript
console.log('Before changes');
```
Execute:
```shell
deno run --unstable --allow-all test.ts
```
Console output:
```shell
ubuntu@deno:~/workspace/deno$ deno run --unstable --allow-all test.ts
Compile file:///home/ubuntu/workspace/deno/test.ts
Before changes
ubuntu@deno:~/workspace/deno$ 
```
File abc.ts after run:
```typescript
console.log('After changes');
```

Deno version
```
deno 1.0.2
v8 8.4.300
typescript 3.9.2
```
OS Linux

**Comment by kitsonk** [comment] 2020-05-29 10:28
Duplicate of #5548

**Closed** 2020-05-29 15:01 UTC
