### ISSUE TITLE
Idea: work with HTTP and WebSockets in Rust, not in TS

### ISSUE THREAD

**Issue by sh7dm** [denoland/deno#1597] opened 2019-01-27 13:15 UTC
This will improve performance

**Comment by sh7dm** [comment] 2019-01-27 13:35
@axetroy the only way we can check it is benchmark, or we can ask @ry

**Comment by akircher** [comment] 2019-01-27 14:58
https://github.com/denoland/deno_std/issues/153

**Comment by kitsonk** [comment] 2019-01-28 02:14
Duplicate of #726

**Closed** 2019-01-28 04:56 UTC
