### ISSUE TITLE
Issues with npm packages when executing compiled Deno binary

### ISSUE THREAD

**Issue by MauriceAndre** [denoland/deno#26356] opened 2024-10-17 16:05 UTC
In Deno's [blog post](https://deno.com/blog/v1.34), it is mentioned that `deno compile` supports npm packages. I followed the example provided, and while the compilation succeeds, I encounter runtime errors when executing the compiled binary.

**Steps to Reproduce**:
1. Run the following command to compile the project:
   ```bash
   deno compile --allow-read --allow-write --allow-env --allow-net npm:vite
   ```
2. Execute the resulting binary.

**Expected Behavior**:  
The compiled binary should execute without errors and support npm packages as described in the blog post.

**Actual Behavior**:  
An error occurs when running the binary, with the following output:
```
error: Uncaught (in promise) Error: Cannot find module @rollup/rollup-win32-x64-msvc. npm has a bug related to optional dependencies (https://github.com/npm/cli/issues/4828). Please try `npm i` again after removing both package-lock.json and node_modules directory.
    at requireWithFriendlyError (file:///C:/path_to_temp/deno-compile-vite.exe/node_modules/localhost/rollup/4.24.0/dist/native.js:59:9)
    at Object.<anonymous> (file:///C:/path_to_temp/deno-compile-vite.exe/node_modules/localhost/rollup/4.24.0/dist/native.js)
    at require (node:module:808:16)
    at file:///C:/path_to_temp/deno-compile-vite.exe/node_modules/localhost/rollup/4.24.0/dist/native.js:3:13
Caused by: TypeError: LoadLibraryExW failed
```

Additionally, when I attempt to run a binary compiled from my own project that uses npm packages, I get another runtime error:
```
An error occurred Error: Command failed: c:\windows\system32\cscript.exe //Nologo C:\path_to_temp\deno-compile-devx.exe\node_modules\localhost\regedit\5.1.3\vbs\regList.wsf A HKCR\devx\

    at ChildProcess.exithandler (node:child_process:290:12)
    at ChildProcess.emit (ext:deno_node/_events.mjs:393:28)
    at maybeClose (ext:deno_node/internal/child_process.ts:69:11)
    at ext:deno_node/internal/child_process.ts:280:11
    at Object.runMicrotasks (ext:core/01_core.js:672:26)
    at processTicksAndRejections (ext:deno_node/_next_tick.ts:57:10)
```

**System Information**:
- Deno version: 2.0.0
- OS: Windows 11

**Comment by lucacasonato** [comment] 2024-10-21 10:04
Duplicate of #23266

**Closed by lucacasonato** 2024-10-21 10:04 UTC
Labels: bug, compile
