### ISSUE TITLE
Main thread panic and JSON parsing error with fetch()

### ISSUE THREAD

**Issue by RickStanley** [denoland/deno#10316] opened 2021-04-22 19:37 UTC
Issuing just this code: `await fetch("https://imunizacao-es.saude.gov.br/_search");`, in deno repl yields:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:564:49
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Running `RUST_BACKTRACE=1 deno`, with the same code:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:564:49
stack backtrace:
   0: rust_begin_unwind
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
   1: core::panicking::panic_fmt
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
   2: core::panicking::panic
             at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
   3: core::option::Option<T>::unwrap
   4: deno::tools::repl::run::{{closure}}
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
<details>
<summary>With `RUST_BACKTRACE=full`</summary>

```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/tools/repl.rs:564:49
stack backtrace:
   0:     0x563d8e68f803 - std::backtrace_rs::backtrace::libunwind::trace::h5e9d00f0cdf4f57e
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/libunwind.rs:90:5
   1:     0x563d8e68f803 - std::backtrace_rs::backtrace::trace_unsynchronized::hd5302bd66215dab9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
   2:     0x563d8e68f803 - std::sys_common::backtrace::_print_fmt::ha0237cd11a34e2bf
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:67:5
   3:     0x563d8e68f803 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h171d4c10df1a98ee
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:46:22
   4:     0x563d8de3f11c - core::fmt::write::h89e4288724daa3fa
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/fmt/mod.rs:1096:17
   5:     0x563d8e68f091 - std::io::Write::write_fmt::h6d40f996e84584d9
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/io/mod.rs:1568:15
   6:     0x563d8e68ea05 - std::sys_common::backtrace::_print::h0c0b93221682afc8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:49:5
   7:     0x563d8e68ea05 - std::sys_common::backtrace::print::h57a9f95204c2fdd6
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:36:9
   8:     0x563d8e68ea05 - std::panicking::default_hook::{{closure}}::h4245258b50e37e69
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:208:50
   9:     0x563d8e68e0ed - std::panicking::default_hook::h7b00dcc1d0944747
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:225:9
  10:     0x563d8e68e0ed - std::panicking::rust_panic_with_hook::h71e6a073d87de1f5
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:591:17
  11:     0x563d8e6ac2de - std::panicking::begin_panic_handler::{{closure}}::hd549436f6bb6dbb8
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:495:13
  12:     0x563d8e6ac27c - std::sys_common::backtrace::__rust_end_short_backtrace::h4e5f4b72b04174c3
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/sys_common/backtrace.rs:141:18
  13:     0x563d8e6ac22d - rust_begin_unwind
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/std/src/panicking.rs:493:5
  14:     0x563d8de3c800 - core::panicking::panic_fmt::hcd56f7f635f62c74
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:92:14
  15:     0x563d8de3c61c - core::panicking::panic::h07405d6be4bce887
                               at /rustc/2fd73fabe469357a12c2c974c140f67e7cdd76d0/library/core/src/panicking.rs:50:5
  16:     0x563d8db06c8e - core::option::Option<T>::unwrap::h476720b7d6af361e
  17:     0x563d8dc05440 - deno::tools::repl::run::{{closure}}::h9536eb290e568853
  18:     0x563d8dc009c6 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::ha5bab82f4502f0b2
  19:     0x563d8daed654 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h316e43b232c30a90
  20:     0x563d8dae0f60 - deno::main::h2f8fc5f55c65ca31
  21:     0x563d8dadcc0b - std::sys_common::backtrace::__rust_begin_short_backtrace::h4543d8b5bf03eeb3
  22:     0x563d8dadce92 - main
  23:     0x7f8814016b25 - __libc_start_main
  24:     0x563d8dad92ca - _start
  25:                0x0 - <unknown>
```
</details>

I expected an error since this public API needs Basic Authorization, and BTW **with authorization** (in REPL):

```
> let headers = new Headers();
undefined
> headers.set("Authorization", `Basic ${btoa("imunizacao_public:qlto5t&7r_@+#Tlstigi")}`)
undefined
> await fetch("https://imunizacao-es.saude.gov.br/_search", {headers: headers});
Uncaught TypeError: this.url is not a function
    at Response.[Deno.customInspect] (deno:op_crates/fetch/23_response.js:360:19)
    at inspectObject (deno:op_crates/console/02_console.js:925:50)
    at inspectValue (deno:op_crates/console/02_console.js:481:16)
    at inspectArgs (deno:op_crates/console/02_console.js:1454:19)
    at console.log (deno:op_crates/console/02_console.js:1504:9)
    at <anonymous>:4:9
```
------
Maybe this is a separate issue, but calling JSON parse in a public API like https://jsonplaceholder.typicode.com/ yields:
```
> fetch('https://jsonplaceholder.typicode.com/todos/1')
  .then(response => response.json())
  .then(json => console.log(json)).catch(console.log)
Promise { <pending> }
> SyntaxError: Unexpected token < in JSON at position 0
    at JSON.parse (<anonymous>)
    at packageData (deno:op_crates/fetch/22_body.js:247:21)
    at Response.json (deno:op_crates/fetch/22_body.js:192:18)
```
In Edge and Firefox:
![image](https://user-images.githubusercontent.com/23178554/115774986-44c78580-a380-11eb-8884-5df3b94e6627.png)
![image](https://user-images.githubusercontent.com/23178554/115775016-4f821a80-a380-11eb-8d60-eed8fd109674.png)

Deno --version:
```
deno 1.9.1 (release, x86_64-unknown-linux-gnu)
v8 9.1.269.5
typescript 4.2.2
```

**Comment by wperron** [comment] 2021-04-22 20:20
The first issue of the Rust panic has been resolved on main in 8d0e0ead and is available in the canary distribution (`deno upgrade --canary`)

As for the second issue, I get the same `SyntaxError: Unexpected token < in JSON at position 0` error on my end, in Deno, curl, Firefox and Chrome. Looking at it more carefully, it seems the host is returning a 401 with some HTML in the body, so this error message would be the expected behaviour. In that case, I would suggest looking at the response code before trying to parse the body as JSON. I'm assuming the reason it works for you in Chrome and Edge is that you are already logged in to the site and cookies are being sent along with your request.

Closing as this isn't actionable

**Closed by wperron** 2021-04-22 20:20 UTC
