### ISSUE TITLE
Bug: `@angular/cli` errors with `The encoded data is not valid.`

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25578] opened 2024-09-11 18:29 UTC
## Steps to reproduce

1. Run `deno run -A npm:@angular/cli@17.3.1 new test-app`
2. Press `Enter` a bunch of times to go through the wizard

Output:

```sh
$ deno run -A npm:@angular/cli@17.3.1 new test-app
? Which stylesheet format would you like to use? CSS             [ https://developer.mozilla.org/docs/Web/CSS                     ]
? Do you want to enable Server-Side Rendering (SSR) and Static Site Generation (SSG/Prerendering)? No
The encoded data is not valid.
```

Version: Deno 2.0.0-rc.1+1463a4a

**Comment by littledivy** [comment] 2024-09-13 18:18
Duplicate of https://github.com/denoland/deno/issues/22607

This was fixed in Angular https://github.com/angular/angular-cli/pull/27570 and works with latest angular CLI.

**Closed by littledivy** 2024-09-13 18:18 UTC
Labels: bug, node compat
