### ISSUE TITLE
Allow-env whitelist

### ISSUE THREAD

**Issue by brandonkal** [denoland/deno#6683] opened 2020-07-07 22:59 UTC
Is there a reason why allow-env does not support a whitelist?

I like the idea of knowing explicitly what environment variables the program can access. Often a program should only be able to access a few variables such as `DEBUG`.

Example invocation
```
DEBUG=* deno run --allow-env=DEBUG,TEST main.tsx
```

Of course the current alternative is something like this:

```
env -i HOME=$HOME PWD=$PWD PATH=$PATH DEBUG=* TEST=$TEST deno run --allow-env main.ts
```

**Comment by nayeemrmn** [comment] 2020-07-07 23:25
Duplicate of #3137.

**Comment by brandonkal** [comment] 2020-07-07 23:33
Man. I searched and didn't see that one. I even commented on it.

**Comment by ry** [comment] 2020-07-08 03:23
I'm in favor of the feature. Closing because duplicate.

**Closed by ry** 2020-07-08 03:23 UTC
