### ISSUE TITLE
when importing d.ts file, it should have a better error message

### ISSUE THREAD

**Issue by keroxp** [denoland/deno#4267] opened 2020-03-05 16:53 UTC
- Deno: v0.35.0

`.d.ts` file can't be compiled when it is  executed from CLI. 

```
$ deno empty.d.ts
Compile file:///Users/keroxp/src/deno/empty.d.ts
No such file or directory (os error 2)
```

Import without declaration cause same error.

**some.ts**

```ts
import "./empty.d.ts"
```
```
$ deno some.ts
Compile file:///Users/keroxp/src/deno/some.ts
Compile file:///Users/keroxp/src/deno/empty.d.ts
No such file or directory (os error 2)
```

With declaration, no error.

```
import * as empty from "./empty.d.ts"
```

**Comment by kitsonk** [comment] 2020-03-05 22:25
This is expected behaviour.  There is no code to run in a `.d.ts` file, so telling Deno to run a `.d.ts` file makes no sense.  A `.d.ts` file describes what is in a JS file, and you would need to reference the `.d.ts` file in an appropriate fashion: https://deno.land/std/manual.md#using-external-type-definitions

Doing a namespace import, you are referencing types in that file, bringing them into the other file and referencing them.  There is still no JavaScript emit from those files, but it brings those types into the type checking of another TypeScript file, and so is valid.

What is the use case?  The only "valid" use case is potentially having a `.d.ts` file with some global scope augmentation, which is more of trying to use the Deno compiler as a generic TypeScript compiler, in which the `Deno.compile()` and `Deno.bundle()` are better suited for that, and they support things like using `lib` and `types`.  But `deno run something.d.ts` should never work.

**Comment by ry** [comment] 2020-03-06 16:44
`No such file or directory (os error 2)` is maybe not the right error message, but I agree with @kitsonk... what would you expect this to do?

**Comment by keroxp** [comment] 2020-03-06 16:51
I know there are few use cases for that situation. I just feel it's strange that valid typescript file can't be imported. I think running `.d.ts` file should show error message before compiling or emit empty js file. 

I met this situation on #4197 . I tried to apply `JSX` namespace in jsx file by just importing `.d.ts` file. Eventually namespace import resolved the problem but `tsc` in Node.js accepts both importation for that purpose (maybe).

**Comment by ry** [comment] 2020-03-06 16:58
> I think running .d.ts file should show error message before compiling or emit empty js file.

I agree that it needs a better error message.

Maybe you can provide some fake sample output of what you'd expect to happen and then it will be easier for us to implement it.

**Comment by kitsonk** [comment] 2020-03-06 22:04
I had an additional thought about the:

```ts
import "something.d.ts";
```

This is the signal to the TS compiler to not drop the module from the emit because it has runtime side effects. This is theb not removing it from the emit, which is what occurs when it is a named import (because TypeScript realises it is types only and can be dropped). Deno then comes along, being told to load a file that didn't get emitted from the compiler, so it is a cache miss.

I believe in TS 3.8 there is the a type only import, which I believe might make the use case work without using some other triple slash directive.

**Comment by lucacasonato** [comment] 2020-08-14 09:45
@bartlomieju fixed this a while ago. We just emit an empty module for d.ts files now. Duplicate of https://github.com/denoland/deno/issues/6746 which is closed

**Closed by lucacasonato** 2020-08-14 09:45 UTC

**Comment by TradeIdeasPhilip** [comment] 2020-11-12 20:28
> This is expected behaviour. There is no code to run in a `.d.ts` file, so telling Deno to run a `.d.ts` file makes no sense. A `.d.ts` file describes what is in a JS file, and you would need to reference the `.d.ts` file in an appropriate fashion: https://deno.land/std/manual.md#using-external-type-definitions
> 
404, Not found

(I'm looking for a good starting place for *.jsx, skimming everything!)

**Comment by kitsonk** [comment] 2020-11-13 03:56
Documents move... updating comments in closed issues is usually not done.  Here is the link though: https://deno.land/manual@v1.5.2/getting_started/typescript#using-external-type-definitions
