### ISSUE TITLE
Allow `Deno.openPlugin` to take a URL specifier

### ISSUE THREAD

**Issue by eliassjogreen** [denoland/deno#10540] opened 2021-05-08 17:27 UTC
This would eliminate the need for modules like [plug](https://github.com/denosaurs/plug) and [deno-plugin-prepare](https://github.com/manyuanrong/deno-plugin-prepare) making plugins way more accessible. Allowing `Deno.openPlugin` to take a URL specifier would also make it possible for deno to directly cache the binary like a dependency (which [plug](https://github.com/denosaurs/plug) already does but using a [separate dependency](https://github.com/denosaurs/cache)) and reload the binary when the `--reload` flag is provided. The `Deno.openPlugin` should be able to take both remote and local urls to the binary and could possibly infer the url from os ~~and architecture~~ like [plug](https://github.com/denosaurs/plug) does.

**Comment by lucacasonato** [comment] 2021-05-08 17:29
Duplicate of https://github.com/denoland/deno/issues/3448

**Comment by eliassjogreen** [comment] 2021-05-08 17:30
Oops 🤦

**Closed by lucacasonato** 2021-05-08 17:29 UTC
