### ISSUE TITLE
Sending fatal alert DecodeError

### ISSUE THREAD

**Issue by NANOmatic** [denoland/deno#12355] opened 2021-10-07 13:20 UTC
We tried to connect to our MQTT broker by TLS secure connection, but without success 🙁
We still receive the same error:
`Sending fatal alert DecodeError`

Our keys and certs are generated correctly, because these work properly with `mosquitto_pub`, `mosquitto_sub` commands and various of other MQTT client softwares.

Bellow my code:
```
const connection = await Deno.connectTls({
  certFile: "./ca.crt",
  hostname: "example.mydomain.com",
  port: 8883
});

connection.close();
```
How can I establish secure TLS connection by Deno?

**Comment by lucacasonato** [comment] 2021-10-07 13:33
Is your CA file PEM encoded?

**Comment by lucacasonato** [comment] 2021-10-07 14:12
Could you send me the full `server.crt` file?

**Comment by lucacasonato** [comment] 2021-10-07 14:44
Your server.crt is missing a "subjectAltName". You need to set this when generating the certificate. https://security.stackexchange.com/questions/74345/provide-subjectaltname-to-openssl-directly-on-the-command-line might help.

**Comment by NANOmatic** [comment] 2021-10-07 16:16
I don't know what I did wrong, so please a look on whole our project.

`mosquitto.conf`
```
port 8883

cafile /etc/mosquitto/ca_certificates/ca.crt
keyfile /etc/mosquitto/certs/server.key
certfile /etc/mosquitto/certs/server.crt
tls_version tlsv1.2

pid_file /var/run/mosquitto.pid

persistence true
persistence_location /var/lib/mosquitto/

log_dest file /var/log/mosquitto/mosquitto.log

allow_anonymous false
password_file /etc/mosquitto/passwd
autosave_interval 0
autosave_on_changes true
```

`ca_gen.sh`
```sh
#!/bin/bash

days=${1:-3650}
caPath="ca_certificates"

caC="PL"
caST="State"
caL="City"
caO="Company"
caOU="Company"
caCN="myrealdomain1"
caE="myemail@address"

mkdir -p ${caPath}

openssl req -x509 -new -extensions v3_ca -keyout ${caPath}/ca.key -out ${caPath}/ca.crt -nodes -subj "/C=${caC}/ST=${caST}/L=${caL}/O=${caO}/OU=${caOU}/CN=${caCN}/emailAddress=${caE}" -days ${days}
```

`cert_gen.sh`
```sh
#!/bin/bash

days=${1:-3650}
cert=${3:-server}
certPath="certs"
caPath="ca_certificates"

caC="PL"
caST="State"
caL="City"
caO="Company"
caOU="Company (${cert})"
caCN="myrealdomain2"
caE="myemail@address"

./ca_gen.sh ${days} ${pass}

mkdir -p ${certPath}

openssl genrsa -out ${certPath}/${cert}.key 2048
openssl req -new -out ${certPath}/${cert}.csr -key ${certPath}/${cert}.key -subj "/C=${caC}/ST=${caST}/L=${caL}/O=${caO}/OU=${caOU}/CN=${caCN}/emailAddress=${caE}"
openssl x509 -req -in ${certPath}/${cert}.csr -CA ${caPath}/ca.crt -CAkey ${caPath}/ca.key -CAcreateserial -out ${certPath}/${cert}.crt -days ${days} -extfile <(printf "subjectAltName=DNS:${caCN},DNS:www.${caCN}")
rm ${caPath}/*.srl ${certPath}/*.csr
```

I replaced fields of the certificate to different names here.

**Comment by lucacasonato** [comment] 2021-10-07 16:22
The panic looks like a bug in our TLS code. @piscisaureus could you take a look?

**Comment by piscisaureus** [comment] 2021-11-05 22:07
> The panic looks like a bug in our TLS code. @piscisaureus could you take a look?

I wasn't able to reproduce the panic. I think it has been fixed in https://github.com/denoland/deno/pull/12501.

**Comment by lucacasonato** [comment] 2024-09-18 10:14
Closing as op did not respond in a while.

**Closed by lucacasonato** 2024-09-18 10:14 UTC
Labels: bug, needs investigation
