### ISSUE TITLE
Uncaught AddrInUse at unwrapResponse

### ISSUE THREAD

**Issue by tarsupin** [denoland/deno#6783] opened 2020-07-17 00:07 UTC
I've noticed that my server will run normally for some time (varies, but I'd expect sometimes for a few hours), then at an arbitrary point it will just stop responding, even if I haven't touched it for a while. Whenever this issue arises, I get the following from netstat -tulpn

```
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name
tcp        2      0 0.0.0.0:443             0.0.0.0:*               LISTEN      127338/deno
```

It looks completely normal, except the Recv-Q, which indicates that some of the requests haven't been processed. They will hang there forever, and just increment as I make additional calls.

I've dumped the logs and found an error that traces back to dispatch_json.ts from the serveTLS method.

```
error: Uncaught AddrInUse: Address already in use (os error 98)
    at unwrapResponse ($deno$/ops/dispatch_json.ts:42:1>
    at Object.sendSync ($deno$/ops/dispatch_json.ts:69:>
    at Object.listenTls ($deno$/ops/tls.ts:67:10^>
    at Object.listenTls ($deno$/tls.ts:51:22^[[90>
    at serveTLS (server.ts:339:25)
    at server.ts:32:11
```

Worth noting that it doesn't actually stop the server from running, it's just that the server will no longer fulfill any requests. My Postman will just sit there forever with "Sending Request..." until I cancel it.

Not sure what else to post, but I'm happy to answer any additional questions that I can.

**Comment by tarsupin** [comment] 2020-07-18 06:35
As part of a try/catch, still the same issue occurring.
```
    at unwrapResponse ($deno$/ops/dispatch_json.ts:42:>
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:93:>
    at async TLSListenerImpl.accept ($deno$/tls.ts:32>
    at async Server.acceptConnAndIterateHttpRequests (server.ts:212:14)
    at async MuxAsyncIterator.callIteratorNext (mux_async_iterator.ts:30:31)
```

**Comment by tarsupin** [comment] 2020-07-18 06:39
This also appears to be happening on an Oak server, running regular HTTP on port 80. It's hosting only static files, and is on a separate environment altogether. As such, since the only similarities between the code is the Server listening, I suspect this is a pretty critical Deno bug.

I ran -Ldebug on the static .html site (running through oak) and got this:

```
...
DEBUG JS - sendSync op_listen
^[[0m^[[1m⚠️️  Granted network access to "0.0.0.0:80"^[[0m
DEBUG JS - sendSync op_apply_source_map
DEBUG JS - sendSync op_apply_source_map
DEBUG JS - sendSync op_apply_source_map
DEBUG JS - sendSync op_apply_source_map
DEBUG JS - sendSync op_apply_source_map
DEBUG JS - sendSync op_apply_source_map
compiled filename: "/root/.cache/deno/gen/https/deno.land/std@0.61.0/http/server.ts.js"
DEBUG JS - sendSync op_apply_source_map
compiled filename: "/root/.cache/deno/gen/https/deno.land/x/oak/application.ts.js"
DEBUG JS - sendSync op_apply_source_map
compiled filename: "/root/.cache/deno/gen/file/opt/CreoWeb/server.ts.js"
^[[0m^[[1m^[[31merror^[[0m: Uncaught AddrInUse: Address already in use (os error 98)
    at ^[[1m^[[3m^[[90munwrapResponse^[[39m^[[23m^[[22m ^[[90m(^[[39m^[[90m$deno$/ops/dispatch_json.ts^[[39m^[[90m:^[[39m^[[90m42^[[39m^[[90m:^[[39m^[[90m11^[[3>
    at ^[[1m^[[3m^[[90mObject.sendSync^[[39m^[[23m^[[22m ^[[90m(^[[39m^[[90m$deno$/ops/dispatch_json.ts^[[39m^[[90m:^[[39m^[[90m69^[[39m^[[90m:^[[39m^[[90m10^[[>
    at ^[[1m^[[3m^[[90mObject.listen^[[39m^[[23m^[[22m ^[[90m(^[[39m^[[90m$deno$/ops/net.ts^[[39m^[[90m:^[[39m^[[90m52^[[39m^[[90m:^[[39m^[[90m10^[[39m^[[90m)^[>
    at ^[[1m^[[3m^[[90mObject.listen^[[39m^[[23m^[[22m ^[[90m(^[[39m^[[90m$deno$/net.ts^[[39m^[[90m:^[[39m^[[90m156^[[39m^[[90m:^[[39m^[[90m22^[[39m^[[90m)^[[39m
    at ^[[1m^[[3m^[[90mObject.listen^[[39m^[[23m^[[22m ^[[90m(^[[39m^[[90m$deno$/net_unstable.ts^[[39m^[[90m:^[[39m^[[90m43^[[39m^[[90m:^[[39m^[[90m12^[[39m^[[9>
    at ^[[1m^[[3mApplication.serve^[[23m^[[22m (^[[36mserver.ts^[[39m:^[[33m287^[[39m:^[[33m25^[[39m)
    at ^[[1m^[[3mApplication.listen^[[23m^[[22m (^[[36mapplication.ts^[[39m:^[[33m360^[[39m:^[[33m20^[[39m)
    at ^[[36mserver.ts^[[39m:^[[33m34^[[39m:^[[33m11^[[39m
^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@^@>
rust:shared_queue:push: num_records=1, num_shifted_off=0, head=988
DEBUG JS - sendAsync op_accept
read rid=588
rust:shared_queue:pre-push: op=37, off=812, end=824, len=12, aligned_end=824
rust:shared_queue:push: num_records=1, num_shifted_off=0, head=824
rust:shared_queue:pre-push: op=40, off=812, end=988, len=176, aligned_end=988
rust:shared_queue:push: num_records=1, num_shifted_off=0, head=988
DEBUG JS - sendAsync op_accept
read rid=589
rust:shared_queue:pre-push: op=40, off=812, end=988, len=176, aligned_end=988
```

**Comment by bartlomieju** [comment] 2020-08-12 10:35
@tarsupin thanks for reporting, can you please provide reproduction code?

**Comment by bartlomieju** [comment] 2021-06-26 02:05
We've had a major rework to net infrastructure since this issue was opened. Tentatively closed as fixed, please let me know if the problem persists.

**Closed by bartlomieju** 2021-06-26 02:05 UTC
Labels: bug
