### ISSUE TITLE
Bundle: Skypack Module Error

### ISSUE THREAD

**Issue by Maxvien** [denoland/deno#8344] opened 2020-11-11 08:51 UTC
**Describe the bug**

**Input code**
```ts
import { cong } from 'https://cdn.skypack.dev/tinh?dts';

console.log(cong(1, 2)); // deno run result: 3
```

**`Run` Result**
```
3
```

**`Bundle` Result**
```js
console.log(cong(1, 2));
```

**`Bundle` Expected Result**
```js
function cong(a, b) {
    return a + b;
}

console.log(cong(1, 2));
```

**Version**
1.5.2

**Comment by kitsonk** [comment] 2020-11-11 10:10
cc/ @kdy1

A minimal reproduction:

*example.ts*

```ts
import { u } from "./v.js";

console.log(u("a"));
```

*u.js*

```js
function u(str) {
  return str;
}

export { u };
export default null;
export const __esModule = true;
```

*v.js*

```js
export * from "./u.js";
export { default } from "./u.js";
```

**Comment by ije** [comment] 2020-11-14 06:36
@kdy1 i have same issue:

```bash
deno bundle entry.js output.js
```

*entry.js*

```javascript
import {useCounter} from './e.js';

console.log(useCounter)
```

*e.js*

```javascript
export * from "./r.js";
```
*r.js*

```javascript
import React from "https://cdn.esm.sh/v4/react@17.0.1/esnext/react.js";

function useCounter() {
    return React.useState(0)
}

export {useCounter}
```

*output.js*

```javascript
...REACT CODE...
console.log(useCounter);
```

**should be**:
```javascript
...REACT CODE...
function useCounter() {
    return React.useState(0);
}
console.log(useCounter);
```

**a little change of r.js**:

```javascript {2}
import React from "https://cdn.esm.sh/v4/react@17.0.1/esnext/react.js";

export function useCounter() {
    return React.useState(0)
}
```
now it works as expected, i guess it is the **tree-shaking** bug?

**Comment by quaos** [comment] 2020-11-14 08:19
@ije I've just tried this:
***deps/react.ts***
```typescript
import { default as _React } from "https://esm.sh/react@17.0.1?no-check";
export const React = {
  ..._React
};
```
It still has error in browser:
```
Uncaught ReferenceError: react_default is not defined
```

in ***public/assets/js/client.js***
```javascript
const React = {
    ...react_default
};
```

**Comment by ije** [comment] 2020-11-14 08:32
@quaos you can use esm.sh's bundle mode:

```javascript
import React from 'https://esm.sh/[react,react-dom]/react'
import ReactDOM from 'https://esm.sh/[react,react-dom]/react-dom'
export {React, ReactDOM}
```

this should work

**Comment by quaos** [comment] 2020-11-14 08:42
@ije Now there's a little progress! But the `ReactDOM` is still not found:

***deps/react.ts***
```typescript
import React from 'https://esm.sh/[react,react-dom]/react?no-check';
import ReactDOM from 'https://esm.sh/[react,react-dom]/react-dom?no-check';
export {React, ReactDOM}
```

***Browser console***
```log
Uncaught ReferenceError: ReactDOM is not defined
    at client.js:5890
```

[client.js.zip](https://github.com/denoland/deno/files/5540391/client.js.zip)

**Comment by ije** [comment] 2020-11-14 08:58
please try:
```javascript
import _React from 'https://esm.sh/[react,react-dom]/react'
import _ReactDOM from 'https://esm.sh/[react,react-dom]/react-dom'
export const React = _React
export const ReactDOM = _ReactDOM
```
i guess **swc** can not handle the `export {React, ReactDOM}` very well currently.

**Comment by quaos** [comment] 2020-11-14 09:15
@ije That was close! Next is this error:
https://reactjs.org/docs/error-decoder.html?invariant=332

![Screenshot 2020-11-14 161042](https://user-images.githubusercontent.com/32825171/99143950-797a3700-2694-11eb-9135-adeb1b773064.png)

**Comment by ije** [comment] 2020-11-14 09:27
this's is not deno(swc) bundler's issue, please move to https://github.com/postui/esm.sh/issues/1, thanks

**Comment by quaos** [comment] 2020-11-14 12:00
> please try:
> 
> ```js
> import _React from 'https://esm.sh/[react,react-dom]/react'
> import _ReactDOM from 'https://esm.sh/[react,react-dom]/react-dom'
> export const React = _React
> export const ReactDOM = _ReactDOM
> ```
> 
> i guess **swc** can not handle the `export {React, ReactDOM}` very well currently.

Umm ... seemed this way cannot be used as Namespace...
```typescript
import { React } from "../deps/react.ts";
console.log("React=", React);
console.log("React.FC=", React.FC);

// Here Deno complains:  Cannot find namespace 'React':
export const NotesList: React.FC<NotesListProps> = ({ }) => {
// ...
}
```

**Comment by bartlomieju** [comment] 2020-11-24 13:56
Fixed in #8443

**Closed by bartlomieju** 2020-11-24 13:56 UTC
Labels: bug :bug:, swc :sparkles:

**Comment by rok-star** [comment] 2021-02-11 04:08
Failed to bundle react + react-dom modules from skypack.

Do I miss something or it's bug of ```deno``` or bug of ```skypack```?

code:
```typescript
import * as React from 'https://cdn.skypack.dev/react?dts'
import * as ReactDOM from 'https://cdn.skypack.dev/react-dom?dts'

class App extends React.Component {
	render() {
		return (
			<div>123</div>
		)
	}
}

// @ts-ignore
ReactDOM.render(<App/>, document.getElementById('root'));
```

terminal:
```bash
deno_react $ deno bundle --unstable --reload ./app.tsx ./app.js
Bundle file:///Users/rs/Downloads/deno_react/app.tsx
Download https://cdn.skypack.dev/react-dom?dts
Download https://cdn.skypack.dev/react?dts
Download https://cdn.skypack.dev/-/react@v17.0.1-tOtrZxBRexARODgO0jli/dist=es2020,mode=imports/optimized/react.js
Download https://cdn.skypack.dev/-/react@v17.0.1-tOtrZxBRexARODgO0jli/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/react-dom@v17.0.1-DtIXT56q6U8PbgLMrBhE/dist=es2020,mode=imports/optimized/react-dom.js
Download https://cdn.skypack.dev/-/react-dom@v17.0.1-DtIXT56q6U8PbgLMrBhE/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/object-assign@v4.1.1-LbCnB3r2y2yFmhmiCfPn/dist=es2020,mode=imports/optimized/object-assign.js
Download https://cdn.skypack.dev/-/scheduler@v0.20.1-K7rlfsuSjvz1sBxLXfP2/dist=es2020,mode=imports/optimized/scheduler.js
Download https://cdn.skypack.dev/-/react@v17.0.1-tOtrZxBRexARODgO0jli/dist=es2020,mode=types/global.d.ts
Download https://cdn.skypack.dev/-/csstype@v3.0.6-gcORN5TZyTLQsfgMt9nf/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/-/prop-types@v15.7.2-IwOLL8mjF6Mz14kJuh13/dist=es2020,mode=types/index.d.ts
Check file:///Users/rs/Downloads/deno_react/app.tsx
error: TS2503 [ERROR]: Cannot find namespace 'CSS'.
    export interface CSSProperties extends CSS.Properties<string | number> {
                                           ~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-tOtrZxBRexARODgO0jli/dist=es2020,mode=types/index.d.ts:1546:44
```

**Comment by kitsonk** [comment] 2021-02-11 04:11
What happens with:

```
$ deno run --unstable ./app.tsx
```

**Comment by rok-star** [comment] 2021-02-11 04:13
> What happens with:
> 
> ```
> $ deno run --unstable ./app.tsx
> ```

I just figured out that React updated on skypack, looks like the bug in their side
<img width="315" alt="Screenshot 2021-02-10 at 22 12 01" src="https://user-images.githubusercontent.com/3323864/107601713-147ba200-6bed-11eb-8d47-4bbc595b9ad5.png">

**Comment by rok-star** [comment] 2021-02-11 04:15
> What happens with:
> 
> ```
> $ deno run --unstable ./app.tsx
> ```

```bash
deno_react $ deno run --unstable ./app.tsx       
Download https://cdn.skypack.dev/-/csstype@v3.0.6-gcORN5TZyTLQsfgMt9nf/dist=es2020,mode=types/index.d.ts
Check file:///Users/rs/Downloads/deno_react/app.tsx
error: TS2503 [ERROR]: Cannot find namespace 'CSS'.
    export interface CSSProperties extends CSS.Properties<string | number> {
                                           ~~~
    at https://cdn.skypack.dev/-/react@v17.0.1-tOtrZxBRexARODgO0jli/dist=es2020,mode=types/index.d.ts:1546:44
```

**Comment by ije** [comment] 2021-02-11 04:55
@rok-star try `https://esm.sh/react` instead

**Comment by rok-star** [comment] 2021-02-11 05:00
@ije 

👍🏿

<img width="296" alt="Screenshot 2021-02-10 at 22 59 53" src="https://user-images.githubusercontent.com/3323864/107603849-c1591d80-6bf3-11eb-91c6-e63d5cad49de.png">
