### ISSUE TITLE
just `deno` doesn't accept arguments that `deno repl` does

### ISSUE THREAD

**Issue by Ragzouken** [denoland/deno#5596] opened 2020-05-18 16:28 UTC
```
PS C:\Users\mark\Documents\PROJECTS\zone> deno --unstable
error: Found argument '--unstable' which wasn't expected, or isn't valid in this context

USAGE:
    deno [OPTIONS] [SUBCOMMAND]

For more information try --help
PS C:\Users\mark\Documents\PROJECTS\zone> deno repl --unstable
Deno 1.0.0
exit using ctrl+d or close()
>
```

**Comment by bartlomieju** [comment] 2020-05-18 22:36
Ref #5508

**Comment by actual-size** [comment] 2020-06-19 04:39
@bartlomieju So, I have a fix for this ready but I want to check what people thought of it. It checks if the first argument if a flag (by naïvely checking if it starts with `-`) and if it does, then it adds repl as the first argument.

**Comment by nayeemrmn** [comment] 2021-02-20 00:59
This works as intended and I think needing to add `repl` to add flags is acceptable. `deno` is a shorthand for `deno repl`, that's as far as the shorthand goes.

**Comment by lucacasonato** [comment] 2021-02-20 01:01
This issue is already resolved:

```
~ ❯❯❯ deno --unstable
Deno 1.7.4
exit using ctrl+d or close()
>
```

**Closed by lucacasonato** 2021-02-20 01:01 UTC
Labels: bug
