### ISSUE TITLE
Completions are broken since 1.18 in zsh

### ISSUE THREAD

**Issue by carlosala** [denoland/deno#13593] opened 2022-02-04 13:31 UTC
Hi!
Completions in zsh doesn't work in the following way since 1.18.0 (1.17.3 works):
  - It completes the commands correctly (such as `run`, `build`, etc)
  - It doesn't complete the directories: if you write `deno run` and <TAB> it doesn't show the folders and files.

**Comment by crowlKats** [comment] 2022-02-04 13:33
Probably related to updating to clap v3

**Comment by carlosala** [comment] 2022-02-04 14:07
I found the problem. Updating `clap_complete` to `3.0.5` creates a correct zsh completion, I tested it compiling only changing that dependency.

**Comment by sant123** [comment] 2022-02-17 15:57
The issue still persist in Deno v1.19.0 😞

**Comment by crowlKats** [comment] 2022-02-17 16:25
@sant123 It works fine for me

**Comment by sant123** [comment] 2022-02-17 17:07
I did the steps above but did not work either :/ 

I have deno installed by the native installer.

**Comment by jrylan** [comment] 2022-02-17 17:11
> try to do a `rm -r $ZSH/cache/completions` and then re-open a terminal. It should work.
> Do you have deno installed with package manager or just with the deno native installer?

Thank you @carlosala! `rm -r $ZSH/cache/completions` worked for me. Just to note, I'm also using the native installer.

**Comment by sant123** [comment] 2022-02-17 20:01
Don't know what I'm doing wrong 🤔 I repeated the same steps in both computers without success

**Comment by carlosala** [comment] 2022-02-19 00:06
For me it's also not working. I think that something changed and continues to not work.

**Comment by crowlKats** [comment] 2022-02-20 21:57
@carlosala I'd rather avoid reverting clap to v2

**Comment by sant123** [comment] 2022-02-21 21:23
I made a diff between Deno v1.17.3 and Deno v1.19.0 for the completion system and I noticed that the `_files` variable is missing in the generation:

![image](https://user-images.githubusercontent.com/7959437/155027794-1fa25ceb-f64e-4027-878b-c9b042218719.png)

Adding them manually fixes the issue 🤔 

@crowlKats @carlosala

**Comment by sant123** [comment] 2022-02-21 21:24
Please take a look at https://www.diffchecker.com/YYQhDZXL

**Comment by carlosala** [comment] 2022-03-07 11:57
Hi @crowlKats! Could you check the message above? Maybe there are some clap configurations that we can add to solve the issue

**Comment by mcornella** [comment] 2022-03-07 12:05
> Hi @crowlKats! Could you check the message above? Maybe there are some clap configurations that we can add to solve the issue

See https://github.com/denoland/deno/issues/10166#issuecomment-1060616635

**Comment by crowlKats** [comment] 2022-03-07 12:07
Hey @carlosala & @mcornella, sorry for not having looked into this yet. i will look at it later today

**Comment by crowlKats** [comment] 2022-03-08 14:45
Apologies for another delay, looking into this now

**Comment by crowlKats** [comment] 2022-03-08 14:54
@mcornella not too familiar with completions, but from my understanding, zsh and friends allow for something to be defined to have multiple "hints" for the same thing? Or rather, should clap allow setting multiple `ValueHint`s for a single argument?

**Comment by sant123** [comment] 2022-04-26 19:55
@crowlKats could you reopen this issue please?

**Comment by sant123** [comment] 2022-05-21 13:50
Tested on Fedora 36 and is working as expected. Somebody else is having issues in Linux?

**Comment by carlosala** [comment] 2022-05-21 15:18
Nope, it's fixed since 1.21 I think 👌🏻

**Comment by sant123** [comment] 2022-05-26 17:42
@carlosala when you input some flags in the subcomand does still work the autocomplete? 

`deno run --allow-net mod.ts`

For me it doesn't 😕

**Comment by crowlKats** [comment] 2023-01-10 04:08
for me this works as expected

**Comment by sant123** [comment] 2023-01-10 04:14
@crowlKats please type:

`deno run --allow-net`

And hit tab. Does it autocomplete the files in the current working directory?

**Comment by crowlKats** [comment] 2023-01-12 11:17
no, youa re right, it does not; I was pressing space after allow-net which would work

**Comment by lucacasonato** [comment] 2024-09-18 15:25
@marvinhagemeister is unable to reproduce this in the latest releases. I am going to close this issue. If you still run into this (or other completion related issues), please open a new issue!

**Closed by lucacasonato** 2024-09-18 15:25 UTC
Labels: bug
