### ISSUE TITLE
websockets error "unexpected eof"

### ISSUE THREAD

**Issue by jakeg** [denoland/deno#19055] opened 2023-05-09 13:49 UTC
I recently updated from Deno 1.27.2 to 1.33.2 and I'm noticing a new error sometimes with websockets that I wasn't seeing before: `unexpected eof`. It's happening quite a bit.

**Comment by bartlomieju** [comment] 2023-05-09 13:57
Could you provide some kind of a reproduction of your code?

**Comment by jakeg** [comment] 2023-05-09 14:27
Not easily. Any specific questions I could answer about it? You can see it running at https://www.mathsuniverse.com/infinity then "sync devices" for the websockets part of it.

**Comment by salemalem** [comment] 2023-06-15 16:24
Same issue.
![image](https://github.com/denoland/deno/assets/42411937/30a87836-0fdc-4912-8124-febe25b12fe3)

**Comment by littledivy** [comment] 2023-08-12 06:01
Hi, thanks for reporting. This was fixed in the latest release (1.36.1). A race condition in the read buffer caused it. Feel free to reopen if its still happening.

**Closed by littledivy** 2023-08-12 06:01 UTC

**Comment by BOLL7708** [comment] 2025-01-19 16:05
If anyone ends up here from Google. I had this work in Firefox but not Chrome, getting this exact error but for a different reason, turns out the upgrade response had to include the incoming subprotocol: 
```ts
const protocol = 'myprotocol'
Deno.upgradeWebSocket(req, { protocol })
```

**Comment by unek** [comment] 2025-04-01 00:43
can confirm still happening with loads of ~25MB/s
