### ISSUE TITLE
Rust compiler regression from 1.70.0 => 1.71.0

### ISSUE THREAD

**Issue by joehillen** [denoland/deno#19878] opened 2023-07-19 16:51 UTC
I was just now building deno for the first time, and I've hit the following compiler panic https://gist.github.com/joehillen/b8494ad2e06e65b8b57a7d2a0864e3d1

Downgrading to 1.70.0 avoids the problem.

I haven't opened a Rust bug yet because I don't have a minimal example. Perhaps someone here could help create one.

I'm on Arch, btw.

**Comment by bartlomieju** [comment] 2024-12-09 00:48
I don't think this is reproducible anymore, since Deno requires a newer Rust version (1.82.0). I'm gonna close this one for now.

**Closed by bartlomieju** 2024-12-09 00:48 UTC
