### ISSUE TITLE
Add section about writing plugins to `manual.md`

### ISSUE THREAD

**Issue by kevinkassimo** [denoland/deno#3895] opened 2020-02-05 23:20 UTC
I was notified that it seems we have no actual introduction about how to write a Deno plugin in the manual. Also the folder `test_plugin/`, while showing an example, is not mentioned anywhere in the manual, and is not easy to find (since the name does not indicate it also being an example)

IMO This could be a good first issue.

**Comment by ry** [comment] 2020-02-06 18:08
duplicate of https://github.com/denoland/deno/issues/3449

**Closed by ry** 2020-02-06 18:08 UTC
