### ISSUE TITLE
npm:otplib uninstall, Deno has panicked

### ISSUE THREAD

**Issue by AmjadRabadi** [denoland/deno#26602] opened 2024-10-28 13:47 UTC
Platform: windows x86_64

Version: 2.0.3
Args: ["C:\\Users\\username\\.deno\\bin\\deno.exe", "uninstall", "npm:otplib"]

thread 'main' panicked at C:\Users\runneradmin\.cargo\registry\src\index.crates.io-6f17d22bba15001f\jsonc-parser-0.26.1\src\cst\mod.rs:2310:24:
begin <= end (2 <= 1) when slicing `
  `
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by dsherret** [comment] 2024-10-28 17:49
Duplicate of https://github.com/denoland/deno/issues/26543

**Closed by dsherret** 2024-10-28 17:49 UTC
Labels: bug, duplicate, panic
