### ISSUE TITLE
Deno.land third party links are broken

### ISSUE THREAD

**Issue by reselbob** [denoland/deno#6007] opened 2020-05-31 16:21 UTC
Get the following error: `Querying the GitHub API failed. This is usually caused by a network outage or because you have reached your hourly API rate limit of 60 requests.`

Here is a screenshot:

![Screen Shot 2020-05-31 at 9 20 02 AM](https://user-images.githubusercontent.com/1110569/83357238-0c5e2980-a320-11ea-8b2c-c534afd8697a.png)

**Comment by nayeemrmn** [comment] 2020-05-31 16:42
Duplicate of https://github.com/denoland/deno_website2/issues/433.

**Comment by bartlomieju** [comment] 2020-06-07 12:24
Please continue in denoland/deno_website2#433

**Closed by bartlomieju** 2020-06-07 12:24 UTC
