### ISSUE TITLE
Type 'URL' is not assignable to type 'string'

### ISSUE THREAD

**Issue by nikorunikk** [denoland/deno#6873] opened 2020-07-25 08:42 UTC
> @ I'm running very simple server. But I have some errors. How I can solve this? I already updated to deno v1.2.1. But steel have this error. 

error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@v0.50.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@v0.50.0/path/posix.ts:433:18

**Comment by crowlKats** [comment] 2020-07-25 08:48
Duplicate of #6755

**Comment by nikorunikk** [comment] 2020-07-25 08:55
Thanks

**Closed** 2020-07-25 08:55 UTC
