### ISSUE TITLE
Broken Async Components in Hono

### ISSUE THREAD

**Issue by sant123** [denoland/deno#25278] opened 2024-08-28 21:32 UTC
Version: Deno 1.46.1

Please see https://hono.dev/docs/guides/jsx#async-component

Hello! Please take a look at this example:

```tsx
/** @jsxImportSource jsr:@hono/hono/jsx */
import { delay } from 'jsr:@std/async';
import { Hono } from 'jsr:@hono/hono';

const app = new Hono();

function SyncComponent() {
  return <h1>Hello from Sync component!</h1>;
}

async function AsyncComponent() {
  await delay(1000);
  return <h1>Hello from Async component!</h1>;
}

app.get('/sync', (c) => {
  return c.html(<SyncComponent />);
});

app.get('/async', (c) => {
  return c.html(<AsyncComponent />);
});

Deno.serve(app.fetch);

```

This code works on Deno v1.45.5 but not on later versions. Please take a look on the different behaviors:

v1.45.5

https://github.com/user-attachments/assets/01aa3f1b-4215-46f6-9b1e-dae5362945c0

v1.46.1

https://github.com/user-attachments/assets/5c58a267-9961-409e-aefa-cc6d68ff8d9b

Deno v1.46.1 for some reason returns an empty response, also if you trigger many requests the server crashes with the following error:

![image](https://github.com/user-attachments/assets/06176556-4c15-41c7-9aad-43b091e1842a)

Do you know what is happening here? 

Thanks.

**Comment by bartlomieju** [comment] 2024-08-28 21:40
This might be caused by the same problem that prompted: https://github.com/denoland/deno/pull/25207. Can you try with latest canary?

**Comment by sant123** [comment] 2024-08-28 22:29
It works with canary, you are the best. Thank you!

**Comment by lucacasonato** [comment] 2024-08-29 12:42
Closing as dupe of #25207

**Closed by lucacasonato** 2024-08-29 12:42 UTC
