### ISSUE TITLE
String.prototype.normalize() seems to to be available?

### ISSUE THREAD

**Issue by glowingblue** [denoland/deno#9000] opened 2021-01-05 09:59 UTC
Dealing with some annoying strings that I try to tame with `.normalize()` but it doesn't seem to work in deno (while it does in browsers), can you confirm that?

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/normalize

**Comment by lucacasonato** [comment] 2021-01-05 11:49
This is effectively a duplicate of #1968. We are planning to address this this quarter (see roadmap #8824).

**Closed by lucacasonato** 2021-01-05 11:49 UTC

**Comment by glowingblue** [comment] 2021-01-05 11:53
@lucacasonato thx for the quick reply! looking forward to that =)!
