### ISSUE TITLE
:bug: `Deno.env.get(KEY_STRING)` incorrectly disallows leading '=' in  KEY_STRING (Windows)

### ISSUE THREAD

**Issue by rivy** [denoland/deno#12305] opened 2021-10-03 03:49 UTC
`Deno.env.get(KEY_STRING)` is incorrectly panicking for environment key strings that contain the `=` character.

```shell
C:>ver

Microsoft Windows [Version 10.0.19042.1237]

C:>deno --version
deno 1.14.2 (release, x86_64-pc-windows-msvc)
v8 9.4.146.16
typescript 4.4.2

C:>echo %=C:%
C:\Users\Roy

C:>deno eval -T "console.log(Deno.env.get('=C:'));"
Check file:///C:/Users/Roy/$deno$eval.ts
error: Uncaught TypeError: Key contains invalid characters.
console.log(Deno.env.get('=C:'));
                     ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at Object.getEnv [as get] (deno:runtime/js/30_os.js:56:17)
    at file:///C:/Users/Roy/$deno$eval.ts:1:22

C:>node -e "console.log(process.env['=C:']);"
C:\Users\Roy
```

This is then causing a panic for `resolve()` from 'https://deno.land/std@0.109.0/path/mod.ts' when used for legal relative paths containing a drive specifier.

```shell
C>deno eval -T "import {resolve} from 'https://deno.land/std@0.109.0/path/mod.ts'; console.log(resolve('C:.'));"
Check file:///C:/Users/Roy/$deno$eval.ts
error: Uncaught TypeError: Key contains invalid characters.
      path = Deno.env.get(`=${resolvedDevice}`) || Deno.cwd();
                      ^
    at deno:core/01_core.js:106:46
    at unwrapOpResult (deno:core/01_core.js:126:13)
    at Object.opSync (deno:core/01_core.js:140:12)
    at Object.getEnv [as get] (deno:runtime/js/30_os.js:56:17)
    at resolve (https://deno.land/std@0.109.0/path/win32.ts:57:23)
    at file:///C:/Users/Roy/$deno$eval.ts:1:80
```

The `resolve()` code is correctly written; `Deno.env.get()` is panicking incorrectly.

**Comment by dsherret** [comment] 2021-10-04 02:24
We shouldn't be doing that in std. I opened https://github.com/denoland/deno_std/issues/1341 for reasons described there.

In Rust, calling `std::env::var` with an equals sign in the variable name will panic. Technically, environment variable names [can't include an equals sign](https://docs.microsoft.com/en-us/windows/win32/procthread/environment-variables) on Windows, but cmd.exe (command prompt) has some special ones that are only injected within cmd's environment for "private bookkeeping reasons":

> Win32 does not have the concept of a separate current directory for each drive, but the command processor wanted to preserve the old MS-DOS behavior because people were accustomed to it (and batch files relied upon it). The solution was to store this “per-drive current directory” in the environment, using a weird-o environment variable name so it wouldn’t conflict with normal environment variables.
>
> ...
>
> The variables are exported into the environment because you want these “fake per-drive current directories” to be inherited by child processes. For example, consider that you are sitting at your command prompt, you run emacs, then from emacs, you shell out to another command prompt. You would expect that the nested command prompt will have the same “per-drive current directories” that you set back in the outer command prompt.

See https://devblogs.microsoft.com/oldnewthing/20100506-00/?p=14133

Overall, I don't think we should bother supporting this.

**Comment by dsherret** [comment] 2021-10-04 02:28
I'm going to close this as working as designed because we don't allow equals signs in environment variables and I don't believe these special cmd-only environment variables are worth supporting. We definitely should fix that issue in std though.

**Closed by dsherret** 2021-10-04 02:28 UTC
Labels: cli, windows, working as designed

**Comment by rivy** [comment] 2021-10-10 02:48
@dsherret , reasonable as long as the `path.resolve()` bug can be fixed without it.
Thanks for the look!
