### ISSUE TITLE
Bundle tree shaking too aggressive in certain situations

### ISSUE THREAD

**Issue by lsarrazi** [denoland/deno#9076] opened 2021-01-10 02:12 UTC
Just trying to compile with the new command `deno compile main.ts --unstable`

```ts
class App
{
	constructor()
	{
		console.log('Hello from app')
	}
}

const app = new App;
```
```
> DenoTest.exe

```
Next:
```ts
console.log('the app:', app); // just add this at the end of the file
```

And get both messages:
```
> DenoTest.exe
Hello from app
the app: App {}
```

deno 1.6.3 (release, x86_64-pc-windows-msvc)
v8 8.8.294
typescript 4.1.3

**Comment by 00ff0000red** [comment] 2021-01-10 04:10
How does that indicate optimization or abnormal behavior at all?

**Comment by Seally** [comment] 2021-01-10 13:43
May I ask what's supposed to be the issue? Seems the output is exactly what I expected (Node produces the same result). Note that in JS, `new Foo` is the same as `new Foo()` if that's what you're wondering.

**Comment by 00ff0000red** [comment] 2021-01-10 15:20
`new App` should show a log to the console

The first one should've been:
```
> DenoTest.exe
Hello from app
```

the second should be:
```
> DenoTest.exe
Hello from app
the app: App {}
```

OP believes that TS is removing `app` since it's unused.

**Comment by Seally** [comment] 2021-01-10 15:49
In that case, yeah, can confirm the issue. Interestingly, not assigning it to any variable (`new App()` instead of `const app = new App()`) keeps the statement.

The attached code seems to be completely missing:

Source A:

```typescript
class App {
	constructor() {
		console.log('Hello from app')
	}
}

const app = new App();
```

Output A:

<img width="518" alt="missing-code0" src="https://user-images.githubusercontent.com/507710/104127599-95990c80-5395-11eb-8db8-fc80ae7fc673.png">

Source B:

```typescript
class App {
	constructor() {
		console.log('Hello from app')
	}
}

new App();
```

Output B:

<img width="511" alt="missing-code1" src="https://user-images.githubusercontent.com/507710/104127633-d133d680-5395-11eb-9c48-45a3328a2813.png">

**Comment by 00ff0000red** [comment] 2021-01-10 17:14
This can't be TS related, at least I highly doubt it.
So... what could be causing this? Deno compile?

**Comment by LukeChannings** [comment] 2021-01-10 18:00
It's the bundler:

```bash
λ deno bundle ./source_a.ts
Bundle file:///Users/luke/Desktop/source_a.ts
Check file:///Users/luke/Desktop/source_a.ts

λ deno bundle ./source_b.ts
Bundle file:///Users/luke/Desktop/source_b.ts
Check file:///Users/luke/Desktop/source_b.ts
class App {
    constructor(){
        console.log('Hello from app');
    }
}
new App();
```

**Comment by RDambrosio016** [comment] 2021-01-10 18:27
This is seems to be caused by swc's tree shaking. Although perhaps its a bit too agressive since instantiation calls an arbitrary function. cc @kdy1

**Closed** 2021-01-11 14:32 UTC
Labels: bug, swc
