### ISSUE TITLE
`asyncDispose` order oddity in test runner

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#20865] opened 2023-10-10 08:43 UTC
while working with [`using` and `Symbol.asyncDispose`](https://www.typescriptlang.org/docs/handbook/release-notes/typescript-5-2.html#using-declarations-and-explicit-resource-management) in typescript 5.2, i found out that resources using `Symbol.asnycDispose` will not get cleaned in expected order.

## Minimal reproduction

[test-dispose.tar.gz](https://github.com/denoland/deno/files/12854670/test-dispose.tar.gz)

### tmp_path.ts

```ts
const sleep = (ms: number) => new Promise((resolve) => setTimeout(resolve, ms))

export const tmpPath = async (path: string) => {
    await sleep(400)
	await Deno.mkdir(path, { recursive: false })
	console.log(`created: `, path)

	return {
		path,
		async [Symbol.asyncDispose]() {
			await sleep(400)
			await Deno.remove(path, { recursive: false })
			console.log(`disposed: `, path)
		},
	}
}
```

### scope.ts

```ts
import { tmpPath } from "./tmp_path.ts"

await using a = await tmpPath("a")
{
	await using b = await tmpPath(a.path + "/b")
	{
		await using c = await tmpPath(b.path + "/c")

		console.log(c.path)
	}
}
```

output:
```
created:  a
created:  a/b
created:  a/b/c
a/b/c
disposed:  a/b/c
disposed:  a/b
disposed:  a
```

### fn.ts

```ts
import { tmpPath } from "./tmp_path.ts"

await using a = await tmpPath("a")

const fn_b = async () => {
	await using b = await tmpPath(a.path + "/b")
	const fn_c = async () => {
		await using c = await tmpPath(b.path + "/c")

		console.log(c.path)
	}
	await fn_c()
}
await fn_b()
```

output:
```
created:  a
created:  a/b
created:  a/b/c
a/b/c
disposed:  a/b/c
disposed:  a/b
disposed:  a
```

### tmp_path_test.ts

```ts
import { tmpPath } from "./tmp_path.ts"

await using a = await tmpPath("a")
Deno.test("b", async (t) => {
	await using b = await tmpPath(a.path + "/b")
	await t.step("c", async () => {
		await using c = await tmpPath(b.path + "/c")

		console.log("result:", await c.path)
	})
})
```

output:
```
created:  a
disposed:  a
running 1 test from ./tmp_path_test.ts
b ... FAILED (403ms)

 ERRORS 

b => ./tmp_path_test.ts:4:6
error: NotFound: No such file or directory (os error 2): mkdir 'a/b'
        await Deno.mkdir(path, { recursive: false })
        ^
    at async Object.mkdir (ext:deno_fs/30_fs.js:140:3)
    at async tmpPath (file:///home/scarf/repo/wanted/test-dispose/tmp_path.ts:4:2)
    at async file:///home/scarf/repo/wanted/test-dispose/tmp_path_test.ts:5:18

 FAILURES 

b => ./tmp_path_test.ts:4:6

FAILED | 0 passed | 1 failed (405ms)

error: Test failed
```

I think this is probably related to how test runners work in general (same happens in node) and thus unlikely to be fixed, but thought it'd be good to share.

**Comment by lucacasonato** [comment] 2023-10-10 08:50
This is expected. `Deno.test` itself only does test registration. We first run the top level file to find all of the tests, then once the top level file is fully executed, we start running all of the tests.

**Comment by scarf005** [comment] 2023-10-10 08:53
would it mean the recommended way to test such resources would be like this?

```ts
Deno.test("global", async (t) => {
	await using a = await tmpPath("a")
	await t.step("b", async (t) => {
		await using b = await tmpPath(a.path + "/b")
		await t.step("c", async () => {
			await using c = await tmpPath(b.path + "/c")

			console.log("result:", await c.path)
		})
	})
})
```

**Comment by lucacasonato** [comment] 2023-10-11 01:44
I'll close this as working as intended.

**Closed by lucacasonato** 2023-10-11 01:44 UTC
Labels: working as designed
