### ISSUE TITLE
Installation

### ISSUE THREAD

**Issue by Riders004** [denoland/deno#21959] opened 2024-01-16 17:36 UTC
How to install in termux or in Ubuntu linux

**Comment by marvinhagemeister** [comment] 2024-01-19 11:02
Closing as duplicate of https://github.com/denoland/deno/issues/1846 . Once arch64 is available in GitHub Actions we'll likely publish binaries for that too. See the issue for more details.

**Closed by marvinhagemeister** 2024-01-19 11:02 UTC
