### ISSUE TITLE
More granular permissions system

### ISSUE THREAD

**Issue by Jimdooz** [denoland/deno#7271] opened 2020-08-30 16:05 UTC
### Problem revoking a subfolder
Currently you cannot revoke a subfolder permission.
**example :**
```ts
///1. Request permissions needed

const permStatus_1 = await Deno.permissions.request({ name: "read", path: "./folderA"}); //Grant
//Skipped because folderA was granted
const permStatus_2 = await Deno.permissions.request({ name: "read", path: "./folderA/SubFolderA" }); 

console.log(permStatus_1); //Granted
console.log(permStatus_2); //Granted

///2. Remove unused permissions

//Revoke the folderA
await Deno.permissions.revoke({ name: "read", path: "./folderA/SubFolderA" }); 
const permStatus_3 = await Deno.permissions.query({ name: "read", path: "./folderA" });
const permStatus_4 = await Deno.permissions.query({ name: "read", path: "./folderA/SubFolderA" });

console.log(permStatus_3); //Granted
console.log(permStatus_4); //Granted [!] The revocation was not taken into account
```
### Proposition : add the **`recursive`** optional attribute
It's an idea, but I think it might be interesting to consider the permission request of the subfolder, although the permission of parent folder was already granted.
Also, when a revocation is called, revoke all children only if the optional `recursive` parameter has been provided.

```ts
const permStatus_5 = await Deno.permissions.request({ name: "read", path: "./folderA" }); //Grant
//Skipped because folderA was granted, /!\ but add the path to the granted list
const permStatus_6 = await Deno.permissions.request({ name: "read", path: "./folderA/SubFolderA" }); 

console.log(permStatus_5 ); //Granted
console.log(permStatus_6 ); //Granted
```
**without** the `recursive` attribute :
```ts
await Deno.permissions.revoke({ name: "read", path: "./folderA" }); //Revoke the folderA 
const permStatus_7 = await Deno.permissions.query({ name: "read", path: "./folderA" });
const permStatus_8 = await Deno.permissions.query({ name: "read", path: "./folderA/SubFolderA" });

console.log(permStatus_7); //Prompt
console.log(permStatus_8); //Granted
```
**with** the `recursive` attribute :
```ts
await Deno.permissions.revoke({ name: "read", path: "./folderA", recursive: true }); //Revoke the folderA recursively
const permStatus_9 = await Deno.permissions.query({ name: "read", path: "./folderA" });
const permStatus_10 = await Deno.permissions.query({ name: "read", path: "./folderA/SubFolderA" });

console.log(permStatus_9);  //Prompt
console.log(permStatus_10); //Prompt
```

**Comment by nayeemrmn** [comment] 2020-08-30 16:47
So to put this proposal in the language of https://deno.land/manual/runtime/permission_apis#revoke-permissions, the changes would be that:

1. When `Deno.permissions.request(desc)` is called, add `desc` to the set of _explicitly granted permissions descriptors_  even when `desc` is already transitively granted (not currently done in this case). I suppose this is logical.
2. When `Deno.permissions.revoke(desc)` is called, remove only `desc` from the set of _explicitly granted permissions descriptors_ (currently removes anything that `desc` is stronger than as well). The current behaviour is instead invoked by specifiying `{ recursive: true }`.
    -  This is kind of problematic because it changes the signature to
        ```ts
        Deno.permissions.revoke(desc: Deno.PermissionDescriptor & { recursive?: boolean })
        ```
        Then again, there's nothing to comply with because `Deno.permissions.revoke()` was removed from the spec 3 years ago and is therefore non-standard 🤪

**Comment by Jimdooz** [comment] 2020-08-30 18:37
I see.
Would there be a way to ask the user if they want to override the different permissions that are less strong if they exist?
like:
```console
⚠️  Deno found collision while revoking "./folderA". overwrite permissions? [y/n (y = yes, n = no)]
```
This will keep the signature
```ts
Deno.permissions.revoke(desc: Deno.PermissionDescriptor)
```

**Comment by caspervonb** [comment] 2020-09-01 09:40
Duplicate of https://github.com/denoland/deno/issues/378

**Closed** 2021-09-24 05:48 UTC
Labels: permissions, suggestion
