### ISSUE TITLE
Multiple errors while using FS example from STD docs.

### ISSUE THREAD

**Issue by astro-nomize** [denoland/deno#5724] opened 2020-05-21 20:09 UTC
```
C:\Coding3\deno>deno run test/test.js
Compile https://deno.land/std/fs/mod.ts
error: TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:92:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'.
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:103:10

TS2339 [ERROR]: Property 'symlink' does not exist on type 'typeof Deno'.
    await Deno.symlink(originSrcFilePath, dest, {
               ~~~~~~~
    at https://deno.land/std/fs/copy.ts:117:16

TS2339 [ERROR]: Property 'symlink' does not exist on type 'typeof Deno'.
    await Deno.symlink(originSrcFilePath, dest);
               ~~~~~~~
    at https://deno.land/std/fs/copy.ts:121:16

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:127:16

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'.
    Deno.symlinkSync(originSrcFilePath, dest, {
         ~~~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:141:10

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'.
    Deno.symlinkSync(originSrcFilePath, dest);
         ~~~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:145:10

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'.
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:152:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, srcStatInfo.atime, srcStatInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:172:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'.
    Deno.utimeSync(dest, srcStatInfo.atime, srcStatInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std/fs/copy.ts:200:10

TS2339 [ERROR]: Property 'link' does not exist on type 'typeof Deno'.
  await Deno.link(src, dest);
             ~~~~
    at https://deno.land/std/fs/ensure_link.ts:28:14

TS2339 [ERROR]: Property 'linkSync' does not exist on type 'typeof Deno'.
  Deno.linkSync(src, dest);
       ~~~~~~~~
    at https://deno.land/std/fs/ensure_link.ts:52:8

TS2339 [ERROR]: Property 'symlink' does not exist on type 'typeof Deno'.
    await Deno.symlink(src, dest, {
               ~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:33:16

TS2339 [ERROR]: Property 'symlink' does not exist on type 'typeof Deno'.
    await Deno.symlink(src, dest);
               ~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:37:16

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'.
    Deno.symlinkSync(src, dest, {
         ~~~~~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:65:10

TS2339 [ERROR]: Property 'symlinkSync' does not exist on type 'typeof Deno'.
    Deno.symlinkSync(src, dest);
         ~~~~~~~~~~~
    at https://deno.land/std/fs/ensure_symlink.ts:69:10

Found 16 errors.
```
Code used:
```javascript
import { exists, existsSync } from "https://deno.land/std/fs/mod.ts";

exists("./foo"); // returns a Promise<boolean>
existsSync("./foo"); // returns boolean
```

**Comment by rafaelferres** [comment] 2020-05-22 02:24
Add --unstable to Deno's run.

 `deno run --allow-all --unstable teste.ts`

**Comment by kitsonk** [comment] 2020-05-22 02:33
Duplicate of #5175 

Please use the search functionality to avoid opening duplicate issues.

**Comment by astro-nomize** [comment] 2020-05-22 03:35
> Add --unstable to Deno's run.
> 
> `deno run --allow-all --unstable teste.ts`
This does not change anything, it still has the same errors.

**Comment by rafaelferres** [comment] 2020-05-22 19:49
What version of your Deno is it? Try using a 1.0.0

**Closed** 2020-05-22 19:52 UTC
