### ISSUE TITLE
CLI: each input leads to a warning msg "WARN RS - rustyline:718 - cannot read initial cursor location"

### ISSUE THREAD

**Issue by Shangbaize-Daoye** [denoland/deno#6641] opened 2020-07-05 12:47 UTC
OS is Ubuntu 20.04
```
cat /etc/os-release
NAME="Ubuntu"
VERSION="20.04 LTS (Focal Fossa)"
ID=ubuntu
ID_LIKE=debian
PRETTY_NAME="Ubuntu 20.04 LTS"
VERSION_ID="20.04"
```
**Each time when inputing something in CLI, I got a msg "WARN RS - rustyline:718 - cannot read initial cursor location".**
```
$ deno
Deno 1.1.3
exit using ctrl+d or close()
WARN RS - rustyline:718 - cannot read initial cursor location
> "hello"
hello
WARN RS - rustyline:718 - cannot read initial cursor location
> "world"
world
WARN RS - rustyline:718 - cannot read initial cursor location
>
```
Source code for that warning:
```rust
From "https://github.com/kkawakam/rustyline/blob/master/src/tty/unix.rs"

    fn move_cursor_at_leftmost(&mut self, rdr: &mut PosixRawReader) -> Result<()> {
        if rdr.poll(0)? != 0 {
            debug!(target: "rustyline", "cannot request cursor location");
            return Ok(());
        }
        /* Report cursor location */
        self.write_and_flush(b"\x1b[6n")?;
        /* Read the response: ESC [ rows ; cols R */
        if rdr.poll(100)? == 0
            || rdr.next_char()? != '\x1b'
            || rdr.next_char()? != '['
            || read_digits_until(rdr, ';')?.is_none()
        {
            warn!(target: "rustyline", "cannot read initial cursor location");
            return Ok(());
        }
        let col = read_digits_until(rdr, 'R')?;
        debug!(target: "rustyline", "initial cursor location: {:?}", col);
        if col.is_some() && col != Some(1) {
            self.write_and_flush(b"\n")?;
        }
        Ok(())
    }
```
Don't know how this comes up but I always get that warning on my own server. OS was upgraded from 18.04 to 20.04 online.
However, on another machine with newly installed Ubuntu 20.04, this problem nerver happens. Can't reproduce it on the second machine.

**Not familiar with Rust, what I want to know is:**
- **1. Possible causes of that warning "WARN RS - rustyline:718 - cannot read initial cursor location".**
- **2. How could I solve that?**

Thanks for any useful help! :D

**Comment by bartlomieju** [comment] 2020-07-14 13:18
I'm not sure, but it seems that our filter level for log is wrong and allows for `WARN` messages to be shown in addition to `ERROR`. Marking as "help wanted" as it should be straight-forward to repeat and track the problem down for anyone wanting to play with Rust.

**Comment by brendanboyle87** [comment] 2020-07-21 00:51
I'd like to take this issue. Should be able to just up the log level to warn when no log_level flag is provided here -> 

https://github.com/denoland/deno/blob/master/cli/main.rs#L697
`let log_level = match flags.log_level {
    Some(level) => level,
    None => Level::Info, // Default log level
  };
  log::set_max_level(log_level.to_level_filter());`

**Comment by brendanboyle87** [comment] 2020-07-21 01:36
Opened a PR above, happy to update a test but I am new to the project/Rust and was struggling to find the right place to test an update to the main.rs file.

**Comment by JayHelton** [comment] 2020-08-04 13:32
@brendanboyle87 Are you actively working on this?

**Comment by brendanboyle87** [comment] 2020-09-02 21:24
@JayHelton Apologies for not responding, missed the email. Looks like there is a PR working on it now, the change I made ended up affecting the output of certain expected warnings/failing some tests and being new to the project/Rust was a bit over my head.

**Comment by bartlomieju** [comment] 2020-09-05 11:15
Tried with `Deno v1.3.3` and can't reproduce. Closing as resolved.

**Comment by tokiedokie** [comment] 2020-09-08 00:37
I still get this error

build from source and run
```
❯ ./target/debug/deno
Deno 1.3.3
exit using ctrl+d or close()
> 
WARN RS - rustyline:718 - cannot read initial cursor location
> 
WARN RS - rustyline:718 - cannot read initial cursor location
> 
WARN RS - rustyline:718 - cannot read initial cursor location
>
```

**Comment by bartlomieju** [comment] 2020-09-08 09:31
@tokiedokie what system are you on? I cannot repeat this problem on macOS

**Comment by Shangbaize-Daoye** [comment] 2020-09-08 13:55
@bartlomieju  I bought a VPS on hostwinds and installed Ubuntu 18.04. Everything's ok on that server but when I upgraded OS from 18.04 to 20.04  online with following CMDs, that error occured on upgraded Ubuntu 20.04.
```
sudo apt install update-manager-core
sudo do-release-upgrade -m server -d
```
The error can be reproduced through such a process from scratch on hostwinds server.
Strangely though, on original Ubuntu 20.04 installed from Ubuntu official image, this error did not occur.

**Comment by bartlomieju** [comment] 2020-09-08 14:00
@Shangbaize-Daoye what's Deno version that causes this output?

**Comment by Shangbaize-Daoye** [comment] 2020-09-08 14:04
@bartlomieju current Deno 1.3.3, I reproduced the error the other day

**Comment by tokiedokie** [comment] 2020-09-08 23:33
@bartlomieju I use WSL2 ubuntu

![deno-readline](https://user-images.githubusercontent.com/42903136/92537420-0b218e80-f277-11ea-8d4a-916b238395fe.gif)

**Comment by caspervonb** [comment] 2020-09-17 05:47
Getting this on my ubuntu server as of recently, it comes and goes appearantly...

**Closed** 2020-09-17 18:38 UTC
Labels: bug, cli, good first issue
