### ISSUE TITLE
`deno publish --dry-run` requires `--token` in pre-commit hook

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#22768] opened 2024-03-07 12:46 UTC
I'm running `deno publish --dry-run` in a `deno task` in a `pre-commit` hook.

When I run the `deno task` directly, this works. When it is run by the hook, however, it fails with the following error:

```
error: No means to authenticate. Pass a token to `--token`.
````

I feel like you should never need to pass `--token` when using `--dry-run`.

Currently, I work-around this issue by adding a fake token, e. g. `deno publish --dry-run --token=dry-run`

---

Deno 1.41.1, Windows 11

**Comment by lucacasonato** [comment] 2024-03-07 16:39
Duplicate of #22658

It's fixed in canary already.

**Closed by lucacasonato** 2024-03-07 16:39 UTC
Labels: bug, publish
