### ISSUE TITLE
Deno 1.32.2 hangs when run and then crashes with OOM error

### ISSUE THREAD

**Issue by lpil** [denoland/deno#18648] opened 2023-04-09 21:44 UTC
Hello!

Today I've returned to my computer (aarch64 macOS 13.1) and now if I run `deno` in the terminal it hangs for about 40 seconds before the shell starts. Once the shell it present it works and feels normal, but then the program entirely crashes with an OOM error 5 to 10 seconds later.

```
Deno 1.32.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> 1
1
> 2
2
<--- Last few GCs --->

[626:0x110040000]    57466 ms: Scavenge 1373.0 (1423.1) -> 1372.2 (1433.1) MB, 3.12 / 0.00 ms  (average mu = 0.831, current mu = 0.711) allocation failure;
[626:0x110040000]    57487 ms: Scavenge 1378.1 (1433.1) -> 1376.2 (1434.4) MB, 4.08 / 0.00 ms  (average mu = 0.831, current mu = 0.711) allocation failure;
[626:0x110040000]    57622 ms: Scavenge 1379.7 (1434.4) -> 1378.2 (1453.4) MB, 123.38 / 0.00 ms  (average mu = 0.831, current mu = 0.711) allocation failure;


<--- JS stacktrace --->


#
# Fatal javascript OOM in Reached heap limit
#

fish: Job 1, 'deno' terminated by signal SIGTRAP (Trace or breakpoint trap)
```

I have not knowningly changed my computer at all since when I last used Deno on this machine a few days ago.

If I run `deno --log-level=debug` it prints many many lines like this before it crashes:

```
DEBUG RS - deno::npm::resolvers:144 - Resolved package folder of file:///Users/louis/Library/Caches/deno/npm/registry.npmjs.org/fp-ts/2.13.1/es6/Pointed.d.ts to /Users/louis/Library/Caches/deno/npm/registry.npmjs.org/fp-ts/2.13.1
DEBUG RS - deno::npm::resolvers:144 - Resolved package folder of file:///Users/louis/Library/Caches/deno/npm/registry.npmjs.org/fp-ts/2.13.1/es6/Predicate.d.ts to /Users/louis/Library/Caches/deno/npm/registry.npmjs.org/fp-ts/2.13.1
DEBUG RS - deno::npm::resolvers:144 - Resolved package folder of file:///Users/louis/Library/Caches/deno/npm/registry.npmjs.org/fp-ts/2.13.1/es6/Refinement.d.ts to /Users/louis/Library/Caches/deno/npm/registry.npmjs.org/fp-ts/2.13.1
```

Here is the full log: [deno-log.txt](https://github.com/denoland/deno/files/11186372/deno-log.txt)

If I move `~/Library/Caches/deno/npm` to a new location it no longer crashes, but it still takes 6 seconds to start the shell.

Here is the logs for when that happens:

```
$ time deno --log-level=debug
DEBUG RS - deno::args::package_json:147 - No package.json file found
DEBUG RS - deno::cache::cache_db:129 - Opening cache /Users/louis/Library/Caches/deno/dep_analysis_cache_v1...
DEBUG RS - deno::cache::cache_db:129 - Opening cache /Users/louis/Library/Caches/deno/node_analysis_cache_v1...
DEBUG RS - deno::js:10 - Deno isolate init with snapshots.
DEBUG JS - args []
DEBUG RS - deno::args::package_json:147 - No package.json file found
DEBUG RS - deno_runtime::permissions:58 - ⚠️️  Granted net access to "deno.land"
DEBUG RS - deno::file_fetcher:342 - FileFetcher::fetch_remote() - specifier: https://deno.land/.well-known/deno-import-intellisense.json
DEBUG RS - deno_runtime::permissions:58 - ⚠️️  Granted net access to "deno.land"
DEBUG RS - deno::file_fetcher:245 - FileFetcher::fetch_cached - specifier: https://deno.land/.well-known/deno-import-intellisense.json
Deno 1.32.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
>

________________________________________________________
Executed in    6.07 secs    fish           external
   usr time    6.66 secs    0.08 millis    6.66 secs
   sys time    0.29 secs    1.72 millis    0.29 secs
```

Do let me know what else I can do to help debug!

Thanks,
Louis

edit: I mistaken when I said removing the npm cache directory fixed it, it seems to instead be based upon what my working directory is. If I'm in my home directory it crashes, but if I'm in the `~/Library/Caches/deno` it starts the shell in 6 seconds and uses 2.52GB of memory at start. If I run it in a new directory it starts near instantly and uses 54MB.

edit 2: 1.32.3 does not have this problem, but I had to manually upgrade. `brew` doesn't have this for some reason.

**Comment by dsherret** [comment] 2023-04-09 22:39
It's fixed in 1.32.3. Homebrew release is temporarily broken https://github.com/denoland/deno/issues/18608

Duplicate of https://github.com/denoland/deno/issues/18538 , https://github.com/denoland/deno/issues/18540 , https://github.com/denoland/deno/issues/18615

**Closed by dsherret** 2023-04-09 22:39 UTC
Labels: duplicate
