### ISSUE TITLE
feat: Support UNIX timestamp

### ISSUE THREAD

**Issue by idanran** [denoland/deno#14476] opened 2022-05-03 15:21 UTC
Hi, there, it would be better if we supported it

example:
```js
Deno.unixTimestamp() \\ 1632847927.599013
```

**Comment by lucacasonato** [comment] 2022-05-03 15:39
No, we should instead implement `performance.timeOrigin`, because you can get a high precision unix timestamp with `performance.timeOrigin + performance.now()`. Thus duplicate of #10837.

**Closed by lucacasonato** 2022-05-03 15:39 UTC

**Comment by idanran** [comment] 2022-05-03 15:45
> No, we should instead implement `performance.timeOrigin`, because you can get a high precision unix timestamp with `performance.timeOrigin + performance.now()`. Thus duplicate of #10837.

thanks
