### ISSUE TITLE
cannot receive `HandleScope` in `#[op]` when function is async.

### ISSUE THREAD

**Issue by sahandevs** [denoland/deno#15375] opened 2022-08-01 18:42 UTC
Hi! While we can get a scope when the `#[op]` is not `async`:

```rust
#[op(v8)]
fn op_my_op(scope: &mut deno_core::v8::HandleScope) { /* OK */ }
```

we can't do the same with `async` functions:
```rust
#[op(v8)]
async fn op_my_op(scope: &mut deno_core::v8::HandleScope) { /* Compile Error */ }
```

is there any particular reason for this? if so, are there any workarounds to get a scope here?

Thanks!

**Comment by littledivy** [comment] 2022-08-02 03:22
Async function outlives the function scope so Rust will correctly prevent you from using it in the async block. One way to do this safely is to use hybrid ops:
```rust
#[op(v8)]
fn op_my_op(
  scope: &mut v8::HandleScope,
  a: serde_v8::Value,
) -> Result<impl Future<Output = Result<T, AnyError>> + 'static, AnyError> {
   // You can use the HandleScope here.
   // Ideally, create owned Rust values to pass into the async block below.
   let i: i32 = a.v8_value.int32_value(scope);
   Ok(async move {
      // .. 
   })
}
```

**Comment by penberg** [comment] 2022-09-20 07:09
@littledivy The hybrid op solution works great if you have the sync part first. However, if you want to return `serde_v8::Value` that no longer works because now the async part is first, but you don't want to block on it. One solution to the problem is to split the op into two ops: (1) async op that returns a future on a resource ID and (2) a sync op that turns the resource ID into a `serde_v8::Value`. But this does feel bit clumsy to be honest. I wonder if there's a way to make `HandleScope` lifetime extend to the lifetime of the returned future?

**Comment by littledivy** [comment] 2022-09-20 07:16
Returning `serde_v8::Value` means the HandleScope needs to be around. 

Note that we are in a Rust future, that means it will execute sometime in the future...even maybe after the scope is deallocated. So, the lifetimes are there for a good reason. 

The correct (& safe) way is to return owned Rust values. `deno_core` (using `serde_v8`) is deserialize them into V8 values when resolving the async promise.

**Comment by littledivy** [comment] 2024-06-13 12:02
Closing as the original question seems to be answered; FYI op macro was rewritten and code has moved to `denoland/deno_core`

**Closed by littledivy** 2024-06-13 12:02 UTC
Labels: custom runtime
