### ISSUE TITLE
When `--inspect` is passed, wait until connection before running?

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#12417] opened 2021-10-13 00:53 UTC
There are situations in `vscode` where when the code is launched with `--inspect`, Deno runs the program and exits before the vscode debugger can connect, causing problems with being able to debug code where a breakpoint is set. (see: denoland/vscode_deno#557)

Is there a logical way to not run code when `--inspect` is provided until a client is connected on the port?  This is different than `--inspect-brk` where the code breaks at the first point, it would be to give time for a client to connect and provide break-points.

**Comment by devmattrick** [comment] 2021-10-17 08:01
For me, even using `--inspect-brk` exits immediately in VSCode's debugger.

**Comment by kitsonk** [comment] 2021-12-07 01:12
ok, need to check what the behaviour is when debugging NodeJS applications in VSCode and if not using `--inspect-brk` just "dumps" without starting the debug tools like it does in Deno then.

**Comment by bartlomieju** [comment] 2021-12-23 18:27
I did some digging into this issue an here's what I found:

1. I created 3 files (`node.js`, `deno.js`, `deno.ts`), each of the files just prints a console statement:
```js
console.log("Hello from {name}");
```
2. For each of the files I opened debugger pane and clicked "Run and Debug", selecting default debugger options (either `Node` or `Deno`)
![Screenshot 2021-12-23 at 19 24 09](https://user-images.githubusercontent.com/13602871/147278817-08a45697-ccae-4d08-96f0-d3d1ed4b64df.png)
3. The result are as follows:
- `node.js`
![Screenshot 2021-12-23 at 19 25 02](https://user-images.githubusercontent.com/13602871/147278878-d76c2b08-8b6f-464e-b04c-a8c61dec3b2a.png)
- `deno.js`
![Screenshot 2021-12-23 at 19 25 28](https://user-images.githubusercontent.com/13602871/147278986-9b473840-d069-4ccc-8855-2adeeb0110a1.png)
- `deno.ts`
![Screenshot 2021-12-23 at 19 26 05](https://user-images.githubusercontent.com/13602871/147278969-8e98a05a-a0fd-4e88-9ec2-c12d1d67767b.png)

As can be seen in the screen shots, neither `deno.js` nor `deno.ts` print out the message to the console. I'm 90% sure this is caused by https://github.com/denoland/deno/issues/13006

**Comment by bartlomieju** [comment] 2021-12-23 19:30
So I fixed the (IMO) underlying issue in https://github.com/denoland/deno/pull/13191 but when I try to run the same code in VSCode there's still no output. It does seem like the process is starting, but nothing shows up in the `Debug console`... @kitsonk do you have any idea if there's some special handling required for messages to show in that console? Maybe we need to redirect stdio of the spawned process somewhere?

**Comment by kitsonk** [comment] 2021-12-24 01:28
I haven't tried the branch, but a recent build off master demonstrates that with `--inspect-brk` the console output gets sent to the console, just like with Node, so if it isn't behaving exactly like Node.js, something else is amiss.

![ins_js_—_scratch](https://user-images.githubusercontent.com/1282577/147304726-7bf31650-9d4e-4d7f-8621-005c26924556.png)

**Comment by bartlomieju** [comment] 2021-12-24 09:20
It does work for me with `--inspect-brk` too (ie. breakpoint is set and execution pauses); what concerns me is that it doesn't work with just `--inspect`.

I will add debug logging to Deno's inspector and see what messages are being exchanged between the binary and VSCode.

**Comment by kitsonk** [comment] 2021-12-24 09:48
I am sure it is the same if you use `about:inspect` in Chrome.  With `--inspect-brk` I see Deno in `about:inspect` and can connect to it.  I am going to try with `--inspect`.

**Comment by bartlomieju** [comment] 2021-12-24 10:04
> I am sure it is the same if you use `about:inspect` in Chrome. With `--inspect-brk` I see Deno in `about:inspect` and can connect to it. I am going to try with `--inspect`.

For both Node and Deno I don't see any targets in `chrome://inspect` - but that's expected IMO, since the code finishes immediately.

**Comment by kitsonk** [comment] 2021-12-24 10:05
Ok, I checked out the branch... if I do this:

```js
console.log("hello");
```

I don't get anything in the output, just like expected, but if I do:

```js
console.log("hello");

await new Promise((res) => {
  setTimeout(() => {
    console.log("deno");
    res();
  }, 5000);
});
```

Then there is enough time to connect to the inspector port and get the information and I see both lines logged to the console.  So I am not sure the waiting is actually working properly in #13191 or at least it isn't working in a way that exhibits the same behaviour as Node, or Deno is just that much faster.

**Comment by bartlomieju** [comment] 2021-12-24 10:08
My other suspicion is that VSCode debugger integration requires some special handling, however I haven't found anything yet in the docs about it. Anyway, something to look into after Christmas.

**Comment by kitsonk** [comment] 2021-12-24 10:22
Well it doesn't... because if the program takes a bit longer, then everything works fine.  For example, on my local machine, using a build of #13191 this works:

```js
console.log("hello");

await new Promise((res) => {
  setTimeout(() => {
    console.log("deno");
    res(undefined);
  }, 750);
});
```

But this behaves with the "blank" behaviour... the "red bar" never appears:

```
console.log("hello");

await new Promise((res) => {
  setTimeout(() => {
    console.log("deno");
    res(undefined);
  }, 500);
});
```

This is my `launch.json`:

```jsonc
{
  "version": "0.2.0",
  "configurations": [
    {
      "request": "launch",
      "name": "Launch Program",
      "type": "pwa-node",
      "program": "${workspaceFolder}/ins.ts",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "deno",
      "runtimeArgs": [
        "run",
        "--inspect",
      ],
      "attachSimplePort": 9229
    }
  ]
}
```

**Comment by bartlomieju** [comment] 2021-12-24 10:30
So, should we just agree that "we're too fast" in the simplest cases and this works as expected?

**Comment by kitsonk** [comment] 2021-12-24 10:50
Yeah, because I just tried with Node 15 using:

```jsonc
{
  "version": "0.2.0",
  "configurations": [
    {
      "request": "launch",
      "name": "Launch Program",
      "type": "pwa-node",
      "program": "${workspaceFolder}/ins.mjs",
      "cwd": "${workspaceFolder}",
      "runtimeExecutable": "node",
      "runtimeArgs": [
        "--inspect",
      ],
      "attachSimplePort": 9229
    }
  ]
}
```

An got the same behaviour... a "blank" debug until I increased the timeout.

**Comment by bartlomieju** [comment] 2021-12-25 22:53
Thanks for checking it. I will update the manual page accordingly and close this issue then.

**Comment by bartlomieju** [comment] 2022-01-10 02:12
I'm going to close this issue now that denoland/manual#201 is open.

**Closed by bartlomieju** 2022-01-10 02:12 UTC
Labels: suggestion, inspector
