### ISSUE TITLE
`ArrayBuffer.prototype.transfer` types missing

### ISSUE THREAD

**Issue by Enva2712** [denoland/deno#25993] opened 2024-10-02 14:21 UTC
Version: Deno 2.0.0-rc.9

the following lib interface is implemented in the runtime but not included: https://github.com/microsoft/TypeScript/blob/ca18009b8bd5cea6a7fbcba3d7e4dd3c4633bc92/src/lib/es2024.arraybuffer.d.ts#L35

as a result this runs successfully but fails typechecking: `new ArrayBuffer(0).transfer()`

**Comment by petamoriken** [comment] 2024-10-03 07:11
The ES2024 type will be introduced in TypeScript 5.7. Please wait.

**Comment by petamoriken** [comment] 2024-10-03 07:41
related #19191

**Comment by lucacasonato** [comment] 2024-10-03 13:00
Closing as effective dupe of https://github.com/denoland/deno/issues/19191

**Closed by lucacasonato** 2024-10-03 13:00 UTC
