### ISSUE TITLE
deno run: panic sometimes when using --allow-read

### ISSUE THREAD

**Issue by behnam-oneschema** [denoland/deno#23292] opened 2024-04-09 03:54 UTC
The docs specify `--allow-read` as taking values *optionally*:
```
--allow-read[=<PATH>...]
```

Looks like the impl for this is causing panics in `deno run` under certain circumstances. Here are a few cases happening for me:

Case 1)
```
≥ deno task start
Task start deno run --allow-read main.ts --allow-net --watch

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.42.1
Args: ["~/.deno/bin/deno", "run", "--allow-read", "main.ts", "--allow-net", "--watch"]

thread 'main' panicked at /Users/runner/work/deno/deno/runtime/permissions/lib.rs:695:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Case 2)
```
≥ deno task start
Task start deno run --allow-read main.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.42.1
Args: ["~/.deno/bin/deno", "run", "--allow-read", "main.ts"]

thread 'main' panicked at /Users/runner/work/deno/deno/runtime/permissions/lib.rs:695:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Case 3)
```
≥ deno task start
Task start deno run main.ts --allow-read
Permission flags have likely been incorrectly set after the script argument.
To grant permissions, set them before the script argument. For example:
    deno run --allow-read=. main.js

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.42.1
Args: ["~/.deno/bin/deno", "run", "main.ts", "--allow-read"]

thread 'main' panicked at /Users/runner/work/deno/deno/runtime/permissions/lib.rs:695:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

Of course, as noted in the warning in Case 3, `--allow-read` should go before the `main.ts` argument. However, still the panic is probably unexpeced, similar to the previous cases.

----

With backtrace:
```
≥ RUST_BACKTRACE=full deno task start
Task start deno run --allow-read main.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.42.1
Args: ["~/.deno/bin/deno", "run", "--allow-read", "main.ts"]

thread 'main' panicked at /Users/runner/work/deno/deno/runtime/permissions/lib.rs:695:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
stack backtrace:
   0:        0x1042d1025 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd71adb7a72f4105
   1:        0x103172023 - core::fmt::write::h30346430340bc336
   2:        0x10429d26e - std::io::Write::write_fmt::heb3d6316c565d5b1
   3:        0x1042d3d59 - std::sys_common::backtrace::print::h67e51ff2e3d5cfbd
   4:        0x1042d3642 - std::panicking::default_hook::{{closure}}::hc666c9a55318d1f1
   5:        0x1042d3200 - std::panicking::default_hook::hf980b1da49948523
   6:        0x102fa4ac2 - deno::setup_panic_hook::{{closure}}::h0fa65b334405b2e8
   7:        0x1042d4312 - std::panicking::rust_panic_with_hook::h683bce980186bbbe
   8:        0x1042d40b4 - std::panicking::begin_panic_handler::{{closure}}::ha6dbd11ba0ec8af1
   9:        0x1042d4009 - std::sys_common::backtrace::__rust_end_short_backtrace::h889430bddc786c98
  10:        0x1042d3ff2 - _rust_begin_unwind
  11:        0x105b46fe5 - core::panicking::panic_fmt::hff768cef35397791
  12:        0x105b47555 - core::result::unwrap_failed::h951d84d71b0bada2
  13:        0x103c49326 - deno_net::ops::op_net_listen_tcp<NP>::v8_fn_ptr::h15d905d3b349c003
```

----

And the ineffective case:
```
≥ RUST_BACKTRACE=full deno task start
Task start deno run main.ts --allow-read
Permission flags have likely been incorrectly set after the script argument.
To grant permissions, set them before the script argument. For example:
    deno run --allow-read=. main.js

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.42.1
Args: ["~/.deno/bin/deno", "run", "main.ts", "--allow-read"]

thread 'main' panicked at /Users/runner/work/deno/deno/runtime/permissions/lib.rs:695:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
stack backtrace:
   0:        0x1019aa025 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hbd71adb7a72f4105
   1:        0x10084b023 - core::fmt::write::h30346430340bc336
   2:        0x10197626e - std::io::Write::write_fmt::heb3d6316c565d5b1
   3:        0x1019acd59 - std::sys_common::backtrace::print::h67e51ff2e3d5cfbd
   4:        0x1019ac642 - std::panicking::default_hook::{{closure}}::hc666c9a55318d1f1
   5:        0x1019ac200 - std::panicking::default_hook::hf980b1da49948523
   6:        0x10067dac2 - deno::setup_panic_hook::{{closure}}::h0fa65b334405b2e8
   7:        0x1019ad312 - std::panicking::rust_panic_with_hook::h683bce980186bbbe
   8:        0x1019ad0b4 - std::panicking::begin_panic_handler::{{closure}}::ha6dbd11ba0ec8af1
   9:        0x1019ad009 - std::sys_common::backtrace::__rust_end_short_backtrace::h889430bddc786c98
  10:        0x1019acff2 - _rust_begin_unwind
  11:        0x10321ffe5 - core::panicking::panic_fmt::hff768cef35397791
  12:        0x103220555 - core::result::unwrap_failed::h951d84d71b0bada2
  13:        0x101322326 - deno_net::ops::op_net_listen_tcp<NP>::v8_fn_ptr::h15d905d3b349c003
```

**Comment by lucacasonato** [comment] 2024-06-08 18:23
Duplicate of #23294

**Closed by lucacasonato** 2024-06-08 18:23 UTC
