### ISSUE TITLE
Regex Unicode category matching throws

### ISSUE THREAD

**Issue by ilpoo** [denoland/deno#2126] opened 2019-04-16 13:11 UTC
Regular expressions that include a Unicode category matcher throw an error, while they work fine in Node and in Chrome.

Example:
```javascript
"0a".match(/\p{L}/u);
```
Expected output:
```javascript
[ 'a', index: 1, input: '0a', groups: undefined ]
```
Actual output: 
```javascript
<unknown>:1:5
"0a".match(/\p{L}/u)
     ^
Uncaught SyntaxError: Invalid regular expression: /\p{L}/: Invalid property name
    at <unknown>:1:6
    at evaluate (js/repl.ts:87:34)
    at replLoop (js/repl.ts:145:13)
```

I brought this up on Gitter and it was suspected to be due to the lack of ICU.

**Comment by ry** [comment] 2019-04-16 16:19
Yeah - we don't use ICU.

**Comment by zekth** [comment] 2019-04-16 16:38
Ref: https://github.com/denoland/deno/issues/1968

**Comment by ry** [comment] 2019-04-16 19:17
duplicate of #1968

**Closed by ry** 2019-04-16 19:17 UTC
