### ISSUE TITLE
tanstack libraries types resolved to `any`

### ISSUE THREAD

**Issue by scarf005** [denoland/deno#27157] opened 2024-11-29 22:55 UTC
Version: Deno 2.1.2, extension 3.42.0, vscode 1.95.3

![image](https://github.com/user-attachments/assets/e3eb9ea0-3d4c-497b-b75b-40872d58d8f9)

on vscode_deno, [@tanstack/solidjs-query](https://tanstack.com/query/latest/docs/framework/solid/overview) and all other `@tanstack/*` family libraries fails to typecheck correctly.

```
scarf@fedora /r/m/h/s/r/e/tanstack-is-any (main) [1]> deno check main.ts
Check file:///run/media/home/scarf/repo/etc/tanstack-is-any/main.ts
error: TS2559 [ERROR]: Type 'string' has no properties in common with type 'OmitKeyof<QueryObserverOptions<unknown, Error, unknown, unknown, QueryKey, never>, "queryKey">'.
    queries: "ㅁㅇㄴㄹㅁㄴㄹㅇ",
    ~~~~~~~
    at file:///run/media/home/scarf/repo/etc/tanstack-is-any/main.ts:5:5
```

however `deno check` works normally.

![image](https://github.com/user-attachments/assets/e3930984-2229-47ef-9b58-8e0cf8292651)

it looks like vscode_deno cannot typecheck NPM imports inside NPM imports.

server log:

```
shutdown request received, shutting down
exit notification received, stopping
Starting Deno language server...
  version: 2.1.2 (release, x86_64-unknown-linux-gnu)
  executable: /var/home/scarf/.local/share/deno/bin/deno
Connected to "Visual Studio Code" 1.95.3
Enabling import suggestions for: https://deno.land/
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///run/media/home/scarf/repo/etc/tanstack-is-any/deno.json"
  Resolved lockfile: "file:///run/media/home/scarf/repo/etc/tanstack-is-any/deno.lock"
Server ready.
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///run/media/home/scarf/repo/etc/tanstack-is-any/deno.json"
  Resolved lockfile: "file:///run/media/home/scarf/repo/etc/tanstack-is-any/deno.lock"
```

reproduction project: [tanstack-is-any.tar.gz](https://github.com/user-attachments/files/17963417/tanstack-is-any.tar.gz)

**Comment by dsherret** [comment] 2024-11-30 00:00
Maybe try running with `deno check --all <filename>`

**Comment by scarf005** [comment] 2024-11-30 01:09
> Maybe try running with `deno check --all <filename>`. It might reveal the source of the `any` types.

i'll try (outside atm), but it looks like to me that `deno check` works correctly here: 
1. `deno check` correctly type checked that interface `defaultOptions.queries` cannot be assigned string (object expected)
2. whereas vscode_deno incorrectly marked `defaultOptions.queries` as `any` , thus no error squiggly line.

as seen on second screenshot, judging by 1. and 2. it seems like `vscode_deno` cannot resolve library(e.g `@tanstack/solid-query`) peerDependencies (e.g `solid-js`).

i've also made sure i didn't set up global `deno.config` in my `settings.json` and had no workspace settings to alter vscode_deno behavior.

**Comment by scarf005** [comment] 2024-11-30 04:17
```
scarf@fedora /r/m/h/s/r/e/tanstack-is-any> deno check --all main.ts
Check file:///run/media/home/scarf/repo/etc/tanstack-is-any/main.ts
error: TS2559 [ERROR]: Type 'string' has no properties in common with type 'OmitKeyof<QueryObserverOptions<unknown, Error, unknown, unknown, QueryKey, never>, "queryKey">'.
    queries: "ㅁㅇㄴㄹㅁㄴㄹㅇ",
    ~~~~~~~
```

**Comment by scarf005** [comment] 2024-12-01 15:47
> Maybe try running with `deno check --all <filename>`. It might reveal the source of the `any` types.

@dsherret to be clear, i don't think `deno check --all` would work in this case because the error only happens on vscode deno, not deno cli. could this issue be moved to https://github.com/denoland/vscode_deno/?

**Comment by nathanwhit** [comment] 2024-12-02 18:32
Oh bizzare, I originally couldn't reproduce the issue, but I noticed I can if I go-to definition on the `queries` property:


https://github.com/user-attachments/assets/3d095318-e157-4eef-b0ae-d49283dedb1d

It seems like loading opening the definition file in the editor borks the type resolution.

**Comment by nayeemrmn** [comment] 2024-12-19 02:02
Closing in favour of #27291.

**Closed by nayeemrmn** 2024-12-19 02:02 UTC
Labels: bug, lsp
