### ISSUE TITLE
Unable to bundle TS code that uses the DOM.

### ISSUE THREAD

**Issue by renatoathaydes** [denoland/deno#8177] opened 2020-10-28 21:45 UTC
**Describe the bug**

Unable to bundle TS code that uses the DOM.

**To Reproduce**

1. Create a `test.ts` file with contents:

```ts
document.getElementById("comments-container");
```

2. Create `tsconfig.json` with contents:

```json
{
  "compilerOptions": {
    "target": "ES2016",
    "module": "commonjs",
    "lib": ["DOM", "ESNext"],
    "esModuleInterop": true,
    "skipLibCheck": true,
    "forceConsistentCasingInFileNames": true
  }
}
```

3. Run the `deno bundle` command:

```bash
deno bundle --unstable -c tsconfig.json test.ts dist/test.js
```

This will fail with the following error:

```
Bundle file:///Users/renato/programming/projects/static-website-reddit-comments/test.ts
Check file:///Users/renato/programming/projects/static-website-reddit-comments/test.ts
error: AssertionError: "data" is unexpectedly null for "asset:///lib.dom.d.ts".
    at assert (deno:cli/tsc/99_main_compiler.js:53:13)
    at Object.getSourceFile (deno:cli/tsc/99_main_compiler.js:377:9)
    at findSourceFile (deno:cli/tsc/00_typescript.js:104355:29)
    at deno:cli/tsc/00_typescript.js:104232:85
    at getSourceFileFromReferenceWorker (deno:cli/tsc/00_typescript.js:104199:34)
    at processSourceFile (deno:cli/tsc/00_typescript.js:104232:13)
    at processRootFile (deno:cli/tsc/00_typescript.js:104055:13)
    at deno:cli/tsc/00_typescript.js:103004:25
    at Object.forEach (deno:cli/tsc/00_typescript.js:382:30)
    at Object.createProgram (deno:cli/tsc/00_typescript.js:103003:24)
```

**Expected behavior**

The `Deno bundle` command should succeed.

It worked before I upgraded to 1.5.0.

**Versions**

```
▶ deno --version
deno 1.5.0
v8 8.7.220.3
typescript 4.0.3
```

**Comment by kitsonk** [comment] 2020-10-29 03:48
Duplicate of #8147 (which is fixed in master an will be part of 1.5.1).

**Closed by kitsonk** 2020-10-29 03:48 UTC
