### ISSUE TITLE
Is deno a virus?

### ISSUE THREAD

**Issue by Libertas007** [denoland/deno#10819] opened 2021-06-02 09:25 UTC
Hello,
today, I was upgrading deno with `deno upgrade` and my antivirus (Avast) made popups. One of them said something like _We've protected **deno.exe** because it was acting suspiciously._ and _Threat blocked. We've blocked **UNP244220764.TMP** because we've founded that it's infected by **IDP.HELU.PSD11**_ (I don't have Avast in english so it can be slightly different).
Can someone explain me what's going on? Is deno virus or not?
Thanks

**Comment by kt3k** [comment] 2021-06-02 09:33
duplicate of #5690

**Closed by kt3k** 2021-06-02 09:33 UTC
