### ISSUE TITLE
Request: native support for matrix operation, with hardware accelation 

### ISSUE THREAD

**Issue by dharmax** [denoland/deno#4606] opened 2020-04-03 15:44 UTC
i think it would be great for modern ML.

**Comment by kitsonk** [comment] 2020-04-03 19:46
This would be a plugin. Not part of core Deno.

**Comment by bartOssh** [comment] 2020-04-07 07:31
Shall it be based on for example some strong [rust crate](https://nalgebra.org/) or it will be written from the basement up ?

**Comment by dharmax** [comment] 2020-04-07 13:11
@kitsonk - where's the place to suggest such plugins for deno?
@bartOssh - good question. What'd you propose?

**Comment by ry** [comment] 2020-04-07 13:29
Ideally Deno would be able to run TFJS which is uses WebGL for accelerated linear algebra. I'm quite interested in adding WebGL support for this reason.

**Comment by kitsonk** [comment] 2020-04-07 22:39
So if we agree this would be accomplished by WebGL, then this becomes a duplicate of #1629.

**Comment by ry** [comment] 2020-04-07 22:47
duplicate of #1629.

**Closed by ry** 2020-04-07 22:47 UTC
