### ISSUE TITLE
`deno install` doesn't work with local `deno.json[c]` imports

### ISSUE THREAD

**Issue by NfNitLoop** [denoland/deno#22961] opened 2024-03-17 01:13 UTC
Problem
----------

When I specify `imports` in my `deno.jsonc`, if I try to `deno install my_main.ts`, it succeeds.

However, running that script gives an error, because the import map was not respected during install:

```
error: Relative import path "@nostr/tools" not prefixed with / or ./ or ../
    at file:///C:/Users/codyc/code/nostr/nt.ts:10:63
```

(Tested with Deno v1.41.3)

Context 
---------

Before JSR, I stuck with the `deps.ts` (or `deps/*.ts`) pattern for modules, so that they could be used as libraries or executable scripts, locally or remotely. During development, I could just `deno install --permissions my_main.ts` and then `my_main sub command ...` to iteratively test. 

~~But my understanding is that that will be incompatible with jsr.io packages, since we can't use http(s) imports there.~~ But when switching to using an import map, `deno install` has had a regression for the above use case.

I mentioned this in Discord and [was asked][1] to create an issue. :) 

[1]: https://discord.com/channels/684898665143206084/684898665151594506/1218724367932985444
 

Workarounds
---------------

I see that `deno install` has an `--import-map` option. But that option doesn't know how to parse a deno.jsonc file. I don't see an option to use imports from that file.

I could automate extracting that import map for local use. Or manually maintain both. But that seems like it should be unnecessary.

As a workaround, I'm just using a `deno task` entry to call `deno run --deno-args my_main.ts`

**Comment by NfNitLoop** [comment] 2024-03-17 01:20
> But my understanding is that that will be incompatible with jsr.io

I just realized there's a compatible workaround: 

I could use the `deps.ts` pattern, and just move my `jsr:` imports there.

Feels odd to need to do this when jsr.io supports deno.jsonc, though. `deno install` should too!

**Comment by dsherret** [comment] 2024-03-17 01:45
Duplicate of #17834 and a few other issues. See https://github.com/denoland/deno/issues/17855

**Closed by dsherret** 2024-03-17 01:45 UTC
