### ISSUE TITLE
Deno.Listener no exposing port

### ISSUE THREAD

**Issue by aricart** [denoland/deno#5477] opened 2020-05-15 21:27 UTC
To extract the port from a random port in a Deno.listen is somewhat painful:
```
    const listener = Deno.listen({ port: 0, transport: "tcp" });
    //@ts-ignore
    const {port} = listener.addr
    this.port = port
```

While the random port doesn't seem that useful, it is extremely. For unit tests,  launching a listener or process at a random port means that unit tests can really be independent, and not hardcoded.

**Comment by SyrupThinker** [comment] 2020-05-15 22:27
Your error is basically a duplicate of #5102, check [this comment](https://github.com/denoland/deno/issues/5102#issuecomment-624716274).

**Closed** 2021-04-13 11:33 UTC
Labels: bug, cli, public API
