### ISSUE TITLE
Failed to deno compile project that imports npm:bcrypt

### ISSUE THREAD

**Issue by avalero** [denoland/deno#27219] opened 2024-12-03 16:33 UTC
Version: Deno 2.1.2
OS: Ubuntu 24.10

When running a deno compiled project that imports `npm:bcrypt` I get the following error:

```
error: Uncaught (in promise) TypeError: /tmp/deno-compile-apps/apps/node_modules/.deno/bcrypt@5.1.1/node_modules/bcrypt/lib/binding/napi-v3/bcrypt_lib.node: cannot open shared object file: No such file or directory
    at Object.Module._extensions..node (node:module:801:20)
    at Module.load (node:module:662:32)
    at Function.Module._load (node:module:534:12)
    at Module.require (node:module:681:19)
    at require (node:module:812:16)
    at Object.<anonymous> (file:///tmp/deno-compile-apps/apps/node_modules/.deno/bcrypt@5.1.1/node_modules/bcrypt/bcrypt.js:6:16)
    at Object.<anonymous> (file:///tmp/deno-compile-apps/apps/node_modules/.deno/bcrypt@5.1.1/node_modules/bcrypt/bcrypt.js:238:4)
    at Module._compile (node:module:745:34)
    at loadMaybeCjs (node:module:770:10)
    at Object.Module._extensions..js (node:module:755:12)
```

**Comment by marvinhagemeister** [comment] 2024-12-03 16:52
Duplicate of https://github.com/denoland/deno/issues/23266

**Closed by marvinhagemeister** 2024-12-03 16:52 UTC
