### ISSUE TITLE
`Deno compile` errors when ancestor directory is windows junction with target on separate drive

### ISSUE THREAD

**Issue by BobFrankston** [denoland/deno#26316] opened 2024-10-16 15:42 UTC
Version:  2.0.0-rc.9

_**Note this happens when I have a legacy program with a package.json** Removing package.json is a simpler fix but needs a better diagnostic to tell me that.

I have an app in y:\x\bin, but that's really a link to C:\Users\Bob\OneDrive\xfer\bin. This confuses the compiler. It should be smart about handling junctions in Windows.

```
Y:\x\Bin\xform>deno compile --allow-read --allow-write --output xform.exe xform.ts
Check file:///Y:/x/Bin/xform/xform.ts
Compile file:///Y:/x/Bin/xform/xform.ts to xform.exe
error: Writing temporary file 'xform.exe.tmp-7f879bfc5a53ae10'

Caused by:
    Failed to strip prefix 'C:\Users\Bob\OneDrive\xfer\bin' from 'Y:\x\Bin\xform\package.json'
```

the work-around is a .cmd file which moves to the real directory and does the compiler there.

**Comment by yazan-abdalrahman** [comment] 2024-10-17 11:37
I am unable to reproduce it.

![image](https://github.com/user-attachments/assets/b827045e-3e49-47ba-98db-3b555fb59395)

**Comment by yazan-abdalrahman** [comment] 2024-10-17 14:04
I am working on it; I found the major issue and am currently working.

**Comment by yazan-abdalrahman** [comment] 2024-10-21 08:53
@dsherret 

Hi, the method `path_relative_root ` tries to strip a prefix from a canonicalized path (like` C:\Users\Bob\OneDrive\xfer\bin`), but it encounters a path that uses the junction (`Y:\x\Bin`), which causes it to fail and return an error.

suggested solution resolves the issue of handling Windows junctions and symbolic links when trying to strip the root path from a given file path.

**solution** attempting to strip the root path normally. If it fails, it checks if the root path is a junction and tries stripping its canonicalized form. If that also fails, it searches for symlinks or junctions within the root directory, resolves their canonical paths, and attempts to strip those. If all efforts fail, an error is returned, making the function robust against junctions and symbolic links in Windows environments.

```
  fn path_relative_root(&self, path: &Path) -> Result<PathBuf, StripRootError> {
    // There are no junctions
    if let Ok(relative_path) = path.strip_prefix(&self.root_path) {
      return Ok(relative_path.to_path_buf());
    }

    // The base is a junction.
    if let Ok(canonical_root) = canonicalize_path(&self.root_path) {
      if let Ok(relative_path) = path.strip_prefix(&canonical_root) {
        return Ok(relative_path.to_path_buf());
      }
    }
    
    // junctions placed at the base
    let mut symlinks = Vec::new();
    let mut visited = HashSet::new();
    let mut symlink_targets = HashSet::new();

    if let Ok(_) = visit_dirs(
      &self.root_path,
      &mut symlinks,
      &mut visited,
      &mut symlink_targets,
    ) {
      if !symlinks.is_empty() {
        for symlink in symlinks {
          if let Ok(canonical_path) = canonicalize_path(&symlink) {
            dbg!(&canonical_path);
            if let Ok(relative_path) = path.strip_prefix(&canonical_path) {
              return Ok(relative_path.to_path_buf());
            }
          }
        }
      }
    }

    // error
    Err(StripRootError {
      root_path: self.root_path.clone(),
      target: path.to_path_buf(),
    })
  }
}
```

Is that the right idea to work on it?

**Comment by BobFrankston** [comment] 2024-10-21 13:16
I don't know the code, so I can't say for sure, but it seems like the right direction. Symbolic links have broken the link with the physical metaphors going back to Multics in the 1960s.

**Comment by dsherret** [comment] 2024-10-25 02:40
This one was a little challenging to reproduce because it only occurs if the data is on multiple drives.

1. `cmd`
1. `C:`
1. `cd C:\Users\david`
1. `mkdir xfer\bin\xform && cd xfer\bin\xform`
1. `echo {} > package.json`
1. `deno install npm:chalk`
1. `echo import 'chalk' > main.ts`
1. `rmdir node_modules /S /Q
1. `V:` (I have a V: drive)
1. `mkdir xfer && cd xfer`
1. `mklink /J V:\xfer\bin C:\Users\david\xfer\bin`
1. `cd bin/xform`
1. `deno install`
1. `deno compile main.ts`

Since it requires multiple drives, it's hard to add a test for this. After being able to reproduce it, I did discover this was fixed by the changes in https://github.com/denoland/deno/pull/26494 (specifically https://github.com/denoland/deno/pull/26494/files#diff-601eae32e207b6a047849c4ed374bdfd7889dbea05800555564876607f87741eR290-R296). So this will be fixed in 2.0.3 (which should be released in a few hours or is available right now via `deno upgrade canary`). Let me know if you run into any other issues.

**Closed by dsherret** 2024-10-25 02:40 UTC
Labels: bug, windows, compile

**Comment by BobFrankston** [comment] 2024-10-25 11:49
Note that I found, in Node, that I need to use 
```
fs.realpath.native
````
for symlinks across a network as in 
```
<SYMLINKD>     d [\\rmf69\d]
```
I don't know about the equivalent in Deno.
