### ISSUE TITLE
Deno panics when --html --name=index.html

### ISSUE THREAD

**Issue by chrisbobek** [denoland/deno#21088] opened 2023-11-04 10:30 UTC
After upgrading to v1.38.0, I ran deno doc --html --name=index.html from Windows Terminal.

Deno panics whenever this is run.

**Comment by crowlKats** [comment] 2023-11-04 11:17
What is the panic?

**Comment by dsherret** [comment] 2023-11-04 15:55
Duplicate of https://github.com/denoland/deno/issues/21067

Will be fixed in the next patch release. Try running `deno doc --html --name=YourLibraryName mod.ts` instead.

**Closed by dsherret** 2023-11-04 15:55 UTC
Labels: duplicate
