### ISSUE TITLE
Imports issue with paths that include `#`

### ISSUE THREAD

**Issue by jeff-hykin** [denoland/deno#15382] opened 2022-08-01 22:32 UTC
It appears some URL escaping is done even if the given file path is not in URL form (`#` along with a handful of other characters are valid across Linux/Mac/Windows filepaths)

<img width="1192" alt="Screen Shot 2022-08-01 at 5 21 16 PM" src="https://user-images.githubusercontent.com/17692058/182256055-1014e22b-73af-451d-b1e8-3db542b31ab3.png">

To Reproduce:
- create a folder with `#` in the name
- try to import a file from that folder (both import statements and import calls)

Current Workaround:
- escape the `#` with `%23` just like it would be in a URL import
- more generically `await import(encodeURIComponent(THE_PATH).replace(/%2F/g,'/'))`

**Comment by Kapsonfire-DE** [comment] 2022-08-02 06:57
The problem isnt limited to the `#`, it also happens with the `@`- UNC paths are allowed to have this, while its not allowed for domain names

**Comment by nayeemrmn** [comment] 2022-08-02 07:00
This is intended, you have to percent encode files since specifiers are URLs.

**Comment by Kapsonfire-DE** [comment] 2022-08-02 07:01
you cant encode if you do a import like "./test.ts" and its automatically gets resolved to the whole unc path

https://discord.com/channels/684898665143206084/689420767620104201/1003683577277468682

**Comment by nayeemrmn** [comment] 2022-08-02 07:10
@Kapsonfire-DE This issue has nothing to do with that discussion or UNC paths

**Comment by jeff-hykin** [comment] 2022-08-02 10:53
I see :/ that is rather unfortunate as it ruins the traceback since error stacks now print out the escaped version rather than the actual file path.

Is there some use-case where developers would intentionally not escape # and @? It seems like they always throw an error, and a confusing error at that. @nayeemrmn

**Comment by jeff-hykin** [comment] 2022-08-02 10:57
I see :/ that is rather unfortunate as it ruins the traceback since error stacks now print out the escaped version rather than the actual file path.

Is there some use-case where developers would intentionally not escape # and @? It seems like they always throw an error, and a confusing error at that. Escaping it for `file:///` makes sense, but I don't see a world in which a developer types `import "./folder#/thing.js"` and were hoping/expecting an error to be thrown. @nayeemrmn

**Comment by nayeemrmn** [comment] 2022-08-02 13:54
> Is there some use-case where developers would intentionally not escape #

Yeah it becomes the hash part of the URL, it can be used to cache bust for example. Anyway using these characters in file names is equivalently uncommon

**Comment by jeff-hykin** [comment] 2022-08-02 14:10
> Yeah it becomes the hash part of the URL, it can be used to cache bust for example.

How could cache busting be done on a local file?

**Comment by lucacasonato** [comment] 2024-09-19 10:39
@jeff-hykin Servers do not receive the data after the `#` anyway. But you can load the same module source code multiple times using hashes to enable having multiple different top level states in the modules.

I am closing this as working as intended (it behaves the same as browsers).

**Closed by lucacasonato** 2024-09-19 10:39 UTC
Labels: bug
