### ISSUE TITLE
[suggest]Is there any plan to drop import extension？

### ISSUE THREAD

**Issue by skimmilk6877** [denoland/deno#13417] opened 2022-01-19 02:15 UTC
I use deno in a Monorepo project witch nodejs and browser code.

And for now,webstorm only support one typescript language server. Actually, I did some work in babel,and now I can deliver code between node、deno and brower.

And I use vscode for deno,webstorm for node and brower.

What annoying me is, if I careless touch a deno file in webstrom,it alart me '.ts' error as you know.

Use deno and node in mix mode is the reality.

Actually,the reason I use deno is because,it is good to write TypeScript script. And I can obtain that ability via esbuild.

I think the incompatible in typescript import syntax,is a big mistake you should change.

deno is good,because if we make a huge program,we can use deno to isolate something.In that scope,what is important is we can tansfer any code from deno to node,and any code from node to deno.

In order to achieve this goal, my design(and I think is the common one) is use node develop code.and generate deno code.(because if a problem can solve in deno,it certainly can be solved in node,but  not the other way around).

And I think it's good for deno to generate language syntax compatible design.

Meanwhile,I think npm discompatible is receivable,because this is higher than lanuage syntax,And we can do a lot to compat that layer.

**Comment by kitsonk** [comment] 2022-01-19 02:24
Duplicate of #2506

**Closed by kitsonk** 2022-01-19 02:24 UTC
Labels: duplicate
