### ISSUE TITLE
Improve CI Performance around changes to `std`.

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#6578] opened 2020-06-30 04:42 UTC
Feels like when we are doing changes in `std` that a whole build of Deno plus the full test suite of Deno is unnecessary for validating a change to `std` and we should consider some mechanism to only test `std` potentially against a prebuilt version of Deno.

**Comment by nayeemrmn** [comment] 2020-06-30 04:46
Duplicate of #5186.

**Closed** 2020-06-30 04:48 UTC
