### ISSUE TITLE
deno doc missing examples in html output

### ISSUE THREAD

**Issue by JOTSR** [denoland/deno#22893] opened 2024-03-13 14:28 UTC
Version: Deno 1.41.2

`deno doc --html` drop `jsdoc` examples for class (no issues for others output formats).

# Example
```ts
//mod.ts

/**
 * Module from mod.ts
 * 
 * @example
 * ```ts
 * console.log("Module - I'm displayed")
 * ```
 * @module
*/

export { myClass } from './mod_b.ts'

/**
 * Nothing from mod.ts
 * @param { string } msg - Message
 * 
 * @example
 * ```ts
 * console.log("Function - I'm displayed")
 * ```
 */
export function nothing(msg: string) {
    console.log(msg)
}
```

```ts
//mod_b.ts

export class myClass {
    /**
     * Method from mod_b.ts
     * @param { string } msg - Message
     * 
     * @example
     * ```ts
     * console.log("Method - I'm not displayed")
     * ```
     */
    method(msg: string) {
        console.log(msg)
    }
}
```

![image](https://github.com/denoland/deno/assets/58234376/f7525b5f-2289-4661-8f24-27029fac991f)
![image](https://github.com/denoland/deno/assets/58234376/5014f22b-6b90-4154-9d76-bf60ae3b242c)
![image](https://github.com/denoland/deno/assets/58234376/e54b027b-63b2-418d-aaae-4f2737532637)

**Comment by Delapouite** [comment] 2024-04-26 11:33
Hi

When I tried to reproduce your example (on deno 1.42.1), the `method` is clickable:
![image](https://github.com/denoland/deno/assets/39315/7fb78c8e-eaed-4375-83e0-54b31a0f3685)

and the `method` `@example` is displayed: 

![image](https://github.com/denoland/deno/assets/39315/454c3951-1029-4d4c-9f43-ef755cfb8434)

**Comment by crowlKats** [comment] 2024-04-26 11:47
yes, we dont render examples on the class page intentionally, as that would be too bloated visually and information-wise, especially for classes thaat have multiple properties/methods.
Closing as intended

**Closed by crowlKats** 2024-04-26 11:47 UTC
