### ISSUE TITLE
Problems: When I import the json module by `import`, I can't using destructuring assignment

### ISSUE THREAD

**Issue by fwqaaq** [denoland/deno#19361] opened 2023-06-04 10:21 UTC
Like this:

```js
import { prefixes } from "https://ip-ranges.amazonaws.com/ip-ranges.json" assert {type: "json"}
```

> error: Uncaught SyntaxError: The requested module 'https://ip-ranges.amazonaws.com/ip-ranges.json' does not provide an export named 'prefixes'

But you can look `deno` hints for `deno` plugins. And in fact, this json has `prefixes` fields.

![image](https://github.com/denoland/deno/assets/82551626/c331a022-083b-42bf-a9a1-b81f76cb5fcb)

This is my deno version

```
deno --version                                                                                                                                                                  ─╯
deno 1.34.1 (release, x86_64-unknown-linux-gnu)
v8 11.5.150.2
typescript 5.0.4
```

**Comment by babiabeo** [comment] 2023-06-04 12:40
I think you should use [default import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#default_import) when importing JSON in Deno.
Somethink like this:
```ts
import ip from "https://ip-ranges.amazonaws.com/ip-ranges.json" assert { type: "json" };

console.log(ip.prefixes);
```
See also: https://examples.deno.land/importing-json.

**Comment by fwqaaq** [comment] 2023-06-04 12:50
> I think you should use [default import](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import#default_import) when importing JSON in Deno.

Yeah. You're right. In fact, it is `default import` when you use `import()`. In here, you can use destructuring assignment

```js
await import("https://ip-ranges.amazonaws.com/ip-ranges.json", {assert: {type: "json"}})
```

**Comment by dsherret** [comment] 2023-06-05 02:51
Yeah, you need to use the default import.

Duplicate of #18614

**Closed by dsherret** 2023-06-05 02:51 UTC
Labels: duplicate, invalid
