### ISSUE TITLE
Deno compile – doesn't work with unstable sloppy imports

### ISSUE THREAD

**Issue by lino-levan** [denoland/deno#27031] opened 2024-11-23 17:12 UTC
I think it would be helpful for adoption if deno compile could work with unstable sloppy imports. Right now it "compiles successfully" and then crashes are runtime, which isn't great.

**Comment by dsherret** [comment] 2024-11-23 18:28
Duplicate of https://github.com/denoland/deno/issues/26102

> Right now it "compiles successfully" and then crashes are runtime, which isn't great.

There is a warning at the moment https://github.com/denoland/deno/blob/12b377247be2b74155ded3a678ff2996ef3d7c9f/cli/tools/compile.rs#L45-L51

**Closed by dsherret** 2024-11-23 18:28 UTC
Labels: duplicate

**Comment by lino-levan** [comment] 2024-11-23 18:51
Right, I missed that in my issue search. Thanks for pointing me in the right direction.
