### ISSUE TITLE
confused by order of cli option flags

### ISSUE THREAD

**Issue by Ragzouken** [denoland/deno#5450] opened 2020-05-15 10:26 UTC
I'm not hugely familiar with CLI standards, but I don't think I've ever run in to the requirement that --flags precede the positional arguments. I spent a long while trying to get `--allow-net` to work before realising this was necessary.

`deno run --allow-net something.ts` vs `deno run something.ts --allow-net`

Is there any reason not to support both forms?

Alternately, a warning that the arguments were being ignored as invalid would have helped me understand.

**Comment by Ragzouken** [comment] 2020-05-15 10:44
I realised github wasn't showing closed issues when I tried to find if this was reported before, so I now understand that all the arguments after `something.ts` are being passed into the script rather than used by deno. I guess this makes sense but it was extremely confusing to me and I wonder if this can be signposted somewhere more clearly?

**Comment by kevinkassimo** [comment] 2020-05-15 19:46
The reason is simple: flag after the script name is passed to the script instead of to Deno. Imagine writing a command-line utility using Deno and later aliasing it (or using `deno install`). There are problems such as `-A` that is meaningful to Deno but might also be meaningful for the command-line program you write

**Comment by nayeemrmn** [comment] 2020-05-16 13:09
I don't think it would be too hard. If a permission error is encountered, check the script args for the relevant flag. If it's there, include `Did you mean: "deno run --allow-net something.ts"?` (the flag shifted back to before the script name) in the error message. Wouldn't always be right but it doesn't have to be.

Sounds like you've found them but duplicate of #2708, #3469, #5294.

**Comment by bartlomieju** [comment] 2020-05-19 12:35
We should add a page to manual discussing CLI in depth with paragraph explaining permissions

**Comment by am01264** [comment] 2020-05-26 00:41
Hi all, first time poster here so apologies for any breach of etiquette.

@bartlomieju 
I just tripped on this exact issue. Reading the issues, I suspect it's not a lack of documentation - because `deno help run` shows it just fine.

The issue is that it took me 5 variations of 
```powershell
PS> deno run .\index.ts --allow-write=./tmp
PS> deno run .\index.ts --allow-write=tmp
PS> deno run .\index.ts --allow-write
```

With this error description as my only clue:
```
error: Uncaught PermissionDenied: write access to "C:\...\tmp\try_me", run again with the --allow-write flag
```

Before I gave up and read the documentation. Even then, it was only desperation that got me to move the flag. 

I've read the other duplicate issues, so I understand why it behaves like this... but in my experience of CLI apps across Windows and Linux there's only a small handful of tools that care about the order of flag arguments... and those that pass arguments to scripts tend to use "--" as a clear separator of arguments to be passed to the script file.

If that's not a solution, then at worst vet the flags on a permission denial, and pass a warning "did you mean: ...". My gut sense is that this could lead to a mess: permission error handling is not the place to put it & it would also be irritating if a deno flag matched an userland script flag.

Short of forcing some users to wrap their head around an un-intuitive argument format, it seems the "--" separator provides a clean solution while limiting added complexity.

I realise some of what I've said has been repeated in the duplicated issues, but it feels like some people are hitting their head against the walls going "how can users be so <insert expletive of choice>" while the users are silently screaming "what do you mean the flag isn't there? I can see it with my own eyes!"... and then eventually "this doesn't work" and giving up.

Maybe even both could be a solution, use "--" optionally to remove any ambiguity, and by default warn about those trailing --allow flags. That way nobodies code breaks, and no useless flags are added.

Food for thought

**Comment by nayeemrmn** [comment] 2020-05-26 01:02
> those that pass arguments to scripts tend to use "--" as a clear separator of arguments to be passed to the script file.

> un-intuitive argument format

@am01264 All the runtimes I've checked handle flags vs script args exactly the same as we do. Could you provide a counter-example?

**Comment by am01264** [comment] 2020-05-26 01:40
@nayeemrmn Sorry if that came over sharper than intended. I'll admit it's near impossible to search for online, but here's a couple:

```powershell
PS> node --help

Usage: node [options] [ script.js ] [arguments]
       node inspect [options] [ script.js | host:port ] [arguments]

Options:
  # skipping a few lines
  --                                  indicate the end of node options
```

I must confess I though python, Java and others would report it on the documentation... but I'm not seeing it.

From a quick search of the StackOverflow network, it appears it's part of a [POSIX Standard (Guideline 10)](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02)

> POSIX.1-2017
> 
> 12.2 Utility Syntax Guidelines
> 
> Guideline 10:
> 
> The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options. Any following arguments should be treated as operands, even if they begin with the '-' character.
> 

From there it's just a variety of man-pages

[BaSH Shell](https://manpage.me/?q=bash#OPTIONS):
```man
BASH(1)								       BASH(1)

NAME
       bash - GNU Bourne-Again SHell

OPTIONS
       --	 A -- signals the end of options and disables  further	option
		 processing.   Any arguments after the -- are treated as file-
		 names and arguments.  An argument of -	is equivalent to --.
```

[startx]()
```man
STARTX(1)               FreeBSD General Commands Manual              STARTX(1)

NAME
       startx - initialize an X session

SYNOPSIS
       startx [ [ client ] options ... ] [ -- [ server ] [ display ] options
       ... ]

DESCRIPTION
...

              startx -- -depth 16

              startx -- -dpi 100

              startx -- -layout Multihead
```

Looking at it, it may be just a Linux/UNIX norm, but it is definitely a thing.

**Comment by nayeemrmn** [comment] 2020-05-26 03:13
@am01264 It seems what you're showing is the precedent for the feature: "Everything after `--` is a consumed as a positional argument". Deno actually works like this already. That's how our arg parsing dependency `clap` does things so we didn't really have a say there anyway.

However this issue, as well as your code example, is about our characteristic that "Everything after the script name is a script argument", and how this is a source of confusion because the flags you passed after the script name were unexpectedly treated like script args. But three examples you mentioned (Node, Python and Bash) I've checked to work exactly the same way.

Let me ask a different way: can you show any Node command that uses both Node flags and script args, a similar Deno command that uses both Deno flags and script args, and demonstrate that Deno has parsed them differently?

**Comment by am01264** [comment] 2020-05-26 13:30
@nayeemrmn 

First of all, sorry. I've been using node for years, and never realised the flags are indeed treated differently before/after the script. [^node-arg-order-test]

The clearest explanation of what I was expecting is this:

> **POSIX Compatible Conflicts/Overrides** - In POSIX args can be conflicting, but not fail parsing because whichever arg comes last "wins" so to speak. This allows things such as aliases (i.e. alias ls='ls -l' but then using ls -C in your terminal which ends up passing ls -l -C as the final arguments.
> 
> &mdash; [Clap's README](https://github.com/clap-rs/clap#features)

This would mean the flag would be interpreted the same regardless of where in the arguments it fell. The only exception is if you use "--" before your additional arguments, then the application wouldn't interpret the arguments any further.

> The first -- argument that is not an option-argument should be accepted as a delimiter indicating the end of options.
>
> &mdash; [POSIX Utility Conventions, Guideline 10](https://pubs.opengroup.org/onlinepubs/9699919799/basedefs/V1_chap12.html#tag_12_02)

Testing my earlier examples, it looks like `startx` is the only application that matches my description word-for-word. Of scripting runtimes, it appears arguments are consumed... and whatevers left is handed to the script.


Bringing this back to Deno, I'm no longer so clear as to what the best way forward is. I imagine most users will likely never have this problem, as they'll start from the docs and work from there.

On the other hand, there's enough duplicate issues that it's clear it's tripping some people up. So here's the suggestions I'm left with:

1. Without changing existing behaviour, a troubleshooting hint would be a good minimal fix.

2. Alternatively, make flag arguments more flexible. This could create ambiguity which the `--` pattern would resolve (and built into `clap`).

Having tested behaviour of other libraries now, I could make an argument for both sides.

---

[^node-arg-order-test]: [Test case for any skeptics](https://gist.github.com/am01264/e003938cde79d5657cd32e7c566dd4a7)

**Comment by nayeemrmn** [comment] 2020-05-26 14:31
Honestly, I have a pretty good idea of why this is tripping people up: **people don't commonly use flags belonging to the runtime**. They aren't as important in other CLIs which don't have essential permission flags or are more config file based. I suspect people mistakenly compare `--allow-net` to e.g. `webpack` flags (which are actually script args from the perspective of Node) creating kind of a Mandela effect as to how arg parsing works in other runtimes.

There isn't much we can do about that except continue to educate. Also you've suggested having a `Did you mean...` system -- I've pushed for this too and think it would work out alright: https://github.com/denoland/deno/issues/5450#issuecomment-629643310.

**Comment by HP4k1h5** [comment] 2020-05-29 19:00
apologies if this is noted elsewhere, but i'm looking for a way to pass flags as a config of some kind. i.e.
```json
{
  "allow-net": true
}
```

**Comment by Alhadis** [comment] 2020-06-07 09:23
Traditionally, options have always preceded positional parameters, because it makes variable-size argument lists much simpler to deal with. Consider:

~~~sh
grep *.js
~~~

… now, imagine if `*.js` expanded to literally thousands of files, and the 453th filename happened to match an option that changes the program's behaviour. It would then need to either reprocess the argument list a *second* time with the new switch in effect, or process subsequent arguments differently than those before. Neither outcome is desirable (especially if you're running `rm -f` and hit a file named `-r`…)

Having the options before the arguments might become more intuitive if you liken it to a variadic JavaScript function:

~~~javascript
function grep(option1, option2, ...argv){
}
~~~

**Comment by ry** [comment] 2020-06-08 13:49
This isn't something we can change in the stable 1.0 release, but I agree that it's very confusing how the options are parsed. I think it would be less confusing to use `--` to distinguish script arguments vs deno arguments.

**Closed** 2020-06-08 13:49 UTC
Labels: cli, docs
