### ISSUE TITLE
'cargo install deno' fails to compile under rustc 1.45.2

### ISSUE THREAD

**Issue by liborty** [denoland/deno#7213] opened 2020-08-27 05:15 UTC
Compiling dprint-plugin-typescript v0.29.1
error[E0308]: mismatched types
   --> /home/l/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.3.1/main.rs:554:7
    |
554 |       syntax,
    |       ^^^^^^ expected enum `swc_ecma_parser::Syntax`, found a different enum `swc_ecma_parser::Syntax`
    |
    = note: perhaps two different versions of crate `swc_ecma_parser` are being used?

error[E0308]: mismatched types
   --> /home/l/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.3.1/main.rs:561:60
    |
561 |       .parse_with_reexports(&module_specifier.to_string(), syntax)
    |                                                            ^^^^^^ expected enum `swc_ecma_parser::Syntax`, found a different enum `swc_ecma_parser::Syntax`
    |
    = note: perhaps two different versions of crate `swc_ecma_parser` are being used?

error[E0308]: mismatched types
   --> /home/l/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.3.1/lint.rs:173:13
    |
173 |     .syntax(syntax)
    |             ^^^^^^ expected enum `swc_ecma_parser::Syntax`, found a different enum `swc_ecma_parser::Syntax`
    |
    = note: perhaps two different versions of crate `swc_ecma_parser` are being used?

error[E0609]: no field `filename` on type `deno_lint::diagnostic::Location`
   --> /home/l/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.3.1/lint.rs:228:21
    |
228 |         &d.location.filename,
    |                     ^^^^^^^^ unknown field
    |
    = note: available fields are: `line`, `col`

error[E0609]: no field `filename` on type `&deno_lint::diagnostic::Location`
   --> /home/l/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.3.1/lint.rs:291:39
    |
291 |   return format!("{}:{}:{}", location.filename, location.line, location.col);
    |                                       ^^^^^^^^ unknown field
    |
    = note: available fields are: `line`, `col`

error: aborting due to 5 previous errors

Some errors have detailed explanations: E0308, E0609.
For more information about an error, try `rustc --explain E0308`.
error: failed to compile `deno v1.3.1`, intermediate artifacts can be found at `/tmp/cargo-installzzCTFN`

Caused by:
  could not compile `deno`.

**Comment by lucacasonato** [comment] 2020-08-27 06:33
Duplicate of #7175

**Closed** 2020-08-27 09:36 UTC
