### ISSUE TITLE
Regression since 1.15.x - deno hangs with 100% CPU usage if importing ajv

### ISSUE THREAD

**Issue by nktpro** [denoland/deno#12624] opened 2021-11-02 09:04 UTC
Here's a quick reproducer, given:

```typescript
import ajv from "https://cdn.skypack.dev/ajv@v8.6.3?dts";
```

`deno` (`eval`, `run`, `cache`, etc.) will hang forever, with 100% CPU usage:
```bash
docker run -it --rm  denoland/deno:1.15.3 deno eval 'import ajv from "https://cdn.skypack.dev/ajv@v8.6.3?dts"' 
```

This used to work perfectly with `1.14.x` and below:
```bash
docker run -it --rm  denoland/deno:1.14.3 deno eval 'import ajv from "https://cdn.skypack.dev/ajv@v8.6.3?dts"' 
```

This seemed to exhibit the behavior of an infinite loop or recursion.

**Comment by kitsonk** [comment] 2021-11-02 09:18
Duplicate of denoland/deno_graph#55

**Closed by kitsonk** 2021-11-02 09:18 UTC
Labels: duplicate

**Comment by lucacasonato** [comment] 2021-11-02 10:39
This will be in the Deno 1.16.0 release on November 9th.
