### ISSUE TITLE
[repl][jupyter-kernel] {"code":-32000,"message":"Promise was collected"}

### ISSUE THREAD

**Issue by rgbkrk** [denoland/deno#20528] opened 2023-09-16 19:36 UTC
Sometimes instead of the result I would expect, this error comes up:

```
{"code":-32000,"message":"Promise was collected"}
```

It goes out as the current exception rather than the output for a cell. The cell seems to run fine still regardless.

<img width="371" alt="image" src="https://github.com/denoland/deno/assets/836375/f51e6d4b-6c6e-4b2b-96ef-783393dd6fcc">

This happens both in the REPL and in Jupyter.

**Comment by mmastrac** [comment] 2023-09-16 22:35
I've seen this as well but I could not reliably reproduce it.

**Comment by rgbkrk** [comment] 2023-09-17 15:46
It appears to come from V8: https://chromium.googlesource.com/v8/v8/+/refs/heads/main/src/inspector/injected-script.cc#1230

Hypotheses

* There is a dangling promise somewhere in code that got injected
* When we get this error message we need to not include it as a message for Jupyter frontends
* Somehow when this message is coming in we are losing out on displaying what was meant to in the cell

**Comment by mmastrac** [comment] 2023-09-17 16:38
I was thinking about this this morning - I think we need to ensure that the object is GC rooted until we've read the properties. This probably means we should assign it to the global object temporarily, and then delete it after.

**Comment by rgbkrk** [comment] 2023-09-17 17:30
Would it be appropriate for us to store results in a global Out array similar to IPython's?

**Comment by mmastrac** [comment] 2023-09-17 21:56
@rgbkrk Is there a way to refer back to those ordered outputs? If so, it might be good to keep that feature around!

**Comment by rgbkrk** [comment] 2023-09-17 22:56
When you use the `jupyter console` with Deno it's going to show `In`, `Out` because that's the Jupyter thing to do. I would kind of hope to keep it in capitals, just like `Deno`.

<img width="256" alt="image" src="https://github.com/denoland/deno/assets/836375/7152c97f-f7d6-4e56-9c6e-3bb7fd105bf6">

Also... kind of funny that I hit an error making a quick screenshot. 🫠

**Comment by rgbkrk** [comment] 2023-09-17 23:00
This is indeed from me logging it here.

```
  if let Some(exception_details) = &response.exception_details {
    // TODO(rgbkrk): Return an error in userspace instead of Jupyter logs
    eprintln!("Exception encountered: {}", exception_details.text);
    return Ok(None);
  }
```

I apparently read this segment of code wrong. We really are attempting to run the `Symbol.for("Jupyter.display")` function on all objects even if it doesn't have that property. Is it better to handle that in the JS function passed in or just be more silent in this segment?

**Comment by rgbkrk** [comment] 2023-09-18 06:24
I'm not sure if the storage of previous outputs will help here, since I'm getting this error message even for `console.log` statements.

<img width="408" alt="image" src="https://github.com/denoland/deno/assets/836375/0a0c4542-9e1e-4893-82c7-7e28b1fd977b">

**Comment by rgbkrk** [comment] 2023-09-21 21:31
All day every day `{"code":-32000,"message":"Promise was collected"}`. This is absolutely the most pressing issue for everyday usability.

**Comment by skybrian** [comment] 2023-09-22 21:44
Seeing this too, occasionally, using VS Code. When I see this for a cell that displays a canvas, it doesn't draw the canvas.

Re-running the cell doesn't fix it, but editing the cell apparently does?

Specifically, I tried adding an await in front of the display function call. It shouldn't do anything since display doesn't return a promise, but perhaps it changes the timing? But removing the await doesn't cause the error to come back.

**Comment by bartlomieju** [comment] 2023-09-23 08:52
I'm debugging this problem. This appears to be a timing issue but I'm digging deeper to understand what's causing this problem.

**Comment by bartlomieju** [comment] 2023-09-23 10:15
Opened https://github.com/denoland/deno/pull/20646 that fixes the problem for me. I would appreciate if you could try it on your side and let me know if you're able to reproduce the problem with this change.

**Comment by rgbkrk** [comment] 2023-09-23 14:36
I have not been able to reproduce this at all! Thank you!!!

**Comment by rgbkrk** [comment] 2023-09-23 14:39
Oh no, I saw one. It seems to be occurring less but not always.

![image](https://github.com/denoland/deno/assets/836375/ccbc9705-94a8-42ba-9245-55bcd9ec97ce)

**Comment by rgbkrk** [comment] 2023-09-23 14:45
Same notebook, I can reliably get this error message to appear in the Jupyter logs. Run the following two cells in Jupyterlab:

`In[1]:`

```typescript
const alphabet = [{"letter":"A","frequency":0.08167},{"letter":"B","frequency":0.01492},{"letter":"C","frequency":0.02782},{"letter":"D","frequency":0.04253},{"letter":"E","frequency":0.12702},{"letter":"F","frequency":0.02228},{"letter":"G","frequency":0.02015},{"letter":"H","frequency":0.06094},{"letter":"I","frequency":0.06966},{"letter":"J","frequency":0.00153},{"letter":"K","frequency":0.00772},{"letter":"L","frequency":0.04025},{"letter":"M","frequency":0.02406},{"letter":"N","frequency":0.06749},{"letter":"O","frequency":0.07507},{"letter":"P","frequency":0.01929},{"letter":"Q","frequency":0.00095},{"letter":"R","frequency":0.05987},{"letter":"S","frequency":0.06327},{"letter":"T","frequency":0.09056},{"letter":"U","frequency":0.02758},{"letter":"V","frequency":0.00978},{"letter":"W","frequency":0.0236},{"letter":"X","frequency":0.0015},{"letter":"Y","frequency":0.01974},{"letter":"Z","frequency":0.00074}]
```

`In[2]`:

```typescript
import * as Plot from "npm:@observablehq/plot"

import { display } from "https://deno.land/x/display@v0.1.1/mod.ts"

import { DOMParser, SVGElement } from "npm:linkedom";
const document = new DOMParser().parseFromString(
  `<!DOCTYPE html><html lang="en"></html>`,
  "text/html",
);

display(
    Plot.barY(alphabet, {x: "letter", y: "frequency"}).plot({document})
)
```

If you hit ctrl-enter rapidly enough while on the second cell, the error comes on the shell channel and shows in the Jupyter Logs:

```
Shell error: {"code":-32000,"message":"Promise was collected"}
```

In fact if you just hold down ctrl-enter you'll get the error message to appear in your terminal.

**Comment by acrodrig** [comment] 2023-09-29 18:21
I do not if it helps diagnosing the actual problem, but I am seeing by just importing polars. I am not using the Jupyter kernel, just starting a Deno REPL and loading a dataframe. Screenshot below.

![image](https://github.com/denoland/deno/assets/959336/fab69ada-aef5-4ed4-9ed5-d279f44001f9)

**Comment by rracariu** [comment] 2023-10-18 17:39
It can be consistently reproduced in `deno` REPL with something like:
```js
import pl from 'npm:nodejs-polars'
pl.Series("foo", [1, 2, 3, 4]).mean()
```
Re-run the last line a couple of times, it will print `error: {"code":-32000,"message":"Promise was collected"}` very often.

At some point `deno` REPL will exit silently.

```
deno --version
deno 1.37.2 (release, aarch64-apple-darwin)
v8 11.8.172.13
typescript 5.2.2
```

**Comment by bartlomieju** [comment] 2023-10-28 00:19
Simplest reproduction found yet:
```
> let a; console.log(1); a = new Uint8Array(100 * 1024 * 1024); console.log(2); a
1
2
error: {"code":-32000,"message":"Promise was collected"}
```

**Comment by rgbkrk** [comment] 2023-10-29 14:28
Interesting. I think it's repeatable even down to:

```
➜ deno
Deno 1.37.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> new Uint8Array(64 * 1024 * 1024)
error: {"code":-32000,"message":"Promise was collected"}
```

**Comment by mmastrac** [comment] 2023-11-02 14:37
I looked quickly into this to better understand the Deno repl version of the error and it appears it may have something to do with us allowing v8 to run a GC between the period when the statement completes execution and when we get the handle from the remote object.

Unfortunately this means that the statement, include all side-effects, has completely run. We have lost the final result in this case.

We probably have two approaches here that will fix it:

1. We can change the form of the REPL execution to something like this:

```
'use strict'
void 0;
try { REPL_DATA.lastExecutionResult = eval(...); } catch (e) { REPL_DATA.lastExecutionError = e; }
```

We would then treat either no return or "-32000" as a form of success, and run a second statement to retrieve the last execution result or error (which should not fail).

2. We can alter how we send execution results to v8, avoiding any sort of yield to allow v8 to execute its background processes (including GC) until we have an opportunity to retrieve the result itself.

3. We can patch this upstream in v8 so the eval promise stays rooted during a GC.

**Comment by bartlomieju** [comment] 2023-11-06 21:47
Debugged the problem with @mmastrac's help. As Matt found out the problem is that GC is allowed to run when we are evaluating a line and handling its result. The solution here is to disable GC in the "critical section" of the REPL and allow it to run, when waiting for input. This will require some invasive changes to the `deno_core`, but we have an idea how to fix it.

**Closed** 2023-11-22 02:45 UTC
Labels: bug, jupyter
