### ISSUE TITLE
error TS2339: Property 'utime' does not exist on type 'typeof Deno'.

### ISSUE THREAD

**Issue by CarlosOnline** [denoland/deno#5201] opened 2020-05-10 03:27 UTC
Error with example in fs module.

```
error TS2339: Property 'utime' does not exist on type 'typeof Deno'.
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std/fs/copy.ts:90:16
```

https://github.com/denoland/deno/blob/master/std/fs/README.md

```
import { emptyDir, emptyDirSync } from "https://deno.land/std/fs/mod.ts";

emptyDir("./foo"); // returns a promise
emptyDirSync("./foo"); // void
```

**Comment by nayeemrmn** [comment] 2020-05-10 03:50
Duplicate of #5175.

**Comment by bartlomieju** [comment] 2020-05-21 09:32
Please follow up discussion in #5175

**Closed by bartlomieju** 2020-05-21 09:32 UTC
