### ISSUE TITLE
Deno.compile doesn't rename imports

### ISSUE THREAD

**Issue by leonelv** [denoland/deno#6393] opened 2020-06-20 03:37 UTC
When using Deno.compile (v1.1.1), the output doesn't have the import paths with the correct ext

### Compile config:
```typescript
const [messages, result] = await Deno.compile(input, undefined, {
    target: 'es6',
    module: 'es6',
    lib: ['dom', 'esnext'],
  })
```

### Source:
![image](https://user-images.githubusercontent.com/16139979/85190319-a49b5e80-b28d-11ea-95bd-d5a6f24dd6ae.png)
### Output:
![image](https://user-images.githubusercontent.com/16139979/85190292-4cfcf300-b28d-11ea-85fd-f40b229ecdd6.png)

**Comment by wongjiahau** [comment] 2020-06-20 14:49
Can you provide what is the expected output?

**Comment by jeroenptrs** [comment] 2020-08-10 11:21
@wongjiahau In this case it should be `../../deps.js`, but in the case of an external dependency like `https://deno.land/std@0.64.0/examples/welcome.js`, it shouldn't rename because the js version does not exist.

**Comment by jeroenptrs** [comment] 2020-08-10 11:26
Also I think this is the same issue as #4538

**Comment by kitsonk** [comment] 2020-08-10 19:41
Correct, duplicate of #4538.

**Closed** 2020-08-10 19:55 UTC
