### ISSUE TITLE
vscode alert for uncached dependency, but cannot cache it

### ISSUE THREAD

**Issue by uriva** [denoland/deno#21657] opened 2023-12-20 15:21 UTC
1.39.0

In vscode I see this error:

```
Uncached or missing npm package: title-case deno(no-cache-npm)
Resolved Dependency

Code: npm​:title-case
```
for this code
```ts
import { titleCase } from "npm:title-case";
```

Caching it has no effect on the error.

more info:
```
$ deno info npm:title-case
dependencies: 0 unique
size: 5.05KB

npm:/title-case@4.0.0 (5.05KB)
```

running `deno cache` on the file has no effect on this error.

**Comment by nayeemrmn** [comment] 2024-01-02 06:10
I can't reproduce on 1.39.1. If you cache with the quick fix it loads and the diagnostic disappears. If you cache with the CLI, make a change in the document or save it and the diagnostic will disappear.

Check the output panel for the extension when you cache with the quick fix and see if there's an informative error there. Closing for now.

**Closed by nayeemrmn** 2024-01-02 06:10 UTC
Labels: bug, lsp

**Comment by uriva** [comment] 2024-01-02 11:42
still happening on 1.39.1

deleting the entries in deno.lock and recaching worked

**Comment by bombillazo** [comment] 2024-03-03 06:30
thanks @uriva !!!
