### ISSUE TITLE
Deno install not working without a version tag

### ISSUE THREAD

**Issue by checkerschaf** [denoland/deno#7555] opened 2020-09-18 13:04 UTC
Hi,

I just found out that `deno install` is not working properly if the version of a module has not been specified. Without a version tag only one file is downloaded and therefore the installed program does not work due to missing depedencies.
I think it has something to do with the redirect happening but it's just an idea.

**How to reproduce?**
This does not work properly:
`deno install --allow-net -f -n sherlock https://deno.land/x/sherlock/cli.ts`
This does:
`deno install --allow-net -f -n sherlock https://deno.land/x/sherlock@v1.6.0/cli.ts`

I think the first command should have the same results as manually setting the version to let users always install the newest version automatically.

**Comment by lucacasonato** [comment] 2020-09-18 13:21
The issue seems to be that `deno bundle` does not handle redirects for the entrypoint correctly.

**Comment by kitsonk** [comment] 2020-09-18 20:57
Which is #3082. Another reason we need to revert the bundle on install until we resolve some bundle issues. I should be able to start looking at all of this very soon.

**Comment by lucacasonato** [comment] 2020-09-18 21:01
Install using bundle was reverted in 1.4.1 which was just released. The redirect issue is a dupe of #3082 like Kitson said.

**Closed** 2020-09-18 21:00 UTC
Labels: bug, cli
