### ISSUE TITLE
HTTPS server ConnectionReset: Connection reset by peer (os error 104)

### ISSUE THREAD

**Issue by iugo** [denoland/deno#7378] opened 2020-09-07 10:21 UTC
When I run an HTTPS server, somehow a request will trigger a panic error.

ConnectionReset: Connection reset by peer (os error 104)

```
error: Uncaught ConnectionReset: Connection reset by peer (os error 104)
  at unwrapResponse (rt/10_dispatch_json.js:24:13)
  at sendAsync (rt/10_dispatch_json.js:75:12)
  at async TLSListener.accept (rt/40_tls.js:42:19)
  at async Server.acceptConnAndIterateHttpRequests (file:///server/dist.server.js:1714:32)
  at async MuxAsyncIterator.callIteratorNext (file:///server/dist.server.js:797:49)
```

<img width="595" alt="Screen Shot 2020-09-07 at 18 16 30" src="https://user-images.githubusercontent.com/499364/92377143-42d4ed00-f136-11ea-91a1-75d006393c16.png">

<img width="671" alt="Screen Shot 2020-09-07 at 18 17 07" src="https://user-images.githubusercontent.com/499364/92377189-58e2ad80-f136-11ea-959b-449fbd880ba9.png">

**Comment by timonson** [comment] 2020-09-19 13:49
This happened to me, too. I was using a static https file server with the Oak framework. The error appeared nondeterministicly on both Ubuntu and Debian. There must be a bug somewhere which should get much more attention here because it makes the Deno https server useless and I had to switch to node.

**Comment by rvdende** [comment] 2020-10-25 17:06
I've been battling this as well.

```bash
% deno --version
deno 1.4.6
v8 8.7.220.3
typescript 4.0.3
```

```bash
error: Uncaught ConnectionReset: Connection reset by peer (os error 104)
    at unwrapResponse (deno:cli/rt/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:cli/rt/10_dispatch_minimal.js:98:12)
    at async write (deno:cli/rt/12_io.js:117:20)
    at async Object.writeAll (deno:cli/rt/13_buffer.js:223:19)
    at async BufWriter.flush (bufio.ts:468:7)
    at async BufWriter.write (bufio.ts:507:9)
    at async writeResponse (_io.ts:273:15)
    at async ServerRequest.respond (server.ts:84:7)
    at async Response.end (response.ts:218:5)
```

It seems no matter where I put my try catch the error remains uncaught. I'm using opine + TLS by the way.. it seems to be some kind of race condition and difficult to reliably reproduce.

**Comment by timonson** [comment] 2020-10-25 17:14
@rvdende please take a look at this issue here https://github.com/denoland/deno/issues/8107 .
Is this happening to you?

**Comment by rvdende** [comment] 2020-10-25 17:19
@timonson thank you. I've indeed had a similar error log before, so its quite possibly related or the same issue.

**Comment by lucacasonato** [comment] 2020-10-26 00:00
I'm going to close this as a duplicate of #8107 as it has more traction. Thanks for reporting :-)

**Closed** 2020-10-26 00:00 UTC

**Comment by GabCores** [comment] 2022-05-19 13:18
occurs sometimes on incoming messages without any visible reason
Deno 1.22.0
 using "https://deno.land/std/http/server.ts" as Web Socket on Deno Deploy

**Comment by Lolicchi** [comment] 2022-07-05 09:55
Happened with me too just now, with a websocket connection and when i tried to reconnect to the websocket again, it took 10 minutes to trigger `Websocket.onopen`

**Comment by js-writer** [comment] 2022-09-04 07:48
Happened to me. Im using deno 1.24.0 and hoisting it at railway.app.
After few hour my login path stop working and I got this error:
`ConnectionReset: Connection reset by peer (os error 104)
at async read (deno:ext/net/01_net.js:28:19)
at async BufReader.read (https://deno.land/std@0.141.0/io/buffer.ts:383:12)
at async BufReader.readFull (https://deno.land/std@0.141.0/io/buffer.ts:415:20)
at async Connection.#readMessage (https://deno.land/x/postgres@v0.16.1/connection/connection.ts:159:5)`

and when I try my login path again I got this:

`BrokenPipe: Broken pipe (os error 32)
at async write (deno:ext/net/01_net.js:33:12)
at async BufWriter.flush (https://deno.land/std@0.141.0/io/buffer.ts:748:21)`
