### ISSUE TITLE
Deno eval script into string

### ISSUE THREAD

**Issue by SRNV** [denoland/deno#5107] opened 2020-05-06 16:15 UTC
```
        req.respond({ body: renderApp(`
        <body>
          <script type="module">
            import server from 'https://unpkg.com/browse/html-dom-parser@0.1.3/dist/html-dom-parser.min.js';
            console.warn(server)
          </script>
        </body>
        `) });
```
throws:

```
Download https://unpkg.com/browse/html-dom-parser@0.1.3/dist/html-dom-parser.min.js
error: Uncaught TypeError: Cannot resolve extension for "https://unpkg.com/browse/html-dom-parser@0.1.3/dist/html-dom-parser.min.js" with mediaType "Unknown".
    at getExtension ($deno$/compiler/sourcefile.ts:42:13)
    at new SourceFile ($deno$/compiler/sourcefile.ts:70:22)
    at processImports ($deno$/compiler/imports.ts:122:45)
    at async Object.processImports ($deno$/compiler/imports.ts:125:7)
    at async compile (file:///home/runner/work/deno/deno/cli/js/compiler.ts:144:31)
    at async tsCompilerOnMessage (file:///home/runner/work/deno/deno/cli/js/compiler.ts:359:22)
    at async workerMessageRecvCallback ($deno$/runtime_worker.ts:73:9)
```

import in string should not be evaluated

**Comment by nayeemrmn** [comment] 2020-05-06 21:30
Duplicate of #3089. Use regular double quotes around the import statement to work around this.

**Closed** 2020-05-06 22:00 UTC
