### ISSUE TITLE
Broken pipe with deno. 

### ISSUE THREAD

**Issue by BayoKwendo** [denoland/deno#8830] opened 2020-12-19 14:38 UTC
Any hope??? after keen monitoring it crushes   . 12 - 24 hrs  

BrokenPipe: Broken pipe (os error 32) 
    at unwrapResponse (deno:cli/rt/10_dispatch_minimal.js:59:13)
    at sendAsync (deno:cli/rt/10_dispatch_minimal.js:98:12)
     at async write (deno:cli/rt/12_io.js:117:20)
    at async Object.writeAll (deno:cli/rt/13_buffer.js:223:19)
    at async BufWriter.flush (bufio.ts:468:7)
    at async writeResponse (_io.ts:288:3)
    at async Server.iterateHttpRequests (server.ts:154:11)
    at async Server.acceptConnAndIterateHttpRequests (server.ts:227:5)
     at async MuxAsyncIterator.callIteratorNext (mux_async_iterator.ts:30:31)

**Comment by timonson** [comment] 2021-02-12 00:35
Maybe a duplicate of this [https://github.com/denoland/deno_std/issues/659](https://github.com/denoland/deno_std/issues/659)?

**Comment by kitsonk** [comment] 2021-02-12 01:16
Duplicate of denoland/deno_std#659

**Closed by kitsonk** 2021-02-12 01:16 UTC
Labels: duplicate
