### ISSUE TITLE
The new JSX transform doesn't work with preact from config(deno.json)

### ISSUE THREAD

**Issue by ije** [denoland/deno#13288] opened 2022-01-05 09:49 UTC
The new JSX transform don't support preact from `deno.json`:

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/preact",
    "lib": [
      "dom",
      "deno.ns"
    ]
  }
}
```

but with `@jsxImportSource` comment works:

```tsx
/** @jsxImportSource https://esm.sh/preact */

export default () => <h1>Hi</h1>
```

__

deno 1.17.1 (release, aarch64-apple-darwin)
v8 9.7.106.15
typescript 4.5.2

**Comment by kitsonk** [comment] 2022-01-05 09:52
@ije what does your command line look like and when you say "don't support" can you provide what you are actually experiencing

**Comment by ije** [comment] 2022-01-05 10:04
```jsonc
// deno.json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/preact",
    "lib": [
      "dom",
      "deno.ns"
    ]
  }
}
```
```tsx
// main.tsx
export default () => <h1>Hi</h1>
```
<img width="876" alt="Screen Shot 2022-01-05 at 18 04 30" src="https://user-images.githubusercontent.com/2883484/148199340-235ee862-169c-4409-8cbd-e4c5bbdc30f4.png">

**Comment by ije** [comment] 2022-01-05 10:08
```jsonc
// deno.json
{
  "compilerOptions": {
    "lib": [
      "dom",
      "deno.ns"
    ]
  }
}
```

```tsx
/** @jsxImportSource https://esm.sh/preact */

export default () => <h1>Hi</h1>
```
this works as expected.

**Comment by ije** [comment] 2022-01-05 10:10
```jsonc
// deno.json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/react",
    "lib": [
      "dom",
      "deno.ns"
    ]
  }
}
```
```tsx
// main.tsx
export default () => <h1>Hi</h1>
```
react works as well.

**Comment by lucacasonato** [comment] 2022-08-24 22:30
Duplicate of #14723

**Closed by lucacasonato** 2022-08-24 22:30 UTC
Labels: bug, cli, needs investigation
