### ISSUE TITLE
[Bug] Deno language server panics in VsCode

### ISSUE THREAD

**Issue by PoignardAzur** [denoland/deno#19381] opened 2023-06-06 11:33 UTC
Error log:

```shell
Starting Deno language server...
  version: 1.34.1 (release, x86_64-unknown-linux-gnu)
  executable: /home/olivier-faure/.cargo/bin/deno
Connected to "Visual Studio Code" 1.78.2
Enabling import suggestions for: https://deno.land
Server ready.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.34.1
Args: ["/home/olivier-faure/.cargo/bin/deno", "lsp"]

thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', /home/olivier-faure/.cargo/registry/src/index.crates.io-6f17d22bba15001f/dprint-swc-ext-0.9.0/src/view/generated.rs:14469:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
[Info  - 1:25:24 PM] Connection to server got closed. Server will restart.
```

[Full log here](https://gist.github.com/PoignardAzur/b25b3dee719c51ec9c274ce2dd41c681), though it's mostly the same on loop.

The error reccommends running the language server with RUST_BACKTRACE=1, but I don't know how to do that from VsCode. I installed deno with `cargo install`.

`deno lsp` alone doesn't give me any error.

**Comment by dsherret** [comment] 2023-06-06 19:30
Duplicate of #19148

You can fix this by using a pre-compiled binary, compile with an older version of Rust (1.68 and lower), or wait until the next release later this week.

**Closed by dsherret** 2023-06-06 19:30 UTC
Labels: duplicate
