### ISSUE TITLE
Top level await in REPL

### ISSUE THREAD

**Issue by pannous** [denoland/deno#5446] opened 2020-05-15 09:35 UTC
Please run the topmost context in async mode, or allow top level await, akin to

https://bugs.chromium.org/p/v8/issues/detail?id=9344

**Comment by SyrupThinker** [comment] 2020-05-15 09:43
Top level await is already supported, see [here](https://github.com/denoland/deno/issues/471).
Please check out said issue in case your particular issue has already been discussed there.

**Comment by pannous** [comment] 2020-05-15 09:48
Sorry reading through the link's comments I couldn't find the option to support this feature
```
> deno
Deno 1.0.0
exit using ctrl+d or close()
> console.log(await Promise.resolve('Success'))
  
> await fetch('http://a.com')
Uncaught SyntaxError: await is only valid in async function
```

**Comment by bartlomieju** [comment] 2020-05-15 10:10
Duplicate of https://github.com/denoland/deno/issues/3029

**Closed by bartlomieju** 2020-05-15 10:10 UTC
