### ISSUE TITLE
"Cannot convert a BigInto value to a number" when using `exists` from `jsr:@std/fs`

### ISSUE THREAD

**Issue by matt1** [denoland/deno#27443] opened 2024-12-21 20:55 UTC
```
> deno --version
deno 2.1.4 (stable, release, x86_64-pc-windows-msvc)
v8 13.0.245.12-rusty
typescript 5.6.2
```
As per the description, when using  `import { exists } from "jsr:@std/fs"` it will fail with this error when trying to check if a 2700kb file in the local directory exists or not:

```
error: Uncaught (in promise) TypeError: Cannot convert a BigInt value to a number
    const stat = await Deno.stat(path);
                 ^
    at new Date (<anonymous>)
    at parseFileInfo (ext:deno_fs/30_fs.js:381:41)
    at Object.stat (ext:deno_fs/30_fs.js:410:10)
    at eventLoopTick (ext:core/01_core.js:175:7)
    at async exists (https://jsr.io/@std/fs/1.0.6/exists.ts:129:18)
    at <...>
```

In case it matters the file system being used is exFAT.

**Comment by matt1** [comment] 2024-12-21 21:42
I applied a horrible hack to get around using `exists` (just try reading a file in a try-catch block), but it seems to also cause the same error when using `serveDir` too.

Can Deno not handle exFAT filesystems?  As far as I know this filesystem is the standard one used for all external media, so not being able to access files on it seems like a bit of a limitation for certain use-cases.

**Comment by matt1** [comment] 2024-12-21 21:55
Breakage appears to have been introduced in this commit? https://github.com/denoland/deno/commit/7becd83a3828b35331d0fcb82c64146e520f154b

**Comment by dsherret** [comment] 2024-12-21 23:55
Duplicate of https://github.com/denoland/deno/issues/27286

**Closed by dsherret** 2024-12-21 23:55 UTC
Labels: duplicate
