### ISSUE TITLE
run locally built npm executable script

### ISSUE THREAD

**Issue by jjallaire** [denoland/deno#19298] opened 2023-05-28 12:04 UTC
Is there currently a way to run a locally built npm executable script using `deno run`. I'm thinking of something like this:

```bash
deno run --allow-env --allow-read npm:<local-path>
```

The scenario is running node code that we don't to publish to a public repository.

I discovered the `createRequire` method, e.g.

```javascript
import { createRequire } from "node:module";
const require = createRequire(import.meta.url);
require("./script.js");
```

However, the script has some behavior that isn't handled well including a dynamic `import()` of an `mjs` module as well as Mathjax which might also do some non-standard importing?  I'm guessing that `deno run` for `npm` scripts might setup some additional facilities to make more scenarios work properly than `createRequire` does?

Anyway, if there is a way to do this for local npm executable scripts it would be fabulous!

**Comment by bartlomieju** [comment] 2023-05-28 23:31
I believe this is a duplicate of https://github.com/denoland/deno/issues/15624 so let's keep track of it there. We'll try to prioritize this feature over the coming weeks.

**Closed by bartlomieju** 2023-05-28 23:31 UTC

**Comment by jjallaire** [comment] 2023-06-02 11:15
Thanks! This would be hugely valuable for us as we are currently contemplating shipping a version of the node runtime to make this work. That would be such a shame given that Deno has all of the underlying capability required to make this happen. Once you have a version of this ready for testing on a branch we are happy to put it through its paces, provide feedback, etc.
