### ISSUE TITLE
Type check error

### ISSUE THREAD

**Issue by 0x018** [denoland/deno#8183] opened 2020-10-29 04:17 UTC
### action:
deno run --allow-read --allow-net  xxx.ts

### result:

**Check** file:///....../xxx.ts

**error**: TS2322 [ERROR]: Type `'import("https://deno.land/std@0.75.0/http/server.ts").ServerRequest | null'` is not assignable to type `'import("https://deno.land/std/http/server.ts").ServerRequest | null'`.

  Type `'import("https://deno.land/std@0.75.0/http/server.ts").ServerRequest'` is not assignable to type `'import("https://deno.land/std/http/server.ts").ServerRequest'`.

    Types have separate declarations of a private property '_contentLength'.
        request = await readRequest(conn, reader);
        ~~~~~~~
    at https://deno.land/std/http/server.ts:147:9

**Comment by 0x018** [comment] 2020-10-29 04:19
If `--no-check` is added, it runs successfully.

**Comment by kitsonk** [comment] 2020-10-29 04:42
Duplicate of #8154 which is fixed in `master` and will be part of 1.5.1.

**Closed by kitsonk** 2020-10-29 04:42 UTC
