### ISSUE TITLE
LSP incorrectly gives error on npm imports when there is no package.json or deno.json

### ISSUE THREAD

**Issue by ry** [denoland/deno#24951] opened 2024-08-08 13:15 UTC
Version: Deno 1.45.5

<img width="1199" alt="Screenshot 2024-08-08 at 9 13 34 AM" src="https://github.com/user-attachments/assets/a73b4d42-39d0-4ab7-ad88-0c6af577851a">

**Comment by dsherret** [comment] 2024-08-08 14:06
@ry is this with DENO_FUTURE=1?

**Comment by dsherret** [comment] 2024-08-08 14:08
Duplicate of #24863

**Closed by dsherret** 2024-08-08 14:08 UTC
