### ISSUE TITLE
REPL chokes on lone surrogates

### ISSUE THREAD

**Issue by bnoordhuis** [denoland/deno#10542] opened 2021-05-08 21:45 UTC
At commit 4ed1428c3.
```
$ deno
Deno 1.9.2
exit using ctrl+d or close()
> "\ud834"
Uncaught "Unterminated string literal"
```
Node.js in comparison prints a replacement character:
```
> "\ud834"
'�'
```
More real-world scenario:
```
> JSON.parse(Deno.readTextFileSync("tools/wpt/expectation.json"))["encoding"]
Unterminated string literal
```
Also affects e.g. `console.log()`. I suspect it's caused by serde_v8.

**Comment by AaronO** [comment] 2021-05-09 21:29
@bnoordhuis I don't think it's related to `serde_v8`, bug is in the `1.7.0` release, which is well before `serde_v8` existed.

```
~/git/deno main
❯ deno upgrade --version 1.7.0
Checking https://github.com/denoland/deno/releases/download/v1.7.0/deno-aarch64-apple-darwin.zip
Download has been found
Deno is upgrading to version 1.7.0
Archive:  /var/folders/p0/t3q1dqy57fsdfqtvxqgbp04m0000gn/T/.tmpFwtJTo/deno..zip
  inflating: deno
Upgraded successfully

~/git/deno main
❯ deno
Deno 1.7.0
exit using ctrl+d or close()
> "\ud834"
Uncaught "Unterminated string literal"
>
```

**Comment by bnoordhuis** [comment] 2021-10-06 20:59
Bug triage: still happens with c4b995ffe.

**Comment by AaronO** [comment] 2021-10-08 00:08
The root issue here is that we use `serde_json` in `core/inspector.rs` (and elsewhere) and it requires`\u` escape sequences to represent valid Unicode code points.

**Comment by littledivy** [comment] 2024-06-13 11:42
Still happens with 1.44.2:
```
[divy@divy deno]$ deno
Deno 1.44.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> "\ud834"
Unterminated string literal Unknown exception
```

**Comment by lucacasonato** [comment] 2024-09-19 09:41
Duplicate of #14664

**Closed by lucacasonato** 2024-09-19 09:41 UTC
Labels: bug, repl
