### ISSUE TITLE
Use of `jsxImportSource` breaks `deno bundle`

### ISSUE THREAD

**Issue by jed** [denoland/deno#14233] opened 2022-04-07 17:06 UTC
Per [this convo](https://discord.com/channels/684898665143206084/684898665151594506/961668940680011796), given the following `deno.json`:

```json
{
  "compilerOptions": {
    "jsx": "react-jsx",
    "jsxImportSource": "https://esm.sh/preact"
  },
  "tasks": {
    "test": "deno run test.jsx",
    "bundle": "deno bundle test.jsx test.js"
  }
}
```

and the following `test.jsx`:

```
console.log(<div></div>)

export {}
```

running `deno task test` returns as expected:

```
Task test deno run test.jsx
{
  type: "div",
  props: {},
  key: undefined,
  ref: undefined,
  __k: null,
  __: null,
  __b: 0,
  __e: null,
  __d: undefined,
  __c: null,
  __h: null,
  constructor: undefined,
  __v: -1,
  __source: undefined,
  __self: undefined
}
```

but running `deno task bundle` throws an error:

```
Task bundle deno bundle test.jsx test.js
Check file:///........................../test.jsx
Bundle file:///........................./test.jsx
error: Unable to output during bundling.

Caused by:
    0: load_transformed failed
    1: failed to analyze module
    2: failed to resolve https://esm.sh/preact/jsx-runtime from file:///........................./test.jsx
    3: Cannot resolve "https://esm.sh/preact/jsx-runtime" from "file:///........................./test.jsx".
```

**Comment by dhardtke** [comment] 2022-04-30 00:44
Probably the same issue as https://github.com/denoland/deno/issues/13389 which includes an explanation for why this is happening and what needs to be done about it.

**Comment by kitsonk** [comment] 2022-04-30 09:58
Duplicate of #13389

**Closed by kitsonk** 2022-04-30 09:58 UTC
