### ISSUE TITLE
"deno bundle" emits syntactically invalid code.

### ISSUE THREAD

**Issue by mcmacker4** [denoland/deno#6764] opened 2020-07-15 13:43 UTC
### Description
When running `deno bundle` on the example code in the front page of http://deno.land/ the resulting code is invalid and throws a syntax error when running it with `deno run`.  
The code example is the following:
```ts
import { serve } from "https://deno.land/std@0.61.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

### Environment
This was tested on Deno 1.2.0 on both Windows 10 installed using the powershell script on the front page, and Arch Linux installed using the aur package `deno-bin`.
`deno --version` on windows reports the following:
```
deno 1.2.0
v8 8.5.216
typescript 3.9.2
```

### Steps to reproduce
1. Save the example code to a file `server.ts`
2. Run the command `deno bundle server.ts server.bundle.js`
3. Run the command `deno run --allow-net server.bundle.js`

### Expected Behaviour
The code should run correctly. The original does work when executing `deno run --allow-net server.ts` (`server.ts` being the original code example)

### Actual Result
The command fails throwing a `SyntaxError`:
```
error: Uncaught SyntaxError: Unexpected reserved word
            for await (const req of s) {
                ~~~~~
    at file:///<redacted path>/server.bundle.js:1715:17
```

### Cause
When inspecting the emitted code `server.bundle.js`, at the line reported in the error there is an invalid `await` keyword in the scope of a non-`async` function.

```js
execute: function () {
  s = server_ts_2.serve({ port: 8000 });
  console.log("http://localhost:8000/");
  for await (const req of s) {
    req.respond({ body: "Hello World\n" });
  }
}
```

**Comment by bartlomieju** [comment] 2020-07-15 13:46
Duplicate of #4207

**Comment by mcmacker4** [comment] 2020-07-15 13:51
Oh apologies, i guess my issue searching skills are not as good as i thought.
Might as well close this one then.

**Closed** 2020-07-15 13:52 UTC
