### ISSUE TITLE
[LSP] Intermittent Rust panic: "called `Option::unwrap()` on a `None` value"

### ISSUE THREAD

**Issue by danopia** [denoland/deno#8881] opened 2020-12-24 21:15 UTC
I think this happens when using the autocomplete UI but I haven't been able to pin down a repro yet.

I've seen two different stack traces so far, this one happened once today on 1.6.1:

```
Starting Deno language server...
  version: 1.6.1 (release, x86_64-unknown-linux-gnu)
Connected to "vscode" 1.51.1
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/lsp/tsc.rs:693:41
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: core::option::Option<T>::unwrap
   4: deno::lsp::tsc::cache_snapshot
   5: deno_core::ops::json_op_sync::{{closure}}
   6: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
   7: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
   8: Builtins_CallApiCallback
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
```

This one happened a bunch both before and after upgrading to 1.6.2:

```
Starting Deno language server...
  version: 1.6.2 (release, x86_64-unknown-linux-gnu)
Connected to "vscode" 1.51.1
language server initialized
Server ready.
thread '<unnamed>' panicked at 'called `Option::unwrap()` on a `None` value', cli/lsp/tsc.rs:691:43
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::panicking::panic
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:50
   3: core::option::Option<T>::unwrap
   4: deno::lsp::tsc::cache_snapshot
   5: deno_core::ops::json_op_sync::{{closure}}
   6: <alloc::boxed::Box<F> as core::ops::function::Fn<A>>::call
   7: <extern "C" fn(A0) .> R as rusty_v8::support::CFnFrom<F>>::mapping::c_fn
   8: _ZN2v88internal25FunctionCallbackArguments4CallENS0_15CallHandlerInfoE
   9: _ZN2v88internal12_GLOBAL__N_119HandleApiCallHelperILb0EEENS0_11MaybeHandleINS0_6ObjectEEEPNS0_7IsolateENS0_6HandleINS0_10HeapObjectEEESA_NS8_INS0_20FunctionTemplateInfoEEENS8_IS4_EENS0_16BuiltinArgumentsE
  10: _ZN2v88internalL26Builtin_Impl_HandleApiCallENS0_16BuiltinArgumentsEPNS0_7IsolateE
  11: Builtins_CEntry_Return1_DontSaveFPRegs_ArgvOnStack_BuiltinExit
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
fatal runtime error: failed to initiate panic, error 5
[Info  - 9:57:56 PM] Connection to server got closed. Server will restart.
```

**Comment by danopia** [comment] 2020-12-24 22:47
I just noticed that the following Code stacktraces mention what request was in-flight when the LSP panics. So the most recent ones have all been `Request textDocument/hover failed.`. Will update this comment if I see others.

**Comment by kitsonk** [comment] 2020-12-25 03:00
Ok, it appears to be that a request is being made for a file that we think should be in the memory of the lsp but isn't.  It is potentially some sort of race condition, since the lsp works asynchronously, and we need to handle it a bit more gracefully.  I suspect it would be really hard to reproduce reliably, because of the nature where the code is.

Will look to into trying to give more diagnostic information and see if we can recover more gracefully here.  Likely will take a day or two.

**Comment by lucacasonato** [comment] 2020-12-25 19:19
> It is potentially some sort of race condition, since the lsp works asynchronously, and we need to handle it a bit more gracefully.

I was pretty certain this was going to be the case when I implemented the async TSC code. I have some ideas on how to clean this up - most notably to not send over state on each request, but rather sending over references to the arc mutexes containing the state when the tsc thread gets started. I will give this a pass after the holidays.

**Comment by danopia** [comment] 2021-04-19 11:31
I haven't seen a panic from LSP in a while... this issue is likely outdated now?

**Comment by kitsonk** [comment] 2021-04-19 11:35
I think we made some changes to do better with the locking, so hopefully these sorts of things gone.  Closing for now.

**Closed by kitsonk** 2021-04-19 11:35 UTC
Labels: bug, lsp
