### ISSUE TITLE
Exception for missing ops in `OP_DETAILS`

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#13938] opened 2022-03-13 19:17 UTC
If an async op is not listed in the `OP_DETAILS` map in `40_testing.js`, you can get the following exception:

```
TypeError: undefined is not iterable (cannot read property Symbol(Symbol.iterator))
    at asyncOpSanitizer (deno:runtime/js/40_testing.js:177:32)
    at async resourceSanitizer (deno:runtime/js/40_testing.js:369:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:426:9)
    at async runTest (deno:runtime/js/40_testing.js:786:7)
    at async Object.runTests (deno:runtime/js/40_testing.js:984:22)
```

Presumably some fallback message should show up in these cases, in case a new op is mistakenly left out, and for ease of development.

Additionally, some async ops related to resources (`op_read`, `op_write`, `op_shutdown`) and workers (`op_host_recv_ctrl`, `op_host_recv_message`) are currently missing.

**Comment by bartlomieju** [comment] 2022-03-13 23:44
Seems like a duplicate of https://github.com/denoland/deno/issues/13729

**Closed** 2022-03-22 23:24 UTC
Labels: bug
