### ISSUE TITLE
feat: LSP should suggest `@ts-types` for npm packages with missing types

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25033] opened 2024-08-14 09:36 UTC
I just ran into a situation where `markdown-it`, an npm package, doesn't ship with types. The DefinitelyTyped project fills that gap with the [`@types/markdown-it`](https://github.com/DefinitelyTyped/DefinitelyTyped/tree/master/types/markdown-it) package. In deno we have the `@ts-types` comment to help with that (previously called `@deno-types`).

```
// @ts-types="@types/markdown-it"
import md from "markdown-it";
```

The thing is that we don't teach users about this anywhere, other than on [this page](https://docs.deno.com/runtime/manual/advanced/typescript/types/) in our documentation. To be able to find this page we expect users to already know about what they are looking for.

The only feedback users get in the IDE is that autocompletion isn't working and `cmd+click` does nothing for some unknown reason.

https://github.com/user-attachments/assets/2b5736dc-8418-4fcf-a38a-42e381f56a34

I feel like this is a great opportunity in the LSP to provide a quick fix that checks if we're dealing with an `npm:` package, checks if there are type definitions on DT and suggests to add them as a type comment:

```ts
// @ts-types="@types/markdown-it"
import md from "markdown-it";
```

Version: Deno 1.46.0-rc.0+e2faf50

**Comment by dsherret** [comment] 2024-08-14 13:14
Duplicate of https://github.com/denoland/deno/issues/18884

**Closed by dsherret** 2024-08-14 13:14 UTC
Labels: feat, duplicate, lsp
