### ISSUE TITLE
Private properties not printed by console.log

### ISSUE THREAD

**Issue by carragom** [denoland/deno#8288] opened 2020-11-08 03:57 UTC
Hello,
I was trying to debug a small app and was surprised when `console.log` did not print the private properties of a class. I ran the code in Chrome and it printed the private property. So at least there is an inconsistency between Chrome and Deno. I would say private properties should be logged by `console.log` and friends, i.e.: `debug`, `warn`, `error` and `trace`. It's very useful for debugging purposes. Is this intended behavior?

## Example
```typescript
class Test {
  #q = "qwe"
  a = "asd"
}
let t = new Test()
console.log(t)
```
## Deno Result
![image](https://user-images.githubusercontent.com/970403/98456457-81415500-2143-11eb-9cb2-de99f1e2430a.png)

## Chrome Result
<img width="237" alt="image" src="https://user-images.githubusercontent.com/970403/98456426-f5c7c400-2142-11eb-82d2-7737862fe53c.png">

**Comment by kitsonk** [comment] 2020-11-08 04:08
Duplicate of #2528

**Closed by kitsonk** 2020-11-08 04:08 UTC
Labels: duplicate :dancers:
