### ISSUE TITLE
Deno panic error

### ISSUE THREAD

**Issue by swiftsword94** [denoland/deno#18915] opened 2023-04-29 14:11 UTC
I found this one while trying to debug a db migration script (using postgres-js and drizzle-orm esm imports) that was throwing an error for:

error: Uncaught TypeError: Class constructor Socket cannot be invoked without 'new'
    at Ht (https://esm.sh/v117/postgres@3.3.4/deno/postgres.mjs:2:11812)
    at Et (https://esm.sh/v117/postgres@3.3.4/deno/postgres.mjs:2:14598)
    at Object.action (ext:deno_web/02_timers.js:147:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:64:10)
    at eventLoopTick (ext:core/01_core.js:171:21)

It seems to be related to setting a breakpoint for caught exceptions in vscode.

Deno panic error below:

Debugger listening on ws://127.0.0.1:9229/ws/083d113d-e7fc-4652-8c08-2f5ebfe63e9a
Visit chrome://inspect to connect to the debugger.
Deno is waiting for debugger to connect.
Debugger session started.

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.32.5
Args: ["C:\\Users\\squid\\.deno\\bin\\deno.EXE", "run", "--inspect-brk", "--allow-all", ".\\db\\drizzle-seed.ts"]

thread 'main' panicked at 'already borrowed: BorrowMutError', runtime\ops\os\mod.rs:106:1
stack backtrace:
   0:     0x7ff69e110449 - napi_release_threadsafe_function
   1:     0x7ff69d35a5db - napi_release_threadsafe_function
   2:     0x7ff69e0eae0a - napi_release_threadsafe_function
   3:     0x7ff69e114b5b - napi_release_threadsafe_function
   4:     0x7ff69e114751 - napi_release_threadsafe_function
   5:     0x7ff69e114365 - napi_release_threadsafe_function
   6:     0x7ff69d1f0bac - napi_fatal_error
   7:     0x7ff69e1153a7 - napi_release_threadsafe_function
   8:     0x7ff69e115116 - napi_release_threadsafe_function
   9:     0x7ff69e11505f - napi_release_threadsafe_function
  10:     0x7ff69e115034 - napi_release_threadsafe_function
  11:     0x7ff69f40e205 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff69f40e6c6 - CrashForExceptionInNonABICompliantCodeRange
  13:     0x7ff69dae02a8 - napi_release_threadsafe_function
  14:     0x7ff69e6a6ed5 - CrashForExceptionInNonABICompliantCodeRange
  15:     0x7ff69e6a647d - CrashForExceptionInNonABICompliantCodeRange
  16:     0x7ff69f1cc479 - CrashForExceptionInNonABICompliantCodeRange
  17:     0x7ff69f13ccec - CrashForExceptionInNonABICompliantCodeRange
  18:     0x7ff69f13ccec - CrashForExceptionInNonABICompliantCodeRange
  19:     0x7ff69f13b25c - CrashForExceptionInNonABICompliantCodeRange
  20:     0x7ff69f13ae5b - CrashForExceptionInNonABICompliantCodeRange
  21:     0x7ff69e4c50e4 - napi_release_threadsafe_function
  22:     0x7ff69e4c4777 - napi_release_threadsafe_function
  23:     0x7ff69e891c46 - CrashForExceptionInNonABICompliantCodeRange
  24:     0x7ff69e891adb - CrashForExceptionInNonABICompliantCodeRange
  25:     0x7ff69e86c7a3 - CrashForExceptionInNonABICompliantCodeRange
  26:     0x7ff69e630d10 - CrashForExceptionInNonABICompliantCodeRange
  27:     0x7ff69e6093ee - CrashForExceptionInNonABICompliantCodeRange
  28:     0x7ff69e5e018b - CrashForExceptionInNonABICompliantCodeRange
  29:     0x7ff69e395500 - napi_release_threadsafe_function
  30:     0x7ff69e36154f - napi_release_threadsafe_function
  31:     0x7ff69e31fa5f - napi_release_threadsafe_function
  32:     0x7ff69d4963b7 - napi_release_threadsafe_function
  33:     0x7ff69e31f887 - napi_release_threadsafe_function
  34:     0x7ff69e5c89d7 - CrashForExceptionInNonABICompliantCodeRange
  35:     0x7ff69e5c8d4f - CrashForExceptionInNonABICompliantCodeRange
  36:     0x7ff69e6af7b7 - CrashForExceptionInNonABICompliantCodeRange
  37:     0x7ff69e6af37e - CrashForExceptionInNonABICompliantCodeRange
  38:     0x7ff69e4484cf - napi_release_threadsafe_function
  39:     0x7ff69e447c07 - napi_release_threadsafe_function
  40:     0x7ff69e3731e5 - napi_release_threadsafe_function
  41:     0x7ff69e35ebcd - napi_release_threadsafe_function
  42:     0x7ff69db9085a - napi_release_threadsafe_function
  43:     0x7ff69e6a6ed5 - CrashForExceptionInNonABICompliantCodeRange
  44:     0x7ff69e6a647d - CrashForExceptionInNonABICompliantCodeRange
  45:     0x7ff69f1cc479 - CrashForExceptionInNonABICompliantCodeRange
  46:     0x7ff69f13ccec - CrashForExceptionInNonABICompliantCodeRange
  47:     0x7ff69f13ccec - CrashForExceptionInNonABICompliantCodeRange
  48:     0x7ff69f13ccec - CrashForExceptionInNonABICompliantCodeRange
  49:     0x7ff69f13ccec - CrashForExceptionInNonABICompliantCodeRange
  50:     0x7ff69f17a940 - CrashForExceptionInNonABICompliantCodeRange
  51:     0x7ff69f13b25c - CrashForExceptionInNonABICompliantCodeRange
  52:     0x7ff69f13ae5b - CrashForExceptionInNonABICompliantCodeRange
  53:     0x7ff69e4c50e4 - napi_release_threadsafe_function
  54:     0x7ff69e4c5c85 - napi_release_threadsafe_function
  55:     0x7ff69e4c5e5d - napi_release_threadsafe_function
  56:     0x7ff69e4ce76a - napi_release_threadsafe_function
  57:     0x7ff69e4cde0a - napi_release_threadsafe_function
  58:     0x7ff69e4cdcf7 - napi_release_threadsafe_function
  59:     0x7ff69e4cd886 - napi_release_threadsafe_function
  60:     0x7ff69e4c82ff - napi_release_threadsafe_function
  61:     0x7ff69e37175f - napi_release_threadsafe_function
  62:     0x7ff69e36172d - napi_release_threadsafe_function
  63:     0x7ff69d53b876 - napi_release_threadsafe_function
  64:     0x7ff69cd9bd99 - <unknown>
  65:     0x7ff69d1bee33 - napi_fatal_error
  66:     0x7ff69d1bbfc8 - napi_fatal_error
  67:     0x7ff69d1bba1a - napi_fatal_error
  68:     0x7ff69d17f32d - napi_fatal_error
  69:     0x7ff69d1cfcbc - napi_fatal_error
  70:     0x7ff69d1f627f - napi_fatal_error
  71:     0x7ff69ce92716 - napi_cancel_async_work
  72:     0x7ff69cd988a8 - <unknown>
  73:     0x7ff69d1f177f - napi_fatal_error
  74:     0x7ff69cdeca4a - <unknown>
  75:     0x7ff69d2da223 - napi_release_threadsafe_function
  76:     0x7ff69f3c132c - CrashForExceptionInNonABICompliantCodeRange
  77:     0x7ff8dfff269d - BaseThreadInitThunk
  78:     0x7ff8e07ca9f8 - RtlUserThreadStart

**Comment by bartlomieju** [comment] 2023-05-13 22:05
Hey @swiftsword94 thanks for the report. Could you provide a reproduction code you used to trigger that error?

**Comment by bartlomieju** [comment] 2023-08-03 23:38
I'm gonna close this for now, since I can't repeat the problem. I will reopen once a reproduction is available.

**Closed by bartlomieju** 2023-08-03 23:38 UTC
Labels: bug, node compat
