### ISSUE TITLE
v1.32.4 breaks web sockets

### ISSUE THREAD

**Issue by caramboleyo** [denoland/deno#18735] opened 2023-04-17 09:47 UTC
For some reason server now only pushes at the same time the browser client pulls something.
i use wss, establishing connection works fine, server onMessage works fine, but after using send on the server it just waits and does nothing until next incoming.

by downgrading to 1.32.3 everything works normal again.

Sidenote: with firefox websockets are waaaaay slower than with chrome.

**Comment by bartlomieju** [comment] 2023-04-17 11:12
This is already fixed by https://github.com/denoland/deno/commit/a4111442191fff300132259752e6d2d5613d1871

**Comment by caramboleyo** [comment] 2023-04-17 12:22
meaning it will be in the next release?

**Comment by bartlomieju** [comment] 2023-04-17 12:24
Correct, we will probably cut another patch release this week.

**Comment by caramboleyo** [comment] 2023-05-13 07:58
Last deno version were websockets were working properly is still 1.32.3
All versions later have issues.

**Comment by bartlomieju** [comment] 2023-05-13 22:09
@caramboleyo is there a reproduction code you could share that triggers this error?

**Comment by jespertheend** [comment] 2023-08-07 10:11
I can reproduce this, but only on secure websockets

**Comment by caramboleyo** [comment] 2023-08-07 12:07
They replaced this bug with another:
https://github.com/denoland/deno/issues/18977

**Comment by caramboleyo** [comment] 2023-08-07 18:10
I made a complex testcase now:
https://github.com/caramboleyo/deno-websocket-bug

**Comment by josephrocca** [comment] 2023-09-01 00:28
@bartlomieju @littledivy I just ran into something similar - v1.33.0 broke secure websockets - causes 20 second hangs when `send`ing more than ~20kb of data in certain cases. Non-secure (`ws://`) still work fine for me.

This script isn't particularly minimal, but it reproduces the problem I'm seeing: https://gist.github.com/josephrocca/ca159f837b351a9cd2dd31d728ed3ea9

As mentioned at the top of that file, just start the docker image, run [`cloudflared`](https://developers.cloudflare.com/cloudflare-one/connections/connect-networks/downloads/) to proxy it to a https URL (no sign-up/account needed), alter the `url` variable to match the one cloudflared gives you, and run the script with `deno run --allow-net main.js`.

The file is 900kb but that's only because I'm sending a big jpeg data URL - it seems to more reliably reproduce if the string being sent is longer.

In 1.33.0 (and all later versions) you'll see at least a few "WARNING" logs indicating that the `socket.send` function took >5 seconds. If you see the warning, it will eventually send - it takes about 20 seconds, whereas it should take less than a second. In the prior version, 1.32.5 it works fine.

**Comment by littledivy** [comment] 2023-09-21 12:43
We're tracking the secure websocket bug in https://github.com/denoland/deno/issues/20355. Closing this one.

**Closed by littledivy** 2023-09-21 12:43 UTC
Labels: bug
