### ISSUE TITLE
`deno run npm:[package]@latest` doesn't check and download the latest version

### ISSUE THREAD

**Issue by alanko0511** [denoland/deno#21821] opened 2024-01-06 03:28 UTC
Version: Deno 1.39.2

I tried following this tutorial (https://docs.deno.com/deploy/tutorials/vite) to create a Vite project with the `create-vite-extra` tool mentioned. I ran this many months ago, so my local machine has an outdated version of `create-vite-extra`.
This is the command I ran:
```
deno run --allow-read --allow-write --allow-env npm:create-vite-extra@latest
```
However, it still uses the version (1.1.0) cached on my local machine, and it doesn't download the latest version (2.0.2).
To fix this, I have to remove `@latest`, and it downloads the latest version.

I'm not sure if it's a feature or a bug, but since I run this command with `@latest`, I expect that it should check and download the latest npm package version.

Related issue and finding are also mentioned in the `create-vite-extra` repo:
https://github.com/bluwy/create-vite-extra/issues/43

**Comment by dsherret** [comment] 2024-01-06 05:32
Try with the `--reload` flag?

**Comment by dsherret** [comment] 2024-01-08 14:21
Do you have a `deno.lock` file? If so, it probably locked `@latest` to `1.1.0`

**Comment by alanko0511** [comment] 2024-01-08 14:33
Do you mean in a directory where I ran that `deno run` command? No there isn't a `deno.lock` file.

**Comment by dsherret** [comment] 2024-01-08 14:41
Did you provide the reload flag before the script? For me providing `--reload` does indeed reload to the latest version.

```
> deno info npm:create-vite-extra@latest 
dependencies: 5 unique
size: 657.67KB

npm:/create-vite-extra@1.1.0 (355.91KB)
├── npm:/kolorist@1.8.0 (49.83KB)      
├── npm:/minimist@1.2.8 (53.2KB)       
└─┬ npm:/prompts@2.4.2 (182.44KB)      
  ├── npm:/kleur@3.0.3 (9.66KB)        
  └── npm:/sisteransi@1.0.5 (6.63KB)   
V:\scratch
> deno run --allow-read --allow-write --reload npm:create-vite-extra@latest
× Project name: ... vite-project
✖ Operation cancelled
V:\scratch
> deno info npm:create-vite-extra@latest
dependencies: 5 unique
size: 656KB

npm:/create-vite-extra@2.0.2 (354.24KB)
├── npm:/kolorist@1.8.0 (49.83KB)
├── npm:/minimist@1.2.8 (53.2KB)
└─┬ npm:/prompts@2.4.2 (182.44KB)
  ├── npm:/kleur@3.0.3 (9.66KB)
  └── npm:/sisteransi@1.0.5 (6.63KB)
```

You can try restoring the cache's registry information for this package by calling `deno info`, noting the "npm modules cache" directory, then within that going to `registry.npmjs.org\create-vite-extra\registry.json` and changing the `dist-tags`'s `latest` property to "1.1.0". In my case, I also had old registry information on this package and it still reloaded the latest information once providing the `--reload` flag.

**Comment by alanko0511** [comment] 2024-01-08 15:30
> Did you provide the reload flag before `npm:create-vite-extra@latest`?

Hmm I probably add the flag after that. Sorry I don't quite remember about it.

**Comment by dsherret** [comment] 2024-01-08 17:55
Going to close this one since I can't reproduce it, but that would be my guess on what happened.

**Closed by dsherret** 2024-01-08 17:55 UTC
Labels: needs info
