### ISSUE TITLE
Suggestion: custom loader option

### ISSUE THREAD

**Issue by aoiste** [denoland/deno#14842] opened 2022-06-11 04:17 UTC
Maybe Deno can make web apps more cloud native via a `loader` option

deno.json
```json
{
  "loaders": {
    "*.vue": "https://deno.land/x/aleph@1.0.0-alpha.66/loaders/vue.ts",
    "*.vue!react": "https://deno.land/x/vue-loader/vue-react.ts",
    "*.(css|scss)": "./style-loader.ts"
  }
}
```

style-loader.ts
```ts
import { ModuleLoader, someHelperFunciton } from "https://deno.land/std@0.143.0/loader/mod.ts"

export default class StyleLoader implements ModuleLoader {
  // ...
}

declare module "*.css" {
  // ...
}
```

SomeComponent.tsx
```tsx
import style from "https://esm.sh/some-lib/SomeComponent.css"

// or even import a vue component to react component via a specific loader
import Button from "https://esm.sh/some-ui-lib/Button.vue!react"
```

* What loaders do is transform a non js/ts module to a ts modlue
* Deno can provide a `cache` API for loaders

**Comment by masx200** [comment] 2022-07-16 15:18
https://nodejs.org/dist/latest-v18.x/docs/api/esm.html#loaders

**Comment by kitsonk** [comment] 2022-07-16 22:17
Duplicate of #1739

**Closed by kitsonk** 2022-07-16 22:17 UTC
Labels: duplicate

**Comment by acrodrig** [comment] 2025-03-01 02:24
Can I suggest you review this decision? I get a tinge of envy every time I see how it is possible to load other resources in other runtimes. I understand your desire to keep things clean but this is one of those things that is to possible (at so I think) to do in user land. Cheers and thanks for a great project.
