### ISSUE TITLE
sorted:true;

### ISSUE THREAD

**Issue by Dpraz** [denoland/deno#6788] opened 2020-07-18 06:56 UTC
error: TS2345 [ERROR]: Argument of type '{ depth: number; sorted: boolean; trailingComma: boolean; compact: boolean; iterableLimit: number; }' is not assignable to parameter of type 'InspectOptions'.
  Object literal may only specify known properties, and 'sorted' does not exist in type 'InspectOptions'.
        sorted: true,
        ~~~~~~~~~~~~
    at https://deno.land/std@0.61.0/testing/asserts.ts:26:9

**Comment by lucacasonato** [comment] 2020-07-18 08:36
std@0.61.0 is only compatible with Deno 1.2.0. You seem to be using an old version of Deno.

**Comment by nayeemrmn** [comment] 2020-07-18 12:57
Duplicate of #6780.

**Closed** 2020-07-18 18:57 UTC
