### ISSUE TITLE
Expose Request and Response on global object

### ISSUE THREAD

**Issue by jed** [denoland/deno#2187] opened 2019-04-23 17:17 UTC
The global object currently surfaces the following:

```
> this
{ Deno, denoMain, window, atob, btoa, fetch, clearTimeout, clearInterval,
setTimeout, setInterval, location, Blob, File, CustomEventInit, CustomEvent,
EventInit, Event, EventTarget, URL, URLSearchParams, Headers, FormData,
TextEncoder, TextDecoder, performance, onmessage, workerMain,
workerClose, postMessage, Worker }
```

Since `fetch` uses the `Request` and `Response` interfaces, and those interfaces are often used along with fetch, those too should be surfaced (they are in Chrome, for example). The absence of these interfaces causes [aws4fetch](https://github.com/mhart/aws4fetch) to fail with an `Uncaught ReferenceError: Request is not defined` error.

**Comment by ry** [comment] 2019-04-23 17:34
👋 

Yes we should expose it. This is a duplicate of #2184. Closing this one.

**Closed by ry** 2019-04-23 17:34 UTC

**Comment by jed** [comment] 2019-04-23 17:42
Ah, thanks! And for changing the issue name to make it easier to find...

**Comment by jed** [comment] 2019-04-23 17:43
(Interacting with @ry on GitHub about an exciting new project feels very 2009 and I like it.)
