### ISSUE TITLE
Error when try to connect MongoDB using Deno: error: Uncaught (in promise) MongoRuntimeError: Server returned an invalid signature

### ISSUE THREAD

**Issue by SviatoslavMJS** [denoland/deno#24855] opened 2024-08-02 17:26 UTC
error: Uncaught (in promise) MongoRuntimeError: Server returned an invalid signature
    at continueScramConversation 
    
    My code:
    import { Db, MongoClient } from "npm:mongodb@6";
    import "jsr:@std/dotenv/load";

    const mongoConnectionUrl = Deno.env.get("DENO_MONGO_CONNECTION_URL") ?? "";

    let database: Db;
    console.log(mongoConnectionUrl);

    export const connectDB = async () => {
      const client = new MongoClient(mongoConnectionUrl);

      await client.connect();
      database = client.db("deno-todos-app");
      console.log("CONNECTED_SUCCESSFULLY");

      return database;
    };

![image](https://github.com/user-attachments/assets/a35adda0-e124-4a91-840c-4f2afabd559d)

**Comment by DMeechan** [comment] 2024-08-02 20:51
@SviatoslavMJS Try downgrading to Deno 1.45.4 with `deno upgrade --version 1.45.4`

Someone in the Deno Discord ran into this same Mongo signature issue last night. This error appears to be a regression in Deno 1.45.5

There was a similar report of a signature error when using `cookie-signature@1.2.1` in Deno 1.45.5

**Comment by nathanwhit** [comment] 2024-08-02 21:11
Duplicate of https://github.com/denoland/deno/issues/24841

**Closed by nathanwhit** 2024-08-02 21:11 UTC

**Comment by SviatoslavMJS** [comment] 2024-08-03 08:01
@DMeechan Works. Thanks.
