### ISSUE TITLE
Error: ReferenceError: self is not defined when importing from npm module in Deno 1.45.3

### ISSUE THREAD

**Issue by nestarz** [denoland/deno#24726] opened 2024-07-25 20:41 UTC
I encountered an issue when upgrading from Deno 1.45.2 to 1.45.3. The following code throws an error in version 1.45.3, while it worked perfectly in 1.45.2.

#### Code

```javascript
import "@sqlite.org/sqlite-wasm";
```

#### Error

```shell
error: Uncaught (in promise) ReferenceError: self is not defined
    at file:///node_modules/.deno/@sqlite.org+sqlite-wasm@3.46.0-build2/node_modules/@sqlite.org/sqlite-wasm/index.mjs:4:32
```

#### Steps to Reproduce

1. Create a new Deno project.
2. Add the following import statement in your code:
    ```javascript
    import "@sqlite.org/sqlite-wasm";
    ```
3. Run the project with Deno 1.45.3.

#### Expected Behavior

The import should work without any errors, as it did in Deno 1.45.2.

#### Actual Behavior

The import throws a `ReferenceError: self is not defined`.

#### Environment

- Deno version: 1.45.3
- `@sqlite.org/sqlite-wasm` version: 3.46.0-build2

#### Additional Information

Rolling back to Deno 1.45.2 resolves the issue, so it seems to be specific to the 1.45.3 release.

Please let me know if you need any additional information or if there are any workarounds for this issue. Thank you!

**Comment by bartlomieju** [comment] 2024-07-25 20:49
CC @kt3k, maybe we should revert that change to remove `self`?

**Comment by bartlomieju** [comment] 2024-07-25 21:03
It appears that this package doesn't really target Node as per comments here: https://github.com/sqlite/sqlite-wasm/issues?q=is%3Aissue+self+is%3Aclosed.

That said, it's unfortunate that it will stop working and there's no workaround to it. 

@dsherret @kt3k thoughts on this?

**Comment by nestarz** [comment] 2024-07-25 21:35
I published a forked version of the faulty package without the "self" reference :

https://www.npmjs.com/package/sqlite-wasm-node

It's a quick fix waiting for the owners to approve the merge of https://github.com/sqlite/sqlite-wasm/pull/48.

**Comment by kt3k** [comment] 2024-07-26 02:06
I don't think we should revert #24637 as the snippet fails in Node.js with the exact same reason. I think this should be addressed in `@sqlite.org/sqlite-wasm`. (Also we can recommend the above fork for now.)

#24683 is not exactly the same issue. #24683 is about the descriptor of `self` in Deno mode. This issue is about unavailability of `self` in Node mode.

**Comment by lucacasonato** [comment] 2024-08-02 09:27
I'm goign to close this as this is not a bug in Deno, but in this package. Deno just happens to follow Node behaviour more closely, so the package that was previously working now fails (like on Node)

**Closed by lucacasonato** 2024-08-02 09:27 UTC
Labels: bug, node compat
