### ISSUE TITLE
Deno seems to fails when importing big WASM file from network

### ISSUE THREAD

**Issue by dyedgreen** [denoland/deno#3521] opened 2019-12-18 19:13 UTC
In Deno WebAssembly modules can be imported directly. However, there seems to be a bug where if a big file is being downloaded via the network, this fails.

## How to reproduce
```JavaScript
// This fails
import * as sqlite from "https://deno.land/x/sqlite/build/sqlite.wasm";
```

Download the big WASM file: `git clone https://github.com/dyedgreen/deno-sqlite && cd deno-sqlite`.

```JavaScript
// This works
import * as sqlite from "./build/sqlite.wasm";
```

## Error
```
$ deno file.js
Compile https://deno.land/x/sqlite/mod.ts
error: Uncaught CompileError: WebAssembly.compile(): expected 7299055 bytes, fell off end @+13
► $deno$/compiler.ts:710:40
    at window_ts_10.window.onmessage ($deno$/compiler.ts:710:40)
    at workerMain ($deno$/workers.ts:93:51)
```

**Comment by dyedgreen** [comment] 2019-12-18 19:26
I had a quick look at the files mentioned in the traceback. Maybe there is an issue with the base64 encoding? (Although I don't know enough about Deno to be sure if that might be the case, or if there is another issue. If the base64 encoding is fine, ignore this comment 😅)

**Comment by ry** [comment] 2019-12-18 20:25
This is a duplicate of #3498 - let's move the discussion there.

**Closed by ry** 2019-12-18 20:25 UTC

**Comment by dyedgreen** [comment] 2019-12-18 20:49
> This is a duplicate of #3498 - let's move the discussion there.

@ry I'm not sure if that is correct. From what I understood based on https://github.com/denoland/deno/pull/3503, the issue there is that the exit routine deadlocks when trying to deallocate the WASM stuff.

Here on the other end, the runtime dies correctly. However, it is unable to instantiate the WASM binary when it was loaded via the network (while there is no issue when it was loaded from a file locally.)

I might be misunderstanding though 😅, but I just wanted to make sure the issue is understood correctly (as embedding the WASM in the JS files, which is a workaround for this, significantly increases the binary size.)
