### ISSUE TITLE
Update checker says new canary is available after upgrading to most recent canary

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#16539] opened 2022-11-04 20:38 UTC
Basically I ran `deno upgrade --canary` and then `deno run --unstable someFile.ts` shortly after. Deno then notifies about a new canary being available, even though I am on the latest version already.

```
deno upgrade --canary

Looking up latest canary version
Found latest version 1410e4adea5d399f9551ff04c6863862f169ee7a
Checking https://dl.deno.land/canary/1410e4adea5d399f9551ff04c6863862f169ee7a/deno-x86_64-unknown-linux-gnu.zip
36.1 MiB / 36.1 MiB (100.0%)
Deno is upgrading to version 1410e4adea5d399f9551ff04c6863862f169ee7a
Archive:  /tmp/.tmpJJ01pQ/deno.zip
  inflating: deno                    
Upgraded successfully

deno run --unstable someFile.ts

A new canary release of Deno is available. Run `deno upgrade --canary` to install it.

deno --version
deno 1.27.1+1410e4a (canary, x86_64-unknown-linux-gnu)
v8 10.8.168.4
typescript 4.8.3

deno upgrade --canary
Looking up latest canary version
Local deno version 1.27.1+1410e4a is the most recent release
```

**Comment by dsherret** [comment] 2022-11-05 14:16
Duplicate of #16537

**Closed by dsherret** 2022-11-05 14:16 UTC
Labels: duplicate
