### ISSUE TITLE
Coloring with escape sequences doesn't work on Windows

### ISSUE THREAD

**Issue by fzs111** [denoland/deno#5498] opened 2020-05-16 12:15 UTC
On Windows, escape sequences don't color Deno's output and display as ordinary text.

For example, an error stack trace looks like:
```none
Uncaught SyntaxError: Unexpected string
    at ←[1m←[3m←[90mevaluate←[39m←[23m←[22m←[90m(←[39m←[90m$deno$/repl.ts←[39m←[90m:←[39m←[90m45←[39m←[90m:←[39m←[90m34←[39m←[90m)←[39m
    at ←[1m←[3m←[90mObject.replLoop←[39m←[23m←[22m←[90m(←[39m←[90m$deno$/repl.ts←[39m←[90m:←[39m←[90m136←[39m←[90m:←[39m←[90m13←[39m←[90m)←[39m
```
I hope that this can be fixed.

**Comment by cj81499** [comment] 2020-05-16 16:48
Have you tried using [the standard library](https://deno.land/std/fmt/colors.ts)?

**Comment by fzs111** [comment] 2020-05-18 08:13
@cj81499  My issue isn't about how to *create* escape sequences, what I could use the library for, but about how to render them correctly on the screen, and doing the same with the error logs generated by Deno.

**Comment by cj81499** [comment] 2020-05-18 15:46
Is it possible that your terminal application doesn't support color codes? What application are you using?

**Comment by fzs111** [comment] 2020-05-20 21:26
I'm using cmd.exe on Win 10 (in legacy console mode), that doesn't support escape sequences by default, but Node.js managed somehow to make them work.

**Comment by bartlomieju** [comment] 2020-05-21 11:37
@piscisaureus PTAL as it's Windows issue

**Comment by cj81499** [comment] 2020-05-21 20:33
@fzs111 seems like you could just use a different terminal, such as Powershell or Windows Terminal.

**Comment by fzs111** [comment] 2020-05-21 20:44
@cj81499 I could use a different terminal, of course, but Deno also could be fixed, if it's possible to fix. That's why I reported this issue here.

Also, it isn't just about me, but everybody who wants to use Deno with `cmd.exe` for some reason. If I just moved on to a different terminal, then the next one of them would have opened this issue...

**Comment by cj81499** [comment] 2020-05-21 20:47
I'd give them all the same advice, which is to avoid using inferior software when something better is readily available (which is exactly why people are interested in Deno over Node), but I understand your point.

**Comment by neroux** [comment] 2020-06-04 22:25
I'd like to second @fzs111's concern.

The issue is not limited to Windows 10's legacy mode but also appears on earlier Windows versions with, both, the standard command prompt and PowerShell.

**Comment by always90s** [comment] 2020-06-09 02:58
I'm getting the following results after installing Deno on my Windows 8 machine.  I ran the following command from windows powershell and from vscode terminal.  Seems like the escape characters are always showing up.

```
> 4+5
←[33m9←[39m
> 11 + 4
←[33m15←[39m
> 19 + 5
←[33m24←[39m
```

**Comment by neroux** [comment] 2020-06-09 08:13
@always90s, they are. On Windows 8 the only way to get support for it is to install PowerShell 5.

**Comment by always90s** [comment] 2020-06-09 15:05
I ran the following command in my windows powershell window

```
PS C:\Users\hrana> $PSVersionTable.PSVersion

Major  Minor  Build  Revision
-----  -----  -----  --------
5      1      14409  1018

```

Do  I need to downgrade to powershell 5 instead of 5.1?

**Comment by neroux** [comment] 2020-06-09 15:49
Interesting, I would have expected it to work out of the box. On my Windows 10 installation it did. Maybe you need to enable it https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes

Still, it will be an issue on Windows 8.1

**Comment by howtologinquickwiththirtyninecharacters** [comment] 2020-07-01 00:59
> Interesting, I would have expected it to work out of the box. On my Windows 10 installation it did. Maybe you need to enable it https://stackoverflow.com/questions/51680709/colored-text-output-in-powershell-console-using-ansi-vt100-codes
> 
> Still, it will be an issue on Windows 8.1

I tried this (Windows 8.1 too), it works for PowerShell when ran as a stand alone program. When ran as embedded in VS Code all the escape sequences keep being displayed as text (just like in the original report). I tried configuring VS Code to launch an external terminal instead of an embedded one and also tried changing the render type of the terminal (auto, canvas, dom, experimentalWebgl) but nothing helped.

**Comment by Spoonbender** [comment] 2020-07-13 11:00
Probably the same issue as #6367

**Comment by neroux** [comment] 2020-07-13 11:17
@Spoonbender, exactly the same issue :)

**Comment by neroux** [comment] 2020-07-13 11:23
@caspervonb, as for ["abandoning legacy systems"](https://github.com/denoland/deno/issues/6367#issuecomment-655820647), yes it is accurate that Microsoft is moving towards a more Unices-like formatting here, however Windows 8 doesn't support colour sequences at all and even Windows 10 doesn't fully support them.

Considering that Windows 8 is still a support system, which also seems to be supported by Deno, it is fair to call this a bug.

**Comment by caspervonb** [comment] 2020-07-13 12:41
You'll run into this with any module that uses escape sequences which is why I think it's not worth trying to support it; console.log can have some support since it's in CLI but other all modules that use escape sequences wether it be in std/ or x/ are going to have this problem and users should just use a better terminal emulator IMHO.

Mostly hang around on Unix but when I do use Windows I use ConEmu because of the limitations of the default conhost as it's a common problem with portable cli programs.

**Comment by neroux** [comment] 2020-07-13 13:57
That might be true, but a bug in a module does not mean it should be equally buggy everywhere else. Colour sequences are not supported on all systems and Windows is one of them.

If there is no plan to address that, then the consequence should be to officialy drop support for pre-10 versions respectively for the traditional command prompt.

**Comment by MarkTiedemann** [comment] 2020-07-13 14:36
As far as I am aware, Node does not ship with a "color this string for terminal output" function. The goto package here is [`chalk`](https://www.npmjs.com/package/chalk). chalk does not call Windows Console API functions, but uses escape sequences, too.

chalk does have detailed checks for whether colors are supported, though:
```js
// Windows 10 build 10586 is the first Windows release that supports 256 colors.
// Windows 10 build 14931 is the first release that supports 16m/TrueColor.
```

https://github.com/chalk/supports-color/blob/master/index.js#L70-L71

I think the "are colors supported?" checks are a good idea and something that we can add to Deno.

Personally, I think it's not worth the trouble to implement the Windows Console APIs for color support on older systems, such as, old Windows 10 builds (we're at 19041 now, first build with color support is 10586), Windows 8.1, 8, 7, Windows Vista, XP, etc.

Recent Windows 10 builds seems like a reasonable target to me.

**Comment by neroux** [comment] 2020-07-13 14:41
Well, everything before 8.1 is not supported anymore anyhow, so it is not unreasonable to say Deno doesn't support it either. 8.1 however still is supported.

> Recent Windows 10 builds seems like a reasonable target to me.

Then mark Deno as incompatible with Windows 8, respectively clearly state only Windows 10 is a supported platform, and you are good to go.

As it is right now the output on Windows 8 is pretty useless.

**Comment by MarkTiedemann** [comment] 2020-07-13 15:15
> 8.1 however still is supported.

Windows 8.1 is from 2013. End of _mainstream support_ was 2018. End of _extended support_ is 2023. Again, I don't think it's worth it to invest too much time into supporting those older systems.

> Then mark Deno as incompatible with Windows 8, respectively clearly state only Windows 10 is a supported platform, and you are good to go.

Just because colors are incorrectly displayed in some terminals, doesn't mean it's "imcompatible".

**Comment by neroux** [comment] 2020-07-13 15:29
> End of extended support is 2023.

Exactly what I said, it is a supported system and if it is supported by Deno, bug reports should be adequately received and fixed.

> Just because colors are incorrectly displayed in some terminals, doesn't mean it's "imcompatible".

It pretty much is. Right now its output is useless. As I said before, it is pretty easy. Either fix the issue or mark everything before 10 as unsupported.

**Comment by MarkTiedemann** [comment] 2020-07-13 17:00
> it is a supported system

Windows extended support != Deno support.

> Right now its output is useless.

AFAIK,  `deno eval -p "'Hello, world!'"` works fine, even without colors. Even better, both `std/fmt/colors` and `cli/js/colors` respect `NO_COLOR` so `set NO_COLOR=1& deno eval -p "(await import('https://deno.land/std@v0.60.0/fmt/colors.ts')).red('Hello, world!')"` works just fine, too.

I agree that `Deno.noColor` could automatically determine that colors are not supported on older Windows builds to disable colored formatting on such systems. That's a simple, unintrusive fix. But implementing complicated Windows Console APIs for systems that are gonna be off extended support soon seems just plain unnecessary to me.

**Comment by neroux** [comment] 2020-07-13 17:03
> Windows extended support != Deno support.

So Windows 8.1 is not a supported platform by Deno?

> AFAIK, deno eval -p "'Hello, world!'"

No offence, but that remark is somewhat pointless ;)

> I agree that Deno.noColor could automatically determine that colors are not supported on older Windows builds to disable colored formatting on such systems. That's a simple, unintrusive fix. But implementing complicated Windows Console APIs for systems that are gonna be off extended support soon seems just plain unnecessary to me.

I never said Windows colours should be supported. Simply disable the colour sequences on platforms which do not support it and we are good.

**Comment by MarkTiedemann** [comment] 2020-07-13 17:17
> > Windows extended support != Deno support.
>
> So Windows 8.1 is not a supported platform by Deno?

I don't know whether it's supported or not. I haven't seen any official statements about Windows support in the docs.

I'm merely pointing out that Windows has a different support lifecycle than Deno. Just because some old Windows version is still supported by Microsoft, doesn't mean Deno has to support it, too.

Also, as I have pointed out, "support" is a spectrum of various degrees. Deno can support Windows 8.1, but not support properly colored output in `cmd.exe`. Those are not contrary positions.

> Simply disable the colour sequences on platforms which do not support it and we are good.

Deno is an open source project. Feel free to send a PR.

**Comment by neroux** [comment] 2020-07-13 17:22
> I'm merely pointing out that Windows has a different support lifecycle than Deno. Just because some old Windows version is still supported by Microsoft, doesn't mean Deno has to support it, too.

That is clear, hence my question if Windows 8 is a supported platform or not.

> Also, as I have pointed out, "support" is a spectrum of various degrees. Deno can support Windows 8.1, but not support properly colored output in cmd.exe. Those are not contrary positions.

It is I am afraid. As I addressed earlier, if it is a support platform reported bugs should be acknowledged and fixed. If it is not supported, obviously not but that should be communicated.

> Deno is an open source project. Feel free to send a PR.

Again, no offence but these standard phrases are not very helpful.

**Comment by caspervonb** [comment] 2020-12-14 17:49
Time to make a call on this?

We can do this, but that means making ops for everything that's in the Windows Console API which is a whole lotta fork for little payoff and its just going to break once you try to use other vt escape sequences anyway.

There are ways to make old-school cmd.exe work with vt escape sequences however, and Windows 7 is EOL already so as I said in #6367 it's on the user to have a capable terminal emulator if pretty output is wanted.

**Comment by neroux** [comment] 2020-12-14 18:26
> Windows 7

Windows 8.1 isn't however.

> if pretty output is wanted

The problem is not "pretty output" though, output is gibberish right now as it contains control characters. The example provided here show how illegible the whole thing is.

**Comment by fzs111** [comment] 2020-12-14 21:16
@caspervonb And, this isn't just about pretty output (that one could turn
off withou consequences with a simple `NO_COLOR=1` env variable -- though
it disables colors in all other console applications too), but *all* escape
sequences, including e.g. cursor control, without which many interactive
and some non-interactive CLI apps **break**.

**Comment by fzs111** [comment] 2020-12-14 21:21
@caspervonb And, this isn't just about pretty output (that one could turn
off withou consequences with a simple `NO_COLOR=1` env variable -- though
it disables colors in all other console applications too), but *all* escape
sequences, including e.g. cursor control, without which many interactive
and some non-interactive CLI apps **break**.

**Comment by kuzivany** [comment] 2020-12-29 00:44
As mentioned by @neroux & @fzs111 this isn't about "pretty output", it's about *usable output*. In Windows 8.1 this is the type of output received whether using `cmd.exe` or PowerShell (versions 4, 5.1, 7.02, 7.03 or 7.1.0):

```
PS C:\Users\x> deno
Deno 1.6.2
exit using ctrl+d or close()
> {k:"L"}
{ k: ←[32m"L"←[39m }
> "Hello, world"
←[32m"Hello, world"←[39m
> [1,2,3]
[ ←[33m1←[39m, ←[33m2←[39m, ←[33m3←[39m ]
```
```
PS C:\Users\x> deno eval "console.log('Hi, W')"
Hi, W
PS C:\Users\x> deno eval "console.log({g: 'Hi, W'})"
{ g: ←[32m"Hi, W"←[39m }
```

**Comment by caspervonb** [comment] 2020-12-29 20:44
> It disables colors in all other console applications too), but all escape
sequences, including e.g. cursor control, without which many interactive
and some non-interactive CLI apps break.

I know, but if you don't have a capable terminal emulator that's pretty much expected. Not that many people bother with non vt100 capable terminal emulators.

Really just boils down to if we want to support curses/conio-esque syscalls in the Deno namespace.

**Comment by neroux** [comment] 2020-12-29 20:48
The whole subject is not really about colours or not colours.

Standard output on pre-Windows 10 is broken altogether and only produces gibberish.

**Comment by neroux** [comment] 2021-01-23 13:04
Has been almost a year at this point. If the fix takes just a tad longer it really becomes irrelevant because even 8.1 will be out of support ;).

**Comment by howtologinquickwiththirtyninecharacters** [comment] 2021-03-03 21:14
I found a workaround, get [ANSICON](https://github.com/adoxa/ansicon). Install following the instructions in the [readme.txt](https://github.com/adoxa/ansicon/blob/master/readme.txt). If you want this just for VS Code instead of a global installation you can use the following settings:

```
"terminal.integrated.shell.windows": "C:\\Windows\\System32\\cmd.exe",
"terminal.integrated.shellArgs.windows": ["/C", "C:\\Path\\To\\ANSICON\\x64\\ansicon.exe"],
```

**Comment by nilslindemann** [comment] 2021-03-21 03:00
Whenever a hipster software does stuff like unasked and unsuccessful printing colors to my cmd.exe, I temporarily use a console wrapper called [cmder](https://cmder.net/), which has other bugs, but hides these '←[33m' thingies.

Of course, it would be better if software would behave more conservative regarding default console windows in [second most used operating systems in the world](https://www.digitaltrends.com/computing/windows-7-end-of-support-still-popular/).

**Comment by howtologinquickwiththirtyninecharacters** [comment] 2021-04-01 01:11
I too use cmder but it doesn't work inside VS Code or I couldn't get it to work there (Win 8.1), thanks for mentioning NO_COLOR, I didn't know about that.

**Comment by aapoalas** [comment] 2023-02-11 19:18
@piscisaureus Can we close this, as I imagine `NO_COLOR` flag should handle the case for when ANSI sequences cannot be used?

**Closed** 2024-09-16 11:25 UTC
Labels: bug, cli, windows
