### ISSUE TITLE
Using tab completion during cli command results in error

### ISSUE THREAD

**Issue by dannypaz** [denoland/deno#5741] opened 2020-05-22 06:08 UTC
When trying to use the utility `deno run`, when I hit tab for tab completion of a file name, I receive the following error in the command:

`deno run ma(eval):1: command not found: _deno`

List of actions: `d e n o r u n m a <tab>`

Expected: deno cli should be able to handle tab completion of file names
Version: Deno 1.0.1
Install Method: asdf
OS: MacOS Catalina

**Comment by lucacasonato** [comment] 2020-05-22 10:06
What shell do you use?

**Comment by dannypaz** [comment] 2020-05-22 20:09
@lucacasonato ZSH. FWIW, in Catalina, Apple replaced bash with ZSH

**Comment by mattd3v** [comment] 2020-06-05 00:08
@dannypaz I’m on Catalina as well, but unable to replicate this. Is it still occurring, and how was Deno installed? If it is still an issue I will look into it!

**Comment by caspervonb** [comment] 2020-12-14 17:02
Unable to reproduce (zsh v5.3), botched shell/completion setup perhaps?

**Comment by kitsonk** [comment] 2020-12-15 20:14
Closing issue until it can be reproduced.

**Closed by kitsonk** 2020-12-15 20:14 UTC
Labels: bug, cli
