### ISSUE TITLE
Bug: deno process keeps running using WebSockts and/or promises

### ISSUE THREAD

**Issue by timonson** [denoland/deno#8390] opened 2020-11-15 12:12 UTC
The deno process keeps running (does not exit) using the WebSockets API on the client side. 

On the backend side I use the `ws` server example from the `std` module: https://github.com/denoland/deno/tree/master/std/ws readme.

On the client side (running with deno) I use the following code. The deno process doesn't finish although the `ws` connection is closed (the server confirms this):

```typescript
async function connect(url: string): Promise<WebSocket> {
  return new Promise((resolve, reject) => {
    const socket = new WebSocket(url);
    socket.onopen = () => resolve(socket);
    socket.onerror = (err) => reject(err);
  });
}

async function getMessage(socket: WebSocket) {
  return new Promise((resolve, reject) => {
    socket.onmessage = (event: any) => {
      resolve(event.data);
    };
    socket.onclose = () => resolve("connection is closed");
  });
}

const socket = await connect("ws://0.0.0.0:8080");
socket.send("Here's some text that the server is urgently awaiting!");
const message = await getMessage(socket);
console.log(message);
socket.close();
```

**Comment by crowlKats** [comment] 2020-11-15 12:16
Duplicate of #7457

**Comment by timonson** [comment] 2020-11-15 12:18
It seems to be @crowlKats , thank you! I actually searched for websockets but not ws in the issues.

**Closed** 2020-11-15 12:19 UTC
