### ISSUE TITLE
Request Feature: Support direct WebAssembly import and run

### ISSUE THREAD

**Issue by HKhademian** [denoland/deno#6279] opened 2020-06-13 06:58 UTC
It's good to directly run WebAssembly files in **deno** like `.js` and `.ts` files. If so then I can run:
```deno run myTask.wasm```
without any additional files and steps. (it exports a common function like `main` or `start` or ...)

Also it's good to directly import these files to project with simple and readable syntax:
```import { task1 } from ".../myLib.wasm"```

Like this code in [dev.to](https://dev.to/lampewebdev/writing-webassembly-in-rust-and-runing-it-in-deno-144j), it writes a simple library function called `square` and import it in `.ts` file and run that `.ts` file with deno.

Example above can be very simpler:
```
const wasmCode = await Deno.readFile("./target/wasm32-unknown-unknown/debug/wasm_deno_example.wasm");
const wasmModule = new WebAssembly.Module(wasmCode);
const wasmInstance = new WebAssembly.Instance(wasmModule);
const {
    square,
} = wasmInstance.exports;
```
can write somthing like:
```
import { square } from "./target/wasm32-unknown-unknown/debug/wasm_deno_example.wasm";
```
It's much more readable, clean, easy to use, and also do not dirty the global context.

This simple feature enables more comfortable journey to publish **libraries** and write cross-platform deno **apps**.

**Comment by bartlomieju** [comment] 2020-06-13 10:20
Duplicate of https://github.com/denoland/deno/issues/5609

**Comment by HKhademian** [comment] 2020-06-13 13:53
this nested issues has not direct vision to every one how want to help.
this feature request has two parts:
1- deno run WASM files from command line to create portable deno **apps**
2- deno support clean import WASM files to create easy to use **libraries**

and yes it's better to use --unstable flag for such features.

**Comment by Spoonbender** [comment] 2020-07-17 07:33
From what I've gathered, wasm currently lacks the concept of an entry point ("main" function or top level code), so it is unclear how deno should execute the wasm module. 
Perhaps we can provide a syntax for specifying the function name (also useful for ts/js), such as `deno run mymodule.wasm;main` or `deno run --entrypoint main mymodule.wasm`?

**Comment by bartlomieju** [comment] 2020-11-18 13:31
I'm gonna close this issue as a duplicate of #5609, let's continue there.

**Closed by bartlomieju** 2020-11-18 13:31 UTC

**Comment by 00ff0000red** [comment] 2021-02-10 03:22
@Spoonbender Sorry for the year late ping, but a WebAssembly module is allowed to choose a function that executes immediately upon compilation, reminiscence of Linux `_start`.
