### ISSUE TITLE
Add Intl.DateTimeFormat support for all languages and calendars

### ISSUE THREAD

**Issue by hashemisa** [denoland/deno#5788] opened 2020-05-23 12:23 UTC
Currently only the Gregorian calendar is available!

`new Intl.DateTimeFormat([locales[, options]])`

https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Intl/DateTimeFormat/DateTimeFormat

**Comment by alisabzevari** [comment] 2020-05-24 10:40
This should be solved by #1968.

**Comment by kishiguro** [comment] 2020-05-24 10:48
```
$ ~/rust/deno/target/debug master* deno
Deno 1.0.2
exit using ctrl+d or close()
> const date = new Date(Date.UTC(2012, 11, 20, 3, 0, 0));
undefined
> console.log(new Intl.DateTimeFormat('en-US').format(date));
12/20/2012
undefined
> console.log(new Intl.DateTimeFormat('en-GB').format(date));
20/12/2012
undefined
> console.log(new Intl.DateTimeFormat(['ban', 'id']).format(date));
20/12/2012
undefined
```

**Comment by hashemisa** [comment] 2020-05-29 18:23
Node.js supports this possibility

**Comment by ry** [comment] 2020-06-15 16:38
duplicate of https://github.com/denoland/deno/issues/1968

**Closed by ry** 2020-06-15 16:38 UTC
Labels: cli, suggestion
