### ISSUE TITLE
Deno.com has broken URLs with trailing slash

### ISSUE THREAD

**Issue by impressivewebs** [denoland/deno#12914] opened 2021-11-27 22:54 UTC
Example:

https://deno.com/blog/

Vs.

https://deno.com/blog

This seems to happen for any deep links that I tried. I noticed this because a newsletter had linked to the blog and the URL was broken.

**Comment by nayeemrmn** [comment] 2021-11-28 00:59
Duplicate of #https://github.com/denoland/dotland/issues/1939.

**Comment by lucacasonato** [comment] 2021-11-29 09:54
Closing as duplicate of denoland/dotland#1939.

**Closed by lucacasonato** 2021-11-29 09:54 UTC
