### ISSUE TITLE
node:process environment variable usage detection no longer working

### ISSUE THREAD

**Issue by njbraun** [denoland/deno#21056] opened 2023-11-02 19:00 UTC
Deno fails to detect usage of process.env from imported `node:process`

Run the following with no allow flags
```ts
import process from 'node:process';
console.log(process.env["USER"]);
```

```
# Deno 1.30.3
❯ deno run main.ts
❌ Denied env access to "USER".
error: Uncaught PermissionDenied: Requires env access to "USER", run again with the --allow-env flag
```

```
# Deno 1.31.0 (and 1.38.0)
❯ deno run main.ts
undefined
```

**Comment by dsherret** [comment] 2023-11-02 21:37
This is a duplicate of https://github.com/denoland/deno/issues/18665

See details in that issue.

**Closed by dsherret** 2023-11-02 21:37 UTC
Labels: duplicate
