### ISSUE TITLE
Improve error message when using `Deno.memoryUsage()` without the --unstable flag

### ISSUE THREAD

**Issue by uki00a** [denoland/deno#10584] opened 2021-05-11 12:54 UTC
When using `Deno.memoryUsage()` without the `--unstable` flag, Deno causes the following error:

```shell
error: TS2339 [ERROR]: Property 'memoryUsage' does not exist on type 'typeof Deno'.
console.log(Deno.memoryUsage());
                 ~~~~~~~~~~~
```

On the other hand, other unstable APIs (e.g. `Deno.resolveDns()`) cause the following error:

```shell
error: TS2339 [ERROR]: Property 'resolveDns' does not exist on type 'typeof Deno'. 'Deno.resolveDns' is an unstable API. Did you forget to run with the '--unstable' flag?
console.log(Deno.resolveDns());
```

It seems that `"memoryUsage"` is not listed in [UNSTABLE_DENO_PROPS](https://github.com/denoland/deno/blob/v1.9.2/cli/diagnostics.rs#L15) :slightly_smiling_face:

**Comment by lucacasonato** [comment] 2021-06-08 16:55
Duplicate of #10827

**Closed by lucacasonato** 2021-06-08 16:55 UTC
