### ISSUE TITLE
Re-enable flaky fetch tests

### ISSUE THREAD

**Issue by ry** [denoland/deno#1228] opened 2018-11-27 19:35 UTC
Note the issue was only appearing on Windows. So ideally someone on Windows would debug this. The first set is to uncomment the tests and see if you can repeat the failure.

https://github.com/denoland/deno/blob/570269b73de713afcff712977d11a3910ed849ad/js/fetch_test.ts#L50-L161

**Comment by kt3k** [comment] 2019-01-19 06:47
duplicate of #1219 ?

**Comment by nstott** [comment] 2019-11-02 19:30
These are flakey on mac as well now, not just windows

**Comment by ry** [comment] 2020-02-24 19:45
Feb 24, 2020: Still an issue.

**Comment by mitch292** [comment] 2020-05-23 20:15
Commented on the PR I submitted for this as well, but the test for fetchRequest in fetch_tests.ts is failing in the build on the latest macOs, but successful on my local. Both running 10.15.4, having a little trouble debugging. Any pointers would be appreciated. 

Here is the output from the build for the test. 
```
 fetchRequest
AssertionError: Values are not equal:


    [Diff] Actual / Expected

Unit tests failed

+   "POST /blah HTTP/1.1
+   hello: World
+   foo: Bar
+   accept: */*
+   user-agent: Deno/1.0.2
+   accept-encoding: gzip, br
+   host: 127.0.0.1:4501
+   
+   "
-   ""
```

**Comment by mitch292** [comment] 2020-05-23 21:39
Ah my bad, I see in the original comment and #1535 that this was the output that spurred original issue. Going to close my PR, but experienced today on macOS.

**Comment by mitch292** [comment] 2020-05-23 23:18
Apologies for all the above comments. PR's back open. I wasn't resolving the response body properly in my original PR.

**Closed** 2020-05-24 16:04 UTC
Labels: bug, good first issue
