### ISSUE TITLE
Debugger does not hit breakpoints in VSCode when running cached files (v 1.8.2)

### ISSUE THREAD

**Issue by elemental-mind** [denoland/deno#9886] opened 2021-03-25 00:27 UTC
When running the debugger on a file that is already compiled and cached by deno in a previous (debugging) run, then the debugger does not hit breakpoints with the `--inspect` flag set.

This is (I suppose) a bug introduced in version 1.8.2 concerning the inspector. This issue does **not** apply to version 1.8.1.

I have the following `launch.json` in VSCode:
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Deno Run",
            "type": "pwa-node",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "deno",
            "runtimeArgs": [
                "run",
                "--inspect",
                "--unstable",
                "--allow-read",
                "--allow-write",
                "-A",
                "${file}"
            ],
            "attachSimplePort": 9229,
            "outputCapture": "std"
        }
    ]
}
```

Sample file `sample.ts`:
```
let array = ["abc", "def", "ghi"];
let index = array.indexOf("ghi");
console.log("String found at position:"
console.log(index);
```
Here are the steps to reproduce:

1. Create the sample file place a breakpoint at line 2 for example. Save it.
2. Hit F5 to start debugging.
3. Following output :
```
Debugger listening on ws:// ...
Check file:/// ...
Debugger session started.
```
...and debugger stopping at line 2 (expected).
4. Cancel the debugging session.
5. Restart the debugging session.
6. Following output: 
```
Debugger listening on ws:// ...
String found at position:  [thus code is executed without breakpoints]
2
```
... and the VSCode debugger waits to attach and times out with an error:
> Error processing launch: Error: Could not connect to debug target at http:// ... : Promise was cancelled.

I don't really know how the inspector protocol works and whether deno is simply too fast for the debugger to attach if the file is already precompiled - but I would expect it to wait for the debugger to attach, when I pass the "--inspect" flag (just like it does in version 1.8.1). I don't like to use "--inspect-brk" as that stops at the first executed line and requires one more F5 (yes, I am that lazy ;-)) and potentially opens up another code tab with code from your imports (plain annoying).

**Comment by TradeItEasy** [comment] 2021-03-25 00:45
As it is related I won't open another issue: Because the debugger does not attach before the checks are done, when running a file where ts-checks fail two times in a row, this leads to the debugger of VSCode to wait indefinitely and to become "uncenacellable" and not even timing out --> You will need to restart VSCode.

Steps to reproduce with the above file and config:
1. Change line 1 to `let arrayChanged = ["abc", "def", "ghi"];`
2. Run a debugging session. You will see a check error complaining that "array" is unknown in line 2. The debugger does automatically cancel the session.
3. Change line 1 to `let arrayChangedAgain = ["abc", "def", "ghi"];`
4. Run a debugging session. You will see a check error complaining that "array" is unknown in line 2. 
Now the debugger does not cancel the session and waits to attach indefinitely. 
5. Try to cancel the debugging session -> It won't work. You will need to restart VSCode.

**Comment by bartlomieju** [comment] 2022-01-17 05:19
@elemental-mind sorry for replying so late. I did triage this issue and here are my findings:
1. what you described in the first comment is related to https://github.com/denoland/deno/issues/12417#issuecomment-1000773654 - ie. the code is so short that it finishes execution before VSCode has a chance to discover and connect to the inspector. The same would be true if you used Chrome DevTools. The solution to this problem is to either use `--inspect-brk` flag to pause execution on the first statement, or to add some kind of timeout to your code to allows the debugger to connect.
2. I tried reproducing issue with type checking errors, but with no luck - the debugger cancels after a few seconds and I can run it as many times as I want.

I'm going to tentatively close this issue as everything is working as expected. Please let me know if you still hit these problems on latest Deno.

**Closed by bartlomieju** 2022-01-17 05:19 UTC
Labels: bug, inspector, needs investigation
