### ISSUE TITLE
LSP: warning on underscore-prefixed unused variable

### ISSUE THREAD

**Issue by paulrouget** [denoland/deno#19462] opened 2023-06-11 08:21 UTC
`deno lint` doesn't warn.
`denols` does.

Using denols from neovim:

```
const _x = 1; // '_x' is declared but its value is never read.
```

**Comment by dsherret** [comment] 2023-06-12 02:21
This is a TypeScript diagnostic. It gets raised with a severity of "hint" (https://microsoft.github.io/language-server-protocol/specifications/lsp/3.17/specification/#diagnosticSeverity -- it is raised as a suggestion on line 1797 in this file https://github.com/microsoft/TypeScript/blob/3cfd6d2b872fb4bbb7573c3375166e0f9f613f71/src/compiler/checker.ts then we convert it to a hint on this line https://github.com/denoland/deno/blob/7f15126f23d97f20a4fb33e43136cd4d13825863/cli/lsp/diagnostics.rs#L463)

In vscode with Deno it displays like so with a quick fix:

![image](https://github.com/denoland/deno/assets/1609021/b380cde9-8fcb-4f24-be34-41d72b99937e)

With TypeScript and Node.js, it displays the same way:

![image](https://github.com/denoland/deno/assets/1609021/898d60a1-9a99-4401-83cf-e740f2827187)

So I think this is not a Deno issue as it's just surfacing the TypeScript hint diagnostic. I think maybe neovim is displaying diagnostics with "hints" as warnings?

**Comment by paulrouget** [comment] 2023-06-12 02:59
Oh right, Neovim shows it as hint, not a warning.

I would argue that this hint should not be raised if the variable starts with a `_` though.

**Comment by dsherret** [comment] 2023-06-12 03:45
Maybe open an issue in the TypeScript repo if there already isn’t one showing how this diagnostic is raised in node with the latest ts version? We just surface what TypeScript diagnostics are raised.

**Comment by paulrouget** [comment] 2023-06-12 07:51
I will do it if it is indeed a typescript issue.

Just to double check:

Typescript is consistent between linter and lsp: Typescript linter and lsp warn of unused variable for _-prefixed variable. A special rule needs to be added to eslint conf file to do so, and then the linter and the lsp server both ignore _-prefixed variables.

Deno is not consistent between linter and lsp: Deno linter doesn't not warn of unused variable for _-prefixed variable by default. I would expect denols to follow deno lint default behavior.

I don't know much about the architecture of Deno. Maybe I am getting something wrong. Please let me know.

**Comment by dsherret** [comment] 2023-06-12 17:27
> Typescript is consistent between linter and lsp: Typescript linter and lsp warn of unused variable for _-prefixed variable. A special rule needs to be added to eslint conf file to do so, and then the linter and the lsp server both ignore _-prefixed variables.

Does it? I added eslint to a project and I still see TypeScript surfacing this hint diagnostic.

![image](https://github.com/denoland/deno/assets/1609021/849b42e9-b47d-47c3-ad26-df0ba7b95044)

> Deno is not consistent between linter and lsp: Deno linter doesn't not warn of unused variable for _-prefixed variable by default. I would expect denols to follow deno lint default behavior.

This is a TypeScript hint diagnostic. Deno surfaces diagnostics that TypeScript raises.

**Comment by dsherret** [comment] 2023-06-12 17:34
Overall, it might actually be "by design" in TypeScript. Not sure they'd change it. Anyway, I'm going to close this issue, but I believe the way forward here would be to get TypeScript to disable this hint diagnostic. Deno is just surfacing what TypeScript raises.

**Closed by dsherret** 2023-06-12 17:34 UTC
Labels: invalid
