### ISSUE TITLE
Unexpected parse error inside deno REPL

### ISSUE THREAD

**Issue by Shifta-Robel** [denoland/deno#17442] opened 2023-01-16 11:32 UTC
This piece of code
```jsx
> function mergeSort(arr){
     if( arr.length <= 1) return arr
     let left = mergeSort( arr.slice( 0 , arr.length/2 ) )
```
keeps giving `parse error: Expected '}', got '<eof>' at 3:50`, can't seem to go past it without using `Ctrl+S`.
And it works fine in node

**Comment by aapoalas** [comment] 2023-01-16 11:45
Minor clarification: The issue is that Deno's REPL doesn't automatically insert a line break with this input but instead tries to interpret the whole code as a complete command, which it is not as it is missing the closing brace for the `mergeSort` function.

Node's REPL correctly infers that an Enter press should insert a line break, not evaluate the code.

**Closed** 2023-01-16 14:45 UTC
