### ISSUE TITLE
Implement Intl.Collator()

### ISSUE THREAD

**Issue by kryptish** [denoland/deno#7600] opened 2020-09-20 19:09 UTC
Just tried to sort an array with .localCompare(), which failed with an error, then tried `new Intl.Collator()`, which also failed. E.g. I assume those browser features are missing in Deno or am I doing something wrong?

**Comment by lucacasonato** [comment] 2020-09-20 19:31
This is because we are missing ICU. Closing as duplicate of https://github.com/denoland/deno/issues/1968

**Closed by lucacasonato** 2020-09-20 19:31 UTC
