### ISSUE TITLE
Exceptions thrown after a worker's initial execution panic

### ISSUE THREAD

**Issue by andreubotella** [denoland/deno#11342] opened 2021-07-09 06:25 UTC
```
error: Uncaught (in worker "") Error
    throw new Error();
          ^
    at file:///home/abotella/test/worker.js:3:11
    at fire (deno:extensions/timers/01_timers.js:477:7)
    at handleTimerMacrotask (deno:extensions/timers/01_timers.js:338:7)
thread 'worker-0' panicked at 'coding error: either js is polling or the worker is terminated', runtime/web_worker.rs:498:9
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: Uncaught (in promise) Error: Unhandled error event reached main worker.
    at Worker.#pollControl (deno:runtime/js/11_workers.js:247:23)
```

### test.js
```js
new Worker(
  new URL("./worker.js", import.meta.url).href,
  { type: "module" },
);
```

### worker.js
```js
setTimeout(() => {
  throw new Error();
}, 1000);
```

-----

This seems to have been introduced in #11076, and it seems to be related to some of the WPT test failures in #11338.

**Comment by andreubotella** [comment] 2021-09-04 17:19
Throwing that error on the worker is not a terminal error, and so it won't close or terminate the worker. However, when the error is propagated to the main thread, the main thread will terminate. This panic seems to be caused because, when `MainWorker` is dropped after an error in cli's `run_command`, the worker's `WebWorkerHandle` is also dropped, which closes the sender before the worker terminates, which is something the worker's event loop doesn't expect to happen. Whether the panic occurs or not is of course spurious, since the process is about to close anyway, but it seems like in most cases it does occur.

We should check if a worker that was created from another worker, which then terminates, also panics in the exact same way.

**Comment by andreubotella** [comment] 2021-09-13 15:47
The same panic happens when closing a worker which has still-running child workers. The `WebWorkerHandle` corresponding to the child worker is dropped because the parent worker is terminating, while the child worker is still alive.

Both Chromium and Firefox (WebKit doesn't support nested workers) will terminate a nested worker when its parent worker is closed or terminated. It's hard to say whether the spec allows this, though – [the fact that errors are propagated up the chain of workers, even if some of those are terminated](https://html.spec.whatwg.org/multipage/workers.html#runtime-script-errors-2) seems to imply that a terminated worker might have alive descendants.

**Comment by andreubotella** [comment] 2021-09-14 12:31
As reported by @kuuote in #12068, this panic also happens when throwing an error in the initial execution of a nested worker.

**Comment by BartTactick** [comment] 2022-02-04 11:49
Hi there,

I have this error comming up after upgrading from 1.14 to 1.18.
I dont have a reproduction case but this is basicly what happends.

At my project we have functions (just a string of code) thats being passed down to one of the workers.
There are always 20 workers in total.
Then when a worker recieves the code, it executes it with eval (its auth protected, i know it can be unsafe).
After the worker has returned a function result the worker will be terminated.
Then a new worker is created to make sure the amound of workers is still 20.

It goes wrong when nothing happends for a hour upto 2 hours
If one of the workers has to do something after that, the following error is thrown: (does not always happen but like 80% of the time).
![image](https://user-images.githubusercontent.com/77833517/152523932-a65aa5fa-4865-4062-82e9-28c5446efe8f.png)
Also since the error is about multiple workers, i guess only this part and not any other part of the application.

**Comment by mmastrac** [comment] 2024-02-23 22:10
Re-closing this issue as the event loop has been changed pretty heavily, and a long-standing bug with promise IDs rolling over has been fixed.

**Closed by mmastrac** 2024-02-23 22:10 UTC
Labels: bug, runtime
