### ISSUE TITLE
Runtime panics when trying to readFileSync a folder

### ISSUE THREAD

**Issue by Pwuts** [denoland/deno#10027] opened 2021-04-05 21:53 UTC
`Deno.readFileSync('./dist/')` causes a runtime panic:
```
thread 'main' panicked at 'already mutably borrowed: BorrowError', /home/runner/work/deno/deno/core/ops_bin.rs:158:18
```
I believe it should instead throw a regular error, like it does when a file doesn't exist.

**Comment by lucacasonato** [comment] 2021-04-05 22:08
I can't reproduce this:
```
> Deno.readFileSync('./Downloads')
Uncaught Error: Is a directory (os error 21)
    at processErr (deno:core/core.js:66:12)
    at processResponse (deno:core/core.js:50:11)
    at jsonOpSync (deno:core/core.js:86:12)
    at Object.binOpSync (deno:core/core.js:100:12)
    at readSync (deno:runtime/js/12_io.js:84:24)
    at File.readSync (deno:runtime/js/30_files.js:95:14)
    at Buffer.readFromSync (deno:runtime/js/13_buffer.js:195:25)
    at readAllSync (deno:runtime/js/13_buffer.js:217:9)
    at Object.readFileSync (deno:runtime/js/40_read_file.js:10:22)
    at <anonymous>:2:6
> Deno.readFileSync('./download')
Uncaught NotFound: No such file or directory (os error 2)
    at processErr (deno:core/core.js:66:12)
    at processResponse (deno:core/core.js:50:11)
    at Object.jsonOpSync (deno:core/core.js:86:12)
    at openSync (deno:runtime/js/30_files.js:31:22)
    at Object.readFileSync (deno:runtime/js/40_read_file.js:9:18)
    at <anonymous>:2:6
```

What OS and Deno version are you on?

**Comment by Pwuts** [comment] 2021-04-05 22:17
Kali Linux, Deno 1.8.3. Not sure if the slash makes a difference, but I was trying to read `./frontend/dist/` including the trailing slash.

**Comment by crowlKats** [comment] 2021-04-05 22:25
Can reproduce
```
> Deno.readFileSync("./Downloads")
thread 'main' panicked at 'already mutably borrowed: BorrowError', /Users/runner/work/deno/deno/core/ops_bin.rs:158:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    40518 abort      deno
```

**Comment by AaronO** [comment] 2021-04-05 22:43
This seems to be a bug in the `ops_bin` implementation that was shipped in `v1.8.3`, see [ops_bin.rs:158@v1.8.3](https://github.com/denoland/deno/blob/2e6b78be9095cc38c392e2477711ff6eec226704/core/ops_bin.rs#L158)

Basically the OpState is double borrowed if/when the bin op fails.

This should be fixed in canary and the upcoming 1.9

**Comment by AaronO** [comment] 2021-04-05 22:46
You can see that `v1.8.3` panics but canary throws as expected:

## 1.8.3

```
❯ deno eval 'Deno.readFileSync("/Users/aaron/Downloads")'
thread 'main' panicked at 'already mutably borrowed: BorrowError', /Users/lucacasonato/projects/github.com/denoland/deno/core/ops_bin.rs:158:18
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
[1]    45759 abort      deno eval 'Deno.readFileSync("/Users/aaron/Downloads")'
```

## Local build of `main` (aka canary)

```
❯ ./target/debug/deno eval 'Deno.readFileSync("/Users/aaron/Downloads")'
error: Uncaught Error: Is a directory (os error 21)
Deno.readFileSync("/Users/aaron/Downloads")
     ^
    at processErr (deno:core/core.js:66:12)
    at processResponse (deno:core/core.js:50:11)
    at jsonOpSync (deno:core/core.js:86:12)
    at Object.binOpSync (deno:core/core.js:100:12)
    at readSync (deno:runtime/js/12_io.js:84:24)
    at File.readSync (deno:runtime/js/30_files.js:95:14)
    at Buffer.readFromSync (deno:runtime/js/13_buffer.js:195:25)
    at readAllSync (deno:runtime/js/13_buffer.js:217:9)
    at Object.readFileSync (deno:runtime/js/40_read_file.js:10:22)
    at file:///Users/aaron/git/deno/$deno$eval.ts:1:6
```

**Comment by kitsonk** [comment] 2021-04-05 22:54
Since we re-worked all of this, and the behaviour is not broken in main, the issue is resolved, but it does feel like we could use a regression test that covers this case, some that ensures that a `Deno.readFileSync("bad_file");` produces a catchable error.

**Comment by caspervonb** [comment] 2021-04-05 23:25
> Since we re-worked all of this, and the behaviour is not broken in main, the issue is resolved, but it does feel like we could use a regression test that covers this case, some that ensures that a Deno.readFileSync("bad_file"); produces a catchable error.

Agreed, should've been part of the unit tests as EISDIR is an _expected_ condition.

**Comment by PauloRSF** [comment] 2021-04-06 16:26
Hello, this question may be silly (i'm a beginner). I wrote a simple test just to check this behavior out with a local (canary) build:

```ts
import { assertThrows } from "https://deno.land/std@0.92.0/testing/asserts.ts";

Deno.test("readFileSync on dir", async () => {
  assertThrows(() => (
    Deno.readFileSync('/home/paulo/misc/temp_dir')
  ), Error, "Is a directory");
});
```

And got an AssertionError because the file handle is still open:

```
AssertionError: Test case is leaking resources.
Before: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr"
}
After: {
  "0": "stdin",
  "1": "stdout",
  "2": "stderr",
  "3": "fsFile"
}

Make sure to close all open resource handles returned from Deno APIs before
finishing test case.
    at assert (deno:runtime/js/06_util.js:33:13)
    at resourceSanitizer (deno:runtime/js/40_testing.js:84:7)
    at async Object.exitSanitizer [as fn] (deno:runtime/js/40_testing.js:100:9)
    at async TestRunner.[Symbol.asyncIterator] (deno:runtime/js/40_testing.js:272:13)
    at async Object.runTests (deno:runtime/js/40_testing.js:347:22)
    at async file:///home/paulo/misc/test_readfilesync/$deno$test.ts:3:1
```

Was that supposed to happen? If so, how can i ensure that it gets closed?

**Comment by lucacasonato** [comment] 2021-04-06 16:28
That is an unrelated Deno bug. Could you open an issue?

**Comment by PauloRSF** [comment] 2021-04-06 16:30
Sure!

**Comment by satyarohith** [comment] 2021-04-18 11:54
> Since we re-worked all of this, and the behaviour is not broken in main, the issue is resolved, but it does feel like we could use a regression test that covers this case, some that ensures that a `Deno.readFileSync("bad_file");` produces a catchable error.

I think this test case covers this issue.
https://github.com/denoland/deno/blob/204b699be4cf88e216572d77ad4cced9ab4748bc/cli/tests/unit/read_file_test.ts#L94

**Comment by satyarohith** [comment] 2021-04-28 13:41
@kitsonk can this issue be closed?

**Closed** 2021-04-28 13:46 UTC
Labels: bug, core
