### ISSUE TITLE
Panicked Error at 'called `Option::unwrap()` on a `None` value'

### ISSUE THREAD

**Issue by chrisbrocklesby** [denoland/deno#15660] opened 2022-08-29 04:25 UTC
## Error / Panicked:
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ext/flash/lib.rs:1316:42
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

Platform: macos aarch64
Version: 1.25.0
Args: ["deno", "run", "--unstable", "--allow-all", "--watch", "main.js"]

```js
import express from "npm:express";
const app = express();

app.get("/", function (req, res) {
  res.send("Hello Express");
});

app.listen(3000);
console.log("listening on http://localhost:3000/");
```

On changing a bit of code (as its watching) the error happens.

**Comment by littledivy** [comment] 2022-08-29 04:39
Duplicate of #15646

**Closed by littledivy** 2022-08-29 04:39 UTC
