### ISSUE TITLE
Deno Vite+Vue starting app bug after migrating from Windows to Mac

### ISSUE THREAD

**Issue by JetSetVideo** [denoland/deno#19087] opened 2023-05-11 08:05 UTC
I have a basic Vite+Vue app created from the command line. While working on Windows, it was working but couldn't be launch from Mac book M1. It said that a npm:package called "has" was missing and then it printed out:

Platform: macos aarch64
Version: 1.33.1
Args: ["/Users/macmax/.deno/bin/deno", "run", "-A", "--node-modules-dir", "npm:vite"]

thread 'main' panicked at 'not found package: vue@3.2.47', /Users/ib/.cargo/registry/src/github.com-1ecc6299db9ec823/deno_npm-0.3.0/src/resolution/graph.rs:376:17
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by bartlomieju** [comment] 2024-12-06 01:18
I'm gonna close this issue since there is no reproduction and I can't reproduce it on my end.

**Closed by bartlomieju** 2024-12-06 01:18 UTC
