### ISSUE TITLE
Standard Library Working Group

### ISSUE THREAD

**Issue by ry** [denoland/deno#8405] opened 2020-11-16 20:36 UTC
The standard library in Deno has seen a lot of growth and improvement over the past year. We think it is time to review and stabilize these APIs, guaranteeing that users will not experience painful changes in the future. In order to avoid cementing mistakes, we want to review these APIs, one-by-one, and come to a consensus on whether they should be included, modified, or excluded.

We will be holding a series of virtual events every two weeks. We will (perhaps tediously 😄 ) review APIs and hear any objections. Because there are so many APIs to review, this will take place over several months.

In order to accommodate people in different timezones, we will have an alternating timing schedule.

This issue will remain pinned and this message updated as we work through each of the modules. If you would like to participate, please join https://groups.google.com/g/deno-std 

December 3 (14:00-16:00 GMT)
- Discussion around std scope, process for adding new modules, and versioning
- async
- bytes

December 16 (21:00 - 23:00 GMT)
- archive
- datetime
- encoding
- flags

January 7 (time TBD)
- fmt
- fs
- hash

January 21 (time TBD)
- http
- io
- log

February 4 (time TBD)
- mime
- node
- path

February 18 (time TBD)
- permissions
- signal
- testing

March 4 (time TBD)
- textproto
- uuid
- wasi
- ws

**Comment by bartlomieju** [comment] 2020-11-17 00:47
Important topic to discuss (preferably sooner than later) is `std` versioning. We won't stabilize all APIs and there will be new APIs added in the future, therefore we should establish some convention similar to `--unstable` flag for built-in `Deno` APIs.

**Comment by MarkTiedemann** [comment] 2020-11-20 12:42
Another important topic to discuss (and write down) is the boundaries between core, std, and third-party modules. What are the criteria for APIs to be included in core? In std?

For example, in Node, the HTTP server is in core. Why is it in std in Deno? In Node, a TOML parser is a third-party module. Why is it in std in Deno?

I think having clearly defined boundaries between these realms would be helpful.

**Comment by hazae41** [comment] 2020-11-22 13:28
> Another important topic to discuss (and write down) is the boundaries between core, std, and third-party modules. What are the criteria for APIs to be included in core? In std?
> 
> For example, in Node, the HTTP server is in core. Why is it in std in Deno? In Node, a TOML parser is a third-party module. Why is it in std in Deno?
> 
> I think having clearly defined boundaries between these realms would be helpful.

- core aims to implement Web APIs and includes the native stuff
- std aims to standardize common modules
- third-parties are modules that don't fit in std

While Node is battery-included, Deno aims to be minimalist in its packaging

This is all explained here https://deno.land/manual@v1.5.3/runtime

**Comment by MarkTiedemann** [comment] 2020-11-22 15:37
@hazae41 I don't intend to discuss this topic now, I merely want to show that a discussion may be warranted.

> core aims to implement Web APIs and includes the native stuff

- `Deno.test` and `Deno.inspect` aren't Web APIs.
- `Deno.iter` and `Deno.copy` don't use "native stuff".

So yes, while "Web APIs" and "native APIs" are included in core,

- only a subset of Web APIs is included in core,
- only a subset of native APIs is included in core, and
- APIs that are neither Web APIs nor native APIs are also included in core.

> std aims to standardize common modules

- `MuxAsyncIterator` from `std/async` isn't a "common API" when searching for it on Google - there aren't even 1000 results.
- `printf` from `std/fmt` may be a common API in C, but is it a common API in JS development?
- There's APIs for `tar` in `std/archive`. Why are there no APIs for `zip`? Is `tar` common but `zip` uncommon?

"common modules" is a very subjective definition.

**Comment by timreichen** [comment] 2020-11-23 01:04
Agree with @MarkTiedemann to define clear boundaries. There seems to be lots of different ideas of what std is/should be.
I would like to mention, that it is a mix of mods with specification and mods that seem to fall more in the category of utility or convention atm.
Maybe the modules could be split in `std` for mods with specs (tar, hash, encoding, etc.), `util` (or something along those lines) for mods like log, fmt, async, node, etc. to have something between std and 3rd party?

@ry Shouldn't the title be [Standard Modules Working Group](https://deno.land/manual@v1.5.3/contributing/style_guide#use-the-term-quotmodulequot-instead-of-quotlibraryquot-or-quotpackagequot)?😉

**Comment by bartlomieju** [comment] 2020-11-25 14:38
After further discussion with @ry we've decided that first meeting will be mostly "organizational" one, where we'll discuss points mentioned above:
- versioning of `std` for stable and unstable APIs
- scope of `std` and heuristics for adding new modules
- organization of `std` directories (which directories should have submodules and which should have only `mod.ts`)

We'll also go through `async` and `bytes` modules to showcase the review process.

**Comment by timreichen** [comment] 2020-12-03 12:37
Sorry, I wont be able to make it for this meeting. Hope I can join the next one.

**Comment by bartlomieju** [comment] 2020-12-03 17:27
Notes from "std-wg" meeting on 03.12.2020

## versioning of std for stable and unstable APIs

General remarks:

- Currently if one of APIs in `std`'s module requires
`--unstable` CLI flag it requires to run whole module
with `--unstable` flag; would be great if those APIs
were separated from APIs that don't require `--unstable` flag.

- If an API in `std` depends on unstable API from `Deno`
namespace it should automatically be considered unstable.

Proposed solutions:

- Unstable modules would have `_unstable` suffix in the filename,
eg. `std/http/server_unstable.ts`

- Top level directory called `unstable` that mimics structure
of standard library

Other suggestions:

- @Soremwar suggests to decouple versioning of `std` from CLI

- @bartlomieju suggests to move `std` to a separate repo as it
was in the past (`deno_std`).

## scope of std and heuristics for adding new modules

Suggestions:

- @bartlomieju suggests that modules from top 500 npm modules
could make their way into std

- @caspervonb suggests module to be added to std has to have
a working implementation

- @Soremwar suggests module to be added to std has to have
standardized implementation (eg. SMTP)

- @Kevinkassimo suggests module election/RFC process; top 500
modules from npm is a lot of code, might need to be filtered;
suggests assigning code-owners/maintainers to modules

- @bartlomieju suggests to research Go's standard libarary in
more details as `std` is already a loose port (@wperron did that
recently, we're mostly covered already)

- @ry suggests anything in Go's standard libarary is fair-game in Deno

- @bartlomieju suggests we should checked standard libraries
in other languages, especially scripting ones (Python, Ruby, Lua)

- @lucacasonato suggests that `std` shouldn't include
highly opinionated modules; some modules might not make 
sense if we wait for JS spec instead (eg. temporal)

- @wperron likes RFC process idea, should make discussion better

No consensus yet.

## organization of std directories

- @wperron some modules are too small to have many modules

- @Soremwar is concerned how to make users know what modules
they're pulling from `std`

- @lucacastonato it depends heavily on concrete module

- @mayank have separate modules but a have to include 
all modules from directory (current `mod.ts` convention)

- @ry having a lot of unnecessary code in a module is worse 
than doing multiple requests

No consensus yet, keep the status quo for now, revisit at the later date.

## review std/async

- `deferred`
    - remove `Object.assign(...)`; instead directly assign `resolve` and `reject` (perf)
    - check is there's a TC39 proposal for similar functionality
    - make it a class (@mayank, #8601)
    - not stable

- `delay`
    - can be considered stable

- `muxAsyncIterator`
    - @bartlomieju asks if anyone uses it outside of `std/http`, @Soremwar uses it, it's useful
    - @Kevinkassimo suggests that name is confusing
    - should have less strict type for argument in "add()"
    - not stable

- `pooledMap`
    - heavy bike-shedding on the name (@wperron "workerMap", @bartlomieju "concurrentMap")
    - in general very useful utility
    - @ry suggests to change the name of the module

- README
    - uses untagged imports in code examples

- remove mod.ts
- @ry "async" is a catch-all module name and is not great, consider alternatives

## review std/bytes

- @Kevinkassimo suggest APIs could better resemble names of APIs on Array-likes
- methods should take generic parameter instead of only `Uint8Array` - debatable,
due to performance considerations for algorithms for different types, for now
let's keep as is
- @ry suggests to rename module to `binary`; @lucacasonato, @wperron concur,
after a discussion let's keep current name cause it's shorter
- think about performance of this module

- `concat`
    - `origin` arg should be named `a`
    - should take more parameters instead of only 2 (`...buf`)

- `contains`
    - @kevinkassimo suggests to rename; points out implementation is not efficient
    - @SyrupThinker suggests to align interface to Array (`includes` instead of `contains`)
    - should take "option bag" as 3rd argument; containing `offset` and `len` parameters

- `copyBytes`
    - rename to `copy`
    - can't specify how many bytes to copy

- `equal`
    - rename parameters to `a` and `b`
    - bike-shedding on the name (`equal` vs `equals`); should be consistent with other
        parts of `std` (eg. `assertEquals` from `testing` module)
    - update docs to inform that this function checks equality of array contents

- `findIndex`
    - update docs
    - rename to `indexOf`
    - should take start index as an optional arg
    
- `findLastIndex`
    - rename to `lastIndexOf`
    - should take index as an optional arg

- `hasPrefix`
    - rename to `startsWith`
    - consider adding `position` arg

- `hasSuffix`
    - rename to `endsWith`
    - consider adding `position` arg

- `repeat`
    - update docs
    - throw `RangeError` is `count` arg is negative

**Comment by wperron** [comment] 2020-12-03 21:20
Related to the semver resolution, there's an open issue on the registry to address this : https://github.com/denoland/deno_registry2/issues/153 I'm of the opinion that it's not strictly necessary, and there may be other options using etags or content-hashes served with the content of files so that multiple versions with the same content can be reused on the file system cache instead.

**Comment by benjamingr** [comment] 2020-12-05 21:46
Regarding Deferred: "check is there's a TC39 proposal for similar functionality"

This was the original API promises had (with `Promise.defer`) but it was deemed unsafe so the promise constructor was created - this is because the function can throw synchronously which means the API consumer need to guard against both sync and async exceptions.

Basically https://github.com/petkaantonov/bluebird/issues/555#issuecomment-210202156 and https://github.com/domenic/promises-unwrapping/issues/80 and 

I think it's better to just refactor it out of the code?

Regarding `delay` - I would consider exposing the same API as Node's `timers/promises` since it's the one browsers will probably implement. However, I am happy to add AbortSignal support to it if a PR would be useful. 

Regarding `pooledMap` - I think it's a pretty big footgun and I'd unship it, but if you want it I'd use the same `p-map` and bluebird terminology of `mapWithConcurrency(data, fn, { concurrency: ... })`.

**Comment by lucacasonato** [comment] 2020-12-05 22:11
> I think it's a pretty big footgun and I'd unship it

@benjamingr How so?

**Comment by benjamingr** [comment] 2020-12-06 06:52
> @benjamingr How so?

I've seen it used incorrectly very often:
 - developers assume that they're actually limiting the concurrency of whatever they're processing but they have multiple servers so it's not actually limited like they expect. (For example when making API calls to a rate-limited third-party)
 - developers assume that they're actually limiting the concurrency but it's limited by the system (for example an HTTP agent or the 6 connection per domain limit in the browser)
 - developers tend to not be great at understanding where their bottlenecks are in the code and rate-limit things like filesystem access in a way which has no actual impact and just complicates the code.

On the plus side - there _are_ some pretty reasonable use cases for it and in certain cases and applications it works well - but just like deferred as an API it's dangerous (with the difference that deferred can be easily done otherwise with the promise constructor and pooledMap can't)

**Comment by caspervonb** [comment] 2020-12-07 22:52
> I've seen it used incorrectly very often:

Can't that be said about just everything? If you don't read the docs you aren't going to have a good time.
I don't see anything in particular wrong with pooledMap, its a trivial implementation that does what it says on the tin which is very useful in some scenarios.

**Comment by benjamingr** [comment] 2020-12-07 22:59
> Can't that be said about just everything?

Not really? Platforms move from one abstraction to another (like callbacks to promises) since certain things are better than others.

Promises are still used incorrectly often even with async/await - but _much much less so_ than callbacks. I believe in most cases the user using a `pooledMap` should have done something else and when they use such a function it's often incorrectly. I say that having maintained the most popular implementation on NPM the past ±5 years.

A lot of API design is pushing users "to the pit of success" and giving them tools that don't only make them productive but also encourage good code. I don't believe `pooledMap` is like that.

You are welcome to ship a foot-gunny API. Nothing is stopping you, and adding things is always easy (especially if you can relatively easily remove them if you need to).

**Comment by benjamingr** [comment] 2020-12-07 23:02
And if I had to ship an API I'd probably ship something like:
 - `throat` (given a function, limit its concurrency), i.e. `Promise.all(arr.map(throat(fn, 30))` instead of `promiseMap(arr, fn, 30)` since it composes better and add a big warning.
 - go buffered channels (that "block" a promise until data is there and with max buffer size) and do `chan(30).of(arr).map(fn)` or something similar.

**Comment by caspervonb** [comment] 2020-12-07 23:09
> @caspervonb suggests module to be added to std has to have a working implementation

To elaborate a bit on that, when it comes to the domain of what to include that's subjective and probably going to have to be done via a voting/rfc process of sorts (there's only one instance of @ry so BDFL probably won't scale in the long term).

But I think there's a short list of absolute requirements for any rfc/proposal.

1. A measurable need/use for it.
2. A working, well tested implementation.
3. A champion as working groups tend to call it, e.g a person who's willing and able to work on getting that implementation integrated, proposals alone are fine but in FOSS they tend to result in zero work getting done.

**Comment by jsejcksn** [comment] 2020-12-08 21:18
In https://github.com/denoland/deno/issues/8405#issuecomment-738162035, Bartek lists several suggestions for renaming.

It seems like these new names are derived from similar functionality of existing JS language methods.

However, there is much code to write which won't have any analogs for comparison, and I think it would be very useful for there to be a guide which provides linguistic prescriptions for variable and function naming, a.k.a. a naming convention guide.

Here is a simplified example of the kind of content that I'm imagining, although these are not necessarily suggestions for inclusion:

---

- Functions should begin with a verb — `getDuplicateValues`, `convertEntries`
- Functions which return a `boolean` should begin with a helping verb<sup>1</sup> — `isInRange`, `hasChildren`, `doesLoop`
- etc.

<sup>1</sup> List of helping verbs: am, are, be, been, being, can, could, did, do, does, had, has, have, is, may, might, must, shall, should, was, were, will, would

---

Naming things is [one of the hard things in computer science](https://twitter.com/codinghorror/status/506010907021828096). The idea is not to create a pedantic filter for code review, but to help with [naming things](https://en.wikipedia.org/wiki/Naming_convention_(programming)).

**Comment by bartlomieju** [comment] 2020-12-16 23:22
Notes from "std-wg" meeting `#2` on 16.12.2020

Meeting recording: https://www.youtube.com/watch?v=RimiwgQr4gI

# `archive` directory

_This module seems to be have quite APIs, probably need a ground up rework._

Establish APIs that will work with different compressions algorithms, should look 
into golang APIs for this purpose.

- @bartlomieju Add zip
- @wperron: Add zlib - some compression stream Web API need zliB

`tar.ts`:
- “append()” - rename “fn” to “filename”
- `TarOptions` takes “filePath” which is similar to “fn” argument on “append()” method
- “TarOptions.filePath” - rename to “destinationFile”
- “Data” is a public property, should probably be private
- Docstrings are pretty lacking
- “getReader()” doesn’t clarify if can be called multiple times
- “contentSize” is used only with “reader” option
- Proposed API: “appendBuffer()”, “appendFile()” with different option bags
- Ryan: in go/archive module one create “TarWriter”, write header and then append bytes (agnostic of file/buffer distinction)


# `datetime` directory

`Temporal` API is in the proposal stage; we should consider it when working on this module (https://github.com/tc39/proposal-temporal).

- @ry proposes to move `datetime` module outside of `std/`, move it to a module in deno.land/x to 
give users time to migrate off of them
- Formatting and parsing is not part of Temporal API
- “Intl” API have formatting utilities 
- @timreichen has a PR open that should cover parsing and formatting, but the problem is testing of that functionality because
of timezones
- @kevinkassimo: Temporal API has a polyfill; @Soremwar tells that polyfill is outdated
- open a separate issue for further discussion

# `encoding` directory

- @sebastienfilion suggests to make encoding modules have class API so that it’s consistent with `TextEncoder`/`TextDecoder`
- Describe the difference between `decode`/`encode` and `parse`/`stringify` in the module README; `decode`/`encode` is between primitive JS types, `parse`/`stringify` is for serialising objects to string and back

## `ascii85`
- Ascii85Options - takes “delimiter” that is not used “decode”
- Why “options.standard” named that, instead of “encoding” (it’s a prefix?)
- Follow what golang does and require user to strip prefixes themselves
- Stripping prefixes as a separate utility function in the module
- Add option to strip/not strip prefix

## `base32`
- @sebastienfilion doesn’t like byteLength() API, @bartlomieju concurs

## `Base64`
- Doesn’t have byteLength() like `base32`
- `encode()` accepts `ArrayBuffer` or `string`, not sure why
- @ry: Go’s version has interfaces that accept `Reader`/`Writer` instead of fixed length string
    - @wperron: all of them have Reader/Writer interface, but some of them will have decode/encode functions without the interface
    - @ry so in Deno we could do the reverse, have free function and some of them would take reader/writer
- @lucacastonato, maybe we should use Streams API instead of reader/writer

## `base64url`
- Internally calls `base64`
- @lucacasonato these APIs should be options in the `base64` module
- @sebastienfilion helper function should be exposed instead of integrating in `base64`
- Go has `withPadding` function 
- Not very popular module
- @ry seems like merging into base64 would make more sense
- @lucacasonato we should check btoa and atob (?)

## `binary`
- `getNBytes()`:
    - is broken, there’s an issue about it
    - naming is debatable
- rename following APIs:
    - `putVarnum` -> `setNumber`
    - `putVarbig` -> `setBigint`
    - `varbig` -> `getBigint`
    - `varnum` -> `getNumber`
    - `varbigBytes` -> `bigintIntoBytes`
    - `varnumBytes` -> `numberIntoBytes`
- `DataType` members are not exported and they should be

## `csv`
- @bartlomieju should we rename to decode/encode
- @sebastienfilion don’t rename to decode/encode
- `parse` - why does that method take “BufReader” instead of “Reader”? why does it return Promise of array instead of AsyncIterable?
- `ParseOptions.parse` should use stronger types than unknown/unknown?
- @sebastienfilion why does `parse` is async, we should make it sync and add separate API for streaming (analogous to `JSON.parse`)
- `ReadOptions` should have JSdoc on each field instead of the interface itself
-  @ry rename “readMatrix” to “parse”
- `parse` should be renamed and return AsyncIterator, remove `opt.parse` callback
- `parse` and `readMatrix` should have sync and async version
- `ObjectWithStringPropertyKeys` should removed
- `stringify` should be sync
- Remove exported variables; either remove completely or make variants of ParseError
- `csv_stringify.ts` - should be merged with `csv.ts`
- @timreichen Can we make it similar to `JSON.parse` by having a “CSV” object with methods
- @lucacasonato Users can import like: `import * as CSV from "..."` to achieve that
- CC @jsejcksn who wrote this module

## `hex`
- `decode` - needs to update JS doc
- `decodedLen` and `encodedLen` should be removed
- `errInvalidByte` and “errLength` should be private, they should return better errors (maybe TypeError), should remove “encoding/hex” from the error message
- `decodeString` and `encodeToString` should be remove, one can do that manually

## `utf8` 
- should be removed

## `toml`
- @marktiedemann module is too simple, parsing is not yet complete, “npm” modules are way more advanced
- Explore compiling Rust version of TOML into WASM and do the same fo YAML

**Comment by jsejcksn** [comment] 2020-12-17 00:03
> * `stringify` should be sync

It is async in order to allow for async transforms during stringification of column data. If it is decided that the transforms must be required to be synchronous, then there's nothing else to prohibit making it sync.

> * Remove exported variables; either remove completely or make variants of ParseError

I'm not what this means exactly. Could whoever said it during the meeting clarify which exports they mean?

> * `csv_stringify.ts` - should be merged with `csv.ts`

It is intentionally a separate module because it is browser-compatible and the code in `csv.ts` is not. This is desirable IMO so that the code can be re-used without modification in browser envs. Isn't that the whole point of asking contributors to document browser compatibility?

https://github.com/denoland/deno/blob/master/docs/contributing/style_guide.md#document-and-maintain-browser-compatibility:

> #### Document and maintain browser compatibility.
> 
> If a module is browser compatible, include the following in the JSDoc at the top
> of the module:
> 
> ```ts
> /** This module is browser compatible. */
> ```
> 
> Maintain browser compatibility for such a module by either not using the global
> `Deno` namespace or feature-testing for it. Make sure any new dependencies are
> also browser compatible.

**Comment by lucacasonato** [comment] 2020-12-17 00:25
> Could whoever said it during the meeting clarify which exports they mean?

@jsejcksn You can watch the VOD at https://www.youtube.com/watch?v=RimiwgQr4gI. We meant the `ERR_*` constants.

**Comment by jsejcksn** [comment] 2020-12-17 00:43
> You can watch the VOD at https://www.youtube.com/watch?v=RimiwgQr4gI.

@lucacasonato Thanks—it's quite a long video. The beginning timestamp for `csv`: https://www.youtube.com/watch?v=RimiwgQr4gI&t=1h21m17s.

**Comment by timreichen** [comment] 2020-12-17 00:46
> rename following APIs:
putVarnum -> setNumber
putVarbig -> setBigint
varbig -> getBigint
varnum -> getNumber
varbigBytes -> bigintIntoBytes
varnumBytes -> numberIntoBytes

Aligning to BigInt methods of DataView, probably should be an uppercase "I" in "int":
`putVarbig` -> `setBigInt`
`varbig` -> `getBigInt`
And maybe the renaming of these functions should use "to" instead of "into", like in `atob` or `btoa`?
`varbigBytes` -> `bigIntToBytes`
`varnumBytes` -> `numberToBytes`

**Comment by timreichen** [comment] 2020-12-17 00:52
> @timreichen has a PR open that should cover parsing and formatting, but the problem is testing of that functionality
because
of timezones

Slight correction: PR covers timeoffset `Z` symbols, which poses problems for testing due to timezones. Parsing and formatting is already implemented and working.

**Closed** 2020-12-17 06:20 UTC
Labels: user feedback wanted
