### ISSUE TITLE
deno.json(workspace): Warning "compilerOptions" field can only be specified in the workspace root deno.json file

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#25778] opened 2024-09-20 21:20 UTC
deno 2.0.0-rc.4+a92ebd9

I have a mono repo, and one of my packages is a solid-js frontend app, where I need need to have a deno.json (used to be tsconfig.json) for just that solid-specific package (just an example of package specific ts config, unrelated to #25767 ):

```
{
  "compilerOptions": {
    "jsx": "preserve",
    "jsxImportSource": "solid-js"
  }
}
```

When I run `deno install` in root, I get the :

```
➜ deno install
Warning "compilerOptions" field can only be specified in the workspace root deno.json file.
```

So with this constraint, a deno workspace can't contain multiple of (react, react native, solid) at the same time.

Haven't thought it through, but maybe it would be better to have it be package level, than workspace level:
> "compilerOptions" field can only be specified in the **package** root deno.json file"

**Comment by dsherret** [comment] 2024-09-21 15:56
Duplicate of #24504

**Closed by dsherret** 2024-09-21 15:56 UTC
Labels: duplicate
