### ISSUE TITLE
deno test simply prefixes everything with `test <testname>`

### ISSUE THREAD

**Issue by aricart** [denoland/deno#6083] opened 2020-06-03 20:07 UTC
With multiple files, it would be more useful if the test runner simply listed `<test_file> <testname>`. To provide a hint of the location of the test.

**Comment by nayeemrmn** [comment] 2020-06-03 20:16
Duplicate of #4644.

Not possible, a function can't know "what module it's being run from" without doing something really hacky which probably won't work for wrappers around `Deno.test()`. The error stack from a failing test should be enough, right?

**Comment by bartlomieju** [comment] 2020-06-16 14:37
Please continue in #4644

**Closed by bartlomieju** 2020-06-16 14:37 UTC
