### ISSUE TITLE
File Path in Stack Traces differ depending on how code is run

### ISSUE THREAD

**Issue by JavaScriptDude** [denoland/deno#5483] opened 2020-05-16 01:09 UTC
I've been porting over some debugging code into Deno 1.0.0 and discovered that the file path in stack traces can be suppressed under certain scenarios. 

I have simplified the test scenario to the following code:
```typescript
// Place this code in /tmp/deno_test as path_test.ts
// % cd /tmp/deno_test
// % deno run path_test.ts
// Exception contains full path
// % cd /tmp
// % deno run deno_test/path_test.ts
// Exception does not contain full path!!

import * as path from "https://deno.land/std/path/mod.ts";

function f1(){ throw new Error("damn") }

try {
  f1()
}catch(e){
  console.log(e)
}
```

Here the output from my Ubuntu 20.04 with Deno 1.0.0:
```bash
/tmp/deno_test$ deno run path_test.ts 
Compile file:///tmp/deno_test/path_test.ts
Error: damn
    at f1 (file:///tmp/deno_test/path_test.ts:11:22)
    at file:///tmp/deno_test/path_test.ts:14:3
/tmp/deno_test$ cd ../
/tmp$ deno run deno_test/path_test.ts 
Compile file:///tmp/deno_test/path_test.ts
Error: damn
    at f1 (path_test.ts:11:22)
    at path_test.ts:14:3
```

When the line `import * as path from "https://deno.land/std/path/mod.ts"` is commented out the issue goes away on my machine.

**Comment by nayeemrmn** [comment] 2020-05-16 01:15
Duplicate of #5202.

**Closed** 2020-05-16 01:18 UTC
