### ISSUE TITLE
Deno arm64 executable doesn't work.. 

### ISSUE THREAD

**Issue by kakashi-69-xd** [denoland/deno#22727] opened 2024-03-06 02:34 UTC
Version: latest

I'm using it on an android 10 phone..
termux

```sh
u0_a605@localhost ~/.deno/bin$ ls
deno
u0_a605@localhost ~/.deno/bin$ ./deno
zsh: no such file or directory: ./deno
```

even after I copied the contents of the `deno` executable and chmoded it.. it didn't work
```sh
u0_a605@localhost ~/.deno/bin$ ls
deno  deno.bak
u0_a605@localhost ~/.deno/bin$ chmod +x deno                          u0_a605@localhost ~/.deno/bin$ ls
deno  deno.bak
u0_a605@localhost ~/.deno/bin$ ./deno
zsh: no such file or directory: ./deno
u0_a605@localhost ~/.deno/bin$
```

I tried the same in bash as well

```bash
u0_a605@localhost ~/.deno/bin$ bash                           127 ↵
~/.deno/bin $ ls
deno  deno.bak
~/.deno/bin $ ./deno
bash: ./deno: cannot execute: required file not found
~/.deno/bin $
```

**Comment by littledivy** [comment] 2024-03-06 04:36
arm64 android is not support at the moment. The executable targets arm64-linux-gnu. 

Duplicate of https://github.com/denoland/deno/issues/19759

**Closed by littledivy** 2024-03-06 04:36 UTC

**Comment by CodeIter** [comment] 2024-05-16 19:23
I made a shell script [termux-pacman-glibc-setup.sh](https://gist.github.com/CodeIter/ccdcc840e432288ef1e01cc15d66c048#file-termux-pacman-glibc-setup-sh) to setup `glibc-runner` with pacman on Termux and install Deno.JS and Bun.JS  as a demo.
