### ISSUE TITLE
`Deno.bench` does not allow specifying setup/teardown functions for each execution

### ISSUE THREAD

**Issue by KrofDrakula** [denoland/deno#17589] opened 2023-01-30 12:07 UTC
Benchmarking functions that mutate their operands is currently impossible to measure without also including the setup portion of the run in the measurement. This will cause the benchmarks to give erroneous results when measuring relative performance of such functions.

Consider the case where we have two functions performing a mutative operation on a large array that we would like to compare:

```ts
const a = <T>(arr: T[], ...items:T[]): T[] => { /* impl A */ };
const b = <T>(arr: T[], ...items:T[]): T[] => { /* impl B */ };

const getSample = () => {
  const sample: number[] = [];
  for (let i = 0; i < 1e6; i++) sample.push(i);
  return sample;
};

Deno.bench('a', {baseline: true}, () => {
  const data = getSample();
  a(data, -1);
});

Deno.bench('b', () => {
  const data = getSample();
  b(data, -1);
});
```

In this case, creating the data on each run will incur an almost fixed time cost on each run measurement.

I could not identify a way to run a function before or after each execution to set up the data outside of the measurement run.

One solution would be to allow specifying `setup()` and `teardown()` functions by extending the `BenchDefinition` interface:

```ts
type BenchDefinition = Parameters<typeof Deno.bench>[0]

type ExtendedBenchDefinition<T> = BenchDefinition & {
  setup: () => T;
  fn: (data?: T) => unknown;
  teardown: () => void
}
```

That way, one could provide provide pre- and post-run function outside of the measurement loop to setup up or reset the requisite data:

```ts
// using setup
Deno.bench({
  name: 'a',
  setup() { return getSample(); },
  fn(data) {
    a(data, -1);
  }
});

// or alternatively using teardown:
let data = getSample();
Deno.bench({
  name: 'a',
  fn() {
    a(data, -1);
  },
  teardown() {
    data = getSample();
  }
});
```

**Comment by KrofDrakula** [comment] 2023-01-30 13:14
Just for reference, here is how [`benchmark.js`](https://benchmarkjs.com/) approaches this:

- https://benchmarkjs.com/docs/#prototype_setup
- https://benchmarkjs.com/docs/#prototype_teardown

[`Matcha`](https://github.com/logicalparadox/matcha) approaches this similarly:

- https://github.com/logicalparadox/matcha#setupteardown

Alternatively, [`nanobench`](https://github.com/mafintosh/nanobench) offers marker functions to mark blocks to benchmark, eliminating the need for setup/teardown or wrapping the block in another function:

- https://github.com/mafintosh/nanobench#usage

A Deno implementation could offer the same kind of functionality:

```ts
Deno.bench('a', ({ start, end }) => {
  // set up data
  let data = getSample();

  start();
  a(data, -1);
  end();

  // this is just a dumb example of some teardown
  data = undefined;
});
```

In this case, if `start` isn't called, it is assumed that the entire function's runtime should be counted towards the statistics, and `end` must be called afterwards and before a set timeout. This would also work for async functions.

A more complicated example in [`Benny`](https://caderek.github.io/benny/) requires returning functions which allows setting up state in a closure and returning the benchmarked function, but that could cause problems when benchmarking higher-order functions in general:

- https://caderek.github.io/benny/#async-benchmark-with-setup---return-a-promise-wrapped-in-a-function

To me, it seems overly complicated to think about return types, especially if you're used to writing arrow functions without braces that could return functions in unexpected cases.

**Comment by Seally** [comment] 2023-02-01 18:19
For the sake of reference, this is a duplicate of the bot-closed issue that I've been watching for a while: https://github.com/denoland/deno/issues/14510

**Comment by Seally** [comment] 2023-02-01 23:22
If you want comparisons, you can also mention the original Deno benchmarking framework in Deno `std`, before it was deprecated and removed in favour of `Deno.bench`. The API required you to call `start()` and `stop()` manually, and start the actual benchmark with `runBenchmark()`. It's admittedly a bit more unwieldy to use than the current API, but setup/teardown was pretty easy to do. The `start/stop` part is also very similar to one of your proposed APIs.

`v0.158.0` I think is the last version of `std` that has the old API before it was removed entirely, though it was deprecated long before then:
<https://github.com/denoland/deno_std/tree/0.158.0/testing>

As additional context, `Deno.bench` itself was introduced as an unstable feature in Deno `v1.20` and stabilized in `v1.28`.

**Comment by nayeemrmn** [comment] 2023-04-17 04:07
+1 for the `BenchContext::{start,end}` functions, where each of these can optionally be called and respectively default to the function's start/end if they aren't. I prefer it to the setup/teardown options because the state is trivially shared between the three phases (without enclosing top level vars or doing tedious stuff with the arguments).

> * https://github.com/mafintosh/nanobench#usage
> 
> A Deno implementation could offer the same kind of functionality:
> 
> ```ts
> Deno.bench('a', (t) => {
>   // set up data
>   let data = getSample();
> 
>   t.start();
>   a(data, -1);
>   t.end();
> 
>   // this is just a dumb example of some teardown
>   data = undefined;
> });
> ```

**Closed** 2023-07-31 10:03 UTC
