### ISSUE TITLE
std crypto module in WebAssembly?

### ISSUE THREAD

**Issue by chiefbiiko** [denoland/deno#3098] opened 2019-10-10 15:14 UTC
How about building a crypto module entirely implemented in WebAssembly?

Benefits would include: good performance, optimal portability

Luckily, we could also get timing safety for WebAssembly by patching V8 to [implement CT-Wasm](https://github.com/denoland/deno/issues/3097).

**Comment by kitsonk** [comment] 2019-10-10 17:51
Really should talk about it in #2372 or #1891 to avoid having loads of issues.

**Comment by thefliik** [comment] 2019-10-13 23:54
FYI, this is also being discussed in the context of WASI https://github.com/WebAssembly/WASI/issues/65

**Comment by tniessen** [comment] 2020-01-20 17:49
>  Benefits would include: good performance

The performance will likely be much worse than native performance, especially since you lose all hardware features, e.g., hardware-accelerated AES.

> ... optimal portability

Wouldn't "patching V8 to implement CT-Wasm" diminish the portability aspect since the patch would affect platform-specific bytecode generation?

Also, time-safety might be the most obvious side attack channel, but there are likely others that would make a WebAssembly implemention insecure. (For example, no memory protection, cache statistics, etc.)

**Comment by lucacasonato** [comment] 2020-08-13 12:15
Isn't this covered by std/hash + WebCrypto (#1891) support?

**Comment by kitsonk** [comment] 2020-08-13 22:47
Yes, I still feel this is a duplicate of #1891

**Closed** 2020-08-13 22:54 UTC
