### ISSUE TITLE
Console.log shows garbage on Windows Server 2012

### ISSUE THREAD

**Issue by Desibabe** [denoland/deno#6367] opened 2020-06-18 17:27 UTC
I wrote a program to watch an incoming files in inbox folder and it's working fine, except some garbage shows on the screen, however, this works fine one Windows 10. I used the following code:

import { green, magenta, red, bold, underline } from "https://deno.land/std/fmt/colors.ts";
const success = (text: string) => {
  console.log(green(bold(text)));
}

success(`Watching the folder: C:/OpenAS2/data/inbox`);

Shows the attached image. 
![consolelog](https://user-images.githubusercontent.com/65683417/85052595-d4981400-b15e-11ea-8ac1-a80597ee359a.jpg)

**Comment by caspervonb** [comment] 2020-06-19 01:44
Those are ansi escape sequences; which apparently cmd.exe doesn't know how to interpret; Not a windows guy but I believe Powershell will interpret them correctly.

The new windows terminal supports them fully but I believe that is Windows 10 only.

**Comment by ry** [comment] 2020-06-19 09:16
Ideally we'd be able to detect if running in cmd.exe and turn off color. Not sure if this is possible.

**Comment by Desibabe** [comment] 2020-06-19 12:24
Thank you Ryan and it's working now. Somehow, color doesn't work on Windows Server. Here is the modified code:

import { green, magenta, red, bold, underline } from "https://deno.land/std/fmt/colors.ts";
const success = (text: string) => {
console.log(green(bold(text)));
}

const log = (text: string) => {
console.log(text);
}

log(Watching the folder: C:/OpenAS2/data/inbox);

**Comment by MarkTiedemann** [comment] 2020-06-21 19:29
`cmd.exe` does support colors on Windows 10 (see [_Console Virtual Terminal Sequences_](https://docs.microsoft.com/en-us/windows/console/console-virtual-terminal-sequences)).

![Capture](https://user-images.githubusercontent.com/7062160/85233201-dbe04b80-b404-11ea-8ea3-f4002de05af5.PNG)

Not sure about Windows Server 2012...

**Comment by obnoxiousnerd** [comment] 2020-07-06 06:22
Maybe we should take a look on how NodeJS implement colors. Because NodeJS colors show up on every OS.

**Comment by ry** [comment] 2020-07-06 13:00
For fun here's the moment @piscisaureus first got cross-platform terminal colors working in 2011 
https://youtu.be/Prav2iZZtP4
This was in Node, but I believe we were the first to achieve it any system.

**Comment by obnoxiousnerd** [comment] 2020-07-08 10:03
@ry Care to mention how did you achieved colors in Node??

**Comment by caspervonb** [comment] 2020-07-09 00:09
Can use the win32 console API; but since Windows is moving towards more unix style terminals I think it's fine to abandon legacy here.

Otherwise all formatting would have to go in cli.. which isn't optimal IMHO.

**Comment by neroux** [comment] 2020-07-13 11:19
As @Spoonbender pointed out, this is a duplicate of #5498.

**Comment by bartlomieju** [comment] 2020-11-09 17:52
Closing in favor of https://github.com/denoland/deno/issues/5498

**Closed by bartlomieju** 2020-11-09 17:52 UTC
Labels: cli :computer:, windows 🗔
