### ISSUE TITLE
deno installation script support risc-v

### ISSUE THREAD

**Issue by summer-boythink** [denoland/deno#26310] opened 2024-10-16 13:25 UTC
After I installed deno on the official website, I found that it could not be executed. Is it the problem of my operating system or does deno download script not support risc-v

<img width="761" alt="image" src="https://github.com/user-attachments/assets/190cf8c5-5e4a-4f53-9cc4-7fe962e3bed4">

<img width="564" alt="image" src="https://github.com/user-attachments/assets/251e2a8b-f807-40ba-9703-e2af692db727">

**Comment by littledivy** [comment] 2024-10-16 17:30
Duplicate of https://github.com/denoland/deno/issues/18702

**Closed by littledivy** 2024-10-16 17:30 UTC
