### ISSUE TITLE
Introduce a way to tell `deno run` to parse the script as TypeScript

### ISSUE THREAD

**Issue by dadooda** [denoland/deno#13393] opened 2022-01-17 09:10 UTC
Hey community,

I presume it would be nice to have an option flag to `deno run` to tell that one wants to parse the file as TypeScript even though it doesn't have a `.ts` extension.

Consider this CLI shebang executable script, named `hello.ts` and `hello`:

```ts
#!/usr/bin/env -S deno run

let s: string = "Hello world"
console.log(s)
```

Trying to run it produces the following:

```
$ ./hello.ts
Check file:///tmp/deno-run/hello.ts
Hello world

$ ./hello
error: Uncaught SyntaxError: Unexpected token ':'
let s: string = "Hello world"
     ^
    at <anonymous> (file:///tmp/deno-run/hello:3:6)
```

As there could be multiple reasons to have a CLI executable named without the `.ts` extension, I think it would be great to have something like `deno run --ts` or `deno run --language=ts` in order to force TypeScript processing of the specified script.

**Comment by crowlKats** [comment] 2022-01-17 09:11
Duplicate of #5088

**Closed by crowlKats** 2022-01-17 09:11 UTC
