### ISSUE TITLE
read waits for process end rather return what is available

### ISSUE THREAD

**Issue by hayd** [denoland/deno#3416] opened 2019-11-28 06:08 UTC
The [documentation](https://deno.land/typedoc/interfaces/deno.readcloser.html#read) suggests read should return immediately rather than wait for the program to exit:

> conventionally returns what is available instead of waiting for more.

Example:
```ts
const p = Deno.run({
  args: [
    "python",
    "-c",
    "import time; print('hello'); time.sleep(2); print('kill before this')"
  ],
  stdout: "piped"
});

console.log("waiting...");
await new Promise(resolve => setTimeout(resolve, 1000));

console.log("reading");
const buf = new Uint8Array(100);
const n = Number(await p.stdout.read(buf)); // Ignore EOF.
console.log(`read ${n} bytes from stdout`);

const dec = new TextDecoder();
console.log("read:", JSON.stringify(dec.decode(buf.slice(0, n))));

p.kill(9);
console.log(await p.status());
console.log("killed");
``` 

output:
```
waiting...
reading
read 23 bytes from stdout
read: "hello\nkill before this\n"
{ signal: 9, success: false }
killed
```

expected:

```
waiting...
reading
read 6 bytes from stdout
read: "hello\n"
{ signal: 9, success: false }
killed
```

**Comment by hayd** [comment] 2019-12-04 07:13
A related issue seems to be if there are 0 bytes to read (read waits forever).

**Comment by kevinkassimo** [comment] 2020-02-08 22:16
Quite a while since the problem, but I noticed that if we switch `python` with a simple shell script or even Deno itself, the problem becomes not reproducible:

Shell:
```ts
const p = Deno.run({
  args: [
    "bash",
    "-c",
    "echo 'hello'; sleep 2; echo 'kill before this'"
  ],
  stdout: "piped"
});

console.log("waiting...");
await new Promise(resolve => setTimeout(resolve, 1000));

console.log("reading");
const buf = new Uint8Array(100);
const n = Number(await p.stdout.read(buf)); // Ignore EOF.
console.log(`read ${n} bytes from stdout`);

const dec = new TextDecoder();
console.log("read:", JSON.stringify(dec.decode(buf.slice(0, n))));

p.kill(9);
console.log(await p.status());
console.log("killed");
```
Deno:
```ts
const p = Deno.run({
  args: [
    "deno",
    "eval",
    "console.log('hello'); setTimeout(() => console.log('kill before this'), 2000);"
  ],
  stdout: "piped"
});

console.log("waiting...");
await new Promise(resolve => setTimeout(resolve, 1000));

console.log("reading");
const buf = new Uint8Array(100);
const n = Number(await p.stdout.read(buf)); // Ignore EOF.
console.log(`read ${n} bytes from stdout`);

const dec = new TextDecoder();
console.log("read:", JSON.stringify(dec.decode(buf.slice(0, n))));

p.kill(9);
console.log(await p.status());
console.log("killed");
```
Both outputs
```
waiting...
reading
read 6 bytes from stdout
read: "hello\n"
{ signal: 9, success: false }
killed
```

**Comment by piscisaureus** [comment] 2020-02-08 22:19
I suspect the problem is with python, you need to tell it to flush it's stdout.
How? https://stackoverflow.com/a/230774

**Comment by kevinkassimo** [comment] 2020-02-08 22:19
It turns out simply Python does not flush after the first `print`. Inserting a `sys.stdout.flush()` fixes the problem.

This should not be a bug of Deno itself. I believe we could close this

**Closed** 2020-02-08 22:19 UTC
Labels: bug

**Comment by hayd** [comment] 2020-02-08 22:22
Yikes, thanks for investigating! Ok, I will see if I can reproduce this with the actual motivating Deno example:

https://github.com/hayd/deno-lambda/blob/0.9.5/tests/server.ts#L18

**Comment by hayd** [comment] 2020-02-12 05:24
The problem I was having was awaiting stdout for a program which _never_ prints to stdout:

- Process never exits so must be killed
- Process doesn't necessarily print to stdout (so the `await p.stdout.read` may hang forever, and cannot be cancelled)

[workaround](https://github.com/hayd/deno-lambda/commit/651f03d2e1dca3709fb38cb7d46f5d56b9dedc27#diff-05b0276744e64e1d580d2fd17d3af935R87) is to exit 🤷‍
