### ISSUE TITLE
Missing completions in VSCode

### ISSUE THREAD

**Issue by nicolo-ribaudo** [denoland/deno#23681] opened 2024-05-03 15:54 UTC
Version: Deno 1.43.1

I have an empty project/folder containing this file:
```js
import * as t from "https://esm.sh/@babel/types@8.0.0-alpha.8/lib/index.js";

t. // <-- cursor here
```

When I trigger completions nothing show up, and the output panel shows `Received an undefined response from tsc for completion details.`. 

However, if I copy-paste the `.d.ts` of that file locally and disable the Deno extension, TypeScript properly shows completions.

**Comment by nayeemrmn** [comment] 2024-07-07 05:54
Can't reproduce as of 1.44.4. Closing for now, please comment if it's still an issue.

**Closed by nayeemrmn** 2024-07-07 05:54 UTC
Labels: bug, lsp
