### ISSUE TITLE
lsp: Import map resolving does not work correctly

### ISSUE THREAD

**Issue by antoniogamiz** [denoland/deno#9923] opened 2021-03-27 13:04 UTC
**Describe the bug**

I'm trying to use an import map in my Deno project. I set up the import map like:

~~~json
{
    "imports": {
        "interfaces/": "./interfaces/",
    }
}
~~~

But when in another file I type:

~~~typescript
import { IEnergyMeterValidator } from "interfaces/validators/mod.ts";
~~~

It shows the following error:

~~~
relative import path "interfaces/validators/mod.ts" not prefixed with / or ./ or ../ Imported from "file:///c%3A/Users/anton/Documents/inversor/validators/EnergyMeterValidator.ts"deno(invalid-specifier)
~~~

All those files exist and if I run the command `deno run --import-map=import_map.json validators\EnergyMeterValidator.ts` from the command line it works great.

Here is my vscode configuration:

~~~json
{
    "deno.enable": true,
    "deno.lint": true,
    "deno.unstable": true,
    "deno.importMap": "./import_map.json"
}
~~~

**To Reproduce**

1. Recreate the file structure described above.
2. Copy my vscode configuration in vscode.
3. Copy my `import_map.json`.
3. Go to `EnergyMeterValidator.ts` and see the import line in red.

**Expected behavior**

The error should not be shown and the import map should be taken into account.

**Versions**

vscode: 1.54.3
deno: 1.8.2
extension: 3.2.0

**Comment by kitsonk** [comment] 2021-04-06 06:44
Closing as duplicate of #9744 (which I am going to start working on fixing)

**Closed by kitsonk** 2021-04-06 06:44 UTC
Labels: duplicate

**Comment by waynebloss** [comment] 2022-08-12 02:19
I'm getting this same issue on Linux (Manjaro) and when I add `deno.importMaps` to my vs code workspace settings, I get the following and the imports still don't work:

```log
Warning: Import map "deno_imports.jsonc" configured in "file:///yada/yada/deno.jsonc" being ignored due to an import map being explicitly configured in workspace settings.
```

**Comment by waynebloss** [comment] 2022-08-12 02:21
OK, I think my problem was that I tried to make the import map a `jsonc` file. Because I took out the comments and changed the file extension and now it works.
