### ISSUE TITLE
More Control Over Cached Dependencies

### ISSUE THREAD

**Issue by mohammadbasyouni** [denoland/deno#10493] opened 2021-05-04 20:39 UTC
As it's clear for us that Deno caches the deps in a cache folder (as I have in my GNU/Linux box), it'd be much nicer to have the control over deleting a specific version of any cached module with it's deps from the cache folder with a Deno `SUBCOMMAND` than deleting it manually.

**Comment by kitsonk** [comment] 2021-05-04 21:03
Do you have a specific use case? Like why you need to delete a specific version? What would you expect on the command line?

**Comment by mohammadbasyouni** [comment] 2021-05-04 21:52
Take Oak for example, when i was learning it it had an older version, but at the current time I no longer use that version, I use the the latest one for a [current project](https://github.com/mohammadbasyouni/notes-app) that I'm working on; mean while there's a file in my disk that i don't use any more, and if i wanted to I will go to 3rd party modules and cache it simply.

I expect a command for listing my deps with its versions on the console 
command: `deno list oak`
result: 
`     - oak@v7.0.0/mod.ts
     ...
     - oak@v7.3.0/mod.ts`
     from the oldest to the latest cached one
     
a command to list them all
command: `deno list`
result: 
`     - oak@v... [list all cached oak versions with its cached files like before]
     - std@v... [...]
     . . . {list the rest of the modules}`
     
A `-d`/`--deps`/`--dependecies` flag can be added to list the module with its dependencies
command: `deno list -d oak` / `deno list oak -d`
result:
     `- oak@v.../mod.ts
     - std@0.94.0/http/server.ts
     . . .`
     
a command to uncache / delete a file or a folder with its files (cached modules)
command: `deno delete oak` to remove all versions of oak from the cached folder 
- or `deno delete oak@v7.0.0` to delete a specific version from the cached oak modules
- or `deno delete oak@v[7.0, 7.3]` to delete a range of cached versions from a specific module
- the `-d` flag can be added to delete also the deps with its module

I hope I made it clear :)

**Comment by crowlKats** [comment] 2021-05-04 21:59
The Deno CLI is not related or dependent on the deno.land/x/ registry

**Comment by nayeemrmn** [comment] 2021-05-04 22:52
Duplicate of #3437, #5600.

**Comment by kitsonk** [comment] 2021-05-04 22:56
@nayeemrmn agreed... closing as duplicate.

**Closed by kitsonk** 2021-05-04 22:56 UTC
Labels: cli, suggestion
