### ISSUE TITLE
The jsxSingleQuote option should be provided in the Deno formatter. like Prettier.

### ISSUE THREAD

**Issue by jabed-web-dev** [denoland/deno#27412] opened 2024-12-18 06:35 UTC
**So that it can be written like this. deno.json**

```json
"fmt": {
    "singleQuote": true,
    "jsxSingleQuote": false,
}
```

**Comment by dsherret** [comment] 2024-12-20 23:15
Duplicate of https://github.com/denoland/deno/issues/26782

**Closed by dsherret** 2024-12-20 23:15 UTC
Labels: suggestion, duplicate, deno fmt
