### ISSUE TITLE
deno test errors when I have `deno.bench`s in the same file

### ISSUE THREAD

**Issue by CanRau** [denoland/deno#14944] opened 2022-06-23 02:56 UTC
Using Deno `1.23.0`, when I have `deno.test` cases and `deno.bench` benches in the same file, in this case it's called `strip-comments_test.ts`

```
deno bench --no-check --unstable strip-comments_test.ts
```
works as expected

whereas

```
deno test --no-check --unstable strip-comments_test.ts
```

throws 

```
Uncaught error from ./strip-comments_test.ts FAILED

 ERRORS 

./strip-comments_test.ts (uncaught error)
error: TypeError: ops[opName] is not a function
Deno.bench("strip-comments", () => {
     ^
    at Object.opSync (deno:core/01_core.js:170:38)
    at Object.bench (deno:runtime/js/40_testing.js:672:10)
    at file:///Users/Can/Projects/Konduktum/Konduktum-2022/konduktum-remix-deno/strip-comments_test.ts:134:6
This error was not caught from a test and caused the test runner to fail on the referenced module.
It most likely originated from a dangling promise, event/timeout handler or top-level code.

 FAILURES 

./strip-comments_test.ts (uncaught error)

FAILED | 0 passed | 1 failed (261ms)
```

example file for reproduction

```ts
// mentioned in https://github.com/unocss/unocss/issues/1139#issuecomment-1163635346
import { assertEquals } from "https://deno.land/std@0.144.0/testing/asserts.ts";
import { default as stripComments } from "https://esm.sh/strip-comments@2.0.1?no-check";
import { stripLiteral } from "https://esm.sh/strip-literal@0.4.0";

const code = `bla original`;

const expected = `the expected`;

Deno.test("strip-comments", () => {
  assertEquals(stripComments(code), expected);
});
Deno.test("strip-literal", () => {
  assertEquals(stripLiteral(code), expected);
});

Deno.bench("strip-comments", () => {
  stripComments(code.repeat(100));
});
Deno.bench("strip-literal", () => {
  stripLiteral(code.repeat(100));
});
```

Also, no matter if I'm in a `_test.ts` or `_bench.ts` file I get

```
Property 'bench' does not exist on type 'typeof Deno'.deno-ts(2339)
```
in VSCode even though the status bar at the bottom correctly show `Deno 1.23.0` and I've got `"deno.enable": true` in `.vscode/settings.json`

For reference I asked on [Discord](https://discord.com/channels/684898665143206084/769285344809451572/989354182991556671) first if this should be supported

**Comment by crowlKats** [comment] 2022-06-23 05:34
Duplicate of #14862

**Closed by crowlKats** 2022-06-23 05:34 UTC
