### ISSUE TITLE
npm express-ws library don't work 

### ISSUE THREAD

**Issue by peterwangfeng** [denoland/deno#21294] opened 2023-11-22 02:52 UTC
ws.send(data, {binary: true})
Uncaught Error: Invalid WebSocket frame: invalid UTF-8 sequence in /node modules/.deno/ws@5.2.3/node modules/ws/lib/receiver.js

**Comment by marvinhagemeister** [comment] 2024-09-02 08:24
Marking as resolved as I cannot reproduce the original issue either.

**Closed by marvinhagemeister** 2024-09-02 08:24 UTC
Labels: bug, needs info, ext/websocket, node compat, node API polyfill, node:http
