### ISSUE TITLE
Dynamic import require

### ISSUE THREAD

**Issue by Fenzland** [denoland/deno#2054] opened 2019-04-05 03:56 UTC
ESModules without dynamic import is incomplete.
We cannot do this:
```js
if( whenWeNeed() )
    import 'some_thing';
```
nor this:
```js
const need= whatWeNeed();
    import need;
```
Only dynamic import can make ESM as strong as CommonJS or AMD.

Maybe there are some security reasons. But local dynamic import should be retain.

**Comment by ry** [comment] 2019-04-05 04:02
Dynamic import is indeed not yet supported. I was surprised to see that we don't have an issue for this yet. Thanks for creating this - it's on my roadmap.

**Comment by hayd** [comment] 2019-04-07 20:42
#1789 is related (also on ry's roadmap!)

**Comment by ry** [comment] 2019-04-08 13:26
Oh thanks @hayd. Somehow that didn't come up when I was searching.


Closing. Duplicate of #1789.

**Closed by ry** 2019-04-08 13:26 UTC

**Comment by Fenzland** [comment] 2019-04-10 09:59
> Oh thanks @hayd. Somehow that didn't come up when I was searching.
> 
> Closing. Duplicate of #1789.

so did I
