### ISSUE TITLE
docker hub

### ISSUE THREAD

**Issue by SouzaRoxo** [denoland/deno#7207] opened 2020-08-26 18:18 UTC
I didn't find the Deno in the docker hub.
Is there an official container ?

**Comment by lucacasonato** [comment] 2020-08-26 18:19
Duplicate of https://github.com/denoland/deno/issues/3356. Use https://github.com/hayd/deno-docker. It is well maintained and very up to date.

**Closed by lucacasonato** 2020-08-26 18:19 UTC
