### ISSUE TITLE
`deno run` doesn't use import map to resolve script argument

### ISSUE THREAD

**Issue by niedzielski** [denoland/deno#15299] opened 2022-07-24 16:08 UTC
`deno run [OPTIONS] <SCRIPT_ARG>...` doesn't use import maps to resolve `<SCRIPT_ARG>`. For example, consider:

```
$ deno run https://deno.land/std@0.148.0/examples/welcome.ts
Welcome to Deno!
```

This could be rewritten to use an import map but that's unsupported:

```
$ cat > mods.json <<eof 
{
  "imports": {
    "std/": "https://deno.land/std@0.148.0/"
  }
}
eof

$ deno run --import-map=mods.json std/examples/welcome.ts
error: Module not found "file:///home/stephen/tmp/sdfoiunouiwsf/std/examples/welcome.ts".
```

Allowing `<SCRIPT_ARG>` to use the import map resolution like the rest of a Deno project is useful for users wishing to keep all their dependency versions in one file. For example, I have a repo with an import map pinned to a specific standard library version:

```jsonc
{
  "imports": {
    // many other imports
    "std/": "https://deno.land/std@0.148.0/"
  }
}
```

And a deno.json with tasks that try to duplicate that version but they often get out of sync and I lose that nice view into seeing all my dependencies in one place:

```json
{
  "tasks": {
    "dev:serve": "deno -q run --allow-read=. --allow-net https://deno.land/std@0.149.0/http/file_server.ts dist",
  }
}
```

I'd like it to be:

```json
{
  "tasks": {
    "dev:serve": "deno -q run --allow-read=. --allow-net std/http/file_server.ts dist",
  }
}
```

**Comment by nayeemrmn** [comment] 2022-07-24 22:50
Ref #14066

**Comment by kitsonk** [comment] 2022-07-24 23:07
Duplicate of #14066

**Closed by kitsonk** 2022-07-24 23:07 UTC
Labels: duplicate
