### ISSUE TITLE
error during the spin up the container (libstdc++.so.6)

### ISSUE THREAD

**Issue by macorifice** [denoland/deno#9892] opened 2021-03-25 11:23 UTC
Hi,
I'm trying to spin up the container with Deno, the build works fine but when I run the docker file I get this error:
```shell
➜ docker run -it deno-app
deno: error while loading shared libraries: libstdc++.so.6: cannot open shared object file: No such file or directory
```

Information: 
```shell
➜ deno --version
deno 1.8.2 (release, x86_64-apple-darwin)
v8 9.0.257.3
typescript 4.2.2
```

Dockerfile
```shell
FROM alpine

RUN apk update && apk add curl

RUN curl -fsSL https://deno.land/x/install/install.sh | sh && mv /root/.deno/bin/deno /bin/deno

ENTRYPOINT ["deno"]

CMD ["run", "--allow-net", "https://deno.land/std/examples/welcome.ts"]
```

**Comment by kitsonk** [comment] 2021-03-25 12:03
Duplicate of #9686 

Please search issues before opening new ones. Search term I used was `alpine` and the referenced issue came top.

**Closed by kitsonk** 2021-03-25 12:03 UTC

**Comment by magurotuna** [comment] 2021-03-25 12:04
You can use a docker image maintained by the community like [hayd/alpine-deno](https://hub.docker.com/r/hayd/alpine-deno/). This image works around the libstdc++ issue as seen [here](https://github.com/hayd/deno-docker/blob/master/alpine.dockerfile#L27).
