### ISSUE TITLE
404 https://deno.land/std@v1.0.0-rc2/http/server.ts

### ISSUE THREAD

**Issue by grant** [denoland/deno#5277] opened 2020-05-13 18:01 UTC
Yesterday, there was a file, `server.ts` that existed.
Today, it doesn't exist.

https://deno.land/std@v1.0.0-rc2/http/server.ts

Navigating to this URL makes it seem like there is a file `server.ts`

https://deno.land/std@v1.0.0-rc2/http/

It looks like all files are returning 404s.

What is wrong?

**Comment by jeanlescure** [comment] 2020-05-13 18:08
This seems to be a duplicate of #5267

**Comment by ry** [comment] 2020-05-13 18:30
std is not yet at 1.0. We were erroneously linking through earlier today (https://github.com/denoland/deno_website2/pull/381).
You can get the current version here: https://github.com/denoland/deno/blob/master/std/version.ts

**Closed by ry** 2020-05-13 18:30 UTC
