### ISSUE TITLE
LSP does not know about lockfile version 3

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#20964] opened 2023-10-24 15:06 UTC
![image](https://github.com/denoland/deno/assets/7829205/eeb81cdc-755b-468f-a86e-f21fc1ed4e2d)

**Comment by nayeemrmn** [comment] 2023-10-24 15:08
This was fixed by https://github.com/denoland/vscode_deno/pull/965, are you on vscode_deno 3.26.0?

**Comment by dsherret** [comment] 2023-10-24 18:35
I also can't reproduce.

**Closed** 2023-12-13 23:02 UTC
Labels: needs info, lsp
