### ISSUE TITLE
Deno 2.0.0-rc.4 panic when passing --allow-all

### ISSUE THREAD

**Issue by redabacha** [denoland/deno#25803] opened 2024-09-22 11:45 UTC
to reproduce, clone this repository https://github.com/redabacha/remix-deno-vite-template and run the following commands:
```
deno install
deno task build
deno task start
```

output with `RUST_BACKTRACE=1`:
```
❯ deno task start
Warning `"nodeModulesDir": true` is deprecated in Deno 2.0. Use `"nodeModulesDir": "auto"` instead
    at file:///Users/reda/Documents/Projects/remix-deno-vite-template/deno.jsonc
Task start deno serve -A --parallel ./server.production.ts
Warning `"nodeModulesDir": true` is deprecated in Deno 2.0. Use `"nodeModulesDir": "auto"` instead
    at file:///Users/reda/Documents/Projects/remix-deno-vite-template/deno.jsonc

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 2.0.0-rc.4
Args: ["/Users/reda/.deno/bin/deno", "serve", "-A", "--parallel", "./server.production.ts"]

thread 'main' panicked at cli/args/flags.rs:671:9:
assertion failed: value.is_none()
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: deno::args::flags::PermissionFlags::to_options::handle_allow
   4: deno::args::CliOptions::permissions_options
   5: deno::factory::CliFactory::create_permissions_container
   6: deno::spawn_subcommand::{{closure}}
   7: <deno_unsync::tokio::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   8: tokio::runtime::task::raw::poll
   9: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

**Comment by HasanAlrimawi** [comment] 2024-09-22 12:29
I can't reproduce it:
![image](https://github.com/user-attachments/assets/6767efc7-5bb8-4313-8775-f1c479216193)

Could you give some insights if there's something different or I did wrong,,, I followed your description

**Comment by bartlomieju** [comment] 2024-09-22 13:02
This was already fixed in https://github.com/denoland/deno/pull/25743, please upgrade to canary version to have it working (`deno upgrade --canary`).

**Closed by bartlomieju** 2024-09-22 13:02 UTC
