### ISSUE TITLE
an error occurred trying to connect: invalid certificate: UnknownIssuer

### ISSUE THREAD

**Issue by potham** [denoland/deno#2301] opened 2019-05-07 04:30 UTC
Hi,

Just installed deno and try to run welcome.ts file which is mentioned in docs, i am facing this issue. Details are below.

```
D:\deno>deno run https://deno.land/welcome.ts
Downloading https://deno.land/welcome.ts
WARN RS - Sending fatal alert BadCertificate
an error occurred trying to connect: invalid certificate: UnknownIssuer
an error occurred trying to connect: invalid certificate: UnknownIssuer
```
```
D:\deno>deno version
deno: 0.4.0
v8: 7.6.53
typescript: 3.4.1
```

Anybody faced this issue.

**Comment by bartlomieju** [comment] 2019-05-07 08:36
Just tried and works fine, do you use any proxy server?

**Comment by potham** [comment] 2019-05-07 09:29
> Just tried and works fine, do you use any proxy server?

yes @bartlomieju. Thanks for reminding. By disabling proxy now i have successfully executed . But now while importing http module i am facing other error.

```
D:deno>deno run first-server.ts
Compiling file:///D:/OLAM-Projects/deno/hello.ts
Downloading https://deno.land/std/http/server.ts
error TS5009: Cannot find the common subdirectory path for the input files. 
```
**first-server.ts**
```
import { serve } from "https://deno.land/std/http/server.ts";
console.log("Hello World");
console.log(5+5);
```

**Comment by bartlomieju** [comment] 2019-05-07 09:49
Related issue: #1383

**Comment by saibing** [comment] 2019-09-26 13:02
I ran into the same problem, but I really need a proxy

```ts
deno https://deno.land/welcome.ts
Download https://deno.land/welcome.ts
WARN RS - rustls::session:815 - Sending fatal alert BadCertificate
https://deno.land/welcome.ts: error trying to connect: invalid certificate: UnknownIssuer
```

**Comment by bartlomieju** [comment] 2019-09-26 13:19
@saibing if you need a proxy you can use `HTTP_PROXY` or `HTTPS_PROXY` env variables. https://deno.land/manual.html#proxies

**Comment by saibing** [comment] 2019-09-27 00:45
@bartlomieju 

I have set these environment variables

**Comment by tdillon** [comment] 2019-11-07 18:16
I'm in a corporate environment with transparent proxies and self signed certificates.  Some way of adding a trusted cert or ignoring invalid certs would be helpful.

```bash
$ deno -v
deno: 0.23.0
v8: 7.9.317.12
typescript: 3.6.3

$ deno https://deno.land/std/examples/welcome.ts
Download https://deno.land/std/examples/welcome.ts
WARN RS - rustls::session:815 - Sending fatal alert BadCertificate
https://deno.land/std/examples/welcome.ts: error trying to connect: invalid certificate: UnknownIssuer
```

**Comment by asyncmax** [comment] 2019-12-04 16:44
I'm trying to use Deno to write a Kubernetes API client. Almost all Kubernetes servers use a self-signed ca setup, so this feature is crucial. Is this coming anytime soon?

**Comment by bartlomieju** [comment] 2019-12-04 17:03
> I'm trying to use Deno to write a Kubernetes API client. Almost all Kubernetes servers use a self-signed ca setup, so this feature is crucial. Is this coming anytime soon?

I think this should be straight-forward to add `--cert` flag to load additional certificate to HTTP client. I can take a look at that

**Comment by asyncmax** [comment] 2019-12-04 17:33
Thanks for your quick response.

Because certificate requirements vary per API server and a single client should be able to connect to multiple servers at once, I believe we should provide it as a per-session option. Perhaps, we need a concept of configurable "connection pool" behind `fetch`, similar to Http Agent in Node?

Moreover, Kubernetes API Client must be able to parse `~/.kube/config` first to get the ca bundle for connection, so a CLI flag will make it impossible to implement this in a single-shot.

**Comment by bartlomieju** [comment] 2019-12-04 17:45
> Thanks for your quick response.
> 
> Because certificate requirements vary per API server and a single client should be able to connect to multiple servers at once, I believe we should provide it as a per-session option. Perhaps, we need a concept of configurable "connection pool" behind `fetch`, similar to Http Agent in Node?
> 
> Moreover, Kubernetes API Client must be able to parse `~/.kube/config` first to get the ca bundle for connection, so a CLI flag will make it impossible to implement this in a single-shot.

@asyncmax it looks like your use case is yet another beast. 

Example provided by @tdillon that needs single certificate for transparent proxy is simple, but providing certificates for `fetch` will be significantly harder. Is there any spec for using custom certificate in `fetch`?

**Comment by asyncmax** [comment] 2019-12-04 18:03
@bartlomieju As far as I know, there is no such spec in `fetch`. Actually, `fetch` may not be an appropriate entity to have that option That's why I am thinking we might need to introduce another configurable layer behind `fetch`. It can be also used for managing other features such as keep-alive.

BTW, is the TLS connection through `fetch` reused or re-established every time?

**Comment by bartlomieju** [comment] 2019-12-04 18:35
> @bartlomieju As far as I know, there is no such spec in `fetch`. Actually, `fetch` may not be an appropriate entity to have that option That's why I am thinking we might need to introduce another configurable layer behind `fetch`. It can be also used for managing other features such as keep-alive.

I guess this might be the place for a library in userland.

> BTW, is the TLS connection through `fetch` reused or re-established every time?

Right now our HTTP client is one-off, there's an issue for that #3068 as well as PR #3099. It's waiting for upgrade to Tokio 0.2. Once we upgrade HTTP client will have connection pool and reuse connections.

**Comment by asyncmax** [comment] 2019-12-04 19:27
> I guess this might be the place for a library in userland.
Yes, I agree. Maybe keep-alive is a bad example.
> Right now our HTTP client is one-off, there's an issue for that #3068 as well as PR #3099. It's waiting for upgrade to Tokio 0.2. Once we upgrade HTTP client will have connection pool and reuse connections.
Sounds good. I guess what I want is a new Deno API that allows userland code to configure TLS parameters of the HTTP client.

**Comment by bartlomieju** [comment] 2019-12-05 14:07
@asyncmax would you mind opening a new issue describing all of your needs there? After some thinking I came to a conclusion that we could expose JS API for creating Rust HTTP client with very little cost (it'd be a resource) so one could leverage some capabilities of `reqwest`.

**Comment by asyncmax** [comment] 2019-12-05 16:29
@bartlomieju No problem. I will gladly do that soon.

**Comment by bartlomieju** [comment] 2019-12-08 13:18
> > I'm trying to use Deno to write a Kubernetes API client. Almost all Kubernetes servers use a self-signed ca setup, so this feature is crucial. Is this coming anytime soon?
> 
> I think this should be straight-forward to add `--cert` flag to load additional certificate to HTTP client. I can take a look at that

Actually I won't be able to work on that due to more priority work on core. If anyone wants to work on this I can provide some tips.

**Comment by tdillon** [comment] 2020-02-03 19:39
Related/Duplicate of #1371?

**Comment by geoFlux** [comment] 2020-02-04 18:40
@bartlomieju I would like to try to fix this if you could give me those tips.
Although, for my purposes, I was able to change `create_http_client` in [http_util.rs](https://github.com/denoland/deno/blob/master/cli/http_util.rs) to `.use_native_tls()` instead of `.use_rustls_tls()` and the certificate errors went away for me.

I looked into it, and found that will use the native system on windows and osx, but openssl on linux, and I guess it's been decided to not use openssl for security reasons. I could make it conditionally compile in native_tls for windows and mac, but use rustls_tls on linux. Imho that would be really nice if it just worked out of the box on mac and windows. 

I could do that and make a `--certs` flag, or I could make a `--http_use_native_tls` flag. Or I could just start with the `--certs` flag and leave the `use_native_tls` functionality for another day.

**Comment by geoFlux** [comment] 2020-02-04 18:47
@bartlomieju I would like to try to fix this if you could give me those tips. Although, for my purposes, I was able to change create_http_client in http_util.rs to .use_native_tls() instead of .use_rustls_tls() and the certificate errors went away for me.
I looked into it, and found that will use the native system on windows and osx, but openssl on linux, and I guess it's been decided to not use openssl for security reasons. I could make it conditionally compile in native_tls for windows and mac, but use rustls_tls on linux. Imho that would be really nice if it just worked out of the box on mac and windows.

**Comment by bartlomieju** [comment] 2020-02-05 09:00
> @bartlomieju I would like to try to fix this if you could give me those tips. Although, for my purposes, I was able to change `create_http_client` in [http_util.rs](https://github.com/denoland/deno/blob/master/cli/http_util.rs) to `.use_native_tls()` instead of `.use_rustls_tls()` and the certificate errors went away for me.

So `--cert` flag should take a filepath to certificate file. In `cli/file_fetcher.rs` there's a call to `create_http_client()` - you need to pass value of the `cert` flag to that function and load appropriate certificate.

> Looks like that will use the native system on windows and osx, but openssl on linux, and I guess it's been decided to not use openssl for security reasons. I could make it conditionally compile in native_tls for windows and mac, but use rustls_tls on linux. Imho that would be really nice if it just worked out of the box on mac and windows.

CC @ry

**Comment by dplewis** [comment] 2020-02-06 21:09
```
WARN RS - rustls::session:815 - Sending fatal alert BadCertificate
```
@geoFlux You fixed my issue. I received this error on a Mac on a corporate network while running this test suite.

**Comment by tdillon** [comment] 2020-05-07 11:12
The `--cert` flag has fixed my issue (i.e., corporate environment with transparent proxies and self signed certificates).

```powershell
> deno --version
deno 1.0.0-rc1
v8 8.2.308
typescript 3.8.3
```

```powershell
> deno run --cert corporate.pem https://deno.land/std/examples/welcome.ts
Download https://deno.land/std/examples/welcome.ts
Compile https://deno.land/std/examples/welcome.ts
Welcome to Deno 🦕
```

**Comment by devanandp** [comment] 2020-05-29 20:46
Iam trying to Connect Heroku Postgres but getting the same issue in title. Can anyone help?

ARN RS - rustls::session:718 - Sending fatal alert BadCertificate
error: Uncaught InvalidData: invalid certificate: UnknownIssuer
    at unwrapResponse ($deno$/ops/dispatch_json.ts:43:11)
    at Object.sendAsync ($deno$/ops/dispatch_json.ts:98:10)
    at async Object.startTls ($deno$/tls.ts:70:15)
    at async startTlsPostgres (https://deno.land/x/pgc4d/src/connection.ts:305:20)
    at async connectPg (https://deno.land/x/pgc4d/src/connection.ts:81:24)
    at async file:///Users/devanand/Documents/Projects/Deno/deno-experiments/models/database.ts:66:12

**Comment by youryss** [comment] 2020-06-14 20:17
I'm having the same issue on my work computer 

deno version

```
deno 1.1.0
v8 8.4.300
typescript 3.9.2
```

```
Download https://deno.land/std/http/server.ts
WARN RS - rustls::session:718 - Sending fatal alert BadCertificate
error: error sending request for url (https://deno.land/std/http/server.ts): error trying to connect: invalid certificate: UnknownIssuer
```

any ideas?

**Comment by ChristianSiegert** [comment] 2020-07-17 15:55
From my home network (no proxy, no VPN), sending a request to a public website, I have the problem too:

```
WARN RS - rustls::session:718 - Sending fatal alert BadCertificate
Http: error sending request for url (https://www.0815.eu/): error trying to connect: invalid certificate: UnknownIssuer
```

```
$ deno --version
deno 1.2.0
v8 8.5.216
typescript 3.9.2
```

Is there a plan to rectify this? It’s been over a year since the issue was opened.

**Comment by lucacasonato** [comment] 2020-08-13 10:28
It looks like the use case for corporate certificates can be resolved via `--cert`, and the k8s use case should be resolved by https://github.com/denoland/deno/pull/6918. The issue (#1383) @potham ran into on windows is also resolved. If you have any issues outside of these use cases please open a new issue.

**Closed by lucacasonato** 2020-08-13 10:28 UTC

**Comment by firmanjabar** [comment] 2021-04-25 01:41
![](https://media.discordapp.net/attachments/768920745618833478/835688501966143548/unknown.png)

anyone know how to fix this problem?
i'm trying to connect to Heroku Postgres.

i don't know how to make corporate.pem? soo i can use `--cert corporate.pem`. How to make `doc.pem` or where do i download?

**Comment by borsemayur2** [comment] 2021-05-03 03:03
@firmanjabar I'm getting  following error:

```
Sending fatal alert BadCertificate
8:23:57 AM web.1 |  error: 
8:23:57 AM web.1 |  Uncaught (in promise) InvalidData: invalid certificate: UnknownIssuer
8:23:57 AM web.1 |            this.#conn = await Deno.startTls(this.#conn, { hostname });
```

**Comment by al6x** [comment] 2021-05-31 09:13
Same error, can't connect to PostgreSQL on Linode VPS, works fine locally.

**Comment by TheAifam5** [comment] 2022-02-12 00:18
Same on my side, will take a look into it.

**Comment by rinsuki** [comment] 2022-06-16 08:22
for corporate/mitm certs, you can also consider `DENO_TLS_CA_STORE=mozilla,system` (or just `...=system`) option.

**Comment by k-paxian** [comment] 2024-10-07 11:21
Thank you @rinsuki that hint saved me hours of time ❤️

**Comment by dgmerinos** [comment] 2024-12-09 15:42
> for corporate/mitm certs, you can also consider `DENO_TLS_CA_STORE=mozilla,system` (or just `...=system`) option.

Windows 11 in corporate computer, this works.
