### ISSUE TITLE
[lsp] Typing `/` inside of a specifier with active completions results in completion being accepted

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#15353] opened 2022-07-30 14:02 UTC
Enter `import ""` into your editor. Place the cursor after the first `"`. Now enter `../`. The import now probably contains `../deps.ts/` or a reference to some other JS file in the parent directory of the file you were trying.

(I'd add a screen capture, but I can't get my screen recording to work anymore).

This effectively means you can not manually type out specifiers unless you press `Esc` between every key stroke. Highly frustrating.

**Comment by kidonng** [comment] 2022-07-30 16:35
Not sure if this is what being described:

https://user-images.githubusercontent.com/44045911/181930368-246e904b-873a-4b2c-a828-7fb3418e1136.mov

**Comment by kitsonk** [comment] 2022-07-30 21:38
Duplicate of #15252

**Closed by kitsonk** 2022-07-30 21:38 UTC
Labels: bug, duplicate, lsp
