### ISSUE TITLE
Using typescript decorators is broken

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#5715] opened 2020-05-21 14:59 UTC
```shell
$ deno cache https://gist.githubusercontent.com/lucacasonato/e7d549c5c2d92ed4c10170f0a758b952/raw/a5fc2b7cc8b1952e1718103b496cc9254e2a9ada/decorator.ts --config https://gist.githubusercontent.com/lucacasonato/e7d549c5c2d92ed4c10170f0a758b952/raw/a5fc2b7cc8b1952e1718103b496cc9254e2a9ada/tsconfig.json
error:
```
It just errors with `error:`. Kinda surprising there is no test for this. I'm on a release build from f98cc34.

**Comment by hayd** [comment] 2020-05-21 16:56
Also confusing that this broke between 1.0.0 and 1.0.1. (Presumably because there is no test :) )

**Comment by lucacasonato** [comment] 2020-05-22 10:07
Ref #5739

**Comment by bartlomieju** [comment] 2020-05-22 11:03
Closing in favor of #5739 because there's a reproduction code there.

**Comment by lucacasonato** [comment] 2020-05-22 11:04
Sure, but there was reproduction here too in the form of a gist.

**Closed by bartlomieju** 2020-05-22 11:03 UTC

**Comment by bartlomieju** [comment] 2020-05-22 11:06
Oooops, right @lucacasonato; I meant to continue in https://github.com/denoland/deno/issues/5736
