### ISSUE TITLE
Awaiting stderr results in script hanging, sometimes

### ISSUE THREAD

**Issue by HarryPeach** [denoland/deno#5621] opened 2020-05-19 10:33 UTC
Hi, I'm writing a library for a terminal spinner, and sometimes the script will hang after writing.
I think I've narrowed it down to the ```Deno.write``` calls, as there seems to be some async issues going on.

The solution to a similar issue in #5515 was to await all write calls, which is what I've done but the error still persists.

The following code:

```js
const kia = new Kia("test");
await kia.start();
await sleep(3000);
await kia.stop();

console.log("All done");
```

Results in this output and hang:
![image](https://user-images.githubusercontent.com/4750998/82316000-16009c80-99c4-11ea-93c4-a5018c536ea8.png)

All the calls to ```Deno.write``` look like this:
```js
export async function writeLine(
	rid: number,
	encoder: TextEncoder,
	text: string,
	indent?: number
) {
	await Deno.write(
		rid,
		encoder.encode(`\r${indent ? ESC + indent + "C" : ""}${text}`)
	);
}
```

And all calls are awaited

```js
await writeLine(
			this.options.resource,
			this.textEncoder,
			`${flair} ${text}`,
			this.options.indent
		);
```
(the full code is at my Kia repo if you need more context)

**Comment by cknight** [comment] 2020-05-19 11:19
Can you post a link to your repo? There's not enough context here to help you effectively.

**Comment by HarryPeach** [comment] 2020-05-19 12:14
https://github.com/HarryPeach/kia/tree/dev

**Comment by bartlomieju** [comment] 2020-05-21 11:25
Most likely same problem as in #4789

**Comment by HarryPeach** [comment] 2020-05-21 21:24
I've tested and this issue still appears on deno version prior to 0.41.0, so it may not be the same issue

**Comment by bartlomieju** [comment] 2020-05-21 21:29
@HarryPeach have you taken into account that `Deno.write()` might write less bytes than the buffer you give? Can you try replacing `Deno.write()` calls with `Deno.writeAll()` to see if that helps?

**Comment by HarryPeach** [comment] 2020-05-21 21:45
Replacing all instances of ```Deno.write()``` with ```Deno.writeAll()``` doesn't seem to fix it

**Comment by bnoordhuis** [comment] 2020-11-30 22:57
@HarryPeach Do you have a small standalone test case I can try locally? I want to track this down but I need something minimal.

**Comment by crowlKats** [comment] 2023-01-09 01:19
I have run the provided example and I cannot reproduce this, and since there has not been a reply from author since nearly 3 years to provide further information, i will close this as fixed.

**Closed by crowlKats** 2023-01-09 01:19 UTC
Labels: bug, cli
