### ISSUE TITLE
`using` keyword generate various errors

### ISSUE THREAD

**Issue by JOTSR** [denoland/deno#22392] opened 2024-02-12 15:31 UTC
Version: Deno 1.40.4

# Summary

Declarations of an instance of a local Disposable class generate the following errors:
- LSP is broken (code completions does not work anymore)
- Runtime throws error when calling `Symbol.dispose`/`Symbol.asyncDispose`

Calling `Symbol.dispose` result in error if there is more than one scope with `using` or when there is `using` in global scope with local `class`.

# Examples

## With `Symbol.dispose`

```ts
export class Disposable {
    [Symbol.dispose]() {
        console.log('dispose')
    }

}

using _f = await Deno.open('./demo.txt')

console.log('ok')
```

```sh
$ deno run --allow-read=. ./src/example.ts
ok
```

## With `Symbol.dispose` and global using

```ts
export class Disposable {
    [Symbol.dispose]() {
        console.log('dispose')
    }

}

using _disposable = new Disposable()

console.log('ok')
```

```sh
$ deno run --allow-read=. ./src/example.ts
error: Uncaught (in promise) TypeError: Property [Symbol.dispose] is not a function.
Warning Couldn't format source line: Line 52 is out of bounds (source may have changed at runtime)
    at _using (file:///.../src/example.ts:52:11)
    at file:///.../src/example.ts:9:1
```

## With `Symbol.dispose` and scoped `using`

```ts
export class Disposable {
    [Symbol.dispose]() {
        console.log('dispose')
    }

}

{
    using _disposable = new Disposable()
}

console.log('ok')
```

```sh
$ deno run --allow-read=. ./src/example.ts
dispose
ok
```

## With `Symbol.dispose` scoped `using` and Deno `using`

```ts
export class Disposable {
    [Symbol.dispose]() {
        console.log('dispose')
    }

}

using _f = await Deno.open('./demo.txt')

{
    using _disposable = new Disposable()
}

console.log('ok')
```

```sh
$ deno run --allow-read=. ./src/example.ts
error: Uncaught (in promise) TypeError: Property [Symbol.dispose] is not a function.
Warning Couldn't format source line: Line 52 is out of bounds (source may have changed at runtime)
    at _using (file:///.../src/example.ts:52:11)
    at file:///.../src/example.ts:11:5
    at eventLoopTick (ext:core/01_core.js:65:7)
```

## With `Symbol.dispose` scoped `using` and scoped Deno `using`

```ts
export class Disposable {
    [Symbol.dispose]() {
        console.log('dispose')
    }

}

{
    using _f = await Deno.open('./demo.txt')
    using _disposable = new Disposable()
}

console.log('ok')
```

```sh
$ deno run --allow-read=. ./src/example.ts
dispose
ok
```

## With `Symbol.AsyncDispose` scoped `using` and scoped Deno `using`

```ts
export class Disposable {
    [Symbol.asyncDispose]() {
        console.log('dispose')
    }

}

{
    using _f = await Deno.open('./demo.txt')
    await using _asyncDisposable = new AsyncDisposable()
}

console.log('ok')
```

```sh
$ deno run --allow-read=. ./src/example.ts
dispose
ok
```

## With `Symbol.AsyncDispose` scoped `using` and Deno `using`

```ts
export class Disposable {
    [Symbol.asyncDispose]() {
        console.log('dispose')
    }

}

using _f = await Deno.open('./demo.txt')

{
    await using _asyncDisposable = new AsyncDisposable()
}

console.log('ok')
```

```sh
$ deno run --allow-read=. ./src/example.ts
dispose
ok
```

## With `Symbol.AsyncDispose` scoped `using` and scoped Deno `using`

```ts
export class Disposable {
    async [Symbol.asyncDispose]() {
        console.log('dispose')
    }

}

{
    using _f = await Deno.open('./demo.txt')
    await using _asyncDisposable = new AsyncDisposable()
}

console.log('ok')
```

```sh
$ deno run --allow-read=. ./src/example.ts
dispose
ok
```

## With `Symbol.AsyncDispose` scoped `using` and Deno `using`

```ts
export class Disposable {
    async [Symbol.asyncDispose]() {
        console.log('dispose')
    }

}

using _f = await Deno.open('./demo.txt')

{
    await using _asyncDisposable = new AsyncDisposable()
}

console.log('ok')
```

```sh
$ deno run --allow-read=. ./src/example.ts
error: Uncaught (in promise) TypeError: Property [Symbol.dispose] is not a function.
Warning Couldn't format source line: Line 52 is out of bounds (source may have changed at runtime)
    at _using (file:///.../src/example.ts:52:11)
    at file:///.../src/example.ts:11:5
    at eventLoopTick (ext:core/01_core.js:65:7)
```

**Comment by dsherret** [comment] 2024-02-12 17:53
This is a regression. I opened https://github.com/swc-project/swc/issues/8629

**Comment by bombillazo** [comment] 2024-02-22 06:02
Hey, I tried using `using` as well recently but we get a `TypeError: Property [Symbol.dispose] is not a function.` error, we are only defining `asyncDispose` since it is a connection closing function.

**Comment by BlowaterNostr** [comment] 2024-06-01 15:03
Same problem here. It works on Mac but failed in Linux (GitHub Action)
```
deno 1.44.0 (release, x86_64-unknown-linux-gnu)
v[8](https://github.com/BlowaterNostr/nostr.ts/actions/runs/9331134263/job/25685473421#step:5:9) 12.6.228.3
typescript 5.4.5
```

**Comment by lucacasonato** [comment] 2024-06-13 12:57
All of these examples are working for me in Deno 1.44.1.

@BlowaterNostr please share what issue you are running into if it is not fixed.

**Closed by lucacasonato** 2024-06-13 12:57 UTC
Labels: bug, swc
