### ISSUE TITLE
It should be possible to handle SIGINT that is raised inside a looped prompt

### ISSUE THREAD

**Issue by finleyjb** [denoland/deno#27465] opened 2024-12-24 14:47 UTC
Version: Deno 2.0.0

Given the following code:

```
// Example 1
Deno.addSignalListener("SIGINT", () => {
  console.log("interrupted!"); // Never prints
  Deno.exit();
});

while (true) {
  const val = prompt('Prompt: '); // Hit Ctrl-c while in this prompt
  console.log(val); // logs null
}
```

As it stands right now, this program will log a null and the `SIGINT` handler will never run. However, if I remove the loop and run this the `SIGINT` handler runs (adapted from the [deno docs](https://docs.deno.com/examples/os_signals_tutorial/#set-up-an-os-signal-listener)):

```
// Example 2
let sigint = false;
Deno.addSignalListener("SIGINT", () => {
  console.log("interrupted!");
  sigint = true;
});

const val = prompt("Prompt: ");
console.log(val); // prints null

// Add a timeout to prevent process exiting immediately.
setTimeout(() => {}, 5000); // prints "interrupted!"
```

The only workaround I've found is that you can yield control using a `setTimeout` in a promise:

```
// Example 3
Deno.addSignalListener("SIGINT", () => {
  console.log("interrupted!");
  Deno.exit(1);
});

while (true) {
  const val = prompt("Prompt: ");
  const printHandlerPromise = new Promise((resolve, reject) => {
    console.log(val);
    setTimeout(() => {
      resolve(null);
    }, 0);
  });
  await printHandlerPromise;
}
```

It seems like Example 1 should do something other than silently swallow the `SIGINT` function call. Perhaps the handler should run after the user inputs text at the next prompt?

**Comment by sigmaSd** [comment] 2024-12-24 21:35
You can use node  readline
```ts
import * as readline from "node:readline/promises";
import process from "node:process";

const rl = readline.createInterface({
  input: process.stdin,
  output: process.stdout,
});
rl.addListener("SIGINT", () => {
  console.log("interrupted!"); // Never prints
  Deno.exit();
});

while (true) {
  const val = await rl.question("Prompt: "); // Hit Ctrl-c while in this prompt
  console.log(val); // logs null
}
```

prompt api is problematic in deno, its synchronous and it blocks all async tasks in deno, i imagine its not the case in browsers implementation

**Comment by kt3k** [comment] 2024-12-25 07:15
> It seems like Example 1 should do something other than silently swallow the SIGINT function call.

It doesn't seem swallowed to me. If you break the loop, then the SIGINT handler works. The example runs the loop synchronously forever. There's no room for the handler to run.

> Perhaps the handler should run after the user inputs text at the next prompt?

That is not possible by the single threaded nature of javascript.

**Comment by dsherret** [comment] 2024-12-28 17:55
As @kt3k pointed out, JavaScript is single threaded, so if you block the event loop by calling `prompt` then the other JavaScript code will never run.

Also, this is essentially a duplicate of https://github.com/denoland/deno/issues/26919

**Closed by dsherret** 2024-12-28 17:55 UTC
Labels: invalid
