### ISSUE TITLE
"let" is required do define variables

### ISSUE THREAD

**Issue by CreaZyp154** [denoland/deno#13803] opened 2022-03-01 13:43 UTC
A JavaScript code like this one:
```javascript
test = 1
```

Throws an  `Uncaught ReferenceError` even though it's a valid (I'll admit not best practice) JavaScript code.

It should define `test` to `1`.

**Comment by kyuzu** [comment] 2022-03-01 13:51
It's not valid code in [strict mode](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Strict_mode) and strict mode is enabled by default when you use ES modules (which Deno uses by default).

**Comment by lucacasonato** [comment] 2022-03-01 13:52
@kyuzu's explanation is correct. Closing as this is working as intended.

**Closed by lucacasonato** 2022-03-01 13:52 UTC

**Comment by andreubotella** [comment] 2022-03-01 13:53
A minor clarification: strict mode is _always_ enabled with ES modules, there's no way to turn it off.
