### ISSUE TITLE
lsp: excluding a file from linting does not clear diagnostics

### ISSUE THREAD

**Issue by igorsaux** [denoland/deno#12877] opened 2021-11-23 19:30 UTC
Reproduction:
 - Create and open a file that contains any warnings or errors from deno, let's it be `a.ts`, for example.
 - Add the file to the exclude list in `deno.json`:
 ```json
"lint": {
    "files": {
      "exclude": ["a.ts"]
    }
  }
 ```

Config re-applies but diagnostics from `a.ts` do not disappear.
If we edit `deno.json` before opening the file - it works as should.

**Comment by kitsonk** [comment] 2021-11-23 21:26
Duplicate of #12871

**Comment by igorsaux** [comment] 2021-11-23 21:36
@kitsonk hm, sorry, I think You misunderstood, It's not a duplicate. This issue is not about the config file, It's about the thing that LSP does not clear diagnostics for ignored files.

**Comment by kitsonk** [comment] 2021-11-23 21:39
Ah, yes, sorry.

@dsherret this is what I was talking about in the other PR. We need to find a way to issue an empty diagnostic array to the client when we stop linting or enabling a file.

**Comment by dsherret** [comment] 2021-11-23 21:41
@kitsonk I think this original issue is now resolved. This other issue that it was renamed to is probably fixed here https://github.com/denoland/deno/pull/12876/files#diff-3f3a0ef604619f4a1dbd591a0749978218fdddc2341646fd05bcd3b372a7a851R321-R326

**Comment by igorsaux** [comment] 2021-11-23 21:42
> Ah, yes, sorry.
> 
> @dsherret this is what I was talking about in the other PR. We need to find a way to issue an empty diagnostic array to the client when we stop linting or enabling a file.

What if do `collection.map.clear()` in `DiagnosticsServer::invalidate_all`? That fixes my issue, but I don't sure It's a correct solution.

**Comment by kitsonk** [comment] 2021-11-23 21:49
@dsherret and I chatted offline, we suspect #12876 when merged will resolve the issue.

**Closed** 2021-11-24 20:14 UTC
Labels: bug, lsp
