### ISSUE TITLE
import in repl causes a crash

### ISSUE THREAD

**Issue by Gozala** [denoland/deno#2706] opened 2019-07-31 20:29 UTC
```sh
echo "export const hi = () => 'hi'" > mod.js
deno
> import('./mod.js')
thread 'tokio-runtime-worker-0' panicked at 'dyn_import callback not set', ../../core/isolate.rs:262:7
note: Run with `RUST_BACKTRACE=1` environment variable to display a backtrace.
fatal runtime error: failed to initiate panic, error 5
[1]    20373 abort      deno
```

**Comment by ry** [comment] 2019-07-31 20:31
duplicate of https://github.com/denoland/deno/issues/1789

**Closed by ry** 2019-07-31 20:31 UTC
