### ISSUE TITLE
`deno repl` hangs without network access

### ISSUE THREAD

**Issue by mhio** [denoland/deno#16426] opened 2022-10-26 01:56 UTC
Running the repl in 1.25.4 and 1.26.2 in a debian:11 container hangs when there's no network access. 

There are connection attempts to deno.land / tcp / 443, that seem to do a retry backoff which takes a couple of minutes

```
$ date; docker run -ti me/deno /deno repl --eval 'console.log(new Date())'
Wed 26 Oct 2022 01:45:56 UTC

2022-10-26T01:48:07.230Z
Deno 1.25.4
exit using ctrl+d or close()
> 
```

I think it might be related to the connections being dropped rather than getting an ICMP response. 

The `--no-remote` options don't seem to affect whatever is loading.

Could the remote lookups be disabled optionally? Is there a way to pre cache the remote lookup?

**Comment by mhio** [comment] 2022-10-26 01:56
Is it the completions that are trying to load?

https://github.com/denoland/deno/blob/4d166e638f387db45d9ae1fe967db6a18ff7cc03/cli/lsp/repl.rs#L302-L306

**Comment by bartlomieju** [comment] 2022-11-25 02:03
@dsherret should we add a timeout here and continue if completion setting can't be obtained?

**Comment by crowlKats** [comment] 2024-10-15 20:45
I cannot reproduce this anymore; @mhio is this still happening?

**Comment by lucacasonato** [comment] 2024-10-22 09:49
Closing because the OP did not respond again.

**Closed by lucacasonato** 2024-10-22 09:49 UTC
Labels: bug, repl
