### ISSUE TITLE
Object.entries does not exist on type ObjectConstructor

### ISSUE THREAD

**Issue by blazmrak** [denoland/deno#16636] opened 2022-11-14 20:49 UTC
Hi, I'm using IntelliJ with deno, and it seems like deno plugin/LSP does not like `Object.entries()`, because it says that I have to change the lib compiler property to es2017 or later. This has been present on 1.27 and now on 1.28.

Compiler options in deno.json are empty and I have also tried setting the module and target to esnext/es2022/es2017 but the error remains the same.

**Comment by Seally** [comment] 2022-11-14 22:21
Have you checked with the relevant JetBrains team? `Object.entries()` is defined out of the box when I'm using VS Code, so I'm thinking it may be an issue with their plugin instead. 

Maybe they have a bad default somewhere or something, or somehow you have the standard TypeScript LSP enabled alongside/instead of Deno LSP. On VS Code the error message clearly tells me where an error originates from (should be `deno-ts`) and if I see something different I can usually tell something went wrong (usually the standard TS server running when it shouldn't). I forget if IntelliJ/Webstorm does the same.

I do not think modifying `deno.json` will do anything, since Deno treats the compiler options there differently from how TS server does it: https://deno.land/manual@v1.28.0/advanced/typescript/configuration#configuring-typescript-in-deno

**Comment by blazmrak** [comment] 2022-11-15 00:19
No, not yet, I thought its a problem with LSP, since I was guessing they just reuse it. I'm not sure where it originates from, but I'm guessing deno, since the message starts with `Deno: ...`. I'll ping the Jetbrains side as well. Something might have gone to shit after I updated to 1.28, because I don't remember the LSP not knowing about Array.find :D Maybe an update is coming for the plugin in the upcoming days :) thanks for the reply!

**Comment by dsherret** [comment] 2022-11-17 00:09
It works for me with the deno lsp and the types should be distributed with Deno. Sounds like an IntelliJ issue. I think @crowlKats uses IntelliJ... Leo, have you noticed this not work?

**Comment by crowlKats** [comment] 2022-11-17 09:53
Hm, it works fine for me, unsure whats happening. the only thing is that i dont get good intellisense for `Object.entries`, but nothing close to it not liking the function

**Comment by blazmrakgid** [comment] 2022-11-17 10:51
@crowlKats What do you mean by "not good intellisense for Object.entries"? For me the problem is that `Object` is the es5 version, so it is missing the .entries and .values... The .find resolved itself by changing the target to esnext, which makes sense...

**Comment by crowlKats** [comment] 2022-11-17 11:04
> I'm guessing that not good intellisense for Object.entries means that you cannot navigate to the .entries implementation (cannot find declaration to go to) which makes sense, because it is looking at es5, but what doesn't make sense is that it resolves the correct type😄

yea exactly; and no argument names, nor any documentation (which usually is the case for other built-ins)

**Comment by crowlKats** [comment] 2022-11-17 11:05
> EDIT: I have no idea wtf is going on, but by setting esnext everywhere, restarting lsp a bunch, closing the tabs and opening them again... It works??? When I open Object implementation, everything turns red, because it navigates to es5, but when I close that tab, everything works.

that is very weird. The JetBrains plugin has been problematic for quite a while, and a lot of times its weird stuff like this

**Comment by lucacasonato** [comment] 2022-11-24 22:56
Seems like a bug that should be reported to JetBrains because it works with VS Code + the Deno LSP. Can we open an upstream issue and close this one?

**Comment by blazmrakgid** [comment] 2022-11-25 07:34
Yeah, this issue can be closed.

**Closed** 2023-01-27 21:05 UTC
Labels: needs info
