### ISSUE TITLE
certificate issue

### ISSUE THREAD

**Issue by neuwirthe** [denoland/deno#23485] opened 2024-04-21 14:23 UTC
Im am trying to run the command 
`quarto install extension juliantao/qletter`
and this is what I get

```
Version: Deno x.x.x
Platform: macos aarch64
Version: 1.37.2
Args: ["/Applications/quarto/bin/tools/aarch64/deno", "run", "--unstable", "--no-config", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--no-check", "--importmap=/Applications/quarto/bin/vendor/import_map.json", "/Applications/quarto/bin/quarto.js", "install", "extension", "juliantao/qletter"]

thread 'main' panicked at cli/args/mod.rs:525:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: deno::args::get_root_cert_store
   4: once_cell::imp::OnceCell<T>::initialize::{{closure}}
   5: once_cell::imp::initialize_or_wait
   6: <deno::args::CliRootCertStoreProvider as deno_tls::RootCertStoreProvider>::get_or_try_init
   7: deno_fetch::Options::root_cert_store
   8: deno_fetch::get_or_create_client_from_state
   9: deno_fetch::op_fetch<FP>::v8_fn_ptr
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
➜  ~ which quarto
/usr/local/bin/quarto

```

**Comment by neuwirthe** [comment] 2024-04-23 22:56
I found out that if I run the command
`quarto install extension juliantao/qletter`
with `sudo`, installation works.
Which is strange because `sudo` is not necessary on another machine with the same version of MacOS.

**Comment by neuwirthe** [comment] 2024-04-24 09:02
I reinstalled MacOS Sonoma 14.4.1 on my MacStudio, and the problem persists.
With `export RUST_BACKTRACE=full` I get the following
```
➜  ~ export RUST_BACKTRACE=full
➜  ~  quarto install extension juliantao/qletter

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.37.2
Args: ["/Applications/quarto/bin/tools/aarch64/deno", "run", "--unstable", "--no-config", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--no-check", "--importmap=/Applications/quarto/bin/vendor/import_map.json", "/Applications/quarto/bin/quarto.js", "install", "extension", "juliantao/qletter"]

thread 'main' panicked at cli/args/mod.rs:525:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
stack backtrace:
   0:        0x105803af4 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h6d4268b2ed62fb94
   1:        0x104dd4930 - core::fmt::write::h5d55d44549819258
   2:        0x1057d76a8 - std::io::Write::write_fmt::hc515897f91abd6cf
   3:        0x105808238 - std::sys_common::backtrace::print::h2c300c1ebedfc73c
   4:        0x105807e90 - std::panicking::default_hook::{{closure}}::h0aa9be5c44269370
   5:        0x105807b5c - std::panicking::default_hook::h2c0ef097934ee9e6
   6:        0x104d2c7fc - deno::setup_panic_hook::{{closure}}::h4eb3da51069d87b4
   7:        0x105808b24 - std::panicking::rust_panic_with_hook::h84c8637cb6e56008
   8:        0x105808904 - std::panicking::begin_panic_handler::{{closure}}::h25482adda06c7b7f
   9:        0x105808878 - std::sys_common::backtrace::__rust_end_short_backtrace::h0c6f3beb22324a29
  10:        0x10580886c - _rust_begin_unwind
  11:        0x104dd2bdc - core::panicking::panic_fmt::h9072a0246ecafd14
  12:        0x104dd8b50 - core::result::unwrap_failed::hd7600d03a3086be4
  13:        0x104a6aba4 - deno::args::get_root_cert_store::h76b12d4a852c4c10
  14:        0x104a69c8c - once_cell::imp::OnceCell<T>::initialize::{{closure}}::hb94fc97dfdcd9e47
  15:        0x1056cabbc - once_cell::imp::initialize_or_wait::h9fe6355f125574fd
  16:        0x104a69984 - <deno::args::CliRootCertStoreProvider as deno_tls::RootCertStoreProvider>::get_or_try_init::h7e9b6dada7d57b54
  17:        0x104fbb390 - deno_fetch::Options::root_cert_store::h0d33271ea060537e
  18:        0x104fbbbe0 - deno_fetch::get_or_create_client_from_state::h2a9e228fc6719b50
  19:        0x105541598 - deno_fetch::op_fetch<FP>::v8_fn_ptr::ha9858d7d4b924921
```

**Comment by lucacasonato** [comment] 2024-07-02 10:36
Duplicate of #23485

**Closed by lucacasonato** 2024-07-02 10:36 UTC
Labels: bug, tls, macos
