### ISSUE TITLE
Script runnnig

### ISSUE THREAD

**Issue by IbrahimFadel** [denoland/deno#5922] opened 2020-05-28 14:55 UTC
Hi, I'm not sure the exact state of deno right now. I was just introduced to it. One of the things I was wondering, was how we can handle running commands similarly to nodejs in the package.json.

So previously we could define, for example:

```
"build": "webpack ."
```

Is there a way to do this in deno, otherwise, how should a development environment be done?

**Comment by nayeemrmn** [comment] 2020-05-28 14:59
Duplicate of #5255.

**Closed** 2020-05-28 15:02 UTC
