### ISSUE TITLE
Can we provide stripped off version of deno binary?

### ISSUE THREAD

**Issue by Wyvern** [denoland/deno#12992] opened 2021-12-04 21:00 UTC
Currently the deno executable take up about 80M on macos, and after a single strip command, it reduces down to 50M! .

It'd be better to build it with `-C link-arg=-s` to strip off unused symbols in binary release tag.

**Comment by kitsonk** [comment] 2021-12-04 21:12
Duplicate of #9198

**Closed by kitsonk** 2021-12-04 21:12 UTC
Labels: duplicate
