### ISSUE TITLE
In Quarto 1.4.553, deno 1.37.2 panic rendering dot or mermaid to PDF

### ISSUE THREAD

**Issue by forcingFunction** [denoland/deno#24918] opened 2024-08-06 20:27 UTC
Version: Deno 1.37.2

In Quarto 1.4.553, the following dot graph reliably produces a deno error (see below). I also receive this error for graphs using mermaid. 

```
---
title: "Untitled"
format: pdf
---

# Abstract

```{dot}
graph G {
    graph [
        layout=neato
        fontname="Helvetica,Arial,sans-serif"
    ]
    node [
        fontname="Helvetica,Arial,sans-serif"
        fontsize=12
    ]
    edge [
        fontname="Helvetica,Arial,sans-serif"
    ]
    subgraph A {
        A1 [tooltip="A1.",shape=oval,style=filled, fillcolor=bisque4]
        A2 [tooltip="A2",shape=oval,style=filled, fillcolor=bisque1]
        A3 [tooltip="A3",shape=oval,style=filled, fillcolor=bisque1]
        
        A1 -- A2 -- A3 -- A1
    }
}
```

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.37.2
Args: ["C:\\Program Files\\Quarto\\bin\\tools\\x86_64\\deno", "run", "--unstable", "--no-config", "--cached-only", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--importmap", "C:\\Program Files\\Quarto\\bin\\vendor\\import_map.json", "C:\\Program Files\\Quarto\\bin\\quarto.js", "render", "c:/[CENSORED]/Untitled-1.qmd", "--to", "pdf"]

thread 'main' panicked at cli\args\mod.rs:525:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by marvinhagemeister** [comment] 2024-08-06 23:58
What does the code that uses quarto look like? It's easier for us to debug when we have a `.js/.ts` file that we can pass to `deno run` to reproduce the error.

**Comment by ry** [comment] 2024-08-07 00:03
Also please upgrade to the latest Deno and see if you can reproduce. Deno has made many improvements to node compat since Deno 1.37

**Comment by lucacasonato** [comment] 2024-08-07 09:08
Duplicate of #24137

**Closed by lucacasonato** 2024-08-07 09:08 UTC
