### ISSUE TITLE
Source code could not be parsed (Unexpected UTF-8 character)

### ISSUE THREAD

**Issue by kefniark** [denoland/deno#13468] opened 2022-01-22 11:02 UTC
## Description
I have a language detection library [tinyld](https://github.com/komodojp/tinyld) which works in node (CJS) and browser (ESM) without trouble.

But I run into a strange issue when I try to use it in deno.
> error: The module's source code could not be parsed: Unexpected character 'ำ'

The issue come from a big object where I store n-gram for different languages (as utf-8 strings)
I have thousands of other keys in there which do not cause any problem (japanese, chinese, arabic, ...)
```js
 //...
 อ: 9,
 ฮ: 9,
 ะ: 9,
 า: 9,
  ำ: 9,
 //...
```

But I don't now why, there is one specific thai character, ` ำ` which cause that `Unexpected character error` 
If I remove that line, it works fine. 

So my question, is there a reason why this specific utf-8 character cause trouble?

**P.S.** I noticed that the same problem seem to appear in VSCode.
It kinda feel like this character is detected as a single quote, maybe more a typescript issue than deno.

![image](https://user-images.githubusercontent.com/4903529/150635693-adb60a47-3de6-4a67-83e2-458e1d3b256b.png)

**Comment by andreubotella** [comment] 2022-01-22 15:34
This is not a bug with Deno's UTF-8 decoding, but an upstream bug with swc's parsing of JS/TS identifiers (variable names, etc., including non-string property names in object literals, as in this case). I filed swc-project/swc#3341.

**Comment by kefniark** [comment] 2022-01-22 16:48
Thanks for the quick feedback 👍

**Comment by andreubotella** [comment] 2022-03-05 17:09
This is now fixed upstream: swc-project/swc#3867

**Comment by dsherret** [comment] 2022-04-27 18:07
Yes, it seems fixed.

**Closed by dsherret** 2022-04-27 18:07 UTC
Labels: bug, swc
