### ISSUE TITLE
Deno should support .npmrc files

### ISSUE THREAD

**Issue by ry** [denoland/deno#22591] opened 2024-02-26 14:13 UTC
Deno should be able to run a project like this:

.npmrc
```
@jsr:registry=https://npm.jsr.io
```

package.json
```
{
  "name": "foo1",
  "version": "1.0.0",
  "main": "index.mjs",
  "license": "MIT",
  "dependencies": {
    "@simple/pbkdf2": "npm:@jsr/simple__pbkdf2@^0.0.2"
  }
}
```

index.mjs
```
import { pbkdf2, compare } from "@simple/pbkdf2";

const hashed = await pbkdf2("myPassword");
console.log(hashed); // hex encoded salted hash

const isValid = await compare("myPassword", hashed);
console.log(isValid); // true
```

**Comment by dsherret** [comment] 2024-02-26 14:37
Duplicate of #21166

**Closed** 2024-02-26 14:38 UTC
