### ISSUE TITLE
worker.onmessage not being invoked at all

### ISSUE THREAD

**Issue by psrcek** [denoland/deno#8915] opened 2020-12-29 12:24 UTC
I've tried to create a simple example that utilizes workers to send and receive messages, but the main "thread" for lack of a better word fails to receive any kind of message from my worker.

According to `deno -V` I'm using `deno 1.5.3`

Below are my test files, run them with `deno run --unstable --allow-read test.ts`

<details> 
  <summary>test.ts (click to expand)</summary>

```ts
const worker = new Worker(new URL('testworker.ts', import.meta.url).href, { type: 'module', deno: true });

worker.onmessage = (e) => {
    //This is never executed
    console.log('Stuff in worker done:', e.data);
};

worker.postMessage('test');
```
</details>

<details> 
  <summary>testworker.ts (click to expand)</summary>

```ts
import Random from 'https://deno.land/x/random@v1.1.2/Random.js';

async function doStuff(data: any) {
    console.log('Doing stuff:', data);
    const r = new Random();
    const randInt = r.int(200, 2000);
    await new Promise((res, _) => setTimeout(() => res(randInt), 1000));
}

//deno-lint-ignore ban-ts-comment
//@ts-ignore
onmessage = async (e) => {
    try {
        //deno-lint-ignore ban-ts-comment
        //@ts-ignore
        postMessage(await doStuff(e.data))
        console.log('Stuff done:', e.data);
    } catch (e) {
        console.error('Stuff error', e);
    }
}
```
</details>

The output shows the following:
<details> 
  <summary>Output (click to expand)</summary>

```
Doing stuff: test
Stuff done: test
```
</details>

As you can see, the line `Stuff in worker done:` is never logged to the console. Unless I'm doing something wrong that's just not how it's supposed to work as far as I'm aware.

**Comment by lucacasonato** [comment] 2020-12-29 12:33
The latest version of Deno is 1.6.2. Please use that.

**Comment by satyarohith** [comment] 2020-12-29 12:34
@psrcek I think you're not returning any value in `doStuff` - try fixing it and rerun again.

**Comment by psrcek** [comment] 2020-12-29 12:38
Wow! Thanks for the SPEEDY response guys!

@lucacasonato Upgrading didn't fix it.
@satyarohith Returning anything other than undefined is a workaround that works, yes.

**Comment by bartlomieju** [comment] 2020-12-29 12:49
> Returning anything other than undefined is a workaround that works, yes.

@psrcek This is a known issue https://github.com/denoland/deno/issues/8702, @yonbav is working on the fix

**Comment by 00ff0000red** [comment] 2020-12-29 16:34
> Wow! Thanks for the SPEEDY response guys!
> 
> @lucacasonato Upgrading didn't fix it.
> @satyarohith Returning anything other than undefined is a workaround that works, yes.

Probably should've reported this myself a few months ago, but to workaround, I've just posted `null` to fulfill an "empty" reponse.

**Comment by bartlomieju** [comment] 2020-12-29 18:56
Closing as a duplicate of #8702

**Closed by bartlomieju** 2020-12-29 18:56 UTC
