### ISSUE TITLE
deno module manager

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#15229] opened 2022-07-18 13:49 UTC
deno builin module manager (dmm) 

we know : no need to install js module like in node (npm i ..) when running js/ts code using deno, deno will fetch the module and cach it (if not done) then run it but this don't mean no need for module built in for deno, I think to take real advantage of esm we need subcommand in deno cli : deno dmm
I imagin :
deno dmm update url1  url2
this will update all url1 ( old version ) used in any js/ts in the current directory to url2 ( new version ).
deno dmm outdate
show package need to be updated 
...
this will make 90% of your code reutisable in other project and copy-past friendly, I mean we can copy one file content and use it other project without need to declare used module in import_map and without need to have import_map for orginize our modules.

**Comment by kitsonk** [comment] 2022-07-20 03:57
Duplicate of #47

**Closed by kitsonk** 2022-07-20 03:57 UTC
Labels: duplicate
