### ISSUE TITLE
Deno.Server can not be returned from an async function

### ISSUE THREAD

**Issue by lilnasy** [denoland/deno#20736] opened 2023-09-29 13:12 UTC
The new built in server is overly restrictive in its usage. The following pattern is not possible:
```ts
export async function createServer(handler) {
    return Deno.serve({ port: 80 }, handler)
}
...
const server = await createServer(handler)
```
<img width="672" alt="image" src="https://github.com/denoland/deno/assets/69170106/795e22ed-e7e8-43c7-aeae-94e147c5f3ee">

**Comment by dsherret** [comment] 2023-09-29 13:30
Duplicate of #20446

**Closed by dsherret** 2023-09-29 13:30 UTC
Labels: duplicate
