### ISSUE TITLE
deno seems not support inline source map ?

### ISSUE THREAD

**Issue by gcxfd** [denoland/deno#13833] opened 2022-03-04 05:43 UTC
see the screenshot
<img width="1919" alt="image" src="https://user-images.githubusercontent.com/69608605/156706522-63d03927-18a0-4c72-bf9b-e91c86aadecf.png">

❯ deno --version
deno 1.19.1 (release, x86_64-apple-darwin)
v8 9.9.115.7
typescript 4.5.2

test.js is

```
// Generated by CoffeeScript 2.6.1
(function() {
  //!/usr/bin/env coffee
  var i, ref;

  ref = [1, 2, 3, 4, 5];
  for (i of ref) {
    console.log(i);
    if (i > 3) {
      throw new Error(i);
    }
  }

}).call(this);

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoidGVzdC5qcyIsInNvdXJjZVJvb3QiOiIuLiIsInNvdXJjZXMiOlsic3JjL3Rlc3QuY29mZmVlIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiI7QUFBcUI7RUFBQTtBQUFBLE1BQUEsQ0FBQSxFQUFBOztBQUVyQjtFQUFBLEtBQUEsUUFBQTtJQUNFLE9BQU8sQ0FBQyxHQUFSLENBQVksQ0FBWjtJQUNBLElBQUcsQ0FBQSxHQUFJLENBQVA7TUFDRSxNQUFNLElBQUksS0FBSixDQUFVLENBQVYsRUFEUjs7RUFGRjtBQUZxQiIsInNvdXJjZXNDb250ZW50IjpbIiMhL3Vzci9iaW4vZW52IGNvZmZlZVxuXG5mb3IgaSBmcm9tIFsxLi41XVxuICBjb25zb2xlLmxvZyBpXG4gIGlmIGkgPiAzXG4gICAgdGhyb3cgbmV3IEVycm9yIGlcbiJdfQ==
//# sourceURL=/Users/z/rmw/rcp/test/src/test.coffee```

**Comment by kitsonk** [comment] 2022-03-04 06:24
Duplicate of #4499

**Closed by kitsonk** 2022-03-04 06:24 UTC
Labels: duplicate
