### ISSUE TITLE
deno fmt panics when formatting an html file with a longer script section

### ISSUE THREAD

**Issue by ManuelFeller** [denoland/deno#26451] opened 2024-10-21 18:15 UTC
Version: Deno 2.0.0

When running `deno fmt` on the attached html file it fails with the following message:

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 2.0.0
Args: ["deno", "fmt"]

thread 'tokio-runtime-worker' panicked at cli/tools/fmt.rs:792:11:
Formatting not stable. Bailed after 5 tries. This indicates a bug in the formatter where it formats the file (/Users/manuelfeller/Desktop/audio-page/index.html) differently each time. As a temporary workaround you can ignore this file.
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

When the script is put into it's own file (`script.js`) and simply referenced by using `<script src="script.js"></script>` everything works nicely - I could not (yet) narrow down what lines exactly cause this issue.

This ZIP contains the file that causes the panic during `deno fmt`:
[index.html.zip](https://github.com/user-attachments/files/17465266/index.html.zip)

**Comment by bartlomieju** [comment] 2024-10-26 19:19
I believe this is caused by https://github.com/dprint/dprint-plugin-typescript/issues/678

**Comment by bartlomieju** [comment] 2024-12-03 02:36
Fixed in https://github.com/denoland/deno/pull/27164

**Closed by bartlomieju** 2024-12-03 02:36 UTC
Labels: bug, upstream, deno fmt, panic
