### ISSUE TITLE
Crash / silent core dump when stdout and stderr are redirected on command line

### ISSUE THREAD

**Issue by udp53** [denoland/deno#21970] opened 2024-01-17 15:18 UTC
Version: Deno 1.39.4
OS: Amazon Linux 2 
Command line shell: bash

On Deno 1.39.4 (a) deno's output differs from node when the stdout is piped and that pipe is closed, and (b) deno crashes with a core dump if stderr is also closed.

Take this simple file, foo.js:
```
for (let i = 1; i < 100; ++i) { console.log(i) }
```

Case A: What I expect when piping stdout through 'head':
```
$ node -v
v18.19.0
$ node foo.js | head -1
1
```

Case B: What I expect when piping stdout/stderr through 'head':
```
$ node foo.js 2>&1 | head -1
1
```

Case A: What I get running on deno --  unexpected errors 
```
$ deno run foo.js | head -1
1
error: Uncaught (in promise) BrokenPipe: Broken pipe (os error 32)
for (let i = 1; i < 100; ++i) { console.log(i) }
                                        ^
    at Object.print (ext:core/01_core.js:931:28)
    at Console.<anonymous> (ext:runtime/98_global_scope_shared.js:123:46)
    at console.log (ext:deno_console/01_console.js:3041:20)
    at file:///tmp/foo.js:1:41
```

Case B: What I get running on deno -- silent core dump 
```
$ ls core*
ls: cannot access 'core*': No such file or directory
$ deno run foo.js 2>&1 | head -1                                                                                                                                                                            
1
$ ls core*
core.12402
```

**Comment by marvinhagemeister** [comment] 2024-06-27 14:15
Duplicate of https://github.com/denoland/deno/issues/22863

**Closed by marvinhagemeister** 2024-06-27 14:15 UTC
Labels: bug, ext/console
