### ISSUE TITLE
deno run --watch exits when file has invalid syntax

### ISSUE THREAD

**Issue by andykais** [denoland/deno#7848] opened 2020-10-07 02:15 UTC
This is possibly intentional, but I would like to illustrate my case regardless:
if I have a file like so:
```ts
// test.ts
function x() {
}
```
when I run `deno run --watch --unstable test.ts`, the file compiles. If I change the file to something with invalid syntax, like so:
```ts
// test.ts
function__ x() {
}
```
then deno outputs the following, but keeps the watcher active:
```
Watcher File change detected! Restarting!
error: Expected ';', '}' or <eof> at file:///home/andrew/test.ts:1:11
Watcher Process terminated! Restarting on file change...
```
however, if I _start_ `deno run --watch --unstable test.ts` on a file with invalid syntax, it writes the error, and then immediately exists:
```
 ✘ andrew  ~  deno run --watch --unstable test.ts
error: Expected ';', '}' or <eof> at file:///home/andrew/test.ts:1:11
```

I believe what should happen here, is that `run --watch` should keep the file watcher active even when the first compilation fails with invalid syntax

**Comment by bartlomieju** [comment] 2020-11-16 15:34
@magurotuna do you think https://github.com/denoland/deno/pull/8276 addresses this problem?

**Comment by magurotuna** [comment] 2020-11-16 15:47
@bartlomieju No, #8276 doesn't fix this issue. To make matters worse, it seems like the watcher exits when the initial content of the file is correct and then it is updated with invalid syntax. I'll investigate it.

**Comment by magurotuna** [comment] 2020-11-16 15:52
I think I've found the cause. I'll fix it in #8276.

**Comment by bartlomieju** [comment] 2020-11-22 22:34
Fixed in #8276

**Comment by magurotuna** [comment] 2020-11-23 10:30
Implementary: What @andykais requested in this PR has not been addressed in #8276. I mean, in the case where a user runs `deno run --watch --unstable test.ts` with `test.ts` having invalid syntax, then the file watcher still immediately exits. This is due to a technical issue - in such a case, module resolution doesn't work, then the dependency graph isn't constructed, so the watcher can't determine which files should be observed.

**Comment by magurotuna** [comment] 2020-11-23 16:43
My intuition to achieve @andykais's request is to have the watcher observe files specified as command line arguments if module resolution fails. For example, say `foo.ts` has invalid syntax thus module resolution cannot be done with it. Running the following command:

```
$ deno run --watch --unstable test.ts
```

then the watcher would observe `test.ts` only. In this way, the watcher wouldn't exit due to invalid syntax.
I'm not really sure if this will fully satisfy users' needs though.

**Comment by andykais** [comment] 2020-11-23 21:17
> I'm not really sure if this will fully satisfy users' needs though.
it would!  Essentially the pain point is that the command line watcher needs to be restarted whenever a syntax error is saved

**Comment by bartlomieju** [comment] 2020-11-24 12:52
I wonder if we could obtain partial list of files from module graph - ie. if loading some module of module graph fails, it'd be great to get a list of already loaded files. That way if building a full graph fails because of syntax error we could still watch other files that were parsed properly. @kitsonk what do you think?

**Comment by andykais** [comment] 2020-11-24 16:03
@bartlomieju I am definitely do not know a ton about the internals here 😅 but I will say as an external user, I think @magurotuna's suggestion makes the most sense and is the least "magical". I imagine for most users that when a syntax error occurs, its the first thing they will fix. It wont be often that they get a syntax error, and then decide to go work on another file and expect the module graph to keep working. I expect a syntax error kind of halts everything (it just doesnt stop the compilation pipeline 😉)

**Closed** 2020-11-28 14:18 UTC
Labels: bug :bug:, cli :computer:
