### ISSUE TITLE
Deno is panicking

### ISSUE THREAD

**Issue by EFISHJ2** [denoland/deno#25713] opened 2024-09-18 16:47 UTC
Version: Deno x.x.x
Im a student and dont know how to explain or fix this. I will include the code below. 

Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.41.0
Args: ["C:\\Users\\elija\\AppData\\Local\\Programs\\Quarto\\bin\\tools\\x86_64\\deno", "run", "--unstable-ffi", "--no-config", "--cached-only", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--v8-flags=--enable-experimental-regexp-engine,--max-old-space-size=8192,--max-heap-size=8192", "--importmap", "C:\\Users\\elija\\AppData\\Local\\Programs\\Quarto\\bin\\vendor\\import_map.json", "C:\\Users\\elija\\AppData\\Local\\Programs\\Quarto\\bin\\quarto.js", "install", "tinytex"]

thread 'main' panicked at cli\args\mod.rs:596:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lucacasonato** [comment] 2024-09-18 17:09
Duplicate of #24137.

**Closed by lucacasonato** 2024-09-18 17:09 UTC
