### ISSUE TITLE
node compat: Cannot destructure property 'Buffer' of 'globalThis' as it is undefined.

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#19733] opened 2023-07-06 11:34 UTC
I tried to run nuxt using deno and I encountered the below error.

To reproduce:
1. `deno run npm:nuxi@3.6.2 init myapp`
2. `cd myapp && deno task dev`

```
Nuxi 3.6.2                                                                                                      5:01:06 PM
Nuxt 3.6.2                                                                                                      5:01:06 PM

 ERROR  Cannot destructure property 'Buffer' of 'globalThis' as it is undefined.                                5:01:06 PM

  at data::1:83
  at evalModule (node_modules/.deno/jiti@1.19.1/node_modules/jiti/dist/jiti.js:1:255371)
  at Object.jiti (node_modules/.deno/jiti@1.19.1/node_modules/jiti/dist/jiti.js:1:253299)
  at resolveConfig (node_modules/.deno/@nuxt+kit@3.6.2/node_modules/c12/dist/index.mjs:280:24)
  at loadConfig (node_modules/.deno/@nuxt+kit@3.6.2/node_modules/c12/dist/index.mjs:116:40)
  at async loadNuxtConfig (node_modules/.deno/@nuxt+kit@3.6.2/node_modules/@nuxt/kit/dist/index.mjs:2483:18)
  at async Object.invoke (node_modules/.deno/nuxt@3.6.2/node_modules/nuxi/dist/chunks/dev.mjs:112:20)
  at async _main (node_modules/.deno/nuxt@3.6.2/node_modules/nuxi/dist/cli.mjs:49:20)
```

**Comment by ajschmidt8** [comment] 2023-07-08 21:37
I'm also experiencing this with the command below:

`deno run -A npm:tailwindcss/tailwindcss -i ./tailwind.css -o ./assets/style.css`

**Comment by bartlomieju** [comment] 2023-07-09 20:26
We need to land https://github.com/denoland/deno/pull/19307 first to debug and address the problem.

**Comment by dsherret** [comment] 2023-07-09 20:26
We should look into this once #19307 is merged.

**Comment by bartlomieju** [comment] 2023-08-03 23:20
@ajschmidt8 your command works for me in both Deno v1.35.0 and v1.36.0. Could you provide a full reproduction if you're still experiencing these problems?

**Comment by bartlomieju** [comment] 2023-08-03 23:23
With https://github.com/denoland/deno/pull/20046 it's almost possible to run the command, the error I'm getting is:
```
 ../../deno/target/debug/deno task dev
Warning Currently only basic package.json `scripts` are supported. Programs like `rimraf` or `cross-env` will not work correctly. This will be fixed in an upcoming release.
Task dev nuxt dev

                                                                                                                1:18:55 AM
Nuxi 3.6.5                                                                                                      1:18:55 AM
Nuxt 3.6.5                                                                                                      1:18:55 AM
                                                                                                                1:18:57 AM
  > Listening:    http://:3000/

✔ Nuxt Devtools is enabled v0.7.4 (experimental)                                                               1:18:58 AM

 WARN  Failed to resolve dependency: vue, present in 'optimizeDeps.include'                                     1:19:00 AM


[nitro 1:19:00 AM]  ERROR  RollupError: Entry module "node_modules/.deno/nuxt@3.6.5/node_modules/nitropack/dist/runtime/entries/nitro-dev" cannot be external.


undefined

✔ Nitro built in 16 ms                                                                                   nitro 1:19:00 AM

 ERROR  Error: The following dependencies are imported but could not be resolved:                               1:19:00 AM

  vue (imported by /Users/ib/dev/try_nuxi/myapp/node_modules/.deno/nuxt@3.6.5/node_modules/nuxt/dist/app/nuxt.js):18:55 AM

Are they installed?
    at file:///Users/ib/dev/try_nuxi/myapp/node_modules/.deno/@nuxt+vite-builder@3.6.5/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:44188:23
    at eventLoopTick (ext:core/01_core.js:183:11)
    at async file:///Users/ib/dev/try_nuxi/myapp/node_modules/.deno/@nuxt+vite-builder@3.6.5/node_modules/vite/dist/node/chunks/dep-e8f070e8.js:43597:38

```

I think I'm gonna need @dsherret's help to fix that.

**Closed** 2024-08-22 08:03 UTC
Labels: node compat
