### ISSUE TITLE
Deno panicks when watching a Koa server using npm compat

### ISSUE THREAD

**Issue by divmgl** [denoland/deno#15738] opened 2022-09-02 04:31 UTC
```
$ RUST_BACKTRACE=1 DENO_NODE_COMPAT_URL=file:///Users/me/dev/deno_std/ deno run --watch --unstable -A main.ts
```
```tsx
import Koa from "npm:koa";
import KoaRouter from "npm:@koa/router";
import bodyparser from "npm:koa-bodyparser";

const app = new Koa();
const router = new KoaRouter();

router.get("/", (context) => {
  context.status = 200;
});

app.use(bodyparser());
app.use(router.routes());

app.listen(3000);
```

```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.25.0
Args: ["/Users/dimgl/.deno/bin/deno", "run", "--watch", "--unstable", "-A", "main.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', ext/flash/lib.rs:1316:42
stack backtrace:
   0: _rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::panicking::panic
   3: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   4: deno_core::runtime::JsRuntime::poll_event_loop
   5: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: deno::run_command::{{closure}}
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: deno::main::{{closure}}
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: deno_runtime::tokio_util::run_local
  12: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```
Run this then save the file. It will immediately panic.

**Comment by bartlomieju** [comment] 2022-09-02 21:47
This is effectively the same issue as https://github.com/denoland/deno/issues/15646

**Comment by littledivy** [comment] 2022-09-05 03:29
Duplicate of #15646

**Closed by littledivy** 2022-09-05 03:29 UTC
Labels: bug, node compat, flash
