### ISSUE TITLE
weird panic in `[param].ts` files

### ISSUE THREAD

**Issue by tkhatibi** [denoland/deno#26038] opened 2024-10-05 06:09 UTC
Version: Deno 1.46.3

When file name is something like `[name].ts` which is a `fresh` route in my project, I face panic errors in the scenario below:
```typescript
export const handler = (_req: Request) => {
 return new URL(_req.url); // comment this
  // return new URL(req.url); // uncomment this to get error `Cannot find name 'req'`
};
```
You don't need to install `fresh` to reproduce the panic below. File name pattern and the code above are enough.
```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.46.3
Args: ["/root/.deno/bin/deno", "lsp"]

thread '<unnamed>' panicked at cli/lsp/diagnostics.rs:741:46:
called `Result::unwrap()` on an `Err` value: ParseError { index: 33, kind: UnexpectedChar }
stack backtrace:
   0: rust_begin_unwind
   1: core::panicking::panic_fmt
   2: core::result::unwrap_failed
   3: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
   4: <core::iter::adapters::filter_map::FilterMap<I,F> as core::iter::traits::iterator::Iterator>::next
   5: deno::lsp::diagnostics::generate_ts_diagnostics::{{closure}}
   6: <deno_unsync::tokio::task::MaskFutureAsSend<F> as core::future::future::Future>::poll
   7: tokio::runtime::task::raw::poll
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
[Error - 5:38:14 AM] The Deno Language Server server crashed 5 times in the last 3 minutes. The server will not be restarted. See the output for more information.
```
And also it's my OS info:
```
Distributor ID: Ubuntu
Description:    Ubuntu 20.04 LTS
Release:        20.04
Codename:       focal
(Running in WSL)
```

**Comment by littledivy** [comment] 2024-10-05 07:11
It seems we need to update `lsp_types` crate which now uses `fluent_uri` (URI RFC) instead of `rust_url` (WHATWG URL)

**Comment by yazan-abdalrahman** [comment] 2024-10-08 09:28
@littledivy 

It was fixed on the latest source.

```
Starting Deno language server...
  version: 2.0.0-rc.10 (debug, x86_64-pc-windows-msvc)
  executable: c:\Users\Yazan.Abdalrahman\.deno\bin\deno.exe
Connected to "Visual Studio Code" 1.94.0
Enabling import suggestions for: https://deno.land
Refreshing configuration tree...
  Resolved Deno configuration file: "file:///D:/yad/deno/ola/deno.json"
Unsupported compiler options in "file:///D:/yad/deno/ola/deno.json".
  The following options were ignored:
    target
successfully cancelled request with ID: 1
Server ready.
successfully cancelled request with ID: 9
```

**Comment by nayeemrmn** [comment] 2024-10-08 15:03
This is fixed in main, try `deno upgrade rc` or canary.

Duplicate of #1157.

**Closed by nayeemrmn** 2024-10-08 15:03 UTC
Labels: bug, lsp
