### ISSUE TITLE
Deno gets confused by dynamic imports

### ISSUE THREAD

**Issue by jaydenseric** [denoland/deno#12325] opened 2021-10-05 07:36 UTC
The Deno LSP gets confused by dynamic imports in weird ways it's easiest to demonstrate with screenshots...

<img width="861" alt="Screen Shot 2021-10-05 at 6 24 20 pm" src="https://user-images.githubusercontent.com/1754873/135978469-6b89e6bd-b2bf-4ac7-ba91-186e23822733.png">

Notice that the type error is invalid (perhaps related to https://github.com/denoland/deno/issues/11362#issuecomment-933269561), and Deno seems to incorrectly think the type is scoped to the file of the first dynamic import later on in the function. Another weird thing is the `file://` path Deno is displaying in the error omits the `.js` file extension.

Later in the same module, you can see that Deno incorrectly thinks each dynamic import is actually the next dynamic import:

<img width="904" alt="Screen Shot 2021-10-05 at 6 29 25 pm" src="https://user-images.githubusercontent.com/1754873/135979234-57f1ada5-6ae5-4920-a319-4585bbfc6503.png">

The last dynamic import incorrectly has no intellisense when the path is hovered:

<img width="736" alt="Screen Shot 2021-10-05 at 6 31 41 pm" src="https://user-images.githubusercontent.com/1754873/135979557-b67d3c6d-a722-4804-8cc9-4fe462e1ed25.png">

I've tried restarting the Deno LSP via the VS Code Deno extension command, and it doesn't help.

**Comment by kitsonk** [comment] 2021-12-21 10:38
Duplicate of #13156, it is the same root issue as #11362.  Basically JSDoc imports were not being added to the dependency graph, and therefore wouldn't be made available at type checking, instead a "blank" module being substituted.

**Closed by kitsonk** 2021-12-21 10:38 UTC
Labels: duplicate
