### ISSUE TITLE
SWC panic during `--watch`

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#17745] opened 2023-02-12 10:07 UTC
```
============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.29.4
Args: ["/Users/lucacasonato/.deno/bin/deno", "run", "-A", "--unstable", "--watch=static/,routes/", "dev.ts"]

thread 'main' panicked at 'assertion failed: `(left != right)`
  left: `None`,
 right: `None`: value of property 'key' should not be empty', /Users/ib/.cargo/registry/src/github.com-1ecc6299db9ec823/swc_ecma_transforms_react-0.156.20/src/jsx/mod.rs:536:41
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

I don't know what syntax caused this. @dsherret can you easially determine what it may have been? I can't repro it anymore. If you can't repro it either, feel free to close.

**Comment by dsherret** [comment] 2023-02-13 16:34
This causes that when using jsxImportSource. I will try to reproduce it in deno_ast to see if there's a diagnostic I could surface instead.

```
const test = <div key></div>
```

**Comment by dsherret** [comment] 2023-02-13 16:44
There is no diagnostic. Opened https://github.com/swc-project/swc/issues/6939

**Comment by nayeemrmn** [comment] 2023-03-28 03:36
This can be closed since the fix landed

**Comment by dsherret** [comment] 2023-03-28 03:37
Thanks @nayeemrmn!

**Closed by dsherret** 2023-03-28 03:37 UTC
Labels: bug, fix available, swc
