### ISSUE TITLE
Suggestion: `deno bundle --declaration` that generates `.d.ts` file

### ISSUE THREAD

**Issue by uzyn** [denoland/deno#6515] opened 2020-06-27 03:42 UTC
While the general direction are users moving from NodeJS into Deno, for me, I enjoy Deno modules while working on a bigger NodeJS/TS project that consumes npm packages.

I would like to import my Deno modules back into NodeJS while retaining type declaration. Steps that I have to do now are:

1. Copy a.. *.ts files to a temp dir.
2. Remove all `.ts` from `import`s .
3. Recursively resolve all externally loaded modules.

There's also `deno bundle`, which is useful, but it does not generate type declaration file. It would be nice if there's `deno bundle --declaration`, similar to `tsc --declaration`. 

What does the community think?

**Comment by kitsonk** [comment] 2020-06-27 03:58
Duplicate of #3385

**Closed** 2020-06-28 02:56 UTC
