### ISSUE TITLE
Invalid certificate when using a runner 

### ISSUE THREAD

**Issue by allyburg** [denoland/deno#24815] opened 2024-07-31 18:53 UTC
When I try to publish a quarto website to posit connect using GitHub actions on a runner, I get this error:

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.41
Args: ["/opt/quarto/bin/tools/x86_64/deno", "run", "--unstable-ffi", "--no-config", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--no-check", "--v8-flags=--enable-experimental-regexp-engine,--max-old-space-size=8192,--max-heap-size=8192", "--importmap=/opt/quarto/bin/vendor/import_map.json", "/opt/quarto/bin/quarto.js", "publish", "connect", ".", "--no-browser"]

thread 'main' panicked at cli/args/mod.rs:596:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
Error: Process completed with exit code 1.

**Comment by lucacasonato** [comment] 2024-07-31 19:16
Duplicate of #24137

**Closed by lucacasonato** 2024-07-31 19:16 UTC
