### ISSUE TITLE
npm imports broken when using dynamic imports (missing node globals)

### ISSUE THREAD

**Issue by davideperozzi** [denoland/deno#20045] opened 2023-08-03 23:18 UTC
I needed to import a module dynamically and noticed, that there are some inconsistencies. I wanted to pass the path to the module via cli args. So the path to the file is inside `Deno.args`. I basically thought of doing it like this: 

```ts
// npm_import.ts
import { transform } from 'npm:lightningcss@1.21.5';

export default typeof transform === 'function';
```

```ts
// cli.ts
await import(import.meta.resolve(Deno.args[0]));
```
> Deno.args[0] = ./npm_import.ts

But if the file that I'm importing contains "npm:x" imports the **node global scope gets lost** and you get errors like:
```Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'platform')```

This works somehow: 
```ts 
await import('./npm_import.ts')
await import(Deno.args[0]);
```
> Deno.args[0] = ./npm_import.ts

As soon as there is a prefix with `file:///` in the module I'm trying to import it breaks. 
Is it even supposed to work with `file://` prefix?

Deno Version: 1.36.0
Ubuntu (WSL): 20.04

You can checkout this repository for reproduction:
https://github.com/davideperozzi/deno-dynamic-import-issue

Here are some issues that might be related, but I'm not quite sure: 
https://github.com/denoland/deno/issues/20028
https://github.com/denoland/deno/issues/15826

**Comment by bartlomieju** [comment] 2023-08-03 23:25
This is essentially a duplicate of the both issues you linked and it appears you did find a proper workaround until we figure out how to fix it properly.

For reference: import any built-in `node:` module will make sure Deno bootstraps proper polyfills and then dynamic imports that can't be analyzed AOT can still use Node globals.

Let's close this one and continue in #20028

**Closed by bartlomieju** 2023-08-03 23:25 UTC
