### ISSUE TITLE
Used port is not freed when using Deno.run with --watch

### ISSUE THREAD

**Issue by yooneskh** [denoland/deno#16267] opened 2022-10-13 17:55 UTC
When running this code
```ts
Deno.serve(() => {}, { port: x })
```
with this command
```bash
deno run -A --unstable --watch script.ts
```
I get this error everytime i make a change and have to kill the script (ctrl + c) and run it again.

```
Watcher File change detected! Restarting!
error: Uncaught (in promise) AddrInUse: Address already in use (os error 98)
Watcher Process finished. Restarting on file change...
```

deno 1.26.1 (release, x86_64-unknown-linux-gnu)
Linux Fedora 37

**Comment by oliverjam** [comment] 2023-02-21 11:43
Could this issue be re-opened? The problem is still present for me with `deno 1.30.3 (release, aarch64-apple-darwin)`. It looks like there was some back-and-forth with reverted PRs—did a fix ever get merged and released?

**Comment by sant123** [comment] 2023-02-24 04:32
I'm having the same issue with Deno v1.31.0

![image](https://user-images.githubusercontent.com/7959437/221092293-7b0f4823-4e27-4702-8c1b-cfce8fbc4ea2.png)

**Comment by lucis** [comment] 2023-03-10 20:30
This problem is happening in 1.31.2 as well in Windows computers (only arch we were able to reproduce)

**Comment by bllyanos** [comment] 2023-03-13 14:34
Same here 1.31.2 on linux

**Comment by fkdiomande** [comment] 2023-03-15 15:36
Same problem version 1.31.2 on MacOs

**Comment by lyovson** [comment] 2023-03-16 07:23
Any news on this?

**Comment by lunsdorf** [comment] 2023-03-16 07:24
You can get around this by adding an `AbortController` (which might be a good idea in general):

```ts
const abortController = new AbortController();

serve(myRequestHandler, {
  signal: abortController.signal,
  port: 8080,
});

globalThis.addEventListener("unload", () => abortController.abort());
```

**Comment by lyovson** [comment] 2023-03-16 07:27
> ```ts
>  signal: abortController.signal,
> ```

Worked Like a charm, thanks!

**Comment by qgates** [comment] 2023-03-16 17:52
Issue seems to be fixed at deno 1.31.3 without needing the above workaround

**Comment by sant123** [comment] 2023-03-17 02:12
![image](https://user-images.githubusercontent.com/7959437/225794417-4a85796f-0553-4792-80de-ed45dcfd7ec1.png)

**Comment by oliverjam** [comment] 2023-03-17 12:09
Yeah this isn't fixed on 1.31.3 for the built-in `Deno.serve`.

```
$ deno --version
deno 1.31.3 (release, aarch64-apple-darwin)
v8 11.0.226.19
typescript 4.9.4

$ deno run --unstable --watch --allow-net mod.ts
Watcher Process started.
Listening on http://127.0.0.1:9000/
Watcher File change detected! Restarting!
error: Uncaught (in promise) AddrInUse: Address already in use (os error 48)
```

```ts
// mod.ts
Deno.serve(() => new Response("hi"));
```

**Comment by qgates** [comment] 2023-03-21 21:54
@oliverjam running your `mod.ts` on my system (Win10), it does fail but with a different error message:
```
error: Uncaught (in promise) AddrInUse: Only one usage of each socket address (protocol/network address/port) is normally permitted. (os error 10048)
Watcher Process finished. Restarting on file change...
```

**Comment by bartlomieju** [comment] 2023-04-03 22:57
Fixed by https://github.com/denoland/deno/pull/18568

**Closed by bartlomieju** 2023-04-03 22:57 UTC
Labels: bug, cli, --watch

**Comment by sjc5** [comment] 2023-09-25 01:03
Seeing this on `1.37.0` using `Deno.serve`.

It happens intermittently which perhaps suggests a race condition.

**Comment by sant123** [comment] 2023-10-03 19:40
Just tested on `1.37.1` and can't reproduce it. Could you try again? I'm using Fedora 38

**Comment by sjc5** [comment] 2023-10-03 22:59
Yes, happening for me on Deno `1.37.1`, on Ubuntu 22.04.3 LTS.

This is the output:

```
error: Uncaught (in promise) AddrInUse: Address already in use (os error 98)
Deno.serve({ port: PORT }, app.fetch);
     ^
    at listen (ext:deno_net/01_net.js:422:39)
    at Object.serve (ext:deno_http/00_serve.js:557:16)
    at file:///home/sjc/deno-test-0ct-3/dist/main.js:89:6
```

If it matters, the watching is happening via a Node script that calls nodemon, which re-runs the start command when specific files change. The start command is `deno run -A dist/main.js`.

The pertinent server code is just `Deno.serve({ port: PORT }, app.fetch)`.

Sorry if any of this is a red herring, just sharing what might be pertinent.

**Comment by sant123** [comment] 2023-10-03 23:21
Ohhh so is another process restarting the Deno app and not using the watch flag from the CLI?

**Comment by sjc5** [comment] 2023-10-03 23:36
Unfortunately yes, because Deno's watch is not yet very flexible. I'm using nodemon because it lets you watch specific files regardless of what is imported into your server entry file (a feature both Bun and Deno equivalents are lacking at the moment).

Nodemon is running via `child_process.spawn` in a node script (not via CLI), but if it were via CLI it would basically just be like running `nodemon --watch ./some-file`, which re-runs the start script when `./some-file` changes -- the start script being `deno run -A server-entry.js`.

It wouldn't exactly be a minimal repro, but if you run `npx create-hwy@0.2.2-beta.13` and choose "Deno" or "Deno Deploy" when asked about deployment target, and then run the dev script and just start editing some pages, it should repro after a few tries.

**Comment by sant123** [comment] 2023-10-04 01:35
I see, well this is related with this issue but definitely should be tracked in a new one. Because the watch from Deno should be working now, the issue now is how other code may stop and restart a Deno process.
