### ISSUE TITLE
[testing] Add code coverage

### ISSUE THREAD

**Issue by zekth** [denoland/deno#2343] opened 2019-05-12 08:57 UTC
V8 offers the possibility to generate code coverage
ref: https://v8.dev/blog/javascript-code-coverage#for-embedders

I've already started writting a lcov parser : https://github.com/zekth/deno-lcov (ATM use standard lcov file but can be ported to v8 coverage files)

I think it would be really usefull for `deno_std` test modules and even for the `core js` of deno, to see what is really tested or not.

**Comment by kitsonk** [comment] 2019-05-13 04:36
Duplicate of #106

**Closed** 2019-05-13 06:11 UTC
