### ISSUE TITLE
Support Rust-style triple slash comments for "deno doc" 

### ISSUE THREAD

**Issue by ry** [denoland/deno#4666] opened 2020-04-07 19:01 UTC
The jsdoc syntax is pretty obnoxious. It often results in two extra lines just source code.

The only thing speaking against this is that it's non-standard. But jsdoc is not a ecmascript standard - and hopefully it will not be. I think we should try to put the language in better directions where possible.

**Comment by kitsonk** [comment] 2020-04-07 22:48
The TypeScript compiler understands JSDoc, which provides a significantly improved developer experience in visual editors, both with TypeScript and JavaScript.  To move to something else, we would need to re-implement all the semantics and parsing that is built into the TypeScript compiler and create a new language service which can be integrated into plugins to provide that rich information, just to get back to parity with the current experience and expectations.  In fact, JSDoc can provide type information for JavaScript which can be enforced by the TypeScript compiler, and Deno, right now.

Also, there is a significant cowpath for JSDoc that won't ever go away.  The only real movement in this space is actually for enhancements to JSDoc, like TSDoc (https://github.com/microsoft/tsdoc).

While I understand the sentiment, there feels like there are a lot of other windmills we could tilt at.

**Comment by kitsonk** [comment] 2020-08-06 20:18
Ref: https://github.com/microsoft/TypeScript/pull/39930

**Comment by aapoalas** [comment] 2023-02-12 18:06
The TS experiment has been closed. I'd like to close this.

**Comment by crowlKats** [comment] 2023-02-12 18:09
I think its still valid to keep this around; i think it makes sense. we dont strictly stick to what TSDoc implements for deno_doc anyway, due to the slow development there, and often pull in features from JSDoc.

**Comment by kj** [comment] 2023-02-13 06:04
> The TS experiment has been closed. I'd like to close this.

The author of the linked PR closed it, but the issue is still open: https://github.com/microsoft/tsdoc/issues/160

I hope this issue won't be closed.

**Comment by lucacasonato** [comment] 2024-09-04 15:05
We're not going to do this. One style of comments is fine.

**Closed by lucacasonato** 2024-09-04 15:05 UTC
Labels: cli, suggestion
