### ISSUE TITLE
Failed to resolve `package.json` dependency with a specifier of "file:{path/to/dependency}"

### ISSUE THREAD

**Issue by MichaelFedora** [denoland/deno#18961] opened 2023-05-02 19:23 UTC
I decided to try and run a node project of mine with the following arguments:

```
$ deno run --node-modules-dir --allow-env --allow-sys ./src/main.ts --ext ts
```

It gave back the following error:

```
error: Parsing version constraints in the application-level package.json is more strict at the moment.

Not implemented scheme 'file'
    at file:///{path/to/project}/src/main.ts:42:31
```

The library it was trying to import at `:42:31` was one with the following definition in the `package.json`:

```package.json
{
  "dependencies": {
    "@my/library": "file:ext/my-library"
  }
}
```

This is a relatively straightforward bug, and is pretty low-priority, but thought I'd write it up as I couldn't find a duplicate.

Thanks for working on Deno!

**Comment by rajsite** [comment] 2023-05-03 07:16
Seems related to: https://github.com/denoland/deno/issues/18474

**Comment by dsherret** [comment] 2023-05-03 20:14
Closing as duplicate of #18474

**Closed by dsherret** 2023-05-03 20:14 UTC
Labels: duplicate
