### ISSUE TITLE
Service Worker API support

### ISSUE THREAD

**Issue by mfulton26** [denoland/deno#6383] opened 2020-06-19 14:14 UTC
As a developer, I want to be able to write a service worker and use it both in clients (user agents / web browsers) and in servers.

If `deno` adds support for installing service workers with support for `install`, `activate`, `fetch` and other `ServiceWorkerGlobalScope` events then isomorphic service workers become a possibility.

**Comment by nayeemrmn** [comment] 2020-06-19 15:01
Duplicate of #5957.

**Comment by mfulton26** [comment] 2020-06-19 15:33
good call, as long as #5957 includes more than just the `fetch` event then I think we can close this issue in lieu of that one

thank you

**Comment by kitsonk** [comment] 2020-11-05 07:31
Duplicate of #5957

**Closed by kitsonk** 2020-11-05 07:31 UTC
Labels: duplicate :dancers:

**Comment by mfulton26** [comment] 2020-11-05 18:07
@kitsonk will #5957 include `install` and `activate` events too or just `fetch`?

**Comment by kitsonk** [comment] 2020-11-05 19:48
I will make that clear.

**Comment by mfulton26** [comment] 2020-11-05 21:52
thank you!
