### ISSUE TITLE
"github:" prefix for npm dependencies

### ISSUE THREAD

**Issue by mhanuszh** [denoland/deno#19982] opened 2023-07-30 14:27 UTC
I stumbled upon a [package that has a "github" prefix](https://github.com/ben-sb/javascript-deobfuscator/blob/0be1eec1bf6cc4a90a44a1c0d38d537b23bc29c3/package.json#L21). Both me and Deno were speechless when I tried to run it. The [spec](https://docs.npmjs.com/cli/v9/configuring-npm/package-json) has nothing on this, but npm installs it without a second thought.

This is not a feature request, neither a bug report, I'm just not sure who should I ask in this case

**Comment by Seally** [comment] 2023-07-30 16:29
I couldn't find where/if the `github:` prefix is documented in the npm docs, but the Yarn project has a list of protocols it supports here: https://yarnpkg.com/features/protocols

**Comment by SebastienGllmt** [comment] 2024-11-23 23:52
This is a duplicate of #18478

**Closed** 2024-11-24 00:23 UTC
Labels: node compat
