### ISSUE TITLE
expose SubtleCrypto on window.crypto.subtle

### ISSUE THREAD

**Issue by brianleroux** [denoland/deno#3538] opened 2019-12-21 19:31 UTC
already baked into V8 (I think?) so hopefully not too big of a stretch.

(can get by on userland hacks but, for example, interacting with the AWS API requires hand rolling your own signing which is probably a big blocker for most folks)

**Comment by kevinkassimo** [comment] 2019-12-27 15:17
Hmm through references of `SubtleCrypto` in [Chromium Codesearch](https://source.chromium.org/search?q=SubtleCrypto&sq=&ss=chromium%2Fchromium%2Fsrc&originalUrl=https:%2F%2Fcs.chromium.org%2F), I believe it is part of Blink but not V8?

**Comment by crowlKats** [comment] 2020-05-12 17:24
duplicate of #1891

**Comment by lucacasonato** [comment] 2020-08-13 11:47
Closing as duplicate of #1891. SubtleCrypto is not part of V8.

**Closed by lucacasonato** 2020-08-13 11:47 UTC
