### ISSUE TITLE
deno 1.44.3 regression test failure

### ISSUE THREAD

**Issue by chenrui333** [denoland/deno#24275] opened 2024-06-19 18:45 UTC
👋 trying to build the latest release, but run into some test issue. The error log is as below:

<details>
<summary>error test log</summary>

```
$ deno --version
deno 1.44.3 (release, aarch64-apple-darwin)
v8 12.6.228.9
typescript 5.4.5

$ deno run -A -r https://fresh.deno.dev
error: error sending request for url (https://deno.land/std@0.208.0/path/posix/glob_to_regexp.ts)
    at https://deno.land/std@0.208.0/path/posix/mod.ts:44:15
```

</details>

full build log, https://github.com/Homebrew/homebrew-core/actions/runs/9576259879/job/26402508791
relates to Homebrew/homebrew-core#175065

**Comment by marvinhagemeister** [comment] 2024-06-19 19:08
Duplicate of https://github.com/denoland/deno/issues/24260 and https://github.com/denoland/deno/issues/24265

**Closed by marvinhagemeister** 2024-06-19 19:08 UTC
