### ISSUE TITLE
Compile Error when running Cargo Install Deno

### ISSUE THREAD

**Issue by dvbnrg** [denoland/deno#19567] opened 2023-06-21 15:20 UTC
Running Cargo install deno results in the following error:

   Compiling deno_runtime v0.117.0
error[E0432]: unresolved import `tokio_metrics::RuntimeMonitor`
 --> /home/justdave/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_runtime-0.117.0/tokio_util.rs:6:5
  |
6 | use tokio_metrics::RuntimeMonitor;
  |     ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ no `RuntimeMonitor` in the root

For more information about this error, try `rustc --explain E0432`.
error: could not compile `deno_runtime` (lib) due to previous error
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.34.3`, intermediate artifacts can be found at `/tmp/cargo-installj3lO39`

**Comment by bartlomieju** [comment] 2023-06-21 22:19
Duplicate of https://github.com/denoland/deno/issues/19528

**Closed by bartlomieju** 2023-06-21 22:19 UTC
