### ISSUE TITLE
Top-level for-await not working in bundles

### ISSUE THREAD

**Issue by davidbailey00** [denoland/deno#4207] opened 2020-03-01 12:33 UTC
## Steps to reproduce

Create `server.js` with the following content:

```js
import { serve } from "https://deno.land/std@v0.35.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" });
}
```

Run `deno bundle server.js out.js`

Run `deno out.js`

## Expected result

The code runs

## Actual result

```sh
error: Uncaught SyntaxError: Unexpected reserved word
► file:///path/to/out.js:113:17

113             for await (const req of s) {
                    ~~~~~
```

## Notes

Adding `await console.log("test");` or any other `await` statement is detected by the bundler and allows the `for-await` block to work properly. (See #4206)

```
deno 0.35.0
v8 8.1.310
typescript 3.8.2
```

**Comment by ecyrbe** [comment] 2020-03-01 12:46
Please read the typescript release notes : https://www.typescriptlang.org/docs/handbook/release-notes/typescript-3-8.html#top-level-await

Top level avait only work for modules

**Comment by davidbailey00** [comment] 2020-03-01 12:53
@ecyrbe Thanks, however this is a module, and as described in the issue, it works correctly with a regular `await`. The issue is when using a `for await (...)` block which isn't detected by Deno in the same way other `await` statements are.

**Comment by nayeemrmn** [comment] 2020-03-01 15:36
@davidbailey00 Can you append "in bundles" to the title?

Better repro:
`a.js`:
```js
for await (const _ of []);
export {};
```
`deno bundle a.js a.bundle.js && deno a.bundle.js`:
```
Bundling "file:///mnt/c/Users/Nayeem/projects/deno/a.js"
Emitting bundle to "a.bundle.js"
2.3 kB emitted.
```
```
error: Uncaught SyntaxError: Unexpected reserved word
► file:///mnt/c/Users/Nayeem/projects/deno/a.bundle.js:107:17

107             for await (const _ of [])
                    ~~~~~

```

**Comment by davidbailey00** [comment] 2020-03-01 16:49
This may be an upstream bug with TypeScript - adding `console.log(data);` before [line 49 in ` cli/js/compiler_api_test.ts`](https://github.com/denoland/deno/pull/4124/files#diff-6533bacca4309f4c64b99552c6c7e419R49) shows that the `execute` function is missing `async`:

```
$ ./target/debug/deno bundle a.js a.bundle.js                                                                                         
Bundling "file:///Users/david/Code/Rust/deno/a.js"
System.register("a", [], function (exports_1, context_1) {
    "use strict";
    var __moduleName = context_1 && context_1.id;
    return {
        setters: [],
        execute: function () {
            for await (const _ of [])
                ;
        }
    };
});

Emitting bundle to "a.bundle.js"
2.3 kB emitted.
```

**Comment by kitsonk** [comment] 2020-03-01 20:25
Top level `for ... await` is seperate in the standards process from Top level await.  TypeScript has not implemented it, because it isn't progressed far enough in the standards.  We are actually ignoring an error in the compiler that complains about it, because we can support it.  So it is an upstream bug/limitation.

A work around for now would be to use a top level await in the module somewhere else, that would trigger TypeScript to emit the execute as an async function and everything else should work.

**Comment by kitsonk** [comment] 2020-03-15 10:45
I was wrong, it is part of the Stage 3 proposal.  I just got confused because it was implemented in V8 separately.  The TypeScript implementation is incomplete and I have opened https://github.com/microsoft/TypeScript/issues/37402.

**Comment by kitsonk** [comment] 2020-03-31 21:53
There is a PR open and pending review, which has been assigned.  Hopefully it will get merged soon, but might not make TS 3.9.

**Comment by StarpTech** [comment] 2020-05-17 10:37
I use Deno 1.0.0 with TS 3.9 and I can still reproduce this issue with the example above.

**Comment by kitsonk** [comment] 2020-05-17 11:09
@StarpTech the issue is still open because the upstream bug is not fixed.

**Comment by StarpTech** [comment] 2020-05-17 12:38
@kitsonk yes I saw it afterward. What's missing there? It looks like the PR is stale for 2 months.

**Comment by kitsonk** [comment] 2020-05-17 20:04
🤷 I am not able to comment on why PRs are or are not merged in TypeScript.

**Comment by ZenLiuCN** [comment] 2020-05-19 09:43
try this hacking is work: change  `function=>async function` with `const=>let`
```js
  execute: async function () {
        s = server_ts_2.serve({ port: 8000 });
        console.log("servce on http://localhost:8000");
        for await (let req of s) {
          req.respond({ body: "hhhhhh" });
        }
      },
```

**Comment by ZenLiuCN** [comment] 2020-05-19 10:20
https://github.com/denoland/deno/blob/1be7ec47ac3b6e63be2b03245a26e060b8268b5e/cli/js/compiler.ts#L996

is that anybody working on this?

**Comment by lucacasonato** [comment] 2020-05-19 10:21
@ZenLiuCN This is an upstream bug in TypeScript. We can not speed up TypeScript's development.

**Comment by partyka1** [comment] 2020-05-30 22:06
would be good to change server example in the docs, because right now first code you run and do `deno bundle` yields you an error, code taken literally from section `First steps`

**Comment by kt3k** [comment] 2020-06-08 17:30
Surrounding the for-await block with main function seems working around the problem.
```ts
import { serve } from "https://deno.land/std@0.55.0/http/server.ts";
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
async function main() {
  for await (const req of s) {
    req.respond({ body: "Hello World\n" });
  }
}
main()
```

```
$ deno bundle example.ts > bundle.js
Bundling file:///Users/kt3k/3/deno/ex.ts
$ deno run -A bundle.js 
http://localhost:8000/
```

**Comment by lukepighetti** [comment] 2020-07-03 15:02
Apologies if this has been discussed in the past, but Dart doesn't have top level code, instead it uses a `main()` function as an entry point, which can be marked as `async`. Would switching to this method be a viable solution?

**Comment by nayeemrmn** [comment] 2020-12-22 13:37
Fixed with swc bundler.

**Closed** 2020-12-22 22:05 UTC
Labels: bug, cli, upstream
