### ISSUE TITLE
Using `/// <reference lib="dom" />` in main file makes test go ' TS6200 [ERROR]: Definitions of the following identifiers conflict with those in another file'

### ISSUE THREAD

**Issue by David-Else** [denoland/deno#10139] opened 2021-04-11 16:35 UTC
My `mod.ts` is simply:

```
  /// <reference lib="dom" />               
                                                                       
  export function example(): number {
    return 42;
  }
```
and test file:
```
  import { assertEquals } from "../deps.ts";
  import { example } from "../src/mod.ts";
                                                                                                
  Deno.test({
    name: "example test",
    fn(): void {
      // Arrange
      const expectedResult = 42;
      // Act
      const result = example();
      // Assert
      assertEquals(result, expectedResult);
    },
  });
```
Without `  /// <reference lib="dom" />` it works great, with I get:
```
error: TS6200 [ERROR]: Definitions of the following identifiers conflict with those in another file: CompileError, Global, Instance, LinkError, Memory, Module, RuntimeError, Table, ImportExportKind, TableKind, ValueType, ExportValue, Exports, ImportValue, ModuleImports, Imports, BufferSource, MessageEvent, ErrorEvent, Worker, PerformanceEntryList, Performance, PerformanceEntry, PerformanceMark, PerformanceMeasure, CustomEvent
interface Account {
~~~~~~~~~
    at asset:///lib.dom.d.ts:25:1

    Conflicts are in this file.
    declare namespace WebAssembly {
    ~~~~~~~
        at asset:///lib.deno.shared_globals.d.ts:15:1

TS6200 [ERROR]: Definitions of the following identifiers conflict with those in another file: DOMException, Event, EventTarget, EventListenerOrEventListenerObject, ProgressEvent, TextDecoder, TextEncoder, AbortController
interface Account {
~~~~~~~~~
    at asset:///lib.dom.d.ts:25:1

    Conflicts are in this file.
    declare class DOMException extends Error {
    ~~~~~~~
        at asset:///lib.deno.web.d.ts:8:1

TS6200 [ERROR]: Definitions of the following identifiers conflict with those in another file: ReadableStreamReader, CountQueuingStrategy, ByteLengthQueuingStrategy, BlobPart, Blob, File, FormDataEntryValue, FormData, HeadersInit, Headers, RequestInfo, RequestCache, RequestCredentials, RequestMode, RequestRedirect, ReferrerPolicy, BodyInit, RequestDestination, Request, ResponseType, Response
interface Account {
~~~~~~~~~
    at asset:///lib.dom.d.ts:25:1

    Conflicts are in this file.
    interface DomIterable<K, V> {
    ~~~~~~~~~
        at asset:///lib.deno.fetch.d.ts:8:1

TS2300 [ERROR]: Duplicate identifier 'CloseEvent'.
interface CloseEvent extends Event {
          ~~~~~~~~~~
    at asset:///lib.dom.d.ts:3642:11

    'CloseEvent' was also declared here.
    declare class CloseEvent extends Event {
                  ~~~~~~~~~~
        at asset:///lib.deno.websocket.d.ts:14:15

TS2300 [ERROR]: Duplicate identifier 'CloseEvent'.
declare var CloseEvent: {
            ~~~~~~~~~~
    at asset:///lib.dom.d.ts:3657:13

    'CloseEvent' was also declared here.
    declare class CloseEvent extends Event {
                  ~~~~~~~~~~
        at asset:///lib.deno.websocket.d.ts:14:15

TS2300 [ERROR]: Duplicate identifier 'Location'.
interface Location {
          ~~~~~~~~
    at asset:///lib.dom.d.ts:9794:11

    'Location' was also declared here.
    declare class Location {
                  ~~~~~~~~
        at asset:///lib.deno.window.d.ts:70:15
```
... and it goes on

I don't see why this is not working, `mod.ts` will be for the browser using the DOM.

**Comment by nayeemrmn** [comment] 2021-04-11 16:38
There will be conflicts by default, a solution of how to use the DOM types with `deno.ns` is given in https://github.com/denoland/deno/issues/8070#issuecomment-717708036.

Duplicate of #8070.

**Comment by David-Else** [comment] 2021-04-11 16:41
@nayeemrmn Cheers!

It seems like a bad solution to have a config file needed to do this basic operation. Did I read that this was going to be solved by having something like `--dom` in the future?

**Comment by nayeemrmn** [comment] 2021-04-11 16:45
I'm pushing for that, yes. Whatever design we end up on for #10050 would lay some conceptual foundation for `--dom` and other type lib flags for `deno bundle`.

**Comment by kitsonk** [comment] 2021-04-11 21:42
The other way to accomplish it without a configuration file:

```ts
/// <reference no-default-lib="true"/>
/// <reference lib="dom" />  
/// <reference lib="deno.ns" />
/// <reference lib="esnext" />             

export function example(): number {
  return 42;
}
```

> It seems like a bad solution to have a config file needed to do this basic operation.

It isn't a basic operation in my opinion to instruct the Deno type checker to accept APIs that it can't run.  That sounds like more than a basic operation.

I do need to complete https://deno.land/manual@v1.8.3/typescript/configuration#using-the-quotlibquot-property and add an FAQ about using Deno to type check "browser" code, though.

Since this is effectively a duplicate of #8070 I am closing.

**Closed by kitsonk** 2021-04-11 21:42 UTC

**Comment by David-Else** [comment] 2021-04-11 22:58
@kitsonk Please make this information available in the docs, I think it is very important. Cheers.
