### ISSUE TITLE
Can't use deno on windows seven 32 bit.

### ISSUE THREAD

**Issue by bussiere** [denoland/deno#10631] opened 2021-05-14 09:13 UTC
Here is the message that i get when i try to execute deno : 

[https://gateway.ipfs.io/ipfs/QmWs8zeuka9ZRfdDpbZLo7Smi2wKYPi95ruVyuCN52eBaR/deno.png](https://gateway.ipfs.io/ipfs/QmWs8zeuka9ZRfdDpbZLo7Smi2wKYPi95ruVyuCN52eBaR/deno.png)

translation :+1: 
"The version of this file is incompatible with the version of windows you're using. Consult the system information of the computer to know if you need an x86(32 bits) or x64 (64bits) then contact the software editor."

I've installed it with powershell and i've tried also by downloading it.

I have the same message.

I'am on windows seven 32 bit.

regards and thanks

**Comment by crowlKats** [comment] 2021-05-14 09:23
Duplicate of #3438, also Deno does not support Windows 7 because it is EOL.

**Closed** 2021-05-14 09:25 UTC
