### ISSUE TITLE
Feature/request Deno package management just like npm

### ISSUE THREAD

**Issue by mohsin51** [denoland/deno#5832] opened 2020-05-25 07:36 UTC
Deno community is against introducing anything similar to package.json but I am not sure if their approach is better. It's difficult to manage/import packages with absolute URL, there should be something like package.json which gives you details and ability to control versions of external modules which your application is using in single file. Need some sort of cli as well like npm i package@latest.
Not sure how to restrict or bring latest version of package .
Dockerizing Deno application seems confusing at this point.

**Comment by cknight** [comment] 2020-05-25 07:50
There are two patterns you can follow to control versions of external modules in a single file.  The first is through the use of [import maps](https://deno.land/manual/linking_to_external_code/import_maps), while the second is a pattern of using `deps.ts` to hold all your application dependencies which are then re-exported.  Other modules in your application then just import from `deps.ts`.  You can see an example of this in the [oak](https://github.com/oakserver/oak/blob/master/deps.ts) framework.

For updating dependencies, checkout [udd](https://github.com/hayd/deno-udd) which can update all your dependencies with a rule based approach.

**Comment by nayeemrmn** [comment] 2020-05-25 09:59
Duplicate of #47, #288.

**Comment by Swap76** [comment] 2020-05-25 10:58
@mohsin51 The Deno is build to solve the existing problems from NodeJS like having a central authority like npm, having package.json, etc.

You can watch the video mentioning all these things https://www.youtube.com/watch?v=M3BM9TB-8yA

**Comment by ry** [comment] 2020-05-25 13:44
Outside of scope of Deno

**Closed by ry** 2020-05-25 13:44 UTC

**Comment by acathur** [comment] 2020-06-02 17:58
@mohsin51 I have the same idea as you, so I built this thing - [dep](https://github.com/denodep/dep), maybe you can try it out.

**Comment by balupton** [comment] 2020-06-10 06:49
I've created https://github.com/bevry/make-deno-edition to make npm packages written in typescript compatible with deno - is working on https://github.com/bevry/badges - and is being applied to all the bevry packages as we speak - you can use https://github.com/bevry/projectz to automatically generate the readme instructions for the deno edition - and can use https://github.com/bevry/deno to automatically scaffold your projects to automate the entire process
