### ISSUE TITLE
ReferenceError: Cannot access 'Error' before initialization on Deno compiled module

### ISSUE THREAD

**Issue by bartmichu** [denoland/deno#12477] opened 2021-10-18 15:38 UTC
Hello,

I'm compiling my module with:
```shell
deno compile --unstable --allow-net module.js
Check file:///chop/chop/module.js
Bundle file:///chop/chop/module.js
Compile file:///chop/chop/module.js
Emit module
```

Now when I try to run it I get ReferenceError:
```shell
./module            
error: ReferenceError: Cannot access 'Error' before initialization
    at file://$deno$/bundle.js:325:30
```

I'm not referencing ```Error``` explicitly in my code, but I'm using ```std/node``` to get ```crypto``` working, so I guess that's where it's coming from? I can share source code if that would be helpful, it is only ~150 lines of code at this stage.

It works fine when I simply run it with:
```shell
deno run --unstable --allow-net module.js
```

My environment:
- Linux 5.13.0-7614-generic on x86-64
- deno 1.15.1 (release, x86_64-unknown-linux-gnu), v8 9.5.172.19, typescript 4.4.2

Any ideas what am I doing wrong or where the problem is? Thank you in advance.

**Comment by juliangruber** [comment] 2021-10-19 08:34
I have the same issue. Steps to reproduce:

```bash
$ echo '{}' > package.json
$ npm install isarray
```

```ts
// source.ts
import { createRequire } from "https://deno.land/std@0.112.0/node/module.ts"
const require = createRequire(import.meta.url)
const isarray = require("isarray")
```

```bash
$ deno bundle --unstable source.ts > out.js
$ deno run --allow-read --unstable out.js
$ deno --version
deno 1.15.2 (release, x86_64-apple-darwin)
v8 9.5.172.19
typescript 4.4.2
```

**Comment by kitsonk** [comment] 2021-10-19 09:27
Duplicate of #12086

**Closed by kitsonk** 2021-10-19 09:27 UTC
