### ISSUE TITLE
"deno bundle" to produce a dependency-less single file version of a module

### ISSUE THREAD

**Issue by ry** [denoland/deno#2357] opened 2019-05-14 04:24 UTC
Using TypeScript's `outFile` feature. Should support multiple targets.

**Comment by kitsonk** [comment] 2019-05-14 04:37
Duplicate of #21 😁

**Comment by kitsonk** [comment] 2019-05-14 04:38
Which was moved to denoland/deno_std#116 😁

**Comment by kitsonk** [comment] 2019-05-14 04:44
Also, you can't just use `--outFile` with ESM.  ESM modules can't just be concatenated, they have to be parsed and rewritten to be able to exist in a single script file that can be loaded.  One of the big disadvantages of ESM over AMD (which allows concatenation without rewriting).

So we would either need to implement a special syntax structure for Deno that informed Deno how to load each module, or we would have to parse each module, rewrite its own closure, and rewrite all the imports (e.g. rollup).

**Comment by ry** [comment] 2019-05-14 04:51
@kitsonk I think the target should be AMD. The use case here is deploying to browsers. (I think deno should also be able to load AMD?)

**Comment by kitsonk** [comment] 2019-05-14 04:58
Oh, good point.  Changing the output target and generating a bundle.  Hadn't occurred to me, forrest for the trees problem.

We would need to build an AMD loader into Deno, which we used to have before we switched to ESM.  It could just be written into the start of a bundle, or built into the runtime.

**Comment by ry** [comment] 2019-05-14 05:58
> We would need to build an AMD loader into Deno, which we used to have before we switched to ESM. It could just be written into the start of a bundle, or built into the runtime.

Better to write at the start of bundle so it's completely hermetic.

**Comment by pkuhlmann** [comment] 2019-05-15 10:06
amd is dead old let it die

**Comment by kitsonk** [comment] 2019-05-15 10:29
@pkuhlmann so what is your suggestion then.  Just stating something is "dead" isn't very useful.

**Comment by thgh** [comment] 2019-05-15 13:18
What is the usecase precisely?

**Comment by ry** [comment] 2019-05-15 14:18
> What is the usecase precisely?

To make bundles for websites.

**Comment by kitsonk** [comment] 2019-05-15 23:27
> To make bundles for websites.

Or any workload where you want to resolve all the the external runtime code into a single artefact, one that could be independently versioned and managed easily in a source control system which is easily audit-able with industry standard tooling.

It would be the foundation for building custom snapshots.  While not a strict requisite for that, it certainly would make doing it easier.  Currently we use rollup to generate a bundle which then get loaded into the snapshotter for the internal compiler and runtime, but for end users as well as for ourselves potentially, we need a better way to have a single artefact we can load to generate the snapshot.

**Comment by thgh** [comment] 2019-05-17 20:55
Okay, what's the blocking issue with rollup then?

**Comment by JustFly1984** [comment] 2019-05-29 14:57
Hello everyone, I want to add my two cents, concerning browser builds, there definitely should be a code splitting implemented natively and lazy-loading too.

**Comment by kitsonk** [comment] 2019-05-29 21:17
Those are not important features for Deno. If someone was building for the web, they wouldn't want to use a built in Deno bundler.

**Comment by JustFly1984** [comment] 2019-05-29 21:21
What if `Deno` evolves and will be integrated to v8 and other browsers as native TS?

**Comment by kitsonk** [comment] 2019-05-30 00:25
That doesn't make sense at all for Deno.  Deno incorporates V8.  V8 won't incorporate Deno.

Even then you solve for the problems you have, not the problems you don't.

**Comment by JustFly1984** [comment] 2019-05-31 08:33
Code splitting could be useful for lambda functions, to lower the main module bundle size, by lazy-loading some corner case code paths. Currently with node.js execution at AWS for example, we need to monitor a file size, and split lambdas to manage cold start time.

**Comment by i5ar** [comment] 2019-06-02 02:55
Node.js bundlers do not work well with ES modules (e.g. https://github.com/parcel-bundler/parcel/issues/1401) since they were not conceived with ES modules in mind. Many front-end developers only use Node.js to bundle the app and they will defenitly make the switch if Deno come with a better tool.

**Comment by kitsonk** [comment] 2019-06-07 05:37
Just to update those following this thread, I have raised two PRs, one built into Deno to generate a bundle and one in `deno_std` to allow the loading of the bundle.  The bundle will consist of all the statically identifiable dependencies for the root module, output to a single file.  The file is a concatenation of each module transpiled to AMD.

With the PRs, usage would look something like this:

```
$ deno bundle https://deno.land/x/oak/examples/server.ts oak_server.js
[43/43] Downloading https://raw.githubusercontent.com/oakserver/oak/master/pathToRegExp.ts
Bundling "https://deno.land/x/oak/examples/server.ts"...
Emitting bundle to "oak_server.js"...
897.2 kB emitted.
$ deno -A https://deno.land/std/bundle/run.ts oak_server.js
[1/1] Compiling https://deno.land/std/bundle/utils.ts
Start listening on 127.0.0.1:8000
```

**Closed** 2019-06-08 18:42 UTC

**Comment by wongjiahau** [comment] 2020-06-01 05:31
> Those are not important features for Deno. If someone was building for the web, they wouldn't want to use a built in Deno bundler.

By the way, I am using it to bundle a website, if not why alternatives should I use that would not use any Node or npm related modules?

**Comment by kitsonk** [comment] 2020-06-01 09:13
@wongjiahau that is the intention of the compiler APIs: https://deno.land/manual/runtime/compiler_apis#denobundle
