### ISSUE TITLE
WASM SWC errors only in debug mode 

### ISSUE THREAD

**Issue by TreetopFlyer** [denoland/deno#23526] opened 2024-04-24 10:33 UTC
Version: Deno 1.42.3

The following initializes the wasm version of swc.rc:
**example.ts**
```typescript
import init from "https://esm.sh/@swc/wasm-web";
await init();
```
You can `deno run example.ts` without issue, ***however*** when in debug mode (`--inspect-wait` or `--inspect-brk`), and **after a debugger gets attached**, it errors with:
```
error: Uncaught (in promise) TypeError: WebAssembly.compile(): Argument 0 must be a buffer source
    at eventLoopTick (ext:core/01_core.js:168:7)
Process exited with code 1
```

It's possible that this is specific to SWC, but it is interesting to note that Deno itself has to be in debug mode for it to happen so just mentioning it here, thank you.

**Comment by Hajime-san** [comment] 2024-05-27 02:36
seems related https://github.com/denoland/deno/issues/21508

**Comment by lucacasonato** [comment] 2024-06-08 17:25
Closing as dupe of #21508

**Closed by lucacasonato** 2024-06-08 17:25 UTC
Labels: bug, inspector
