### ISSUE TITLE
Workspaces don't work when using a custom config file with `--config` flag

### ISSUE THREAD

**Issue by arnauorriols** [denoland/deno#25428] opened 2024-09-04 13:12 UTC
Using [the workspaces tutorial code](https://docs.deno.com/runtime/fundamentals/workspaces/). Without `--config` runs fine. When adding the flag, even if the config file is the default deno.json, fails:
```bash
$ deno run --allow-env main.ts
1 + 2 = 3
2 - 4 = -2

$ deno run --allow-env --config=deno.json main.ts
error: Relative import path "@scope/subtract" not prefixed with / or ./ or ../ and not in import map from "file:///Users/johndoe/dev/test-workspaces/main.ts"
    at file:///Users/johndoe/dev/test-workspaces/main.ts:3:26
```

**Comment by HasanAlrimawi** [comment] 2024-10-02 14:42
I'm trying to solve this issue....

**Comment by HasanAlrimawi** [comment] 2024-10-02 15:04
I've just noticed you pushed a commit to deno_config where the problem lies to address this issue.
The fix that I came up with was in of file `src/workspace/discovery.rs`  `fn discover_workspace_config_file_for_single_dir`
 -> to replace `start_dir = file.parent().and_then(|p| p.parent())` with --> `start_dir = file.parent();`
This caused the rest of the flow to check for workspace members back in the upper side of the tree rather than going forward and thus finding other workspace members buried inside directories.
I tried this fix and it worked for all tests run by this command `cargo test --package cli_tests --test specs --features run -- workspaces:: --show-output`
 
As I can't see why to roll-back to grandparent to check for more config files, like shouldn't the config file passed to the flag be the main config file of the whole deno project?

**Comment by dsherret** [comment] 2024-10-02 15:27
Oh, #25847 was a duplicate of this one. This is fixed now.

> to replace start_dir = file.parent().and_then(|p| p.parent()) with --> start_dir = file.parent();

I considered this, but I think it would cause it to do a little bit extra work.

**Closed by dsherret** 2024-10-02 15:27 UTC
Labels: bug, workspaces
