### ISSUE TITLE
Deno test sanitizeOps and sanitizeResources leak the ops to adjacent tests.

### ISSUE THREAD

**Issue by baetheus** [denoland/deno#10728] opened 2021-05-20 16:50 UTC
For tests that must (for some reason) leak an operation or resource deno test allows us to [opt out of Op and Resource sanitizing for a single test](https://deno.land/manual/testing#resource-and-async-op-sanitizers). Unfortunately, the resources purposefully leaked by a "leaky" test end up associated with other tests, causing hard to diagnose errors.

I've created a minimal reproduction of the issue in [this repository](https://github.com/baetheus/deno_leaky_async_bug).

Thanks for all the hard work you guys are doing!

**Comment by lucacasonato** [comment] 2021-06-08 16:54
I'm going to close this as an effective duplicate of #10388. I think solving that would also solve this.

**Closed by lucacasonato** 2021-06-08 16:54 UTC
