### ISSUE TITLE
"import type" raises "error: TS7006"

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno#4297] opened 2020-03-09 08:44 UTC
deno version: v0.35.0

Minimal recurrence:
```ts
// main.ts
import type { Func } from "./func.ts";
const func: Func = t => t;

// func.ts
export type Func = (t: string) => string;
```
If we use tsc(v3.8.2), no error will be raised.

**Comment by zhmushan** [comment] 2020-03-09 08:46
err msg:
```
error TS7006: Parameter 't' implicitly has an 'any' type.
► main.ts:2:20
2 const func: Func = t => t;
```

**Comment by ry** [comment] 2020-03-09 14:20
Same error with TS 3.8.3 ... what is the expected output?

**Comment by zhmushan** [comment] 2020-03-09 14:43
TS 3.8.3 threw this error? I only got this error when executing `deno main.ts`, and no error was raised when using `tsc` in strict mode.

**Comment by ry** [comment] 2020-03-09 14:49
Yes, I've done the upgrade in https://github.com/denoland/deno/pull/4301 (should be merged shortly)

**Comment by zhmushan** [comment] 2020-03-09 15:01
I don't seem to express myself clearly. What I want to say is that if I execute the file using `deno`, I will receive an error message, but I will not get an error when compiling with `tsc` (Whether its version is 3.8.2 or 3.8.3)

WITH TSC:
```ts
// main.ts
import type { Func } from "./func";
const func: Func = t => t;

// func.ts
export type Func = (t: string) => string;

// tsconfig.json
{
  "compilerOptions": {
    "strict": true,
    "outDir": "dist"
  }
}
```
```sh
tsc --build tsconfig.json
```
output:
```
```

WITH DENO:
```ts
// main.ts
import type { Func } from "./func.ts";
const func: Func = t => t;

// func.ts
export type Func = (t: string) => string;
```
```sh
deno main.ts
```
output:
```
error TS7006: Parameter 't' implicitly has an 'any' type.
► main.ts:2:20
2 const func: Func = t => t;
```

**Comment by kitsonk** [comment] 2020-03-09 20:20
We may not be handling `import type` correct... I need to check.  @zhmushan what do you get with `deno -L debug main.ts`?

**Comment by zhmushan** [comment] 2020-03-10 00:00
@kitsonk 
```
(base) PS C:\Users\zhmushan\Desktop\ttst> deno -L debug main.ts
DEBUG RS - deno::startup_data:26 - Deno isolate init with snapshots.
DEBUG RS - deno_core::shared_queue:67 - rust:shared_queue:reset
DEBUG JS - cwd C:\Users\zhmushan\Desktop\ttst
DEBUG JS - args []
DEBUG RS - deno:354 - main_module file:///C:/Users/zhmushan/Desktop/ttst/main.ts
DEBUG RS - deno::file_fetcher:154 - fetch_source_file specifier: file:///C:/Users/zhmushan/Desktop/ttst/main.ts 
Compile file:///C:/Users/zhmushan/Desktop/ttst/main.ts
DEBUG RS - deno::startup_data:52 - Deno isolate init with snapshots.
DEBUG RS - deno_core::shared_queue:67 - rust:shared_queue:reset
DEBUG RS - deno::web_worker:94 - received message from host: {"type":0,"target":"main","rootNames":["file:///C:/Users/zhmushan/Desktop/ttst/main.ts"],"outFile":null,"bundle":false}
DEBUG TS - >>> compile start { rootNames: [ "file:///C:/Users/zhmushan/Desktop/ttst/main.ts" ], type: "Compile" }
DEBUG TS - compiler::host.getCompilationSettings()
DEBUG TS - compiler_imports::resolveModules { specifiers: [ "file:///C:/Users/zhmushan/Desktop/ttst/main.ts" ], referrer: undefined }
DEBUG TS - sendSync op_resolve_modules 22
DEBUG TS - compiler_imports::fetchSourceFiles { specifiers: [ "file:///C:/Users/zhmushan/Desktop/ttst/main.ts" 
], referrer: undefined }
DEBUG TS - sendAsync op_fetch_source_files 23
DEBUG RS - deno::file_fetcher:154 - fetch_source_file specifier: file:///C:/Users/zhmushan/Desktop/ttst/main.ts
DEBUG RS - deno_core::shared_queue:177 - rust:shared_queue:pre-push: op=23, off=812, end=1052, len=240
DEBUG RS - deno_core::shared_queue:195 - rust:shared_queue:push: num_records=1, num_shifted_off=0, head=1052
DEBUG TS - compiler::host.getCompilationSettings()
DEBUG TS - compiler::host.getDefaultLibFileName()
DEBUG TS - compiler::host.getSourceFile file:///C:/Users/zhmushan/Desktop/ttst/main.ts
DEBUG TS - compiler::host.resolveModuleNames { moduleNames: [ "./func.ts" ], containingFile: "file:///C:/Users/zhmushan/Desktop/ttst/main.ts" }
DEBUG TS - compiler::host.getSourceFile $asset$/lib.deno.window.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.deno.ns.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.esnext.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2020.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2019.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2018.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2017.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2016.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es5.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.core.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.collection.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.generator.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.iterable.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.symbol.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.promise.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.proxy.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.reflect.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2015.symbol.wellknown.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2016.array.include.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2017.object.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2017.sharedmemory.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2017.string.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2017.intl.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2017.typedarrays.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2018.asyncgenerator.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2018.asynciterable.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2018.promise.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2018.regexp.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2018.intl.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2019.array.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2019.object.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2019.string.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2019.symbol.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2020.bigint.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2020.promise.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2020.string.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.es2020.symbol.wellknown.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.esnext.intl.d.ts
DEBUG TS - compiler::host.getSourceFile $asset$/lib.deno.shared_globals.d.ts
DEBUG TS - sendSync op_worker_post_message 3
DEBUG TS - <<< compile end { rootNames: [ "file:///C:/Users/zhmushan/Desktop/ttst/main.ts" ], type: "Compile" }DEBUG TS - sendSync op_worker_close 4
DEBUG RS - deno::web_worker:98 - channel closed by host, worker event loop shuts down
DEBUG RS - deno::diagnostics:204 - format_message
error TS7006: Parameter 't' implicitly has an 'any' type.

► file:///C:/Users/zhmushan/Desktop/ttst/main.ts:2:20    

2 const func: Func = t => t;
                     ^

```

**Comment by kitsonk** [comment] 2020-03-10 02:12
Hmmm... Ok, nothing obvious. Thanks. Investigating.

**Comment by kitsonk** [comment] 2020-03-11 10:02
I think we needed to change some code, but those changes seem not to work because of microsoft/TypeScript#37338.  So we need to see what is going on there, but for now, sadly, `import type` doesn't work in Deno.

**Comment by kitsonk** [comment] 2020-03-11 23:55
Confirmed as a bug in TypeScript.  Likely won't be fixed until TypeScript 3.9 though.

Workaround for now it to not use `import type` and instead just use `import`.  There are very few cases where this should cause problems.

**Comment by kitsonk** [comment] 2020-03-23 21:44
The fix has landed.  Still targeted for TS 3.9, so won't close until we update to that.

**Comment by zhmushan** [comment] 2020-05-14 00:38
https://github.com/denoland/deno/pull/4510

**Closed** 2020-05-14 00:38 UTC
