### ISSUE TITLE
Not compiling on ARM64

### ISSUE THREAD

**Issue by hironichu** [denoland/deno#16309] opened 2022-10-16 17:40 UTC
Hello,

After trying for a couple of time on many different install, Deno does not seem to build on ARM platforms,

I know there is a bug that has been recently patched after the NAPI bug that occured : 
```
Caused by:
  process didn't exit successfully: `/tmp/cargo-installOYnaBk/release/build/deno-007064bedc20ccfe/build-script-build` (exit status: 101)
  --- stderr
  thread 'main' panicked at 'Missing ./napi_sym/symbol_exports.json! This is a bug in napi_sym: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/ubuntu/.cargo/registry/src/github.com-1ecc6299db9ec823/deno-1.26.1/build.rs:354:65
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
```

This seems to be fixed on master however.. there's now something else on the main branch : 

```
    Building [=======================> ] 886/887: deno(bin)
error: linking with `cc` failed: exit status: 1
  |
  = note: "cc" "/tmp/rustc8figy5/symbols.o" "/tmp/cargo-installGMFLYG/release/deps/deno-a43bf147a58f1098.deno_emit-89aa5c977eb8594f.deno_emit.1c994cce-cgu.0.rcgu.o.rcgu.o" "-Wl,--as-needed" "-L" "/tmp/cargo-installGMFLYG/release/deps" "-L" "/tmp/cargo-installGMFLYG/release/gn_out/obj" "-L" "/tmp/cargo-installGMFLYG/release/build/ring-0beefcbac786742d/out" "-L" "/tmp/cargo-installGMFLYG/release/build/libsqlite3-sys-d2f30d487d144aaa/out" "-L" "/tmp/cargo-installGMFLYG/release/build/libffi-sys-8f5020895edb14cf/out/libffi-root/lib" "-L" "/tmp/cargo-installGMFLYG/release/build/libffi-sys-8f5020895edb14cf/out/libffi-root/lib64" "-L" "/tmp/cargo-installGMFLYG/release/build/lzzzz-58d69c089844a321/out" "-L" "/tmp/cargo-installGMFLYG/release/build/sys-info-f5ddac2bff6c14e9/out" "-L" "/tmp/cargo-installGMFLYG/release/build/zstd-sys-1a83c9d5fc0362a9/out" "-L" "/home/ubuntu/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-Wl,-Bstatic" "/tmp/rustc8figy5/libzstd_sys-7e83e14319244e0d.rlib" "/tmp/rustc8figy5/libsys_info-8e8b0e45422ab787.rlib" "/tmp/rustc8figy5/liblzzzz-beb1d4c11488b121.rlib" "/tmp/rustc8figy5/liblibffi_sys-e326ef2e20352594.rlib" "/tmp/rustc8figy5/libring-10a0f63861f5a1da.rlib" "/tmp/rustc8figy5/liblibsqlite3_sys-7dbcc2f42a55fa3d.rlib" "/tmp/rustc8figy5/libv8-71106ed27ce211a5.rlib" "/home/ubuntu/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib/libcompiler_builtins-e0edb30d3bc4ef0f.rlib" "-Wl,-Bdynamic" "-ldl" "-lgcc_s" "-lutil" "-lrt" "-lpthread" "-lm" "-ldl" "-lc" "-Wl,--eh-frame-hdr" "-Wl,-znoexecstack" "-L" "/home/ubuntu/.rustup/toolchains/nightly-aarch64-unknown-linux-gnu/lib/rustlib/aarch64-unknown-linux-gnu/lib" "-o" "/tmp/cargo-installGMFLYG/release/deps/deno-a43bf147a58f1098" "-Wl,--gc-sections" "-pie" "-Wl,-zrelro,-znow" "-nodefaultlibs" "-Wl,--export-dynamic-symbol-list=/home/ubuntu/.cargo/git/checkouts/deno-22855de1c03c9128/07213de/cli/generated_symbol_exports_list_linux.def"
  = note: /usr/bin/ld:/home/ubuntu/.cargo/git/checkouts/deno-22855de1c03c9128/07213de/cli/generated_symbol_exports_list_linux.def:1: syntax error in dynamic list
          collect2: error: ld returned 1 exit status
```

Any idea/update on this bug?

**Comment by kitsonk** [comment] 2022-10-16 22:56
Duplicate of #16207

**Closed by kitsonk** 2022-10-16 22:56 UTC
Labels: duplicate
