### ISSUE TITLE
node WriteStream leaks in deno tests

### ISSUE THREAD

**Issue by MirKml** [denoland/deno#24649] opened 2024-07-19 14:47 UTC
Version: Deno 1.45.2 - windows 11

simple node write stream example, it's ended with correct end() method call.

write.ts
```typescript
import { createWriteStream } from "node:fs";

export function createFile() {
  const outputWriteStream = createWriteStream("./output.txt", {
    encoding: "utf-8",
  });

  outputWriteStream.on("error", (error) => {
    console.error("error occurs when writing to file: ", error);
    return;
  });
  
  outputWriteStream.write("first line\n", "utf-8");
  outputWriteStream.write("second line\n", "utf-8");
  outputWriteStream.end();
}
```

simple test
write_test.ts
```typescript
import { createFile } from "./write.ts";

Deno.test(
  "write stream test", () => {
    createFile();
  },
);
```

`deno test -A` crashes every time with

```
running 1 test from ./write_test.ts
write stream test ... FAILED (1ms)

 ERRORS

write stream test => ./write_test.ts:3:6
error: Leaks detected:
  - A file was opened before the test started, but was closed during the test. Do not close resources in a test that were not created during that test.
  - A timer was started before the test, but completed during the test. Intervals and timers should not complete in a test if they were not started in that test. This is often caused by not calling `clearTimeout`.
To get more details where leaks occurred, run again with the --trace-leaks flag.

 FAILURES

write stream test => ./write_test.ts:3:6

FAILED | 0 passed | 1 failed (3ms)
```
work around -  disabling all sanitizers - sanitizeResources: false, sanitizeOps: false - but I think it isn't correct solution
`deno test -A --trace-leaks` also makes the test without any errors every time.

I think it's bug. Or any recommendation how can I handle these type of tests without disabled sanitizers?

**Comment by dsherret** [comment] 2024-07-19 18:31
Duplicate of https://github.com/denoland/deno/issues/22626

See that issue for details.

**Closed by dsherret** 2024-07-19 18:31 UTC
Labels: duplicate, invalid

**Comment by MirKml** [comment] 2024-07-20 19:12
Hm, I tried callback event for stream.end(), but nothing changed, still leaking. So disable sanitizers is only solution.

I'm still thinking, that Deno.test would have some user possibility for disposing resources waiting. Maybe some events, callbacks...
Nowadays only disable sanitizers is possible.
Testing some event related code e.g  can be not so easy and straightforward.

**Comment by dsherret** [comment] 2024-07-20 19:14
Can you show your code?

**Comment by MirKml** [comment] 2024-07-20 19:28
It was simple createFile function arg which was used in stream.end() callback. This one was filled in test, with function which tests file content. It's still leaking.

I will try an example of later.

**Comment by dsherret** [comment] 2024-07-20 19:38
It would be good to show an example. There might be something small wrong with it.

**Comment by MirKml** [comment] 2024-07-21 18:32
I updated code in bug report as I mentioned - stream.end(callback), when callback is checked in filled with checks in the test.
It's still leaking with deno test -A

What I don't like in your recommendations in developer point view - disabling sanitizers for such tests:
I have code without any leaks - (I think this one will run without leaks in any app ) - and try to make tests for it. It crashes with leak - resources and timer. It's tells we that I have buggy code with some resource leaks - but it's not true - but I still needs to disable sanitizers in test.

When I will have more complicated bugy code with resource leaks I have no chance to detect this leaks in tests, because I need to always disable sanitizers - if I test code with or without leaks.

**Comment by dsherret** [comment] 2024-07-22 00:45
Yeah, it's not a bug. The test synchronously completes. If you log on the test end you'll see it completes before the callback.

Doing something that waits for the code to complete before exiting the test will fix it. For example:

```ts

Deno.test(
  "write stream test", () => {
    return new Promise(resolve =>
    createFile(function() {
        const content = Deno.readFileSync("./output.txt");
        assertExists(content);
        resolve();
    }));
  },
);
```

**Comment by MirKml** [comment] 2024-07-22 09:47
@dsherret thank you for your advice, I tried - returning Promise which is resolved after assert - 
but it still leaking. See updated test code in bug reports. Can you look at it please?

**Comment by dsherret** [comment] 2024-07-22 14:30
@MirKml sorry, I was on my phone yesterday. I just looked into this and the correct method is `.close()` and not `.end()`. So the following works: `outputWriteStream.close(afterClose)`

**Comment by dsherret** [comment] 2024-07-22 14:33
@MirKml sorry, I was on my phone yesterday. It looks like the close event needs to be listened for:

```
outputWriteStream.on('close', afterClose)
```

**Comment by MirKml** [comment] 2024-07-22 16:08
Fine. Thanks. But as I said, from developer point of view

Original code - without any callbacks, with pure stream.end() - is valid and without any leaks.
But it leaks with simple test case.
For  avoiding leaks - there is necessary to use callback for closing streams and wait for it in test. This isn't always possible.
Or disable sanitizers, which completely hides if there are "dangerous/real" leaks.

I hope for better solution later - when I can test event based code without disabled sanitizers, without additional callback, which can detect "dangerous" leaks better.

**Comment by dsherret** [comment] 2024-07-22 18:11
> Original code - without any callbacks, with pure stream.end() - is valid and without any leaks.

It's not though. If you try to read from the file immediately after calling that code, the file will still be open and not necessarily fully written. 

For example:

```ts
import { createWriteStream } from "node:fs";

export function createFile() {
  const outputWriteStream = createWriteStream("./output.txt", {
    encoding: "utf-8",
  });

  outputWriteStream.on("error", (error) => {
    console.error("error occurs when writing to file: ", error);
    return;
  });

  outputWriteStream.write("first line\n", "utf-8");
  outputWriteStream.write("second line\n", "utf-8");
  outputWriteStream.end();
}

try {
  Deno.removeSync("output.txt");
} catch {
}
createFile();
console.log(Deno.readTextFileSync("output.txt"));
```

```ts
> deno run -A main.ts
error: Uncaught (in promise) NotFound: The system cannot find the file specified. (os error 2): readfile 'output.txt'
console.log(Deno.readTextFileSync("output.txt"));
                 ^
    at Object.readTextFileSync (ext:deno_fs/30_fs.js:864:10)
    at file:///V:/scratch/main.ts:23:18
```

The code needs to be changed to asynchronously wait for the stream to finish in order for that to work correctly.

**Comment by MirKml** [comment] 2024-07-22 19:42
It's depends on use case, for many use cases, such function for create file once - without callbacks/awaits - is perfectly fine, stream.end() finish it and node dispose resources, nothing leaks.

When we need to work with created file etc., some type of wait is necessary, but not everytime.

What isn't fine, that deno.test forces me to bother with such callbacks, awaits everytime, or escape from sanitizers as I understand.

**Comment by dsherret** [comment] 2024-07-22 19:54
It does depend on the use case, but writing code like that could potentially lead to race condition bugs. Deno test is correctly identifying this. If you don't want to run with resource santizers then you can disable them.
