### ISSUE TITLE
Console.log Won't Display Property Values of Objects Having 6 or More Properties

### ISSUE THREAD

**Issue by Lonniebiz** [denoland/deno#3213] opened 2019-10-27 04:57 UTC
deno: 0.21.0
v8: 7.9.304
typescript: 3.6.3

Run this code in both node.js and deno:
```
let o = {};
o.a = 1;
o.b = 2;
o.c = 3;
o.d = 4;
o.e = 5;
o.f = 6;
console.log(o);
```
Node.js output: { a: 1, b: 2, c: 3, d: 4, e: 5, f: 6 }
deno output: { a, b, c, d, e, f }

So, if there are six or more properties, deno's console.log doesn't show the property values.

**Comment by kevinkassimo** [comment] 2019-10-27 19:29
FYI this behavior is introduced in https://github.com/denoland/deno/pull/1969

**Comment by kitsonk** [comment] 2019-10-27 19:41
Effectively duplicate of #3165, though as pointed out, it was specifically introduced in #1969.

**Comment by bartlomieju** [comment] 2019-12-27 16:38
Closing in favor of #3165, thanks for the report!

**Closed by bartlomieju** 2019-12-27 16:38 UTC
