### ISSUE TITLE
Minimal node:http POST/PUT sends duplicate `Content-Length:0` headers

### ISSUE THREAD

**Issue by udp53** [denoland/deno#21196] opened 2023-11-14 02:42 UTC
Duplicate `Content-Length: 0` headers are generated by the node:http.request API.  This very visibly breaks the official npm:aws-sdk npm package. 

Minimal example on deno 1.38.1

```javascript
import http from "node:http";
let req = http.request('http://google.com/', { method: 'POST'})
req.on("response", (res) => { console.log(res.statusCode)})
req.end(); 
```

Via strace or wireshark you can see two Content-Length headers going onto the wire.  Formatted for readability:
`$ strace -v -s 200 -e sendto deno run --allow-net test.js`.  

```POST / HTTP/1.1
host: google.com
content-length: 0
content-length: 0
accept: */*
user-agent: Deno/1.38.1
accept-encoding: gzip, br
\r\n
```

Node is more terse and more importantly only sends one Content-Length header:
`$ strace -v -s 200 -e write node test.js`.  

```POST / HTTP/1.1
Host: google.com
Connection: close
Content-Length: 0
\r\n
```

It's hard to believe this bug hasn't been noticed before, but the real-world impact is very visible to users of the official AWS SDK.  An otherwise-valid PUT api call (with a single optional HTTP header) generates a 4XX error response from the AWS EC2 metadata service, rendering *other* services bafflingly unavailable behind a cryptic `CredentialsProviderError: Could not load credentials from any providers` exception.

Closed/fixed issue #15545 does disclose a similar problem in the fetch API, but in that case the caller was explicitly manipulating the content-length header whereas here the API call is bare-bones.

**Comment by udp53** [comment] 2024-01-18 15:58
@crowlKats @lucacasonato I just noticed this working as of 1.39.0, but don't see any mention in release notes.  Was this fixed?

**Comment by marvinhagemeister** [comment] 2024-04-12 23:02
Closing, I'm unable to reproduce this issue anymore. I only see one `Content-Length` header. Not sure which PR resolved it.

**Closed by marvinhagemeister** 2024-04-12 23:02 UTC
Labels: bug, node compat, node API polyfill
