### ISSUE TITLE
module incompatiblity issue after upgrade to deno 1.2.2

### ISSUE THREAD

**Issue by martunta** [denoland/deno#6972] opened 2020-08-06 15:19 UTC
on mac, after upgrading Deno from 1.1.3 to 1.2.2 I see this error:

```
error: TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname
                 ~~~
    at https://deno.land/std@0.51.0/path/win32.ts:911:18

TS2345 [ERROR]: Argument of type 'string | URL' is not assignable to parameter of type 'string'.
  Type 'URL' is not assignable to type 'string'.
  return new URL(url).pathname;
                 ~~~
    at https://deno.land/std@0.51.0/path/posix.ts:433:18
```

I did --reload for all modules, and another similar error disappeared, but this did not. How can I isolate which module is causing this incompatibility issue to appear?

**Comment by martunta** [comment] 2020-08-06 15:31
by trial and error I found that I needed to bump deno-postgres from 0.4.2 to 0.4.3 for std dependency to go to 0.63.0. 

Is there any way how to see which dependency exactly is causing issue in the case like this? Maybe I am missing some extra command that I could have used.

**Comment by nayeemrmn** [comment] 2020-08-06 15:35
You can use `deno info deps.ts`, look around for `https://deno.land/std@0.51.0/path/win32.ts` and see what the parent modules are.

**Comment by ry** [comment] 2020-08-06 15:39
duplicate of #6873

@martunta This was a project management failure on my part. We inadvertently introduced an incompatibly several weeks ago. This problem will dissipate soon as code gets upgraded and I'm going to try to not let this happen in the future.

**Closed by ry** 2020-08-06 15:39 UTC
