### ISSUE TITLE
Disallow reading from psuedo devices

### ISSUE THREAD

**Issue by dosisod** [denoland/deno#6166] opened 2020-06-07 18:48 UTC
```typescript
import {readFileStr} from "https://deno.land/std@0.56.0/fs/read_file_str.ts";

console.log("start");
readFileStr("/dev/urandom").then(e=>console.log("done!"));
console.log("end");
```

Running:

```
$ deno run --allow-read main.ts
start
end
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', core/bindings.rs:744:5
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
fatal runtime error: failed to initiate panic, error 5
Aborted (core dumped)
```

On Unix systems, files like `/dev/urandom` and `/dev/zero` are pseudo devices, which behave differently then normal files. Is this intended behaviour? Should the user be expected to check for these kinds of files beforehand?

**Comment by ry** [comment] 2020-06-08 16:34
Not sure but we shouldn’t panic.

**Comment by implicitdef** [comment] 2020-06-22 19:17
This seems partially fixed in Deno 1.1.0.
Deno doesn't panic anymore, the Promise is rejected with an exception after ~30s.

```ts
// index.ts
import { readFileStr } from "https://deno.land/std@0.56.0/fs/read_file_str.ts";

console.log("start");
readFileStr("/dev/urandom")
  .then((e) => console.log("done!"))
  .catch((e) => console.log("caught error!", e));
console.log("end");
```
```
$ deno run --allow-read index.ts
start
end
caught error! Error: The buffer cannot be grown beyond the maximum size.
    at Buffer.#grow ($deno$/buffer.ts:137:13)
    at Buffer.readFrom ($deno$/buffer.ts:161:27)
    at async Object.readAll ($deno$/buffer.ts:191:3)
    at async Object.readFile ($deno$/read_file.ts:14:20)
    at async readFileStr (https://deno.land/std@0.56.0/fs/read_file_str.ts:32:25)
```
At least we don't panic. But I'm not sure if it's normal that an exception is thrown so soon (after ~30s) ? At that time the deno process was using around 5.8G of memory.
Does this mean we would also throw an exception like that if we're reading from a very large file ?

FYI I tested the same thing in node.js (10.14.1):
```js
// index.js
const fs = require("fs");

fs.readFile("/dev/urandom", "utf8", function (err, data) {
  if (err) {
    console.log("got error", err);
  } else {
    console.log("got file content");
    console.log(data);
  }
});
```
```
$ node index.js
```
It kept running, I interrupted it after 3 minutes. It was eating 32G of memory and going further. I think this would be the expected behavior ?

**Comment by dosisod** [comment] 2020-06-22 19:48
It is probably happening so fast since it isnt reading from an actual file location, its generated on the fly from the system as you request it.

I dont know why one would need to ingest such large files (in Deno at least). Maybe instead of returning a single string, it would return a chunk of the file, with a promise for the next chunk of data?

Psuedo devices differ from normal files, in that they are a continous stream, as opposed to a file with a fixed size. If the user does not specify when to stop reading from the stream, it will never stop. Users should probably be allowed to read big files, and should probably not be allowed to read infinite streams of data. It would be cool to be able to read partial data from `/dev/urandom/` though.

**Comment by kitsonk** [comment] 2020-06-22 19:52
`BufReader` is a mechanism to read arbitrary large files (or network requests) without creating a gigantic amount of runtime memory.

`Deno.Buffer` has a built in maximum size intentionally.

I can't see consuming 36GB of random memory being the desired behaviour.

If you don't want to allow read access to `/dev/*` then narrow your read permission to only allow access to the paths you want to read from.

**Comment by implicitdef** [comment] 2020-06-22 20:03
Ok so we don't panic anymore and the error is the intended one, I think you can close this.

**Closed** 2020-06-22 20:42 UTC
Labels: bug, cli
