### ISSUE TITLE
Cannot resolve file imported from URL with two slashes

### ISSUE THREAD

**Issue by KnorpelSenf** [denoland/deno#14879] opened 2022-06-15 22:43 UTC
I have a URL that contains two slashes in its path (`//`). I am able to run the script located at that URL using `deno run <url>` and everything works as expected. The URL is: `https://streif.deno.dev/https://deno.land/std@0.144.0/examples/cat.ts`

```bash
$ echo "hello tmp file" > /tmp/file.txt
$ deno run --allow-read=/tmp/file.txt https://streif.deno.dev/https://deno.land/std@0.144.0/examples/cat.ts /tmp/file.txt
hello tmp file
```

However, when I try to import the same module from the REPL, I am left with this:

```bash
$ deno
Deno 1.22.3
exit using ctrl+d or close()
> import 'https://streif.deno.dev/https://deno.land/std@0.144.0/examples/cat.ts'
Module {}
> ERROR TSLS = Error: Error resolving. Referring specifier "https://streif.deno.dev/https:/deno.land/std@0.144.0/examples/cat.ts" was not found.
    at Object.opSync (deno:core/01_core.js:170:12)
    at Object.resolveModuleNames (deno:cli/tsc/99_main_compiler.js:362:29)
    at actualResolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:114795:153)
    at resolveModuleNamesWorker (deno:cli/tsc/00_typescript.js:115064:26)
    at resolveModuleNamesReusingOldState (deno:cli/tsc/00_typescript.js:115240:19)
    at processImportedModules (deno:cli/tsc/00_typescript.js:116661:35)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:116444:17)
    at findSourceFile (deno:cli/tsc/00_typescript.js:116300:26)
    at processImportedModules (deno:cli/tsc/00_typescript.js:116696:25)
    at findSourceFileWorker (deno:cli/tsc/00_typescript.js:116444:17)
```

Note how the two slashes were reduced to one.

> `deno.dev/https:/deno.land`

It seems like Deno is not able to resolve the URL from its cache when in the REPL.

**Comment by Robertoskr** [comment] 2022-06-20 20:07
Hey, thanks for reporting, i will try to solve this issue!

**Comment by KnorpelSenf** [comment] 2022-08-29 08:59
@Robertoskr have you been able to look into this?

**Comment by KnorpelSenf** [comment] 2022-11-05 15:32
I don't care too much about this, but it's not fixed, so hey, let's leave it open until someone bothers to fix it

**Comment by ayame113** [comment] 2023-01-23 02:38
lsp frequently gives an error message when I have an import with two slashes.

https://user-images.githubusercontent.com/40050810/213956974-147058fb-0653-4893-838b-ade7b146d008.mp4

**Comment by lucacasonato** [comment] 2024-09-19 09:52
Duplicate of #9427

**Closed by lucacasonato** 2024-09-19 09:52 UTC
