### ISSUE TITLE
"prompt" should support utf8

### ISSUE THREAD

**Issue by zhmushan** [denoland/deno#8492] opened 2020-11-25 14:47 UTC
```ts
const msg = prompt();
console.log(msg);
```
Then enter `你好`, it outputs `�`.
It looks like we should reconsider the implementation of `readline`

https://github.com/denoland/deno/blob/d40b0711a786d04b5e6321ae9bbf73c11220e865/cli/rt/41_prompt.js#L48-L73

**Comment by bartlomieju** [comment] 2020-11-26 16:58
Duplicate of https://github.com/denoland/deno/issues/8239, let's continue there

**Closed by bartlomieju** 2020-11-26 16:58 UTC
