### ISSUE TITLE
Deno fmt does not always take into account `--config` when using an equals sign in the CLI arguments

### ISSUE THREAD

**Issue by x80486** [denoland/deno#13231] opened 2021-12-29 23:24 UTC
I have a small Deno project that uses a `deno.json` config file:

```json
{
  "fmt": {
    "options": {
      "lineWidth": 120,
      "proseWrap": "preserve"
    }
  },
  "lint": {
    "files": {
      "exclude": ["code_coverage/", "output/"]
    }
  }
}
```

I do run `deno fmt --config=deno.json` and everything is fine, but then on the pipeline I use `deno fmt --check --config=deno.json` instead, and that fails because I set `120` for line width, whereas the default is `80`.

I'm currently using Deno `1.17.1`.

**Comment by csunday95** [comment] 2021-12-31 07:30
while investigating this issue, I found a possible related problem. For lines that are too long, the dprint typescript plugin can make format suggestions that do not resolve the line length problem. For example, 

**test.ts**
```ts
console.info("This line is made intentionally much too long in order to illustrate the issue at hand");
```

if we run `deno fmt` with this file, it will reformat the file to

```ts
console.info(
  "This line is made intentionally much too long in order to illustrate the issue at hand"
);
```

which still has the second line longer than the 80 line length limit. Running ```deno fmt --check`` on this file will also (incorrectly) output no issues.

**Comment by csunday95** [comment] 2021-12-31 08:03
I've now noticed that the doc comment in the dprint plugin for line_width() notes that `the printer may exceed this width in certain cases`, so this is perhaps a known issue / works as intended on that front. I can't, however, seem to reproduce the issue with --check, as running `deno fmt --config=deno.json` with the following file contents
main.ts
```ts
console.info("This line is made intentionally much too long in order to illustrate the issue at hand");
```
deno.json
```json
{
  "fmt": {
    "options": {
      "lineWidth": 120
    }
  }
}
```

does not result in any format changes or issues emitted, with or without the `--check` flag. If `"lineWidth"` is set to, for example, 60, then `deno fmt` correctly identifies the line length issue both with and without `--check`.

**Comment by bartlomieju** [comment] 2021-12-31 14:59
CC @dsherret please take a look

**Comment by dsherret** [comment] 2021-12-31 15:12
> I do run deno fmt --config=deno.json and everything is fine, but then on the pipeline I use deno fmt --check --config=deno.json instead, and that fails because I set 120 for line width, whereas the default is 80.
>
> I'm currently using Deno 1.17.1.

@x80486 what does "pipeline" mean? Is that your CI? How does it fail? Is the CI on Deno 1.17.1? Are there more files on the CI than your local machine that `deno fmt` is finding? Is it perhaps a double format issue where running `deno fmt --config=deno.json` needs to be run a second time for it to format correctly (this would be a bug in the formatting)? I just tried it out and it works fine for me.

**Comment by x80486** [comment] 2021-12-31 19:03
Yes, it's the CI pipeline, but I also get the same result(s) when executing the commands everywhere else. I'm using Deno `1.17.1` — across the board. This is the error message I'm getting:

```shell
[x80486@uplink:~/Workshop/deno-template]$ deno fmt --config=deno.json 
Checked 5 files
[x80486@uplink:~/Workshop/deno-template]$ deno fmt --check --config=deno.json 

from /home/x80486/Workshop/deno-template/src/main.ts:
 5 | -  return Math.round((Math.pow((1 + Math.sqrt(5)) / 2, n) - Math.pow((1 - Math.sqrt(5)) / 2, n)) / Math.sqrt(5));
 5 | +  return Math.round(
 6 | +    (Math.pow((1 + Math.sqrt(5)) / 2, n) -
 7 | +      Math.pow((1 - Math.sqrt(5)) / 2, n)) / Math.sqrt(5),
 8 | +  );

error: Found 1 not formatted file in 5 files
[x80486@uplink:~/Workshop/deno-template]$ uname -a 
Linux uplink 5.10.88-2-lts #1 SMP Wed, 22 Dec 2021 19:16:31 +0000 x86_64 GNU/Linux
[x80486@uplink:~/Workshop/deno-template]$ deno --version 
deno 1.17.1 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.15
typescript 4.5.2
```

> `deno.json` content has what I posted initially.

I use a GitLab CI pipeline, but it's _roughly_ the same as running everything using this `Dockerfile` manifest:

```dockerfile
#
# https://hub.docker.com/r/denoland/deno/
FROM docker.io/denoland/deno:alpine-1.17.1

WORKDIR /tmp/workspace/

# Only src/, deno.json, import-map.json, and lock.json will be copied because of .dockerignore
COPY . ./

RUN set -o errexit -o nounset -o pipefail; \
  apk add lcov --no-cache --no-progress --repository=https://dl-cdn.alpinelinux.org/alpine/edge/testing/; \
  # ...whish --config=deno.json is inferred ;)
  deno fmt --check --config=deno.json; \
  deno lint --config=deno.json; \
  deno test --coverage=code_coverage/ --fail-fast --import-map=import-map.json src/; \
  deno coverage code_coverage/ --lcov > code_coverage/lcov.info; \
  genhtml --output-directory=code_coverage/html_report/ code_coverage/lcov.info; \
  deno cache --import-map=import-map.json --lock=lock.json --reload src/main.ts; \
  mkdir --parents output/; \
  deno bundle --import-map=import-map.json --lock=lock.json src/main.ts output/deno-template.bundle.js; \
  deno compile --cached-only --import-map=import-map.json --lock=lock.json --output=output/deno-template src/main.ts
```

**Comment by dsherret** [comment] 2021-12-31 19:28
@x80486 thanks for the details and that's strange! This works fine for me. Would you be able to provide the file or a file that reproduces the problem?

**Comment by x80486** [comment] 2021-12-31 20:27
`./src/main.ts` only have this 😅

```typescript
/**
 * @author x80486
 */
export function fibonnaci(n: number): number {
  return Math.round((Math.pow((1 + Math.sqrt(5)) / 2, n) - Math.pow((1 - Math.sqrt(5)) / 2, n)) / Math.sqrt(5));
}
```

This is just a template project I use to bootstrap any other Deno project(s), so it only has that one file and `./src/main_test.ts`

```typescript
import { assertStrictEquals } from "testing/asserts.ts"; // import-maps.json > "testing/": "https://deno.land/std@0.119.0/testing/"
import { fibonnaci } from "./main.ts";

Deno.test("fibonnaci", () => {
  const valueSource = [
    [0, 0],
    [1, 1],
    [2, 1],
    [3, 2],
    [4, 3],
    [5, 5],
    [6, 8],
    [7, 13],
    [8, 21],
    [9, 34],
  ];
  valueSource.forEach(([input, expected]) => {
    assertStrictEquals(fibonnaci(input), expected);
  });
});
```

**Comment by dsherret** [comment] 2021-12-31 21:16
@x80486 I'm still not able to reproduce it unfortunately and I don't see anything wrong in the code. Maybe it's a shell specific thing... so try without the equals sign: `deno fmt --config deno.json --check`

**Comment by x80486** [comment] 2021-12-31 23:31
OK...what is this? 🤯 😑

If I don't use the `=` sign, it's working. I don't really understand that, it must work the same with or without the sign. But, you know...now I'm all set! 😃

But on the other hand, within the Docker container behaves the same, so it's weird.

**Comment by dsherret** [comment] 2022-01-01 00:17
@x80486 thanks for trying it! There must be some way for us to surface this and error.

**Comment by bartlomieju** [comment] 2022-01-04 17:17
@crowlKats PTAL, it seems like something that could be solved by clap v3

**Comment by crowlKats** [comment] 2022-01-04 21:09
Yes this potentially could be fixed by clap v3 if i understand the issue, but i think its not just a matter of upgrade here, but also behavioural change we need to address (which most definitively would have to wait for 2.0). I do have a complete refactor of flags.rs planned

**Comment by x80486** [comment] 2022-03-25 13:39
Hit the snag again with `deno test --coverage=coverage/ ...`, somehow the `=` sign is a must for this one :confused:

**Closed** 2024-08-27 17:58 UTC
Labels: bug, deno fmt
