### ISSUE TITLE
redirected imports cause type errors in v1.5

### ISSUE THREAD

**Issue by maximousblk** [denoland/deno#8184] opened 2020-10-29 05:50 UTC
when using x.nest.land, which **redirects** to the arweave URL

![image](https://user-images.githubusercontent.com/28438021/97530340-e674a800-19d7-11eb-8dea-cc7b635be274.png)

<details><summary>full error</summary>

```ts
error: TS2345 [ERROR]: Argument of type 'import("https://x.nest.land/std@0.74.0/log/logger.ts").LogRecord' is not assignable to parameter of type 'import("https://nghbeaead2s4n5znqogrk627qxhfdfterapmd3orofnyqlfusora.arweave.net/aY4SAIAepcb3LYONFXtfhc5RlmSIHsHt0XFbiCy0k6I/log/logger.ts").LogRecord'.
  Property '#args' in type 'LogRecord' refers to a different member that cannot be accessed from within type 'LogRecord'.
      handler.handle(record);
                     ~~~~~~
    at https://x.nest.land/std@0.74.0/log/logger.ts:116:22

TS2416 [ERROR]: Property 'format' in type 'ConsoleHandler' is not assignable to the same property in base type 'BaseHandler'.
  Type '(logRecord: import("https://x.nest.land/std@0.74.0/log/logger.ts").LogRecord) => string' is not assignable to type '(logRecord: import("https://nghbeaead2s4n5znqogrk627qxhfdfterapmd3orofnyqlfusora.arweave.net/aY4SAIAepcb3LYONFXtfhc5RlmSIHsHt0XFbiCy0k6I/log/logger.ts").LogRecord) => string'.
    Types of parameters 'logRecord' and 'logRecord' are incompatible.
      Type 'import("https://nghbeaead2s4n5znqogrk627qxhfdfterapmd3orofnyqlfusora.arweave.net/aY4SAIAepcb3LYONFXtfhc5RlmSIHsHt0XFbiCy0k6I/log/logger.ts").LogRecord' is not assignable to type 'import("https://x.nest.land/std@0.74.0/log/logger.ts").LogRecord'.
        Property '#args' in type 'LogRecord' refers to a different member that cannot be accessed from within type 'LogRecord'.
  format(logRecord: LogRecord): string {
  ~~~~~~
    at file:///C:/Users/maela/code/gh/nestdotland/eggs/src/utilities/log.ts:35:3

TS2416 [ERROR]: Property 'format' in type 'FileHandler' is not assignable to the same property in base type 'BaseHandler'.
  Type '(logRecord: import("https://x.nest.land/std@0.74.0/log/logger.ts").LogRecord) => string' is not assignable to type '(logRecord: import("https://nghbeaead2s4n5znqogrk627qxhfdfterapmd3orofnyqlfusora.arweave.net/aY4SAIAepcb3LYONFXtfhc5RlmSIHsHt0XFbiCy0k6I/log/logger.ts").LogRecord) => string'.
    Types of parameters 'logRecord' and 'logRecord' are incompatible.
      Type 'import("https://nghbeaead2s4n5znqogrk627qxhfdfterapmd3orofnyqlfusora.arweave.net/aY4SAIAepcb3LYONFXtfhc5RlmSIHsHt0XFbiCy0k6I/log/logger.ts").LogRecord' is not assignable to type 'import("https://x.nest.land/std@0.74.0/log/logger.ts").LogRecord'.
  format(logRecord: LogRecord): string {
  ~~~~~~
    at file:///C:/Users/maela/code/gh/nestdotland/eggs/src/utilities/log.ts:77:3

TS2322 [ERROR]: Type 'ConsoleHandler' is not assignable to type 'BaseHandler'.
  Types of property 'format' are incompatible.
    Type '(logRecord: import("https://x.nest.land/std@0.74.0/log/logger.ts").LogRecord) => string' is not assignable to type '(logRecord: import("https://nghbeaead2s4n5znqogrk627qxhfdfterapmd3orofnyqlfusora.arweave.net/aY4SAIAepcb3LYONFXtfhc5RlmSIHsHt0XFbiCy0k6I/log/logger.ts").LogRecord) => string'.
      Types of parameters 'logRecord' and 'logRecord' are incompatible.
        Type 'import("https://nghbeaead2s4n5znqogrk627qxhfdfterapmd3orofnyqlfusora.arweave.net/aY4SAIAepcb3LYONFXtfhc5RlmSIHsHt0XFbiCy0k6I/log/logger.ts").LogRecord' is not assignable to type 'import("https://x.nest.land/std@0.74.0/log/logger.ts").LogRecord'.
      console: new ConsoleHandler(debugEnabled ? "DEBUG" : "INFO"),
      ~~~~~~~
    at file:///C:/Users/maela/code/gh/nestdotland/eggs/src/utilities/log.ts:122:7

TS2322 [ERROR]: Type 'FileHandler' is not assignable to type 'BaseHandler'.
  Types of property 'format' are incompatible.
    Type '(logRecord: import("https://x.nest.land/std@0.74.0/log/logger.ts").LogRecord) => string' is not assignable to type '(logRecord: import("https://nghbeaead2s4n5znqogrk627qxhfdfterapmd3orofnyqlfusora.arweave.net/aY4SAIAepcb3LYONFXtfhc5RlmSIHsHt0XFbiCy0k6I/log/logger.ts").LogRecord) => string'.
      Types of parameters 'logRecord' and 'logRecord' are incompatible.
        Type 'import("https://nghbeaead2s4n5znqogrk627qxhfdfterapmd3orofnyqlfusora.arweave.net/aY4SAIAepcb3LYONFXtfhc5RlmSIHsHt0XFbiCy0k6I/log/logger.ts").LogRecord' is not assignable to type 'import("https://x.nest.land/std@0.74.0/log/logger.ts").LogRecord'.
      file: new FileHandler("DEBUG"),
      ~~~~
    at file:///C:/Users/maela/code/gh/nestdotland/eggs/src/utilities/log.ts:123:7

Found 5 errors.
```

</details>

when using [envoy](https://envoy.now.sh), which **proxies** to the arweave URL. note that the source is still the same as using nest.land directly.

![image](https://user-images.githubusercontent.com/28438021/97530420-1de35480-19d8-11eb-9f24-dd878c9ea65f.png)

this only happens in deno v1.5

**Comment by kitsonk** [comment] 2020-10-29 06:21
Duplicate of #8154 

Which is fixed in master and will be part of 1.5.1.

**Closed by kitsonk** 2020-10-29 06:21 UTC
Labels: duplicate
