### ISSUE TITLE
deno bundleForNode {filename.js/ts} -- --output o.js command

### ISSUE THREAD

**Issue by elycheikhsmail** [denoland/deno#13752] opened 2022-02-23 19:43 UTC
## suggestion

I suggess to add the following  command :

```
deno bundleForNode {filename.js/ts} -- --output o.js

```
like deno bundleForNode {filename.js/ts} -- --output o.js
but 
- finlename.js/ts can access any node api
- node can run o.js without problem
- deno run --compet o.js may failed if the some node api not supported by --compat are used

## use case

- allow develop to use deno ecosystem for develop frontend using framwork like svelte, vue ... with little effort

**Comment by dsherret** [comment] 2022-02-23 21:39
> use case: allow develop to use deno ecosystem for develop frontend using framwork like svelte, vue ... with little effort

See dnt: https://github.com/denoland/dnt

It would be very hard to develop a `deno bundleForNode` sub command because there's lots of edge cases. dnt tries to handle them.

**Comment by kitsonk** [comment] 2022-02-23 22:48
Duplicate of #13753 which is closed.

**Closed by kitsonk** 2022-02-23 22:48 UTC
Labels: duplicate
