### ISSUE TITLE
will Deno backward compatible with current NodeJS module?

### ISSUE THREAD

**Issue by giavy0209** [denoland/deno#6107] opened 2020-06-04 18:09 UTC
Like my title, in the future could Deno use NodeJS module or developer have to rewrite NodeJS module for Deno?

**Comment by nayeemrmn** [comment] 2020-06-04 18:10
Duplicate of #2644.

**Comment by ry** [comment] 2020-06-04 18:25
see https://deno.land/std/node

**Closed by ry** 2020-06-04 18:25 UTC
