### ISSUE TITLE
Standard Module, Websocket Example Error!

### ISSUE THREAD

**Issue by gungunfebrianza** [denoland/deno#7018] opened 2020-08-11 08:58 UTC
Just trying to use basic ws example from the documentation here 
https://deno.land/std@0.64.0/ws
and i got this error 
```
error: TS2322 [ERROR]: Type 'import("https://deno.land/std/io/bufio").BufReader' is not assignable to type 'import("https://deno.land/std@0.64.0/io/bufio").BufReader'.
  Types have separate declarations of a private property 'buf'.
      bufReader,
      ~~~~~~~~~
    at file:///F:/MarketkoinMaster/Application/API-Marketkoin2.0/v1/api-client/b.ts:48:7

    The expected type comes from property 'bufReader' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufReader: BufReader;
      ~~~~~~~~~
        at https://deno.land/std@0.64.0/ws/mod.ts:421:3

TS2322 [ERROR]: Type 'import("https://deno.land/std/io/bufio").BufWriter' is not assignable to type 'import("https://deno.land/std@0.64.0/io/bufio").BufWriter'.
  Types have separate declarations of a private property 'writer'.
      bufWriter,
      ~~~~~~~~~
    at file:///F:/MarketkoinMaster/Application/API-Marketkoin2.0/v1/api-client/b.ts:49:7

    The expected type comes from property 'bufWriter' which is declared here on type '{ conn: Conn; bufWriter: BufWriter; bufReader: BufReader; headers: Headers; }'
      bufWriter: BufWriter;
      ~~~~~~~~~
        at https://deno.land/std@0.64.0/ws/mod.ts:420:3

Found 2 errors.
```
Deno Version 1.2.3
OS : Windows 10

**Comment by lucacasonato** [comment] 2020-08-11 10:19
Could you change the imports to point to `https://deno.land/std@0.64.0`instead of `https://deno.land/std`?

**Comment by caspervonb** [comment] 2020-08-13 23:20
I'm unable to reproduce this, tried both the server and client on v1.2.3 and v1.3.0.

**Comment by bartlomieju** [comment] 2020-08-27 09:47
Closed as resolved. Please use tagged imports.

**Closed by bartlomieju** 2020-08-27 09:47 UTC
