### ISSUE TITLE
`deno compile` does not include local binary files read by the source code in the output

### ISSUE THREAD

**Issue by intpfx** [denoland/deno#25832] opened 2024-09-23 15:57 UTC
When using the `deno compile` command to compile a project, it was found that the binary output does not include local binary files read by the source code.

I would like to understand the rationale behind this current behavior.

The purpose of using the compile operation is to distribute the program as a single file (which aligns with the minimalist design philosophy and is very cool). However, the current compile operation requires distributing additional binary files that are not compiled into the executable file (unless the source code is modified in advance to embed the files read by APIs like Deno.readFileSync into the JavaScript code in an ugly text format). In my opinion, this is not elegant.

I noticed that the dependencies packaged during the current compile operation are all imported through the import statement. So, I wonder if it is possible to import files in the following way to be statically analyzed by deno:

```javascript
import file_content from './file.txt' with { type: "binary" } // file_content is a Uint8Array object
```

```javascript
const file_content = await import('./file.txt', { with: { type: "binary" } }) // file_content is a Uint8Array object
```

**Comment by dsherret** [comment] 2024-09-23 18:33
Duplicate of https://github.com/denoland/deno/issues/20885

**Closed by dsherret** 2024-09-23 18:33 UTC
Labels: feat, duplicate, compile
