### ISSUE TITLE
Unclear error message when upgrading to non-existent version

### ISSUE THREAD

**Issue by sholladay** [denoland/deno#6347] opened 2020-06-17 22:37 UTC
I was trying to figure out which version of Deno broke my app, so I was bisecting different versions blindly and discovered an amusing error. When `deno upgrade` is given a non-existent version, its output is unclear and contradictory, as it says that the version was found, but then fails to download it due to a 404 Not Found error.

Is "Version has been found" hardcoded? 😄 

```
❯ deno upgrade --version 1.0.6
Version has been found
Deno is upgrading to version 1.0.6
downloading https://github.com/denoland/deno/releases/download/v1.0.6/deno-x86_64-apple-darwin.zip
error: Import 'https://github.com/denoland/deno/releases/download/v1.0.6/deno-x86_64-apple-darwin.zip' failed: 404 Not Found
```

**Comment by lucacasonato** [comment] 2020-06-17 22:37
Duplicate of https://github.com/denoland/deno/issues/6329

**Closed** 2020-06-17 22:43 UTC
