### ISSUE TITLE
Unusual behaviour with `Deno.run` and large buffers

### ISSUE THREAD

**Issue by andybee** [denoland/deno#7070] opened 2020-08-16 18:43 UTC
Further to a [Discord discussion](https://discordapp.com/channels/684898665143206084/689420767620104201/744610445322747934) today, I'm seeing unusual behaviour when using `Deno.run` and piping a large buffer in to `stdin`.

The following script hangs indefinitely on the `Deno.writeAll` line (using this instead of `proc.stdin.write` to ensure the entire buffer is written.

```
const response = await fetch("http://localhost:8000/a.mp3");
const buffer = new Uint8Array(await response.arrayBuffer());

const proc = Deno.run({
  cmd: ["sox", "-t", "mp3", "-", "-t", "raw", "-"],
  stdin: "piped",
  stdout: "piped",
  stderr: "inherit",
});
console.error("input length=", buffer.length);
await Deno.writeAll(proc.stdin, buffer);
console.error("write done");
proc.stdin.close();
await proc.status();
const data = await proc.output();
proc.close();
```

In the Discord chat we collectively tried various things such as shuffling an empty buffer of the correct length (fine) and also mimicking the same functionality entirely with the shell (e.g. `curl http://localhost:8000/a.mp3 | sox -t mp3 - -t raw - | play -q -t raw -b 16 -e signed -c 2 -r 44100 - > dump.raw`) - which works. If we disable piping stdout (change to inherit), it completes successfully.

Tested on Deno 1.3.0 on macOS.

**Comment by caspervonb** [comment] 2020-08-16 19:41
Generate sample data with something like

```sh
sox -n -r 44100 -c 2 silence.wav trim 0.0 3.0
```

This also fails with just Deno.readFile, so to simply the example

```typescript
const buffer = await Deno.readFile('silence.wav');

const proc = Deno.run({
  cmd: ["sox", "-t", "wav", "-", "-t", "raw", "-"],
  stdin: "piped",
  stdout: "piped",
  stderr: "inherit",
});
console.error("input length=", buffer.length);
await Deno.writeAll(proc.stdin, buffer);
console.error("write done");
proc.stdin.close();
await proc.status();
const data = await proc.output();
proc.close();
```

Swapped out mp3 for wav here because mp3 is not in default distros.

**Comment by caspervonb** [comment] 2020-08-16 20:06
Example run with Deno.writeAll "instrumented" with log calls

```
input length= 10584080
written 0 of 10584080
written 65536 of 10584080
written 131072 of 10584080
written 167936 of 10584080
```

**Comment by paul-thompson-helix** [comment] 2020-08-25 08:48
Ensure that you are reading data from the stdout while it is running, then it doesn't end up relying on kernel buffering.

Try the following in order to read the data from stdout in parallel with writing it into stdin.

```const buffer = await Deno.readFile('data.txt');
console.error("input length=", buffer.length);

const proc = Deno.run({
  cmd: ["cat"],
  stdin: "piped",
  stdout: "piped",
  stderr: "inherit",
});

async function write() {
    await Deno.writeAll(proc.stdin, buffer);
    proc.stdin.close();
    return null;
};

async function read() {
    const data = await proc.output();
    return data;
}

async function result() {
    const res = await proc.status();
    proc.close();
    return res;
}

const [_, data] = await Promise.all([
    write(),
    read()
]);
await result();
console.log('output length:', data.length);
```

**Comment by paul-thompson-helix** [comment] 2020-08-25 08:51
Conclusion: not a bug - just something to watch out for when piping data to subprocesses.

**Comment by bartlomieju** [comment] 2020-10-07 15:56
@paul-thompson-helix thanks for detailed report. Closing as non-issue.

**Closed by bartlomieju** 2020-10-07 15:56 UTC
Labels: bug, cli
