### ISSUE TITLE
Native Deno typescript parser api 

### ISSUE THREAD

**Issue by hodev-dev** [denoland/deno#13237] opened 2021-12-30 09:50 UTC
any plan to expose typescript parser under Deno namespace?
it would be primitive requirement for making code generator or transformations
if Deno uses swc under the hood it would be great if we get parser under Deno namespace for development tools;
like 
```typescript
Deno.typescript.parse('const variable = "value");
```

**Comment by kitsonk** [comment] 2021-12-30 10:00
Duplicate of #2355 #3983 and #9851

**Closed by kitsonk** 2021-12-30 10:00 UTC
Labels: duplicate
