### ISSUE TITLE
Support VitePress (Vite/Vue SSG)

### ISSUE THREAD

**Issue by birkskyum** [denoland/deno#20609] opened 2023-09-21 12:35 UTC
VitePress - [Website](https://vitepress.dev/) - [GitHub](https://github.com/vuejs/vitepress)

**Platform**

Darwin 22.6.0 arm64 arm

**Version**

deno 1.37.0

**Repro**

- create a new folder and `cd` to it
- `deno run -A npm:vitepress init` - just step through
- `deno run -A npm:vitepress dev` - Dev mode is working  🎉
- `deno run -A npm:vitepress build`

**Expected**

That a build is made

**Actual**

```rust
➜ deno task build
Warning Currently only basic package.json `scripts` are supported. Programs like `rimraf` or `cross-env` will not work correctly. This will be fixed in an upcoming release.
Task build vitepress build docs
vitepress v1.0.0-alpha.28
✓ building client + server bundles...
build error:
 TypeError: Cannot read properties of undefined (reading 'hash')
    at file:///Users/admin/repos/deno-kitchensink/vitepress-project/docs/.vitepress/.temp/app.js:369:42
```

**Comment by bartlomieju** [comment] 2023-10-10 14:33
https://github.com/denoland/deno/issues/20339#issuecomment-1755554197

**Comment by birkskyum** [comment] 2024-01-25 17:30
With deno 1.40 the build now errors at:

```sh
➜ deno run -A npm:vitepress build

  vitepress v1.0.0-rc.40

build error:
TypeError: unknown variant `junction`, expected `file` or `dir`
    at Object.symlinkSync (ext:deno_fs/30_fs.js:545:3)
    at Object.symlinkSync (ext:deno_node/_fs/_fs_symlink.ts:21:8)
    at Object.createSymlinkSync$1 (file:///Users/admin/repos/deno-kitchensink/new-vitepress/node_modules/.deno/vitepress@1.0.0-rc.40/node_modules/vitepress/dist/node/serve-e9-zRdpq.js:2160:27)
    at linkVue (file:///Users/admin/repos/deno-kitchensink/new-vitepress/node_modules/.deno/vitepress@1.0.0-rc.40/node_modules/vitepress/dist/node/serve-e9-zRdpq.js:46718:12)
    at build (file:///Users/admin/repos/deno-kitchensink/new-vitepress/node_modules/.deno/vitepress@1.0.0-rc.40/node_modules/vitepress/dist/node/serve-e9-zRdpq.js:46622:21)
    at eventLoopTick (ext:core/01_core.js:59:7)
```

Also, in the `dev` mode (deno run -A npm:vitepress dev) I see Deno.stdin deprecation warnings now, but vitepress isn't a deno-specific package and i doubt it uses Deno.stdin.rid anywhere. @bartlomieju  any idea what's going on here?

```sh
➜ deno run -A npm:vitepress dev  

  vitepress v1.0.0-rc.40

  ➜  Local:   http://localhost:5173/
  ➜  Network: use --host to expose
  ➜  press h to show help
warning: Use of deprecated "Deno.stdin.rid" API. This API will be removed in Deno 2.

hint: Use `Deno.stdin` instance methods instead.

```

**Comment by birkskyum** [comment] 2024-03-09 08:32
@littledivy , when i run the build command now i see:

```sh
➜ deno run -A npm:vitepress build

  vitepress v1.0.0-rc.40

✓ building client + server bundles...
build error:
TypeError: Relative import path "vue/server-renderer" not prefixed with / or ./ or ../
    at file:///Users/admin/repos/deno-kitchensink/vitepress-working/.vitepress/.temp/app.js?t=1709973087929:2:161
    at async build (file:///Users/admin/repos/deno-kitchensink/vitepress-working/node_modules/.deno/vitepress@1.0.0-rc.40/node_modules/vitepress/dist/node/serve-e9-zRdpq.js:46644:24)
```

**Comment by birkskyum** [comment] 2024-03-09 16:28
Can this be re-opened?

**Comment by littledivy** [comment] 2024-03-10 02:54
Hmm, does it work using BYONM?

```jsonc
// deno.jsonc
{ unstable: ["byonm"] }
```

```
$ npm i vitepress
$ deno task docs:build
```

**Comment by birkskyum** [comment] 2024-03-10 11:10
Oh right, I missed that - where will these details for each framework be stored? Could there be a frameworks section somewhere in the [deno docs](https://docs.deno.com/runtime/tutorials/hello_world)?

It actually did fix build, but the preview break with this when I go to the localhost:

```sh
➜ deno task docs:preview
Task docs:preview vitepress preview

  vitepress v1.0.0-rc.45

Built site served at http://localhost:4173/
error: Uncaught (in promise) TypeError: Cannot set properties of undefined (setting 'statusCode')
    at Polka.onError (file:///Users/admin/repos/deno-kitchensink/vitepress-working/node_modules/.pnpm/vitepress@1.0.0-rc.45_@algolia+client-search@4.22.1_search-insights@2.13.0/node_modules/vitepress/dist/node/serve-CXeFQMGg.js:63027:24)
    at next (file:///Users/admin/repos/deno-kitchensink/vitepress-working/node_modules/.pnpm/vitepress@1.0.0-rc.45_@algolia+client-search@4.22.1_search-insights@2.13.0/node_modules/vitepress/dist/node/serve-CXeFQMGg.js:63103:38)
    at eventLoopTick (ext:core/01_core.js:208:9)
```

**Comment by littledivy** [comment] 2024-03-10 16:29
> where will these details for each framework be stored? Could there be a frameworks section somewhere in the [deno docs](https://docs.deno.com/runtime/tutorials/hello_world)?

We still need to figure out a good DX for this. Ideally the user wouldn't have to know about 'byonm'

**Comment by KnorpelSenf** [comment] 2024-04-05 09:27
IMO it would be great if Vitepress could be supported without a `node_modules` folder. Would this require any changes to Vitepress?

**Comment by marvinhagemeister** [comment] 2024-04-12 22:25
Tried to reproduce the issue again and it seems like the mentioned problems have been resolved. I'm now stuck on the following error:

```sh
TypeError: Relative import path "vue/server-renderer" not prefixed with / or ./ or ../
    at file:///<project>/.vitepress/.temp/app.js?t=1712960529044:2:161
    at async build (file:///<project>/node_modules/.deno/vitepress@1.1.0/node_modules/vitepress/dist/node/serve-Csn-CKFx.js:46758:24)
```

My assumption that this is caused by Deno applying node resolution only to files with `node_modules` somewhere in the parent path.

**Comment by littledivy** [comment] 2024-04-15 17:18
@marvinhagemeister It works with `npm i` with `DENO_FUTURE=1`. Removing the `node resolution` tag.

**Comment by littledivy** [comment] 2024-04-16 03:52
Closing, all functionality is working with DENO_FUTURE=1. DX will get better when `deno i` is added

```
$ deno run -A npm:vitepress init
$ npm i vitepress
$ export DENO_FUTURE=1

$ deno task docs:dev
$ deno task docs:build
$ deno task docs:preview
```

**Closed by littledivy** 2024-04-16 03:52 UTC
Labels: bug, node compat

**Comment by marvinhagemeister** [comment] 2024-08-06 19:13
@alexgleason Can you open a new issue for that? It sounds like the issue is different from what the original poster here ran into, even if both happened in the context of `vitepress`. Tracking issues separately makes it much easier for us to handle them.

**Comment by alexgleason** [comment] 2024-08-06 19:31
@marvinhagemeister I opened https://github.com/denoland/deno/issues/24916, just wanted to update this thread as well for posterity.

**Comment by marvinhagemeister** [comment] 2024-08-06 19:37
@alexgleason Sweet, thanks for opening a new issue. Instead of commenting on closed issues, you can link your issue to the old one by adding something in your text like:

```md
Relates to: <LINK TO THE ISSUE>
```

By putting a link to another issue in your issue GitHub will automatically create a shared connection that is visible from both issues. That's an easier way to update other issues without having to create new comments there.

**Comment by alexgleason** [comment] 2025-03-29 01:23
Since this is still the top Google result for "vitepress deno", I want to share the magic of how to get Vitepress working in Deno.

This is what deno.json should look like:

```json
{
  "tasks": {
    "dev": "deno run -A npm:vitepress dev",
    "build": "deno run -A npm:vitepress build",
    "preview": "deno run -A npm:vitepress preview"
  },
  "nodeModulesDir": "auto",
  "imports": {
    "vitepress": "npm:vitepress@^1.6.3",
    "vue": "npm:vue@^3.5.13"
  }
}
```

- `nodeModulesDir` should be set to `auto`
- `vue` must be present in deno.json (`deno add npm:vue`)
- `package.json` can be deleted

Without `vue` added as a dependency, this error will occur when running `deno task build`:

```
build error:
[vite]: Rollup failed to resolve import "vue/server-renderer" from "/home/alex/Projects/nostrify-docs/README.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
[vite]: Rollup failed to resolve import "vue/server-renderer" from "/home/alex/Projects/nostrify-docs/README.md".
This is most likely unintended because it can break your application at runtime.
If you do want to externalize this module explicitly add it to
`build.rollupOptions.external`
```
