### ISSUE TITLE
docker image for deno

### ISSUE THREAD

**Issue by nathanawmk** [denoland/deno#6041] opened 2020-06-02 08:28 UTC
Hello! any plans to make dockerize deno? If this is not done, I like to help. 

Nathan Aw (Singapore)

**Comment by lucacasonato** [comment] 2020-06-02 09:58
The best docker images for Deno are maintained by @hayd: https://github.com/hayd/deno-docker

Duplicate of #3356

**Comment by bartlomieju** [comment] 2020-06-07 12:20
Please continue in #3356

**Closed by bartlomieju** 2020-06-07 12:20 UTC
