### ISSUE TITLE
Deno Keeps Giving false Ouput Using `detect-port` Package

### ISSUE THREAD

**Issue by cj-1010-1414** [denoland/deno#25393] opened 2024-09-03 14:28 UTC
Version: Deno 1.46.2

I use `detect-port` package to check if some ports available. This is my simple file.
 
```
import detect from 'detect-port'

// memberikan fungsi
console.log(await detect(2431))
```
First I check if port `2431` is not used.

In Bun, it outputs `2431` meaning the port isn't used.

But Deno keeps giving different ports; meaning it's used. But it's actually not used.

**Comment by marvinhagemeister** [comment] 2024-09-03 14:35
yeah it's a duplicate of #25175

**Closed by marvinhagemeister** 2024-09-03 14:35 UTC

**Comment by marvinhagemeister** [comment] 2024-09-03 15:19
no need to apologies. It's always better to report issues and potentially close them as duplicates, compared to not reporting them.
