### ISSUE TITLE
Brew fails to compile and install 1.7.1 on High Sierra 

### ISSUE THREAD

**Issue by nodesocket** [denoland/deno#9404] opened 2021-02-04 21:09 UTC
Version `1.7.1` is failing to compile and install via **brew** on an older iMac. The iMac is running **macOS High Sierra**.

```
==> Installing deno
==> python build/gen.py
==> ninja -C out
==> cargo install -vv
Last 15 lines from /Users/justin/Library/Logs/Homebrew/deno/03.cargo:
[rusty_v8 0.16.0] See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
[rusty_v8 0.16.0] import("//build/config/mac/mac_sdk.gni")
[rusty_v8 0.16.0] ^--------------------------------------
[rusty_v8 0.16.0] See //BUILD.gn:4:1: which caused the file to be included.
[rusty_v8 0.16.0] static_library("rusty_v8") {
[rusty_v8 0.16.0] ^---------------------------
[rusty_v8 0.16.0] thread 'main' panicked at '
[rusty_v8 0.16.0] command did not execute successfully, got: exit code: 1
[rusty_v8 0.16.0]
[rusty_v8 0.16.0] build script failed, must exit now', /Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/cargo_gn-0.0.15/src/lib.rs:203:3
[rusty_v8 0.16.0] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `deno v1.7.1 (/private/tmp/deno-20210204-79091-yndwd1/deno/cli)`, intermediate artifacts can be found at `/private/tmp/deno-20210204-79091-yndwd1/deno/target`

Caused by:
  build failed

Do not report this issue to Homebrew/brew or Homebrew/core!
```

**Comment by kitsonk** [comment] 2021-02-04 22:38
cc/ @carlocab

**Comment by carlocab** [comment] 2021-02-04 22:41
Compiling `deno` isn't a fun time. My experience is just to keep trying till it works.

See

https://github.com/denoland/deno/issues/9244
https://github.com/Homebrew/homebrew-core/pull/66920
https://github.com/Homebrew/homebrew-core/pull/70018

**Comment by kitsonk** [comment] 2021-02-04 22:42
Thanks, closing as duplicate of #9244 then.

**Closed by kitsonk** 2021-02-04 22:42 UTC
Labels: external

**Comment by carlocab** [comment] 2021-02-04 22:44
However, if you can get `brew gist-logs` to work, you can share the logs here and I'll try to have a look at them.

**Comment by nodesocket** [comment] 2021-02-04 23:11
> Compiling `deno` isn't a fun time. My experience is just to keep trying till it works. Yes, it sometimes fails now and succeeds later (or vice-versa).
> 
> See
> 
> #9244
> [Homebrew/homebrew-core#66920](https://github.com/Homebrew/homebrew-core/pull/66920)
> [Homebrew/homebrew-core#70018](https://github.com/Homebrew/homebrew-core/pull/70018)

I have tried brew upgrading Deno multiple times _(maybe over 8 times)_ and everytime it fails.

**Comment by carlocab** [comment] 2021-02-04 23:14
Try looking at the logs. If it fails at a different point each time, then you're likely looking at the same problem.

**Comment by nodesocket** [comment] 2021-02-06 08:10
@crabmusket here are the logs from the most recent attempting building Deno version `1.7.2` on High Sierra. The following few lines seem to be the source the error/bug:

```
[rusty_v8 0.16.0]     raise Exception('No %s+ SDK found' % min_sdk_version)
[rusty_v8 0.16.0] Exception: No 10.15+ SDK found
```

Full logs:

```
Running `/private/tmp/deno-20210206-39871-7y24li/deno/target/release/build/rusty_v8-0222b9bb743e91bf/build-script-build`
[rusty_v8 0.16.0] clang_base_path /usr/local/opt/llvm
[rusty_v8 0.16.0] The current directory is /Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0
[rusty_v8 0.16.0] gn gen --root=/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0 /private/tmp/deno-20210206-39871-7y24li/deno/target/release/gn_out
[rusty_v8 0.16.0] running: "/private/tmp/deno-20210206-39871-7y24li/deno/gn/out/gn" "--root=/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0" "gen" "/private/tmp/deno-20210206-39871-7y24li/deno/target/release/gn_out" "--args=is_debug=false v8_enable_handle_zapping=false clang_base_path=\"/usr/local/opt/llvm\" treat_warnings_as_errors=false clang_use_chrome_plugins=false cc_wrapper=\"/usr/local/opt/sccache/bin/sccache\""
[rusty_v8 0.16.0] ERROR at //build/config/mac/mac_sdk.gni:107:7: Script returned non-zero exit code.
[rusty_v8 0.16.0]       exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
[rusty_v8 0.16.0]       ^----------
[rusty_v8 0.16.0] Current dir: /private/tmp/deno-20210206-39871-7y24li/deno/target/release/gn_out/
[rusty_v8 0.16.0] Command: python /Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.15
[rusty_v8 0.16.0] Returned 1.
[rusty_v8 0.16.0] stderr:
[rusty_v8 0.16.0]
[rusty_v8 0.16.0] Traceback (most recent call last):
[rusty_v8 0.16.0]   File "/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/mac/find_sdk.py", line 98, in <module>
[rusty_v8 0.16.0]     print(main())
[rusty_v8 0.16.0]   File "/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/mac/find_sdk.py", line 81, in main
[rusty_v8 0.16.0]     raise Exception('No %s+ SDK found' % min_sdk_version)
[rusty_v8 0.16.0] Exception: No 10.15+ SDK found
[rusty_v8 0.16.0]
[rusty_v8 0.16.0] See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
[rusty_v8 0.16.0] import("//build/config/mac/mac_sdk.gni")
[rusty_v8 0.16.0] ^--------------------------------------
[rusty_v8 0.16.0] See //BUILD.gn:4:1: which caused the file to be included.
[rusty_v8 0.16.0] static_library("rusty_v8") {
[rusty_v8 0.16.0] ^---------------------------
[rusty_v8 0.16.0] thread 'main' panicked at '
[rusty_v8 0.16.0] command did not execute successfully, got: exit code: 1
[rusty_v8 0.16.0]
[rusty_v8 0.16.0] build script failed, must exit now', /Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/cargo_gn-0.0.15/src/lib.rs:203:3
[rusty_v8 0.16.0] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to run custom build command for `rusty_v8 v0.16.0`

Caused by:
  process didn't exit successfully: `/private/tmp/deno-20210206-39871-7y24li/deno/target/release/build/rusty_v8-0222b9bb743e91bf/build-script-build` (exit code: 101)
  --- stdout
  clang_base_path /usr/local/opt/llvm
  The current directory is /Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0
  gn gen --root=/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0 /private/tmp/deno-20210206-39871-7y24li/deno/target/release/gn_out
  running: "/private/tmp/deno-20210206-39871-7y24li/deno/gn/out/gn" "--root=/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0" "gen" "/private/tmp/deno-20210206-39871-7y24li/deno/target/release/gn_out" "--args=is_debug=false v8_enable_handle_zapping=false clang_base_path=\"/usr/local/opt/llvm\" treat_warnings_as_errors=false clang_use_chrome_plugins=false cc_wrapper=\"/usr/local/opt/sccache/bin/sccache\""
  ERROR at //build/config/mac/mac_sdk.gni:107:7: Script returned non-zero exit code.
        exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
        ^----------
  Current dir: /private/tmp/deno-20210206-39871-7y24li/deno/target/release/gn_out/
  Command: python /Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.15
  Returned 1.
  stderr:

  Traceback (most recent call last):
    File "/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/mac/find_sdk.py", line 98, in <module>
      print(main())
    File "/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/mac/find_sdk.py", line 81, in main
      raise Exception('No %s+ SDK found' % min_sdk_version)
  Exception: No 10.15+ SDK found

  See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
  import("//build/config/mac/mac_sdk.gni")
  ^--------------------------------------
  See //BUILD.gn:4:1: which caused the file to be included.
  static_library("rusty_v8") {
  ^---------------------------

  --- stderr
  thread 'main' panicked at '
  command did not execute successfully, got: exit code: 1

  build script failed, must exit now', /Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/cargo_gn-0.0.15/src/lib.rs:203:3
  note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
warning: build failed, waiting for other jobs to finish...
[rusty_v8 0.16.0] ERROR at //build/config/mac/mac_sdk.gni:107:7: Script returned non-zero exit code.
[rusty_v8 0.16.0]       exec_script("//build/mac/find_sdk.py", find_sdk_args, "list lines")
[rusty_v8 0.16.0]       ^----------
[rusty_v8 0.16.0] Current dir: /private/tmp/deno-20210206-39871-7y24li/deno/target/release/gn_out/
[rusty_v8 0.16.0] Command: python /Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/mac/find_sdk.py --print_sdk_path --print_bin_path 10.15
[rusty_v8 0.16.0] Returned 1.
[rusty_v8 0.16.0] stderr:
[rusty_v8 0.16.0]
[rusty_v8 0.16.0] Traceback (most recent call last):
[rusty_v8 0.16.0]   File "/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/mac/find_sdk.py", line 98, in <module>
[rusty_v8 0.16.0]     print(main())
[rusty_v8 0.16.0]   File "/Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/rusty_v8-0.16.0/build/mac/find_sdk.py", line 81, in main
[rusty_v8 0.16.0]     raise Exception('No %s+ SDK found' % min_sdk_version)
[rusty_v8 0.16.0] Exception: No 10.15+ SDK found
[rusty_v8 0.16.0]
[rusty_v8 0.16.0] See //build/toolchain/mac/BUILD.gn:15:1: whence it was imported.
[rusty_v8 0.16.0] import("//build/config/mac/mac_sdk.gni")
[rusty_v8 0.16.0] ^--------------------------------------
[rusty_v8 0.16.0] See //BUILD.gn:4:1: which caused the file to be included.
[rusty_v8 0.16.0] static_library("rusty_v8") {
[rusty_v8 0.16.0] ^---------------------------
[rusty_v8 0.16.0] thread 'main' panicked at '
[rusty_v8 0.16.0] command did not execute successfully, got: exit code: 1
[rusty_v8 0.16.0]
[rusty_v8 0.16.0] build script failed, must exit now', /Users/justin/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/cargo_gn-0.0.15/src/lib.rs:203:3
[rusty_v8 0.16.0] note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
error: failed to compile `deno v1.7.2 (/private/tmp/deno-20210206-39871-7y24li/deno/cli)`, intermediate artifacts can be found at `/private/tmp/deno-20210206-39871-7y24li/deno/target`

Caused by:
  build failed

HOMEBREW_VERSION: 3.0.0
ORIGIN: https://github.com/Homebrew/brew
HEAD: ebc7cc36a0e029d58fac8cebd1b5ff583b3fd95b
```

**Comment by carlocab** [comment] 2021-02-06 11:25
I opened https://github.com/Homebrew/homebrew-core/pull/70576 to try to fix this for you.
