### ISSUE TITLE
Can not use `import.meta.resolve()` in REPL

### ISSUE THREAD

**Issue by lucacasonato** [denoland/deno#16948] opened 2022-12-05 10:44 UTC
```
> import.meta.resolve()
Uncaught SyntaxError: Cannot use 'import.meta' outside a module
```

We should probably transpile it, like import statements.

**Comment by bartlomieju** [comment] 2022-12-05 14:53
Duplicate of https://github.com/denoland/deno/issues/15720

**Closed by bartlomieju** 2022-12-05 14:53 UTC
Labels: repl, needs discussion
