### ISSUE TITLE
TypeScript 4.0 support in Deno

### ISSUE THREAD

**Issue by trivikr** [denoland/deno#7136] opened 2020-08-20 18:19 UTC
**Is your feature request related to a problem? Please describe.**
Not a problem, but support for TypeScript 4.0 would be good in Deno - especially to test forward compatibility for modules written in TS <=3.9 and come up with a release schedule for TypeScript updates in future versions of Deno.
* Typescript 4.0 is available on August 20th, 2020 https://devblogs.microsoft.com/typescript/announcing-typescript-4-0/
* Deno 1.3.0 supports typescript 3.9.7

	<details>
	<summary>Console output</summary>
	
	```console
	$ deno --version
	deno 1.3.0
	v8 8.6.334
	typescript 3.9.7
	```
	
	</details>

**Describe the solution you'd like**
Support TypeScript 4.0 in future minor version of Deno (say 1.4.0?)
A WIP PR was posted on Jun 26 https://github.com/denoland/deno/pull/6514, but deno_typescript was removed on Jul 19 in https://github.com/denoland/deno/pull/6813 as a follow-up to porting internal TS code to JS https://github.com/denoland/deno/pull/6793

**Describe alternatives you've considered**
Stick with TypeScript 3.9 in Deno in foreseeable future

**Comment by kitsonk** [comment] 2020-08-20 19:43
Duplicate of #6514 which I will be updating today.

**Closed** 2020-08-23 21:16 UTC
