### ISSUE TITLE
Dynamic import with Deno compile not work, ERROR: Module not found

### ISSUE THREAD

**Issue by keelii** [denoland/deno#24673] opened 2024-07-22 14:23 UTC
```
deno 1.45.2 (release, aarch64-apple-darwin)
v8 12.7.224.12
typescript 5.5.2
```

ERROR:

```
➜  test_deno cat test.ts
const filePath = "/Users/XXXX/repo/git.jd.com/fe-linter/eslint-custom.config.js"
await import(filePath);
➜  test_deno ls /Users/XXXX/repo/git.jd.com/fe-linter/eslint-custom.config.js           
/Users/XXXX/repo/git.jd.com/fe-linter/eslint-custom.config.js
➜  test_deno deno run -A test.ts                                          
➜  test_deno deno compile -A test.ts
Compile file:///Users/XXXX/test_deno/test.ts to test
Archive:  /var/folders/83/27zmq9fn1j1499db2z4pg_s80000gp/T/.tmpjYxNdw/denort.zip
  inflating: denort                  
➜  test_deno ./test 
error: Uncaught (in promise) TypeError: Module not found: file:///Users/XXXX/repo/git.jd.com/fe-linter/eslint-custom.config.js
await import(filePath);
^
    at async file:///var/folders/83/27zmq9fn1j1499db2z4pg_s80000gp/T/deno-compile-test/test_deno/test.ts:2:1

```

**Comment by dsherret** [comment] 2024-07-22 14:38
Can you provide a reproduction? Is this a duplicate of https://github.com/denoland/deno/issues/18327 ?

**Comment by keelii** [comment] 2024-07-22 23:45
> Can you provide a reproduction? Is this a duplicate of #18327 ?

@dsherret I seems like is a same issue.

```
➜  deno_test tree      
.
├── log.ts
└── test.ts
➜  deno_test cat log.ts      
console.log(1)
➜  deno_test cat test.ts 
const log = './log.ts';
await import(log);
➜  deno_test deno run ./test.ts  
1
➜  deno_test deno compile test.ts
Check file:///Users/XXX/deno_test/test.ts
Compile file:///Users/XXX/deno_test/test.ts to test
Archive:  /var/folders/56/18ks5nln0hd8h104twhl9tz80000gn/T/.tmpsDgz1q/denort.zip
  inflating: denort                  
➜  deno_test ./test 
error: Uncaught (in promise) TypeError: Module not found: file:///Users/XXX/deno_test/log.ts
await import(log);
^
    at async file:///Users/XXX/deno_test/test.ts:2:1
➜  deno_test 
```

Why it is ok on `deno run`, but not for `deno compile`?

**Comment by Mutefish0** [comment] 2024-07-23 05:15
try change
```
const log = './log.ts';
await import(log);
```
to:
```
await import('./log.ts');
```

docs:  https://docs.deno.com/runtime/manual/tools/compiler/#dynamic-imports

**Comment by keelii** [comment] 2024-07-23 05:18
> try change
> 
> ```
> const log = './log.ts';
> await import(log);
> ```
> 
> to:
> 
> ```
> await import('./log.ts');
> ```
> 
> docs: https://docs.deno.com/runtime/manual/tools/compiler/#dynamic-imports

@Mutefish0 I mean log is dynamic path.

**Comment by dsherret** [comment] 2024-07-23 23:54
> Why it is ok on deno run, but not for deno compile?

It's a techincal challenge that hasn't been implemented.

**Closed by dsherret** 2024-07-23 23:54 UTC
Labels: duplicate
