### ISSUE TITLE
Error parsing javascript object to serde_json::Value

### ISSUE THREAD

**Issue by augustocdias** [denoland/deno#11502] opened 2021-07-23 13:43 UTC
I'm using deno embedded in a rust application and we're facing an issue with the `serde_v8` with some objects. 

At some point in our script we call `await Deno.core.opAsync('success', message);`

This `message` on the script side is an object, such as:

```javascript
{
    lines: {
        100: {
           unit: "m"
        },
        200: {
           unit: "cm"
        }
    }
}
```
On the rust side, my `success` function expects a `serde_json::Value` object. This is failing to be serialised back to rust because it cannot handle the numbers as keys. Shouldn't deno convert them to string in this case?

Even if I set the object like this:

```javascript 
{
    lines: {
        "100": {
           unit: "m"
        },
        "200": {
           unit: "cm"
        }
    }
}
```

deno still treats it as a number and fails to parse it.

**Comment by bnoordhuis** [comment] 2021-07-27 07:47
@AaronO pointed out it's caused by rusty_v8's `Object::get_own_property_names()` using `KeyConversionMode::kKeepNumbers` (default inherited from V8's C++ API), whereas for this particular case you'd want `kConvertToString` or `kNoNumbers`.

To summarize: needs a change in rusty_v8 before it can be fixed in deno.

**Comment by bnoordhuis** [comment] 2021-07-28 11:12
I've opened https://github.com/denoland/rusty_v8/issues/740 to track the necessary changes to rusty_v8.

**Comment by RaisinTen** [comment] 2022-09-18 15:18
And finally, here's the PR that fixes the issue - https://github.com/denoland/deno/pull/15946! :)

**Closed** 2022-10-02 20:18 UTC
Labels: bug, core, upstream
