### ISSUE TITLE
Wrong typings for connection address in http request

### ISSUE THREAD

**Issue by PatrykMiszczak** [denoland/deno#5466] opened 2020-05-15 17:31 UTC
## Steps to reproduce
For the example code:
```ts
import { serve } from "https://deno.land/std@0.50.0/http/server.ts";

const server = serve({ port: 8000 });

console.log("Started");

for await (const req of server) {
    const peerHost: string = req.conn.remoteAddr.hostname;

    console.log(`Host ${peerHost} connected`);

    req.respond({});
}
```

I get:
```
error: TS2339 [ERROR]: Property 'hostname' does not exist on type 'Addr'.
  Property 'hostname' does not exist on type 'UnixAddr'.
    const peerHost: string = req.conn.remoteAddr.hostname;
```

When I replace `req.conn.remoteAddr.hostname` with `(req.conn.remoteAddr as Deno.NetAddr).hostname` everything works as expected:
```
Started
Host 127.0.0.1 connected
```

The full `remoteAddr` looks similar to `{ hostname: "127.0.0.1", port: 64859, transport: "tcp" }`

## Version
```
$ deno --version
deno 1.0.0
v8 8.4.300
typescript 3.9.2
```

**Comment by xReveres** [comment] 2020-05-15 21:14
I also solved it by doing like this:
```typescript
const remote = JSON.parse(JSON.stringify(req.conn.remoteAddr));
console.log(remote.hostname, remote.port, remote.transport);
```
It is bugged like groups in regex match I guess

**Comment by SyrupThinker** [comment] 2020-05-15 22:33
Your error is a duplicate of #5102, check [this comment](https://github.com/denoland/deno/issues/5102#issuecomment-624716274); it applies to the `hostname` field aswell.

Your cast `(req.conn.remoteAddr as Deno.NetAddr).hostname` is an expected solution because you know contextually that it is a `Deno.NetAddr`.

**Comment by bartlomieju** [comment] 2020-05-21 11:39
@SyrupThinker's response is a proper solution

**Closed by bartlomieju** 2020-05-21 11:39 UTC
