### ISSUE TITLE
suggestion: `deno check` checks all code and markdown files by default

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#20278] opened 2023-08-25 01:17 UTC
I suggest that `deno check` checks all code and markdown files by default. `deno fmt` and `deno lint` do this. `deno check` behaves differently by requiring that a file list be provided. As a result, solutions like [this](https://github.com/denoland/fresh/blob/fb6d11747b0f0e17af0e43be2331db35946c6900/deno.json#L8) and [this](https://github.com/denoland/deno_kv_oauth/blob/f05688dee73108ec49db6036b97e2a17b7dd876d/deno.json#L8), are being done.

**Comment by lino-levan** [comment] 2023-08-25 15:55
Completely agree. I have found the current behavior confusing in the past.

**Comment by lucacasonato** [comment] 2023-10-11 02:32
Closing as dupe of https://github.com/denoland/deno/issues/20813 (has more discussion)

**Closed by lucacasonato** 2023-10-11 02:32 UTC
