### ISSUE TITLE
Files deno.json and jsr.json are not complementary

### ISSUE THREAD

**Issue by oscarotero** [denoland/deno#24210] opened 2024-06-14 15:09 UTC
Version: Deno 1.44.2

From [Discord](https://discord.com/channels/684898665143206084/1203185670508515399/1251122843903725700)

I have a project with two files: `deno.json` and `jsr.json`.

The idea is to have `deno.json` for runtime configuration and `jsr.json` for publishing. But it seems that Deno only can read one file. If I run `deno publish` I have the error 

```
error: .../deno.json is missing 'name' field
```
because it only read `deno.json`. But running `deno publish --config=jsr.json` the `imports` defined in `deno.json` don't work because this file is not loaded.

It seems that there isn't distinction between deno configuration and jsr configuration. Both configuration options must be in the same file, no matter its name. I was hoping for something similar to import maps: they can be defined in deno.json or in a different file without conflicts.

**Comment by thesmart** [comment] 2024-06-15 19:52
Maybe you thought of this already, but could you segment your source so that one folder is the module and the root is the runtime? That way, you can publish the module using `jsr.json` and your runtime can use it.

**Comment by lucacasonato** [comment] 2024-06-17 05:41
Duplicate of #22651

**Closed by lucacasonato** 2024-06-17 05:41 UTC
Labels: bug, cli, jsr
