### ISSUE TITLE
Bug exposed after bundle patch

### ISSUE THREAD

**Issue by ry** [denoland/deno#6341] opened 2020-06-17 17:21 UTC
https://github.com/denoland/deno/commit/75bb9dbdfc7f8b4e8d17978808ae575e61843aef has exposed some sort of internal bug. CI is reliably red. We're occasionally able to repeat locally.

Two different failure modes: segfault and panic in `get_backing_store_slice()`

Sometimes able to repeat like this:
```
../../target/debug/deno run --quiet --reload -Ldebug --allow-net 053_import_compression/main.ts
gzip
brotli
[1]    83000 segmentation fault  ../../target/debug/deno run --quiet --reload -Ldebug --allow-net
```

**Comment by kitsonk** [comment] 2020-06-17 20:30
Hmmmm... crazy.  There were a couple changes to the `system_loader.js` which is shared between the runtime bundles and the Deno bundles, which I guess in theory could impact the behaviour of the snapshots.

First was to use a `Object.create(null)` as the cache for modules instead of `Map()`.  This was because this helped ensured that when things were transpiled, it would work in ES5, it was the only functional structure we didn't support.  This could be impacting GC in some way though.

Second was that there was a bit of redundant code, and realised that we didn't actually need `__instantiate()` and `__instantiateAsync()` as neither needed to be async functions, they simply passed through a return value, so all was needed was an argument and branching in the code.  This eliminated like 8 lines of code from the bundler.

I can just revert the changes to `system_loader.js` to see if that is the cause, it seems crazy if it is, but then again it seems crazy that the PR had an impact anyways, as it does seem to have exposed some other bug that is going to be crazy to try to isolate.

**Comment by ry** [comment] 2020-06-18 02:26
@kitsonk We’re unable to repeat it outside of CI - so it’s not clear what’s happening - but my suspicion is that this patch just happens to be calling ops with the exact size to induce some off-by-one error in shared_queue. It may be that changing the patch makes things go green but doesn’t solve the underlying bug. We really need to understand what is causing these failures. Unfortunately to do that I really need to be able to reproduce it locally.

**Comment by bartlomieju** [comment] 2020-11-09 17:52
@ry I don't think we have a reliable way to reproduce this bug, wanna keep the issue open?

**Comment by kitsonk** [comment] 2020-11-09 19:45
Well and bundling was totally rewritten.

**Comment by kitsonk** [comment] 2020-11-09 22:17
I am going to close this, since the code that changed which exposed the problem is no longer in the codebase.

**Closed by kitsonk** 2020-11-09 22:17 UTC
Labels: cli :computer:, core :gear:
