### ISSUE TITLE
Cannot unref() node http2 connections

### ISSUE THREAD

**Issue by yzalium** [denoland/deno#16647] opened 2022-11-15 10:13 UTC
Deno 1.28.0

While using npm compatibility, one of my dependencies establishes a http2 connection, and then tries to close the session calling `session.unref()`, which causes the following error 

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'unref')
    at Subchannel.createSession (file:///Users/yzalium/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.7.3/build/src/subchannel.js:413:17)
    at file:///Users/yzalium/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.7.3/build/src/subchannel.js:502:18
    at Object.runMicrotasks (deno:core/01_core.js:377:30)
    at processTicksAndRejections (https://deno.land/std@0.164.0/node/_next_tick.ts:62:10)
```

This happens using the Cerbos package like so:

```typescript
import { GRPC } from 'npm:@cerbos/grpc';

const client = new GRPC('localhost:3592', { tls: false })
const result = await client.checkResource({/* */})
client.close();
```
```
deno run --allow-env --allow-net --allow-write=. --allow-read=. main.ts
```
I've checked, and it doesn't seem like neither Cerbos nor its grpc dependency has postinstall scripts.

Thank you.

**Comment by spalberg** [comment] 2022-12-12 09:00
I get the same exception when using [zeebe-node](https://www.npmjs.com/package/zeebe-node) which also establishes a grpc-connection.

Since we are in the process of deciding to use either Deno or NodeJS for script and CLI application development and we need such libraries, it would be good to know if GRPC should actually work with Deno via NPM packages and this is just a bug, or if Deno generally does not support GRPC via HTTP2 in NPM packages.

**Comment by c0per** [comment] 2023-01-02 08:01
Deno 1.29.1

Same exception using `@grpc/grpc-js`

**Comment by bartlomieju** [comment] 2023-01-02 23:25
@kt3k could you take a look at this issue?

**Comment by nubunto** [comment] 2023-04-21 03:46
ran into this issue using Temporal SDK for TypeScript:

```
error: Uncaught TypeError: Cannot read properties of undefined (reading 'unref')
    at Subchannel.createSession (file:///Users/nubunto/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.7.3/build/src/subchannel.js:413:17)
    at file:///Users/nubunto/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.7.3/build/src/subchannel.js:502:18
    at eventLoopTick (ext:core/01_core.js:172:13)
```

Was able to reproduce with grpc-js as well:

```
✦ ❯ deno run grpcjs.ts
✅ Granted read access to "foo.proto".
error: Uncaught TypeError: Cannot read properties of undefined (reading 'setTimeout')
    at setupServer (file:///Users/nubunto/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.8.14/build/src/server.js:269:25)
    at file:///Users/nubunto/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.8.14/build/src/server.js:289:37
    at Array.map (<anonymous>)
    at bindSpecificPort (file:///Users/nubunto/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.8.14/build/src/server.js:277:44)
    at Object.onSuccessfulResolution (file:///Users/nubunto/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.8.14/build/src/server.js:419:45)
    at Timeout._onTimeout (file:///Users/nubunto/Library/Caches/deno/npm/registry.npmjs.org/@grpc/grpc-js/1.8.14/build/src/resolver-dns.js:128:31)
    at cb (ext:deno_node/internal/timers.mjs:37:46)
    at Object.action (ext:deno_web/02_timers.js:147:11)
    at handleTimerMacrotask (ext:deno_web/02_timers.js:64:10)
    at eventLoopTick (ext:core/01_core.js:171:21)
```

Seems like an issue when loading Node's `http2` package?

**Comment by NfNitLoop** [comment] 2023-07-07 18:56
Ran into this issue as well with Deno 1.35, when trying to use Google's SecretManagerService, which uses gRPC and so needs http/2 support:

```
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.unref
Warning: Not implemented: Http2Session.ref
error: Uncaught TypeError: error sending request for url (http://secretmanager.googleapis.com:443/google.cloud.secretmanager.v1.SecretManagerService/GetSecret): connection error: Connection reset by peer (os error 54)
    at async mainFetch (ext:deno_fetch/26_fetch.js:266:12)
    at async fetch (ext:deno_fetch/26_fetch.js:490:7)
    at async node:http2:144:28
```

Steps to reproduce:

Unfortunately, you have to have valid gcloud credentials locally, else we fail before even making a connection:
* install gcloud CLI
* `gcloud auth application-default login`

```typescript
import {SecretManagerServiceClient as Client} from "npm:@google-cloud/secret-manager"

const client = new Client({ projectId: "my-project"})
const secret = await client.getSecret({name: "my-secret"})
```

**Comment by oleggromov** [comment] 2023-07-31 01:51
Having the same issue here as @NfNitLoop

**Comment by bartlomieju** [comment] 2023-07-31 09:55
I am currently working on improving support for `node:http2` module specifically to support `@google-cloud` package.

**Comment by jotacamou** [comment] 2023-08-17 18:15
Just for the sake of reporting, I'm also experiencing the same issue with Deno v1.36.1

**Comment by cesumilo** [comment] 2023-09-04 15:41
Same here, experiencing the issue with `@google-cloud/pubsub`, I hope it will be fixed soon 🙏

**Closed** 2023-10-12 14:03 UTC
Labels: bug, node compat

**Comment by samrocksc** [comment] 2023-12-21 08:44
Just checked this morning with 1.39:

- Google Pub/Sub => same issue
- Google Secret Manager => same issue

**Comment by mpcref** [comment] 2024-09-15 13:52
Same issue here:

```sh
✗ deno run -A npm:trigger.dev@beta login

Trigger.dev (3.0.0-beta.56)

T  Logging in to Trigger.dev
|
o  Created authorization code
|
o  Please visit the following URL to login:
|  https://cloud.trigger.dev/account/authorization-code/Ws6oxuBRDovT7O0m4c1rzz_Gmb-6Zomzm7hGtqnYdQqkuFK3Lvsi62VLnamWi4bC
X Error: Cannot read properties of undefined (reading 'unref')
```
