### ISSUE TITLE
Warning: Not implemented: ClientRequest.options.createConnection

### ISSUE THREAD

**Issue by sandersemmel** [denoland/deno#26478] opened 2024-10-22 19:07 UTC
Version: Deno 2.0.1

main.ts
```
import puppeteer from 'puppeteer';

console.log("Starting..")
// Launch the browser and open a new blank page
const browser = await puppeteer.launch({
    executablePath: '/Applications/Chromium.app/Contents/MacOS/Chromium'
});
const page = await browser.newPage();
console.log("Ending..")
```

deno.json
```
{
  "imports": {
    "puppeteer": "npm:puppeteer"
  }
}
```

deno --allow-all main.ts                                                                  
```
Starting..
Warning: Not implemented: ClientRequest.options.createConnection
```

I have tried with Chromium browser which was installed with:

brew install --cask Chromium

I have tried with Google Chrome browser was was installed with:

brew install --cask google-chrome

In both cases the application just hangs after starting with the warning message.

**Comment by sandersemmel** [comment] 2024-10-22 19:14
The warning was actually just a message. It was just running in headless mode and I thought it was erroring.

After adding these everything seems to work:

```
const browser = await puppeteer.launch({
    headless: false,
    executablePath: '/Applications/Chromium.app/Contents/MacOS/Chromium'
});
const page = await browser.newPage();
await page.goto('https://developer.chrome.com/');
```

**Comment by sandersemmel** [comment] 2024-10-22 19:31
Maybe related to this?
https://github.com/denoland/deno/pull/25470

**Comment by bartlomieju** [comment] 2024-10-22 20:32
It's a duplicate of https://github.com/denoland/deno/issues/19507, let's continue there. And yes, the above PR should fix the problem.

**Closed by bartlomieju** 2024-10-22 20:32 UTC
