### ISSUE TITLE
fmt: sort imports grouped by local / external and alphabetical

### ISSUE THREAD

**Issue by KotlinIsland** [denoland/deno#9740] opened 2021-03-09 23:28 UTC
```ts
import { x, y } from "./alphabet.ts"
import { foo, bar } from "std/foo/bar.ts"
import { z } from "./blah.ts"
```
imo would look better as
```ts
import { x, y } from "./alphabet.ts"
import { z } from "./blah.ts"
import { foo, bar } from "std/foo/bar.ts"
```

**Comment by Soremwar** [comment] 2021-03-09 23:32
Imports can have secondary effects, so import order can have an actual reason to be as it is, not just a stylistic one.

I believe this was already discussed in another issue

**Comment by kitsonk** [comment] 2021-03-10 02:40
Duplicate of #8551

**Closed by kitsonk** 2021-03-10 02:40 UTC
Labels: duplicate
