### ISSUE TITLE
Deno repl crashes with OOM in 1.32.2

### ISSUE THREAD

**Issue by kennethvikse** [denoland/deno#18780] opened 2023-04-20 09:53 UTC
Can deno be installed? I experienced issues installing. No response in original post @deno_install.

**Comment by bartlomieju** [comment] 2023-04-20 09:58
What's the issue?

**Comment by dsherret** [comment] 2023-04-20 14:09
Issue: https://github.com/denoland/deno_install/issues/259

Duplicate of https://github.com/denoland/deno/issues/18648#issuecomment-1501228408

**Closed by dsherret** 2023-04-20 14:09 UTC
Labels: duplicate
