### ISSUE TITLE
Error.cause works when logging but not when throwing in a file

### ISSUE THREAD

**Issue by GJZwiers** [denoland/deno#12712] opened 2021-11-09 19:28 UTC
If I use the new `cause` property and throw an Error in a `.ts` file it doesn't show the expected output when using `deno run`

code:
```
throw new Error("main error", { cause: new TypeError("caused by this") });
```

expected:
```
Uncaught Error: main error
    at <anonymous>:2:7
Caused by TypeError: caused by this
    at <anonymous>:3:12
```

actual:
```
error: Uncaught Error: main error
throw new Error("main error", { cause: new TypeError("caused by this") });
      ^
    at file:///path/to/my/file.ts:1:7
```

It does work if I `console.log` the error or if I `throw` one using the REPL though.

```
deno --version

deno 1.16.0 (release, x86_64-unknown-linux-gnu)
v8 9.7.106.2
typescript 4.4.2
```

**Comment by petamoriken** [comment] 2021-11-09 19:47
duplicate: https://github.com/denoland/deno/issues/12308

**Comment by lucacasonato** [comment] 2021-11-09 19:48
Closing as duplicate of #12308

**Closed by lucacasonato** 2021-11-09 19:48 UTC
