### ISSUE TITLE
Failed to get directory listing

### ISSUE THREAD

**Issue by fauzan121002** [denoland/deno#6936] opened 2020-08-01 14:56 UTC
Got an error (403) while querying the GitHub API: {"message":"API rate limit exceeded for 180.253.11.147. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)","documentation_url":"https://developer.github.com/v3/#rate-limiting"}

it gots me this url https://deno.land/x/accepts

**Comment by nayeemrmn** [comment] 2020-08-01 15:10
Duplicate of https://github.com/denoland/deno_website2/issues/433.

**Comment by lucacasonato** [comment] 2020-08-01 15:16
Should be fixed in the coming week.

**Closed** 2020-08-01 15:16 UTC

**Comment by fauzan121002** [comment] 2020-08-03 03:38
> Should be fixed in the coming week.

Thanks!!
