### ISSUE TITLE
React v17 JSX Transform

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#7993] opened 2020-10-15 20:42 UTC
React introduces a new JSX transform that is supported in TypeScript 4.1: https://devblogs.microsoft.com/typescript/announcing-typescript-4-1-beta/#jsx-factories

We should consider the impact of this on Deno and specifically `--no-check`.

**Comment by kitsonk** [comment] 2020-10-15 20:46
Ref: https://github.com/swc-project/swc/issues/1103

**Comment by lucacasonato** [comment] 2021-02-03 00:06
Duplicate of #8440 (closing this because the other issue is more active).

**Closed by lucacasonato** 2021-02-03 00:06 UTC
Labels: cli, feat

**Comment by kitsonk** [comment] 2021-02-03 03:35
🤦
