### ISSUE TITLE
Support auto-accessors

### ISSUE THREAD

**Issue by duncanmak** [denoland/deno#22173] opened 2024-01-29 18:32 UTC
Version: Deno 1.40.2

I'm trying to use Deno as my complete toolchain for writing a component using Lit. I'm trying out the new Stage 3 decorators.

When I compile using `"experimentalDecorators": false`, the `accessor` properties stay in the generated code, instead of being down-leveled.

For code like this,

```javascript
@property()
accessor name = "World";

@property({ type: Number })
accessor count = 0;
```

tsc can generate output like this:
```js
    get name() {
      return __classPrivateFieldGet(this, _MyElement_name_accessor_storage, "f");
    }
    set name(value) {
      __classPrivateFieldSet(this, _MyElement_name_accessor_storage, value, "f");
    }
    get count() {
      return __classPrivateFieldGet(this, _MyElement_count_accessor_storage, "f");
    }
    set count(value) {
      __classPrivateFieldSet(this, _MyElement_count_accessor_storage, value, "f");
    }

```

I'm using this `tsconfig.json` in tsc 5.3.3:

```json
"compilerOptions": {
    "target": "ES6",
    "experimentalDecorators": false,
    "useDefineForClassFields": true,
    "forceConsistentCasingInFileNames": true,
    "strict": true,
    "module": "esnext",
    "moduleResolution": "Bundler",
    "esModuleInterop": true,
    "verbatimModuleSyntax": true,
    "sourceMap": true,
  },
```

**Comment by bartlomieju** [comment] 2024-01-29 20:21
Could you please provide the full example file?

**Comment by duncanmak** [comment] 2024-01-31 02:00
Here's the sample file I'm using: https://gist.github.com/duncanmak/a4b1f65001658fb1509a99e44213d1cf

**Comment by bartlomieju** [comment] 2024-02-06 02:20
@duncanmak how are you running this gist?

When I do `deno run elements.ts` I get:
```
error: Uncaught (in promise) ReferenceError: HTMLElement is not defined
    at https://esm.sh/v135/@lit/reactive-element@2.0.2/denonext/reactive-element.mjs:2:973
```

Any chance you could provide a self-contained reproducible example? This seems like a nasty bug that needs to be squashed.

**Comment by nberlette** [comment] 2024-02-06 02:57
@bartlomieju since it's a Lit component it's expecting DOM APIs to be present that Deno doesn't implement natively. The only time I've seen Lit playing nice with Deno is [with vite as a bundler](https://github.com/bluwy/create-vite-extra/tree/master/template-deno-lit-ts)...

@duncanmak If you could please provide some insight on what exactly your toolchain consists of, it would really help. I'm specifically interested in what exactly your target platform / bundler / dev environment are looking like. Until then, it's a little hard to diagnose.

**Comment by duncanmak** [comment] 2024-02-07 21:26
I made my test repo available here: https://github.com/duncanmak/deno-lit-sandbox/tree/deno.

I started off using https://eisenbergeffect.medium.com/an-esbuild-setup-for-typescript-3b24852479fe as a base, and that version is on the `main` branch.

On the `deno` branch, I have my own implementation of these ideas using Deno. You can start it via `deno task serve`.

**Comment by lucacasonato** [comment] 2024-06-18 14:50
I can not reproduce this:

![image](https://github.com/denoland/deno/assets/7829205/f79554a3-e706-4287-bf16-73f75a3a86d6)


Please provide a reproduction of something that fails when running in Deno

**Comment by lucacasonato** [comment] 2024-07-31 18:05
Closing as working as intended, because OP has not provided more info.

Please open an other issue if you think this is still broken.

**Closed by lucacasonato** 2024-07-31 18:05 UTC
Labels: needs info

**Comment by nberlette** [comment] 2024-08-01 02:44
@lucacasonato this was fixed when the upstream fixes landed in swc if I'm not mistaken. I tried it as well and it seems to work fine. Sorry for commenting post close. ✌🏻
