### ISSUE TITLE
panic on `WebAssembly.instantiateStreaming`

### ISSUE THREAD

**Issue by lilnasy** [denoland/deno#18995] opened 2023-05-05 00:10 UTC
![Screenshot (141)](https://user-images.githubusercontent.com/69170106/236354909-b46917ed-298a-4792-90b1-8faa254a8ed3.png)
### Chrome devtools
![Screenshot (142)](https://user-images.githubusercontent.com/69170106/236355267-3f89d7e8-0bdb-4f9b-bb19-76c94868b628.png)

### Reproduction
```ts
const response = await fetch('https://deno.land/x/dax@0.31.1/src/lib/rs_lib_bg.wasm')
const instance = WebAssembly.instantiateStreaming(response)
```

**Comment by aapoalas** [comment] 2023-05-06 18:26
Duplicate of https://github.com/denoland/deno/issues/18571

**Closed** 2023-05-06 18:26 UTC

**Comment by aapoalas** [comment] 2023-05-06 18:27
Note that for getting a proper instance you should await the `WebAssembly.instantiateStreaming(response)`: This will fix the panic.
