### ISSUE TITLE
thread 'main' panicked at 'Cached source file doesn't exist'

### ISSUE THREAD

**Issue by xReveres** [denoland/deno#8265] opened 2020-11-06 10:48 UTC
After changes in my code, deno panics every time.
Full log:
```
thread 'main' panicked at 'Cached source file doesn't exist', cli/program_state.rs:206:8
stack backtrace:
   0:     0x55a1a896ad83 - std::backtrace_rs::backtrace::libunwind::trace::h577ea05e9ca4629a
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/libunwind.rs:96
   1:     0x55a1a896ad83 - std::backtrace_rs::backtrace::trace_unsynchronized::h50b9b72b84c7dd56
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/../../backtrace/src/backtrace/mod.rs:66
   2:     0x55a1a896ad83 - std::sys_common::backtrace::_print_fmt::h6541cf9823837fac
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:79
   3:     0x55a1a896ad83 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf64fbff071026df5
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:58
   4:     0x55a1a86001ac - core::fmt::write::h9ddafa4860d8adff
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/fmt/mod.rs:1082
   5:     0x55a1a896a5b6 - std::io::Write::write_fmt::h1d2ee292d2b65481
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/io/mod.rs:1514
   6:     0x55a1a8969f40 - std::sys_common::backtrace::_print::ha25f9ff5080d886d
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:61
   7:     0x55a1a8969f40 - std::sys_common::backtrace::print::h213e8aa8dc5405c0
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:48
   8:     0x55a1a8969f40 - std::panicking::default_hook::{{closure}}::h6482fae49ef9d963
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:200
   9:     0x55a1a8969638 - std::panicking::default_hook::he30ad7589e0970f9
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:219
  10:     0x55a1a8969638 - std::panicking::rust_panic_with_hook::haa1ed36ada4ffb03
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:569
  11:     0x55a1a89692d8 - std::panicking::begin_panic_handler::{{closure}}::h7001af1bb21aeaeb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:476
  12:     0x55a1a89692a4 - std::sys_common::backtrace::__rust_end_short_backtrace::h39910f557f5f2367
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/sys_common/backtrace.rs:153
  13:     0x55a1a896925d - rust_begin_unwind
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/std/src/panicking.rs:475
  14:     0x55a1a85fd880 - core::panicking::panic_fmt::h4e2659771ebc78eb
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/panicking.rs:85
  15:     0x55a1a86048c2 - core::option::expect_failed::hd5a1da3a6b6bbb34
                               at /rustc/18bf6b4f01a6feaf7259ba7cdae58031af1b7b39/library/core/src/option.rs:1213
  16:     0x55a1a8444c63 - core::option::Option<T>::expect::hb09dbc765aa5ae29
  17:     0x55a1a84ba4a4 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hdde66c28789f890e
  18:     0x55a1a8615e08 - <core::pin::Pin<P> as core::future::future::Future>::poll::hdcc7cb1733f8f646
  19:     0x55a1a8615603 - <deno_core::modules::RecursiveModuleLoad as futures_core::stream::Stream>::poll_next::he006242bd12754af
  20:     0x55a1a84b5264 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h9b3f326a1b645f86
  21:     0x55a1a84b7d8b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::hc92eb54ac15f0a05
  22:     0x55a1a85a29ad - deno::run_command::{{closure}}::h2731d1858f4ccaf6
  23:     0x55a1a84b409b - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h84023c1f02b7ced5
  24:     0x55a1a8477192 - tokio::runtime::Runtime::block_on::h7148315b848bf24b
  25:     0x55a1a85ac551 - deno::main::hfcf455f2df1a44ec
  26:     0x55a1a8414495 - std::sys_common::backtrace::__rust_begin_short_backtrace::hcc04b8b81d5e1708
  27:     0x55a1a85b3494 - main
  28:     0x7f505d635b97 - __libc_start_main
  29:     0x55a1a838333a - _start
  30:                0x0 - <unknown>
```
Deno version:
```
deno 1.5.1
v8 8.7.220.3
typescript 4.0.3
```
I tried restore changes but again the same errors.
Also I tried `deno cache -r --unstable -c tsconfig.json startup.t` but still panic.
In last case I resolved my problem by downgrading deno to version 1.5.0 then run my application and OK without errors.
Again I upgraded to latest version and OK without errors.

**Comment by bartlomieju** [comment] 2020-11-06 11:04
CC @kitsonk

**Comment by kitsonk** [comment] 2020-11-06 11:34
Need more details of how to reproduce this.  It is really hard to guess at what might be in `startup.t`.

**Comment by lucacasonato** [comment] 2020-11-07 09:57
Possible duplicate of: https://github.com/denoland/deno/issues/8279

Can you try delete your $DENO_DIR. You can find the location of the deno dir by running `deno info`. Then try delete the entire deno dir folder.

**Comment by xReveres** [comment] 2020-11-07 12:58
@lucacasonato As I wrote, I fixed issue by downgrading and then upgrading Deno version. Also I tried to recreate the problem but I can't.

**Comment by kitsonk** [comment] 2020-11-07 20:03
Closing until it can be reproduced.

**Closed by kitsonk** 2020-11-07 20:03 UTC
Labels: needs info :information_source::grey_question:
