### ISSUE TITLE
Deno should not import remote files without --allow-net flag

### ISSUE THREAD

**Issue by hisorange** [denoland/deno#1301] opened 2018-12-10 12:21 UTC
Just experimenting with deno so please excuse my instant misbehave.

But isn't the `--allow-net` flag's purpose is to encapsuate the process from the network and not let the script access the network without permission?

If this is the case, then we should block imports/require from calling remote urls.

This small [snippet](https://gist.github.com/hisorange/83a22f60c3e6928c497402c59bbb7736) allowed me to read and send my secret without net access.

As I seen the `--allow-read` will block me from reading the filesystem but still the netwoking is available with crafted imports.

**Comment by bartlomieju** [comment] 2018-12-10 12:33
`--allow-new` flag is used to **allow** Deno to make network requests.

Imports are implicitly allowed and cached in `DENO_DIR` for subsequent requests.

**Comment by hisorange** [comment] 2018-12-10 12:40
Wrongly worded title, but my main concern is simple, I can craft new import urls with secrets hidden in them and respond dummy ts codes without `--allow-net` flag.

**Comment by ry** [comment] 2018-12-10 16:45
Yes, this is a bug. Dynamic import should not be allowed unless --allow-net is specified.

I'm in the process of refactoring how dynamic import works (#975) and will add this constraint in the new implementation.

Duplicate of https://github.com/denoland/deno/issues/712 - let's move the discussion there.

**Closed by ry** 2018-12-10 16:45 UTC
