### ISSUE TITLE
Add `deno uninstall` to install modules

### ISSUE THREAD

**Issue by KanseiKy** [denoland/deno#11136] opened 2021-06-26 05:13 UTC
Similar to how `npm uninstall` works, I would like this feature to be added. You can pass the full URL used during the installation. Examples:
```sh
$ deno uninstall https://deno.land/std/node/module.ts # Uninstall via URL
$ deno un https://deno.land/std/path/mod.ts           # Shorthand for `uninstall`
```
This way, we can uninstall modules faster rather than browsing the `~/.deno/bin` directory and uninstall the desired module

**Comment by crowlKats** [comment] 2021-06-26 05:27
Duplicate of #3139

**Closed** 2021-06-26 07:26 UTC
