### ISSUE TITLE
Support for Modern Web API's, dev tool protocol, serial/I2C,USB,BLE, ETC

### ISSUE THREAD

**Issue by HansUXdev** [denoland/deno#6210] opened 2020-06-09 18:09 UTC
Part of what made node.js take off so much wasn't the http server,  but rather, the runtime's ability to allow developers to use JS to write a server, mobile app, and even hardware. 

In that same spirit, wouldn't it be advantageous to add direct support for serial, usb, ble, etc?

Also if the goal is to make it more "web like" or webby,  adding support for modern [web API's](https://developer.mozilla.org/en-US/docs/Web/API) like #5954 mentions could be really help this.

There are also other API's beyond Serial API and the Native File System API, that could definitely help bring native-like app and hardware development to deno such as:

Browser Debugging:
- [Dev Tool Protocol](https://chromedevtools.github.io/devtools-protocol/)
- Would adding out of the box support for this drastically aid debugging between the server and client communication?
- What about browserfy-like opening, refreshing, or even cross-browser visual testing? 
- Chrome, chromium-edge and [firefox](https://docs.firefox-dev.tools/backend/protocol.html) all use it (if I'm not mistaken).

Native / Mobile App API's 
-  [I2C](https://browserobo.github.io/WebI2C/)
-  [USB](https://developer.mozilla.org/en-US/docs/Web/API/USB)
-  [web serial](https://github.com/svendahlstrand/web-serial-api)
-  [sensor APIs](https://developer.mozilla.org/en-US/docs/Web/API/Sensor_APIs)
-  [Web Bluetooth API ](https://developer.mozilla.org/en-US/docs/Web/API/Web_Bluetooth_API)
-  [Geolocation](https://developer.mozilla.org/en-US/docs/Web/API/Geolocation_API)

Light weight Database Stuff also addresses #5605 
- [IndexDB](https://developer.mozilla.org/en-US/docs/Web/API/IndexedDB_API)
- [WebSQL](https://www.w3.org/TR/webdatabase/)

[Others Worth considering] (https://www.creativebloq.com/features/15-web-apis-youve-never-heard-of)

**Comment by nayeemrmn** [comment] 2020-06-09 18:36
Duplicate of #4756 (deemed unhelpful to just list a bunch of web APIs), #1120 (devtools is already implemented), #1699 and #5605.

Please use issues to request a specific feature with a stated use case, and search for similar issues before opening a new one.

**Comment by HansUXdev** [comment] 2020-06-09 19:08
Please don't assume I didn't search for duplicates when I did. I searched for devtools and didn't see 4756 or 1699 similarly. 

I get your request for a specific feature, which in this case is more about supporting hardware and native app development out of the box, which is why I wouldn't necessarily call it a duplicate of those or the one's I already mentioned. 

Web API's are one way of doing it and more consistent with being "webby" but I'm sure there are other ways as well.

**Comment by HansUXdev** [comment] 2020-06-09 20:25
Although adding hardware/mobile app support isn't technically part of deno's goals, it is both what makes node shine and what holds it back in terms of making hybrid apps competitive. 

The following core goals, in and of themselves make a compelling argument for adding web API's that allow hardware support out of the box.
- "Given a URL to a Deno program, it is runnable with nothing more than the ~15 megabyte zipped executable"
- "Deno programs which are written completely in JavaScript... ought to also be able to be run in a modern web browser without change." 

Lets say even a few of the API's mentioned above were implemented (like serial and I2C).
Then lets say deno was used as runtime replacement for node on a PI, arduino, etc.
You'd have every thing needed to communicate to a hardware module.
On top of that, the device be able to run a single executable from a url or perhaps, better, watch the url for changes than re-run the denon program?
That could dramatically speed up dev time because it takes a hot minute to recompile code to a T2.

**Comment by monteslu** [comment] 2020-06-09 21:12
as someone that's worked with node-serialport and noble (node BLE), i can say it's been a nightmare maintaining those projects as native plugins to node.

Would be awesome to see these as built-ins to deno.  If there's any possibility to get webSerial from chromium into deno, we could have denobots powered by johnny-five :)

![400px-DinobotsG1](https://user-images.githubusercontent.com/423800/84200213-34a20280-aa5b-11ea-8302-42a2d6f672c9.jpg)

**Comment by bartlomieju** [comment] 2021-08-07 22:22
> Native / Mobile App API's

Some of those requested had already PRs opened, however they pose a significant challenge from the testing standpoint so I'm respectfully declining at this time.

`IndexDB` will make its way into Deno soonish. The rest of suggestions are not really actionable for us. Please open an issue with specific request.

**Closed by bartlomieju** 2021-08-07 22:22 UTC
Labels: suggestion
