### ISSUE TITLE
Angular 16 after deno task start errors with Too many open files

### ISSUE THREAD

**Issue by sant123** [denoland/deno#26071] opened 2024-10-09 02:14 UTC
Version: Deno 2.0.0+a62c7e0

Related with https://github.com/denoland/deno/issues/22995

Currently I have an Angular 16 project and I would like to run it with Deno. However after `deno task start` it throws with the following message:

![image](https://github.com/user-attachments/assets/a9752024-2945-4e32-a000-93926a9059c2)

Steps to reproduce:
- npm install -g @angular/cli@16
- ng new my-deno-port
- deno task start

I know this is an old version, but still Node v20.17.0 is able to run it without issues.

Thanks 🙏🏼

**Comment by satyarohith** [comment] 2024-10-09 07:07
I couldn't reproduce this with latest rc on macOS
```
deno 2.0.0-rc.10 (release candidate, release, aarch64-apple-darwin)
v8 12.9.202.13-rusty
typescript 5.6.2
```
Logs:
```
➜  my-deno-port git:(main) deno task start
Task start ng serve
✔ Browser application bundle generation complete.

Initial Chunk Files   | Names         |  Raw Size
vendor.js             | vendor        |   2.04 MB |
polyfills.js          | polyfills     | 331.94 kB |
styles.css, styles.js | styles        | 229.21 kB |
main.js               | main          |  46.79 kB |
runtime.js            | runtime       |   6.52 kB |

| Initial Total |   2.64 MB

Build at: 2024-10-09T07:05:49.084Z - Hash: f1733c6f31e6c762 - Time: 1155ms

** Angular Live Development Server is listening on localhost:4200, open your browser on http://localhost:4200/ **


✔ Compiled successfully.
```

@sant123 can you upgrade to latest rc (run: `deno upgrade rc`)? I'll close this issue for now but feel free to comment if you're having issues with the latest rc too.

**Comment by sant123** [comment] 2024-10-09 10:43
I'm testing this again with Deno 2.0 and I'm having the same issue:

![image](https://github.com/user-attachments/assets/2d6a3f06-ef8c-49ce-a717-a77a115777af)

I'm on Fedora 40

**Comment by sant123** [comment] 2024-10-09 11:06
@satyarohith please take into account this fails on Angular 16 but Angular 18 works good.

**Comment by sant123** [comment] 2024-10-09 11:17
Alright I just tested with Mac OS and is working good with Sonoma:

<img width="1727" alt="image" src="https://github.com/user-attachments/assets/f6559f93-c84f-4436-9737-82ee9114a8fd">

It seems the issue is in Linux only 🤔

**Comment by littledivy** [comment] 2024-10-09 19:06
This is the same issue as https://github.com/denoland/deno/issues/17757. I think we have an idea how to fix this.

**Comment by sant123** [comment] 2024-10-09 19:29
> This is the same issue as #17757. I think we have an idea how to fix this.

Thanks @littledivy 🙏🏼

**Closed** 2024-10-23 03:53 UTC
Labels: bug, linux
