### ISSUE TITLE
Unable to get quick info: Error: Debug Failure.

### ISSUE THREAD

**Issue by Mqxx** [denoland/deno#18769] opened 2023-04-19 09:02 UTC
Deno throws an error with the following `jsDoc`.

```ts
/**
 * @returns {{[]}}
 */
export function func() {
    
}
```

`Extension:`
![image](https://user-images.githubusercontent.com/62719703/233023877-62d6648e-1d13-44d5-afa1-1c40dba67931.png)

`Output log:`
```
Unable to get quick info: Error: Debug Failure.
    at visitEachChildOfIndexSignatureDeclaration (ext:deno_tsc/00_typescript.js:86025:19)
    at visitEachChild (ext:deno_tsc/00_typescript.js:85871:35)
    at visitExistingNodeTreeSymbols (ext:deno_tsc/00_typescript.js:51300:18)
    at visitArrayWorker (ext:deno_tsc/00_typescript.js:85683:51)
    at visitNodes2 (ext:deno_tsc/00_typescript.js:85654:21)
    at visitEachChildOfTypeLiteralNode (ext:deno_tsc/00_typescript.js:86071:13)
    at visitEachChild (ext:deno_tsc/00_typescript.js:85871:35)
    at visitExistingNodeTreeSymbols (ext:deno_tsc/00_typescript.js:51300:18)
    at visitNode (ext:deno_tsc/00_typescript.js:85621:21)
    at serializeExistingTypeNode (ext:deno_tsc/00_typescript.js:51172:29)
[Error - 10:55:58] Request textDocument/hover failed.
  Message: Internal error
  Code: -32603
```

**Comment by samreid** [comment] 2023-04-20 14:09
I saw a similar problem and reported it in https://github.com/phetsims/chipper/issues/1388.  I'm using `tsc --version` `Version 5.0.4` on `Node.js v18.12.1` on MacOS 13.0.1.

**Comment by bartlomieju** [comment] 2024-12-06 01:12
I'm gonna close this one because I'm not able to reproduce it anymore in Deno v2.1.2, no matter what I try to change the JSDoc.

**Closed by bartlomieju** 2024-12-06 01:12 UTC
