### ISSUE TITLE
Provide a way to limit imports to certain domains/directories 

### ISSUE THREAD

**Issue by jahtalab** [denoland/deno#13330] opened 2022-01-10 21:07 UTC
It would be useful to have a permission option to limit the imports to a certain domain or directory.

**Comment by kitsonk** [comment] 2022-01-10 21:25
What is the use case, what would be an example of something this would fix/improve?

**Comment by bartlomieju** [comment] 2022-01-10 21:28
Seems related to #8266

**Comment by kitsonk** [comment] 2022-01-10 21:33
Actually, feels like a duplicate.  @jahtalab I would suggest you add feedback there around what you had in mind.

Duplicate of #8266

**Closed by kitsonk** 2022-01-10 21:33 UTC
Labels: duplicate
