### ISSUE TITLE
fmt: breaks gfm callouts

### ISSUE THREAD

**Issue by kitsonk** [denoland/deno#21905] opened 2024-01-12 00:55 UTC
Version: Deno 1.39.2

GitHub supports callouts using block quotes (see: [community/discussions#16925](https://github.com/orgs/community/discussions/16925)).

Currently running `deno fmt` on the following markdown will "break" the gfm callout:

```md
> [!NOTE]
> Some sort of note
```

Which should look like this:

> [!NOTE]
> Some sort of note

But it will reformatting it as:

```md
> [!NOTE] Some sort of note
```

But this breaks rendering of the callout in gfm which renders as:

> [!NOTE] Some sort of note

[Prettier](https://prettier.io/playground/#N4Igxg9gdgLgprEAuEBiABAWQIYCcDWAJhAO5QA6FUAfOgNoCEAcgPIAqAogLqW0DKEALZx0AZwi4Y6CADN0UCPEogANCAgAHGAEtoo5KDy5SABTwJ9KbABsS2AJ761AI1zYw+ODD7ZhAGW0oOGQZG1E4FzcPLz4Nd0CAc2QYXABXCJBwwW1ktIy4AA8NOFxtYVgbNhKoPG04S1DrcLVRROs4AEVUxWCkRuaQACtRAr42zu74ELCMgEdJuBNjDUsQbFEAWiC4Qh3VEBTsbWtEgGEhQWxkNetrfdaoBPaAQRgU7WdU+BMSgKDppoZAAWMEE1gA6kDtPBRHEwHA+BZodoAG7Q+zXMCiJwgFHpACSUF2sD4YFKWmeRL4MHs7QBAw0xnC4LcGmujPqJRRwTUgXCkiW2ASl3pGTiuH510uBGIZH2jMCMHB2kIMCByAAHAAGNS4ODzbR6wXCq59GZqGDYZzK1XqpAAJjUqXCbCtDXNIDggmcO12hD82EeqSFcAAYhJLm9EtdsF8ICAAL4JoA) does not reformat it this way (though it doesn't appear to rewrap blocks anyways)

**Comment by dsherret** [comment] 2024-08-17 01:29
Duplicate of https://github.com/denoland/deno/issues/20917

**Closed by dsherret** 2024-08-17 01:29 UTC
Labels: bug, deno fmt
