### ISSUE TITLE
fetch() ignores RequestInit.referrer

### ISSUE THREAD

**Issue by jcayzac** [denoland/deno#23762] opened 2024-05-10 04:28 UTC
Version: Deno 1.43.2

Simple repro with the CLI:

```
Deno 1.43.2
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> void Deno.serve((req) => new Response(JSON.stringify([...req.headers], null, 2)))
Listening on http://localhost:8000/
undefined
> await (await fetch(`http://localhost:8000/`, { referrer: `http://localhost:8000/foo` })).json()
[
  [ "accept", "*/*" ],
  [ "accept-encoding", "gzip, br" ],
  [ "accept-language", "*" ],
  [ "host", "localhost:8000" ],
  [ "user-agent", "Deno/1.43.2" ]
]
>
```

### Current Behavior

Although I passed a value for `referrer`, it was ignored and `fetch()` didn't set the `referer` header on the request.

Adding any value for `referrerPolicy` makes no difference.

### Expected Behavior

I should be getting a `referer` header.

**Comment by jcayzac** [comment] 2024-05-10 04:54
It seems something is missing around here, maybe? `Request(input, init)` never references the field.

https://github.com/denoland/deno/blob/19c0633a947f2ee28cc07b59c32322151779101d/ext/fetch/23_request.js#L395-L409

**Comment by jcayzac** [comment] 2024-05-10 05:11
The workaround for now is to use the `referer` request header, although it's forbidden even in WinterCG's spec for fetch() (and ignores any referrer policy, so you have to compute it manually):

```
> await (await fetch(`http://localhost:8000/`, { headers: { referer: `http://localhost:8000/foo` }})).json()
[
  [ "accept", "*/*" ],
  [ "accept-encoding", "gzip, br" ],
  [ "accept-language", "*" ],
  [ "host", "localhost:8000" ],
  [ "referer", "http://localhost:8000/foo" ],
  [ "user-agent", "Deno/1.43.2" ]
]
```

**Comment by bartlomieju** [comment] 2024-05-12 21:14
CC @lucacasonato, I recall there's a reason for this but I can't recall what's the particular reason.

**Comment by lucacasonato** [comment] 2024-06-08 14:26
This is somewhat intentional - setting a referrer makes no sense on the server, as you do not have an origin to refer from.

We will be looking at this again in WinterCG to determine what the best path forward is for this. For now I'll close this issue as "working as intended".

**Closed by lucacasonato** 2024-06-08 14:26 UTC

**Comment by jcayzac** [comment] 2024-06-11 23:42
@lucacasonato 

> setting a referrer makes no sense on the server

You're assuming Deno runs on a server. This is not the only use case for Deno.

**Comment by lucacasonato** [comment] 2024-06-18 14:02
What is your usecase?

**Comment by jcayzac** [comment] 2024-06-19 11:15
@lucacasonato CLI locally running (or rather emulating headlessly) some code common with a web application, interfacing with an endpoint that uses CORS.
