### ISSUE TITLE
poll_event_loop returns Poll::Pending but doesn't guarantee that wake() will be called

### ISSUE THREAD

**Issue by espindola** [denoland/deno#13458] opened 2022-01-21 15:36 UTC
The included program is a reduced testcase of an server where each request is represented with a javascript Promise. We create a rust future for each javascript promise and wait for them to complete. The waiting is done with FuturesUnordered, so only if wake() is called will the corresponding future be polled. The problem is that poll_event_loop doesn't guarantee that.

When running the program, it prints

```
espindola 29 0x55fbbf71a8a8 Pending
espindola 29 0x55fbbf669c68 Pending
espindola 29 0x55fbbf71a8a8 Pending
espindola 29 0x55fbbf71a8a8 Ready(Ok(()))
espindola 99
```

Which show that one of futures is polled until complete, but since wake() is not called for the second, the program blocks waiting for the second one without ever calling poll in it.

```rust
use deno_core::url::Url;
use deno_core::NoopModuleLoader;
use deno_runtime::permissions::Permissions;
use deno_runtime::worker::MainWorker;
use deno_runtime::worker::WorkerOptions;
use deno_runtime::BootstrapOptions;
use futures::stream::FuturesUnordered;
use futures::StreamExt;
use std::cell::RefCell;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;
use std::sync::Arc;
use std::task::Context;
use std::task::Poll;
use tokio;

struct MyFuture {
    worker: Rc<RefCell<MainWorker>>,
}

impl Future for MyFuture {
    type Output = anyhow::Result<()>;
    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let mut borrow = self.worker.borrow_mut();
        let runtime = &mut borrow.js_runtime;
        let ret = runtime.poll_event_loop(cx, false);
        let s: &Self = &self;
        println!("espindola {} {:?} {:?}", line!(), s as *const Self, ret);
        ret
    }
}

async fn get_fut(worker: Rc<RefCell<MainWorker>>) {
    MyFuture { worker: worker }.await.unwrap();
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let module_loader = Rc::new(NoopModuleLoader);
    let create_web_worker_cb = Arc::new(|_| {
        todo!("Web workers are not supported in the example");
    });

    let options = WorkerOptions {
        bootstrap: BootstrapOptions {
            apply_source_maps: false,
            args: vec![],
            cpu_count: 1,
            debug_flag: false,
            enable_testing_features: false,
            location: None,
            no_color: false,
            runtime_version: "x".to_string(),
            ts_version: "x".to_string(),
            unstable: false,
        },
        extensions: vec![],
        unsafely_ignore_certificate_errors: None,
        root_cert_store: None,
        user_agent: "hello_runtime".to_string(),
        seed: None,
        js_error_create_fn: None,
        create_web_worker_cb,
        maybe_inspector_server: None,
        should_break_on_first_statement: false,
        module_loader,
        get_error_class_fn: None,
        origin_storage_dir: None,
        blob_store: Default::default(),
        broadcast_channel: Default::default(),
        shared_array_buffer_store: None,
        compiled_wasm_module_store: None,
    };

    let main_module = Url::parse("file:///no/such/file").unwrap();
    let permissions = Permissions::allow_all();

    let worker = MainWorker::bootstrap_from_options(main_module, permissions, options);
    let worker = Rc::new(RefCell::new(worker));

    let _js_promise = {
        let mut borrow = worker.borrow_mut();
        borrow
            .js_runtime
            .execute_script(
                "",
                r#"
new Promise(resolve => setTimeout(resolve, 1000))
"#,
            )
            .unwrap()
    };

    let mut set = FuturesUnordered::new();
    set.push(get_fut(worker.clone()));
    set.push(get_fut(worker.clone()));
    while let Some(_) = set.next().await {
        println!("espindola {}", line!());
    }
    println!("espindola {}", line!());
    Ok(())
}
```

**Comment by bartlomieju** [comment] 2022-01-21 16:10
There is only a single promise (which maps to only a single op); once it resolves, once of your futures is resolved. Why should the second future be polled again if the event loop is empty and there's no more work to do? I you schedule another timeout it should be polled and resolved.

**Comment by espindola** [comment] 2022-01-21 16:17
There are two promises ( in the original program) and two futures (both in the original program and in the reduced testcase). The name get_fut was a bad choice, it should be create_fut.

The poll API requires that if Pending is returned, then something must have registered the waker. In here a single promise unblocks two futures. In the original program there are two promises that compete in a single call to poll_event_loop.

The net result is that the above program freezes, and it is not clear how to work around it.

**Comment by bartlomieju** [comment] 2022-01-21 16:25
> The poll API requires that if Pending is returned, then something must have registered the waker. In here a single promise unblocks two futures. In the original program there are two promises that compete in a single call to poll_event_loop.

Futures created by you register the waker - `JsRuntime` can resolve multiple promises in a single tick - this is by design. But you use two different futures to poll a single future, in this case (if I'm not mistaken) one future overrides the registered waker for the other. 

Do you have some specific use case in mind? Maybe it's just a matter of restructuring the code?

**Comment by espindola** [comment] 2022-01-21 16:32
There are still two futures. They happen to both resolve in the same time, but there are two. In the original program each request becomes a promise, which gets mapped to a future. I will expand the reduced testcase a bit.

**Comment by espindola** [comment] 2022-01-21 16:49
Expanded the testcase a bit:

Imagine this being a hyper server. Every http request has to be mapped to a rust future. In our case, that future can depend on a javascript promise being fulfilled.

```
use deno_core::url::Url;
use deno_core::v8;
use deno_core::JsRuntime;
use deno_core::NoopModuleLoader;
use deno_runtime::permissions::Permissions;
use deno_runtime::worker::MainWorker;
use deno_runtime::worker::WorkerOptions;
use deno_runtime::BootstrapOptions;
use futures::pin_mut;
use futures::stream::FuturesUnordered;
use futures::StreamExt;
use std::cell::RefCell;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;
use std::sync::Arc;
use std::task::Context;
use std::task::Poll;
use tokio;

fn get_js_promise(runtime: &mut JsRuntime) -> v8::Global<v8::Value> {
    runtime
        .execute_script(
            "test",
            r#"
new Promise(resolve => setTimeout(resolve, 1000))
"#,
        )
        .unwrap()
}

// Each user request produces a promise. We have to wait for that in
// rust, so we create a future for each JS promise. There can be many
// requests, so the futures are stored on a FuturesUnordered or
// equivalent (not sure what exactly hyper user under the hood).
struct MyFuture {
    js_promise: v8::Global<v8::Value>,
    worker: Rc<RefCell<MainWorker>>,
}

impl Future for MyFuture {
    type Output = anyhow::Result<v8::Global<v8::Value>>;
    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let mut borrow = self.worker.borrow_mut();
        let runtime = &mut borrow.js_runtime;

        // FIXME: propose having a runtime::poll_promise in deno.
        let fut = runtime.resolve_value(self.js_promise.clone());
        pin_mut!(fut);
        let ret = fut.poll(cx);
        println!("espindola {} {:?} {:?}", line!(), self.js_promise, ret);
        ret
    }
}

async fn get_fut(worker: Rc<RefCell<MainWorker>>) {
    let js_promise = {
        let mut borrow = worker.borrow_mut();
        get_js_promise(&mut borrow.js_runtime)
    };
    MyFuture {
        js_promise,
        worker: worker.clone(),
    }
    .await
    .unwrap();
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let module_loader = Rc::new(NoopModuleLoader);
    let create_web_worker_cb = Arc::new(|_| {
        todo!("Web workers are not supported in the example");
    });

    let options = WorkerOptions {
        bootstrap: BootstrapOptions {
            apply_source_maps: false,
            args: vec![],
            cpu_count: 1,
            debug_flag: false,
            enable_testing_features: false,
            location: None,
            no_color: false,
            runtime_version: "x".to_string(),
            ts_version: "x".to_string(),
            unstable: false,
        },
        extensions: vec![],
        unsafely_ignore_certificate_errors: None,
        root_cert_store: None,
        user_agent: "hello_runtime".to_string(),
        seed: None,
        js_error_create_fn: None,
        create_web_worker_cb,
        maybe_inspector_server: None,
        should_break_on_first_statement: false,
        module_loader,
        get_error_class_fn: None,
        origin_storage_dir: None,
        blob_store: Default::default(),
        broadcast_channel: Default::default(),
        shared_array_buffer_store: None,
        compiled_wasm_module_store: None,
    };

    let main_module = Url::parse("file:///no/such/file").unwrap();
    let permissions = Permissions::allow_all();

    let worker = MainWorker::bootstrap_from_options(main_module, permissions, options);
    let worker = Rc::new(RefCell::new(worker));

    let mut set = FuturesUnordered::new();
    set.push(get_fut(worker.clone()));
    set.push(get_fut(worker.clone()));
    while let Some(_) = set.next().await {
        println!("espindola {}", line!());
    }
    println!("espindola {}", line!());
    Ok(())
}
```

**Comment by espindola** [comment] 2022-01-24 19:25
Updated to use poll_value:

```rust
use deno_core::url::Url;
use deno_core::v8;
use deno_core::JsRuntime;
use deno_core::NoopModuleLoader;
use deno_runtime::permissions::Permissions;
use deno_runtime::worker::MainWorker;
use deno_runtime::worker::WorkerOptions;
use deno_runtime::BootstrapOptions;
use futures::stream::FuturesUnordered;
use futures::StreamExt;
use std::cell::RefCell;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;
use std::sync::Arc;
use std::task::Context;
use std::task::Poll;
use tokio;

fn get_js_promise(runtime: &mut JsRuntime) -> v8::Global<v8::Value> {
    runtime
        .execute_script(
            "test",
            r#"
new Promise(resolve => setTimeout(resolve, 1000))
"#,
        )
        .unwrap()
}

// Each user request produces a promise. We have to wait for that in
// rust, so we create a future for each JS promise. There can be many
// requests, so the futures are stored on a FuturesUnordered or
// equivalent (not sure what exactly hyper user under the hood).
struct MyFuture {
    js_promise: v8::Global<v8::Value>,
    worker: Rc<RefCell<MainWorker>>,
}

impl Future for MyFuture {
    type Output = anyhow::Result<v8::Global<v8::Value>>;
    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let mut borrow = self.worker.borrow_mut();
        let runtime = &mut borrow.js_runtime;

        let ret = runtime.poll_value(&self.js_promise, cx);
        println!("espindola {} {:?} {:?}", line!(), self.js_promise, ret);
        ret
    }
}

async fn get_fut(worker: Rc<RefCell<MainWorker>>) {
    let js_promise = {
        let mut borrow = worker.borrow_mut();
        get_js_promise(&mut borrow.js_runtime)
    };
    MyFuture {
        js_promise,
        worker: worker.clone(),
    }
    .await
    .unwrap();
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let module_loader = Rc::new(NoopModuleLoader);
    let create_web_worker_cb = Arc::new(|_| {
        todo!("Web workers are not supported in the example");
    });

    let options = WorkerOptions {
        bootstrap: BootstrapOptions {
            apply_source_maps: false,
            args: vec![],
            cpu_count: 1,
            debug_flag: false,
            enable_testing_features: false,
            location: None,
            no_color: false,
            runtime_version: "x".to_string(),
            ts_version: "x".to_string(),
            unstable: false,
        },
        extensions: vec![],
        unsafely_ignore_certificate_errors: None,
        root_cert_store: None,
        user_agent: "hello_runtime".to_string(),
        seed: None,
        js_error_create_fn: None,
        create_web_worker_cb,
        maybe_inspector_server: None,
        should_break_on_first_statement: false,
        module_loader,
        get_error_class_fn: None,
        origin_storage_dir: None,
        blob_store: Default::default(),
        broadcast_channel: Default::default(),
        shared_array_buffer_store: None,
        compiled_wasm_module_store: None,
    };

    let main_module = Url::parse("file:///no/such/file").unwrap();
    let permissions = Permissions::allow_all();

    let worker = MainWorker::bootstrap_from_options(main_module, permissions, options);
    let worker = Rc::new(RefCell::new(worker));

    let mut set = FuturesUnordered::new();
    set.push(get_fut(worker.clone()));
    set.push(get_fut(worker.clone()));
    while let Some(_) = set.next().await {
        println!("espindola {}", line!());
    }
    println!("espindola {}", line!());
    Ok(())
}
```

**Comment by espindola** [comment] 2022-01-25 17:28
Reduced to use only deno_core:

```rust
use deno_core::op_async;
use deno_core::v8;
use deno_core::JsRuntime;
use deno_core::OpState;
use futures::stream::FuturesUnordered;
use futures::StreamExt;
use std::cell::RefCell;
use std::future::Future;
use std::pin::Pin;
use std::rc::Rc;
use std::task::Context;
use std::task::Poll;
use std::time::Duration;
use tokio;

fn get_js_promise(runtime: &mut JsRuntime) -> v8::Global<v8::Value> {
    runtime
        .execute_script(
            "test",
            r#"
new Promise(resolve => { resolvers.push(resolve); })
"#,
        )
        .unwrap()
}

// Each user request produces a promise. We have to wait for that in
// rust, so we create a future for each JS promise. There can be many
// requests, so the futures are stored on a FuturesUnordered or
// equivalent (not sure what exactly hyper user under the hood).
struct MyFuture {
    js_promise: v8::Global<v8::Value>,
    runtime: Rc<RefCell<JsRuntime>>,
}

impl Future for MyFuture {
    type Output = anyhow::Result<v8::Global<v8::Value>>;
    fn poll(self: Pin<&mut Self>, cx: &mut Context<'_>) -> Poll<Self::Output> {
        let mut borrow = self.runtime.borrow_mut();
        let runtime = &mut borrow;

        let ret = runtime.poll_value(&self.js_promise, cx);
        println!("espindola {} {:?} {:?}", line!(), self.js_promise, ret);
        ret
    }
}

async fn get_fut(runtime: Rc<RefCell<JsRuntime>>) {
    let js_promise = {
        let mut borrow = runtime.borrow_mut();
        get_js_promise(&mut borrow)
    };
    MyFuture {
        js_promise,
        runtime: runtime.clone(),
    }
    .await
    .unwrap();
}

async fn op_sleep(_: Rc<RefCell<OpState>>, millis: u64, _: ()) -> anyhow::Result<()> {
    tokio::time::sleep(Duration::from_millis(millis)).await;
    Ok(())
}

#[tokio::main]
async fn main() -> anyhow::Result<()> {
    let mut runtime = JsRuntime::new(Default::default());
    runtime.register_op("my_sleep", op_async(op_sleep));
    runtime.sync_ops_cache();

    runtime.execute_script(
        "test",
        r#"
const resolvers = [];
Deno.core.opAsync("my_sleep", 1000).then(() => {
    for (const r of resolvers) {
        r();
    }
});
"#,
    )?;

    let runtime = Rc::new(RefCell::new(runtime));

    let mut set = FuturesUnordered::new();
    set.push(get_fut(runtime.clone()));
    set.push(get_fut(runtime.clone()));
    while let Some(_) = set.next().await {
        println!("espindola {}", line!());
    }
    println!("espindola {}", line!());
    Ok(())
}

```

**Comment by espindola** [comment] 2022-03-28 09:03
not stale

**Comment by bartlomieju** [comment] 2023-12-14 16:32
This should be fixed now with all the recent changes to `deno_core`.

**Closed by bartlomieju** 2023-12-14 16:32 UTC
Labels: bug
