### ISSUE TITLE
Docusaurus: Bad Resource ID with example code

### ISSUE THREAD

**Issue by levino** [denoland/deno#26348] opened 2024-10-17 07:33 UTC
Version: Deno 2.0.1

I am trying to migrate my docusaurus project from yarn to deno. However I found out that even the [example from the docs](https://docs.deno.com/runtime/fundamentals/web_dev/#docusaurus) does not work as expected: After I run the commands, the `deno task start` command fails with:
```
$ deno task start
Task start docusaurus start
[INFO] Starting the development server...
[SUCCESS] Docusaurus website is running at: http://localhost:3000/

✔ Client
  Compiled successfully in 1.11s

client (webpack 5.95.0) compiled successfully
BadResource: Bad resource ID
    at TcpConn.setNoDelay (ext:deno_net/01_net.js:211:12)
    at TCP.setNoDelay (ext:deno_node/internal_binding/tcp_wrap.ts:229:28)
    at Socket.setNoDelay (node:net:595:20)
    at WebSocket.setSocket (file:///private/tmp/my-website/node_modules/webpack-dev-server/node_modules/ws/lib/websocket.js:241:35)
    at WebSocketServer.completeUpgrade (file:///private/tmp/my-website/node_modules/webpack-dev-server/node_modules/ws/lib/websocket-server.js:419:8)
    at WebSocketServer.handleUpgrade (file:///private/tmp/my-website/node_modules/webpack-dev-server/node_modules/ws/lib/websocket-server.js:344:10)
    at ServerImpl.<anonymous> (file:///private/tmp/my-website/node_modules/webpack-dev-server/lib/servers/WebsocketServer.js:47:29)
    at ServerImpl.emit (ext:deno_node/_events.mjs:393:28)
    at handler (node:http:1310:14)
    at ext:deno_http/00_serve.ts:369:24 {
  name: "BadResource"
}
Upgrade response was not returned from callback
```
and the browser shows
```
ERROR
Loading chunk __comp---site-src-pages-index-tsx-1-df-d3e failed.
(error: http://localhost:3000/__comp---site-src-pages-index-tsx-1-df-d3e.js)
ChunkLoadError
    at __webpack_require__.f.j (http://localhost:3000/runtime~main.js:803:29)
    at http://localhost:3000/runtime~main.js:146:40
    at Array.reduce (<anonymous>)
    at __webpack_require__.e (http://localhost:3000/runtime~main.js:145:67)
    at fn.e (http://localhost:3000/runtime~main.js:354:50)
    at __WEBPACK_DEFAULT_EXPORT__.__comp---site-src-pages-index-tsx-1-df-d3e (webpack-internal:///./.docusaurus/registry.js:5:242)
    at load (webpack-internal:///./node_modules/react-loadable/lib/index.js:27:17)
    at eval (webpack-internal:///./node_modules/react-loadable/lib/index.js:55:20)
    at Array.forEach (<anonymous>)
    at loadMap (webpack-internal:///./node_modules/react-loadable/lib/index.js:54:22)
```

I am unable to fix this issue myself. Fwiw, I would expect the example from the docs to just work.

Is there anything else I can provide to make the issue reproducible?

**Comment by marvinhagemeister** [comment] 2024-10-17 07:54
Duplicate of https://github.com/denoland/deno/issues/26343

**Closed by marvinhagemeister** 2024-10-17 07:54 UTC
Labels: bug, node compat
