### ISSUE TITLE
Panicked when slice emoji in interactive mode

### ISSUE THREAD

**Issue by skanehira** [denoland/deno#14810] opened 2022-06-07 10:51 UTC
# Summary
Deno has panicked when run bellow code at interactive mode.

```ts
const str = "🌍🤖😸🎉";
console.log(str.slice(0,3));
```

Error message
```
root@523db2214abf:/# RUST_BACKTRACE=1 deno
Deno 1.21.3
exit using ctrl+d or close()
> const str = "🌍🤖😸🎉";
undefined
> console.log(str.slice(0,3));
🌍�

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.21.3
Args: ["deno"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Error("unexpected end of hex escape", line: 1, column: 113)', /home/runner/work/deno/deno/core/inspector.rs:724:66
stack backtrace:
   0: rust_begin_unwind
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/std/src/panicking.rs:498:5
   1: core::panicking::panic_fmt
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/panicking.rs:116:14
   2: core::result::unwrap_failed
             at ./rustc/9d1b2106e23b1abd32fce1f17267604a5102f57a/library/core/src/result.rs:1690:5
   3: core::result::Result<T,E>::unwrap
   4: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   5: <futures_util::future::select::Select<A,B> as core::future::future::Future>::poll
   6: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   7: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   8: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
   9: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  10: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  11: deno::tools::repl::run::{{closure}}
  12: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  13: deno::main::{{closure}}
  14: <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll
  15: deno_runtime::tokio_util::run_basic
  16: deno::main
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
root@523db2214abf:/#
```

But when I run code from stdin, it looks work fine.

```sh
root@8bf9e7714971:/# deno run - < `tty`
const str = "🌍🤖😸🎉";
console.log(str.slice(0,3));
🌍�
root@8bf9e7714971:/#
```

# Environments
```sh
root@8bf9e7714971:/# uname -a
Linux 8bf9e7714971 5.10.104-linuxkit #1 SMP PREEMPT Thu Mar 17 17:05:54 UTC 2022 x86_64 GNU/Linux
```

**Comment by lucacasonato** [comment] 2022-06-07 11:16
Duplicate of #13482

**Closed by lucacasonato** 2022-06-07 11:16 UTC
Labels: bug, inspector
