### ISSUE TITLE
Fatal process out of memory: Oilpan: CagedHeap reservation.

### ISSUE THREAD

**Issue by Munrok** [denoland/deno#23698] opened 2024-05-04 23:39 UTC
Version: Deno 1.42.1

I can't use Deno, when I try to do it I receive:

```
$ deno


#
# Fatal process out of memory: Oilpan: CagedHeap reservation.
#
==== C stack trace ===============================

    0x6a36669bfa3 <???> at /usr/local/bin/deno
    0x6a36669aebb <???> at /usr/local/bin/deno
    0x6a366696b18 <???> at /usr/local/bin/deno
    0x6a3666e36fb <???> at /usr/local/bin/deno
    0x6a36684ba4e <???> at /usr/local/bin/deno
    0x6a366ea7719 <???> at /usr/local/bin/deno
    0x6a366eae9b0 <???> at /usr/local/bin/deno
    0x6a366eae6af <???> at /usr/local/bin/deno
    0x6a366ea77c1 <???> at /usr/local/bin/deno
    0x6a3654a96e1 <???> at /usr/local/bin/deno
    0x6a3654a91a0 <???> at /usr/local/bin/deno
Trace/BPT trap (core dumped)
```

```
$ ulimit -a
number of pseudoterminals                (-P) unlimited
socket buffer size           (bytes, -b) unlimited
core file size              (blocks, -c) 1048576
data seg size               (kbytes, -d) 33554432
file size                   (blocks, -f) unlimited
max kqueues                         (-k) unlimited
max locked memory           (kbytes, -l) 2048000
max memory size             (kbytes, -m) 2048000
open files                          (-n) 1500
pipe size                (512 bytes, -p) 1
stack size                  (kbytes, -s) 524288
cpu time                   (seconds, -t) unlimited
max user processes                  (-u) 20
virtual memory              (kbytes, -v) 15360000
swap size                   (kbytes, -w) unlimited
```

**Comment by marvinhagemeister** [comment] 2024-05-08 06:56
@Munrok What are the steps to reproduce the error?

**Comment by Munrok** [comment] 2024-05-13 22:05
@marvinhagemeister Everything I did was to enter the command "deno" (just like in my example) without any additional actions.

**Comment by ThatRick** [comment] 2024-05-14 00:10
I get the same error when trying to run deno in gpt-4o linux sandbox

**Comment by mpcref** [comment] 2024-05-18 16:19
Same here.
```bash
$ deno --version
deno 1.42.4 (release, x86_64-unknown-freebsd)
v8 12.3.219.9
typescript 5.4.3

$ deno


#
# Fatal process out of memory: Oilpan: CagedHeap reservation.
#
==== C stack trace ===============================

    0x3d060f57dfa3 <???> at /usr/local/bin/deno
    0x3d060f57cebb <???> at /usr/local/bin/deno
    0x3d060f578b18 <???> at /usr/local/bin/deno
    0x3d060f5c56fb <???> at /usr/local/bin/deno
    0x3d060f72da4e <???> at /usr/local/bin/deno
    0x3d060fd89719 <???> at /usr/local/bin/deno
    0x3d060fd909b0 <???> at /usr/local/bin/deno
    0x3d060fd906af <???> at /usr/local/bin/deno
    0x3d060fd897c1 <???> at /usr/local/bin/deno
    0x3d060e38b6e1 <???> at /usr/local/bin/deno
    0x3d060e38b1a0 <???> at /usr/local/bin/deno
Trace/BPT trap (core dumped)
```

**Comment by marvinhagemeister** [comment] 2024-05-18 17:55
@mpcref Does the error happen with the latest Deno version?

**Comment by mpcref** [comment] 2024-05-18 23:04
@marvinhagemeister this is the latest version I'm able to test it with.
It's on a shared hosting service that uses FreeBSD 13.2-RELEASE-p10.

**Comment by avkarenow** [comment] 2024-06-03 10:15
Crash still appears with deno `1.44.0` and limited virtual memory.

System: `FreeBSD 14.0`
```
$ deno --version
deno 1.44.0 (release, x86_64-unknown-freebsd)
v8 12.6.228.3
typescript 5.4.5
```

Without limits:
`virtual mem size        (kbytes, -v)  unlimited`
```
$ deno
Deno 1.44.0
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> Deno.version.v8
"12.6.228.3"
> 
```
With limits:
`$ ulimit -v 15360000`
`virtual mem size        (kbytes, -v)  15360000`
```
$ deno


#
# Fatal process out of memory: Oilpan: CagedHeap reservation.
#
==== C stack trace ===============================

    0x320c18519f93 <???> at /usr/local/bin/deno
    0x320c18518eab <???> at /usr/local/bin/deno
    0x320c18514b08 <???> at /usr/local/bin/deno
    0x320c185616eb <???> at /usr/local/bin/deno
    0x320c186d17fe <???> at /usr/local/bin/deno
    0x320c18da77c9 <???> at /usr/local/bin/deno
    0x320c18daf185 <???> at /usr/local/bin/deno
    0x320c18daef0f <???> at /usr/local/bin/deno
    0x320c18da7871 <???> at /usr/local/bin/deno
    0x320c17015e31 <???> at /usr/local/bin/deno
    0x320c17015868 <???> at /usr/local/bin/deno
    0x320c16838cd0 <???> at /usr/local/bin/deno
    0x320c16d769e4 <???> at /usr/local/bin/deno
    0x320c1683661e <???> at /usr/local/bin/deno
    0x320c16833ff8 <???> at /usr/local/bin/deno
    0x320c16835098 <???> at /usr/local/bin/deno
    0x32143cf79afa <__libc_start1+0x12a> at /lib/libc.so.7
Trace/BPT trap (core dumped)
```

**Comment by lucacasonato** [comment] 2024-06-17 05:37
This looks like a bug with upstream v8 running under FreeBSD. I suggest you open an issue there. FreeBSD is not an officially supported platform for Deno, so I'll close this issue here.

**Closed by lucacasonato** 2024-06-17 05:37 UTC
Labels: bug, upstream

**Comment by benz0li** [comment] 2024-11-28 05:15
To reproduce with the docker image:

```shell
docker run --rm -ti denoland/deno:1.44.0 bash -c 'ulimit -v 20971520; deno'
```

Deno 1.44.0 runs out of memory when the address space is below 20 GB.

**Comment by benz0li** [comment] 2024-11-28 05:16
With Deno 2.1.1 this bar was raised to 64 GB.

Cross reference:

* https://github.com/denoland/deno/issues/27121
