### ISSUE TITLE
perf(kv): `list` of 20k+ items takes 34+ seconds

### ISSUE THREAD

**Issue by skoshx** [denoland/deno#20219] opened 2023-08-21 08:39 UTC
Is it meant to be that the performance of `list` is ~linearly correlated with the time it takes to `kv.list` all items?

So if there would be 40k items, it would take over a minute.

Is this expected speeds?

**Comment by bartlomieju** [comment] 2023-08-21 09:20
Duplicate of #20218

**Closed by bartlomieju** 2023-08-21 09:20 UTC
