### ISSUE TITLE
node: ClientRequest.options.createConnection

### ISSUE THREAD

**Issue by monotter** [denoland/deno#19507] opened 2023-06-14 18:13 UTC
```ts
import tls from 'node:tls'
import https from 'node:https'
import net from 'node:net'

function tlsConnect(options) {
  options.path = undefined;

  if (!options.servername && options.servername !== '') {
    options.servername = net.isIP(options.host) ? '' : options.host;
  }

  return tls.connect(options);
}

const opts = {
  protocolVersion: 13,
  maxPayload: 104857600,
  skipUTF8Validation: false,
  perMessageDeflate: true,
  followRedirects: false,
  maxRedirects: 10,
  handshakeTimeout: 30000,
  createConnection: tlsConnect,
  socketPath: undefined,
  hostname: undefined,
  protocol: undefined,
  timeout: 30000,
  method: "GET",
  host: "gateway.discord.gg",
  path: "/?v=10&encoding=json",
  port: 443,
  defaultPort: 443,
  headers: {
    Connection: "Upgrade",
    Upgrade: "websocket",
    "Sec-WebSocket-Extensions": "permessage-deflate; client_max_window_bits"
  }
}

https.request(opts)
```

I've had an issue on DiscordJS with deno. Whenever I run this code I am getting this issue below.
<img width="486" alt="Ekran Resmi 2023-06-14 21 12 16" src="https://github.com/denoland/deno/assets/48836542/c6e53b20-9842-4587-a250-e7b8051bbece">

**Comment by bartlomieju** [comment] 2023-06-14 22:01
FYI support for discord.js was added in https://github.com/denoland/deno/pull/19412 and will be released tomorrow in v1.34.3. That said `ClientReuqest.options.createConnection` is still not supported and ignored entirely.

**Comment by RandyPen** [comment] 2023-07-04 10:50
I encoutered a similar bug.

```
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
Warning: Not implemented: ClientRequest.options.createConnection
error: Uncaught Error: Too many subscriptions on the connection
    at new JSONRPCError (file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/@open-rpc/client-js/1.8.1/build/Error.js:24:28)
    at Object.exports.convertJSONToRPCError (file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/@open-rpc/client-js/1.8.1/build/Error.js:37:16)
    at TransportRequestManager.processResult (file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/@open-rpc/client-js/1.8.1/build/transports/TransportRequestManager.js:91:31)
    at TransportRequestManager.resolveRes (file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/@open-rpc/client-js/1.8.1/build/transports/TransportRequestManager.js:113:18)
    at TransportRequestManager.resolveResponse (file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/@open-rpc/client-js/1.8.1/build/transports/TransportRequestManager.js:53:25)
    at WebSocket.<anonymous> (file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/@open-rpc/client-js/1.8.1/build/transports/WebSocketTransport.js:77:47)
    at WebSocket.onMessage (file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/ws/7.5.9/lib/event-target.js:132:16)
    at WebSocket.emit (ext:deno_node/_events.mjs:379:28)
    at Receiver.receiverOnMessage (file:///Users/xxx/Library/Caches/deno/npm/registry.npmjs.org/ws/7.5.9/lib/websocket.js:1068:20)
    at Receiver.emit (ext:deno_node/_stream.mjs:1852:9)
```

the source code is 
```typescript
import { JsonRpcProvider, Connection, SuiEvent } from 'npm:@mysten/sui.js';

// Construct your connection:
const connection = new Connection({
	websocket: 'wss://fullnode.testnet.sui.io',
	faucet: 'https://faucet.testnet.sui.io/gas',
});
// connect to Testnet
const provider = new JsonRpcProvider(connection);

const promptPackage = '0x86e2ab6c370fbfed0ee955158ca95ca5b465dede4a79eb3594d2959e72d3d62a';
const promptFilter = { MoveModule: { package: promptPackage, module: 'cybrosnetwork' } };
const promptSub = await provider.subscribeEvent({
    filter: promptFilter,
    onMessage(event: SuiEvent) {
      // handle subscription notification message here
      console.log(event["parsedJson"]);
    },
  });

```

**Comment by Mrowa96** [comment] 2023-08-10 10:43
Same for me using `puppeteer`

```js
import { join } from "https://deno.land/std@0.197.0/path/mod.ts";
import denoDir from "https://deno.land/x/dir/mod.ts";
import puppeteer from 'npm:puppeteer-core@21.0.2';
import {install, resolveBuildId} from "npm:@puppeteer/browsers@1.5.1"

const {executablePath} = await install({
      browser: 'chrome',
      buildId: '113.0.5672.0',
      cacheDir: join(denoDir('cache'), "puppeteer")
});

const browser = await puppeteer.launch({
      headless: false,
      executablePath, 
});

const page = await browser.newPage();

await page.setContent(`<p>test</p>`, { waitUntil: 'networkidle2' });
```

**Comment by acrodrig** [comment] 2023-10-03 17:57
Is there a workaround? I am trying to use Deno with the [mqtt](https://github.com/mqttjs) and I get the same issue. Thanks.

**Comment by theandym** [comment] 2023-10-16 04:12
I'm also experiencing this issue with [CCXT](https://github.com/ccxt/ccxt) — specifically with CCXT Pro and its connection via websockets for the `watch*` methods.

**Comment by uynilo9** [comment] 2023-10-28 03:54
same me with `npm:discord.js`

**Comment by SoftwareAndOutsourcing** [comment] 2023-11-06 11:04
I can reproduce this issue in #21096.

**Comment by Abdillah** [comment] 2023-12-01 11:45
I'm reproducing this on `npm:selenium-webdriver` which uses Chrome Debug Protocol (using websocket, `ws` package). Using the following code:

```
    const builder = new Builder()
    .forBrowser(Browser.CHROME)

    try {
        const driver = await builder.build();
        const cap = await conn.driver.getCapabilities();
        // Fix IP address
        cap.set('se:cdp', cap.get('se:cdp').replace('0.3', '0.2'));
        const cdp = await conn.driver.createCDPConnection('page');
    } catch(e) {
        console.log("ERR", e, conn)
    }
```

**Comment by worotyns** [comment] 2024-01-02 14:52
Same in `npm:@slack/bolt`

**Comment by mariusheil** [comment] 2024-01-07 10:27
I am also using mqtt.js and while everything seems to work, the same error is thrown and it would be nice if it were fixed. Not sure of the implications when this error is thrown.

**Comment by jpagand** [comment] 2024-01-23 10:12
> I am also using mqtt.js and while everything seems to work, the same error is thrown and it would be nice if it were fixed. Not sure of the implications when this error is thrown.

For me, the websocket reconnection logic doesn't work

**Comment by gardc** [comment] 2024-05-01 03:58
> +1 having this issue with Discord JS

Same here, still an issue.

**Comment by ducan-ne** [comment] 2024-06-18 12:18
Same here, this blocks me on using port checking libs

**Comment by Sunf3r** [comment] 2024-06-27 00:00
Same in `npm:baileys`

**Comment by maheshbansod** [comment] 2024-07-16 05:29
Issue still exists in 1.45.2

**Comment by mariusheil** [comment] 2024-07-16 06:14
For npm:mqtt, this is really annoying as it is the only major mqtt implementation that can be used for deno. All the other implementations are not maintained anymore. At least I was not able to find a maintained package.

**Comment by elimydlarz** [comment] 2024-10-07 11:33
Also getting this error when trying to use OpenAI's new [Realtime API client](https://github.com/openai/openai-realtime-api-beta) in my Deno project.

It's problematic that Deno's `WebSocket` implementation is missing features from Node's implementation, mainly:
- Whatever is causing this error
- Attaching headers from clients (if I wanted to bypass this library and make my own Deno native client, I couldn't because I need to attach auth headers)

**Comment by hydrangea-sh** [comment] 2024-10-09 20:46
The same issue is happening in with `npm:shoukaku`

**Comment by xxhertz** [comment] 2024-10-10 05:56
socket.io-client causing the same issue

**Comment by josephrocca** [comment] 2024-10-11 08:31
Another affected package: `npm:chrome-remote-interface` (DevTools debugger protocol)

**Comment by mlshv** [comment] 2024-10-11 12:24
Same with `npm:puppeteer`

**Comment by ValorHeart** [comment] 2024-10-12 10:44
Happends also with `npm:@slack/bolt`

**Comment by bartlomieju** [comment] 2024-10-12 10:48
Thanks for comments. We'll prioritize fixing this problem.

**Comment by cobbvanth** [comment] 2024-10-12 20:30
> Thanks for comments. We'll prioritize fixing this problem.

Awesome, thank you, just encountered this and am very excited for the merge.

**Comment by RickDT** [comment] 2024-10-12 22:07
I think this is also blocking `npm:wrangler pages dev` which is Cloudflare's local preview environment.

TIA for prioritizing it!

**Comment by herenickname** [comment] 2024-10-16 12:10
node:http Agents dont work because of this, were waiting! :)

**Comment by rdbo** [comment] 2024-11-28 01:34
I'm having issues as well connecting with a local websocket

**Comment by 117** [comment] 2024-12-03 02:44
`npm:ws` has this issue as well

**Closed** 2024-12-13 00:44 UTC
Labels: bug, node compat, node API, node:http

**Comment by monotter** [comment] 2024-12-14 05:44
It's incredible, it's been over a year and I didn't know it would catch on this much. At first, I had just written here because I couldn't solve an error that I didn't understand the meaning of, and many people said they had the same problem.

Deno is a fantastic environment. I generally choose not to do something if I can't do it with Deno, and it usually works for everything.

May God be pleased with everyone who has contributed to this wonderful project.

**Comment by m-emelchenkov** [comment] 2024-12-25 12:03
Any news on this issue?
