### ISSUE TITLE
Deno 1.25.2 doesn't accept `--compat` flag any more. 

### ISSUE THREAD

**Issue by sergey-shandar** [denoland/deno#15854] opened 2022-09-10 19:17 UTC
It looks like the `compatibility` mode is broken in 1.25.2 https://deno.land/manual@v1.25.2/node/compatibility_mode

```
> deno run --unstable --compat --allow-read --allow-env ./test.f.cjs
PS C:\github.com\functionalscript\functionalscript> deno run --unstable --compat --allow-read --allow-env ./test.f.cjs
error: Found argument '--compat' which wasn't expected, or isn't valid in this context

        If you tried to supply `--compat` as a value rather than a flag, use `-- --compat`

USAGE:
    deno run --unstable <SCRIPT_ARG>...

For more information try --help
```

Example: https://github.com/functionalscript/functionalscript/runs/8286749568?check_suite_focus=true

**Comment by sergey-shandar** [comment] 2022-09-10 19:26
I've found this PR https://github.com/denoland/deno/pull/15678

My question is, how to use the `npm:` specifier?

**Comment by kitsonk** [comment] 2022-09-10 20:05
Duplicate of #15678

For information on the `npm:` specifiers check here: https://deno.com/blog/v1.25#experimental-npm-support. The manual is going through a re-write and will be added there soon.

**Closed by kitsonk** 2022-09-10 20:05 UTC
Labels: duplicate
