### ISSUE TITLE
[Discussion] Decide on reading directory API for 1.0 release

### ISSUE THREAD

**Issue by cknight** [denoland/deno#4277] opened 2020-03-07 21:59 UTC
**Background**

#4225 renamed `readDir()` to `readdir()` to fit more with the familiar Unix naming convention which has also been widely adopted by other runtimes and libraries.  `readdir`, as implemented by most other runtimes/libraries, will read directory entries one at a time.  Each call to `readdir` returns a new entry until null is returned when the list is exhausted.

`Deno.readdir()` on the other hand, as currently implemented, will return all directory entries in one go and is not iterable. 

**Proposal**

(see below for options)

~~I suggest we rename the existing functionality and provide a `Deno.readdir()` iterable implementation (as per #4218) in it's place which would provide a consistent and expected experience for developers.  Options for renaming the existing/current `Deno.readdir()` method could be `Deno.readDir()`, `Deno.readDirectory()`, `Deno.readAllDir()`, or ...?~~

**Other APIs**
* Go provides both a [ReadDir](https://golang.org/pkg/io/ioutil/#example_ReadDir) (fetch all at once) and a [readdir](https://golang.org/pkg/os/#File.Readdir) (iterable) implementation.
* Node's [fs.readdir](https://nodejs.org/api/fs.html#fs_fs_readdir_path_options_callback) is an iterable implementation.
* PHP's  [readdir](https://www.php.net/manual/en/function.readdir.php) also is iterable
* Linux/libc/etc implements `readdir` as an iterable.
* Rust has a [read_dir](https://doc.rust-lang.org/std/fs/fn.read_dir.html) iterable
* Probably lots more

**Summary**

With the recent rename, Deno's current implementation for `readdir` is inconsistent with most other libraries/platforms/runtimes, but still provides a useful implementation.  We should agree the correct API for reading directories before 1.0 is released.  Ref: #2473 

**Options**
1. `Deno.readdir()` is iterable.  There is no other implementation.
2. `Deno.readdir()` is iterable.  The current 'return everything' implementation is retained, but under another API.  E.g. `Deno.readDir()`, `Deno.readDirectory()`, `Deno.readAllDir()`, etc.
3. `Deno.readdir()` is retained as is (i.e. non-iterable).  An iterable API is introduced under a different name.  E.g. `Deno.readdirIter()`.
4. `Deno.readdir()` is iterable.  A replica of the current API is rewritten in `std` using the Deno iterable API to build an array which is returned. ([example](https://github.com/cknight/deno/blob/master/std/node/_fs_dir.ts#L20))
5. `Deno.readdir({iterate: true})` where the API is `readdir(options?:ReadDirOptions): Promise<FileInfo[]> | Promise<FileInfo>`, allowing both iterable and non-iterable implementation within the one API
6. An API of `Deno.readdir(n: number): Promise<FileInfo[]> | Promise<FileInfo>` similar to Go which returns `n` number of entries at a time.  If n = -1, then all entries are returned.

#4218 has been previously raised to capture implementing an iterable version of reading directories.

Of course, while this is all about `Deno.readdir`, the solution must also apply to `Deno.readdirSync`.

cc @ry, @dubiousjim

**Comment by dubiousjim** [comment] 2020-03-07 22:10
I'm pro us introducing an iterable implementation, and also pro it's taking over the ’readdir’ name. Don't have a view about whether the current implementation should also be retained, and if so how it should be named.

**Comment by nayeemrmn** [comment] 2020-03-07 22:16
I would hate having both, if we have the generator implementation we shouldn't need the other... the problem is that JS doesn't have an easy way of "collecting" an async iterable (i.e. an async spread operator). However, it most likely will in the future so we should be careful nevertheless.

**Comment by cknight** [comment] 2020-03-07 22:50
Another possible option to consider is to move the current implementation to `std`.  Then, the Deno API would have the iterable option (as it's only option) and the `std` library would have the "give me everything at once" option.

**Comment by cknight** [comment] 2020-03-07 22:52
Oh, just remembered yet another option to highlight.  Go's [readdir](https://golang.org/pkg/os/#File.Readdir) implementation takes an integer argument which defines how many entries to return at once.  Give it `-1` and it returns everything in one go, hence combining the two into one.

**Comment by dubiousjim** [comment] 2020-03-07 22:55
Current implementation is in Rust. std/ looks to be TypeScript-only.

**Comment by cknight** [comment] 2020-03-07 23:07
> Current implementation is in Rust. std/ looks to be TypeScript-only.

Yes.  The idea for a `std` implementation would be to simply have a function to iterate the Deno API `readdir` and build an array to return which would replicate what we currently have in the Deno API.

**Comment by ry** [comment] 2020-03-08 15:48
moving to an iteratator API is ideal. The only reason it isn’t that way currently was to add some functionality quickly early on in Deno’s development.

**Comment by Skillz4Killz** [comment] 2020-03-10 00:06
Just want to add a note here that the `std/fs/walk.ts` is broken because of the different naming formats.

**Comment by nayeemrmn** [comment] 2020-03-10 00:08
@Skillz4Killz You're linking to std @ master, are you using `deno` at master?

**Comment by cknight** [comment] 2020-04-14 22:36
@ry - What would you like to do with this issue?  I believe @dubiousjim started looking at this (#4440), but at a guess won't have anything ready before the 20th April API freeze.  Do we go into the 1.0 release with the current non-iterable `readdir` API?  If the answer is no, what steps would you like to see taken prior to the 1.0 release around this API?

**Comment by ry** [comment] 2020-04-14 22:42
@cknight I would really like to get this fixed before 1.0 ... I haven’t got around it it myself. I think readdir should return an async iterator.

**Closed** 2020-04-16 05:40 UTC
