### ISSUE TITLE
Bug: Error message logging on repl tab completion on windows

### ISSUE THREAD

**Issue by JOTSR** [denoland/deno#17952] opened 2023-02-25 20:45 UTC
Since Deno 1.31 upgrade, on startup and at each tab completion an error message is logged. 
Platform: windows 11

Full re-install, cleaning cache, ... not solving this issue
Downgrading solve it
Install on VM don't seems to have this issue

```sh
Could not set npm package requirements. Error getting response at https://registry.npmjs.org/npm for package "npm": An npm specifier not found in cache: "npm", --cached-only is specified.
Deno 1.31.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> MCould not set npm package requirements. Error getting response at https://registry.npmjs.org/npm for package "npm": An npm specifier not found in cache: "npm", --cached-only is specified.

Map             Math            MessageChannel  MessageEvent    MessagePort
```

**Comment by drewbitt** [comment] 2023-02-28 00:12
#17929

**Comment by dsherret** [comment] 2023-02-28 19:18
Duplicate of https://github.com/denoland/deno/issues/17929

**Closed by dsherret** 2023-02-28 19:18 UTC
Labels: duplicate
