### ISSUE TITLE
Debugger does not hit breakpoints in VSCode with "--no-check"

### ISSUE THREAD

**Issue by elemental-mind** [denoland/deno#9787] opened 2021-03-15 02:25 UTC
I wanted to debug a file in TypeScript that still had type errors in it and thought debugging with omitted type checks would work. However it breaks the debugger. Probably because the swc outputted source strings are wrapped in angle brackets <..../sourceFile.js>. 

I have the following `launch.json` :
```
{
    "version": "0.2.0",
    "configurations": [
        {
            "name": "Deno",
            "type": "pwa-node",
            "request": "launch",
            "cwd": "${workspaceFolder}",
            "runtimeExecutable": "deno",
            "runtimeArgs": [
                "run",
                "--no-check",
                "--inspect",
                "-A",
                "/path/to/sourceFile.ts"
            ],
            "attachSimplePort": 9229
        }
    ]
}
```
and several breakpoints set in `sourceFile.ts`. When I hit F5 the debugger does not stop at these breakpoints.

Changing `runtimeArgs` to:
```
            [
                "run",
                "--no-check",
                "--inspect-brk",
                "-A",
                "/path/to/sourceFile.ts"
            ]
```
opens up a new window upon hitting F5 with a file titled `sourceFile.ts>` (and of course no breakpoints set in it).

If `sourceFile.ts` includes a first import `import { bla } from "importFile.ts"` it normally opens up a new `importFile.ts>` tab. (I have only tested local files here).

As there is no issue when the files are checked (I suspect tsc is used to emit files), I guess the swc output needs to be sanitized/post-processed when debugging.

Probably related to #9640 .

**Comment by kitsonk** [comment] 2021-03-15 03:13
It is caused by #9640

**Comment by bartlomieju** [comment] 2022-01-17 05:27
I believe this is now working as expected, see https://github.com/denoland/deno/issues/9640#issuecomment-1014155593. I'm going to tentatively close this issue as fixed, let me know if the problem still persists in the latest version of Deno.

**Closed by bartlomieju** 2022-01-17 05:27 UTC
Labels: bug, inspector
