### ISSUE TITLE
Can't Import Ecmascript Modules via REPL

### ISSUE THREAD

**Issue by Lonniebiz** [denoland/deno#2629] opened 2019-07-10 05:49 UTC
deno: 0.10.0
v8: 7.7.37
typescript: 3.5.1

When you try to import an ecmascript module using the [REPL](https://en.wikipedia.org/wiki/Read%E2%80%93eval%E2%80%93print_loop), you get an Uncaught SyntaxError:

```
> import Drash from "https://deno.land/x/drash@v0.8.6/mod.ts";
error: Uncaught SyntaxError: Unexpected identifier
► <unknown>:1:8
    at evaluate (js/repl.ts:87:34)
    at replLoop (js/repl.ts:145:13)
```

Node.js allows CommonJS module loading using their REPL, but I'm unable to import ES modules there either: [https://stackoverflow.com/questions/56963708/](https://stackoverflow.com/questions/56963708/).

**Comment by kt3k** [comment] 2019-07-10 06:29
(duplicate of #1285)

**Comment by kevinkassimo** [comment] 2019-07-10 06:30
Dup of #1285. This is expected. ES Module is slightly different from require as resolution is asynchronous, and could only exist in module level (e.g. in an independent file). Also see https://medium.com/the-node-js-collection/an-update-on-es6-modules-in-node-js-42c958b890c

What you want is actually the dynamic `import`. I think Ryan has a WIP implementation for it, so it should be available soon.

**Comment by kevinkassimo** [comment] 2019-07-10 06:37
I think currently if we really want to do this, there are only 2 solutions:
1. Fake one: parse import statements and convert to dynamic import secretly. Also requires top level await support.
2. Concatenate past commands and join them into a script and eval from beginning every single time. I remember this is similar to what ts-node is doing with their REPL.
I believe neither of these solutions are perfect, and should not be prioritized due to other more important work to complete

**Comment by Lonniebiz** [comment] 2019-07-10 08:51
@kevinkassimo : I should have thought of that!

https://stackoverflow.com/a/56966774/217867

**Closed** 2019-07-10 14:15 UTC
