### ISSUE TITLE
cli: include path in NotFound os errors

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#11213] opened 2021-07-01 18:10 UTC
Consider the following code:

```ts
const path = "./404.txt";
await Deno.readTextFile(path);
```

I get the following error when I run the script.
```
error: Uncaught (in promise) NotFound: No such file or directory (os error 2)
const text = await Deno.readTextFile(path);
             ^
    at deno:core/core.js:86:46
    at unwrapOpResult (deno:core/core.js:106:13)
    at async open (deno:runtime/js/40_files.js:46:17)
    at async Object.readTextFile (deno:runtime/js/40_read_file.js:40:18)
    at async file:///Users/sr/deno_issues/io_error.ts:2:14
```

It isn't easy to debug when you've hundreds of files with the above information.

One thing I'm not sure about is if we should delegate the responsibility to scripts or if we should include the path in Deno's built-in error itself. 

I favor including the path in the default error message as most scripts usually won't take the extra effort to display additional information when they encounter the error.

**Comment by caspervonb** [comment] 2021-07-01 18:31
Duplicate of https://github.com/denoland/deno/issues/10553
Consensus is that we'll add context to all the path related system calls.

**Closed** 2021-07-01 18:34 UTC
Labels: suggestion
