### ISSUE TITLE
Cannot bundle app with Materials UI web components - appears to be a namespace clash?

### ISSUE THREAD

**Issue by nsadeh** [denoland/deno#7282] opened 2020-08-31 04:33 UTC
Hello, I am trying to build a front end with web components using Materials UI as a UI library. I have the following `deps.tsx`:

```typescript
import MatUI from "https://jspm.dev/@material-ui/core@4.11.0";

export {MatUI};
```

`tsconfig.json`:
```json
{
    "compilerOptions": {
      "experimentalDecorators": true,
      "noImplicitAny": false,
      "skipLibCheck": true,
      "lib": ["dom", "esnext", "deno.ns"],
      "plugins": [
        {
          "name": "typescript-deno-plugin",
          "enable": true
        }
      ],
    },
    "include": [
      "./src/**/*"
    ]
  }
```

and `app.ts`:
```typescript
import { MatUI } from "../src/deps.tsx"

const { Button }  = MatUI as any;
```

I am getting many (7008) errors, but a common one looks like this:

`TS2441 [ERROR]: Duplicate identifier 'exports'. Compiler reserves name 'exports' in top level scope of a module.
var exports = {};
    ~~~~~~~
    at https://jspm.dev/npm:tiny-warning@1.0.3!cjs:1:5`

I am running `deno bundle src/app.ts --config tsconfig.json src/app.js`.

Does anyone know a way to configure out the name clashes?

**Comment by kitsonk** [comment] 2020-08-31 05:09
Duplicate of #6176.

**Closed** 2020-08-31 07:49 UTC
