### ISSUE TITLE
Line numbering is off when reporting errors

### ISSUE THREAD

**Issue by gs0-pix4d** [denoland/deno#12576] opened 2021-10-28 14:26 UTC
Here is my deno invocation and output:

```console
$ /home/user/.local/bin/deno run --unstable --inspect --allow-all projectsync/app.ts

Debugger listening on ws://127.0.0.1:9229/ws/d1c67e89-7d24-5d18-9b6f-a0ee94e7ab9d
[my script output, about 10 lines of text]
error: Uncaught (in promise) SyntaxError: Unexpected end of JSON input
  metadata_from_spreadsheet: Record<string, string>;
                ^
    at JSON.parse (<anonymous>)
    at getJson (file:///home/user/projectsync/app.ts:14:17)
    at async file:///home/user/projectsync/app.ts:29:22
```

However, my script starts with type definitions and therefore, the offending lines reported (14 and 29) are part of a definition:

```typescript
type Project = {
3: type Project = {
...
13:  // deno-lint-ignore camelcase
14:  metadata_from_spreadsheet: Record<string, string>;
...
20: type Settings = {
...
28:  featuresImageScale: number;
29:  descriptorExtractorType: "LDAH";
```

I was previously running 1.15.1 that was crashing on _error: thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/fmt_errors.rs:195:45_, but after updating, I encountered the error described in this bug report.
```
deno 1.15.3 (release, x86_64-unknown-linux-gnu)
v8 9.5.172.19
typescript 4.4.2
```

I don't know if this bug report is enough.

**Comment by bartlomieju** [comment] 2021-12-01 15:12
@gs0-pix4d we had a few more refactors since 1.15.3 that might have alleviated this problem. Could you check if the problem persists on 1.16.3?

**Comment by bartlomieju** [comment] 2021-12-08 12:44
I'm going to tentatively close this issue as we don't have a way to reproduce the problem.

**Closed by bartlomieju** 2021-12-08 12:44 UTC
Labels: bug, cli, needs info

**Comment by gs0-pix4d** [comment] 2021-12-08 13:06
Sorry, I just happened to come back to that project. I had it working in another way in the meantime, and didn't check-out in VCS the problematic script. So, I guess it works for now :sweat_smile: 

Thanks anyway!
