### ISSUE TITLE
Provide limited env during startup

### ISSUE THREAD

**Issue by webdeb** [denoland/deno#8194] opened 2020-10-30 12:24 UTC
There is a thread about limiting `--allow-env` variables to some explicit keys.
https://github.com/denoland/deno/issues/3137

This issue is a bit different. Instead of allowing access to environment at runtime at all, the user should be able to _provide_ environment values during startup with the `--env` flag `--env SECRET=secret`. If possible, it would be great to have the ability to use it multiple times (in multiple lines) like the `-e` from Docker

```
deno run \
  --allow-net \
  --env SECRET=$SOME_SECRET \
  --env OPTION_X=true \
  --env URL \ # provide systems variable
  main.ts
``` 

Pros: All Env are still protected
Cons: immutable. To have access to new values, one would need to restart the program. (lets call it a feature)

**Comment by kitsonk** [comment] 2020-10-30 19:55
I am not really supportive of this.  Environment variables are environment variables.  You can already express them on the command line.

```
OPTION_X=true deno run --allow-net main.ts
```

If you want to pass an argument, pass an argument.

```
deno run --allow-net main.ts --secret=$SOME_SECRET
```

**Comment by webdeb** [comment] 2020-10-30 20:05
@kitsonk oh thats somehow dropped out of my mind, that you can actually do it with args.
Hmm. And first example would work without `--allow-env` ?

**Comment by kitsonk** [comment] 2020-10-30 20:49
> And first example would work without `--allow-env` ?

Apologies, no... it should be:

```
OPTION_X=true deno run --allow-net --allow-env main.ts
```

**Comment by jsejcksn** [comment] 2020-10-31 16:58
I think this is a duplicate of the referenced issue. Casper suggested exactly that in https://github.com/denoland/deno/issues/3137#issuecomment-656032020.

**Comment by MarkTiedemann** [comment] 2020-11-02 11:41
> You can already express them on the command line.

Yes, but doing so cross-plattform can be tricky. This is why [`cross-env`](https://www.npmjs.com/package/cross-env) is popular.

**Comment by kitsonk** [comment] 2020-11-02 23:38
Makes me even more convinced we should build something arbitrary into Deno CLI.

**Comment by webdeb** [comment] 2020-11-03 00:23
I've created that issue, because I don't like to _allow_ access to systems environment variables in prod (who knows whats in there)

As a user, I still would like to use Deno.env since its the application environment.

`--allow-env` is misleading anyway. Because `Deno.env.set` will not override any systems environment variable. It's only allowed to read it at some point. So you cannot rely on `Deno.env.get`, that it will return the systems value at runtime, because it could be changed with `Deno.env.set` at some point and be out of sync with the system anyway.

**Comment by webdeb** [comment] 2020-11-03 00:30
Just a side not
@kitsonk thx for oak! I am impressed of deno and the already existing tooling here, and that my small and simple webhook handler is only about ~400kb as a bundle.js. Deno is a game changer for me already.

**Comment by bartlomieju** [comment] 2020-12-12 13:28
> --allow-env is misleading anyway. Because Deno.env.set will not override any systems environment variable. It's only allowed to read it at some point. So you cannot rely on Deno.env.get, that it will return the systems value at runtime, because it could be changed with Deno.env.set at some point and be out of sync with the system anyway.

I don't believe this statement is true. The sole purpose of `Deno.env.set` is to set env variables on your system. 

> This issue is a bit different. Instead of allowing access to environment at runtime at all, the user should be able to provide environment values during startup with the --env flag --env SECRET=secret. If possible, it would be great to have the ability to use it multiple times (in multiple lines) like the -e from Docker

I'm with @kitsonk on this one and that'a a hard -1 from me on this one. There's no need for deno to provide this functionality if every shell can do that. Respectfully closing.

**Closed by bartlomieju** 2020-12-12 13:28 UTC
Labels: cli, suggestion
