### ISSUE TITLE
error: "Leaks detected" using createWriteStream from 'node:fs' in tests

### ISSUE THREAD

**Issue by 77it** [denoland/deno#22626] opened 2024-02-28 23:01 UTC
Version: Deno 1.41.0 on Windows 11

Running the following test many times, sometimes (1 time every 10/20 runs) returns the following error:

```
error: Leaks detected:
  - An async call to op_fs_open_async was started in this test, but never completed. The operation was started here:
    at op_fs_open_async (ext:core/00_infra.js:265:13)
    at Object.open (ext:deno_fs/30_fs.js:633:21)
    at Object.open (ext:deno_node/_fs/_fs_open.ts:80:10)
    at WriteStream._construct (ext:deno_node/internal/fs/streams.mjs:63:17)
    at constructNT (ext:deno_node/_stream.mjs:1672:16)
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:30:15)
    at eventLoopTick (ext:core/01_core.js:150:29)
```

```javascript
import fs from 'node:fs';
import os from 'node:os';
import path from 'node:path';

import { test } from 'node:test';
import assert from 'node:assert';

/** @type {any} */ const t = (typeof Deno !== 'undefined') ? Deno.test : test;

const tempDir = os.tmpdir();
const filePath = path.join(tempDir, 'test.txt' + Date.now());
const data = Array.from({ length: 10 }, (_, i) => `Line àèéìòù ${i + 1}`);

t('createWriteStream (called 1 times): write txt to a file stream and read it back', async () => {
  const stream = fs.createWriteStream(filePath, { flags: 'w', encoding: 'utf8' });  // 'a' means append; 'w' means overwrite

  stream.on('finish', () => {
    const readData = fs.readFileSync(filePath, 'utf8');
    console.log(readData);

    const expectedData = data.join('\n') + '\n';
    assert.strictEqual(readData, expectedData, 'The read data was not correct');

    fs.unlinkSync(filePath);
  });

  stream.on('error', (err) => {
    console.error('An error occurred:', err);
  });

  // Write each line to file
  for (const line of data) {
    if (!stream.write(line + '\n')) {
      // Handle backpressure, waiting for the drain event before writing more data
      await new Promise((resolve) => stream.once('drain', resolve));
    }
  }

  stream.end();
});
```

**Comment by mmastrac** [comment] 2024-02-28 23:21
Dupe of https://github.com/denoland/deno/issues/22473

Should be fixed by https://github.com/denoland/deno/pull/22480

**Comment by mmastrac** [comment] 2024-02-28 23:25
@dsherret Actually, looks like this fix should have been in 1.41.0. Any ideas?

**Comment by mmastrac** [comment] 2024-02-28 23:30
@77it 

Looking closer, I see that you are using `Deno.test` when running on Deno. This means that the op and resource sanitizers are enabled, which means you might get occasional sanitizer failures.

You should be able to fix this by either 1) using node:test on Deno (which will disable the sanitizers for you) or 2) waiting for the stream close event with something like `await new Promise(r => stream.on('close', r))`.

**Comment by dsherret** [comment] 2024-02-28 23:36
@mmastrac that looks like the correct fix to me. Alternatively it looks like .end takes a callback for when it's done: https://nodejs.org/api/stream.html#writableendchunk-encoding-callback

I think we can close this one.

**Closed by dsherret** 2024-02-28 23:36 UTC
Labels: invalid

**Comment by 77it** [comment] 2024-02-28 23:38
resolved adding  `await new Promise(r => stream.on('close', r));` at the end. thanks to all
