### ISSUE TITLE
Debugging in VsCode doesn't seem to work

### ISSUE THREAD

**Issue by nicu-chiciuc** [denoland/deno#24211] opened 2024-06-14 12:24 UTC
### Setup

I've created a new Fresh project per https://fresh.deno.dev/docs/getting-started/create-a-project

I've added a `lanch.json` file with the recommended configuration for Deno.
```jsonc
{
  // Use IntelliSense to learn about possible attributes.
  // Hover to view descriptions of existing attributes.
  // For more information, visit: https://go.microsoft.com/fwlink/?linkid=830387
  "version": "0.2.0",
  "configurations": [
    {
      "request": "launch",
      "name": "Launch Program",
      "type": "node",
      "program": "${workspaceFolder}/main.ts",
      "cwd": "${workspaceFolder}",
      "env": {},
      "runtimeExecutable": "/opt/homebrew/bin/deno",
      "runtimeArgs": [
        "run",
        "--inspect-wait",
        "--allow-all"
      ],
      "attachSimplePort": 9229,
      "outputCapture": "std"
    }
  ]
}
```

I've only added the `    "outputCapture": "std"` part so I can see the errors.

When I try to start the debugger I get this massive error:
```
/opt/homebrew/bin/deno run --inspect-brk --allow-all ./main.ts
Debugger listening on ws://127.0.0.1:9229/ws/a08a7d73-8b9a-484a-9f72-28957addbcac
Visit chrome://inspect to connect to the debugger.
Deno is waiting for debugger to connect.
Debugger session started.


#
# Fatal error in , line 0
# unreachable code
#
#
#
#FailureMessage Object: 0x16d0ffae8
==== C stack trace ===============================

    0   deno                                0x0000000104250f8c v8::base::debug::StackTrace::StackTrace() + 24
    1   deno                                0x0000000104256718 v8::platform::(anonymous namespace)::PrintStackTrace() + 24
    2   deno                                0x000000010424dc34 V8_Fatal(char const*, ...) + 324
    3   deno                                0x000000010476e51c v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) + 0
    4   deno                                0x000000010476e6f4 v8::internal::String::SlowFlatten(v8::internal::Isolate*, v8::internal::Handle<v8::internal::ConsString>, v8::internal::AllocationType) + 472
    5   deno                                0x00000001043ddb78 v8::internal::MessageFormatter::Format(v8::internal::Isolate*, v8::internal::MessageTemplate, v8::base::Vector<v8::internal::Handle<v8::internal::Object> const>) + 264
    6   deno                                0x00000001043e191c v8::internal::ErrorUtils::MakeGenericError(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSFunction>, v8::internal::MessageTemplate, v8::base::Vector<v8::internal::Handle<v8::internal::Object> const>, v8::internal::FrameSkipMode) + 112
    7   deno                                0x0000000104418920 v8::internal::Factory::NewTypeError(v8::internal::MessageTemplate, v8::base::Vector<v8::internal::Handle<v8::internal::Object> const>) + 152
    8   deno                                0x000000010474720c v8::internal::Object::AddDataProperty(v8::internal::LookupIterator*, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes, v8::Maybe<v8::internal::ShouldThrow>, v8::internal::StoreOrigin, v8::internal::EnforceDefineSemantics) + 272
    9   deno                                0x00000001046ce59c v8::internal::JSObject::AddProperty(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSObject>, v8::internal::Handle<v8::internal::Name>, v8::internal::Handle<v8::internal::Object>, v8::internal::PropertyAttributes) + 404
    10  deno                                0x00000001044eeec0 v8::internal::SimpleInstallFunction(v8::internal::Isolate*, v8::internal::Handle<v8::internal::JSObject>, char const*, v8::internal::Builtin, int, bool, v8::internal::PropertyAttributes) + 132
    11  deno                                0x00000001044ffec0 v8::internal::Genesis::InitializeGlobal_harmony_rab_gsab() + 244
    12  deno                                0x00000001044ffcd4 v8::internal::Genesis::InitializeExperimentalGlobal() + 24
    13  deno                                0x0000000104508534 v8::internal::Genesis::Genesis(v8::internal::Isolate*, v8::internal::MaybeHandle<v8::internal::JSGlobalProxy>, v8::Local<v8::ObjectTemplate>, unsigned long, v8::internal::DeserializeEmbedderFieldsCallback, v8::MicrotaskQueue*) + 1028
    14  deno                                0x00000001044ed7a0 v8::internal::Bootstrapper::CreateEnvironment(v8::internal::MaybeHandle<v8::internal::JSGlobalProxy>, v8::Local<v8::ObjectTemplate>, v8::ExtensionConfiguration*, unsigned long, v8::internal::DeserializeEmbedderFieldsCallback, v8::MicrotaskQueue*) + 96
    15  deno                                0x00000001042ae2e8 v8::NewContext(v8::Isolate*, v8::ExtensionConfiguration*, v8::MaybeLocal<v8::ObjectTemplate>, v8::MaybeLocal<v8::Value>, unsigned long, v8::internal::DeserializeEmbedderFieldsCallback, v8::MicrotaskQueue*) + 1576
    16  deno                                0x00000001042ae714 v8::Context::New(v8::Isolate*, v8::ExtensionConfiguration*, v8::MaybeLocal<v8::ObjectTemplate>, v8::MaybeLocal<v8::Value>, v8::DeserializeInternalFieldsCallback, v8::MicrotaskQueue*, v8::DeserializeContextDataCallback, v8::DeserializeAPIWrapperCallback) + 44
    17  deno                                0x0000000104c463b8 v8_inspector::V8InspectorImpl::regexContext() + 112
    18  deno                                0x0000000104c54778 v8_inspector::V8Regex::V8Regex(v8_inspector::V8InspectorImpl*, v8_inspector::String16 const&, bool, bool) + 92
    19  deno                                0x0000000104c0f9f8 v8_inspector::V8DebuggerAgentImpl::setBlackboxPattern(v8_inspector::String16 const&) + 64
    20  deno                                0x0000000104c1841c v8_inspector::V8DebuggerAgentImpl::setBlackboxPatterns(std::Cr::unique_ptr<std::Cr::vector<v8_inspector::String16, std::Cr::allocator<v8_inspector::String16>>, std::Cr::default_delete<std::Cr::vector<v8_inspector::String16, std::Cr::allocator<v8_inspector::String16>>>>) + 144
    21  deno                                0x0000000104c03c28 v8_inspector::protocol::Debugger::DomainDispatcherImpl::setBlackboxPatterns(v8_crdtp::Dispatchable const&) + 160
    22  deno                                0x0000000104c75e2c v8_crdtp::UberDispatcher::DispatchResult::Run() + 52
    23  deno                                0x0000000104c4ea6c v8_inspector::V8InspectorSessionImpl::dispatchProtocolMessage(v8_inspector::StringView) + 472
    24  deno                                0x000000010424c71c v8_inspector__V8InspectorSession__dispatchProtocolMessage + 44
    25  deno                                0x000000010325db00 deno_core::inspector::JsRuntimeInspector::poll_sessions::h438938e0ac10a3e3 + 1944
    26  deno                                0x000000010325fa40 deno_core::inspector::JsRuntimeInspector::wait_for_session_and_break_on_next_statement::h7359b81755e5481a + 44
    27  deno                                0x0000000102df1e14 _ZN4deno6worker13CliMainWorker33evaluate_module_possibly_with_npm28_$u7b$$u7b$closure$u7d$$u7d$17hb40254ad364481fcE + 192
    28  deno                                0x0000000102e44b0c _ZN4deno6worker13CliMainWorker37execute_main_module_possibly_with_npm28_$u7b$$u7b$closure$u7d$$u7d$17h0e523efd78d17055E + 840
    29  deno                                0x0000000102e43e90 _ZN4deno6worker13CliMainWorker3run28_$u7b$$u7b$closure$u7d$$u7d$17hefbaa1de9deb0f1eE + 1100
    30  deno                                0x0000000102e415a4 _ZN4deno5tools3run10run_script28_$u7b$$u7b$closure$u7d$$u7d$17h6bfa418c1ec35471E + 3500
    31  deno                                0x0000000102e451d0 _ZN4deno16spawn_subcommand28_$u7b$$u7b$closure$u7d$$u7d$17hf01539f20ca27314E + 532
    32  deno                                0x000000010308f3bc _ZN93_$LT$deno_unsync..task..MaskFutureAsSend$LT$F$GT$$u20$as$u20$core..future..future..Future$GT$4poll17h1b0838be5055cd27E + 20
    33  deno                                0x000000010308f6c0 tokio::runtime::task::raw::poll::h9fbb3cbbd8b3e646 + 88
    34  deno                                0x0000000102d05210 deno::main::h14f08e47267a5115 + 4008
    35  deno                                0x0000000102cf01b4 std::sys_common::backtrace::__rust_begin_short_backtrace::h9096fd507c8dfa71 + 12
    36  deno                                0x0000000102d03fe0 main + 656
    37  dyld                                0x00000001925320e0 start + 2360
```
    
   ### Things I've tried
   
I've tried running `dev.ts` instead of the default `main.ts`. I've also tried replacing `--inspect-wait` with `--inspect-brk`. None of these solutions seem to help. It's not even clear how would I try to investigate this.

**Comment by bartlomieju** [comment] 2024-06-14 16:45
Duplicate of https://github.com/denoland/deno/issues/24196, let's continue there.

**Closed** 2024-06-14 16:45 UTC
