### ISSUE TITLE
parsed deno info object

### ISSUE THREAD

**Issue by qballer** [denoland/deno#6612] opened 2020-07-02 19:08 UTC
Looking for a way to get a parsed `deno info` object in user.land. Is there a way to avoid implementing it?

**Comment by kitsonk** [comment] 2020-07-02 20:09
Duplicate of #2096

**Comment by bartlomieju** [comment] 2020-07-02 21:04
You might want to take a look at https://github.com/denoland/deno/pull/6372 which is slated for `v1.2.0` next week.

**Closed by bartlomieju** 2020-07-02 21:04 UTC
