### ISSUE TITLE
Deno bundle file doesn't support top level await

### ISSUE THREAD

**Issue by starkwang** [denoland/deno#3481] opened 2019-12-11 09:07 UTC
This is the example code in [std/http](https://deno.land/std/http/README.md):
```ts
// index.ts
import { serve } from "https://deno.land/std/http/server.ts";
const body = new TextEncoder().encode("Hello World\n");
const s = serve({ port: 8000 });
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body });
}
```
I bundled and tried to run it.
```
deno bundle index.ts > bundle.ts
deno run bundle.ts
```

Then got an error:
```
error: Uncaught SyntaxError: Unexpected reserved word
► file:///Users/starkwang/Desktop/try-deno/bundle.ts:4445:9

4445     for await (const req of s) {
             ~~~~~
```

**Comment by bartlomieju** [comment] 2019-12-11 09:13
Duplicate of #3301

**Comment by kitsonk** [comment] 2019-12-22 22:01
@ry close in favour of #3301

**Closed** 2019-12-22 22:03 UTC
