### ISSUE TITLE
Allow flags in deno.json

### ISSUE THREAD

**Issue by franz101** [denoland/deno#26117] opened 2024-10-10 16:00 UTC
First of all congrats to the launch. Migration to 2.x was seamless
Current setup
```
{
    "unstable": ["net"],
    "tasks": {
        "dev": "deno --allow-env  --allow-run  --allow-read --allow-net --env main.ts"
    },
}
```
Is it possible to run it like the following?
```
{
    "unstable": ["net"],
    "tasks": {
        "dev": "deno --env main.ts"
    },
    "allow" : ["read","env","net"]
}
```

**Comment by yazan-abdalrahman** [comment] 2024-10-13 07:01
@lucacasonato @bartlomieju 

it suggestion
Can I work on this?

**Comment by lucacasonato** [comment] 2024-10-18 07:58
Duplicate of #12763

**Closed by lucacasonato** 2024-10-18 07:58 UTC
