### ISSUE TITLE
First-class WebSocket server support

### ISSUE THREAD

**Issue by MarkTiedemann** [denoland/deno#10363] opened 2021-04-25 11:25 UTC
I like the design of the new `Deno.serveHttp` API. I think a similar design would work well for WebSockets, too.

Example API:

```typescript
async function acceptWebSocket(
  conn: Deno.Conn,
  httpConn: Deno.RequestEvent
): Promise<WebSocket> {}
```

Example usage:

```typescript
for await (const conn of Deno.listen({ port: 80 })) {
  handleConn(conn);
}

async function handleConn(conn: Deno.Conn) {
  for await (const httpConn of Deno.serveHttp(conn)) {
    handleHttpConn(conn, httpConn);
  }
}

async function handleHttpConn(conn: Deno.Conn, httpConn: Deno.RequestEvent) {
  try {
    const ws = await Deno.acceptWebSocket(conn, httpConn);
    ws.onopen = todo;
    ws.onmessage = todo;
    ws.onerror = todo;
    ws.onclose = todo;
  } catch {
    httpConn.respondWith(new Response("Failed to accept WebSocket", { status: 400 }));
  }
}

function todo() {}
```

**Comment by crowlKats** [comment] 2021-04-25 12:36
Duplicate of #10211

**Comment by lucacasonato** [comment] 2021-04-25 12:52
Closing as duplicate of #10211

**Closed by lucacasonato** 2021-04-25 12:52 UTC
