### ISSUE TITLE
Provide .JS files which are usable in browser deno.land/x

### ISSUE THREAD

**Issue by Ciantic** [denoland/deno#12959] opened 2021-12-01 12:28 UTC
I think this would make deno.land/x way more usable outside Deno too. Currently Deno works well with ES Modules, but deno.land/x does not provide JS files that could be used in vanilla browser script tags or JS files.

For instance sometimes I find a nice Deno library, and because most Deno code follows standards, I could import it in the browser. But I can't because `deno.land/x/` does not provide JS files, it only provides TS files, e.g.

```html
<script type="module">
import { pathToRegexp, match, parse, compile } from "https://deno.land/x/path_to_regexp@v6.2.0/index.js"
</script>
```

Does not work, because `https://deno.land/x/path_to_regexp@v6.2.0/index.ts` is just a TS file. Then I have to jump hoops to get it in my adhoc script tags.

Third Party Modules library could just compile all TS files to JS files when updated, then they would be usable in the browser as well.

**Comment by crowlKats** [comment] 2021-12-01 12:35
Duplicate of denoland/dotland#1728

**Closed by crowlKats** 2021-12-01 12:35 UTC
