### ISSUE TITLE
CLI: Flags don't work after file name

### ISSUE THREAD

**Issue by Luke-zhang-04** [denoland/deno#7445] opened 2020-09-13 12:29 UTC
This behavior seems very weird to me.

If I run test.ts with
```bash
deno run test.ts --allow-net
```

I get the following error
```bash
error: Uncaught PermissionDenied: network access to "http://127.0.0.1:3333/", run again with the --allow-net flag
    at unwrapResponse (rt/10_dispatch_json.js:24:13)
    at sendAsync (rt/10_dispatch_json.js:75:12)
    at async fetch (rt/26_fetch.js:279:29)
```

However, this works if I run it like this
```bash
deno run --allow-net test.ts
```

Everything works fine.

I feel like most users expect the same behavior from both examples.

Deno version 1.3.3

**Comment by crowlKats** [comment] 2020-09-13 12:46
anything that is passed after the file is passed directly to the script and accessible through `Deno.args`

**Comment by nayeemrmn** [comment] 2020-09-13 12:47
Duplicate of #5450. Arguments after the script name are passed to `Deno.args()` for consumption by user code. This design is intentional, shared by every other runtime and documented here: https://deno.land/manual/getting_started/command_line_interface#script-arguments.

**Closed** 2020-09-13 13:13 UTC
