### ISSUE TITLE
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli\graph_util.rs

### ISSUE THREAD

**Issue by xXACCEXx** [denoland/deno#19763] opened 2023-07-08 02:08 UTC
Got this message while playing around with the Deno.serve interface.

```
$ deno --version
deno 1.35.0 (release, x86_64-pc-windows-msvc)
v8 11.6.189.7
typescript 5.1.6
```

Basically, just trying to interpret the URL from a request path and map to a local import.

// example.ts
```ts
import { join } from 'https://deno.land/std@0.193.0/path/mod.ts'

type RequestHandler = (url: URL, headers: Headers) => Response;

const _server = Deno.serve({ port: 8080 }, async handler => {
	const url = new URL(handler.url);
	const pathname = url.pathname.split('/').filter(x => x);

	if (pathname.at(0) === 'api') {
		try {
			const apiFilePath = join(...pathname.slice(1))
			const { handler } = await import(`file:///${apiFilePath}`) as { handler: RequestHandler };
			// this was for testing, I have a file to import, but it doesn't do anything so not handling it yet.
			throw new Error('asd')
		}
		catch (e) {
			console.log(e);
			return new Response()
		}
	}

	return new Response(`Deno Server Response from: ${JSON.stringify(pathname)}`)
});

```

The `RequestHandler` type is just a function that returns a Response, as it's required by the `Deno.ServeHandler`.

When running the server, everything is fine.
```
Listening on http://localhost:8080/
```

If I request `/api/test` which should be mapped to a local file, then this error occurs

The error is consistent, so here's the result when run with DENO_BACKTRACE=full

```
$ RUST_BACKTRACE=full deno run -A --watch example.ts
Watcher Process started.
Listening on http://localhost:8080/

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.35.0
Args: ["C:\\Users\\****\\.deno\\bin\\deno.exe", "run", "-A", "--watch", "example.ts"]

thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: ()', cli\graph_util.rs:587:48  
stack backtrace:
   0:     0x7ff7844dda39 - napi_release_threadsafe_function
   1:     0x7ff7835ea75b - napi_release_threadsafe_function
   2:     0x7ff7844bb48a - napi_release_threadsafe_function
   3:     0x7ff7844e204b - napi_release_threadsafe_function
   4:     0x7ff7844e1c42 - napi_release_threadsafe_function
   5:     0x7ff7844e184a - napi_release_threadsafe_function
   6:     0x7ff7833ff20c - napi_fatal_error
   7:     0x7ff7844e2877 - napi_release_threadsafe_function
   8:     0x7ff7844e25e6 - napi_release_threadsafe_function
   9:     0x7ff7844e2539 - napi_release_threadsafe_function
  10:     0x7ff7844e2524 - napi_release_threadsafe_function
  11:     0x7ff785750845 - CrashForExceptionInNonABICompliantCodeRange
  12:     0x7ff785750c16 - CrashForExceptionInNonABICompliantCodeRange
  13:     0x7ff783059c4c - napi_cancel_async_work
  14:     0x7ff78325da45 - napi_cancel_async_work
  15:     0x7ff782f3dc76 - <unknown>
  16:     0x7ff782f3ae8c - <unknown>
  17:     0x7ff78325c1b1 - napi_cancel_async_work
  18:     0x7ff7833066ab - napi_cancel_async_work
  19:     0x7ff78330a34c - napi_cancel_async_work
  20:     0x7ff7837db7be - napi_release_threadsafe_function
  21:     0x7ff7838067f9 - napi_release_threadsafe_function
  22:     0x7ff7837e1067 - napi_release_threadsafe_function
  23:     0x7ff782f5a5c1 - <unknown>
  24:     0x7ff7833a88cc - napi_fatal_error
  25:     0x7ff782fd0a74 - <unknown>
  26:     0x7ff7834ed8f5 - napi_release_threadsafe_function
  27:     0x7ff7830aaa4c - napi_cancel_async_work
  28:     0x7ff78340119f - napi_fatal_error
  29:     0x7ff782fa43a7 - <unknown>
  30:     0x7ff7834eda13 - napi_release_threadsafe_function
  31:     0x7ff78570318c - CrashForExceptionInNonABICompliantCodeRange
  32:     0x7fffe3d07614 - BaseThreadInitThunk
  33:     0x7fffe5aa26f1 - RtlUserThreadStart
```

**Comment by bartlomieju** [comment] 2023-07-08 20:05
@dsherret please take a look

**Comment by HasanAlrimawi** [comment] 2024-08-26 08:01
I can't reproduce it, it seems to be addressed.

**Comment by marvinhagemeister** [comment] 2024-08-26 08:27
Closing, I can't reproduce the described issue either anymore.

**Closed by marvinhagemeister** 2024-08-26 08:27 UTC
Labels: bug
