### ISSUE TITLE
Using Rust as Backend?

### ISSUE THREAD

**Issue by Soremwar** [denoland/deno#3240] opened 2019-10-29 21:21 UTC
Call me crazy but.

What if I need to create a highly consuming task I don't want to be runned by Deno? Is there any way to program Rust code inside Deno?

Or do I have to set up a completely new Rust server to do it and call it as an API?

I honestly don't see a way to do this without making a hole in the whole Deno structure, but being able to use Rust as more than just the interpreter looked like an idea that's worth giving a shot.

**Comment by ry** [comment] 2019-10-29 21:26
We're working towards a stable binding and plugin interface - but it's not done yet.  https://github.com/denoland/deno/issues/2180 https://github.com/denoland/deno/pull/2385 https://github.com/denoland/deno/pull/3031 https://github.com/denoland/deno/pull/3025 https://github.com/denoland/deno/pull/2840

**Comment by nayeemrmn** [comment] 2019-10-29 21:27
Duplicate of #296?

**Comment by ry** [comment] 2019-10-29 21:32
Oh that's the one I was looking for. Yes.

**Closed by ry** 2019-10-29 21:32 UTC
