### ISSUE TITLE
[node:timers] after `timeout.unref()` should not fail with `Leaking async ops`

### ISSUE THREAD

**Issue by loynoir** [denoland/deno#20881] opened 2023-10-11 11:05 UTC
https://github.com/nodejs/undici/issues/2206

```ts
import { setTimeout } from 'node:timers'

Deno.test('reproduce', () => {
  const timeout = setTimeout(() => {}, 1)
  timeout.unref()
})
```

```sh
$ deno test -A --trace-ops ./reproduce.ts 
Check file:///path/to/reproduce.ts
running 1 test from ./reproduce.ts
reproduce ... FAILED (2ms)

 ERRORS 

reproduce => ./reproduce.ts:5:6
error: Leaking async ops:
  - 1 async operation to sleep for a duration was started in this test, but never completed. This is often caused by not cancelling a `setTimeout` or `setInterval` call. The operation was started here:
    at handleOpCallTracing (ext:core/01_core.js:610:42)
    at op_sleep (ext:core/01_core.js:394:21)
    at runAfterTimeout (ext:deno_web/02_timers.js:231:20)
    at initializeTimer (ext:deno_web/02_timers.js:189:3)
    at setTimeout (ext:deno_web/02_timers.js:333:10)
    at Timeout.<computed> (ext:deno_node/internal/timers.mjs:67:7)
    at new Timeout (ext:deno_node/internal/timers.mjs:54:37)
    at setTimeout (node:timers:16:10)
    at file:///path/to/reproduce.ts:6:19
    at innerWrapped (ext:cli/40_testing.js:543:11)

 FAILURES 

reproduce => ./reproduce.ts:5:6

FAILED | 0 passed | 1 failed (58ms)

error: Test failed
```

**Comment by lucacasonato** [comment] 2023-10-17 01:22
Why do you think it should not? It's a leaking test. If you create 100 of these test and don't clean them up, you are leaking memory.

**Comment by lucacasonato** [comment] 2023-10-17 01:27
I'll close this as working as intended. I can reopen if you think there is an actual Deno bug here.

**Closed by lucacasonato** 2023-10-17 01:27 UTC

**Comment by loynoir** [comment] 2023-10-17 05:32
Related to https://github.com/denoland/deno/issues/20919

https://github.com/nodejs/undici/issues/2206#issuecomment-1662104551

https://github.com/nodejs/undici/issues/2206#issuecomment-1765508201
