### ISSUE TITLE
Support npm packages with git dependencies

### ISSUE THREAD

**Issue by Gabryx64** [denoland/deno#18557] opened 2023-04-01 21:25 UTC
On Arch Linux using the Arch Communty Repository deno, after upgrading to canary (which seems to be already done for the package) it does not work when i try to import `npm:activitypub-express@4.2.2`, instead it errors with:
```
error: npm package: activitypub-express@4.2.2

Caused by:
    0: error parsing version requirement for dependency: http-signature@git+https://git@github.c
om/wmurphyrd/node-http-signature.git#9c02eeb
    1: Invalid npm version requirement. Unexpected character.
         git+https://git@github.com/wmurphyrd/node-http-signature.git
         ~
    2: Unexpected character.
         git+https://git@github.com/wmurphyrd/node-http-signature.git
         ~
```
, so I searched some issue addressing this and found #18101 that says it should work, but, at least for me, it doesn't.

**Comment by dsherret** [comment] 2023-04-01 22:48
That's a slightly different. For that issue it was when the package.json existed in the current working directory. In this case, the dependency `http-signature` of `activitypub-express` has a git dependency.

**Comment by Gabryx64** [comment] 2023-04-02 05:37
So, while this feature is still not supported, is there any way to still use the library?

**Comment by dsherret** [comment] 2023-04-02 17:30
Not at the moment because git dependencies are not supported. If they remove the git dependency and depend on npm instead then it might work:

https://github.com/immers-space/activitypub-express/blob/364d90705731dca755f3cb21747274eba0aad1e4/package.json#L35

**Comment by tmcw** [comment] 2023-05-05 13:35
We're also hitting this error. I get that github dependencies aren't supported, but the tough part is that this is an uncatchable, unrecoverable error:

```
try {
  const pl = await import("npm:@postlight/parser");
} catch (e) {
  // Never runs
  console.error(e);
}
```

Even if the `import()` is in a Worker, as it is in our system, it's not possible to recover from this issue. In the meantime, while github dependencies aren't supported, can `import()` at least always try and throw a recoverable error?

**Comment by ayame113** [comment] 2023-05-06 12:29
I ran into this issue too, but got around it by using [esm.sh](https://esm.sh/). (esm.sh supports git dependencies since v116.)

**Comment by threkk** [comment] 2023-05-07 21:40
I am experiencing the same problem, and esm.sh doesn't seem to solve it, as it returns a 500 on https://esm.sh/v119/turndown@7.1.2/deno/turndown.mjs (although this could be a temporary error).

**Comment by tmcw** [comment] 2023-08-09 15:13
Reconsidering this, I think it's a little more general: Deno throws an unrecoverable error for failed dynamic imports. I can't 100% confirm whether there's specified behavior here, but I can confirm that in Chrome, you get a TypeError for any failed dynamic import. It seems like the latter - a recoverable TypeError - is a lot better.

**Comment by dsherret** [comment] 2024-06-10 22:38
@tmcw there is now a PR for that here: https://github.com/denoland/deno/pull/24170

**Comment by und-miller** [comment] 2024-10-22 14:17
@dsherret and @lucacasonato #24170 was merged on 06/11/2024 but the issue still persists. Has it not been rolled out into a release?

**Comment by dsherret** [comment] 2024-10-22 14:20
@und-miller I can't reproduce #17802, which #24170 fixes. Can you open a new issue with a reproduction?

**Comment by und-miller** [comment] 2024-10-22 14:24
I did but it was closed. I authored #26274, which currently fails for me.

**Comment by dsherret** [comment] 2024-10-22 14:26
That's a different issue than https://github.com/denoland/deno/issues/17802

**Comment by und-miller** [comment] 2024-11-21 22:57
Would it be possible to get an update on this? Will this make it into any upcoming releases?

**Comment by dsherret** [comment] 2024-11-21 23:23
No update. It's challenging because we need to figure out the security story it and probably need to add another flag (something like `--allow-npm-git=github.com/some-org/some-repo`).

**Comment by SebastienGllmt** [comment] 2024-11-23 23:52
This is a duplicate of #18478

**Closed** 2024-11-25 02:04 UTC
Labels: suggestion, duplicate, node compat
