### ISSUE TITLE
Tinytex installation for Quarto unsuccessful because of bug in deno 

### ISSUE THREAD

**Issue by VanessaMillich** [denoland/deno#25654] opened 2024-09-16 09:10 UTC
Deno: deno 1.46.3 (stable, release, aarch64-apple-darwin)
v8 12.9.202.5-rusty
typescript 5.5.2

Command: quarto install tinytex (performed in Terminal)

Bug: 
============================================================
Deno has panicked. This is a bug in Deno. 
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.41.0
Args: ["/Applications/quarto/bin/tools/aarch64/deno", "run", "--unstable-ffi", "--no-config", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--no-check", "--v8-flags=--enable-experimental-regexp-engine,--max-old-space-size=8192,--max-heap-size=8192", "--importmap=/Applications/quarto/bin/vendor/import_map.json", "/Applications/quarto/bin/quarto.js", "install", "tinytex"]

**Comment by lucacasonato** [comment] 2024-09-16 09:37
You did not include the panic message. Please provide the full panic message (everything after the `=====`).

**Comment by VanessaMillich** [comment] 2024-09-16 09:39
quarto install tinytex

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.41.0
Args: ["/Applications/quarto/bin/tools/aarch64/deno", "run", "--unstable-ffi", "--no-config", "--allow-read", "--allow-write", "--allow-run", "--allow-env", "--allow-net", "--allow-ffi", "--no-check", "--v8-flags=--enable-experimental-regexp-engine,--max-old-space-size=8192,--max-heap-size=8192", "--importmap=/Applications/quarto/bin/vendor/import_map.json", "/Applications/quarto/bin/quarto.js", "install", "tinytex"]

thread 'main' panicked at cli/args/mod.rs:596:14:
Failed to add platform cert to root cert store: InvalidCertificate(BadEncoding)
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace

**Comment by lucacasonato** [comment] 2024-09-16 10:35
Duplicate of #24137. You can track Quarto updating their Deno build here: https://github.com/quarto-dev/quarto-cli/issues/10809

**Closed by lucacasonato** 2024-09-16 10:35 UTC
Labels: needs info
