### ISSUE TITLE
modulegraph panics on get_media_type

### ISSUE THREAD

**Issue by crowlKats** [denoland/deno#9506] opened 2021-02-14 20:30 UTC
running `deno cache https://cdn.skypack.dev/pngjs\?dts` 
will cause a panic:
```
thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/module_graph.rs:1388:40
```

**Comment by buttercubz** [comment] 2021-02-14 20:42
> running `deno cache https://cdn.skypack.dev/pngjs\?dts`
> will cause a panic:
> 
> ```
> thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', cli/module_graph.rs:1388:40
> ```

seems not to transform well 
https://cdn.skypack.dev/-/pngjs@v6.0.0-qNq9S3ewVXhQL1DwRmSg/dist=es2020,mode=imports/optimized/pngjs.js

**Comment by kitsonk** [comment] 2021-02-15 00:41
can't reproduce @crowlKats on master:

```
$ deno cache https://cdn.skypack.dev/pngjs\?dts
Download https://cdn.skypack.dev/pngjs?dts
Download https://cdn.skypack.dev/-/pngjs@v6.0.0-qNq9S3ewVXhQL1DwRmSg/dist=es2020,mode=imports/optimized/pngjs.js
Download https://cdn.skypack.dev/-/pngjs@v6.0.0-qNq9S3ewVXhQL1DwRmSg/dist=es2020,mode=types/index.d.ts
Download https://cdn.skypack.dev/error/node:string_decoder?from=pngjs
Download https://cdn.skypack.dev/error/node:zlib?from=pngjs
```

```
$ deno --version
deno 1.7.4 (debug, x86_64-apple-darwin)
v8 9.0.123
typescript 4.1.4
```

**Comment by crowlKats** [comment] 2021-02-15 00:51
just tried on latest canary and it does panic for me. i am on macos x86 as well

**Comment by kitsonk** [comment] 2021-02-15 00:59
can you do a `deno cache -L debug https://cdn.skypack.dev/pngjs\?dts`... the code you are hitting is a bit strange, as it shouldn't really be panic'ing there... after doing the debug log, try `deno cache --reload https://cdn.skypack.dev/pngjs\?dts` and see if it goes away... I think maybe your cache is in an unstable position for some reason.

**Comment by crowlKats** [comment] 2021-02-15 01:11
the reload actually did it, completely forgot to try that. tho still quite the weird thing to happen

**Comment by kitsonk** [comment] 2021-02-15 01:29
> response '404 Not Found' for https://cdn.skypack.dev/-/pngjs@v6.0.0-qNq9S3ewVXhQL1DwRmSg/dist=es2020,mode=types/index.d.ts

That was the problem, for some reason that was in the cache at some point (or a reference to it) and so it was part of the module graph, but then we couldn't find it, and when we tried to send it over to typescript to type check, we couldn't figure out what the media type was...

I am not sure if there is any easy way to fix it, because I am not sure how you got into that situation in the first place, and if you hadn't hit a panic there, you likely would have hit a panic somewhere else.  I suspect something changed on the CDN side at some point and the inconsistent state was in the cache.

**Comment by kitsonk** [comment] 2021-02-17 04:52
Closing for now until we can find something more reproducible.

**Closed by kitsonk** 2021-02-17 04:52 UTC
Labels: cli, needs info, unactionable
