### ISSUE TITLE
Links to the deno manual no longer work

### ISSUE THREAD

**Issue by sethcenterbar** [denoland/deno#5246] opened 2020-05-12 13:59 UTC
https://deno.land/std/manual.md#typescript-compiler-options

**Comment by Marcos-Costa** [comment] 2020-05-12 16:16
Any deno manual link actually is redirecting user to it's github repo right now.

**Comment by nayeemrmn** [comment] 2020-05-12 16:38
Duplicate of #5124.

**Comment by bartlomieju** [comment] 2020-05-15 16:23
Notice about new URL was added to above URL

**Closed by bartlomieju** 2020-05-15 16:23 UTC
