### ISSUE TITLE
Bug: importing `npm:openbibles` fails

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#25127] opened 2024-08-21 08:14 UTC
Reported on discord: https://discord.com/channels/684898665143206084/1275652905390575669/1275652905390575669

## Steps to reproduce

Run this script:

```ts
import bible from "npm:openbibles";
console.log(bible);
```

Output:

```sh
error: Error in openbibles@1.3.0 parsing version requirement for dependency: chapter-and-verse@https://github.com/heb12/chapter-and-verse/

Invalid npm version requirement. Unexpected character.
  https://github.com/heb12/chapter-and-verse/
  ~
    at file:///Users/marvinhagemeister/dev/test/deno-bible/main.ts:1:19
```

Version: Deno 1.46.0-rc.3+dd8a9c5

**Comment by dsherret** [comment] 2024-08-21 13:49
Caused by the centralized registry being centralized/s:

```json
  "dependencies": {
    "bible-book-num": "^1.0.0",
    "bible-translation-lookup": "git+https://github.com/MasterOfTheTiger/bible-translation-lookup.git",
    "chapter-and-verse": "https://github.com/heb12/chapter-and-verse/"
  }
```

**Comment by lucacasonato** [comment] 2024-08-22 08:06
Duplicate of #18478

**Closed by lucacasonato** 2024-08-22 08:06 UTC
Labels: bug, node compat
