### ISSUE TITLE
Deno.customInspect should be given InspectOptions

### ISSUE THREAD

**Issue by nayeemrmn** [denoland/deno#9293] opened 2021-01-27 06:56 UTC
Users can consume the options appropriately or pass them down to recursive `Deno.inspect()` calls.

**Comment by kitsonk** [comment] 2021-01-27 09:54
I had previously edited the title and the leading comment on the proposal, isn't this a duplicate of #8099?

**Closed** 2021-01-27 10:40 UTC
