### ISSUE TITLE
When using `Deno.listen()` without passing in the parameter `hostname`, it should listen to both ipv6 and ipv4 by default.

### ISSUE THREAD

**Issue by masx200** [denoland/deno#14497] opened 2022-05-05 12:51 UTC
When using `Deno.listen()` without passing in the parameter `hostname`, it should listen to both ipv6 and ipv4 by default.

I found that currently it only listens on ipv4.

Deno 1.21.1

**Comment by lucacasonato** [comment] 2022-05-05 13:02
Duplicate of #10762

**Closed by lucacasonato** 2022-05-05 13:02 UTC
