### ISSUE TITLE
`deno check .`

### ISSUE THREAD

**Issue by harrysolovay** [denoland/deno#20889] opened 2023-10-12 09:50 UTC
I often want to type-check my entire project (not just members of an entry-point-specified module graph). I created [star](https://github.com/crosshatch/star), a utility to solve this... but this adds boilerplate. I believe this feature should be possible via the Deno CLI's `check` command. Perhaps one could specify a directory instead of an entry point?

```sh
deno check .
```

**Comment by crowlKats** [comment] 2023-10-12 09:55
Duplicate of #20813

**Closed by crowlKats** 2023-10-12 09:55 UTC

**Comment by harrysolovay** [comment] 2023-10-12 10:06
Whoops, sorry!
