### ISSUE TITLE
Native HTTP server request hangs when using async request handler.

### ISSUE THREAD

**Issue by dkonasov** [denoland/deno#10545] opened 2021-05-09 17:12 UTC
I am testing new native HTTP/2 server and got a problem while trying to handle requests asynchronously, I am just can't get the response. My code:
```
const listener = Deno.listenTls({
    port: 2022,
    certFile: "./localhost.pem",
    keyFile: "./localhost-key.pem",
    alpnProtocols: ["h2", "http/1.1"],
  });
  
  for await (const conn of listener) {
    handleConn(conn);
  }
  
  async function handleConn(conn: Deno.Conn) {
    const httpConn = Deno.serveHttp(conn);
    for await (const c of httpConn) {
      handleHttpConn(c);
    }
  }

  async function handleHttpConn(conn: Deno.RequestEvent) {
    await Promise.resolve(); // pretending to do some looooong job
    conn.respondWith(new Response(`Responding to ${conn.request.url}`));
  }
```

When I am using simple non-async function everything works fine.

**Comment by nayeemrmn** [comment] 2021-05-09 17:35
Likely duplicate of #10419.

**Comment by kitsonk** [comment] 2021-05-09 20:22
Duplicate of #10419

**Closed by kitsonk** 2021-05-09 20:22 UTC
Labels: duplicate
