### ISSUE TITLE
New WS api blocking after closing connection

### ISSUE THREAD

**Issue by MarcDwyer** [denoland/deno#7457] opened 2020-09-14 00:17 UTC
```
import { delay } from "https://deno.land/std@0.65.0/async/delay.ts";

const ws = new WebSocket("wss://irc-ws.chat.twitch.tv:443");

ws.onopen = () => console.log("connection opened");

ws.onclose = () => console.log("conn closed");

await delay(5000);

ws.close();
```

Issue is when closing a WS connection something appears to be stuck in the event loop (just a guess), preventing the program from terminating. To replicate this issue, just create a ws connection and close it.

**Comment by MarcDwyer** [comment] 2020-09-14 00:18
Another user on Deno's discord seems to be having the same issue.

**Comment by crowlKats** [comment] 2020-09-14 01:31
from a bit of testing it seems it gets stuck on the eventloop; https://github.com/denoland/deno/blob/daa780e2cf2bf606f78c686ac1416786bf85d107/cli/ops/websocket.rs#L237
This behaviour seems only to happen when setTimeout or setInterval are in play.

**Comment by bartlomieju** [comment] 2020-09-15 11:41
I did some investigation and it seems the problem is in `op_ws_next_event` which never finishes. Probably need to add task tracking to it and notify the future to error out when `op_ws_close` is called.

**Comment by lucacasonato** [comment] 2020-09-15 11:42
> I did some investigation and it seems the problem is in `op_ws_next_event` which never finishes. Probably need to add task tracking to it and notify the future to error out when `op_ws_close` is called.

This was an issue with the initial PR already - did that never get fixed before landing?

**Comment by bartlomieju** [comment] 2020-09-15 11:46
> > I did some investigation and it seems the problem is in `op_ws_next_event` which never finishes. Probably need to add task tracking to it and notify the future to error out when `op_ws_close` is called.
> 
> This was an issue with the initial PR already - did that never get fixed before landing?

I does look like it CC @crowlKats @ry

**Comment by kryptish** [comment] 2020-09-16 19:54
I'm experiencing the opposite behaviour at the moment, for some reason my connection (maybe?) is closed pretty quickly after opening it, I can't figure out what's going on, no error or close events are ever triggered, but the script simply exits...

This particular ws server sends pings in a (I believe) 3 minute interval, can't see those either (while I can with the old way of implementing a ws clinet trough the std-ws module, maybe some code speaks better words than I can write...

I'm on the Deno 1.4.0

```js
import {
	connectWebSocket,
	isWebSocketCloseEvent,
	isWebSocketPingEvent,
	isWebSocketPongEvent,
} from 'https://deno.land/std@0.68.0/ws/mod.ts';


const ws = new WebSocket('wss://stream.binance.com:9443/ws');

const status = new Map([
	[0, 'CONNECTING'],
	[1, 'OPEN'],
	[2, 'CLOSING'],
	[3, 'CLOSED'],
]);

ws.onopen = function(...args) {
	console.log('ws opened', args, {
		readyState: status.get(ws.readyState),
		url: ws.url,
		extensions: ws.extensions,
		protocol: ws.protocol,
		binaryType: ws.binaryType,
		bufferedAmount: ws.bufferedAmount,
	});
	
}

ws.onmessage = function(...args) {
	console.log('ws message', args);
}

ws.onclose = function(...args) {
	console.log('ws closed', args);
	console.table(Deno.resources());
	console.table(Deno.metrics());
}

ws.onerror = function(...args) {
	console.log('ws error', args);
}

// this will keep the script running, without it, it will just exit pretty quickly
// let elapsed = 0;
// setInterval(function() {
// 	elapsed += 10000;
// 	console.log(`ws.readyState after ${elapsed/1000}s`, status.get(ws.readyState));
// }, 10000);


// the "old" (but working) way of doing a simple ws client
// this will also keep the new ws running, without it, it will exit pretty quickly
// furthermore with this implementation the ping messages visible, there is nothing
// logged with the new ws, is that supposed to be the case?
/*const wsold = await connectWebSocket('wss://stream.binance.com:9443/ws');

for await (const ev of wsold) {
	try {
		if ( typeof ev === 'string' || ev instanceof Uint8Array ) {
			console.log('wsold message', ev);
		} else if ( isWebSocketPingEvent(ev) ) {
			console.log('wsold ping', ev);
		} else if ( isWebSocketPongEvent(ev) ) {
			console.log('wsold pong', ev);
		} else if ( isWebSocketCloseEvent(ev) ) {
			console.log('wsold closed', ev);
			console.table(Deno.resources());
			console.table(Deno.metrics());
		}
	} catch (err) {
		console.log('wsold error', err);
	}
	// just to see if the new ws is still running => and yes, it will be, I assume because of the loop,
	// still no ping messages coming in
	console.log(`ws.readyState`, status.get(ws.readyState));
}*/
```

probably I am doing something wrong here... any ideas?

**Comment by MarcDwyer** [comment] 2020-09-17 00:05
> ```js
> const ws = new WebSocket('wss://stream.binance.com:9443/ws');
> 
> const status = new Map([
> 	[0, 'CONNECTING'],
> 	[1, 'OPEN'],
> 	[2, 'CLOSING'],
> 	[3, 'CLOSED'],
> ]);
> 
> ws.onopen = function(...args) {
> 	console.log('ws opened', args, {
> 		readyState: status.get(ws.readyState),
> 		url: ws.url,
> 		extensions: ws.extensions,
> 		protocol: ws.protocol,
> 		binaryType: ws.binaryType,
> 		bufferedAmount: ws.bufferedAmount,
> 	});
> 	
> }
> 
> ws.onmessage = function(...args) {
> 	console.log('ws message', args);
> }
> 
> ws.onclose = function(...args) {
> 	console.log('ws closed', args);
> 	console.table(Deno.resources());
> 	console.table(Deno.metrics());
> }
> 
> ws.onerror = function(...args) {
> 	console.log('ws error', args);
> }
> ```

It stays alive for me.

**Comment by qu4k** [comment] 2020-09-17 18:28
```typescript
const sock = new WebSocket("ws://localhost:8080");
sock.onclose = () => {
  console.log("onclose");
}

const online = await new Promise((resolve) => {
  sock.onopen = () => resolve(true);
  sock.onerror = () => resolve(false);
});

console.log("socket is online:", online);

sock.close();
```

Getting the same issue. I should note that when `online` is resolved to `false` the script exists correctly. It will hang only when the connection is actually available.

I circumvented the issue performing a `fetch` request on the host.

```typescript
  const online = await fetch("http://localhost:8080")
    .then(() => true)
    .catch(() => false);
```

This is by no means a correct solution but could work while we wait for a fix. 🔨

**Comment by kryptish** [comment] 2020-09-17 23:24
> It stays alive for me.

@MarcDwyer now that's interesting... no sudden exiting of the script without any close or error events emitted? It's also noteworthy that with other similar ws endpoints I don't have that problem (neither with this one if I subscribe to a topic and then data comes in) but those send regular messages for "heartbeat", no ping events, not sure if it even has anything to do with those... can anybody else run that script quickly, maybe I'm the only one with this issue...

**Comment by exside** [comment] 2020-09-23 13:32
Not sure if any of the issues in this discussion is related, but I'm (again) able to somehow create a panic =):

```
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: AlreadyClosed', cli/ops/websocket.rs:210:36
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

what I'm doing potentially is to call `socket.close()` after I received an "error" event in the onerror listener of the socket (because it didn't seem to close the socket)... IMHO this should probably not cause a panic =)...I mean, if the socket is already closed, ok, just do nothing, but crash the entire program is probably not too helpful, even if I'm doing something kinda "wrong"...

**Comment by timonson** [comment] 2020-11-18 12:27
Another case:

Although the `onerror` listener is executed (on connection loss), the promise won't be rejected correctly.

```typescript
async function connect(url: string): Promise<WebSocket> {
  return new Promise((resolve, reject) => {
    const socket = new WebSocket(url);
    socket.onopen = () => resolve(socket);
    socket.onerror = (err) => {
      reject(
        new BadServerDataError(
          "An error event occured on the WebSocket connection.",
          32005,
        ),
      );
    };
  });
}
```

**Comment by Soremwar** [comment] 2020-12-16 18:45
Tried the original example with several delays under latest canary, WebSocket no longer hangs.

**Comment by lucacasonato** [comment] 2020-12-16 18:51
Before closing, lets add a test to prevent regressions.

**Comment by bartlomieju** [comment] 2020-12-17 20:47
@Soremwar thanks for checking, can you add some small test case?

**Comment by Andrepuel** [comment] 2021-01-03 02:19
On the mentioned issue above I've managed to reproduce the issue using Deno 1.6.3.
The problem does not happen when I use separated processes for the server and the client.

**Comment by crowlKats** [comment] 2021-06-28 08:10
I cant reproduce this anymore, so i assume it got fixed sometime

**Comment by bartlomieju** [comment] 2021-06-28 11:39
> I cant reproduce this anymore, so i assume it got fixed sometime

Then closing as resolved :)

**Closed by bartlomieju** 2021-06-28 11:39 UTC
Labels: bug, cli
