### ISSUE TITLE
Deno panic when running modules from jsr.io via https specifiers

### ISSUE THREAD

**Issue by cotyhamilton** [denoland/deno#23697] opened 2024-05-04 22:33 UTC
Version: Deno 1.43.1

## not working 1 (jsr)

```sh
deno run -A https://jsr.io/@cotyhamilton/deno-tools/0.1.4/bump.ts --dry

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.43.1
Args: ["deno", "run", "-A", "https://jsr.io/@cotyhamilton/deno-tools/0.1.4/bump.ts", "--dry"]

thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_graph-0.74.3/src/packages.rs:217:8:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## not working 2 (jsr)
```sh
deno run -A https://jsr.io/@std/http/0.224.0/file_server.ts

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos aarch64
Version: 1.43.1
Args: ["deno", "run", "-A", "https://jsr.io/@std/http/0.224.0/file_server.ts"]

thread 'main' panicked at /Users/runner/.cargo/registry/src/index.crates.io-6f17d22bba15001f/deno_graph-0.74.3/src/packages.rs:217:8:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

## working 1 (localhost)

```sh
deno run -A http://localhost:5500/bump.ts --dry
{"oldVersion":"0.1.1","newVersion":"0.1.2"}
```

## working 2 (deno.land/x)

```sh
deno run -A https://deno.land/std/http/file_server.ts
Listening on:
- Local: http://localhost:4507
- Network: http://10.0.0.160:4507
```

**Comment by dsherret** [comment] 2024-05-06 01:30
Duplicate of https://github.com/denoland/deno/issues/23644

**Closed by dsherret** 2024-05-06 01:30 UTC
Labels: duplicate
