### ISSUE TITLE
Deno don't recognise Inline Source Map

### ISSUE THREAD

**Issue by al6x** [denoland/deno#20392] opened 2023-09-06 21:21 UTC
Deno doesn't recognise inline source map and prints error stack trace in JS build, not in CoffeeScript source.

CoffeeScript Source:

```CoffeeScript
hi = ->
  throw new Error 'nope'
  console.log 'hi'
hi()
```

JS build with inline source map as result of `coffee --compile --no-header --bare --inline-map play.cs`

```JavaScript
var hi;

hi = function() {
  throw new Error('nope');
  return console.log('hi');
};

hi();

//# sourceMappingURL=data:application/json;base64,eyJ2ZXJzaW9uIjozLCJmaWxlIjoicGxheS5qcyIsInNvdXJjZVJvb3QiOiIvIiwic291cmNlcyI6WyJwbGF5LmNzIl0sIm5hbWVzIjpbXSwibWFwcGluZ3MiOiJBQUFBLElBQUE7O0FBQUEsRUFBQSxHQUFLLFFBQUEsQ0FBQSxDQUFBO0VBQ0gsTUFBTSxJQUFJLEtBQUosQ0FBVSxNQUFWO1NBQ04sT0FBTyxDQUFDLEdBQVIsQ0FBWSxJQUFaO0FBRkc7O0FBR0wsRUFBQSxDQUFBIiwic291cmNlc0NvbnRlbnQiOlsiaGkgPSAtPlxuICB0aHJvdyBuZXcgRXJyb3IgJ25vcGUnXG4gIGNvbnNvbGUubG9nICdoaSdcbmhpKCkiXX0=
//# sourceURL=/alex/projects/js/play.cs
```

Running with deno, note the stack trace is wrong, it shows JS files, not CoffeeScript

```
> deno run play.js
error: Uncaught Error: nope
  throw new Error('nope');
        ^
    at hi (file:///alex/projects/js/play.js:4:9)
    at file:///alex/projects/js/play.js:8:1
```

**Comment by lino-levan** [comment] 2023-09-06 23:39
Seems to be a duplicate of https://github.com/denoland/deno/issues/4499

**Comment by lucacasonato** [comment] 2023-09-28 06:16
This is a duplicate of #4499

**Closed by lucacasonato** 2023-09-28 06:16 UTC
