### ISSUE TITLE
Avast Antivirus marks Deno as a threat

### ISSUE THREAD

**Issue by itsmohamed205** [denoland/deno#18922] opened 2023-04-29 19:16 UTC
I was trying to install Deno (ended up with so many errors for revocation function 'n used Chocolaty instead) 'n every time I install Deno, it works in the current working PowerShell session, but as soon as I close it 'n try to use it again, it says Deno is unrecognized.
```
deno : The term 'deno' is not recognized as the name of a cmdlet, function, script file, or operable program. Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
At line:1 char:1
+ deno
+ ~~~~
    + CategoryInfo          : ObjectNotFound: (deno:String) [], CommandNotFoundException
    + FullyQualifiedErrorId : CommandNotFoundException
```

so, I tried upgrading Deno from PowerShell session 'n Avast blocked the upgrade script as show below in the [image](https://i.imgur.com/TzmjIRN.jpg)

![screenshot from the incident](https://i.imgur.com/TzmjIRN.jpg)

> I guess also Avast has something to do with Deno being temporarily installed then suddenly uninstalled or not recognized

last thing is, whenever Deno is installed 'n I run Deno then type `deno --version`, it yields this error
```
PS C:\WINDOWS\system32> deno
Deno 1.33.1
exit using ctrl+d, ctrl+c, or close()
REPL is running with all permissions allowed.
To specify permissions, run `deno repl` with allow flags.
> deno --version
parse error: Expected ';', '}' or <eof> at 1:8
> deno repl
parse error: Expected ';', '}' or <eof> at 1:6
> deno -help
Uncaught ReferenceError: deno is not defined
    at <anonymous>:2:1
```

**Comment by foxydevloper** [comment] 2023-04-30 00:53
you're trying to run deno commands in the javascript repl, when you do `deno`, it opens a javascript repl that lets you run javascript code, `deno --version` isn't a valid javascript command. you have to exit out of the repl to run those commands

**Comment by dsherret** [comment] 2023-04-30 19:48
Duplicate of #5690

**Closed by dsherret** 2023-04-30 19:48 UTC
