### ISSUE TITLE
getting 404 on https://deno.land/x/oak

### ISSUE THREAD

**Issue by ajerni** [denoland/deno#6307] opened 2020-06-15 18:48 UTC
What happened to oak? Seems not to be available anymore?

**Comment by nayeemrmn** [comment] 2020-06-15 18:57
Duplicate of https://github.com/oakserver/oak/issues/169. Please check the correct repo.

**Comment by lucacasonato** [comment] 2020-06-15 20:46
The issue is fixed now :-)

**Comment by ry** [comment] 2020-06-15 22:46
Fixed in https://github.com/denoland/deno_website2/pull/1132

**Closed by ry** 2020-06-15 22:46 UTC
