### ISSUE TITLE
CLI imports

### ISSUE THREAD

**Issue by stephenhandley** [denoland/deno#9962] opened 2021-04-02 00:55 UTC
```
~ $ deno
Deno 1.8.2
exit using ctrl+d or close()
> import { emptyDir } from "https://deno.land/std@0.91.0/fs/mod.ts";
Uncaught SyntaxError: Cannot use import statement outside a module
```

seems like import should probably work on cli without having to do something like this (which also didn't ultimately work)
```
> let emptyDir; import("https://deno.land/std@0.91.0/fs/mod.ts").then(m => ({emtpyDir} = m))
Check https://deno.land/std@0.91.0/fs/mod.ts
Promise {
  <rejected> TypeError: TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.91.0/fs/copy.ts:96:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.91.0/fs/copy.ts:111:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, statInfo.atime, statInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.91.0/fs/copy.ts:135:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, statInfo.atime, statInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.91.0/fs/copy.ts:160:10

TS2339 [ERROR]: Property 'utime' does not exist on type 'typeof Deno'. 'Deno.utime' is an unstable API. Did you forget to run with the '--unstable' flag?
    await Deno.utime(dest, srcStatInfo.atime, srcStatInfo.mtime);
               ~~~~~
    at https://deno.land/std@0.91.0/fs/copy.ts:183:16

TS2339 [ERROR]: Property 'utimeSync' does not exist on type 'typeof Deno'. 'Deno.utimeSync' is an unstable API. Did you forget to run with the '--unstable' flag?
    Deno.utimeSync(dest, srcStatInfo.atime, srcStatInfo.mtime);
         ~~~~~~~~~
    at https://deno.land/std@0.91.0/fs/copy.ts:214:10

Found 6 errors.
}
> 
```

**Comment by crowlKats** [comment] 2021-04-02 00:59
Duplicate of #1285

**Comment by stephenhandley** [comment] 2021-04-02 00:59
Ok needed `deno --unstable` 
```
let emptyDir; import("https://deno.land/std@0.91.0/fs/mod.ts").then(m => ({emptyDir} = m))
Promise {
  Module {
    EOL: { LF: "\n", CRLF: "\r\n" },
    _createWalkEntry: [AsyncFunction: _createWalkEntry],
    _createWalkEntrySync: [Function: _createWalkEntrySync],
    copy: [AsyncFunction: copy],
    copySync: [Function: copySync],
    detect: [Function: detect],
    emptyDir: [AsyncFunction: emptyDir],
    emptyDirSync: [Function: emptyDirSync],
    ensureDir: [AsyncFunction: ensureDir],
    ensureDirSync: [Function: ensureDirSync],
    ensureFile: [AsyncFunction: ensureFile],
    ensureFileSync: [Function: ensureFileSync],
    ensureLink: [AsyncFunction: ensureLink],
    ensureLinkSync: [Function: ensureLinkSync],
    ensureSymlink: [AsyncFunction: ensureSymlink],
    ensureSymlinkSync: [Function: ensureSymlinkSync],
    exists: [AsyncFunction: exists],
    existsSync: [Function: existsSync],
    expandGlob: [AsyncGeneratorFunction: expandGlob],
    expandGlobSync: [GeneratorFunction: expandGlobSync],
    format: [Function: format],
    move: [AsyncFunction: move],
    moveSync: [Function: moveSync],
    walk: [AsyncGeneratorFunction: walk],
    walkSync: [GeneratorFunction: walkSync]
  }
}
```

**Closed** 2021-04-02 01:14 UTC
