### ISSUE TITLE
`deno compile` doesn't work twice in a row on m1 Mac

### ISSUE THREAD

**Issue by lino-levan** [denoland/deno#15713] opened 2022-08-31 22:28 UTC
Reproc:
1. Create a script and write `console.log("test")`
2. Run `deno compile test.ts` (this will work)
3. Run `deno compile test.ts` (this will fail)

Notes:
- Deleting the file it produces changes nothing
- Changing the file in any way between doing 2 and 3 causes it to succeed

Terminal log:
```
ioB:Desktop$ echo "console.log('test')" > test1.ts # Create the file
ioB:Desktop$ deno compile test1.ts # Compile the file (success)
Check file:///Users/linolevan/Desktop/test1.ts
Compile file:///Users/linolevan/Desktop/test1.ts
Emit test1
ioB:Desktop$ deno compile test1.ts # Compile the file (fail)

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: macos x86_64
Version: 1.25.0
Args: ["deno", "compile", "test1.ts"]

thread 'main' panicked at 'called `Option::unwrap()` on a `None` value', /Users/brew/Library/Caches/Homebrew/cargo_cache/registry/src/github.com-1ecc6299db9ec823/eszip-0.25.0/src/v2.rs:512:60
stack backtrace:
   0:        0x1017f4d19 - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::hf40d0caef3ef003c
   1:        0x100dca2da - core::fmt::write::h7fafa4d8eb87db06
   2:        0x1017d8988 - std::io::Write::write_fmt::he2d3473829bfad58
   3:        0x1017db0b8 - std::panicking::default_hook::{{closure}}::h2e54ef15ea4323a2
   4:        0x1017dada7 - std::panicking::default_hook::ha4f40c368619ac79
   5:        0x100d59943 - deno::setup_panic_hook::{{closure}}::he0294168cb0c0d8f
   6:        0x1017dbafb - std::panicking::rust_panic_with_hook::hd7ebe5d3a09e3b75
   7:        0x1017f50cf - std::panicking::begin_panic_handler::{{closure}}::h53bdf79c49b104e9
   8:        0x1017f5069 - std::sys_common::backtrace::__rust_end_short_backtrace::h73d9d520ad1d0732
   9:        0x1017db4e5 - _rust_begin_unwind
  10:        0x102baf9e3 - core::panicking::panic_fmt::he3416ad8dabf8a89
  11:        0x102bafaa7 - core::panicking::panic::h2675996f18b77b08
  12:        0x10157fa8c - eszip::v2::EszipV2::from_graph::visit_module::hf407b54cbb136c92
  13:        0x100d26734 - deno::compile_command::{{closure}}::h70b6120ee7456569
  14:        0x100d24c66 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h622265d96264ea8f
  15:        0x1009f4c17 - deno::main::{{closure}}::hfd220545647f9818
  16:        0x1009e7ae1 - <core::future::from_generator::GenFuture<T> as core::future::future::Future>::poll::h808b0be9b3a09bb3
  17:        0x1009e4ed8 - deno_runtime::tokio_util::run_local::h3f8035d1fbda0e5e
  18:        0x1009e4336 - deno::main::hd31f23f32394030f
  19:        0x1009e3c5c - std::sys_common::backtrace::__rust_begin_short_backtrace::h8e206b1e2808c429
  20:        0x1009e3ee6 - _main
  ```

**Comment by dsherret** [comment] 2022-08-31 23:34
Duplicate of #15672

**Closed by dsherret** 2022-08-31 23:34 UTC

**Comment by lino-levan** [comment] 2022-09-01 21:39
Thanks, excited to see this patched quickly.
