### ISSUE TITLE
deno does not support https scheme

### ISSUE THREAD

**Issue by saibing** [denoland/deno#589] opened 2018-08-24 02:35 UTC
```bash
baas@SZX1000428520:~/git/js/deno$ deno hello.ts
Downloading https://unpkg.com/deno_testing@0.0.7/testing.ts
Error: Cannot resolve module "https://unpkg.com/deno_testing@0.0.7/testing.ts" from "/home/baas/git/js/deno/hello.ts".
  os.codeFetch message: an error occurred trying to connect: invalid URL, scheme must be http
    at throwResolutionError (deno/js/compiler.ts:99:9)
    at DenoCompiler.resolveModule (deno/js/compiler.ts:362:16)
    at DenoCompiler.resolveModuleName (deno/js/compiler.ts:396:33)
    at moduleNames.map.name (deno/js/compiler.ts:552:33)
    at Array.map (<anonymous>)
    at DenoCompiler.resolveModuleNames (deno/js/compiler.ts:543:24)
    at Object.compilerHost.resolveModuleNames (deno/third_party/node_modules/typescript/lib/typescript.js:111649:117)
    at resolveModuleNamesWorker (deno/third_party/node_modules/typescript/lib/typescript.js:82561:106)
    at resolveModuleNamesReusingOldState (deno/third_party/node_modules/typescript/lib/typescript.js:82768:24)
    at processImportedModules (deno/third_party/node_modules/typescript/lib/typescript.js:84005:35)
```

**Comment by ry** [comment] 2018-08-24 02:57
duplicate of #528 - coming soon.

**Closed by ry** 2018-08-24 02:57 UTC
