### ISSUE TITLE
Optimize platform compatibility

### ISSUE THREAD

**Issue by ityspace** [denoland/deno#20232] opened 2023-08-22 07:07 UTC
I want to use Deno with Termux on an Android phone. But it's not in the package list. I hope Deno can be used on more platforms.

**Comment by romanovj** [comment] 2023-08-22 09:09
I installed deno with
`cargo install deno --locked`
Not with standart rustc, but with glibc linked (on device compiled inside termux-pacman glibc environent).
You can try

**Comment by lucacasonato** [comment] 2023-10-11 02:38
Closing as this is not a bug with Deno itself.

**Closed by lucacasonato** 2023-10-11 02:38 UTC
