### ISSUE TITLE
File specifier not handled correctly in `package.json`

### ISSUE THREAD

**Issue by renhiyama** [denoland/deno#20103] opened 2023-08-09 09:41 UTC
```
error: Parsing version constraints in the application-level package.json is more strict at the moment.

Not implemented scheme 'file'
 at <file>
```

at `dependencies` field in `package.json` add a new value:
`"preact": "file:./.reejs/deps/preact"`
and try to import it.

(Note: try a similar example. write a file locally, and try to import it like this.)

Deno fails. Node passes.

**Comment by dsherret** [comment] 2023-08-09 13:22
Duplicate of #18701

**Closed by dsherret** 2023-08-09 13:22 UTC
Labels: duplicate
