### ISSUE TITLE
Raise a signal on the current process

### ISSUE THREAD

**Issue by mk12** [denoland/deno#9093] opened 2021-01-11 17:51 UTC
A common pattern with signals like SIGHUP, SIGINT, and SIGTERM is to perform some cleanup and then invoke the default handler. For example, in C:

```c
static void signal_handler(int signum) {
    do_cleanup();
    signal(signum, SIG_DFL);
    raise(signum);
}
```

This is different from calling `exit` yourself. For one thing, `exit` is not async-signal-safe, so you'd actually need to call `_exit` or `abort`. But more importantly, the parent process (e.g. the shell) can tell from `wait` if a child was killed by a signal or exited normally. So even if you mimic the exit code:

```typescript
await Deno.signal(sig);
Deno.exit(128 + sig);
```

it will not be the same as invoking the default handler.

You can call `Deno.kill(Deno.pid, sig)`, but this requires the very broad permission `--allow-run`. It would be better if there was a `Deno.raise(sig)` function that did not require any permission.

**Comment by lucacasonato** [comment] 2021-01-13 19:00
Is there a node equivalent for this?

**Comment by lucacasonato** [comment] 2021-01-25 16:55
Duplicate of #8299.

**Closed by lucacasonato** 2021-01-25 16:55 UTC
Labels: permissions, public API, runtime, suggestion
