### ISSUE TITLE
Allow to fetch("file://")

### ISSUE THREAD

**Issue by Nemo64** [denoland/deno#8967] opened 2021-01-02 23:40 UTC
The title says it all. I'd like if `fetch` could also open local files, just like the browser can if the origin ist `file://`.

There is even a test that checks that this does not work here: https://github.com/denoland/deno/blob/e568ddf99687f635abe931c1eff2b8b37be3bc54/cli/tests/unit/fetch_test.ts#L14-L20

Allowing `file://` could profit any library or script that really just needs the contents of a file and doesn't really care where it is.... just like `deno run` in fact.

At this moment, you'd have to implement some kind of wrapper.

```js
async function readTextFile(url: URL): Promise<string> {
    if (url.protocol === 'file:' && typeof Deno.readTextFile !== 'undefined') {
        return await Deno.readTextFile(url.pathname)
    } else {
        const response = await fetch(url)
        return await response.text()
    }
}
```

There are a few things interesting points to look out for:
- Error code mapping aka: 404 = not found/file does not exist, 403 = unauthorized/--allow-read-missing/filemod
- Partial request?
- Post/Put request?

**Comment by lucacasonato** [comment] 2021-01-02 23:47
Duplicate of #2150

**Closed by lucacasonato** 2021-01-02 23:47 UTC
