### ISSUE TITLE
Allow typescript transforms via Compiler API

### ISSUE THREAD

**Issue by jimsimon** [denoland/deno#5524] opened 2020-05-17 01:34 UTC
I'm interested in writing a typescript transform that rewrites all of the Import declarations to named identifiers and outputs an import map.  The idea being that this could be the basis for a frontend dependency management tool that could handle semver resolution and deduping transitive dependencies.  As far as I can tell there's no way to pass transforms via the Compiler API.  Adding the ability to do so could potentially open up a wide range of output customizations.

Alternatively I could write a tool that does that before deno is called, but I'd prefer the above approach because aking multiple passes at the source code would be slower than making a single pass

**Comment by bartlomieju** [comment] 2020-05-17 11:11
Duplicate of https://github.com/denoland/deno/issues/3354

**Closed by bartlomieju** 2020-05-17 11:11 UTC
