### ISSUE TITLE
Can I grant/deny permissions to specific (external) modules?

### ISSUE THREAD

**Issue by nekdolan** [denoland/deno#7698] opened 2020-09-26 16:50 UTC
If not I would like to request this feature.

Given the fact that npm modules have been hacked before and that I/we will use modules from the registry it would be nice if we could reduce the threat of these modules and only give permissions to each module if necessary.

If this is possible I would suggest a new parameter like --block-external which would deny all given permissions from cached/external modules and than each permission could be extended by a list that would come after it.

I don't really know if this is feasible.
Btw good job on Deno! Its pretty cool so far.

**Comment by kitsonk** [comment] 2020-09-26 21:10
Duplicate of #171 #410 (and others)

**Closed by kitsonk** 2020-09-26 21:10 UTC
Labels: duplicate
