### ISSUE TITLE
[feature request] createImageBitmap and Image

### ISSUE THREAD

**Issue by josephrocca** [denoland/deno#19533] opened 2023-06-16 11:04 UTC
I didn't realise that Deno *still*<sup> 1</sup> doesn't have `OffscreenCanvas`, so I was setting up a system that would rely on it, and of course eventually came across a need for [`createImageBitmap`](https://developer.mozilla.org/en-US/docs/Web/API/createImageBitmap) and `Image`.

Here's the issue for OffscreenCanvas, which blocks this one:

* https://github.com/denoland/deno/issues/5701

Please feel free to close this if the above issue is a relevant-enough catch-all for this.

[1] Probably waiting for this: https://bugs.chromium.org/p/skia/issues/detail?id=12512

**Comment by backspaces** [comment] 2023-10-28 23:17
Try: https://deno.land/x/skia_canvas/mod.ts
I've used it to run browser scripts that need Image & Canvas.

**Comment by nhrones** [comment] 2023-10-28 23:24
The skia_canvas linked above, works very well.  I've written desktop GUI apps with it. The context2D is completely DOM canvas compatible.

**Comment by josephrocca** [comment] 2024-03-20 08:04
Looks like Deno has `createImageBitmap` now:

* https://github.com/denoland/deno/pull/21898

But it's currently not working. I can confirm replication of this bug:

* https://github.com/denoland/deno/issues/22649

**Comment by bartlomieju** [comment] 2024-12-06 01:49
Appears the issue is now fixed.

**Closed by bartlomieju** 2024-12-06 01:49 UTC
Labels: web, needs info
