### ISSUE TITLE
suggestion: test code blocks in `deno test --doc`

### ISSUE THREAD

**Issue by iuioiua** [denoland/deno#23669] opened 2024-05-03 02:55 UTC
Currently, `deno test --doc` type-checks code blocks in JSDoc and Markdown. It'd be cool if it could run tests on them, too. Doing so would ensure that code blocks behave as expected when copied and run. Taken a step further, this could completely omit the need for test files for simple APIs. This would kill two birds with one stone and save developers much time. I'm playing with this idea in https://github.com/denoland/deno_std/pull/4669.

**Comment by lucacasonato** [comment] 2024-06-08 14:39
Duplicate of #4716

**Closed by lucacasonato** 2024-06-08 14:39 UTC
Labels: suggestion
