### ISSUE TITLE
Installing Deno with Cargo fails on building snapshots

### ISSUE THREAD

**Issue by Siilwyn** [denoland/deno#15053] opened 2022-07-03 12:01 UTC
Runnin `cargo install deno --locked`, with rustc 1.62.0 on Fedora 36 causes the following failure:
(Set `$RUST_BACKTRACE` to `full`)
<details>
<summary>error: failed to run custom build command for 'deno_snapshots v0.1.0</summary>

```
Caused by:
  process didn't exit successfully: `/tmp/cargo-installm0nvVB/release/build/deno_snapshots-5d2af0c0924ae010/build-script-build` (exit status: 101)
  --- stdout
  Snapshot size: 2148688
  Snapshot compressed size: 548605
  Snapshot written to: /tmp/cargo-installm0nvVB/release/build/deno_snapshots-5c8bb8085c9667c4/out/CLI_SNAPSHOT.bin 
  cargo:rerun-if-changed=/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_broadcast_channel-0.53.0/lib.deno_broadcast_channel.d.ts
  cargo:rerun-if-changed=/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_websocket-0.64.0/lib.deno_websocket.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno_webgpu.d.ts
  cargo:rerun-if-changed=/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_webstorage-0.54.0/lib.deno_webstorage.d.ts
  cargo:rerun-if-changed=/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_console-0.59.0/lib.deno_console.d.ts
  cargo:rerun-if-changed=/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_url-0.59.0/lib.deno_url.d.ts
  cargo:rerun-if-changed=/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_web-0.90.0/lib.deno_web.d.ts
  cargo:rerun-if-changed=/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_net-0.51.0/lib.deno_net.d.ts
  cargo:rerun-if-changed=/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_crypto-0.73.0/lib.deno_crypto.d.ts
  cargo:rerun-if-changed=/home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_fetch-0.82.0/lib.deno_fetch.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.window.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.worker.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.shared_globals.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.ns.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.deno.unstable.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es5.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.collection.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.core.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.generator.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.iterable.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.proxy.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.reflect.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.symbol.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2015.symbol.wellknown.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2016.array.include.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2016.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.object.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.sharedmemory.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2017.typedarrays.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.asyncgenerator.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.asynciterable.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2018.regexp.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.array.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.object.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2019.symbol.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.bigint.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.date.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.number.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.sharedmemory.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2020.symbol.wellknown.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.promise.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2021.weakref.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.array.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.error.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.intl.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.object.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.es2022.string.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.esnext.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.esnext.array.d.ts
  cargo:rerun-if-changed=V:\deno/cli/dts/lib.esnext.intl.d.ts

  --- stderr
  thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Os { code: 2, kind: NotFound, message: "No such file or directory" }', /home/siilwyn/.cache/cargo/registry/src/github.com-1ecc6299db9ec823/deno_snapshots-0.1.0/build_tsc.rs:316:6
  stack backtrace:
     0:     0x55a4a3fec06d - std::backtrace_rs::backtrace::libunwind::trace::hb729d9642bb971eb
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/libunwind.rs:93:5
     1:     0x55a4a3fec06d - std::backtrace_rs::backtrace::trace_unsynchronized::h373bb774579df5c7
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/../../backtrace/src/backtrace/mod.rs:66:5
     2:     0x55a4a3fec06d - std::sys_common::backtrace::_print_fmt::hfbd4e92d240c89bb
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:66:5
     3:     0x55a4a3fec06d - <std::sys_common::backtrace::_print::DisplayBacktrace as core::fmt::Display>::fmt::h8f618991fbf64972
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:45:22
     4:     0x55a4a400fd5c - core::fmt::write::hc69b5b640d88cce8
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/fmt/mod.rs:1196:17
     5:     0x55a4a3fe5c01 - std::io::Write::write_fmt::h3403cef06a24a303
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/io/mod.rs:1654:15
     6:     0x55a4a3fed885 - std::sys_common::backtrace::_print::h368f27cdedea0e52
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:48:5
     7:     0x55a4a3fed885 - std::sys_common::backtrace::print::ha105c9cf5a64cd17
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:35:9
     8:     0x55a4a3fed885 - std::panicking::default_hook::{{closure}}::h48ed2c3707d5e20e
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:295:22
     9:     0x55a4a3fed4f9 - std::panicking::default_hook::h8744fc5cea5e3110
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:314:9
    10:     0x55a4a3fede58 - std::panicking::rust_panic_with_hook::hc82286af2030e925
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:698:17
    11:     0x55a4a3fedd07 - std::panicking::begin_panic_handler::{{closure}}::h1c15057c2f09081f
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:588:13
    12:     0x55a4a3fec524 - std::sys_common::backtrace::__rust_end_short_backtrace::h65de906a5330f8da
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/sys_common/backtrace.rs:138:18
    13:     0x55a4a3feda39 - rust_begin_unwind
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:584:5
    14:     0x55a4a12d10f3 - core::panicking::panic_fmt::h741cfbfc95bc6112
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/panicking.rs:142:14
    15:     0x55a4a12d11e3 - core::result::unwrap_failed::h995262f85f9c4e2c
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/result.rs:1785:5
    16:     0x55a4a132dbfd - core::result::Result<T,E>::unwrap::h0bf6bf4dd3ba070c
    17:     0x55a4a130d9d7 - build_script_build::build_tsc::get_js_files::h513898c86c19c27c
    18:     0x55a4a130d061 - build_script_build::build_tsc::load_js_files::h46376643c9217b07
    19:     0x55a4a130b47f - build_script_build::build_tsc::create_tsc_snapshot::h8d1d13491be3038d
    20:     0x55a4a12fc1bf - build_script_build::main::hc4683bc0394cde9a
    21:     0x55a4a1323683 - core::ops::function::FnOnce::call_once::h33861e106e61b3da
    22:     0x55a4a12ff099 - std::sys_common::backtrace::__rust_begin_short_backtrace::hf05c6eb2073cff0b
    23:     0x55a4a133c739 - std::rt::lang_start::{{closure}}::h8b1c9fe4f93cc364
    24:     0x55a4a3fe0aae - core::ops::function::impls::<impl core::ops::function::FnOnce<A> for &F>::call_once::hf833e7144973d4be
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/core/src/ops/function.rs:280:13
    25:     0x55a4a3fe0aae - std::panicking::try::do_call::h79761d203bfb6b46
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
    26:     0x55a4a3fe0aae - std::panicking::try::h0561cbbe1722251d
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
    27:     0x55a4a3fe0aae - std::panic::catch_unwind::hbca347ddd031b141
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
    28:     0x55a4a3fe0aae - std::rt::lang_start_internal::{{closure}}::h0492050ad281ec32
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:48
    29:     0x55a4a3fe0aae - std::panicking::try::do_call::h3ebce69871996bb3
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:492:40
    30:     0x55a4a3fe0aae - std::panicking::try::hbed537d20e728475
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panicking.rs:456:19
    31:     0x55a4a3fe0aae - std::panic::catch_unwind::h4185e2024c6a5d05
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/panic.rs:137:14
    32:     0x55a4a3fe0aae - std::rt::lang_start_internal::h1899cfd715ca6829
                                 at /rustc/a8314ef7d0ec7b75c336af2c9857bfaf43002bfc/library/std/src/rt.rs:128:20
    33:     0x55a4a133c721 - std::rt::lang_start::hb88813bebea56cc4
    34:     0x55a4a12fc213 - main
    35:     0x7fa404f1f550 - __libc_start_call_main
    36:     0x7fa404f1f609 - __libc_start_main_alias_1
    37:     0x55a4a12d19c5 - _start
    38:                0x0 - <unknown>
warning: build failed, waiting for other jobs to finish...
error: failed to compile `deno v1.23.2`, intermediate artifacts can be found at `/tmp/cargo-installm0nvVB`
```

</details>

**Comment by ctronp** [comment] 2022-07-03 19:32
also here in fedora 36 testing.

**Comment by littledivy** [comment] 2022-07-04 05:04
Duplicate of https://github.com/denoland/deno/issues/15030

**Closed by littledivy** 2022-07-04 05:04 UTC
