### ISSUE TITLE
Compiler Hints cause issues with bundle

### ISSUE THREAD

**Issue by mcbobby123** [denoland/deno#6852] opened 2020-07-23 03:40 UTC
This is likely related to, or the same issue as these 3: #6687 #6802 #6516

It appears that using compiler hints for types causes issues with bundle.

Take this example:

index.ts
```ts
// @deno-types="./foo.d.ts"
import * as Foo from './foo.js';

console.log(Foo.bar);
```

foo.js
```js
export const bar = 'string';
```

foo.d.ts
```ts
export as namespace Foo;
export const bar: string;
```

If I just do `deno run index.ts`  it runs without error.

If I do `deno bundle index.ts app.js && deno run app.js`, then I get this output:
```
Bundle file:///home/mcpqndq/repos/typeHintTest/index.ts
Emit "app.js" (2.51 KB)
error: Uncaught TypeError: Cannot read property 'bar' of undefined
            console.log(Foo.bar);
                            ^
    at execute (file:///home/mcpqndq/repos/typeHintTest/app.js:112:29)
    at gExp (file:///home/mcpqndq/repos/typeHintTest/app.js:90:7)
    at __instantiate (file:///home/mcpqndq/repos/typeHintTest/app.js:97:27)
    at file:///home/mcpqndq/repos/typeHintTest/app.js:117:1
```

Not going to go through it of course, but removing the hint the error goes away.

**Comment by mcbobby123** [comment] 2020-07-23 03:53
Oops it appears my issue is a direct copy of #6338

**Comment by kitsonk** [comment] 2020-07-24 21:21
Duplicate of #6338

**Closed** 2020-07-26 15:19 UTC
