### ISSUE TITLE
Intl.NumberFormat Error is Preventing a jQuery Replacement

### ISSUE THREAD

**Issue by Lonniebiz** [denoland/deno#2748] opened 2019-08-08 05:01 UTC
deno: 0.13.0
v8: 7.7.200
typescript: 3.5.1

Today, I wrote a great replacement for jQuery:

```
function $(dollarAmount)
{
	const locale = 'en-US';
	const options = { style: 'currency', currency: 'USD' };
	return Intl.NumberFormat(locale, options).format(dollarAmount);
}
$(987654.321); // This should return: '$987,654.32'
```
A you can see, it is the most sensible use of the "$" character, as a function name, that has ever been written in the history of javascript.

The only issue is, when I run this code in Deno, I get this:

```
error: Uncaught ReferenceError: Intl is not defined
► <unknown>:5:2
    at $ (<unknown>:5:2)
    at <unknown>:7:1
    at evaluate (js/repl.ts:87:34)
    at replLoop (js/repl.ts:145:13)
```

**Comment by kitsonk** [comment] 2019-08-08 05:04
Duplicate of #1968 we need to add some version of the ICU for `Intl` to be available.

**Closed** 2019-08-08 11:16 UTC
