### ISSUE TITLE
thread 'main' panicked at ext\websocket\lib.rs:723:29: called `Option::unwrap()` on a `None` value

### ISSUE THREAD

**Issue by masx200** [denoland/deno#22185] opened 2024-01-30 12:24 UTC
Version: Deno 1.40.2
============================================================
```
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: windows x86_64
Version: 1.40.2
Args: ["C:\\Users\\Administrator\\.deno\\bin\\deno.exe", "run", "--unstable", "-A", "./client.ts"]

thread 'main' panicked at ext\websocket\lib.rs:723:29:
called `Option::unwrap()` on a `None` value
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```

**Comment by masx200** [comment] 2024-01-30 12:30
https://github.com/masx200/websocket-proxy-deno-deploy/blob/5293345d125509bcbd5ee27528712d017769b14b/client.ts

**Comment by masx200** [comment] 2024-01-30 13:27
error: Uncaught (in promise) TypeError: The stream controller cannot close or enqueue.
    at ReadableStreamDefaultController.enqueue (ext:deno_web/06_streams.js:6055:13)
    at pull (ext:deno_websocket/02_websocketstream.js:255:30)
    at eventLoopTick (ext:core/01_core.js:78:9)

**Comment by Bloodiko** [comment] 2024-02-16 09:58
There needs to be a better Error message for content parsing. 

Adding to this issue, i'm trying to run Deno (Fresh) in an air gapped env with an artifact storage in between, More or less similar behaviour than a proxy, but only kinda. 

I mirrord deno.fresh and esm.sh and others into my local env, rewriting those to point to the "proxy" (which isnt a full proxy) which does work. The files are served as intended. Yet deno panicks, when something unexpected happens. 

For example if I run `deno cache https://deno.land/std@0.211.0/assert/assert_strict_equals.ts` i get this error: 

```
Download https://deno.land/std@0.211.0/assert/assert_strict_equals.ts
============================================================
Deno has panicked. This is a bug in Deno. [...]

Platform: linux x86_64
Version: 1.40.5
Args: ["deno", "cache", "https://deno.land/std@0.211.0/assert/assert_strict_equals.ts"]

thread 'main' panicked at cli/file_fetcher.rs:379:67:
called `Option::unwrap()` on a `None` value
```

But it does not elaborate on to why it was None and I dont know how to check. 
Curl does correctly retrieve the files contents. 

This is not the only file. Sometimes it hangs at std/media_types/* or a similar file.

**Comment by lucacasonato** [comment] 2024-06-18 14:43
This was fixed by https://github.com/denoland/deno/pull/21849

**Closed by lucacasonato** 2024-06-18 14:43 UTC
Labels: bug, good first issue
