### ISSUE TITLE
REPL error if return value includes orphaned surrogate pairs: "Unterminated string literal"

### ISSUE THREAD

**Issue by lionel-rowe** [denoland/deno#25626] opened 2024-09-14 03:35 UTC
Version: Deno 1.46.3

From `deno` or `deno repl` subcommand:

```ts
> console.log('💩'.split(''))
[ "�", "�" ]
> '💩'.split('')
Unterminated string literal
```

With `console.log` works fine (...ish, it should probably display as `\u....` escapes rather than replacement chars), but simply showing the return value with no log statement displays the error.

Asciicast:

[![asciicast](https://asciinema-svg.deno.dev/https://asciinema.org/a/qWOM7mBXo6TyHYi1i0QHgkAG1.svg)](https://asciinema.org/a/qWOM7mBXo6TyHYi1i0QHgkAG1)

**Comment by lucacasonato** [comment] 2024-09-16 10:40
Cross referencing this issue: https://github.com/denoland/deno/issues/12226

**Comment by lucacasonato** [comment] 2024-09-16 14:09
Duplicate of #10542.

**Closed by lucacasonato** 2024-09-16 14:09 UTC
Labels: bug, repl
