### ISSUE TITLE
'main' panicked

### ISSUE THREAD

**Issue by fangyuan-neko** [denoland/deno#24602] opened 2024-07-16 09:28 UTC
I encountered a problem while run `deno run npm:http-server`.
```
fangyuan@fedora ~/Downloads [1]> deno run npm:http-server
✅ Granted read access to <main_module>.
✅ Granted env access to "FORCE_COLOR".
✅ Granted env access to "TERM".
✅ Granted env access to "CI".
✅ Granted env access to "TEAMCITY_VERSION".
✅ Granted env access to "COLORTERM".
✅ Granted env access to "DEBUG_MIME".
✅ Granted env access.
✅ Granted sys access to "networkInterfaces".
✅ Granted net access to "0.0.0.0:8080".
✅ Granted net access to "127.0.0.1:8080".
✅ Granted net access to "127.0.0.1:8081".

============================================================
Deno has panicked. This is a bug in Deno. Please report this
at https://github.com/denoland/deno/issues/new.
If you can reliably reproduce this panic, include the
reproduction steps and re-run with the RUST_BACKTRACE=1 env
var set and include the backtrace in your report.

Platform: linux x86_64
Version: 1.44.4
Args: ["deno", "run", "npm:http-server"]

thread 'main' panicked at /home/runner/work/deno/deno/runtime/permissions/lib.rs:698:19:
called `Result::unwrap()` on an `Err` value: InvalidLabelChar
note: run with `RUST_BACKTRACE=1` environment variable to display a backtrace
```
```
fangyuan@fedora ~/Downloads [1]> RUST_BACKTRACE=1 deno run --allow-read --allow-net --allow-env --allow-sys npm:http-server
error: Uncaught Error: listen UNKNOWN: unknown error fe80::b09:9bf4:436e:ea24:8080
    at __node_internal_captureLargerStackTrace (ext:deno_node/internal/errors.ts:93:9)
    at __node_internal_uvExceptionWithHostPort (ext:deno_node/internal/errors.ts:124:10)
    at Server._setupListenHandle [as _listen2] (node:net:1180:16)
    at _listenInCluster (node:net:1012:12)
    at doListen (node:net:1022:7)
    at Array.processTicksAndRejections (ext:deno_node/_next_tick.ts:36:15)
    at eventLoopTick (ext:core/01_core.js:165:29)
```
It seems happend [before](https://github.com/denoland/deno/issues/23294) and the issue was closed but it troubles me again.

**Comment by satyarohith** [comment] 2024-07-16 10:42
Duplicate of https://github.com/denoland/deno/issues/23753

**Closed by satyarohith** 2024-07-16 10:42 UTC
Labels: bug
