### ISSUE TITLE
deno run --watch=./ stops watching after the first restart

### ISSUE THREAD

**Issue by myobie** [denoland/deno#17603] opened 2023-01-31 11:04 UTC
I've created a minimal repo to demonstrate the issue: https://github.com/shareup/deno-watch-stops-watching-bug

Deno version: 1.30.0
OS: macOS 13.2, aarch64

The first time a file outside the module graph is updated, the server restarts. The second and further times, files outside the module graph do not trigger a server restart anymore. Files in the module graph always trigger a restart.

This worked correctly, I believe, in version 1.27.x – the server would restart if any watched file changed, even if it was outside the module graph, across server restarts.

**Comment by magurotuna** [comment] 2023-01-31 11:13
Thanks for reporting! This should have been fixed by #17591.
Duplicate of #17584

**Closed by magurotuna** 2023-01-31 11:13 UTC
