### ISSUE TITLE
fetch does not support aborting with AbortController

### ISSUE THREAD

**Issue by Bzvwf16WSDKoSZd8** [denoland/deno#7019] opened 2020-08-11 11:39 UTC
```javascript
let abortController = new AbortController()
abortController.abort()
await fetch("https://www.blockchain.com/ticker", { signal: abortController.signal }).catch(console.log)
```
The web browser (Google Chrome 84.0.4147.125) will output the correct result:
 --> DOMException: The user aborted a request.

But the Deno (1.2.3) will not output anything:
-------------------------------------------
According to the Web API Standard Documentation:
https://developer.mozilla.org/en-US/docs/Web/API/AbortController
https://developer.mozilla.org/en-US/docs/Web/API/AbortSignal
[Note: When abort() is called, the fetch() promise rejects with a DOMException named AbortError.]

Because of Deno is aim to implementing Web APIs on server side, So the problem is on Deno.

I hope this bug can be fix as soon as possible, because this is the recommeded method to abort the fetch at the Web API Standard Documentation
https://developer.mozilla.org/en-US/docs/Web/API/Fetch_API
(See "Aborting a fetch")

**Comment by lucacasonato** [comment] 2020-08-11 11:46
Deno does not support aborting fetches at the minute. There is an open PR here: #6093

**Comment by ry** [comment] 2021-01-18 16:55
The new [CancelHandle](https://github.com/denoland/deno/blob/db3a1d66331c88917f59beaabf2faf0de11e3019/core/async_cancel.rs) should be useful in implemented this feature.

cc @mrkurt  @piscisaureus

**Comment by EmNudge** [comment] 2021-03-01 11:20
For some context, this has been a pretty big annoyance for me and forced me to move away from Deno for a project of mine.

Some websites will hang forever. Last I checked, either the HTTP or HTTPS version of Ikea's homepage will never resolve. It was important then to race the 2 fetches and use whichever resolved first AND was successful. If neither resolved, we can cancel both after a setTimeout has passed. 
This scenario forces me to have the ability to cancel promises. When still using Deno, I needed o use `Deno.exit()` since all the promises that were still pending did not allow the program to auto-close.

**Comment by danopia** [comment] 2021-03-01 19:51
I haven't had to move away from Deno over this, but I've definitely had to write some hacks that leak fetch ops, for example talking to cloud provider metadata endpoints: https://github.com/cloudydeno/deno-aws_api/blob/ffe2c663ea015c65692ce9be647d7702fe577248/lib/client/instance-metadata.ts#L32-L47

My test for that function needs to disable sanitization in order to pass despite the dropped op: https://github.com/cloudydeno/deno-aws_api/blob/ffe2c663ea015c65692ce9be647d7702fe577248/lib/client/instance-metadata_test.ts#L18

This issue's been open 6 months; would be nice to see some movement on it.

**Comment by lucacasonato** [comment] 2021-03-01 19:55
As mentioned previously, this issue is rather involved to implement. I will see if we can get it in for 1.9.

**Comment by mrkurt** [comment] 2021-03-01 22:50
For our purposes, we'd be ok with a global runtime setting that set timeouts on the underlying Rust requests/sockets. We don't need a lot of control, just enough to really protect the processes from leaking immortal requests.

**Comment by bartlomieju** [comment] 2021-06-05 12:45
We don't yet infrastructure for this, removing the milestone for now.

**Comment by lucacasonato** [comment] 2021-06-05 23:37
Closing as duplicate of #5471.

This should land for 1.11.

**Closed by lucacasonato** 2021-06-05 23:37 UTC
Labels: cli, feat, web
