### ISSUE TITLE
cannot execute binary file: Exec format error

### ISSUE THREAD

**Issue by BearD01001** [denoland/deno#2632] opened 2019-07-11 03:35 UTC
![image](https://user-images.githubusercontent.com/16353144/61019849-3936e480-a3ce-11e9-8332-77c7fee4fe50.png)
---
Platform: Windows10 1703
OS Version: 15063.1387
---
After search many documents & issues, I got no answer.
Is there anybody knows what happened to the installation of deno?

**Comment by ry** [comment] 2019-07-11 03:39
duplicate of https://github.com/denoland/deno_install

**Closed by ry** 2019-07-11 03:39 UTC

**Comment by BearD01001** [comment] 2019-07-11 06:35
> Yes - somehow it’s not working in mingw denoland/deno_install#68
@BearD01001 try the powershell install command
(and delete the $HOME/.deno/bin/deno file)
>
>replied from @ry at [①deno/Lobby - Gitter](https://gitter.im/denolife/Lobby)

Leave it here in case of someone needed.

**Comment by MarkTiedemann** [comment] 2019-07-11 07:55
@BearD01001 If you want to use a Unix shell rather than PowerShell on Windows, [Bash on Windows](https://blogs.windows.com/windowsdeveloper/2016/03/30/run-bash-on-ubuntu-on-windows/#KmPpsLdVepxQK8Zu.97) via the [Windows Subsystem for Linux](https://docs.microsoft.com/en-us/windows/wsl/about) works fine AFAIK.

**Comment by rafaelcastrocouto** [comment] 2020-01-31 01:49
After installing on PowerShell (and adding the PATH) it works on every terminal (cmd prompt, bash and powershell)

**Comment by AnzenKodo** [comment] 2022-06-23 20:34
![exec: Failed to execute process '/home/ramen/.config/deno/bin/deno': The file exists and is executable. Check the interpreter or linker?](https://user-images.githubusercontent.com/50282743/175392725-f7d4ee38-f1d2-45c8-86eb-77df950f157b.png)

**Platform:** NixOS
**OS Version:** 22.11pre387075.e1e08fe28bf (Raccoon)

The above output shell is from Fish Shell. But when I tried it on Bash, it doesn't even show Deno is in the path.

![bash: ./deno: No such file or directory](https://user-images.githubusercontent.com/50282743/175393734-a4e42c58-b23a-4251-af5c-a8baf4076dfe.png)

When I run Deno executable with `bash`/`sh` commands it shows `deno: deno: cannot execute binary file`

![deno: deno: cannot execute binary file](https://user-images.githubusercontent.com/50282743/175394140-ce15d07c-cfc0-4c18-8f18-800b9666c409.png)

Here is `ldd` command output:
![ldd output](https://user-images.githubusercontent.com/50282743/175394410-7b0aa594-f07f-482a-9ad7-8e6645ecbcaf.png)

**Comment by johndeighan** [comment] 2025-02-24 12:15
Maybe related:

In my `deno.jsonc` file,inside the `tasks` key, I have:

```ts
   "docs:all": "
         deno doc --html --name=@jdeighan/utils src/lib/datatypes.ts 			
      && bash cp test/*.test.civet docs
   ",
```
When I try to run the task, though, the `deno doc` command runs fine, but the attempt to copy files to the `docs` folder fails with error `/usr/bin/cp: /usr/bin/cp: cannot execute binary file`.

In my `git bash` shell, I can execute the command `cp test/*.test.civet docs` without issue.

**Comment by bartlomieju** [comment] 2025-02-24 15:04
@johndeighan the original issue is completely unrelated to the problem you are facing. Also `deno task` natively support `cp` command (https://docs.deno.com/runtime/reference/cli/task/#built-in-commands) so you can drop `bash` from your task.

**Comment by johndeighan** [comment] 2025-02-24 16:12
I was pretty sure I tried using the `cp` command without the `bash`, and when that didn't work, I added the `bash`. However, after removing the `bash` - it works now! Thanks for your help.
