### ISSUE TITLE
`imports` field in top level `package.json` not supported

### ISSUE THREAD

**Issue by marvinhagemeister** [denoland/deno#23142] opened 2024-03-30 16:36 UTC
Tried porting the astro test suite to Deno and ran into the error that we don't support resolving the `imports` field in `package.json`. Theirs looks like this:

```json
{
  "imports": {
    "#astro/*": "./dist/*.js"
  }
}
```
Made a minimal reproduction out of that. Steps to reproduce:

1. Clone https://github.com/marvinhagemeister/deno-node-imports-bug
2. Run `deno run -A main.mjs`

Error:

```sh
error: Relative import path "#foo/foo.mjs" not prefixed with / or ./ or ../
    at file:///<project>/deno-node-imports/main.mjs:1:23
```

Version: Deno 1.42.0

**Comment by dsherret** [comment] 2024-06-11 19:18
Duplicate of https://github.com/denoland/deno/issues/22772

**Closed by dsherret** 2024-06-11 19:18 UTC
Labels: duplicate, node compat, enhancement
