### ISSUE TITLE
`deno bundle` output of the serve example doesn't work

### ISSUE THREAD

**Issue by kt3k** [denoland/deno#5490] opened 2020-05-16 08:24 UTC
When I bundle the serve example in the homepage:
```ts
import { serve } from "https://deno.land/std@0.50.0/http/server.ts";
const s = serve({ port: 8000 }); 
console.log("http://localhost:8000/");
for await (const req of s) {
  req.respond({ body: "Hello World\n" }); 
}
```
with `deno bundle` command, the output script doesn't work with `deno run`. It includes the SyntaxError at for-await loop:
```
$ deno bundle serve.ts > serve.js
$ deno run serve.js 
error: Uncaught SyntaxError: Unexpected reserved word
        for await (const req of s) {
            ~~~~~
    at file:///Users/kt3k/3/deno/serve.js:5467:13
```

Strangely that for-await loop appears inside a non-async function and it seems causing the error.

**Comment by bartlomieju** [comment] 2020-05-16 09:43
Duplicate of https://github.com/denoland/deno/issues/4207

**Closed by bartlomieju** 2020-05-16 09:43 UTC
