### ISSUE TITLE
Deno LSP in VSCode different from `deno check`

### ISSUE THREAD

**Issue by charsleysa** [denoland/deno#19577] opened 2023-06-22 07:26 UTC
Hi there,

I'm getting a weird issue where VSCode says my code is fine but when I run `deno check` on the same code it complains about typings issues.

Here's a minimal reproduction:
```ts
import { S3, GetObjectCommand } from 'npm:@aws-sdk/client-s3@^3.354.0';
import { getSignedUrl } from 'npm:@aws-sdk/s3-request-presigner@^3.354.0';

const S3Instance = new S3({
    endpoint: 'http://aws-local:4566',
    region: 'ap-southeast-2',
    forcePathStyle: true
});

const command = new GetObjectCommand({
    Bucket: 'example',
    Key: '123',
    ResponseContentType: 'text/plain'
});

const downloadUrl = await getSignedUrl(S3Instance, command, { expiresIn: 60 * 60 * 2 });

console.log(downloadUrl);
```

Here's my deno version:
```
deno 1.34.3 (release, x86_64-unknown-linux-gnu)
v8 11.5.150.2
typescript 5.0.4
```

Here's the error:
```
error: TS2345 [ERROR]: Argument of type 'GetObjectCommand' is not assignable to parameter of type 'Command<GetObjectCommandInput, GetObjectCommandOutput, any, ServiceInputTypes, MetadataBearer>'.
  Types of property 'resolveMiddleware' are incompatible.
    Type '(clientStack: MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>, configuration: S3ClientResolvedConfig, options?: HttpHandlerOptions | undefined) => Handler<...>' is not assignable to type '(stack: MiddlewareStack<ServiceInputTypes, MetadataBearer>, configuration: any, options: any) => Handler<GetObjectCommandInput, GetObjectCommandOutput>'.
      Types of parameters 'clientStack' and 'stack' are incompatible.
        Type 'MiddlewareStack<ServiceInputTypes, MetadataBearer>' is not assignable to type 'MiddlewareStack<ServiceInputTypes, ServiceOutputTypes>'.
          Types of property 'concat' are incompatible.
            Type '<InputType extends ServiceInputTypes, OutputType extends MetadataBearer>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<InputType, OutputType>' is not assignable to type '<InputType extends ServiceInputTypes, OutputType extends ServiceOutputTypes>(from: MiddlewareStack<InputType, OutputType>) => MiddlewareStack<...>'.
              Types of parameters 'from' and 'from' are incompatible.
                Type 'MiddlewareStack<InputType, OutputType>' is not assignable to type 'MiddlewareStack<InputType, MetadataBearer>'.
                  Types of property 'addRelativeTo' are incompatible.
                    Type '(middleware: MiddlewareType<InputType, OutputType>, options: RelativeMiddlewareOptions) => void' is not assignable to type '(middleware: MiddlewareType<InputType, MetadataBearer>, options: RelativeMiddlewareOptions) => void'.
                      Types of parameters 'middleware' and 'middleware' are incompatible.
                        Type 'MiddlewareType<InputType, MetadataBearer>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                          Type 'InitializeMiddleware<InputType, MetadataBearer>' is not assignable to type 'MiddlewareType<InputType, OutputType>'.
                            Type 'InitializeMiddleware<InputType, MetadataBearer>' is not assignable to type 'InitializeMiddleware<InputType, OutputType>'.
                              Call signature return types 'InitializeHandler<InputType, MetadataBearer>' and 'InitializeHandler<InputType, OutputType>' are incompatible.
                                Type 'Promise<InitializeHandlerOutput<MetadataBearer>>' is not assignable to type 'Promise<InitializeHandlerOutput<OutputType>>'.
                                  Type 'InitializeHandlerOutput<MetadataBearer>' is not assignable to type 'InitializeHandlerOutput<OutputType>'.
                                    Types of property 'output' are incompatible.
                                      Type 'MetadataBearer' is not assignable to type 'OutputType'.
                                        'MetadataBearer' is assignable to the constraint of type 'OutputType', but 'OutputType' could be instantiated with a different subtype of constraint 'ServiceOutputTypes'.
const downloadUrl = await getSignedUrl(S3Instance, command, { expiresIn: 60 * 60 * 2 });
                                                   ~~~~~~~
```

**Comment by dsherret** [comment] 2023-06-22 09:24
I'm not able to reproduce. Is this all the code? Do you have a deno.json or deno.lock file?

With `deno check --check=all` I get some errors about `Buffer` not existing, but when I add `/// <reference types="npm:@types/node" />` to the top of the file then that goes away.

**Comment by charsleysa** [comment] 2023-06-22 09:43
Hi @dsherret

I've double checked and it looks like you also need a `package.json` file. The file can be pretty much empty, only `{}` is needed.

I've tested this by running `deno check ./repro.ts --reload`.

**Comment by dsherret** [comment] 2023-06-22 09:48
Thanks. I'm able to reproduce with `deno check --node-modules-dir --reload main.ts` or by adding `"nodeModulesDir": true,` to the deno.json file, which will cause it to occur in the lsp too.

**Comment by nayeemrmn** [comment] 2024-12-06 02:18
This no longer gives a type checking error for me with `"nodeModulesDir": "auto"`. Closing, comment if it's still an issue.

**Closed by nayeemrmn** 2024-12-06 02:18 UTC
Labels: bug, lsp
