### ISSUE TITLE
optional stripping of the binary generated by `deno compile`

### ISSUE THREAD

**Issue by kskarthik** [denoland/deno#15387] opened 2022-08-02 08:17 UTC
My Observation:
```sh
kar@earth:~/my/projects/guix-pkg-search$ deno compile main.js 
Check file:///home/kar/my/projects/guix-pkg-search/main.js
Compile file:///home/kar/my/projects/guix-pkg-search/main.js
Emit guix-pkg-search
kar@earth:~/my/projects/guix-pkg-search$ du -sh guix-pkg-search 
94M	guix-pkg-search
kar@earth:~/my/projects/guix-pkg-search$ strip guix-pkg-search 
kar@earth:~/my/projects/guix-pkg-search$ du -sh guix-pkg-search 
65M	guix-pkg-search
```

If possible, Please add an optional feature with `--strip` flag to `deno compile` to enable stripping of the output binary

**Comment by kitsonk** [comment] 2022-08-02 10:11
Duplicate of #9198

**Closed by kitsonk** 2022-08-02 10:11 UTC
Labels: duplicate
