### ISSUE TITLE
Better error.stack after deno bundle or deno compile

### ISSUE THREAD

**Issue by iugo** [denoland/deno#9430] opened 2021-02-07 12:46 UTC
When using `deno run webserver.ts` directly, the error stack looks like this:

```
{
    "errStack": [
        "Error: test error",
        "    at router (router.ts:11:11)",
        "    at webserver.ts:44:17"
    ]
}
```

When used `deno bundle` or `deno compile`, the error stack looks like this:

```
{
    "errStack": [
        "Error: test error",
        "    at router (file://$deno$/bundle.js:8446:15)",
        "    at file://$deno$/bundle.js:8490:21"
    ]
}
```

It would be very helpful if the stack information of the ts file can also be available after compilation.

Maybe it is related to #4499.

**Comment by kitsonk** [comment] 2021-02-07 22:25
Duplicate of #4499 plus #8577, part of #8824

**Closed by kitsonk** 2021-02-07 22:25 UTC
Labels: duplicate
