### ISSUE TITLE
Get deno fmt working on markdown code blocks

### ISSUE THREAD

**Issue by satyarohith** [denoland/deno#8879] opened 2020-12-24 14:38 UTC
Developers often use code samples in their module readmes, so it would be really nice to have `deno fmt` format the code inside markdown code blocks. This would lead to more consistent styles in presentation as well. :)

**Comment by nayeemrmn** [comment] 2020-12-24 14:59
Duplicate of #7352.

**Closed** 2020-12-24 15:00 UTC
