### ISSUE TITLE
Support json media type for importing modules

### ISSUE THREAD

**Issue by wrnrlr** [denoland/deno#10748] opened 2021-05-23 00:19 UTC
Dunno if this makes sense in a Deno context, but I've seen people do things like 

```js
import {version} from '../package.json'
```

but this fails:

```
error: An unsupported media type was attempted to be imported as a module.
  Specifier: https://raw.githubusercontent.com/wrnrlr/as-bind/master/package.json
  MediaType: Json
```

Same failure when importing local copy of same code.

**Comment by lucacasonato** [comment] 2021-05-23 01:52
Duplicate of #7623

**Closed** 2021-05-23 01:53 UTC
Labels: duplicate
