### ISSUE TITLE
race condition in test: fetchPostBodyTypedArray

### ISSUE THREAD

**Issue by ry** [denoland/deno#1219] opened 2018-11-25 22:17 UTC
Only happening occasionally - only observed on windows. 
```
test fetchPostBodyTypedArray_permW0N1E0R0
HttpUser: connection closed
    at maybeError (deno/js/errors.ts:38:12)
    at handleAsyncMsgFromRust (deno/js/dispatch.ts:27:17)
test result: FAILED. 7 passed; 1 failed; 0 ignored; 0 measured; 206 filtered out
Error: There were 1 test failures.
    at setTimeout (file:///C:/deno/js/testing/testing.ts:110:13)
    at fire (deno/js/timers.ts:131:3)
```

ex: https://ci.appveyor.com/project/deno/deno/builds/20541747

**Comment by kt3k** [comment] 2019-01-19 06:48
Note: My attempt #1535 (now reverted).

**Comment by bartlomieju** [comment] 2019-12-28 12:38
Duplicate of #1228

**Closed by bartlomieju** 2019-12-28 12:38 UTC
Labels: bug
